### ISSUE TITLE
添加redux支持后编译到转web demo报错 process is not defined

### ISSUE THREAD

**Issue by eddyzhang1986** [Tencent/wepy#1001]
## Description
  
 添加redux支持后编译到**Web版报错** process is not defined，
尝试使用 #835  解决无效

## Environment
  * wepy-cli version: [wepy-cli -v] 1.7.0、1.7.1
  * wepy-web": "1.5.10"  

  
## Reproduce
  
只要创建项目时添加redux支持,默认demo即报错

### Observed Results
  
只要创建项目时添加redux支持,默认demo即报错
  
### Expected Results
  
只要创建项目时添加redux支持,默认demo不应报错应该可以正常使用
![error](https://user-images.githubusercontent.com/6470398/36778496-d2c458bc-1ca7-11e8-9873-ce5b8869e22d.png)

**Comment by eddyzhang1986** [comment]
》》》》》

**Comment by MiGongOrg** [comment]
https://github.com/Tencent/wepy/issues/835

**Comment by eddyzhang1986** [comment]
@MiGongOrg  谢谢,已搞定，以下是我的wepy.config.js配置:
`const path = require('path');
var prod = process.env.NODE_ENV === 'production';

module.exports = {
  wpyExt: '.wpy',
  eslint: true,
  cliLogs: !prod,
  build: {
    web: {
      htmlTemplate: path.join('src', 'index.template.html'),
      htmlOutput: path.join('web', 'index.html'),
      jsOutput: path.join('web', 'index.js')
    }
  },
  resolve: {
    alias: {
      counter: path.join(__dirname, 'src/components/counter'),
      '@': path.join(__dirname, 'src')
    },
    aliasFields: ['wepy'],
    modules: ['node_modules']
  },
  compilers: {
    less: {
      compress: prod
    },
    /*sass: {
      outputStyle: 'compressed'
    },*/
    babel: {
      sourceMap: true,
      presets: ['env'],
      plugins: [
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions'
      ]
    }
  },
  plugins: {
    replace: [
      {
        filter: /\.js$/,
        config: {
          find: /process.env.NODE_ENV/g,
          replace: prod ? "'production'" : "'development'"
        }
      }
    ]
  },
  appConfig: {
    noPromiseAPI: ['createSelectorQuery']
  }
};

if (prod) {
  // 压缩sass
  // module.exports.compilers['sass'] = {outputStyle: 'compressed'}

  // 压缩js
  module.exports.plugins = {
    replace: [
      {
        filter: /\.js$/,
        config: {
          find: /process.env.NODE_ENV/g,
          replace: prod ? "'production'" : "'development'"
        }
      }
    ],
    uglifyjs: {
      filter: /\.js$/,
      config: {}
    },
    imagemin: {
      filter: /\.(jpg|png|jpeg)$/,
      config: {
        jpg: {
          quality: 80
        },
        png: {
          quality: 80
        }
      }
    }
  };
}
`
