### ISSUE TITLE
wepy 如何兼容echarts呢?

### ISSUE THREAD

**Issue by LoserMr** [Tencent/wepy#1010]
组件的方式移植了一遍 没有出来 有大神能给个模板么

**Comment by LoserMr** [comment]
https://github.com/ecomfe/echarts-for-weixin

**Comment by Gcaufy** [comment]
现在开发的一个版本将会支持这个

**Comment by BernersH** [comment]
`              <ec-canvas id="mychart-dom-line" canvas-id="mychart-line" ec="{{ ec }}" class="recycle-chart"></ec-canvas>
`
`config = {
      "usingComponents": {
        "ec-canvas": "./../../lib/ec-canvas"
      }`

这样使用就好了 那个echarts自带了components

**Comment by shangdev** [comment]
@BernersH 
这样子引入图表不能渲染出来，怎么解决的？

**Comment by duanduan2288** [comment]
在watch里面处理可以吧

**Comment by Gcaufy** [comment]
https://github.com/ecomfe/echarts-for-weixin/issues/7#issuecomment-390092922
