### ISSUE TITLE
repeat只能正确展开一层组件

### ISSUE THREAD

**Issue by rchunping** [Tencent/wepy#1012]
根据实际遇到的坑，
是不是因为没有VDOM，repeat只是翻译成原生的wx:for列表形式，碰到组件就把组件模板展开

一层组件还能勉强工作，碰到二级子组件就无法动态传值了，并且始终固定在列表第一个值

传说中的2.x版本啥时候出来啊

**Comment by coolhwm** [comment]
可以hack，再套一层repeat
```
// root.wpy
<repeat for="{{list}}" key="i" index="i" item="item">
    <parent :data.sync="item"/>
</repeat>

// parent.wpy
<repeat for="{{[data.childData]}}" key="i" index="i" item="item">
    <child :data.sync="item"/>
</repeat>
```
另外，同问2.0计划

**Comment by rchunping** [comment]
@coolhwm 感谢，管用！

之前试过在parent的computed里放过子数组，repeat展开也不行，没想到直接放[]里能识别

**Comment by rchunping** [comment]
@coolhwm 
但是碰到一个问题，child组件内的@tap事件响应就出错了，找不到binddata

**Comment by Gcaufy** [comment]
1.7.2的版本中支持了原生组件，大家可以试一下这个版本，应该能解决repeat下的一些问题：

安装使用：
```
npm install wepy-cli@1.7.2-alpha1 -g
npm install wepy@1.7.2-alpha1 --save
wepy build --no-cache
```
文档说明：https://github.com/Tencent/wepy/blob/component/docs/md/doc.md#%E7%BB%84%E4%BB%B6
迁移参考：https://github.com/wepyjs/wepy-wechat-demo/commit/5f84a3aed82547d7db4eb816f5c83f5ad35eba65

**Comment by byk04712** [comment]
同问
index.wpy 
`
<template>
	<repeat for="{{list}}">
		<ticket :ticket.sync="item" />
	</repeat>
</template>
<script>

export default class CashCoupon extends wepy.page {
      data = {
          list: [{imgurl:'图片1url'}, {imgurl:'图片2url'}, {imgurl:'图片3url'}, {imgurl:'图片4url'}]
      }
}
</script>
`

ticket.wpy  组件
`
<template>
    <view>
        <view class="zan-card__thumb">
            <image class="zan-card__img" src="{{img}}" mode="aspectFit" />
        </view>
    </view>
</template>
<script>
//...
export default class Ticket extends wepy.component {
	props = {
		ticket: {
			type: Object,
			default: {}
		}
	};
	computed = {
	   img() {
              // 这里每次只返回图片1url 的值
   	      return ticket.imgurl;
 	   }
	}
</script>
`

**Comment by jcto** [comment]
@byk04712  你这没有两层组件，只有一层应该是没问题的 `<repeat for="{{list}}" key="i" index="i" item="item">` 少了item赋值
