### ISSUE TITLE
[大BUG]Component中定义unLoad无效

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#1013]
重现方法很简单，定义一个wepy.component和一个wepy.page，将组件放到page中，分别在它们的onLoad和onUnload中console.log打印调试信息即可

page的onLoad/onUnload都会打印出信息而component只有onLoad的信息

不知道这个行为是by design的还是个bug，无论如何这种不对称性都不应该出现在框架中

**Comment by cuijiemmx** [comment]
看了下代码，page的onLoad会依次调用其中嵌入的component的onLoad，而page的onUnload在wepy中没有实现 - -
@Gcaufy 。。。

**Comment by Gcaufy** [comment]
组件的静态编译进page的，只有onLoad， 不存在unLoad的情况。
