### ISSUE TITLE
1.7.0新版本的组件渲染结果和1.6.0 不一样

### ISSUE THREAD

**Issue by maocanmao** [Tencent/wepy#1015]
## Description

 之前在1.6.0的版本上开发，有个自定义的小组件，在1.7.0版本下渲染出来的不正常。UI都没有了
 

## Environment

  * Wechat version:1.9.1
  * wepy-cli version: 1.7.0
  * wepy version: 1.7.0
  
## Reproduce
组件代码
`<style` lang="less">
.timeLine-item-container {
  display: flex;
  flex-direction: column;
  justify-content: center space-around;
}

.timeline-item-circle {
  align-self: center;
  margin-top: 10rpx;
}
.timeline-item-text {
  font-size: 11pt;
  margin: 0 auto;
}
</style>'

`<template>
  <view class="timeLine-item-container" @tap="tap({{date}},{{status}})">
    <text class="timeline-item-text">{{title}}</text>
    <icon class="timeline-item-circle" type="{{status}}" size="25"></icon>
  </view>
</template>`

'<script>
import wepy from "wepy";

export default class TimeLineItem extends wepy.component {
  components = {};

  data = {};
  methods = {
    tap(date, status) {
      console.log("child is clicked");
      this.$emit("timeLine", date, status);
    }
  };

  events = {};
  // Other propertie
  props = {
    title: String,
    status: String,
    date: String
  };
}
</script>
`

`<view class="timeLine-container" wx:if="{{weekDataLoaded}}">
      <repeat for="{{indexWeekData}}" item="item">
        <timeLineItem title="item.title" status="item.status" date="item.date" @timeLine.user="reCheckIn"></timeLineItem>
      </repeat>
    </view>`

  [1.7.0表现]
  
  [Observed Results]
![1 7](https://user-images.githubusercontent.com/5929428/36880169-3661bb7a-1e02-11e8-86f8-aecbce0a3710.png)

### Expected Results

  [1.6.0表现]
  
![1 6](https://user-images.githubusercontent.com/5929428/36836863-82cc80b8-1d75-11e8-929c-8d6ea41893da.png)

**Comment by Gcaufy** [comment]
是不是用了scoped?

要看看是什么原因样式 没了。

**Comment by maocanmao** [comment]
我代码是没有任何改动的。只是换回了1.6.0版本就正常了。。

**Comment by Gcaufy** [comment]
建议对比一下两个版本生成的代码 有什么区别。
从简单的表现来看暂时看不出问题。
