### ISSUE TITLE
加入了Component的onUnload实现

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#1016]
@Gcaufy 表示组件是静态编译入页面，不存在onUnload，我认为如果这样解释对于组件也不应该存在onLoad

wepy组件onLoad机制和page不一样，不是天生的，而是由wepy框架加入，由Page在onLoad时调用的，

因此对于框架，Page在onUnload时也应该依次调用内部组件的onUnload，这个道理和onLoad完全一致

附上PR，实现了这个需求

**Comment by Gcaufy** [comment]
那组件使用wx:if 切换状态时是不是也应该调用 unload 呢？
但现实是做不到的。。。

**Comment by cuijiemmx** [comment]
@Gcaufy 先别急着关，仔细看看再说哈

**Comment by cuijiemmx** [comment]
@Gcaufy @组件的onLoad/onUnload和页面的onLoad/onUnload是关联的，始终是由页面的onLoad/onUnload发起的

**Comment by Gcaufy** [comment]
我正在处理的一个功能会解决这个问题，所以wepy组件的一些功能先放下不管吧。

**Comment by cuijiemmx** [comment]
@Gcaufy 关于wx:if切换装态的解释也是一致的，wx:if在切换状态时并没有调用onLoad，所以也不应该调用onUnload

当前组件的onLoad都是在页面onLoad的时候调的
那组件的onUnload也都是在页面onUnload的时候调用

逻辑很清晰

**Comment by cuijiemmx** [comment]
现在我遇到的问题是在封装一个智能组件时（带一定页务逻辑，不仅仅是渲染页面），使用wepy-redux的@connect这个组件到redux store，onLoad时会自动subscribe state change（这个过程由wepy-redux实现），同时wepy-redux会往组件中注入onUnload用于自动unsubscribe，但由于页面不会调用组件的onUnload，导致unsubscribe无法完成 - -||

**Comment by ystarlongzi** [comment]
> 组件的onLoad/onUnload和页面的onLoad/onUnload是关联的，始终是由页面的onLoad/onUnload发起的

感觉组件的 `onUnload` 实现只考虑这种情况，也能接受

**Comment by Gcaufy** [comment]
其实我并不赞成组件实现 onUnload 功能。
因为wepy组件是静态组件，不存在unload的情况。
如果给组件添加了unload事件后，会让人以为在使用wx:if 等功能时也是会触发组件 的unload功能的。

**Comment by cuijiemmx** [comment]
@Gcaufy 这事前因后果是这样，我封装的智能组件需要有个lifecycle的callback能自我释放资源，看了一圈貌似只有onUnload能拿来用，碰巧又能解决@connect的组件的unsubscribe问题，所以就这么整了，另外由于组件的onLoad过程依赖父组件（页面）提供context，所以调整了onLoad顺序

至于wx:if的误解其实对于组件onLoad也是存在的（wx:if时是否会触发组件的onLoad？），组件onLoad又不能不提供，不然没法封装智能组件，所以我倒不纠结wx:if带来的误解问题，毕竟得解决问题先

归根到底，我觉得wepy得好好考虑完善下lifecycle的callback

BTW，mpVue开源了

**Comment by ystarlongzi** [comment]
>至于wx:if的误解其实对于组件onLoad也是存在的（wx:if时是否会触发组件的onLoad？）
> .....
>  我倒不纠结wx:if带来的误解问题，毕竟得解决问题先

个人比较赞成这种做法，根据目前经验来说，感觉组件应该会更关心当页面 `onUnload` 时，尽量也把组件也 `onUnload` 下，这样就好处理一些业务逻辑
