### ISSUE TITLE
为 onPageScroll 添加 throttle

### ISSUE THREAD

**Issue by ystarlongzi** [Tencent/wepy#1022]
如题，建议对下面`onPageScroll` 的监听添加个 throttle，或移除对 `onPageScroll` 的监听，有开发者在内部调用 `this.$apply()` 触发数据脏检测

https://github.com/Tencent/wepy/blob/934f41fefaddb3b0c15f6aacef2c16a1149ec4a8/packages/wepy/src/base.js#L188-L207

**Comment by cuijiemmx** [comment]
这个问题我已经修复了，貌似已经合并进wepy 1.7.1了，你升下级就行了

**Comment by ystarlongzi** [comment]
@cuijiemmx @Gcaufy 
`onUnload` 是不是也可以不用触发 `$apply()`？

**Comment by cuijiemmx** [comment]
@ystarlongzi 我的一个未合并PR里onUnload是去掉了$apply()的
