### ISSUE TITLE
在page 页面，输出console.log(this) 真机报错

### ISSUE THREAD

**Issue by bulolo** [Tencent/wepy#1024]
报错条件：

1.在page 页面，onLoad()  输出console.log(this) 
2.这个页面不作为第一个启动页面

还原：共2个页面，一个主页（A）里面有一个按钮，按钮点了出来另外一个页面（B）
在页面B onLoad() 输出console.log(this)
微信调试工具不会报错。当真机调试时候，用二维码扫描进入到B页面就报错。

这个不知道是不是小程序自身问题。

![image](https://user-images.githubusercontent.com/10026498/36930886-d5abdb3c-1ee5-11e8-867a-6e24f2d159db.png)

**Comment by cuijiemmx** [comment]
@bulolo @Gcaufy 单页面的onLoad里加入console.log(this)也会报这个错...很容易重现
我昨天也遇到这个问题了，没发现原因- -，rollback了一下代码... @bulolo 感谢.

**Comment by Gcaufy** [comment]
在console.log时会进行json序列化，而this刚好是个循环引用的object，会导致序列化报错。
