### ISSUE TITLE
[BUG]setInterval报错

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#1027]
setInterval(() => {}, 0)

真机控制台报错（模拟器正常）：thirdScriptError ... setInterval time can not be Zero

按照标准，setInterval的间隔可以设为0，实际效果是按最小间隔触发，一般是10ms

这个和上一个console.log(this)的BUG，可能都不是wepy的bug吧，如果是这样麻烦腾讯哥向相关人员反映一下

**Comment by Gcaufy** [comment]
这里： https://developers.weixin.qq.com/
