### ISSUE TITLE
自定义的组件，import不了？

### ISSUE THREAD

**Issue by wuchuguang** [Tencent/wepy#1030]
## Description

  [问题描述：自定义src/components/Topnavs.wpy组件
  在wepy.page的组件：src/index.wpy
  import topnavs from './components/Topnavs.wpy‘;
  components = {
       topnavs:topnavs
  }
 <template>
     <page>
         <topnavs></topnavs>
     </page>
 </template>
  
wepy build --watch
报错：
   [01:13:49] [写入] JS  : dist\components\Topnavs.js
   [Error] 找不到组件：C:\phpstorm\wepy-csjx\src\components\Topnavs.wpy
   请尝试使用 npm install C:\phpstorm\wepy-csjx\src\components\Topnavs.wpy 安装

## Environment

  * wepy-cli version: 1.7.1
  * wepy version:1.7.1
  
期望正常使用这个Topnavs.wpy组件。

**Comment by Gcaufy** [comment]
建议看看demo中的组件是怎么引入的

**Comment by Slngle** [comment]
这个楼主解决了不 我也遇到这个问题

**Comment by Slngle** [comment]
@wuchuguang

**Comment by chengpan168** [comment]
`
import wepy from 'wepy'
import LoadMore from '../components/loadMore'
import logger from '../mixins/logger'
`

不要带后缀，正常引入了,  可以试试
@Slngle @wuchuguang
