### ISSUE TITLE
编写组件时遇到的样式缓存问题【微信开发者工具】

### ISSUE THREAD

**Issue by shengbeiniao** [Tencent/wepy#1031]
wepy已经成功编译组件，但在微信开发者预览时还是旧的样式

重新执行wepy build --watch后，样式刷新

添加--no-cache参数也无效

PS:具有偶发性

**Comment by shengbeiniao** [comment]
环境,mac
v1.7

**Comment by Gcaufy** [comment]
是否有删除过dist目录。如果删除过需要重启开发者工具。
其它情况下，使用开发者工具的清缓存就够了。

**Comment by shengbeiniao** [comment]
重启可以解决问题，但重启后再次变更清缓存无效，已测试

**Comment by shengbeiniao** [comment]
查看了每次生成的dist文件，组件变更过的内容并未写入page页

**Comment by q215171650** [comment]
我也遇到类似的情况了，我去查看dist文件中的wxml已经生成了变动内容，但微信开发者工具的预览还是没变化。我改page的文件内容是可以实时监听到文件变动的，改components的文件内容就出现这种问题了，而且还有一点奇怪的，我改components中的script或者style，是可以监听到内容变化的，唯独改动template中的内容，实时预览不到。

**Comment by l987974** [comment]
两个组件 一个正常 另一个 dist里面没有了 不见了 怎么回事

**Comment by heeroluo** [comment]
遇到同样的情况，页面引用的其中一个组件正常，另一个组件有问题。
