### ISSUE TITLE
input/textarea 输入光标问题

### ISSUE THREAD

**Issue by callmesoul** [Tencent/wepy#1036]
input/textarea 在字段中间修改值后，ios光标自动跳到最后，安卓不会。
官方解释是因为调用了this.setData(),重新渲染模板导致。
解决方法是只赋值不渲染。
this.xxx=e.datail.value;
但在wepy好像都用了双向绑定，都是重新渲染模板，怎么解？

**Comment by jimmyrogue** [comment]
用两个值来存储。

**Comment by callmesoul** [comment]
input 和textarea组件较多，全部改成用两个值来存储工作量有点大，有更好的解决方法？

**Comment by Gcaufy** [comment]
@callmesoul  
在使用 this.xxx = e.detail.value; 后， 后会执行setData。
所以需要自己考虑这里的问题。。。

另外，如果不想触发setData， 可以通过 这个方法规避过去；
```
    this.xxx = e.detail.value;
    this.$data.xxx = this.xxx;  // 将备份值改为一样，这样就不会当成脏数据了
```
