### ISSUE TITLE
wepy 删除pages页面时候，dist打包项还是存在以前的页面。

### ISSUE THREAD

**Issue by Niofh** [Tencent/wepy#1039]
![image](https://user-images.githubusercontent.com/15324717/36958446-d99e45f8-2076-11e8-92ed-959f4b4af7b5.png)

**Comment by rchunping** [comment]
手动删除dist/下除  project.config.json 之外的所有文件和目录 , 再build

mac上也可以 wepy clean 做这些事情

**Comment by Gcaufy** [comment]
npm run clean
