### ISSUE TITLE
store-actions 中reject执行是否有问题?

### ISSUE THREAD

**Issue by wanwusangzhi1992** [Tencent/wepy#1040]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  demo中, counter的actions发起后, 触发resove跟reject都会导致state改变, 
export const asyncInc = createAction(ASYNC_INCREMENT, () => {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			console.log('--12-');
			reject(1); // 这里无论写resolve,还是reject,执行结果都是resolve的结果 
		}, 1000);
	});
});

个人觉得, resolve就正常修改state, reject 应该是返回异常给用户自行处理.

## Environment

  * Platform: [Web 1.02.18]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v 7]
  * wepy version: [1.6]
  * other version: [如果是插件问题，请列出问题插件的版本号]

**Comment by rchunping** [comment]
为啥不是 reject一个Error，然后那边正常的action里面对 .payload里做判断 ？

**Comment by rchunping** [comment]
看 https://github.com/redux-utilities/redux-promise#usage

If it receives an Flux Standard Action whose payload is a promise, it will either

dispatch a copy of the action with the resolved value of the promise, and set status to success.
dispatch a copy of the action with the rejected value of the promise, and set status to error.

**Comment by wanwusangzhi1992** [comment]
@rchunping  正常是reject一个error, 但既然执行了reject, 那么框架可以统一封装与处理了, 就不触发修改reducers, 然后把reject直接返回给用户自己处理不是更好? 
还要在action.payload判断 ,没有必要性意义吧? 
reducers只处理resolve的数据不就更好了. 判断直接在action里写. 不需要在reducers的纯函数里作多余的判断吧.
