### ISSUE TITLE
wepy.component重大的bug

### ISSUE THREAD

**Issue by wanwusangzhi1992** [Tencent/wepy#1043]
组件代码

export default class ListItem extends wepy.component {
    props = {
      productItem: {
       
      }
    }
    data = {
    }
    computed = {
      productItem() {
        console.log(this.productItem) // 这样能得到对象的值
        console.log(this.productItem.create_time) // 这样却以下错误. 
        return 'this.productItem.images.image[0]'
      }
    }
   onLoad() {
        console.log(this.productItem) // 这个值一定要有默认值 , 否则repeat传入item为空.
   }
  }

报错如下:
Cannot read property 'create_time' of undefined;at tabbar/product page lifeCycleMethod onLoad function
TypeError: Cannot read property 'parent_id' of undefined
以述为问题一, 以下为问题二 即onLoad提出的, 如果父组件 没有默认值,该productItem为空或undefined

**Comment by coolhwm** [comment]
1）repeat组件的onLoad只会调用一次，所以基本没什么用
2）onLoad调用时机为组件创建的时候，如果是异步数据动态传值（`:productItem.sync=`），那么肯定是获取不到的，静态传值可以获取到
3）repeat组件尽量也不要用computed，所有组件会同共享一个productItem

**Comment by bigsomg** [comment]
请问原生组件怎样用啊？有没有详细一点的介绍呢？
