### ISSUE TITLE
请问开启错误监控是什么意思

### ISSUE THREAD

**Issue by zjfjiayou** [Tencent/wepy#1044]
运行npm run dev在微信开发者程序里面预览中,console第一句话就报错“ WePY开启错误监控”，请问有遇到同样问题的童鞋吗？

**Comment by zarkin404** [comment]
遇到过，效果如下：

![](https://s1.ax1x.com/2018/03/06/9cgXSP.png)

原因可能是因为这个：

![](https://s1.ax1x.com/2018/03/06/9cgjQf.png)

[[Changelog]](https://tencent.github.io/wepy/document.html#/changelog)

**Comment by zjfjiayou** [comment]
@zarkin404 是你这样的，只有一个提示，然后并没有错误信息，要怎么去掉，或者说没有什么影响吧

**Comment by zarkin404** [comment]
@zjfjiayou 完全没影响的

**Comment by rchunping** [comment]
反正你最后 npm build 生成发布版的时候这个_wepylogs.js文件会去掉的

**Comment by Gcaufy** [comment]
这个功能是1.7.0 加入了。。通过config中的 `cliLogs`控制。
因为有时候，cmd中编译报错，这时候不会编译生成新代码，在开发者工具调试时不知道是怎么回事，一定要切回cmd才能看到错误，因此加入这个功能，把cmd的报错显示到开发者工具当中。
