### ISSUE TITLE
如何编译 node_modules 中的 es6 模块？

### ISSUE THREAD

**Issue by Samlv9** [Tencent/wepy#1045]
我有一个模块是用 es6 写的并且发布到了 npm 上。
**es6-module**
```
export default function add( v1, v2 ) {
    return v1 + v2;
}
```

**业务代码**
```
import add from "es6-module";

console.log(add);
```

这段代码用 wepy-cli 根本无法编译过去，但是如果是 webpack 或者 babel 的话：
**webpack.config.js**
```
modules.exports = {
      ...
      "rules": [
             { "test": /\.js$/, "excludes": /node_modules\/(?!es6\-modules)/, "loader": "babel-loader" }
      ]

}
```

有没有类似 webpack excludes 或者 babel excludes 之类的配置？

**Comment by Samlv9** [comment]
>同时WePY也是一款 **成长中** 的框架，大量吸收借鉴了一些优化前端工具以及框架的设计理念和思想。如果WePY有不足地方，或者你有更好的想法，欢迎提交ISSUE或者PR。

咳，这框架估计是长不大了（底层写的真的很不靠谱！！！）。
花了我 2 天时间才发现要想编译 `node_modules` 下的  ES6 的话，就得去修改 `wepy-cli` 下的源码（我的是 `wepy-cli@1.6.0` 版本)。

```js
/// compile-script.js
if (needCopy) {
    if (!_cache2.default.checkBuildCache(source)) {
        _cache2.default.setBuildCache(source);
        _util2.default.log('依赖: ' + _path2.default.relative(process.cwd(), target), '拷贝');
        var newOpath = _path2.default.parse(source);
        newOpath.npm = npmInfo;

        /// 这里直接写死了 `lang="js"`，也就是说直接拷贝出去，根本就不走 `babel` 编译。
        _this.compile('js', null, 'npm', newOpath);
    }
}
```

另外 `resolve.alias` 就是摆设：
```js
/// wepy.config.js
/// browser.js 是 es6-module 编译成 es5 的版本。
modules.exports = {
  "resolve": {
    "alias": {
      "es6-module$": path.resolve("./node_modules/es6-module/dist/browser.js")
    }
  }
}
```
这样是不会拷贝到 `dist/npm` 下的，因为这是一个绝对路径，`needCopy`  是 false：
```js
/// compile-script.js
lib = _resolve2.default.resolveAlias(lib);
if (_path2.default.isAbsolute(lib)) {
    source = lib;
    target = _util2.default.getDistPath(source);
}
```
只能是通过修改 `es6-module` 的 pageage.json，让 `resolve.js#getMainFile()` 方法能找到：
```
/// package.json
{
     "main": "es6-module.js",
     "browser": "./dist/browser.js"
}
```

**总结：作者自己用 nodejs 写了一套蹩脚的文件引用解析机制（其实就是一个递归搜索的问题），但是没有考虑 *别名(alias)*，*忽略(babelrc#ignore, wepack-config#excludes)*，*模块解析/加载机制(webpack-loader)*，*内置模块补丁( 虽然有个 `npmHack`，但是跟没有没啥区别)*  等等一些常用的功能。**

**为什么 `require()` 不能交给 `webpack` 呢？像 `vue` 一样写一个 `wepy-loader` 不就可以了么？**

所以吧～与其去踩这种坑。还不如直接用  webpack 搞一个来的直接。你想想你引用一个 "axios"，他告诉你找不到 `http` 模块是一种怎样的痛。 PS: 我 axios 的 adapter 都写好了:(

**Comment by dlhandsome** [comment]
- 2.0底层正在大换血
- 不好用，提pr就是了，吐这些槽并不能改变什么

**Comment by Gcaufy** [comment]
目前是不支持 es6 module 的 npm 包，这个功能 建议使用`aliasFields` 去实现，这个是测试过的：
https://github.com/Tencent/wepy/pull/595

整套方案写得比较仓促，很多东西都是修修补补上去的，所以底层写得比较凌乱。而且功能也是参考了 webpack 的一些功能去实现的，但可能有些地方考虑得不全面，这几点虚心接受。
另外，建议不要尝试去做一些没有人做过，或者文档上没有的事情，不能完全像用webpack一样去用wepy。毕竟 webpack 有一个强大的团队在维护。而wepy只是我工作之外的一个开源项目。

虚心接受意见，同时也希望如果有能力或者有好的想法，可以做出有意义的贡献。

**Comment by Samlv9** [comment]
@Gcaufy 多谢建议～目前找到一种比较曲折的方法来解决 `wepy` 引入 ES6 文件的问题。

### 要求：`^wepy@1.7.1` ###
假设 `es6-module` 这个库是使用 `es6` 实现的：

- 1，先安装这个库 `npm i es6-module --save`。
- 2，然后将 `./node_modules/es6-module/` 拷贝到 `./src/packages/es6-module/`（这个可以通过 `postinstall ` 脚本完成）。
>注意：不要拷贝其他的 JS 代码，仅拷贝源码部分进来！
- 3，在 `package.json` 上添加 `wepy` 字段（也可以用 `postinstall` 脚本来处理)：
```js
{
  "name": "awesome-wepy-project",
  "version": "1.0.0",
  // `^wepy@1.7.1` 版本开始支持 `aliasFields ` 字段。
  "wepy": {
    // 这里的 `{main.js}` 对应 `es6-module` 的 `package.json` 上的 `main` 字段。
    "es6-module$": "./src/packages/es6-module/{main.js}"
  }
}
```
然后在其他的业务代码中就可以直接使用 `es6` 的库了，就像这个库在 `node_modules` 里面一样：
```
/// 业务代码
import ES6Module from "es6-module";

console.log(ES6Module);
```

**Comment by Choicelin** [comment]
@Gcaufy，您好，这个不是腾讯官方的开源项目吗？

**Comment by jimmyrogue** [comment]
@Choicelin 之前一直是 @Gcaufy 一个人在维护的，之前还是个人项目，去年才被收到腾讯下面，而且现在大部分时间也是他一个人在升级维护

**Comment by mdsb100** [comment]
@Samlv9 你的方案有例子参考一下吗

**Comment by huadong** [comment]
> @Choicelin 之前一直是 @Gcaufy 一个人在维护的，之前还是个人项目，去年才被收到腾讯下面，而且现在大部分时间也是他一个人在升级维护

看完这个评论心里凉了半截！不知道现在腾讯是否有投入官方研发力量，一直把它当“官方”维护项目原因选用。

**Comment by Samlv9** [comment]
@mdsb100 好久没用 wepy 了，你参考这个应该是可以实现的。我现在是用自己开发的一套插件编译小程序：

https://github.com/guless/mpx-webpack-plugin

> @Gcaufy 多谢建议～目前找到一种比较曲折的方法来解决 `wepy` 引入 ES6 文件的问题。
> 
> ### 要求：`^wepy@1.7.1`
> 假设 `es6-module` 这个库是使用 `es6` 实现的：
> 
> * 1，先安装这个库 `npm i es6-module --save`。
> * 2，然后将 `./node_modules/es6-module/` 拷贝到 `./src/packages/es6-module/`（这个可以通过 `postinstall` 脚本完成）。
> 
> > 注意：不要拷贝其他的 JS 代码，仅拷贝源码部分进来！
> 
> * 3，在 `package.json` 上添加 `wepy` 字段（也可以用 `postinstall` 脚本来处理)：
> 
> ```js
> {
>   "name": "awesome-wepy-project",
>   "version": "1.0.0",
>   // `^wepy@1.7.1` 版本开始支持 `aliasFields ` 字段。
>   "wepy": {
>     // 这里的 `{main.js}` 对应 `es6-module` 的 `package.json` 上的 `main` 字段。
>     "es6-module$": "./src/packages/es6-module/{main.js}"
>   }
> }
> ```
> 
> 然后在其他的业务代码中就可以直接使用 `es6` 的库了，就像这个库在 `node_modules` 里面一样：
> 
> ```
> /// 业务代码
> import ES6Module from "es6-module";
> 
> console.log(ES6Module);
> ```
