### ISSUE TITLE
wepy有没有国际化的资源？

### ISSUE THREAD

**Issue by jiangdianen** [Tencent/wepy#1050]
## Description

  [问题描述]：目前官方文档没看见有国际化相关的资源

  [期望表现]：有相关的国际化方案或者资源

**Comment by rchunping** [comment]
直接做多个不同语言的小程序应该是更快的方案吧

**Comment by jiangdianen** [comment]
并不觉得啊，如果这样，有5个语言还得维护5个项目？ @rchunping

**Comment by sunkehappy** [comment]
官方人员能回答下吗？或者有没有替代方案？

**Comment by mny459** [comment]
@Flavour86 @sunkehappy 两位小哥方便说一下后面是怎么解决的吗？

**Comment by sunkehappy** [comment]
@mny459 我是用的[i18next](https://github.com/i18next/i18next)，在app.wpy的onLaunch方法中初始化，然后保存到wx中，然后别的页面就调用wx.i18next.t('xxx')来获取对应的文本就可以了。
