### ISSUE TITLE
我将data里面的数组通过filter方法（copy）了一份数据，改变这个新的数组，会引起页面渲染。为什么？

### ISSUE THREAD

**Issue by wuweijia** [Tencent/wepy#1051]
最新版本框架

**Comment by Gcaufy** [comment]
版本号？

**Comment by wuweijia** [comment]
"wepy": "^1.6.0",
    "wepy-async-function": "^1.4.4",
    "wepy-com-toast": "^1.0.2"

**Comment by wuweijia** [comment]
@Gcaufy

**Comment by cuijiemmx** [comment]
@wuweijia 你应该发package-lock.json中的版本号

**Comment by Superman-wc** [comment]
@wuweijia filter操作只是浅拷贝，实际并没有产生新的数据，你改变新数据的数据实际指向的还是data里的数据
