### ISSUE TITLE
wepy 1.7.1 取消了this.setData 吗？

### ISSUE THREAD

**Issue by dgleung** [Tencent/wepy#1052]
以下//注释的代码不能改变数据。虽然用this.xx=''可以改变，但是有时用setData更方便，，，，使用文档说保留setData的，但为何用不了呢？是我写错了吗？
methods={
    editSku(index) {
      let { skuName, skuPrice, skuOrgPrice, skuWeight, skuImage } = this.skus;
      // let [maskStatus , isEditSku]=['show',true] 
      // this.setData({
      //   skuName,skuPrice,skuOrgPrice,skuWeight,skuImage,maskStatus , isEditSku
      // })
      this.skuPrice = skuPrice;
      this.skuPrice = skuPrice;
      this.skuName = skuName;
      this.skuOrgPrice = skuOrgPrice;
      this.skuWeight = skuWeight;
      this.skuImage = skuImage;
      this.maskStatus = 'show';
      this.isEditSku = true;
      this.editSkuIndex = index;
    },
}

**Comment by Gcaufy** [comment]
没有取消，具体为什么可能得调试一下看看才行。

**Comment by dgleung** [comment]
见鬼了。直接wepy init empty project，在index.wpy   
  data={
      rst:'yes'
    }
    onLoad() {
      this.setData({rst:'no'})
      console.log('rst:',this.rst)
    }
数值依然没必变．wepy 1.7.1，win10，node v8.9.3 开发工具版本v1.02.1802270

**Comment by Gcaufy** [comment]
console.log('rst:',this.rst) 不会变的，
this.rst 与 setData 无关。

**Comment by dgleung** [comment]
我将rst放到 wxml里面 <view>{{rst}}</view> ,this.setData({rst:'no'})后，依然没改变？

**Comment by Gcaufy** [comment]
如果是在组件中， this.setData 会为 rst 加上一个前缀的。。
你可以试试
```
this.$wxpage.setData({rst: 'no});
```

**Comment by realeve** [comment]
@ilaipi 解决了没，我也遇到同样的问题。
![image](https://user-images.githubusercontent.com/448208/47802447-3c6fd000-dd6b-11e8-903c-cdd6857d8452.png)

**Comment by ilaipi** [comment]
> @ilaipi 解决了没，我也遇到同样的问题。
> ![image](https://user-images.githubusercontent.com/448208/47802447-3c6fd000-dd6b-11e8-903c-cdd6857d8452.png)

@realeve 好像当时直接`this.city = ''`这样是可以的。还有`this.$apply()`可能也需要。

**Comment by realeve** [comment]
@ilaipi 我就是想用解构一次性赋值，不想用  this.xxx

**Comment by ilaipi** [comment]
@realeve 我也是这么想的，不知道什么问题

**Comment by agoodcoolman** [comment]
在组件中使用这样可以生效。
```
this.city = ''
this.$apply()
```
