### ISSUE TITLE
[bug]页面组件内同时引用“普通组件”和 “ 原生组件”的问题 

### ISSUE THREAD

**Issue by bigmeow** [Tencent/wepy#1054]
## 问题描述

页面组件内同时引用“普通组件”和 “ 原生组件”时，如果普通组件比原生组件先引入，在原生组件里获取的 this.$parent 会不对，错误的指向了普通组件，同时监听原生组件的事件将不会被触发；
如果将普通组件干掉不引入，则一切正常，按照期望走。
临时解决方案是不用普通组件了，都转成 原生组件，但是原生组件无法公用全局的css ， 需要单独引入css，这点有些麻烦

## Environment

  * Platform: 开发者工具
  * Wechat version: 最新版开发工具内置模拟器
  * wepy-cli version: 1.7.2-alpha1
  * wepy version: 1.7.2-alpha1

  
## 如何重现问题

  
 在页面级组件里同时引入一个普通组件和一个原生组件，**注意普通组件要比原生组件先引入**，如：
![image](https://user-images.githubusercontent.com/10484248/37138016-5b2668da-22e3-11e8-91b5-2f8edefce9c5.png)

在 原生组件里触发一个自定义事件，同时打印下this.$parent：
```javascript
console.log(this.$parent)
this.$emit('tabChange', '参数')
```

在页面里监听该组件的自定义事件，如上图

### 实际表现
  页面监听的自定义事件没有被触发，原生组件里打印的this.$parent显示的是  search 组件
  
### 期望表现

  页面监听的自定义事件应该被触发，原生组件里打印的 this.$parent 显示的是  页面级组件

**Comment by xuxiao** [comment]
试了一下以下的方式可以触发自定义事件:
`this.$wxpage.triggerEvent('tabChange', ['参数1','参数2']);`

**Comment by AnthonyACE** [comment]
我遇到了一样的问题，this.$parent 指向了普通组件。
而且就算普通组件在原生组件之后引入也是一样的。
