### ISSUE TITLE
wepy build --output ant  wepy版本v1.7.1编译错误

### ISSUE THREAD

**Issue by z448401921** [Tencent/wepy#1057]
错误提示：(undefined) ./npm/wepy-async-function/index.js
Module build failed: TypeError: Cannot read property 'length' of null

**Comment by z448401921** [comment]
导致该错误的原因是编译后wepy-async-function下的js文件为空文件，请问该怎么解决这问题？

**Comment by pmg1989** [comment]
请问，这个问题还没有解决么，好像还是会报这个错误呢

**Comment by z448401921** [comment]
告诉你个神奇的办法，注释掉 一行//import Promise from 'promise-polyfill';

**Comment by nightost** [comment]
> 告诉你个神奇的办法，注释掉 一行//import Promise from 'promise-polyfill';
哪里注释啊

**Comment by minzhang2** [comment]
怎么解决的，你们转化成支付宝小程序还遇到其他问题么，可以一起交流下

**Comment by z448401921** [comment]
app.wpy里面
![image](https://user-images.githubusercontent.com/9210994/41410436-10915b6a-700c-11e8-9fdc-8332ce7e0264.png)

**Comment by minzhang2** [comment]
嗯嗯，我也是这么做的，你写支付宝小程序有没有发现断点的位置打不对，几乎无法调试

**Comment by Gcaufy** [comment]
因为目前没有这方面的实际需求，所以这里没有更进一步的调度测试。

**Comment by BoleLee** [comment]
> 告诉你个神奇的办法，注释掉 一行//import Promise from 'promise-polyfill';

遇到类似的错误：
`Uncaught TypeError: Cannot set property 'Promise' of undefined
    at Object../npm/wepy-async-function/index.js`
但我的`app.wpy`里并没有显式地 import promise polifill, 我猜是这句 `this.use('promisify')`，但试过了无效
