### ISSUE TITLE
output 失效

### ISSUE THREAD

**Issue by jessjava** [Tencent/wepy#1060]
wepy 1.7.1版本  output 怎么配置编译都还是 dist目录。郁闷

**Comment by Gcaufy** [comment]
应该是target 
哪里看到的output, 是不是文档没修复 过来？

**Comment by jessjava** [comment]
对。文档没有更新过来哦。
https://tencent.github.io/wepy/document.html#/?id=wepyconfigjs%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6%e8%af%b4%e6%98%8e
