### ISSUE TITLE
wepy自定义组件内的canvas， canvasToTempFilePath保存图片时出错

### ISSUE THREAD

**Issue by dgleung** [Tencent/wepy#1063]
自定义组件WXML：
` <wxc-mask status="{{bMaskStatus}}" locked="true">
 <canvas style="width: 100px; height: 100px;" canvas-id="thumbCanvas"></canvas>
</wxc-mask>`

methods内代码:
        ctx.drawImage(res.tempFilePaths[0], 0, 0, 100, 100);
        ctx.draw();
        wx.canvasToTempFilePath({ 
          canvasId: 'thumbCanvas',
          success: function(res) {
            console.log('canvasToTempFilePath:',res.tempFilePath);
          },
          fail(err) { 
            console.log('canvasToTempFilePath err :', err);
          }

出错信息：
errMsg：“canvasToTempFilePath:fail canvas is empty”

但是我将<canvas>移出到普通<view>标签，是成功的，
请问为何呢？

**Comment by jimmyrogue** [comment]
draw方法的回调里去canvasToTempFilePath
类似这样 
```
ctx.draw(true, ()=> {
wx.canvasToTempFilePath({
xxxxxxx
})
})
```
