### ISSUE TITLE
子组件的props属性传不到孙组件

### ISSUE THREAD

**Issue by yolo2013** [Tencent/wepy#1064]
A页面有一个组件叫child，
<child :widget="somedata"></child>

其中 somedata = { title: 'abc' }

child组件再引用一个子组件：
`<grandson :title="widget.title"></grandson>`

此时，props都配置正常的情况下，在grandson组件中，无法取得widget.title这个数据，请问是设计如此吗？
`props = {
      widget: {
        type: Object,
        default: {}
      }
    }`

`props = {
      title: {
        type: String,
        default: ''
      }
    }`

**Comment by wulaweb** [comment]
我也遇到了
父组件
···js

<repeat for="{{parcelList}}" key="index" index="index" item="item">
        <rich-text name="h3" class="title grey font14">包裹{{item.id+1}}</rich-text>
        <ParcelItem :config="config" :parcelid.sync="item.id"/>
</repeat>

```
子组件
···js

<repeat for="{{config}}" key="index" index="index" item="one">
          <view class="form-item">
              <text class="label bold font14">{{one.title}}</text>
              <view class="con" id="{{parcelid}}">
                  <UnitInput :name="one.name" :unit="one.unit" :placeholder="one.placeholder" :parcelid.sync="parcelid"/>
              </view>
          </view>
      </repeat>

```

孙组件
···js

 <input type="digit" class="input" id="{{name}}" data-parcelid="{{parcelid}}" placeholder="{{placeholder}}" value="{{values[parcelId][name]}}" focus="{{inputShowed}}" @input="input" />

```

parcelid在子组件能够获取，在孙组件是undefined

**Comment by coolhwm** [comment]
#1012

**Comment by WClouds** [comment]
一样的问题，没法做组件嵌套，怎么玩转组件化？

**Comment by PetersonLian** [comment]
同样问题

**Comment by Gcaufy** [comment]
两个问题要注意：
1. props 中不要使用表达式，不要使用点操作符号，建议直接传对象
2. 不要在repeat中使用props.

**Comment by Gcaufy** [comment]
这个在其它issue中说过，这两个问题开发者换个写法就可以避免了。
因为本身机制问题，没有计算在1.7.x中修复这个问题，会在后续的2.0.x中修复。但会是一个全新的版本。

**Comment by NinoWang** [comment]
> 两个问题要注意：
> 
> 1. props 中不要使用表达式，不要使用点操作符号，建议直接传对象
> 2. 不要在repeat中使用props.

repeat 中不使用 props, 还有推荐的传值方式吗
