### ISSUE TITLE
usingComponents和components无法同时使用

### ISSUE THREAD

**Issue by happybobo** [Tencent/wepy#1066]
## 问题

  usingComponents和components无法同时使用，页面编译后的json里只有components里的组件，会丢失usingComponents里写的组件。

## Environment

  * wepy-cli version: 1.7.2-alpha1
  * wepy version:1.7.2-alpha1
  
## Reproduce

在页面中同时使用
```
config = {
      navigationBarTitleText: '教务宝',
        usingComponents: {
            'BBB':'BBB'
        }
    };

 components = {
    'AAA':'AAAA'
  }
```

### 实际编译后

页面生成的json只有：
`{"navigationBarTitleText":"","usingComponents":{"AAA":"AAA"}}`
  
### 期望编译后

`{"navigationBarTitleText":"","usingComponents":{"AAA":"AAA", "BBB":"BBB"}}`

**Comment by Gcaufy** [comment]
不能同时使用，请直接 使用 components 

```
components = {
'@aaa': aaa
}
```
