### ISSUE TITLE
拦截navigateBack问题

### ISSUE THREAD

**Issue by AdamWei** [Tencent/wepy#1067]
由于业务需要，需要拦截navigateBack，能不能针对noPromiseMethods中把navigateBack去掉单独开个分支，供我们使用，要不每次改源码感觉不舒服。

**Comment by Gcaufy** [comment]
```
// wepy.config.js

appConfig: {
   noPromiseAPI: ['navigateBack']
}
```

**Comment by AdamWei** [comment]
这个具体加在那个地方？

**Comment by AdamWei** [comment]
加上好像不管用,感觉反了
![image](https://user-images.githubusercontent.com/18081527/37319641-ee2b191c-26aa-11e8-8afa-5d10af2d0014.png)

**Comment by hudongyang** [comment]
@Gcaufy  你理解反了,  楼主的意思是将navigateBack加上Promise,  而不是取消Promise

**Comment by hudongyang** [comment]
这样配置

appConfig: {
      noPromiseAPI: {
          navigateBack: false
      }
}
