### ISSUE TITLE
zsh: command not found: wepy

### ISSUE THREAD

**Issue by foxsin10** [Tencent/wepy#1075]
## Description
zsh: command not found: wepy

## Platform
  * Mac
## Environment
  * wepy-cli version: 1.7.1
## Reproduce

  [如何重现问题]
  
在 mac 上使用 `Homebrew` 安装了 `node@8`, `npm` 命令正常，如下图
<img width="897" alt="qq20180314-105356 2x" src="https://user-images.githubusercontent.com/11630650/37381492-6ab54a66-2778-11e8-9d8c-bd3248bdc784.png">

### Observed Results

在安装完 `wepy-cli` 之后，无法识别 `wepy` 命令；在 `.zshrc` 中加入以下配置也没生效
  
<img width="639" alt="qq20180314-112748 2x" src="https://user-images.githubusercontent.com/11630650/37381905-c77e975a-277a-11e8-8db3-8ee2bfb9345c.png">

**Comment by foxsin10** [comment]
node: 8.9.4
npm: 5.6.0
均可正常使用， vue-cli 也可正常使用；
有人遇到同样问题吗？

**Comment by foxsin10** [comment]
在安装完 wepy-cli 之后按照路径提示
<img width="570" alt="qq20180314-134209 2x" src="https://user-images.githubusercontent.com/11630650/37385119-8db4f52e-278d-11e8-80fd-8201a6663448.png">
如图，找到使用的 `node` 文件夹路径下的 `bin` 文件夹，找到 `wepy` ，将路径添加到 `.zshrc` 文件中
<img width="517" alt="qq20180314-134521 2x" src="https://user-images.githubusercontent.com/11630650/37385196-f704b262-278d-11e8-9552-bb85692576bc.png">

**Comment by eightfeet** [comment]
![image](https://user-images.githubusercontent.com/5194178/43358934-5fc5c51c-92cc-11e8-9502-478da251dbb8.png)
![image](https://user-images.githubusercontent.com/5194178/43358955-af9caa1a-92cc-11e8-9529-bb2a665927b5.png)
@foxsin10 我同样的问题，按照您的配置还是显示如下
```sh
zsh: command not found: wepy
```
请问是哪里姿势不对～～～

**Comment by eightfeet** [comment]
ok, I get it.
![image](https://user-images.githubusercontent.com/5194178/43361729-4d7df18e-930a-11e8-9d19-409d78e153a3.png)

**Comment by WangShuXian6** [comment]
重新安装一下wepy-cli就可以了，会自动将路径写如对应系统的对应配置文件内
