### ISSUE TITLE
pug 模板 + style scoped 报错 unexpected character `@`

### ISSUE THREAD

**Issue by gauseen** [Tencent/wepy#1077]
pug 模板：
`view.test__btn(@tap="tap") click me`

```
style:
 <style lang="stylus" scoped>
```

运行报错：
`unexpected character `@``

去掉 scoped 就可以编译成功，请问能解决吗？

**Comment by gauseen** [comment]
` $ wepy -v
1.7.1`

**Comment by Gcaufy** [comment]
改成bindtap呢？
是pug的原因还是 scoped的原因？

**Comment by GooeyNyan** [comment]
@gauseen 
```pug
view.test__btn( @tap="tap") click me
```
像上面👆这样，`@tap` 和 `(` 之间加个空格应该能解决吧？

**Comment by xream** [comment]
pug 的老问题了, 属性换行写
