### ISSUE TITLE
How to use Redux under WEPY?

### ISSUE THREAD

**Issue by Liqiankun** [Tencent/wepy#1078]
Someone can share me a demo?

**Comment by Gcaufy** [comment]
wepy init standard myproject

**Comment by mogazheng** [comment]
Why did a Chinese people use English in a Chinese Project...

**Comment by Liqiankun** [comment]
@mogazheng  Cuz not just Chinese people use wepy!  See? Github is an international community! That's it!

**Comment by dgleung** [comment]
wepy init standard myproject  no redux demo，，，and wepy-cli /package/template has a 'counter' demo ,too simple

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/37499435-a662cc50-28fe-11e8-97c4-303a16558ef5.png)
