### ISSUE TITLE
手机端引用的本地图片不显示，文件夹未上传

### ISSUE THREAD

**Issue by ZhengKehang** [Tencent/wepy#1086]
image src="../assets/images/kh.png"
图片不显示，PC端没有问题，手机端这种形式的图片都不显示。
远端调试发现，整个assets文件夹没有上传，PC端上传成功的。有谁知道怎么解决这个问题？

**Comment by ZhengKehang** [comment]
谁来解答一下啊

**Comment by Gcaufy** [comment]
看一下dist里有没有assets文件夹吧。

**Comment by ZhengKehang** [comment]
就是assets文件没有上传成功，在PC端可以的
