### ISSUE TITLE
目前尝试过这样的行为:scroll-view视图中的bindscrolltolower及bindscrolltoupper事件无法触发

### ISSUE THREAD

**Issue by levinzero** [Tencent/wepy#1087]
如下：
`<scroll-view scroll-y="{{true}}" id="first" @scrolltolower="lower" @scrolltoupper="upper" style="height:{{swiperHeight * (recordList.length) + 'rpx'}}" @scroll="scroll" @tap="tap">
          <view class="list" wx:if="{{recordList.length > 0}}">
            <repeat for="{{recordList}}" key="index" index="index" item="item">
              <list :content.sync="item" :height.sync="swiperHeight"></list>
            </repeat>
          </view>
        </scroll-view>

methods = {
      lower(){
        console.log("lower")
      },
      upper(){
        console.log("upper")
      },
      scroll(){
        console.log("hi")
      },
      tap() {
        console.log("hi")
      }

  }
`

预期得到一个滑动时，滑动到底部时， 滑动到顶部时触发效果，结果均无输出，tap事件正常。
请问这是框架本身的BUG还是？

**Comment by jxl893251217** [comment]
已经找到问题了，page要也设高度100%
