### ISSUE TITLE
$apply 到组件渲染有大概3 - 5秒，不懂在处理什么，导致数据呈现无故延迟3 - 5秒

### ISSUE THREAD

**Issue by ymqq** [Tencent/wepy#1091]
[数据渲染延迟](https://github.com/ymqq/resources/blob/master/2018-03-16%2016.30.52.gif)

![2018-03-16 16 30 52](https://user-images.githubusercontent.com/3469590/37513145-23e37658-293f-11e8-83f5-d45c709d8aeb.gif)

[接口代码逻辑](https://github.com/ymqq/resources/blob/master/QQ20180316-163806%402x.png)

<img width="809" alt="qq20180316-163806 2x" src="https://user-images.githubusercontent.com/3469590/37513153-2a24b9fa-293f-11e8-9aac-3d134d29c5ab.png">

因为页面数据相对较大，上拉加载更多时，接口数据都已经返回了，界面数据渲染明显延迟。

怀疑是$apply()脏数据检查耗时。

或者是列表组件数据增长时，渲染耗时。

**Comment by ystarlongzi** [comment]
确实是，见我刚发的 #1090

**Comment by Gcaufy** [comment]
@ymqq @ystarlongzi 
你把看看数据的大小。。这个问题跟脏数据检查关系不大，
以前的测试数据：一个10m的数据能在20ms内完成1000次深比较。但是一个10m的数据进行setData  却需要 8000ms

所以先看看你的数据大小，数据太大了，你直接用setData也一样

**Comment by ystarlongzi** [comment]
@Gcaufy @ymqq 
抱歉，我刚又验证了下，看来我那个 issue 里描述的不对。

我这里上拉加载 15 * 10 = 150 条数据，不管是纯 js 对象，还是 Immutable 数据对象，【深比较】都没啥性能问题，那个 issue 里我分析不对。

我这里碰的性能问题，完全是有 `this.setData()` Immutable 数据类型导致的，只要在 `this.setData` 前，将 Immutable 数据类型转换为纯 js 对象，性能就没啥问题了 😅 😅😅

@ymqq 你可以 debug 下，你那里是什么问题导致的

**Comment by Seanwong933** [comment]
我也遇到这个问题，而且我数据一点都不大，统统都延迟。
