### ISSUE TITLE
[信息] 检测到wepy版本不符合要求，正在尝试更新，请稍等。

### ISSUE THREAD

**Issue by bolen** [Tencent/wepy#1093]
MAC wepy运行sudo wepy build --watch出现这个问题：
[信息] 检测到wepy版本不符合要求，正在尝试更新，请稍等。

先安装微信开发者工具；在安装wepy那就会导致；开发者工具打不开，提示：您的个人资料来自更高版本的NW.js，因此无法使用。
先安装wepy在安装微信开发者工具就会大致编译项目不了；
我都是全新安装的环境，运行的是wepy init standard myproject下载的项目

**Comment by maxiaochunchun** [comment]
同样的问题 大佬解决了吗

**Comment by bolen** [comment]
问题是没有安装npm；执行
`npm  install`
就行
