### ISSUE TITLE
组件里wx.createSelectorQuery().in()怎么使用？

### ISSUE THREAD

**Issue by callmesoul** [Tencent/wepy#1095]
再组件里wx.createSelectorQuery()，可以，但是找不到组件内的节点。看文档说组件内的不需加.in(this)。
但是wepy组件好像跟原生组件不一样啊。加.in(this)，不进入也不报错啊
请问怎么查找wepy组件内节点。

**Comment by insub** [comment]
同问，请问解决了么？ @callmesoul

**Comment by callmesoul** [comment]
@insub 没有，想其他方法吧。这暂时是个bug。 原生组件跟wepy组件完全就两回事。而wx.createSelectorQuery()是针对原生的。

**Comment by Gcaufy** [comment]
如果你是使用的原生组件，那才可以使用`wx.createSelectorQuery()` 去查找。
同时需要注意 this的不同， wepy中，this.$wxpage 才是对应的 小程序中的 this

**Comment by guopeng27** [comment]
wx.createSelectorQuery().in(this.$wx).select('#xxx')
