### ISSUE TITLE
使用了一段时间，暂时发现的部分问题，repeat内子组件的数据不独立

### ISSUE THREAD

**Issue by wang-fu** [Tencent/wepy#1099]
wepy 1.7.0
微信开发者工具1.02.1803150
真机MZ5s  微信6.6.5

使用了一段时间，发现的部分问题（都变通解决了），有些在 issuse 里找了，有些没有，如果不是 bug，或者不支持的特性，就请关闭吧。

- repeat 标签里面的自定义组件下再直接嵌套自定义组件不支持 props 传值(只会取第一个)[已只问题](https://github.com/Tencent/wepy/issues/323)，但内部可以再通过Repeat嵌套进去。

- repeat循环组件时，item.xx 通过 props父组件传值时，把对象的子属性xx传入，当对象数据发送改变时，不会触发子组件更新。 （ 已变通解决办法，放在  repeat 标签内有效， 或整个 item 传入）

- repeat 下子组件的 computed 计算属性无效，一直使用第一个。

- repact 下子组件 data 内的值会被所有其他组件共享。（暂时发现可以用 props 传进来的对象动态设置值进去，其值不会被其他循环组件共享）

以上反馈是按照和 vue 的表现差异所对比的。比如后面几个基本上是vue日常使用场景，期待一般应该是子组件的数据是独立的。不知wepy设计是否是本身如此。

其他还有些不是很明显的问题，都能变通处理，项目不错，总体比写原生小程序逻辑要优雅，作者辛苦了~

**Comment by cuijiemmx** [comment]
@wang-fu 翻阅一下issue list，这些问题报过无数遍了
比较安全的做法是
1. 能不用repeat的地方用原生的wx:for
2. 用repeat的时候，子组件内部使用时不要用data, computed，尽量用props

据说这些问题会在下个重大更新时解决..

**Comment by lipeiwei-szu** [comment]
@wang-fu @cuijiemmx 兄弟，你们目前怎么做？
1. wx:for似乎传递不了object给子组件
2. “用repeat的时候，子组件内部使用时不要用data, computed，尽量用props”。这个我也知道，但是有的数据源比较复杂，得重新computed一下才能给item使用，除非你传给repeat的时候将数据重新组装修饰一下，这样子也很麻烦，暂时先找找其它方法

**Comment by cuijiemmx** [comment]
@lipeiwei-szu 就是按你说的这种办法做！按组件结构组装好数据传入..

**Comment by wang-fu** [comment]
嗯，目前也是这样解决的，期待重大更新。

**Comment by nishino-tsukasa** [comment]
那事件响应怎么办呢，也拿不到值

**Comment by kennylbj** [comment]
感觉这几个问题是优先度很高的bug，但是限于wepy的架构又不易解决，而采用hack trick来绕过这些问题的方式又非常不优雅。期待下次重大更新能解决。
