### ISSUE TITLE
template 中数据使用三元运算绑定时出现编译问题

### ISSUE THREAD

**Issue by 9wenzi** [Tencent/wepy#1101]
## Description
  组件的template 中，当在组件内容在数据绑定使用三元运算时，若三元运算左边存在 '<'  符号比较大小时，会出现编译错误。若果是 '>'  则可以通过编译

错误提示为：
[Error] ERROR IN : src\components\test.wpy
[xmldom error]  element parse error: Error: invalid tagName:
@#[line:undefined,col:undefined]

## Environment

  * Platform: [开发者工具]
  * Platform version: [1.02.1803150]
  * wepy-cli version: [wepy-cli-v1.7.1]
  * wepy version: [1.7.1]
  
## Reproduce
src/components/test.wpy
```
<style></style>
<template>
  <view>{{1 < 2 ? 1 : 2}}</view>

</template>
<script>
  import wepy from 'wepy'

  export default class Test extends wepy.component {

  }
</script>
```
  
### Observed Results

 执行 wepy build -w 命令
提示：
 [Error] ERROR IN : src\components\test.wpy
[xmldom error]  element parse error: Error: invalid tagName:
@#[line:undefined,col:undefined]
终止编译
 
### Expected Results

在微信开发者工具v1.02.1803150 中
```
<view>{{1 < 2 ? 1 : 2}}</view>
```
如此书写则没有问题，显示的内容为 1

**Comment by SuperJolly** [comment]
这里建议使用计算属性，目前wepy不支持三元运算符数据绑定

**Comment by 9wenzi** [comment]
好吧(lll￢ω￢)......，根据报错的表现，'<' 小于号出现错误，'>'’大于号又可以编译，我猜是解析组件的正则没有处理好。
