### ISSUE TITLE
wepy-redux connect 不建议把store的所有state放到computed里去

### ISSUE THREAD

**Issue by Superman-wc** [Tencent/wepy#1106]
版本
"name": "wepy-redux",
  "version": "1.5.4",

原代码 wepy-redux/src/connect/index.js
第39行到43行
```
this.computed = Object.assign(this.computed || {}, states, mapState({
                    $state(state) {
                        return state;
                    }
                }));
```
这个设置会将store的所有state设置到page.data里， 对于大的数据会导致小程序AppData超过限制

官方优化里提到：
https://mp.weixin.qq.com/debug/wxadoc/dev/framework/performance/tips.html
2. 每次 setData 都传递大量新数据
由setData的底层实现可知，我们的数据传输实际是一次 evaluateJavascript 脚本过程，当数据量过大时会增加脚本的编译执行时间，占用 WebView JS 线程，

```
 connect (states, actions) 
```
本身这个方法的states已经从store的state里取组件需要的数据了，就不应该多此一举把所有数据connect到data里吧

**Comment by rchunping** [comment]
是的，用它弄过上拉加载列表数据，后面直接跪了

**Comment by ystarlongzi** [comment]
安装最新版的 wepy-redux@1.5.6 https://github.com/Tencent/wepy/pull/1079#issuecomment-373243476
