### ISSUE TITLE
组件传递异步数据有BUG

### ISSUE THREAD

**Issue by a24576946** [Tencent/wepy#1108]
父组件.sync传递一个异步数据，在子组件props接收时，在微信开发者工具上组件能接受到异步数据并且渲染正常，在手机微信上却接收不到，这种Bug怎么解决呢？？？

**Comment by littleQing** [comment]
我也遇到了这样的问题，页面传递异步数据到子组件首次加载传递不过去，在开发工具没问题，手机上有问题。请问你问题解决了吗

**Comment by lettgers** [comment]
兄弟解决了吗?开发者工具没问题,真机有问题

**Comment by kekeon** [comment]
官方处理问题有点慢啊，好多人提都不修复

**Comment by 18978909244** [comment]
这个问题也发现了

**Comment by Gcaufy** [comment]
代码压缩上传关掉

**Comment by msdog** [comment]
辣鸡框架
