### ISSUE TITLE
请问是否有计划支持单元测试？

### ISSUE THREAD

**Issue by xbl** [Tencent/wepy#1110]
如题啦，请问是否有计划支持单元测试？

**Comment by Gcaufy** [comment]
单元测试自己添加 就行了吧，不需要单独去支持。
或者是给项目模板添加单元测试。

**Comment by xbl** [comment]
如果希望测试page 或者component 就需要对wpy 文件的loader支持，如果是js 文件测试的确可以自己加。

**Comment by xbl** [comment]
我自己写了一个 [wepy-jest](https://www.npmjs.com/package/wepy-jest) 
以及写这模块的思路：
https://xbl.github.io/2018/03/22/unit-test-wepy/
有兴趣的同学可以了解一下，欢迎吐槽！

**Comment by 1193082625** [comment]
小程序可以使用miniprogram-simulate做单元测试，但是放到wepy里面并不使用，还是希望可以通过模拟场景和数据对页面和组件做测试
