### ISSUE TITLE
将小程序的promise api单独拆分成npm包

### ISSUE THREAD

**Issue by klouskingsley** [Tencent/wepy#1113]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

当用户只需要使用wepy.request, wepy.getUserInfo等promisify api的时候，需要npm install wepy，然后wepy中有page/component等东西是多余的

**Comment by bigmeow** [comment]
已拆 https://www.npmjs.com/package/minapp-api-promise
