### ISSUE TITLE
onLoad 问题

### ISSUE THREAD

**Issue by leefj** [Tencent/wepy#1114]
我在使用中发现，当page没有onLoad方法时，page中组件的onLoad方法不被调用，这是bug吗？

**Comment by cuijiemmx** [comment]
@leefj 我重现不了你说的问题...

**Comment by iluozhiqiang** [comment]
我遇到了，痛苦的折腾了很久。在开发工具里，正常调用。在预览中不调用。在远程调试中正常调用。
是从a界面跳转到b界面，b界面的onLoad不执行，不是所有的都不执行，单这个b界面，我已经最简化了，依然不调用onLoad

**Comment by iluozhiqiang** [comment]
![image](https://user-images.githubusercontent.com/7245622/41355692-bcc77214-6ee7-11e8-9ac1-62cc2eb1baa8.png)
大家帮忙看看，是否也有同样的问题
