### ISSUE TITLE
参数中带有特殊字符的时候，无法传递

### ISSUE THREAD

**Issue by wells1013** [Tencent/wepy#1115]
版本: wepy@1.7.1
参数是: params = {};params.src='https://www.baidu.com/mobile/?p=test'
通过 this.$navigate('page', params)
在page 中获取参数src 的时候得到的值是'https://www.baidu.com/mobile/'

**Comment by xiaosongxiaosong** [comment]
使用 encodeURIComponent 对 src 编码，获取的时候再使用 decodeURIComponent 进行解码

**Comment by xiaosongxiaosong** [comment]
使用 encodeURIComponent 对 src 编码，获取的时候再使用 decodeURIComponent 进行解码

**Comment by wells1013** [comment]
目前已经如此处理了，但是是不是可以封装在 wepy 内部跳转 方法里呢？

**Comment by heath-l** [comment]
我也遇到这个问题了。。。把传参保存在全局变量了。。确实这个方案encodeURIComponent比较好
