### ISSUE TITLE
eslint没有监测js文件的语法规则

### ISSUE THREAD

**Issue by cztflove** [Tencent/wepy#1117]
## Description
src目录下有action文件夹，其中的js文件无法用eslint来监测其中的语法问题
但是wpy文件是可以监测的
在哪里可以配置监测范围包括js文件呢？

## Environment
  * wepy-eslint 1.5.3

  [期望表现]
  
  js文件可以被eslint实时监测

**Comment by EdwardZZZ** [comment]
https://github.com/Tencent/wepy/pull/1287
