### ISSUE TITLE
注释异常

### ISSUE THREAD

**Issue by leefj** [Tencent/wepy#1118]
只是把config注释掉，就报错了
![222222](https://user-images.githubusercontent.com/12420137/37801948-775679c4-2e63-11e8-8047-db21db9b3a86.png)

![33333333](https://user-images.githubusercontent.com/12420137/37801950-7bcabea2-2e63-11e8-90d4-fbd284fc23f7.png)

**Comment by leefj** [comment]
然后携程这样又正常了
![444444](https://user-images.githubusercontent.com/12420137/37802044-d178b0de-2e63-11e8-881d-1147d5abb258.png)

**Comment by Gcaufy** [comment]
Page 的config 是必填字段，
后面考虑把这个只作一个warning而不是error

**Comment by leefj** [comment]
[UUUU-HD.mp4.zip](https://github.com/Tencent/wepy/files/1849844/UUUU-HD.mp4.zip)
