### ISSUE TITLE
子组件props传值

### ISSUE THREAD

**Issue by SpringHgui** [Tencent/wepy#1119]
### 给子组件传属性值时，难道必须要定义变量
##例如
`<components1 :show="true"></components1>`

[components1组件的show属性控制组件的某一标签是否显示，如上面例子使用时，不能正确渲染，必须在调用控件的父组件或页面的data中定义一个变量来进行传递

```
<components1 :show="show"></components1>

{
     data={
        show：true
  }
}
```
]

**Comment by coolhwm** [comment]
`<components1 show="true"></components1>`
传递字符串“true”
`<components1 :show="isShow"></components1>`
传递变量isShow
