### ISSUE TITLE
wepy打包生成dist后，丢失所有样式问题

### ISSUE THREAD

**Issue by luyuan11233** [Tencent/wepy#1122]
执行 npm run build,生成dist文件，在微信开发工具上打开，在设置的项目里关掉
1、关闭ES6转ES5。2、关闭上传代码时样式自动补全。3、关闭代码压缩上传
然后小程序跑起来后丢失所有样式。不关掉这些设置 也是丢失所有样式，请问有什么解决办法

**Comment by Gcaufy** [comment]
版本是？

**Comment by SnowFlowers** [comment]
同样的问题，换了一个电脑后，两个同事的dist文件里面的 wxss都不见了

**Comment by NoahSun** [comment]
![image](https://user-images.githubusercontent.com/12728157/40444983-663868da-5efd-11e8-85ee-7091aae014f5.png)
使用最新的wepy-cli 1.7.2 .wxss 文件倒是生成了，但是样式并没有应用
