### ISSUE TITLE
在template中background-image 加载图片失效，但无任何error。

### ISSUE THREAD

**Issue by yoohan-dex** [Tencent/wepy#1129]
## Description

  在template中background-image 加载图片失效，但无任何error。
## Environment

  * Platform: iOS
  * Platform version: 11.3
  * Wechat version: 6.6.5
  * wepy-cli version: 1.7.2-alpha2
  * wepy version: ^1.7.1
  
## Reproduce

* 在开发者工具可以加载出图片，但到真机测试就不可以。但用image的src在真机可以加载出来 而background则不行。

### Observed Results

* 渲染不出图片
  
### Expected Results

 * background会有图片出现
## Relevant Code / Logs

  ```
<view class="image" style="background-image: url({{mainImage}})"></view>
<image src="{{ mainImage }}" />
   ```

**Comment by ymqq** [comment]
backgroud的路径是本地路径么？小程序不支持bg的本地路径？

若是使用网址路径，你有配置相应的域名么？

或者小程序打开调试功能试试，或者是IDE上开启域名验证。
