### ISSUE TITLE
'@mytest:Mytest' 原生组件，在1.7.2中不生效

### ISSUE THREAD

**Issue by kala888** [Tencent/wepy#1132]
写了一个mytest的组件，在页面上没效果
    "moment": "^2.21.0",
    "numeral": "^2.0.6",
    "promise-polyfill": "^6.0.2",
    "redux": "^3.7.2",
    "redux-actions": "^2.2.1",
    "redux-promise": "^0.5.3",
    "redux-saga": "^0.16.0",
    "wepy": "^1.7.2-alpha1",
    "wepy-async-function": "^1.4.4",
    "wepy-com-toast": "^1.0.2",
    "wepy-redux": "^1.5.3"

![image](https://user-images.githubusercontent.com/1215976/37902143-13c482c8-3126-11e8-930e-081ac4ee689b.png)

**Comment by Gcaufy** [comment]
对照编译后的文件看看？是哪里不对。

**Comment by kala888** [comment]
@Gcaufy 没有生成Mytest.json这个文件

**Comment by wq1308786830** [comment]
我也有这个问题，而且组件传值报错：`unexpected attribute name, near `.once``编译后的结果`<recProjectItem  v-bind:items.once="item"/>`，希望能尽快解决一下
