### ISSUE TITLE
npm run build 未进行压缩

### ISSUE THREAD

**Issue by klouskingsley** [Tencent/wepy#1134]
* wepy version: [在package.json里] 1.6.0

**Comment by klouskingsley** [comment]
刚开始是这样：
```
[WARNING] 找不到插件：wepy-plugin-uglifyjs。
[17:16:55] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
npmup to date in 3.22s
 WARN wechat-live@1.0.0 No repository field.

[17:17:00] [完成] 已完成安装 wepy-plugin-uglifyjs，重新启动编译。
```

后来手动安装 wepy-plugin-uglifyjs, wepy-plugin-imagemin后压缩成功了

**Comment by qianzhaoy** [comment]
我也是这样，可是自动安装好 `wepy-plugin-uglifyjs` 后， 只有wxss压缩了。 JS 还是原样。
请问你执行 `npm run build` 后，dist 文件夹里的 js 是压缩状态的吗

**Comment by klouskingsley** [comment]
js是压缩状态的

**Comment by Gcaufy** [comment]
插件是在wepy.config.js里面配置的。比如你不需要压缩图片，你就把那个imagemin去掉就行了。

**Comment by Julyyq** [comment]
如果运行`npm run build`发现JS没有压缩，那么需要先安装`npm install wepy-plugin-imagemin --save-dev`, 然后重新运行`npm run build`就可以了。

**Comment by huhai122** [comment]
我 imagemin 和uglifyjs 都--save-dev了 run build 正常 就是js没编译

**Comment by kekemao** [comment]
运行 npm run build 时 出现警告如下，但是实际上图片路径是没问题的
[WARNING] Error: Error in file: D:/hisunpay/act-balance-query-wxminiprogram/src/images/close.png

The system cannot find the path specified

**Comment by kekemao** [comment]
运行 npm run build 时 出现警告如下，但是实际上图片路径是没问题的，是什么原因导致警告呢
[WARNING] Error: Error in file: D:/hisunpay/act-balance-query-wxminiprogram/src/images/close.png

The system cannot find the path specified

**Comment by Teemwu** [comment]
@kekemao 我也遇到同样问题，重装 `wepy-plugin-imagemin` 就好了，感谢 @Julyyq 的回答

**Comment by cvpv** [comment]
2022年，wepy1最新版，按照官方安装的1.72 wepy init standard myproject ，官方demo还是有这个问题。
