### ISSUE TITLE
请问如何在gitlab中，添加wepy文件格式的语法高亮呢？

### ISSUE THREAD

**Issue by allendongyx** [Tencent/wepy#1142]
请问如何在gitlab中，添加wepy文件格式的语法高亮呢？

**Comment by BelinChung** [comment]
在项目根目录下面新建一个 .gitattributes 文件，然后里面配置
*.wpy gitlab-language=vue

具体文档参考：https://docs.gitlab.com/ee/user/project/highlighting.html
