### ISSUE TITLE
wepy init standard后，初始的index.wpy “测试组件Repeat”部分有问题

### ISSUE THREAD

**Issue by alexjingjing** [Tencent/wepy#1146]
## Description

  [问题描述：wepy init standard后，初始的index.wpy文件测试组件部分有问题]

## Environment

  * Platform: Windows7
  * Platform version: 
  * Wechat version: 微信开发者工具v1.02.1802270
  * wepy-cli version: 1.7.2-alpha2
  * wepy version: 1.7.2-alpha2
  * other version: 
  
## Reproduce
1、使用 wepy init standard myproject 初始化项目
2、npm install
3、npm build --watch
4、微信开发者工具引入项目
5、发现“测试组件Repeat” Panel下只有一个小数点。

### Observed Results
“测试组件Repeat” Panel下只有一个小数点。
  
### Expected Results
展示两级列表，列表项点击可变

## Relevant Code / Logs
* index.wpy 67-72原始文件
```
<panel>
  <view class="title" slot="title">测试组件Repeat</view>
  <repeat for="" index="index" item="item" key="key">
    <group :grouplist="item" :indexa="index"></group>
  </repeat>
</panel>
```
* 修改为如下便可正常显示
```
<panel>
  <view class="title" slot="title">测试组件Repeat</view>
  <repeat for="{{groupList}}" index="index" item="item" key="key">
    <group :grouplist="item" :indexa="index"></group>
  </repeat>
</panel>
```

请问是不是需要修改wepy源码才能修复这个问题。

**Comment by Gcaufy** [comment]
好像并没有问题
代码在这里：https://github.com/wepyjs/wepy-templates/blob/master/templates/standard/template/src/pages/index.wpy
