### ISSUE TITLE
层级数据绑定支持

### ISSUE THREAD

**Issue by leefj** [Tencent/wepy#1147]
data = {
        kk:"999999",
        name:"姓名",
        mobile:"13555679082"
        address: {
           name:"姓名",
           mobile:"13555679082"
        }
    };

<name :value.sync="address.name">  
                 <text slot="label">姓名</text>
</name>

<mobile :value.sync="name">  
                 <text slot="label">手机</text>
</mobile>

请问可以支持层级绑定吗？

**Comment by aokihu** [comment]
不行，我实际使用中发现，最好是只有一层，二层以上的好像不能动态更新

**Comment by Gcaufy** [comment]
这个是支持的
