### ISSUE TITLE
初始化项目总是有这个错误：thirdScriptError 

### ISSUE THREAD

**Issue by NinoWang** [Tencent/wepy#1152]
thirdScriptError 
 sdk uncaught third Error 
 regeneratorRuntime is not defined 
 ReferenceError: regeneratorRuntime is not defined

thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined

**Comment by xiaosefengyun** [comment]
和你的问题一样

**Comment by DoubleWoodH** [comment]
我也是，当我把这个 `import 'wepy-async-function'` 注释掉后就没有这个报错了，应该就是这个库 `wepy-async-function` 的问题吧

**Comment by NinoWang** [comment]
@DoubleWoodH  我这里注释掉也不可以，况且，这个库还要用， 所以还没找到解决办法

**Comment by NinoWang** [comment]
@xiaosefengyun 麻烦有解决方案了和大家分享一下

**Comment by xiaosefengyun** [comment]
@NinoWang i import 'wepy-async-function'首先在app.wpy引入这个文件，然后关闭项目选项里的ES6转ES5还有babel: {
      sourceMap: true,
      presets: [
        'env'
      ],
      plugins: [
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions',
        'transform-async-to-generator'
      ]
    }
设置这个。。。

**Comment by xiaosefengyun** [comment]
@NinoWang 我是这么解决的，现在没有报错了，但是我发现wepy那个request不支持async/await还要再封装一次。。。

**Comment by Megasu** [comment]
你们是不是把项目目录名称改成了驼峰命名的写法    
如： **wepyshop  改成了 wepyShop**，
平常写代码都不报错，直到  `import 'wepy-async-function'` 的时候报错了，调了一天都调不好。
试试把wepy项目目录改成小写，当然也不要出现特殊字符。

**Comment by ljw930824** [comment]
把项目中ES6 转 ES5关闭
