### ISSUE TITLE
使用request报错，‘then‘ undefined 

### ISSUE THREAD

**Issue by z784324922** [Tencent/wepy#1157]
![qq1](https://user-images.githubusercontent.com/31068244/38131872-489bb936-343b-11e8-80b5-0ecb0bd51e6a.png)
![then](https://user-images.githubusercontent.com/31068244/38131901-6a1f6bf2-343b-11e8-96f9-489f09758794.png)

**Comment by fengxinming** [comment]
你一定是没有仔细看文档，需要在app.wpy里面添加promise支持，赶紧再仔细看一下文档

**Comment by Gcaufy** [comment]
看一下wiki
