### ISSUE TITLE
cmd 打印大量 log 不利于调试

### ISSUE THREAD

**Issue by jackdizhu** [Tencent/wepy#1164]
wepy.config.js

// 处理框架 大量 log 排错难问题
let log = console.log
console.log = (msg) => {
  let _arrR = [
    /\[编译\]/g,
    /\[写入\]/g,
    /\[变更\]/g,
    /\[拷贝\]/g
  ]
  for (let i = 0; i < _arrR.length; i++) {
    let r = _arrR[i].test(msg)
    if (r) {
      return 0
    }
  }
  log(msg)
}

![qq 20180331102950](https://user-images.githubusercontent.com/17809883/38158821-7d39b27c-34ce-11e8-90dc-52041c960f89.png)

我认为只留一个成功 和 error 打印就行了

**Comment by Gcaufy** [comment]
后面这一部会做成用户可控的。
