### ISSUE TITLE
[重用思路]原生小程序TEMPLATE作WEPY框架組件

### ISSUE THREAD

**Issue by hou000123** [Tencent/wepy#1167]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]
有没有原生小程序TEMPLATE作組件，反向編譯為WEPY 框架COMPONENT組件，這樣就不用重寫原生小程序組件，不能重用之前的原生小程序TEMPLATE在WEPY框架作組件使用很不科學，或請提供重用思路

**Comment by Gcaufy** [comment]
原生小程序TEMPLATE 是指什么？

**Comment by hou000123** [comment]
@Gcaufy  原生小程序TEMPLATE 是指什么？
_____________________________________________________________________________
詳見小程序官方網站:
https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/template.html
