### ISSUE TITLE
wepy 如何忽略编译或压缩某个特定的js文件

### ISSUE THREAD

**Issue by LinkXSystem** [Tencent/wepy#1176]
编译前
![image](https://user-images.githubusercontent.com/26039188/38188306-f5fd6e90-368d-11e8-822e-87b90d82881a.png)
编译之后，文件会变大到4M多
![snipaste_2018-04-02_15-56-12](https://user-images.githubusercontent.com/26039188/38188502-d32673f2-368e-11e8-8514-fa4ed9212ca3.png)

**Comment by shenahobo** [comment]
我也遇到了同样的问题,每次预览都只能去dist删除 大文件下的sourceMappingURL

**Comment by shenahobo** [comment]
![image](https://user-images.githubusercontent.com/23427149/38192504-c90c88e6-369f-11e8-939d-b1478dd8907c.png)
发现将sourceMap=false 就不会生成了,不知道有没有其他更好的方法, 这个方法好像对debug有影响.

**Comment by LinkXSystem** [comment]
成功了，但改这个,对项目上线有影响吗

**Comment by SoyMeng** [comment]
```
var prod = process.env.NODE_ENV === 'production';
sourceMap: prod
```
so,build之后是没有sourceMap的
