### ISSUE TITLE
wepy-redux 是如何绑定数据到页面上的?

### ISSUE THREAD

**Issue by greatemoon** [Tencent/wepy#1177]
![image](https://user-images.githubusercontent.com/25219300/38191352-ed23596c-369a-11e8-96a2-f6087ead2153.png)

![image](https://user-images.githubusercontent.com/25219300/38191373-07467f18-369b-11e8-95ff-dbb84446b65d.png)

我也像之前的这样的写法，新增加了一个 oneNum ，但是打印出来是 undefined，我也全局搜索过 sumNum 发现除了这样声明，其他地方也没有什么改动，发现 sunNum 的初始值就为 0 ；不求甚解，望指教！

**Comment by SoyMeng** [comment]
reduces中定义了初始值，handleActions初始化state
