### ISSUE TITLE
修改样式文件不能热更新

### ISSUE THREAD

**Issue by lj0812** [Tencent/wepy#1178]
我在.wpy文件里通过以下方式

1.`<style> @import 'path/to/my.less'</style>`
2.`<style src='path/to/my.less' lang='less'></style>`

的方式引用样式文件时，修改my.less都不会热更新，需要重新npm run dev才会应用新样式

**Comment by weiyunpeng** [comment]
scss也是，每次更改内容会刷新页面，但内容并没有更新
