### ISSUE TITLE
navigateTo 从页面 A[0] => B[1] => A[2], 然后通过回退, A[2] 的数据会覆盖A[0]的数据

### ISSUE THREAD

**Issue by alanlong9278** [Tencent/wepy#1180]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]
通过navigateTo 从 商祥页 A[0] 跳到 商品列表页 B[1], 再从B[1] 跳到另外一个商祥页A[2],这时A[2]的数据 通过回退键从A[2] 返回到 B[1]再返回A[1], A[1]的数据被A[2]覆盖
## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
开发者工具 & ios
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
1.02.1803210
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
1.7.0
  * wepy version: [在package.json里]
1.7.0
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]
通过navigateTo 从 商祥页 A[0]  option: {id: '123'}跳到 商品列表页 B[1], 再从B[1] 跳到另外一个商祥页A[2]  option: {id: '321'}
### Observed Results

  [实际表现]
  
  [Observed Results]
  A[0] 的option: { id: '321' } 
### Expected Results

  [期望表现]
  
  [Expected Results]
  
  A[0] 的option: { id: '123' } 
## Relevant Code / Logs

 Page A code:
  ```
  // TODO(you): code or logs here to reproduce the problem

<template>
    <view>{{id}}</view>
    <view bindtap="go">go</view>
</template>
<script>
    export default class A extends wepy.page {
        data = {
           id: ''
         }
         methods = {
           go() {
           wepy.navigateTo('pages/b')
          }
       }
        onShow() {     
          this.id = this.$wxpage.options.id
        }
    }
</script>
  ```
Page B 
```
<template>
    <view bindtap="go">go</view>
</template>
<script>
    export default class B extends wepy.page {
        data = {
           id: ''
         }
        methods = {
           go() {
           wepy.navigateTo('pages/a?id=321')
          }
       }
    }
</script>
```

**Comment by SoooHy** [comment]
同问= =，从列表页=>详情页,后退回列表页,然后所有的详情页的数据就被覆盖了，但是开发者工具和远程调试又没有问题

**Comment by LittleDragonHuman** [comment]
#1092
