### ISSUE TITLE
请教一下 你们怎么管理全局变量 globaldata

### ISSUE THREAD

**Issue by wuweijia** [Tencent/wepy#1181]
首先，我不想引入状态管理工具。因为我的数据量不多。但是我觉得还是要有一些对全局变量管理的模式，来尽量避免出现问题。请问大家都是怎么管理的

**Comment by yangxin9003** [comment]
你的 module 就可以作为一个共享的数据存在

**Comment by tolerance-go** [comment]
觉得 redux 麻烦的话，推荐用 [wepyx](https://github.com/tolerance-go/wepyx) 管理单例数据层。
