### ISSUE TITLE
 process.env.NODE_ENV  环境变量的问题

### ISSUE THREAD

**Issue by 18613109040** [Tencent/wepy#1182]
你好！请问我在config.js 引用 process.env.NODE_ENV 变量报错 请问要怎么在项目中获取process.env.NODE_ENV的值

**Comment by xieyihao** [comment]
参考issues 
#835  请问如何设置一个环境常量？ process.ENV is not defined

**Comment by 18613109040** [comment]
谢谢

**Comment by 18613109040** [comment]
请问其他js里面如何拿到app 里面的globalData

**Comment by xieyihao** [comment]
恰巧有遇到 `wepy.$instance.globalData`，但是未在看`wepy`的API里看到。我也好奇哪里有这文档。
