### ISSUE TITLE
iphone6s上，顶部莫名少展示大约25px的空间

### ISSUE THREAD

**Issue by LittleDragonHuman** [Tencent/wepy#1183]
1、wepy框架开发
2、页面包含一个scroll-view，从导航底部开始，覆盖page
3、scroll-view内部的最上面有轮播部分
3、正常机型上面，轮播区域的起始位置正常
4、iphone6s上，轮播区域莫名奇妙被盖住大约25px的空间，只有下拉的时候才能看见

求助 why？以及 解决方案。

谢谢。

**Comment by sfanr** [comment]
分享代码出来看看了，工具不是支持代码分享吗
