### ISSUE TITLE
repeat标签渲染自定义嵌套组件问题

### ISSUE THREAD

**Issue by AkbarOsman** [Tencent/wepy#1188]
### 这是文档所说的组件循环渲染部分
![_20180405202310](https://user-images.githubusercontent.com/11870024/38365578-6fb2bc94-390f-11e8-9565-cc6551a0bb41.png)
### 遇到的问题
在我的场景中，文档使用的Child组件结构是嵌套的，也就是说Child组件里面还有一个自定义组件GrandChild，而这个歌GrandChild也会接受Child传递的prop，那么我的问题来了：单独渲染Child自定义组件的时候prop传递是正常的，从Parent到Child，再到GrandChild，都是正常传递，但是把Child放在你们所说的repeat标签时Child能够接受到每次循环的新prop，可是再传到GrandChild的时候就不会传新的prop值，GrandChild里的prop是循环第一次的prop值，并且整个循环过程中保持不变。
#### 是不是因为Child里面引入的GrandChild的ID是同一个，所以循环从头到尾都使用同一个GrandChild导致这样的问题？这个问题有没有什么解决方法？

**Comment by SoyMeng** [comment]
```
components = {
    Child1: Child,
    Child2: Child
  }
```
暂时只能这种方式

**Comment by AkbarOsman** [comment]
@SoyMeng 要是知道总共需要多少个组件的话，你这个方法还是可以的，问题是列表的数据是从后台来的，而且还会有加载更多的功能，这种情况怎么确定你要是用多少个组件！？
总之，这个坑迟早会掉的，他们还说循环里的prop不要再往下传了，我就呵呵。

**Comment by exvu** [comment]
@AkbarOsman 我今天也是遇到这个问题。很烦，想嵌套生成组件没办法

**Comment by Gcaufy** [comment]
@AkbarOsman 目前版本 wepy 的组件是静态编译组件，那么也就是需要在编译过程中知道组件是有多少个的。

**Comment by pspgbhu** [comment]
@Gcaufy 需要动态渲染组件的场景真的很多，加把油赶紧更新一波吧。

**Comment by holysky5** [comment]
@Gcaufy 需要动态循环渲染组件的场景真的很多，加把油赶紧更新一波吧。

**Comment by holysky5** [comment]
不解决这个问题,repeat还有什么用

**Comment by 2534290808** [comment]
我也有同样的问题

**Comment by ranshaw** [comment]
从父组件接受到item后，在子组件中对想要传值的（子组件中的子组件）外层包个repeat标签
`<repeat for="{{ [item] }}" key="item.orderNo" index="index" item="itemval">
           <giftItem :itemval="itemval" ></giftItem>
      </repeat>` ，这样就完美解决了

**Comment by iniself** [comment]
静态组件不适用啊。我跟你的问题一模一样，其实pageye页传到Child页的props是能传递成功的，但child再传到GrandChild时，GrandChild接收的props就有问题了

**Comment by dengying3939** [comment]
> ### 这是文档所说的组件循环渲染部分
> ![_20180405202310](https://user-images.githubusercontent.com/11870024/38365578-6fb2bc94-390f-11e8-9565-cc6551a0bb41.png)
> 
> ### 遇到的问题
> 在我的场景中，文档使用的Child组件结构是嵌套的，也就是说Child组件里面还有一个自定义组件GrandChild，而这个歌GrandChild也会接受Child传递的prop，那么我的问题来了：单独渲染Child自定义组件的时候prop传递是正常的，从Parent到Child，再到GrandChild，都是正常传递，但是把Child放在你们所说的repeat标签时Child能够接受到每次循环的新prop，可是再传到GrandChild的时候就不会传新的prop值，GrandChild里的prop是循环第一次的prop值，并且整个循环过程中保持不变。
> 
> #### 是不是因为Child里面引入的GrandChild的ID是同一个，所以循环从头到尾都使用同一个GrandChild导致这样的问题？这个问题有没有什么解决方法？

我的场景中，从Child传递props到GrandChild就失败了。我的数据是多层循环嵌套，在Parent中循环渲染传递props到Child成功，在Child中将prop.list传递到GrandChild就失败了，现在不知该如何解决

**Comment by Strong-Man** [comment]
这个最好咋解决的?
