### ISSUE TITLE
this.selectComponent() is not a function

### ISSUE THREAD

**Issue by HEYEggplant** [Tencent/wepy#1189]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs here to reproduce the problem
  ```
请问wepy 如何支持 this.selectComponent() 这个function 参阅其他issue this.$wxpage.selectComponent() 也报错 is not a function

**Comment by shangdev** [comment]
@HEYEggplant 
你好，问题解决了嘛？如何使用selectComponent()呢？

**Comment by beyonddevil** [comment]
你好，怎么解决这问题
