### ISSUE TITLE
微信开发者工具 Mac 版更新到最新 1.02.1804080 版时有报错

### ISSUE THREAD

**Issue by zaing** [Tencent/wepy#1194]
![https://ws3.sinaimg.cn/large/006tKfTcgy1fq5nc4nk38j30v607q3zh.jpg](https://ws3.sinaimg.cn/large/006tKfTcgy1fq5nc4nk38j30v607q3zh.jpg)

按照官方文档中的安装流程操作，完成后有错误信息。

尝试安装 polyfill 和 安装 runtime 包后，错误信息未消失。

**Comment by fudiwei** [comment]
#1197 同样的问题
