### ISSUE TITLE
import  wxs 文件自动添加了.js导致报错

### ISSUE THREAD

**Issue by supwjm** [Tencent/wepy#1196]
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
按文档写了wxs 文件，但在组件文件中引入的时候自动附加了 .js 导致如下报错： 
Error: module "wxs/wxsTools.wxs.js" is not defined

尝试配置wepy.config.js 的 resolve.extensions : false 和["*",'.js'] , ["",'.js'] ，仍然出现相同的报错。

## Environment

  * Wechat version: 在微信小程序开发工具上报的错
  * wepy-cli version : 1.7.2
  * wepy version:1.6.0

  
## Reproduce

  [如何重现问题]
  
 按文档，创建wxs文件夹，在创建wxs文件，在page组件文件中引入，编译的时候就报错了，自动添加了.js 导致找不到文件

  ```

**Comment by insub** [comment]
@supwjm 请问解决了么？

**Comment by supwjm** [comment]
没解决，wepy发现其他坑，转向mpvue了

**Comment by gonghao** [comment]
刚从坑里爬出来，需要仔细检查一下 `import` 以及 `wxs = { xxx }` wepy 的原理是从 wpy 文件分析 `script` 里面的 wxs 依赖，然后动态修改，在最终生成的 wxml 里面插入 `<wxs module="xxx">` 的语句，然后在原来的 js 文件里面，注释掉相关 `.wxs` 的 `import` 语句

**Comment by iniself** [comment]
这个问题现在解决了吗？我现在也遇到了

**Comment by iniself** [comment]
解决办法是必须要import 和 wxs={}同时存在，如果只存在import那就会加.js后缀

**Comment by Thinking80s** [comment]
这个问题现在解决了吗？我现在也遇到了

**Comment by Thinking80s** [comment]
解决办法是必须要import 和 wxs={}同时存在

**Comment by Vector-Hope** [comment]
> 解决办法是必须要import 和 wxs={}同时存在

你好，请问一下，wxs={}是什么，怎么写这个
