### ISSUE TITLE
write Promise is not allowed when using plugins at app.json.

### ISSUE THREAD

**Issue by tolerance-go** [Tencent/wepy#1197]

**Comment by fsy0718** [comment]
同样的问题，更新开发者工具到 1.02.1803210后产生的
![image](https://user-images.githubusercontent.com/3926479/38492318-1fdd0598-3c21-11e8-8210-37a895da29c3.png)

**Comment by Inori-Lover** [comment]
暂时以我的渣渣分析来看，原因是ap.js中拿不到window？（this和window都是undefined）

**Comment by tolerance-go** [comment]
我的版本 1.02.1804090

**Comment by Inori-Lover** [comment]
确实是this拿不到……

**Comment by fudiwei** [comment]
开发者工具升级到 1.02.1804090 后出现的问题。

``` javascript
import 'wepy-async-function';
```

如果没用到 async/await 的话，把这句注掉就好了。

**Comment by qinshou** [comment]
同样的问题

**Comment by GitHubAFeng** [comment]
+1
求解

**Comment by 2534290808** [comment]
我也遇到同样的错误

**Comment by 2534290808** [comment]
+1求解

**Comment by PharrellWANG** [comment]
+1求解

**Comment by Gcaufy** [comment]
```
npm i wepy-async-function@1.4.6 --save
wepy build --no-cache
```

**Comment by Serif-x** [comment]
上面的办法貌似相比以前判断了一下环境

```javascript
var g = require('./global');

if (!g.Promise) {
  // IOS 10.0.1 may cause IOS crash.
  g.Promise = require('promise-polyfill');
}
if (!g.regeneratorRuntime) {
  g.regeneratorRuntime = require('regenerator-runtime/runtime');
}
```

但同样的问题是，之前的 `.prototype.prototype['finally']` 语法还是不能使用了

**Comment by taichenglu** [comment]
+1 使用第三方插件会报这个错

**Comment by Gcaufy** [comment]
@Serif-x 目前 Promise.protpery.finally 还在 stage4 的阶段：https://github.com/tc39/proposal-promise-finally
。因此要在原生使用时，可能还需要加个这个。
https://github.com/es-shims/Promise.prototype.finally

**Comment by Serif-x** [comment]
@Gcaufy 感谢，之前在 `wepy-async-function` 貌似已经包含了这个 shim 了，部分代码里面使用了 `finally` 也没问题，之后小程序开发工具更新后 **`Promise` 无法写入**（non-writable），任何 shim 也无效了。

之后 `wepy-async-function`  库增加了环境判断 `if (!g.Promise) {}` ，暂时修复了**报错的问题**，但同时 `finally` 也无法使用了，我只好放弃 `finally` （主要是这个太好用了😆 ）。

最近小程序开发工具又更新了（但没看到更新日志），好像可以 write `Promise` 了， `wepy-async-function`  库环境判断 `promise-polyfill` 可以恢复了？因为感觉再引用 `Promise.protpery.finally` 好像有点冗余，`promise-polyfill` 已经包含了 `finally` 的 shim 。

感谢交流，生活愉快 😄
