### ISSUE TITLE
wepy-cli@1.7.2-alpha2 compile-wpy 编译异常 usingComponents 失效

### ISSUE THREAD

**Issue by jinasonlin** [Tencent/wepy#1201]
## Description
![image](https://user-images.githubusercontent.com/5010606/38540793-a8d246e8-3ccf-11e8-9209-39c5cb0eff40.png)

wepy-cli latest 指向了 '1.7.2-alpha2'。

wepy-cli@1.7.2-alpha2 中 compile-wpy 处理 `config.usingComponents` + `components`存在问题，两个数据共存时会导致 `usingComponents` 内容丢失。

## Environment

  * Platform: *
  * Platform version: *
  * Wechat version: *
  * wepy-cli version: 1.7.2-alpha2
  
  
### Expected Results

考虑将 latest 指向到早期版本，或兼容`config.usingComponents` + `components`

**Comment by Gcaufy** [comment]
Fixed, Thanks.

```
npm dist-tag ls wepy-cli | grep latest
```
