### ISSUE TITLE
无法给wepy.component创建的自定义组件绑定监听函数

### ISSUE THREAD

**Issue by panjiangyi** [Tencent/wepy#1202]
## Description

无法给wepy.component组件绑定监听函数，在标签里写下@tap="handle"无效。
```html
<customComponent @tap="handle"/>
```
  [Description of the issue]

## Environment

  * Platform: 开发者工具
  * Platform version: v1.02.1803210
  * Wechat version: [微信版本号]
  * wepy-cli version: 1.7.1
  * wepy version: "^1.6.0"
  
## Reproduce

  [如何重现问题]
  绑定tap事件监听函数就行了
### Observed Results
 绑定了没反应

**Comment by phillyprr** [comment]
用法错啦，看一下 文档，如果是想事件传递组建的数据可以在组件里面绑定tap传递到父组件做处理

**Comment by Gcaufy** [comment]
```
<customComponent @tap.user="handle"/>
```

然后在子组件中
```
this.$emit('handle')
```
