### ISSUE TITLE
新建项目权限问题

### ISSUE THREAD

**Issue by JingLiii** [Tencent/wepy#1203]
## Description

1. 新建项目使用命令: `wepy init empty wx-test`
2. 未给sudo权限, 报错: `downloading template   wepy-cli · Failed to download repo empty: EACCES: permission denied, mkdir '/Users/zhangrh/.wepy_templates/empty'`
3. 使用sudo新建项目: `sudo wepy init standard wx-test`
4. 项目新建成功, 但是项目文件夹, 的所属者 变为 `root`. 编辑器保存有问题
5. 我认为每一次新建项目后, 再使用命令更改文件夹权限, 是不合理的.

## Environment

  * Platform: mac vscode 
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v] 1.7.2-alpha2
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  每次新建项目 都会有这个问题

### Observed Results

  [实际表现]
  
新建项目需要 sudo权限,  新建后, 文件夹所属者更改.
  
### Expected Results

  [期望表现]
  
  不需要sudo权限即可新建文件夹
  
[尴尬截图](http://oy3ywgz62.bkt.clouddn.com/1.png)

**Comment by Gcaufy** [comment]
init 需要的权限只有两个：
1. ~/.wepy_templates
2. 当前init执行的目录

为什么会没有 `/Users/zhangrh/.wepy_templates/empty` 的创建权限呢？
User 没有~/ 的权限是不是不太合理呢？
如果没有当前执行目录的权限 ，那么为什么要以当前 user 的身份去 init 呢？既然是 sudo 去 init 那为什么又要把权限改成 user呢？

所以这里应该还是自己的目录权限出了问题。
