### ISSUE TITLE
tap事件传参数据丢失的问题

### ISSUE THREAD

**Issue by AkbarOsman** [Tencent/wepy#1204]
### 代码
```
...
<a @tap="onActionTap('{{testAction}}')">{{testAction.text}}</a>
...
computed = {
  testAction() {
  return {
    text: '是',
    data: 'positive',
    onTap: () => {
       console.log('on positive tap');
      }
   };
 }
};
methods = {
  onActionTap(action) {
     console.log(this.testAction);   //有onTap
     console.log(action);   //无onTap
  }
};
```
### 目的
想在a标签被点击的时候，把data(或者computed，或者props)里的testAction以参数的方式传到methods里的onActionTap函数中，然后再调用接收到的action的onTap方法。
### 结果
万万没想到，onActionTap接受的action里居然没有onTap这个属性！！！于是我在onActionTap里打印了data里的testAction和收到的action，就差onTap属性，是不是因为onTap是函数类型，才导致这样的结果吗？还是别的原因？望各位大神开导开导我啊!!!!
这已经是我使用这个框架遇到的第二个大Bug啦，我的项目还能不能继续下去！！！！

**Comment by Gcaufy** [comment]
```
<a @tap="onActionTap({{testAction}})">{{testAction.text}}</a>
```

`testAction` 是一个对象，那就不要加引号了

**Comment by AkbarOsman** [comment]
@Gcaufy 我试了一下你说的，结果还是没变
![qq 20180411154034](https://user-images.githubusercontent.com/11870024/38602974-f7a3fc60-3d9e-11e8-82fa-ccff440af8cd.png)
