### ISSUE TITLE
小程序版本库和 wepy 中使用 Promise 冲突问题

### ISSUE THREAD

**Issue by jessjava** [Tencent/wepy#1205]
## Environment

  * Platform: [开发者工具/iOS/Andriod/Web] ：微信开发者工具
  * Platform version: [对应工具或者iOS或者Andriod的版本号] ： ios11.3
  * Wechat version: [微信版本号] ：ios 6.6.6
  * wepy-cli version: [wepy-cli -v] ：1.7.1
  * wepy version: [在package.json里] 1.7.1
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
1. 安装完wepy-cli(1.7.1) 
2. wepy init standard projectname
3. cd projectname  & wepy build -w
4. 微信开发者工具打开 projectname/dist
5. console控制台 会报错，错误信息：
 `VM54:1 [non-writable] write Promise is not allowed when using plugins at app.json.`
6. 微信‘调试基础库1.9.3以下（不含）没有此问题

### Observed Results

 微信‘调试基础库1.9.3以上（含）wepy 编译后报promise 错误：
`[non-writable] write Promise is not allowed when using plugins at app.json.`

### Expected Results

  [期望表现]
1.  希望说明一下原因；
2. 为什么wepy在1.4.1以后的版本，需要用户手动加入promise-polyfill
3. 现在的 wepy 中 promise 如何设计的？官方文档严重落后，无法查找具体文档

**Comment by jingxinxin** [comment]
更新 wepy-async-function 到最新版本
yarn outdated
yarn upgrade

**Comment by jessjava** [comment]
可以了。感谢！
我的疑问：
现在 init 的 demo项目都会有问题，而且文档进度又跟不上。
感觉 wepy 的版本升级和维护线路不是很清晰。
