### ISSUE TITLE
安装 wepy -cli 报错

### ISSUE THREAD

**Issue by heda20** [Tencent/wepy#1206]
C:\Users\31447>npm install wepy-cli -g
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! path C:\Users\31447\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\.lodash.DELETE
npm ERR! code ENOTEMPTY
npm ERR! errno -4051
npm ERR! syscall rmdir
npm ERR! ENOTEMPTY: directory not empty, rmdir 'C:\Users\31447\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\.lodash.DELETE'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\31447\AppData\Roaming\npm-cache\_logs\2018-04-11T10_27_20_998Z-debug.log

**Comment by Gcaufy** [comment]
升级一下node 和 npm 再试试

**Comment by heda20** [comment]
谢谢已解决。因为是第二次安装，而nodes_modules中.lodash.DELETE文件一直删除不掉造成的。获取系统最高权限强制删除，才安装成功。
