### ISSUE TITLE
基于 redux 的数据管理方案

### ISSUE THREAD

**Issue by tolerance-go** [Tencent/wepy#1209]
https://github.com/tolerance-go/wepyx
作者有空看一下嘛 个人的项目 希望得到更多建议
可以加入 wepy-cli 里面吗

**Comment by Gcaufy** [comment]
这个是基于wepy-redux实现的类似vuex的语法规范吗？

如果是想加入模板的话，可以pr 这里  https://github.com/wepyjs/wepy-templates

**Comment by tolerance-go** [comment]
语法参考了dva和vuex两者
readme里面的使用方法就是对标准redux模板的修改教程，所以就不提pr了，感谢解答
