### ISSUE TITLE
wepy-com-toast sdk uncaught error

### ISSUE THREAD

**Issue by zfan40** [Tencent/wepy#1210]
毫无头绪的一个错误。。。
thirdScriptError 
 sdk uncaught third Error 
 require(...).default.$createComponent is not a function 
 TypeError: require(...).default.$createComponent is not a function
    at http://127.0.0.1:54652/appservice/npm/wepy-com-toast/toast.js:164:52
    at require (http://127.0.0.1:54652/appservice/__dev__/WAService.js:17:28101)
    at http://127.0.0.1:54652/appservice/appservice:1289:9

src里面把所有toast相关都删了，查了下相关说wepy-com-toast是一定自带的
貌似是升级了一下alpha1出现的问题

**Comment by fengxinming** [comment]
你应该删掉dist里面的内容，编译的时候经常出现这种错误

**Comment by zfan40** [comment]
@fengxinming 还真是。。。感谢

**Comment by zhangaofei** [comment]
请问一下这个是2.x中用wepy-com-toast组件出的错吗，我发现在2.x里面没法用这个组件，发现这个组件用道1.想的this.invoke方法，但是2.x不支持这个了，怎么解
