### ISSUE TITLE
wepy.request在new Promise的回调函数中出现BUG

### ISSUE THREAD

**Issue by fengxinming** [Tencent/wepy#1211]
## Description

  当使用new Promise包裹wepy.request时，reject之后依然进入then的第一个方法，而且得到的值为undefined

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: 1.7.1
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  使用new Promise包裹wepy.request，当接口返回非200的状态码，reject返回的信息，然后就会进入then的第一个方法，得到的第一个参数为undefined

### Observed Results

  [实际表现]
  
  Promise之后进入then的第一个方法
  
### Expected Results

  [期望表现]
  
  进入then的第二个方法，或者catch
  

## Relevant Code / Logs

  ```
function request(options = {}) {
  return new Promise((resolve, reject) => {
    if (options.mask) {
      gloading.start();
    }
    // ... 其它处理
    
    wepy
      .request(options).then((res) => {
        if (res.statusCode === 200) {
          resolve(res);
        } else {
          if (options.toast) {
            wx.showToast({
              icon: options.toast.icon,
              title: res.data.message,
              duration: options.toast.duration
            });
          }
          reject(res);
        }
      }).catch((err) => {
        if (options.mask) {
          gloading.stop();
        }
        err.data = err;
        err.statusCode = -1;
        reject(err);
      });
  });
};

request( ... ).then(res => {
  // 当接口报错我reject之后，还会进入到这里，但是这个res确实undefined
}).catch(res => {
  // 竟然进入到这个函数中
});
  ```

**Comment by GitHubAFeng** [comment]
我也是碰过这个问题，后来用 干脆全用await async

**Comment by fengxinming** [comment]
@GitHubAFeng 这个怎么在redux里面加，我刚用redux

**Comment by Gcaufy** [comment]
Promise 的用法 还是有一些问题的。。。

```
function request(options = {}) {
   // do something else
   return wepy.request().then(res => {
      if () {
         retrun res;
      } else {
         throw 'err'
      }
   })
}
```

另外上面的问题看起来更多的是代码问题，哪里出了问题还是得自己调试一下看看了

**Comment by fengxinming** [comment]
@Gcaufy 问题还没解决就关掉，这样不好吧。你没发现我外面包了一层Promise，我是用外面的那个promise去reject，你这个不是解决问题，是更换我的代码呀

**Comment by Gcaufy** [comment]
@fengxinming 

抱歉，issue有些多。
我是说 你的 prmoise 的用法不太对，这样写只会让代码更不好读，所以建议换个写法。
至于 issue 本身，从代码来看我并没有看出有什么问题，而且 这似乎是Promise的一个用法的问题，与小程序，或者与 wepy 有什么关系，所以关掉了。

这个问题最好的办法就是自己断点调试一下，看看 wx.request 是走的 success 还是 fail。

**Comment by fengxinming** [comment]
@Gcaufy 行吧，暂时先这样解决，用Promise.reject先处理。我那种Promise使用绝对没有问题，也很好阅读，而且new Promise之后还有作用域隔离的效果

**Comment by Gcaufy** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

或者提供一个类似的代码片段方便我来调试一下，看看问题所在

**Comment by fengxinming** [comment]
@Gcaufy 刚刚离职，代码在原公司不好重现，我下午自己写了demo没有重现，以后再复现我就按照这种代码片段的方式发出来

**Comment by chenillen** [comment]
> 我也是碰过这个问题，后来用 干脆全用await async

在redux裡不能用 async/await 吧？
