### ISSUE TITLE
wepy build --no-cache后文件体积剧增，从600kb到3.4M...

### ISSUE THREAD

**Issue by shangdev** [Tencent/wepy#1215]
使用了组件echarts，源文件echarts.js文件体积只有600Kb，但是wepy build --no-cache后再dist下面的echarts.js体积竟然达到了3.4M，，

很纳闷，，怎么解决？

**Comment by Gcaufy** [comment]
是不是开启了sourcemap? 打开文件看一看，到底是什么内容导致文件那么大吧。

**Comment by shangdev** [comment]
@Gcaufy 
编译后的文件尾部确实有sourceMappingURL，，这个该如何关闭呢，，首次编译后没有sourceMappingURL，以后编译就会有这个了，，

**Comment by Gcaufy** [comment]
先手动删除 sourcemap。
然后再看看 wepy.config.js 中的 sourcemap 的配置项是不是打开了

**Comment by Gcaufy** [comment]
```
npm i wepy-compiler-babel@1.5.3 --save-dev
wepy build --no-cache
```
忽略超过大于500kb 的文件的编译

**Comment by Gcaufy** [comment]
https://github.com/ecomfe/echarts-for-weixin/issues/203

**Comment by BoleLee** [comment]
关闭 sourceMap 可以解决echarts.js打包后文件体积巨大的问题，但这样不就意味着，如果引入整个echarts包，就不能使用sourceMap了
