### ISSUE TITLE
引入了一个图表组件库（echarts），我想使用selectComponent()选择组件，提示not defined!

### ISSUE THREAD

**Issue by shangdev** [Tencent/wepy#1216]
引用了组件库echarts 小程序版本，现在需要使用selectComponent()这个api,但是提示未定义，那么在wepy中该如何选择该组件呢？

看到有的文档说用this.$wxPage.selectComponent()，但是依然会提示：Uncaught (in promise) TypeError: this.$wxpage.selectComponent is not a function

**Comment by shangdev** [comment]
问题已解决!
使用config的usingComponents引入组件：
`
<template>
    <view class="container">
        <ec-canvas id="ec-dom" canvas-id="ec" ec="{{ ec}}"></ec-canvas>
    </view>
</template>
<script>
export default class Index extends wepy.page {
  config = {
      navigationBarTitleText: '首页',
      usingComponents: {
        'ec-canvas': '../../ec-canvas/ec-canvas'
      }
    };
}
</script>
`
实例化组件的方式：
this.$wxpage.selectComponent('#组件id（上面的ec-dom）')

**Comment by Gcaufy** [comment]
https://github.com/ecomfe/echarts-for-weixin/issues/7#issuecomment-390092922
