### ISSUE TITLE
导入uuid的时候由于缺少某些模块导致报错

### ISSUE THREAD

**Issue by MofiU** [Tencent/wepy#1221]
## Description

  import uuid的时候，没有将rng.js自动打包到dist/npm文件夹内，导致报错
  
## Environment
  * wepy version: 1.7.0

## Reproduce
  
  import { v4 } from 'uuid'
  let value = v4()

### Observed Results
  `
  VM45:1 thirdScriptError 
  sdk uncaught third Error 
  module "npm/uuid/lib/rng.js" is not defined 
  Error: module "npm/uuid/lib/rng.js" is not defined]
`
dist/npm 目录下只有如下文件
- uuid
  - lib
    - bytesToUuid.js
  - v4.js
  - index.js

v4.js 第一行代码 ```var rng = require('./lib/rng.js');```
缺少必要js模块导致报错

不清楚是我个人问题，还是大家都有。

**Comment by notedit** [comment]
有遇到类似的问题,  wepy build 的时候node_module 下的依赖copy到npm目录下  copy不全

**Comment by Gcaufy** [comment]
编译报错了吧。
这个模块依赖于 crypto， 而 crypto 在小程序端不可用
