### ISSUE TITLE
wepy 卸载页面后自定义属性值没有销毁

### ISSUE THREAD

**Issue by 9wenzi** [Tencent/wepy#1222]
## Description

   1.在 wepy 中 unLoad 页面不能完全卸载页面吗？我发现：从a页面 -- > b页面 ，b页面中存在自定义属性，该属性被修改后，返回 a 页面， 再次 从 a 页面 进入 b  页面 ，此时打印出 b页面的自定义属性不是初始值，而是被修改过的值， 用原生的小程序中，同样用以上步骤进入，自定义属性则不会存在这个问题。
    2.有没有可以在页面 unLoad 后，再次进入时，让自定义属性是初始值的方法，（目前我临时用的是页面在unLoad时，手动让自定义属性重置为初始值）。

  
  [Description of the issue]

## Environment

  * Platform: [开发者工具]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * wepy version: [1.7.1]

  
## Reproduce

  [如何重现问题]
  1.有两个页面 page A、page B, 其中 page B 有自定义属性';
  2.从 page A ==> page B, 打印 自定义属性;
  4.随后 page B 对自定义属性修改;
  5.page B 点击左上角 返回  page A;
  6.再次从 page A ==> page B;
  7. 再次打印 page B 自定义属性
 
  

### Observed Results

 再次打印的结果是 page B 的自定义属性 是修改过的值，而**不是初始值**
  
  
### Expected Results

  [期望表现]
  
在原生小程序中，页面返回，该页面会被卸载，再次进入，页面的自定义属性的值是初始值，wepy 页面 卸载之后 再次进入 ，自定义属性应该遵循这个逻辑，其值应该为初始值
  

## Relevant Code / Logs
  page A:
  ```
<navigator url="../pageB/pageB" >跳转</navigator>
  ```
page B:
```
import wepy from 'wepy'

  export default class PageB extends wepy.page {
    config = {}

    onLoad() {
    //打印 自定义属性
      console.log(this.customData.flag)
    }

    onShow() {
      if (!this.customData.flag) return

      //修改自定义属性
      setTimeout(() => {
        this.customData.flag = false
      }, 2000)
    }

   //自定义属性
    customData = {
      flag: true
    }
  }

```

**Comment by Gcaufy** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

能否提供一个类似的代码片段方便我来调试一下

**Comment by 9wenzi** [comment]
[wechatide://minicode/aHImvJm163Yn](url)

**Comment by nxboo** [comment]
遇到同样问题，wepy1.7.1

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/issues/1092

**Comment by Gcaufy** [comment]
需要要unLoad中进行手动销毁。
