### ISSUE TITLE
wepy 不支持 原生微信小程序自定义组件的 externalClasses 

### ISSUE THREAD

**Issue by byg** [Tencent/wepy#1227]
原生微信小程序自定义组件的 externalClasses 这个外部样式在 wepy 的自定义组件中无法使用,是不支持吗

**Comment by byg** [comment]
测试发现可以直接使用 pages 目录下的样式，也就是说没有了原生的样式引入限制问题了

**Comment by ManbasJi** [comment]
> 测试发现可以直接使用 pages 目录下的样式，也就是说没有了原生的样式引入限制问题了

请问这个是怎么使用
