### ISSUE TITLE
wepy build --watch 在微信开发工具报3处错误

### ISSUE THREAD

**Issue by afacode** [Tencent/wepy#1233]
wepy 版本   1.7.2-alpha2
wepy build --watch  以后 用微信开发者工具打开 dist文件目录
报3处错误
Cannot read property 'Promise' of undefined 
 TypeError: Cannot read property 'Promise' of undefined
    at http://127.0.0.1:49851/appservice/npm/wepy-async-function/index.js:14:7
    at require (http://127.0.0.1:49851/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:49851/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:49851/appservice/app.js:23:1
    at require (http://127.0.0.1:49851/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:49851/appservice/appservice:1034:9

Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (http://127.0.0.1:49851/appservice/npm/wepy/lib/base.js:144:27)
    at http://127.0.0.1:49851/appservice/pages/index.js:244:51
    at require (http://127.0.0.1:49851/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:49851/appservice/appservice:1038:9

pages/index.js 出现脚本错误或者未正确调用 Page()

我看好像是npm包问题，但是在npm install 时候是完好的

**Comment by Gusvily** [comment]
我也遇到同样的问题了，请问解决了吗

**Comment by kala888** [comment]
```
npm i wepy-async-function@1.4.6 --save
```

**Comment by cobola** [comment]
https://github.com/Tencent/wepy/issues/1200
https://github.com/Tencent/wepy/issues/1152?_pjax=%23js-repo-pjax-container
这两个都看了 没找到解决办法 :(
