### ISSUE TITLE
某些情况下wepy不触发数据检查

### ISSUE THREAD

**Issue by Zertu** [Tencent/wepy#1234]
某些情况下绑定的数据变化之后，不会触发数据检查

## Environment

  * Platform: 开发者工具
  * Platform version: [1.02.1804120]
  * wepy-cli version: 1.7.1
  * wepy version:1.6.0
  
## Reproduce

  ```

  <style lang="less">
.userinfo {
  display: flex;
  flex-direction: column;
  align-items: center;
}

</style>
<template>
  <view class="container">
      <input class="weui-input"  value="{{price}}" type="digit" @blur="inputP"/>
  </view>
</template>
<script>
import wepy from 'wepy'

export default class Index extends wepy.page {
  data = {
    price: 0
  };
  methods = {
    inputP(e) {
      console.log(e.detail.value)
      this.price=Number(e.detail.value).toFixed(2) 
    }
  }
}
</script>
```
### Observed Results

  第一次离开焦点后可以实现小数点四舍五入，之后如果输入的值是舍去，比如1.1111111，则不会修改值
  
### Expected Results

  输入1.111111后应该变为1.11

**Comment by Gcaufy** [comment]
加一行
```
return this.price
```
试试

**Comment by Zertu** [comment]
@Gcaufy  没有用

**Comment by xixilive** [comment]
碰巧在看WePY文档, 异步回调没有触发脏检查吗?, 试试`this.$apply()`

**Comment by Zertu** [comment]
@xixilive 首先这不是异步，而且你可以输入1.555555555，这个时候是正常工作的

**Comment by zhouweiming** [comment]
tofixed后，price就变成了字符串，可能类型改变后，就不触发了，我碰到一个类似的就是把一个对象改成null，就不会触发检查，即使我用了$apply也不触发，如果只是触发对象的某个属性，就完全正常，所以我猜可能跟类型有关系。

ps：真不明白，小程序抄的vue，为啥就折腾出了个$apply这种很ng1的方式

**Comment by xixilive** [comment]
不敢苟同wepy的做法，况且wepy的packages测试太少，不敢陷入太深呐

**Comment by lihuangshuaige** [comment]
怎么解决?遇到同样的问题

**Comment by lihuangshuaige** [comment]
加个setTimeout  亲测可行

**Comment by lihuangshuaige** [comment]
就是加个字母  强行触发数据检查  在setTimeOut一下  把加的字母去掉

**Comment by forMine** [comment]
状态不更新的问题无解了吗？？？同一个页面多次进入，页面状态改变了，可实时打印，但是UI不渲染，不会触发数据的检查。。。某些机型才会有。。。
