### ISSUE TITLE
在less中使用calc 函数时，会自动转化！！！【重要】

### ISSUE THREAD

**Issue by cielu** [Tencent/wepy#1240]
## Description

在less中使用函数时，会自动给计算出来值，转换掉函数。。。【bug】

## Environment

  * Platform: [最新版]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [1.7.1]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce
这是我在wepy中写的

  ```
<style lang="less">
    .style {
        width: calc(100% - 20rpx);
    }
</style>
  ```
### Observed Results
这是它生成出来后，我在对应的wxss文件中看到的

    .style {
        width: calc(80%);
    }
  
### Expected Results

    .style {
        width: calc(100% - 20rpx);
    }

## Relevant Code / Logs

日志就算了，就是一个样式中使用函数会被格式化掉的问题

**Comment by cielu** [comment]
#340 找到了解决方案

**Comment by ccerlc** [comment]
这个是less-loader编译器的问题 加上 ~即可
