### ISSUE TITLE
template里面该如何调用methods里面定义的方法，新手求指引下

### ISSUE THREAD

**Issue by agikoo** [Tencent/wepy#1243]
![image](https://user-images.githubusercontent.com/696429/38985008-cbcd021e-43fa-11e8-8d5e-77ae696c0cfc.png)

这是演示的代码，但是在微信开发者工具中显示的是空白，{{item}}能正常输出，但是{{moment(item).format('MM.DD')}}不行

**Comment by forMine** [comment]
methods中的方法在页面执行必须要绑定到事件上去触发，写到methods外部去掉用执行。

**Comment by Gcaufy** [comment]
小程序自身限制，{{}}中不能直接调逻辑层的方法。
建议换成`computed`的实现。

**Comment by iamlaobie** [comment]
在格式化输出的时候特别麻烦。。。
现在是创建一堆computed变量

**Comment by diamont1001** [comment]
用 wxs 就可以了：

```js
wxs = {
  filter: {
    format: function(s) {
      ....
    }
  }
}
```
