### ISSUE TITLE
customData在页面销毁后没有被销毁

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#1249]
举例：页面X -> 页面a
页面a，有个customData为loadFinish=false。当页面a调用onShow时，将loadFinish设置为true。
回退到页面X，再进入页面a。在a页面onLoad里打印发现loadFinish已经是true了。

**Comment by simdd** [comment]
小程序视图层跟逻辑层完全分离，跳转前对js逻辑在页面跳转后，也会继续执行，这是原生小程序`特性`，页面跳转的时候自己手动清理一下吧

**Comment by nishino-tsukasa** [comment]
这个我知道，可能你弄反了我的意思，我这个是X -> a 再回退到 X -> a。是a里面的数据，在a 回退到 X的时候，a实例应该已经被释放了吧。
如果页面a：loadFinish不是customData而是在data里面，就不会有这个问题哦。

**Comment by simdd** [comment]
`a实例应该已经被释放了吧`, a实例没有被释放，页面重新load，data会reset，但自定义的数据，包括import进来的js库，他们都还在继续运行。

**Comment by nishino-tsukasa** [comment]
好的，谢谢
