### ISSUE TITLE
顶部导航乱跑

### ISSUE THREAD

**Issue by zhouweiming** [Tencent/wepy#1250]
## Description

在页面上放置一个在底部的input输入框后，点击输入框，如果显示了底部导航，则顶部导航条会跑到页面中间，如果没有显示，一切正常

## Environment

  * Platform: iOS
  * Platform version: iOS11.3
  * Wechat version: 6.6.6
  * wepy-cli version: 1.7.1
  * wepy version: 1.6.0

##Codes:
```	
	<style lang="less">
        input {
       	        display: block;
         	width: 100%;
         	height: 20px;
         	border: 1px solid red;
         	margin-top: 1600rpx;
    	}
    </style>
    <template>
    	<input type="text" />
    </template>
    <script>
      	import wepy from 'wepy'
      	export default class Room3 extends wepy.page {}
   </script>
```

**Comment by Gcaufy** [comment]
这个应该是原生问题，input是原生组件，会产生各种奇异的表现。

**Comment by zhouweiming** [comment]
@Gcaufy 应该是小程序在有底部导航的情况下，顶部导航在启动键盘后，页面自适应的bug
