### ISSUE TITLE
"wepy": "^1.7.2-alpha1",  使用原生组件创建自定义组件 并没有生成 json wxml  

### ISSUE THREAD

**Issue by tolerance-go** [Tencent/wepy#1252]
父组件内部
```js
 '@button': Button,
```

页面上只出现了一个 `<button></button>` 的占位

dist 内没有生成 button 的 json wxml

**Comment by tolerance-go** [comment]
之前的组件不能和repeat组合使用感觉连button的事件响应回调都复用不了，很鸡肋

**Comment by tolerance-go** [comment]
什么时候出来2.0 什么时候支持完善的动态自定义组件 求文档，求回应~

**Comment by px0078** [comment]
有解决吗，是不是要把Button改成原生的才能出来

**Comment by WynnLin** [comment]
请问有什么解决办法么， 现在我也遇到了这个问题
