### ISSUE TITLE
wepy.chooseLocation 回调不执行

### ISSUE THREAD

**Issue by zhangbuding** [Tencent/wepy#1256]
代码如下, 选取位置后, 控制台没有任何输出;
用 wx 前缀是可以的;
wepy 版本 1.60

  ```
    wepy.chooseLocation({
          success: (res) => {
            console.log(res)
          },
          fail: (res) => {
            console.log(res)
          }
        })
  ```

**Comment by Gcaufy** [comment]
promisify的原因？
试一下 wepy.chooseLocation().then(res => console.log(res));

**Comment by careCao** [comment]
不仅仅chooseLocation出现这个问题
uploadFile，requestPayment都出现该问题，使用wepy前缀，都不会执行回调

**Comment by Gcaufy** [comment]
@careCao 确认是否使用了 promisify, 如果使用了，那就需要使用 promise 的方式调用而不是 回调
