### ISSUE TITLE
项目中使用wepy build提示找不到编译器wepy-compiler-less

### ISSUE THREAD

**Issue by ttfather** [Tencent/wepy#1259]
找不到编译器wepy-compiler-less
![qq 20180423235311](https://user-images.githubusercontent.com/20608641/39138039-9f79d4e4-4751-11e8-9823-2dcf5915c730.png)

**Comment by dengbaoling** [comment]
npm 安装就可以了

**Comment by ttfather** [comment]
已解决，非常感谢 @dengbaoling
