### ISSUE TITLE
wepy.config.js中resolve.alias修改为~后报错

### ISSUE THREAD

**Issue by asins** [Tencent/wepy#1265]
## Description

在我的`wepy.config.js`文件中想把`resolve.alias`修改为~，因为这是我的一直以来的开发习惯。

但发现修改后wepy-cli就无法编译通过了。下面的配置能正常编译：

```js
resolve: {
  alias: {
    '@': path.join(__dirname, 'src'),
  },
  aliasFields: ['wepy'],
  modules: ['node_modules']
},

// in .js file is work
import Api from '@/model/api'
```

但当我修改为~后，就没办法编译通过了，报`ReferenceError: Api is not defined`

```js
resolve: {
  alias: {
    '~': path.join(__dirname, 'src'),
  },
  aliasFields: ['wepy'],
  modules: ['node_modules']
},

// in .js file is not work
import Api from '~/model/api'
```

## Environment

wepy-cli@1.7.1

**Comment by Wind4** [comment]
因为正则未能正确匹配替换包含“~”的路径。 
https://github.com/Tencent/wepy/blob/2.0.x/packages/wepy-cli/src/compile-script.js#L32 ，

![image](https://user-images.githubusercontent.com/3997851/39558602-900ba35c-4ec2-11e8-9e1c-4825875b8550.png)

**Comment by jackywq** [comment]
我按照你上面写的方式，在wepy.config.js写入resolve；
![tim 20180518114227](https://user-images.githubusercontent.com/21954704/40215080-f44ced6a-5a90-11e8-9cef-fe339b708ab6.png)


在我的组件里全局引用，结果编译时出错了, 大佬知道是什么原因吗？
![2](https://user-images.githubusercontent.com/21954704/40215085-f807184a-5a90-11e8-97e1-6392d27b437a.png)
![tim 20180518114244](https://user-images.githubusercontent.com/21954704/40215091-0a9cb898-5a91-11e8-96c2-fe441a5c223b.png)

**Comment by jackywq** [comment]
@asins

**Comment by asins** [comment]
看你最后一张截图，
```js
let ajax = require('/utils/request.js')
```

这里写的错了，因为你在`wepy.config.js`中定义的是`utils`，而不是`/utils`，所以正确的写法应该是

```js
let ajax = require('utils/request')
```

另外 .js后缀可以默认不写的

**Comment by jackywq** [comment]
恩，谢谢，这个问题我已经纠正了！ @asins
