### ISSUE TITLE
$broadcast事件传递问题

### ISSUE THREAD

**Issue by fitcong** [Tencent/wepy#1269]
条件
- page A
- 组件B  C
- 组件  D
A引用B和C    BC都引用D

表现
- A向D直接发送事件,D的事件会执行两遍

看了文档,发现是会循环下去的,但是$destory()不存在,怎么才能中断这个事件呢

**Comment by fitcong** [comment]
@Gcaufy 关键在与我处理的是一样的事件,但是会处理多次,会造成页面重复刷新

**Comment by MaxMooc** [comment]
我也遇到了，有解吗？

**Comment by Gcaufy** [comment]
判断 parent 是可行的。
另外天理论上 destroy 方法也是可以的。
