### ISSUE TITLE
引入第三方报错

### ISSUE THREAD

**Issue by smithyj** [Tencent/wepy#1272]
```
[Error] Error: 找不到模块: @babel/runtime/helpers/interopRequireWildcard
被依赖于: /Users/yyj/Docker/wwwroot/yangyj-wxapp/node_modules/dva-core/lib/index.js。
请尝试手动执行 npm install @babel/runtime/helpers/interopRequireWildcard 进行安装。
```

**Comment by smithyj** [comment]
项目地址：https://github.com/smithyj/yangyj-wxapp

**Comment by smithyj** [comment]
```
这两个依赖已经安装
@babel/runtime
babel-plugin-transform-runtime
```

**Comment by baqihg** [comment]
@smithyj 问题找到了，应该是webpack的玄学操作，在wepy.config.js中的resolve.alias 加一行
`'@babel': path.join(__dirname, 'node_modules/@babel'),`
即可

**Comment by smithyj** [comment]
@baqihg 你引入dva成功了？

**Comment by smithyj** [comment]
引入成功之后 dva-core 有个依赖 然后有个 createTextNode 操作 蛋疼

**Comment by smithyj** [comment]
唉 webpack 被魔改太严重了

**Comment by smithyj** [comment]
转mpvue了

**Comment by baqihg** [comment]
@Gcaufy 请问下这个有解决方案么，引入dva的这个问题。

**Comment by linkdesu** [comment]
@smithyj 多谢指条明路，折腾几小时发现这东西 1.7.1 版问题太多，就算是官方钦定也没办法。相比而言 vuemp 只需要 `npm install` `npm run build` 立马项目就跑起来了！

**Comment by smithyj** [comment]
@linkdesu 腾讯这么大个团队 怎么就不能做好一个东西呢

**Comment by smithyj** [comment]
@linkdesu 主要是mpvue支持vuex 用起来太爽了

**Comment by YufJi** [comment]
@baqihg  引入dva实际上是需要引入dva-core  主要一个问题其实和引入redux-saga是一样的 们需要引入打包后的压缩文件 就OK了 详情可以参考一下我的方案


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by lili21** [comment]
这个问题解决了吗？

**Comment by Zronel** [comment]
9102年了  这个问题还存在

**Comment by smithyj** [comment]
> 9102年了 这个问题还存在

这么厉害 这个问题还存在？
