### ISSUE TITLE
更新到1.7.1后Error：找不到模块：util

### ISSUE THREAD

**Issue by popojja** [Tencent/wepy#1276]
初始化一个wepy 的时候：
npm install wepy-cli -g
yarn install
npm run dev

结果：
![image](https://user-images.githubusercontent.com/26264748/39288756-e729f1e6-495b-11e8-822e-aedf393bf728.png)

![5436546357](https://user-images.githubusercontent.com/26264748/39288968-ba8f32bc-495c-11e8-81f4-737373ed15d9.png)

**：之前也是这个步骤生成了项目并没有什么问题，这次是因为代码有过更新么？

**Comment by yy197133** [comment]
我也是同样的问题。。。

**Comment by acccco** [comment]
现在修复了这个问题了吗？装了个新包，结果一堆错，急啊

**Comment by yy197133** [comment]
@acccco 我刚用wepy upgrade wepy 升级了下wepy  就可以了，你试试，不行的话把.wepycache删掉，重新npm install ,wepy build

**Comment by wmwgijol28** [comment]
@yy197133 按照你说的操作之后,还是报错的

**Comment by acccco** [comment]
@yy197133 @wmwgijol28 反反复复删了好几次 node_module ，还是不行，但是如果不用 redux 的话就没问题，应该是 wepy-redux 里面的东西有问题，还好依赖 redux 不多，去掉没问题

**Comment by Ryuurock** [comment]
这个问题很严重啊    我都没办法启动起来

**Comment by tolerance-go** [comment]
暂时的解决方法

npm i util

wepy build --no-cache

**Comment by 1124953475** [comment]
第一次用这个，感觉创建个demo都是艰难不已。。各种报错

**Comment by Gcaufy** [comment]
这个问题实际是上因为lodash在4月份最近更新了一下，然后正好命中了wepy编译的一个bug

```
$ npm info lodash | 4.17
```

暂时来说最简单的解决办法是，还原lodash至 4.17.5的版本
```
npm i lodash@4.17.5 --save
```

**Comment by guotie** [comment]
靠，启动不了啊

**Comment by Gcaufy** [comment]
@kunkuntang @guotie 

```
npm i wepy-cli@1.7.2-alpha4 -g
```

**Comment by Same-time** [comment]
具体 什么时候能够修好这个bug？

**Comment by zybieku** [comment]
各位大佬的方法都用了,还没解决

**Comment by WangShuXian6** [comment]
我试了这样可以
```
npm i lodash@4.17.5 --save
wepy build --no-cache
```
如果还不行，就在 package.json 手动更改 lodash 版本号
```
"lodash": "4.17.5"
```

**Comment by Gcaufy** [comment]
修复已release
```
npm i wepy-cli@1.7.2 -g
```

**Comment by chenshishuo** [comment]
1.npm install util
2.删除.wepycache
3.npm run dev
