### ISSUE TITLE
内容太大，导致无法预览

### ISSUE THREAD

**Issue by moyaying** [Tencent/wepy#1279]
使用npm run dev开发调试，随着项目慢慢变大，提示超过2M，不能预览，这个怎么办呢？
能压缩一下吗？

**Comment by ymqq** [comment]
npm run build 出来的包也很大，大大超过源文件，js 与css是大头，希望可以再压缩 @

**Comment by ymqq** [comment]
@moyaying 你可以使用npm run build进行预览提交

**Comment by d393911462** [comment]
分包吧 我就是分包处理的

**Comment by moyaying** [comment]
@ymqq 那我开发的时候，就用npm run build的方式吗开发预览吗？

**Comment by d393911462** [comment]
@moyaying 不需要吧， 分包上限貌似是 4M 我现在总量 超过了2M 分包后 还是可以预览的

**Comment by d393911462** [comment]
@moyaying 用 uglifyjs 压缩一下js 效果很好啊， 我的项目直接从2.4M压缩到只有 1.1M了

**Comment by moyaying** [comment]
@d393911462 uglifyjs开发的时候，能自动开启吗，怎么开启呢

**Comment by d393911462** [comment]
@moyaying 可以 配置一下 默认是 发布的时候压缩

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/tree/2.0.x/packages/wepy-plugin-uglifyjs
