### ISSUE TITLE
真机预览报错，模拟器测试正常

### ISSUE THREAD

**Issue by dengbaoling** [Tencent/wepy#1282]
![_20180426180909](https://user-images.githubusercontent.com/17171011/39300051-060af51c-497d-11e8-93ab-8d7998da265d.png)

**Comment by dengbaoling** [comment]
有大佬们遇到吗？急

**Comment by ymqq** [comment]
app.wpy中没有配置页面，或者配置错了，检查一下。

**Comment by ymqq** [comment]
app.wpy中没有配置页面，或者配置错了，检查一下。

**Comment by kiccer** [comment]
我也遇到同样问题了，有解决了的吗？
