### ISSUE TITLE
Repeat动态数据临时解决办法

### ISSUE THREAD

**Issue by aokihu** [Tencent/wepy#1283]
Repeat中的组件似乎无法动态的获取数据，因此导致了computed没发使用，而onLoad的时候props还没有初始化，要实现动态改变repeat中组件的内容似乎变得非常困难。

要实现repeat中组件动态更新的办法，我临时找到一个，那就是在Page层级中对数据进行更新，而不是在component中对数据做出反应，对于数组这样的数据可以使用map，或者reduce进行二次处理，似乎，repeat中组件的数据都是延迟静态绑定的，因此你能修改的是组件上一级的数据源，不能对组件本身的数据修改

**Comment by px0078** [comment]
redux可以，不过我不能在repeat出来的组件里把数据再往下传

**Comment by chenshaonian** [comment]
我这边的处理方法是 把所有的子组件或者孙组件里面需要用到的数据，都在page 页面统一加工好，然后通过props 传进去。不知道还有没有其他更好的方法。

**Comment by songguangyu** [comment]
这个机器人不负责任啊

**Comment by aokihu** [comment]
我差，我那么辛苦给了大家解决方案，就给我closed了？
