### ISSUE TITLE
wepy 怎么跟web-view 组件进行交互？

### ISSUE THREAD

**Issue by 1peng** [Tencent/wepy#1285]
<script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.3.2.js"></script>

// javascript
wx.miniProgram.navigateTo({url: '/path/to/page'})
wx.miniProgram.postMessage({ data: 'foo' })
wx.miniProgram.postMessage({ data: {foo: 'bar'} })
wx.miniProgram.getEnv(function(res) { console.log(res.miniprogram) // true })

官方如上。但是在wepy上不好使

**Comment by Gcaufy** [comment]
这里并没有特殊处理。官方怎么用，那在wepy里也是这么用。不工作可能还是需要自己定位一下看看。这个问题应该和wepy无关
