### ISSUE TITLE
创建项目，微信开发工具首页报错

### ISSUE THREAD

**Issue by guotie** [Tencent/wepy#1289]
最新的版本 1.7.1

```
WAService.js:4 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'Promise' of undefined 
 TypeError: Cannot read property 'Promise' of undefined
    at http://127.0.0.1:57265/appservice/npm/wepy-async-function/index.js:14:7
    at require (http://127.0.0.1:57265/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:57265/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:57265/appservice/app.js:23:1
    at require (http://127.0.0.1:57265/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:57265/appservice/appservice:1034:9
```

```
WAService.js:4 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (http://127.0.0.1:57265/appservice/npm/wepy/lib/base.js:144:27)
    at http://127.0.0.1:57265/appservice/pages/index.js:243:51
    at require (http://127.0.0.1:57265/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:57265/appservice/appservice:1038:9
```

```
pages/index.js 出现脚本错误或者未正确调用 Page()
console.error
(anonymous) @ appservice:1042

```

**Comment by shiran1992** [comment]
me too

**Comment by jielanglang** [comment]
Looking at wepy development documents, you need to close some of the developer tools.

**Comment by zening0809** [comment]
When I after initialization program, open the home page error by wechat debugging tools

**Comment by guotie** [comment]
nice，关闭开发工具的一些选项就可以了

为什么会出现这样的问题呢？是wepy的bug还是开发工具的bug？

**Comment by shiran1992** [comment]
麻烦问一下，关闭哪些选项的。或许给个链接，谢谢啦！

**Comment by guotie** [comment]
![wx-dev](https://user-images.githubusercontent.com/42231/39503198-211d2b12-4df7-11e8-84bd-83d06dd67315.png)

**Comment by iwangx** [comment]
还是有问题啊。。。调试基础库2.2.0

**Comment by guotie** [comment]
@Gcaufy 
我的问题已经解决了，问问 @iwangx  具体是什么问题吧

感谢你的耐心回答。

**Comment by iwangx** [comment]
没问题了我的

**Comment by huiuhhui** [comment]
谢谢回答

**Comment by 316boss** [comment]
所有选项都关了，并且只有在启用了 promise 的时候才报错

**Comment by Ding-Fan** [comment]
In my situation, delete the `dist/` folder, delete `.wepycache` , problem solved.

**Comment by wcghhk** [comment]
webpack.base.conf.js 的 module 下加 noParse: [/ali-oss/]

**Comment by ghostsatan** [comment]
VM3283:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'userAgent' of undefined 
 TypeError: Cannot read property 'userAgent' of undefined
    at http://127.0.0.1:24190/appservice/common/vendor.js:6353:91853
    at e.version (http://127.0.0.1:24190/appservice/common/vendor.js:6353:91131)
    at http://127.0.0.1:24190/appservice/common/vendor.js:6353:91208
    at http://127.0.0.1:24190/appservice/common/vendor.js:6353:91043
    at http://127.0.0.1:24190/appservice/common/vendor.js:6353:91070
    at a (http://127.0.0.1:24190/appservice/common/vendor.js:6353:90595)
    at Object.<anonymous> (http://127.0.0.1:24190/appservice/common/vendor.js:6353:90599)
    at Object.t.exports.render.t (http://127.0.0.1:24190/appservice/common/vendor.js:6353:106445)
    at e (http://127.0.0.1:24190/appservice/common/vendor.js:6353:282)
    at Object.defineProperty.value (http://127.0.0.1:24190/appservice/common/vendor.js:6353:28029)



有没有人遇到我这个问题  mpvue开发小程序 引入高德地图

**Comment by lawler61** [comment]
> VM3283:1 thirdScriptError
> sdk uncaught third Error
> Cannot read property 'userAgent' of undefined
> TypeError: Cannot read property 'userAgent' of undefined
> at http://127.0.0.1:24190/appservice/common/vendor.js:6353:91853
> at e.version (http://127.0.0.1:24190/appservice/common/vendor.js:6353:91131)
> at http://127.0.0.1:24190/appservice/common/vendor.js:6353:91208
> at http://127.0.0.1:24190/appservice/common/vendor.js:6353:91043
> at http://127.0.0.1:24190/appservice/common/vendor.js:6353:91070
> at a (http://127.0.0.1:24190/appservice/common/vendor.js:6353:90595)
> at Object. (http://127.0.0.1:24190/appservice/common/vendor.js:6353:90599)
> at Object.t.exports.render.t (http://127.0.0.1:24190/appservice/common/vendor.js:6353:106445)
> at e (http://127.0.0.1:24190/appservice/common/vendor.js:6353:282)
> at Object.defineProperty.value (http://127.0.0.1:24190/appservice/common/vendor.js:6353:28029)
> 
> 有没有人遇到我这个问题 mpvue开发小程序 引入高德地图

我也是，请问下你解决了吗
