### ISSUE TITLE
出现#1276问题，使用里面的方法之后，无法实时编译……

### ISSUE THREAD

**Issue by liuqian1996** [Tencent/wepy#1295]
出现#1276问题后，使用了里面的临时方法，出现底部tabBar无法点击切换，而且好像vscode里保存后开发者工具没有编译，或者很卡…………

**Comment by liuqian1996** [comment]
![Uploading image.png…]()

**Comment by liuqian1996** [comment]
真机没问题，这是谁的问题……

**Comment by fengxinming** [comment]
把dist目录下的代码删掉重新编译就好了吧

**Comment by liuqian1996** [comment]
这样也只能保持一两次，和重开开发者工具一样，不知道是不是昨天更新了开发者工具的原因……
