### ISSUE TITLE
wepy如何获取全局唯一的版本更新管理器，用于管理小程序更新。

### ISSUE THREAD

**Issue by Ex-Caliburn** [Tencent/wepy#1299]
`const updateManager = wx.getUpdateManager()

updateManager.onCheckForUpdate(function (res) {
  // 请求完新版本信息的回调
  console.log(res.hasUpdate)
})

updateManager.onUpdateReady(function () {
  wx.showModal({
    title: '更新提示',
    content: '新版本已经准备好，是否重启应用？',
    success: function (res) {
      if (res.confirm) {
        // 新的版本已经下载好，调用 applyUpdate 应用新版本并重启
        updateManager.applyUpdate()
      }
    }
  })

})

updateManager.onUpdateFailed(function () {
  // 新的版本下载失败
})`

我该如何使用
wepy.getUpdateManager()
        .then((res) => {
          console.log(res)
        }).catch(err => {
          console.log(err)
        })

**Comment by adsjkqhaoran** [comment]
同求= =

**Comment by adsjkqhaoran** [comment]
找到解决方法了 用原生的写法 wx  
 let updateManager =  wx.getUpdateManager()
    console.log(updateManager, 'updateManager')
    updateManager.onCheckForUpdate(function (res) {
      // 请求完新版本信息的回调
      console.log(res.hasUpdate)
    })
虽然编译前没有wx变量 语法报错  但是仔细想想 编译完后环境里是有wx的 所以编译完后可以使用的
