### ISSUE TITLE
使用this.$apply()数据过大时，渲染很慢，会有好几秒（数据20多kb）

### ISSUE THREAD

**Issue by liling0726** [Tencent/wepy#1301]
机型：红米note3
微信版本：6.6.6
基础库：2.0.4
描述：this.$apply()渲染数据，数据越大，渲染时间越长，20多kb会有2s，甚至更长的渲染时间
代码片段：
this.townDetailList = townDetailList;
        this.townNavList[this.navIndex].list = townDetailList;
        this.$apply();

**Comment by Gcaufy** [comment]
尽量避免数据量过大，这个是setData本身的限制，比较麻烦

**Comment by wendycan** [comment]
你是不是用了老版本的 wepy-redux, 1.5.3 是有这个问题的，connect 的时候它把 store 放到了 this.data 里($state)，导致 data 更大了。升级 wepy-redux 到 1.5.9 就没有这个问题了。

**Comment by liling0726** [comment]
@wendycan 没有，就没有用wepy-redux，直接用的this.xxx=xxx

**Comment by sharpzhao** [comment]
It seems I got a similar problem. 
I'm wondering if you fixed this? 
@liling0726 Thanks.
