### ISSUE TITLE
使用async，await数据不是异步的时候，返回数据需要1s，甚至更长

### ISSUE THREAD

**Issue by liling0726** [Tencent/wepy#1302]
机型：红米note3
微信版本：6.6.6
基础库：2.0.4
代码：
let townDetailList = await indexApi.getTownListById(list, id）
描述：getTownListById里面某些条件直接返回数据，有时异步请求数据

**Comment by Gcaufy** [comment]
这个似乎与你的代码逻辑有关吧，看看异步请求是是不是接口吐数据太慢了？
