### ISSUE TITLE
components目录下的wpy组件不生成wxml

### ISSUE THREAD

**Issue by Wind4** [Tencent/wepy#1307]
## Description

  src/components目录下的*.wpy组件，没有生成对应的wxml文件。

![image](https://user-images.githubusercontent.com/3997851/39558153-e0c95f7c-4ebe-11e8-8828-71a8669464e9.png)

## Environment

  * wepy-cli version: 1.7.1

##  Logs
  
  经过Debug定位到了文件：

[https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy-cli/src/compile-wpy.js#L469](https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy-cli/src/compile-wpy.js#L469)

[https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy-cli/src/compile-wpy.js#L546](https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy-cli/src/compile-wpy.js#L546)

代码第469行判断路径里面出现components就当作component类型，第546行则忽略了component类型的wxml编译。

因为没有在文档找到相关描述，所以不确定是feature还是bug，麻烦确认一下。

**Comment by Wind4** [comment]
暂时的解决方案是把components文件夹改成其他名称，比如component。这样识别出来就是Other类型，可以编译出wxml文件。
![image](https://user-images.githubusercontent.com/3997851/39558278-d27ff81c-4ebf-11e8-9a87-fb845916efb3.png)

------
也许是我理解错了，component本身是没有template的？

**Comment by cdll** [comment]
same issue here~

**Comment by cdll** [comment]
same issue here~
