### ISSUE TITLE
demo 里面，更新components/list.wpy，没有更新父页面 pages/index.wxml

### ISSUE THREAD

**Issue by ylksty** [Tencent/wepy#1308]
## Description
1.demo 里面，更新components/list.wpy，没有更新父页面 pages/index.wxml，必须父页面也更新才会重新编译里面的list组件
2.index.wxml里，console.log(List)，发现是ListAnother，所以 template是components/list.wpy 的，script是components/wepy_list.wpy的

## Environment

  * Platform: [开发者工具]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * wepy version: [1.6.0]

**Comment by Gcaufy** [comment]
这样就对了。
这是aliasField的一个示例

https://github.com/wepyjs/wepy-templates/blob/master/templates/standard/template/package.json#L15
