### ISSUE TITLE
  Error: module "npm/web3/src/index.js" is not defined

### ISSUE THREAD

**Issue by changjiashuai** [Tencent/wepy#1314]
WAService.js:4 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token / 
 SyntaxError: Unexpected token /
console.error
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:1008
window.onerror
_wepylogs.js:1 WePY开启错误监控
WAService.js:4 thirdScriptError 
 sdk uncaught third Error 
 module "npm/web3/src/index.js" is not defined 
 Error: module "npm/web3/src/index.js" is not defined
    at require (http://127.0.0.1:51431/appservice/__dev__/WAService.js:18:26606)
    at http://127.0.0.1:51431/appservice/__dev__/WAService.js:18:26461
    at http://127.0.0.1:51431/appservice/pages/index.js:42:12
    at require (http://127.0.0.1:51431/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:51431/appservice/appservice:1227:9

**Comment by changjiashuai** [comment]
github: https://github.com/ethereum/web3.js
npm: https://www.npmjs.com/package/web3

**Comment by Gcaufy** [comment]
这个库依赖node端的net模块，应该是无法在小程序端使用的。

**Comment by changjiashuai** [comment]
有计划支持这块吗？
