### ISSUE TITLE
vagrant虚拟机环境下无法监听文件变动

### ISSUE THREAD

**Issue by majingtao** [Tencent/wepy#1316]
开发环境是mac + vagrant 虚拟机环境
运行wepy build --watch无法监听文件变动，之前webpack也有类似问题，设置
watchOptions: {  
  poll: true
} 可以解决 wepy 不知道怎么解决

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/blob/2a8ea50eb19d6becf8b1c3bfdef490c9ff7a53d4/CHANGELOG.md

1.7.0 中就已经添加了watchOption选项。
