### ISSUE TITLE
生产环境下怎么编译怎么去掉console.log

### ISSUE THREAD

**Issue by shiran1992** [Tencent/wepy#1318]
最近，在搭建一个微信小程序框架，可能会后续有频繁的业务需求，所以使用了wepy框架。一个星期来，也遇到了很多问题，不过都一一解决了。现在，又遇到了一个优化问题，就是我们开发过程中，会经常性了写“console.log('******')”；但是，这个东西多了，会引起内存泄漏问题，所以问一下，可不可以在生产编译阶段直接过滤掉这些。

**Comment by Gcaufy** [comment]
会引起内存泄漏这个没太理解 。

编译阶段过滤这个可以使用replace插件处理。

**Comment by shiran1992** [comment]
嗯，这个方法我考虑过，可是过滤的正则有点困难（我不太会写）。现在，直接
replace: [{
        filter: /\.js$/,
        config: [{
            find: 'console.log',
            replace: ''
        }]
    }]
直接将console.log替换成‘’，但是打印的内容依然没有去掉。请问，find里面怎么写才可以全部过滤呢？

**Comment by shiran1992** [comment]
其实换个思路依然可以解决这个问题，可以将“console.log”替换成‘false && console.log’，一些原生开发屏蔽打印信息，也都是这样解决的。

**Comment by meibin08** [comment]
__DEBUG__&&console.log('#--baseUrl:', baseUrl);
__DEBUG__&&console.log('#--请求地址:', `${baseUrl}${url}`);
"build": "cross-env NODE_ENV=production wepy build --no-cache";
我们是这么干的，__DEBUG__在配置文件内控制，process.env.NODE_ENV === 'production' ? false:true;
这样虽然能解决不输出的问题，但还是会产生很多无用的代码，小程序本身代码量就有限制，所有还是替换过滤掉是最好的解决方案！

**Comment by zengzhichao** [comment]
你好,这个问题可以尝试在使用uglifyjs插件压缩js时加入   “drop_console: true”解决  

```
  // 压缩js
  module.exports.plugins = {
    uglifyjs: {
      filter: /\.js$/,
      config: {
        compress: {
          drop_console: true
        }        
      },

    }
  }
```

**Comment by wu775825** [comment]
> 你好,这个问题可以尝试在使用uglifyjs插件压缩js时加入 “drop_console: true”解决
> 
> ```
>   // 压缩js
>   module.exports.plugins = {
>     uglifyjs: {
>       filter: /\.js$/,
>       config: {
>         compress: {
>           drop_console: true
>         }        
>       },
> 
>     }
>   }
> ```

正解
