### ISSUE TITLE
[bug] 使用wepy.reportAnalytics 接口会丢失参数

### ISSUE THREAD

**Issue by bojan0624** [Tencent/wepy#1319]
## Description

通过wepy 调用 reportAnalytics 接口 会丢失 第二个参数
例: wepy.reportAnalytics('open_page', {
        usertype: this.userType
      })

使用wx调用无问题

## Environment

   wepy version: 1.7.1
  
## Reproduce

使用自定义分析 创建API统计接口 调用wepy.reportAnalytics

### Observed Results

接口第二位参数为统计参数， 统计参数在上传时丢失
    
### Expected Results

 可以正确上传统计参数
  

## Relevant Code / Logs

https://github.com/Tencent/wepy/blob/a60e44b3483740502f9b5d5293f95f99d3ec8466/packages/wepy-web/src/app.js#L51:13

解决方案 应在 app.js中的noPromiseMethods 中 添加reportAnalytics

**Comment by Gcaufy** [comment]
```
appConfig: {
  noPromiseAPI: ['reportAnalytics']
}
```

**Comment by bojan0624** [comment]
3q

2018-05-04 21:34 GMT+08:00 Gcaufy <notifications@github.com>:
