### ISSUE TITLE
computed 计算属性和Vue设计的有差距是否会影响性能？

### ISSUE THREAD

**Issue by chenxianqi** [Tencent/wepy#1321]
我发现在实际应用中computed如果设置了某个计算属性，当组件载入的时候不管你是否有使用到这个计算属性，都会执行5次，如果我某个计算属性内部有大量的数据计算，那不是很耗费资源，Vue的却不是这样设计的，Vue会进行监听当前计算属性所用到的数据是否有变更才会从新计算，且Vue当组件初始化后computed只执行1次，不知道wepy的这个computed是开始就这样设计的吗

**Comment by Gcaufy** [comment]
Vue 中是有通过getter计算出computed 所依赖的数据变动。但wepy并非是基于getter，setter的实现。。
因此computed在apply时就会做一次计算。上面说的执行了5次看看是不是apply执行了5次。

当然这里也的确是存在可以优化的空间。
在2的版本中，已经使用了Vue的实现。
