### ISSUE TITLE
麻烦问一下npm run dev和npm run build，编译之后的文件有什么不同吗？

### ISSUE THREAD

**Issue by shiran1992** [Tencent/wepy#1323]
"dev": "cross-env NODE_ENV=development wepy build --watch",
"build": "cross-env NODE_ENV=production wepy build --no-cache",

因为最后还是运行这两段脚本，也只有最后的“--watch”和‘--no-catch’不同。就是想知道，最终变异之后，到底有没有区别。麻烦了

**Comment by Gcaufy** [comment]
--watch：监控文件变化，时实编译
--no-cache: 不会缓存npm编译结果，重新进行完整编译
NODE_ENV：这个你就看看wepy.config.js 不同环境下可能会引用不同的编译插件，有不同的配置等等
