### ISSUE TITLE
组件的某个属性默认值是非空对象时会报错（栈溢出）

### ISSUE THREAD

**Issue by pyyzcwg2833** [Tencent/wepy#1327]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
props动态传值的时候，如果某一个属性的default是一个对象Object且不为空的时候，会报错
>thirdScriptError
Maximum call stack size exceeded;at pages/order-status page lifeCycleMethod onLoad function
![image](https://user-images.githubusercontent.com/24390069/39665622-dfa88e94-50c9-11e8-8162-4c324d24846d.png)

## Environment

  * Platform: 开发者工具
  * Platform version: 1.02.1804251
  * Wechat version: [微信版本号]
  * wepy-cli version: 1.7.2-alpha2
  * wepy version: 1.7.1
  
## Reproduce

  [如何重现问题]
  可使用以下代码测试
![image](https://user-images.githubusercontent.com/24390069/39665585-672129ea-50c9-11e8-95a8-38aee1f1f04e.png)

**Comment by Gcaufy** [comment]
把data改成xyz试试

**Comment by Gcaufy** [comment]
released
