### ISSUE TITLE
想问下，安装了但代码中没有引用的库也会打包进去吗？

### ISSUE THREAD

**Issue by iijx** [Tencent/wepy#1328]
比如那个 lodash ，我把示例的inde.wpy和app.wpy都删掉了，然后打包，发现dist包还是挺大的，发现主要是 npm 那个文件夹比较大，而且里面有一些库并没有用到。

所以想问下。

**Comment by Gcaufy** [comment]
没有require就不会被编译进去。

loadash这类个库可能被其它库引用的，比如Redux之类的。所以有可能是你引用了某个库，他引用了loadash
