### ISSUE TITLE
自定义组件样式加载问题

### ISSUE THREAD

**Issue by byg** [Tencent/wepy#1329]
用 wepy 写了几个自定义组件，样式是计算出来的(一堆逻辑如果写在模板中会比较麻烦，且不方便理解)，写在 computed 中，在测试中发现，稍微复杂一点的页面(如引入了较多的组件)就会出现打开页面时能看到初始化渲染组件的过程：高度撑搞，加上颜色等。请问样式是不能通过 js 代码来赋值吗？有没有更好的办法(原生的也没有这个问题)？ @Gcaufy 

*补充*：默认隐藏这个页面，在 page 的 onReady 函数中再显示页面能解决上述问题，但打开页面明显变慢了许多，体校效果更差。上述的问题有 [demo](https://github.com/byg/wechat-textinput) 可以运行

**Comment by Gcaufy** [comment]
@byg 可以用computed来计算样式的。但是你需要注意的是computed的运行时机，computed 运行是在 apply 阶段，如果在页面没有触发apply的话，那么computed不会被计算。
所以根据你的描述大致可以理解为样式开始并没有计算，然后其它代码再触发了apply，导致看到整个样式 被延时计算。

**Comment by byg** [comment]
<p>示例演示：<br>
<img src="https://github.com/byg/wechat-textinput/raw/master/assets/images/demo.gif" alt="image" width='50%'>
</p>
