### ISSUE TITLE
如何跳过某些大文件

### ISSUE THREAD

**Issue by tinybright** [Tencent/wepy#1331]
有个大的压缩js，
每次build耗时很久，其实不需要处理 只需要复制过去就行了。
配置忽略也无效
compilers: {
	babel: {
		compact: true,
		sourceMap: false,
		presets: ['es2015', 'stage-1'],
		plugins: ['transform-export-extensions', 'syntax-export-extensions'
			// ,'transform-decorators-legacy'
		],
		ignore: [
			"./src/static/*", "./src/static/echarts.js", path.join('src', 'static', 'echarts.js')
		]
	}
}

**Comment by Gcaufy** [comment]
npm i wepy-compiler-babel@1.5.3 --save-dev
wepy build --no-cache
