### ISSUE TITLE
无法使用class-transformer第三方包

### ISSUE THREAD

**Issue by sunlandong** [Tencent/wepy#1334]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]vscode
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]1.7.1
  * wepy version: [在package.json里]1.6.0
  * other version: [如果是插件问题，请列出问题插件的版本号] "class-transformer": "^0.1.9",
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

在任意地方，引用class-transformer这个包中的
import {plainToClassFromExist} from "class-transformer"; 并使用，都会复现问题，

另外，已经是最新版的wepy-cli，但是依然不支持私有仓库的私有包引用
### Observed Results

  [实际表现]
  thirdScriptError 
 sdk uncaught third Error 
 Maximum call stack size exceeded 
 RangeError: Maximum call stack size exceeded
    at Array.join (native)
    at http://127.0.0.1:53251/appservice/__dev__/WAService.js:18:26769
    at http://127.0.0.1:53251/appservice/npm/class-transformer/storage.js:3:25
    at require (http://127.0.0.1:53251/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:53251/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:53251/appservice/npm/class-transformer/TransformOperationExecutor.js:3:17
    at require (http://127.0.0.1:53251/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:53251/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:53251/appservice/npm/class-transformer/metadata/MetadataStorage.js:3:36
    at require (http://127.0.0.1:53251/appservice/__dev__/WAService.js:18:27248)
  [Observed Results]
  
### Expected Results

  [期望表现]
  无错误
  [Expected Results]
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs here to reproduce the problem
  // 可以使用小程序代码片段功能，方便其它人帮助你定位代码问题
  // 详情可参考这里：https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
  ```

**Comment by sunlandong** [comment]
class-transformer里，TransformOperationExecutor.js,storage.js,MetadataStorage.js三个js，有相互依赖的关系，wepy-cli在处理这三个相互依赖的时候，形成的循环，导致内存溢出

**Comment by sunlandong** [comment]
import 带有命名空间@符号的私有组件无法使用，是在ts中如果引入了，无法使用

**Comment by Gcaufy** [comment]
@sunlandong 
这个应该不是wepy-cli的问题，wepy-cli测试过是可以处理循环引用的问题
这个是在运行阶段报错的，而不是在编译阶段，这是微信小程序是有一个循环引用的bug的。

**Comment by sunlandong** [comment]
4月12号更新的开发工具 ，支持循环引用了，还是出现这问题，有解否？

**Comment by may215** [comment]
I have the same issue, can you tell me please if you solve this?
