### ISSUE TITLE
page页面首次打开异步数据无法通过props传递到子组件

### ISSUE THREAD

**Issue by littleQing** [Tencent/wepy#1335]
页面传递异步数据到子组件首次加载传递不过去，在开发工具没问题，手机上有问题。之后再放回到之前页面组件传值没问题，这bug怎么解决？

**Comment by Gcaufy** [comment]
能贴一部分代码片段么？

**Comment by littleQing** [comment]
已经解决了
  解决方法：在开发者工具关闭上传代码时自动压缩就解决了，在wepy文档里也有强调（气哭）
  感谢回复！
