### ISSUE TITLE
wepy.getUserInfo() 容易误导人

### ISSUE THREAD

**Issue by hanwenbo** [Tencent/wepy#1337]
import wepy from 'wepy';

async onLoad() {
    await wepy.login();
    this.userInfo = await wepy.getUserInfo();
}
文档这么写误导人，我表示不理解，硬是跑不出来
最后换成类似微信官方的写法可以出来，建议wepy团队把这块文档完善下，我这么有效果，代码如下：
const res = await wepy.getUserInfo({
        success: (res) => {
          console.log('wepy.getUserInfo.success:', res)
        },
        fail: (res) => {
        }
      })

**Comment by Gcaufy** [comment]
哪里，给个link我更新优化一下

**Comment by hanwenbo** [comment]
https://tencent.github.io/wepy/document.html#/?id=wepyconfigjs%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E @Gcaufy    await wepy.login(); 这个 await 还有 wepy.getUserInfo() 的await 有什么用呢，因为加不加都没任何数据返回 并且也不是异步  页面都执行完了 返回数据才能console.log出来 说明不是异步的

**Comment by hanwenbo** [comment]
wepy.login() 我不知道你是怎么用的；
我反正得↓ 这样才能打印出来data
await wepy.login({
        success: function (data) {
          console.log(data)
         
        }
      })

**Comment by hanwenbo** [comment]
我好像明白了  ， 必须要加        'syntax-export-extensions'个是吗？我翻到了wepy项目中使用async await
里的介绍  安装下之后发下变异步了

**Comment by hanwenbo** [comment]
使用了  this.use('promisify') 之后，new Promise 无效，我很郁闷 这是什么编程思想

**Comment by liuqian1996** [comment]
唉，都没给介绍清楚……

**Comment by hanwenbo** [comment]
@Gcaufy this.use('promisify')了之后  ，默认es里的new Promise  无效这是为什么

**Comment by Gcaufy** [comment]
建议再多看一下js的基础，先多了解一下 Promise, async/await等。

另外在文档开发规范里已经说明了如何使用 promise

**Comment by Gcaufy** [comment]
另外，如果觉得文档有更好的表述方式的话，也欢迎PR

**Comment by hanwenbo** [comment]
@Gcaufy 可以 我有时间提交文档的pr吧 项目顺利完成了  对js基础没兴趣  我需求是拿看文档wepy快速做项目 我看了一些基于wepy的开源项目完成的 很顺利 除了上面问你的 没有预见其他网上说的坑

**Comment by 378978764** [comment]
2018年7月5日之后发布的版本已经全部改了，只能放个按钮获取用户信息，原有的接口都不能用了，不知道官方会不会适配。 @Gcaufy
