### ISSUE TITLE
wepy能否实现模块热替换(HMR)

### ISSUE THREAD

**Issue by yucccc** [Tencent/wepy#1338]
当项目比较大的时候，每次修改项目都会重新刷新，能否实现模块热替换的功能

**Comment by dlhandsome** [comment]
这个是开发工具的特性吧，监测到文件变化都会重新刷新

**Comment by Gcaufy** [comment]
他说的是指类似 webpack 的HMR 机制，可以做的无刷新替换。
这个功能理论上好像是可行的。但是目前不在开发计划当中。
