### ISSUE TITLE
BUG：传递组件属性值时，不能使用对象属性

### ISSUE THREAD

**Issue by colaboy** [Tencent/wepy#1339]
&lt;List :caption="userInfo.avaterUrl"/&gt;这样传值List组件读不到这个值

&lt;List :caption="avaterUrl"/&gt; 拉平后传值是可以的

List组件代码如下：
![1](https://user-images.githubusercontent.com/8551272/39790621-afb026e6-5369-11e8-9275-323a8a0c97dd.png)

**Comment by heath-l** [comment]
没办法。。这玩意坑这么多。。能实现就行了。
