### ISSUE TITLE
循环渲染自定义组件的坑（keywords: repeat, computed, watch, onLoad）

### ISSUE THREAD

**Issue by yusphy45** [Tencent/wepy#1341]
## Description

在使用<repeat>循环渲染自定义组件时，组件内的computed属性，引起属性变化的值发现永远是列表中的第一个值。

## Environment

  * Platform: [开发者工具]
  * Platform version: [1.02.1804240]
  * Wechat version: [微信版本号]
  * wepy-cli version: [1.7.1]
  * wepy version: [1.7.1]
  
## Reproduce

举例：一个列表，列表中的每个元素都有一个selected属性（用来显示特殊的样式，默认为true），组件内部定义
```
//template
<view class="{{disable ? 'disable': ''}}">

// script
computed = {
   disable () {
      return !this.selected
   }
}

```

### Observed Results

我只更改了第一个元素的selected为false，结果列表中的每个组件都添加了特殊样式。
  
### Expected Results

我只更改了第一个元素的selected为false，列表中只有第一个组件添加了特殊样式。

希望一定在文档里标示清楚，repeat渲染的自定义组件中，现阶段不要使用computed, watch（无法监听props属性的改变）, onLoad钩子（仅触发一次）这些属性，因为基本可以说是无法使用的状态，最好还是把列表以及列表内处理数据的逻辑放入上层组件中。

多说一句：当然我很感谢作者的辛苦劳动使我们可以以更优雅的方式编写小程序，但是列表循环基本可以算是组件的基本使用姿势之一，这些问题当然如果使用者去搜issue是可以搜到的，但是这中间包含了很多试错成本在，所以还是真诚的希望明确的在文档中标注，而不是仅仅在issue中回复

**Comment by yusphy45** [comment]
@Gcaufy 哇，大神响应好迅速，恩恩，满完善的，非常感谢

**Comment by superlbr** [comment]
期待2.x

**Comment by Cecil0o0** [comment]
tencent加油，期待2.x

**Comment by mylesshie** [comment]
现在才发现这个坑，我还以为我使用方式不对，，，

**Comment by Gcaufy** [comment]
@jhd124 可以pr一下文档。

**Comment by DSKcpp** [comment]
我改一个其中一个data,所有的循环组件全都改了，有什么好的办法能解决吗？
