### ISSUE TITLE
Compiler: app `config` match pattern fails for Typescript type declaration

### ISSUE THREAD

**Issue by o-jules** [Tencent/wepy#1342]
## Issues

The compilation came with fatal error when I was using Typescript and adding type declaration for the app's `config`.

Code that works:
```typescript
export default class App extends wepy.app {
    public config = {
        pages: [
            'pages/main/index'
        ]
    }
}
```

Code that fails:
```typescript
export default class App extends wepy.app {
    public config: WxAppConfig = {
        pages: [
            'pages/main/index'
        ]
    }
}
```

Inspection into the wepy-cli compiler showed that the problem was due to the following line:

https://github.com/Tencent/wepy/blob/75746b2654dc0ecafec100a08f8a25e099e59891/packages/wepy-cli/src/compile-wpy.js#L215

where the regular expression fails the typed version.

## Fixes

Something like this will work.

```js
var match = rst.script.code.match(/[\s\r\n]config(?:\s*\:\s*[_a-zA-z]\w+)?\s*=[\s\r\n]*/);
```

**Comment by Gcaufy** [comment]
the solution to parse script is totally horrible in 1.7.x. so I'm not going to fix it is in 1.7.x.
this will be fixed in 2.0 version, but it will be a total different version.
