### ISSUE TITLE
npm build 之后svg 图片的内容替换为空， 生产环境（测试环境正常）

### ISSUE THREAD

**Issue by Ex-Caliburn** [Tencent/wepy#1345]
![image](https://user-images.githubusercontent.com/24788764/39831079-f4e32060-53f5-11e8-944f-1c48a8648128.png)

**Comment by Gcaufy** [comment]
图和问题关系不大吧。
如果图片内容为空，对比 一下src和dist内的文件看是不是为空先。

**Comment by whatthecole** [comment]
执行npm run build 之后，所有的图片的内容都变为空

**Comment by Gcaufy** [comment]
@whatthecole 建议重装一下npm 看看
