### ISSUE TITLE
刚生成的新项目；在工具内一直报错

### ISSUE THREAD

**Issue by songxianling** [Tencent/wepy#1348]
wepy-cli 版本号 . 1.7.2-alpha2
用wepy init standard myproject 新生成的项目；安装依赖；开始编译 ； 放在开发者工具中一直报错
编译没有错误
![image](https://user-images.githubusercontent.com/16551088/39856300-e0e6bbc8-5461-11e8-97c1-cb555af74b41.png)
但是在开发者工具中就会出现
![image](https://user-images.githubusercontent.com/16551088/39856193-8c0b828c-5461-11e8-97d2-a5a8c7cddba2.png)
![image](https://user-images.githubusercontent.com/16551088/39856236-ae9ea77a-5461-11e8-8b8d-e77b652c58eb.png)
点击都不能xiang ying响应

**Comment by Gcaufy** [comment]
```
npm install wepy-cli@1.7.2 -g
```
