### ISSUE TITLE
unhandled promise rejection 没有任何提示

### ISSUE THREAD

**Issue by liusome** [Tencent/wepy#1350]
#280
**问题复现步骤:**

脚手架生成一个代码
在index.vue里面的
`created () {`
`  (async () => {`
`     let a = {}`
`     a.b.c = 0`
`  })()`
`},`
**期望的表现:**

期望在控制台里面报告created中不能够赋值给undefined

**观察到的表现:**

没有任何提示

**官方给出的回答是**
![image](https://user-images.githubusercontent.com/13285305/39857082-ad614ea0-5464-11e8-85bf-48b7a1a61109.png)
**小程序没有window对象，Promise对象的报错不会冒泡到全局，请看一下这个问题。**

**Comment by Gcaufy** [comment]
发错地方了吧。

**Comment by liusome** [comment]
好吧 的确是发错地方了~
