### ISSUE TITLE
使用 vscode wepy小程序 如何优雅的使用 js 智能提示

### ISSUE THREAD

**Issue by moyuanhua** [Tencent/wepy#1353]
在script标签里面的js无法 使用js的智能提示  
而且import进来的类库也无法正常提示函数的参数

请问目前有解决方案吗

**Comment by moyuanhua** [comment]
目前的骚操作是。。。
[图片]

**Comment by moyuanhua** [comment]
![4ff xb 5 2z c trco4z8](https://user-images.githubusercontent.com/7417755/39866096-c30509b4-5481-11e8-804c-702ecefdd09d.png)

**Comment by moyuanhua** [comment]
不过这样会多编译出来一个js文件

**Comment by moyuanhua** [comment]
![tim 20180510184338](https://user-images.githubusercontent.com/7417755/39866158-121dd882-5482-11e8-8080-d851f4d2e9d0.png)
刚才试了一下 这样也行。。。emmm  牛逼！！

**Comment by iniself** [comment]
vsc没有去做，如果不介意用PhpStorm/WebStorm，那么[WePY Plugin For IntelliJ Platform](http://wepy.iniself.com)适合你
