### ISSUE TITLE
props不支持表达式中的点运算符 eg :prop="query.something"

### ISSUE THREAD

**Issue by yusphy45** [Tencent/wepy#1354]
## Description

发现组件的props属性当父组件传入动态属性时，无法识别:val.sync="query.something"(.sync加不加都一样)这种形式，最终页面的val值依旧为默认值

## Environment

  * Platform: [开发者工具]
  * Platform version: [1.02.1804240]
  * wepy-cli version: [1.7.1]
  * wepy version: [1.7.1]
 
## Relevant Code / Logs

```
// index.wpy

// template
<child :val="query.something"></child>
// script
export default class Index from wepy.page {
  components = {
    'child':child
  }

  data = {
    query: {
      something: [1,2,3]
    }
  }
}

// child.wpy
<repeat for={{val}} item="item">
  <text>{{item}}</text>
</repeat>
// script
export default class Child from wepy.component {
  props = {
    val: {
      type: Array,
      default: []
    }
  }
  onLoad () {
    console.log(this.val)  // 输出 []
  }
}
```

### Observed Results

控制台输出: []
页面无内容
  
### Expected Results

控制台输出:  [1,2,3]
页面显示123

### Ps
如果直接在父组件data中定义something, :val="something"是正常的
希望能够正确识别表达式中的点符号，或指导另一种黑魔法 👻

**Comment by jcto** [comment]
对啊，这个问题有解决吗？

**Comment by yusphy45** [comment]
@Gcaufy 求大神给个解决的思路哇

**Comment by DsAco** [comment]
还真是这个问题。。。

**Comment by Gcaufy** [comment]
在 1.7 的版本不会支持 点操作符。 props 设计的就是一个key, 而不是一个表达示。
需要将整个object 传过去，然后再在组件之中去取值 。
