### ISSUE TITLE
wepy-web不支持swiper

### ISSUE THREAD

**Issue by blovetad** [Tencent/wepy#1355]
## Description

wepy-web不支持swiper
  
  [Description of the issue]

## Environment

  * Platform: [Web]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v] 5.5.1
  * wepy version: [在package.json里]  "wepy": "^1.7.1"
  * other version: [如果是插件问题，请列出问题插件的版本号]  "wepy-web": "^1.6.0"
  
### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs
VM412:1 [Vue warn]: Cannot find element: #app
17:38:13.353 VM412:1 [Vue warn]: Unknown custom element: <swiper> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

17:38:13.359 VM412:1 [Vue warn]: Unknown custom element: <swiper-item> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
  ```
  // TODO(you): code or logs here to reproduce the problem
  // 可以使用小程序代码片段功能，方便其它人帮助你定位代码问题
  // 详情可参考这里：https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
  ```

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/tree/1.7.x/packages/wepy-web/src/components

目前支持的只有这么多了
