### ISSUE TITLE
组件props 传值，亲测onLoad里this.xxx无效

### ISSUE THREAD

**Issue by hanwenbo** [Tencent/wepy#1356]
文档地址：
https://tencent.github.io/wepy/document.html#/?id=props-%E4%BC%A0%E5%80%BC

<child title="mytitle"></child>

// child.wpy
props = {
    title: String
};

onLoad () {
    console.log(this.title); // mytitle
}

**Comment by hanwenbo** [comment]
<faInput1 :value.sync="college_name"/>
props = {
      type: {
        type: String,
        default: 'text'
      },
      placeholder: {
        type: String
      },
      value: {
        type: [String, Number],
        twoWay: true
      }
    }

**Comment by hanwenbo** [comment]
当
```
 <faInput1 value="college_name"/>
props = {
     
      value: {
        type: [String, Number]
      }
    }
```
才有效果，这是我理解是个bug

**Comment by hanwenbo** [comment]
我分析是    onLoad () {}  // 在Page和Component共用的生命周期函数
这个生命周期的共用的原因  因为我是在Page的onLoad里赋值的，如果遇到这种情况我应该在哪儿提前改变page里的属性值呢  因为我要请求赋给组件

**Comment by hanwenbo** [comment]
子组件先执行导致的，不算bug

**Comment by NinoWang** [comment]
> 子组件先执行导致的，不算bug

请问最终怎么处理这个问题的呢：“在哪儿提前改变page里的属性值”
