### ISSUE TITLE
有没有框架自带的状态 能判断当前页面是否加载完毕的？

### ISSUE THREAD

**Issue by hanwenbo** [Tencent/wepy#1357]
有没有框架自带的状态 能判断当前页面是否加载完毕的？

**Comment by hanwenbo** [comment]
还有想请教下：
如何在标签里使用函数呢？因为我想对日期循环并将时间戳转换格式
<view data="{{time.fomate(xxxxxxxx,'Y-M-D')}}"> Click me! </view>
不知道怎么在标签里使用函数

**Comment by Gcaufy** [comment]
问题1：wx小程序的生命周期看一下
问题2：wxs

**Comment by hanwenbo** [comment]
@Gcaufy 谢谢  看了生命周期解决不了，computed浪费性能及麻烦，最后我用js里叫装饰器的东西包过了下你写的onLoad方法 注入了个状态解决了
