### ISSUE TITLE
await wepy.getUserInfo();

### ISSUE THREAD

**Issue by heath-l** [Tencent/wepy#1360]
const rawUser = await wepy.getUserInfo();
以前是这么写。。今天就不走了。。现在要怎么改。。或者官方哪里有说明？。文档里没找到啊。、

**Comment by alucardhyx** [comment]
4月19日，微信团队在“微信公众平台”发出通知，从2018年4月30日开始，小程序与小游戏的体验版、开发版调用 wx.getUserInfo 接口，将无法弹出授权询问框，默认调用失败。正式版暂不受影响。开发者可使用以下方式获取或展示用户信息：
    1、使用button组件，并将open-type指定为getUserInfo类型，获取用户基本信息。
    详情参考文档：
        https://developers.weixin.qq.com/miniprogram/dev/component/button.html
    2、使用open-data展示用户基本信息。
    详情参考文档：
        https://developers.weixin.qq.com/miniprogram/dev/component/open-data.html

**Comment by jiangdi0924** [comment]
同问

**Comment by 15011120064** [comment]
怎么改啊？

**Comment by sxyseo** [comment]
这边修改了后台的验证，跳过了验证用户信息，直接使用sessionKey, encryptedData, iv这三个参数可以解密用户信息。
建议按照最新的来，如下。
```
<button  type="primary" open-type="getUserInfo" bindgetuserinfo="bindGetUserInfo">授权</button>
```

**Comment by aaronwf** [comment]
wepy里面该怎么用？
