### ISSUE TITLE
what is newFeature

### ISSUE THREAD

**Issue by EternalChildren** [Tencent/wepy#1361]
## Description
利用最新命令 wepy init standard name生成的项目中
project.config.json配置文件中 setting这个属性有个字段叫做newFeature这个字段在小程序官方的setting中是不存在的，为何会有这个配置

	"setting": {
		"urlCheck": true,
		"es6": false,
		"postcss": false,
		"minified": false,
		"newFeature": true
	}

**Comment by gentlelynn** [comment]
这个字段是表示是否支持新特性 https://hexuanzhang.github.io/2018/01/23/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%85%8D%E7%BD%AE%E8%A7%A3%E6%9E%90/
