### ISSUE TITLE
对于wx.request请求返回的requestTask句柄，wepy.request是否可以支持？

### ISSUE THREAD

**Issue by jimmyrogue** [Tencent/wepy#1363]
对于wx.request请求返回的requestTask句柄，wepy.request是否可以支持？
wx.request请求会返回requestTask，可使用abort方法来中止请求
但是目前wepy.request无法使用此项功能。

不知是否可以支持一下。

**Comment by Gcaufy** [comment]
如果使用promise的话那是无法做到，如果需要用句柄那就用 wx.request就好了。

**Comment by shiny** [comment]
wepy.request 获取 cookie 也很困难
