### ISSUE TITLE
wepy 结合typescript 写小程序，如何实现？

### ISSUE THREAD

**Issue by hanwenbo** [Tencent/wepy#1364]
我用es7写了个项目，但感觉很别扭，代码是否正确全靠猜，或者写好类了查看页面刷新页面 是否运行正确。我看了typescript能像其他后端语言一样可以约定参数，所以我想用typescript重构现在wepy写的项目，不然我无法保证后续随着升级能稳定运行 而且自动化测试很难  ，请教下库主 wepy 可以 结合typescript编程吗？

**Comment by banxi1988** [comment]
@hanwenbo 

我写的一个使用 Wepy + Typescript 的 TodoDemo 可供参考：
https://github.com/banxi1988/wepy-todo-demo

**Comment by hanwenbo** [comment]
@banxi1988 牛逼 谢谢啊  您有qq或者微信吗  我们开发的时候一起交流 提高效率

**Comment by hanwenbo** [comment]
@banxi1988 经过测试发现随便传入值也并未编译错误

**Comment by hanwenbo** [comment]
@banxi1988 十分感谢，我现在就差一个问题了  就是为什么wepy build --watch编译的时候 ts错了 依然能后编译通过   如果这个搞明白  我就能往下继续推进了

**Comment by hanwenbo** [comment]
@banxi1988 谢谢经过测试 暂时不行 只能等官方升级
