### ISSUE TITLE
 no-multiple-empty-lines  

### ISSUE THREAD

**Issue by blockChainB** [Tencent/wepy#1365]
当我init 之后 打开文件后报错了  
![wechatimg1](https://user-images.githubusercontent.com/11595694/39914065-758503dc-5536-11e8-8981-e5b5571b785c.jpeg)
![wechatimg2](https://user-images.githubusercontent.com/11595694/39914088-861babf6-5536-11e8-8b0f-19d8c9629d4c.jpeg)

这个怎么破? 谢谢

**Comment by Gcaufy** [comment]
eslint 的报错。google 一下就能看到答案。
