### ISSUE TITLE
最新版本wepy 1.7.2 初始化化项目问题：

### ISSUE THREAD

**Issue by webdzq** [Tencent/wepy#1370]
最新版本wepy 1.7.2 初始化化项目问题：

cmd：wepy init standard my-project
⠸ downloading template   wepy-cli · Failed to download repo standard: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8118

**Comment by Gcaufy** [comment]
网络不通。

**Comment by coolpo** [comment]
下载了最新的standard模板，编译完成之后，还是有warn提示，而且样式可以出来，所有的功能无法实现

**Comment by saillin** [comment]
⠦ downloading template   wepy-cli · Failed to download repo standard: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN ip:80
我也是出现了这种情况

**Comment by Gcaufy** [comment]
@saillin  看看是不是网络的问题， 找个 github raw 文件 curl 看看。

**Comment by gzgogo** [comment]
不要使用淘宝镜像，将镜像切换回npm
