### ISSUE TITLE
dependencies "wepy": "^1.7.1" 不能更新为1.7.2，文档和模板没有更新如何使用小程序原生自定义组件的内容

### ISSUE THREAD

**Issue by panhezeng** [Tencent/wepy#1371]
------------------------
## Description

package.json dependencies "wepy": "^1.7.1" 不能更新为1.7.2，还有文档关于使用组件的部分，没有更新关于如何使用小程序原生自定义组件的介绍，还有最新wepy-cli 1.7.2 init的模板，也没有使用使用小程序原生自定义组件的示例

  
## Reproduce

  [如何重现问题]
  
  npm install wepy-cli@1.7.1 -g

  wepy init standard myproject

 npm update 
// dependencies "wepy": "^1.7.1" 不能更新为1.7.2

  npm install wepy-cli@1.7.2 -g

  wepy init standard myproject
 // 没有使用使用小程序原生自定义组件的示例

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy-wechat-demo/tree/components

这是使用原生组件的示例。。。
1.7 的版本使用原生组件可能还会存在一些问题。

**Comment by panhezeng** [comment]
？@Gcaufy 我说的是，wepy 1.7.2 (2018-05-08)A 添加了对小程序原生组件的支持，https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/

你这个wepy-wechat-demo最后的更新日期是两个月以前，package.json里面"wepy": "^1.5.8",
是穿越了吗？
