### ISSUE TITLE
1.7.2 的原生组件无法编译

### ISSUE THREAD

**Issue by BaranWang** [Tencent/wepy#1373]
看更新日志 1.7.2 已经支持小程序原生组件了。但是按照文档方法操作后并没有编译，组件缺少 wxml 和 json 文件，引入的页面缺少 usingComponents

**Comment by Wind4** [comment]
只有1.7.2-alpha1编译正常，以下版本都不支持

- 1.7.2-alpha2
- 1.7.2-alpha3
- 1.7.2-alpha4
- 1.7.2

**Comment by BaranWang** [comment]
@Wind4 wepy-cli 还是 wepy 呢？还是两者

**Comment by BoleLee** [comment]
@BaranWang 原生组件支持的相关文档你是在哪里看的，我翻了下wePY的文档，没有找到原生组件编译的支持，只看到一句话：

> 在 1.7.2-alpha4 的实验版本中提供了对原生组件的支持。

**Comment by BaranWang** [comment]
@BoleLee 我也找不到了，之前看到过，wepy的文档感觉很多都不同步。换成 1.7.2-alpha1 可以正常编译，但是 attached 生命周期有些问题，别的还没发现。

具体是调用组件的时候写成
```
components = {
  '@component': component
}
```

**Comment by NoahSun** [comment]
@BoleLee [更新日志](https://github.com/Tencent/wepy/blob/2.0.x/CHANGELOG.md) - 5月8号的第一个新特性就是支持小程序原生组件。
@BaranWang 然而npm仓库里面没有上传新版本的wepy。

**Comment by BoleLee** [comment]
@NoahSun 额，这个我看到了，才去找的文档，我想找的是，比如App, Page, WePY实现的component, 会有对应的API文档，使用说明也有，原生组件的支持也应该有；
其二，WePY实现的自定义组件与小程序原生自定义组件之间的一些问题，比如命名上怎么区分，使用方式有什么区别；
第三，在1.7.2版本之前，其实也可以开发小程序原生自定义组件，只不过代码保留其原生的写法

**Comment by icepole-jon** [comment]
你们是在说原生自定义组件吗？
我试了下引入zanui-weapp是可以的
```html
<zan-button>取消订单</zan-button>
<zan-dialog id="zan-dialog-test"></zan-dialog>
<zan-icon type="success"></zan-icon>
```
```js

import Dialog from '../utils/zanui/dialog/dialog'
export default class Index extends wepy.page {
    config = {
      navigationBarTitleText: 'test',
      usingComponents: {
        'zan-button': '/utils/zanui/btn/index',
        "zan-icon": "/utils/zanui/icon/index",
        "zan-dialog": "/utils/zanui/dialog/index"
      }
    }
   onShow() {
      Dialog({
        title: 'zanUI dialog',
        message: 'test test test',
        selector: '#zan-dialog-test'
      }).then((res) => {
        console.log(res);
      })
    }
}
```

**Comment by liuyangcharlie** [comment]
请问是否能把新版本上传到npm？https://github.com/Tencent/wepy/issues/1464

**Comment by liuyangcharlie** [comment]
@icepole-jon 请问你在什么版本测试通过的？
1.7.2-alpha1是编译不过的，会报cannot find module `../utils/zanui/dialog/dialog`这种错误

**Comment by icepole-jon** [comment]
@liuyangcharlie 
```json
{
"wepy": "^1.7.1",
"zanui-weapp": "^3.0.4"
}
```
要做一点处理，手动把node_modules/zanui-weapp/dist中的文件拷到src目录里面去。
目录结构例如：
```
src/components/zanui/
src/components/zanui/actionsheet
src/components/zanui/btn
...
src/components/zanui/index.js
src/components/zanui/index.wxss
```
编译的时候就会自动复制到dist去了，如上引用就不会报找不到模块了。

**Comment by liuyangcharlie** [comment]
@icepole-jon 明白了，需要让zanui的组件出现在编译后的dist中，多谢

**Comment by nishino-tsukasa** [comment]
我也是，只有1.7.2-alpha1版本可以

**Comment by yhz0206** [comment]
我用的是1.7.2版本
