### ISSUE TITLE
watcher不能监听props变化？

### ISSUE THREAD

**Issue by liuzhenji** [Tencent/wepy#1375]
## Description

子组件的watcher不能监听props变化的话，那当父组件传递给子组件的属性变化了咋办？动态传props的.sync作用不是鸡肋吗？

**Comment by liuzhenji** [comment]
难道要每次props变化的时候，触发子组件的更新事件么，这样感觉还繁琐

**Comment by liuzhenji** [comment]
看了半天，还是不用组件了。。。直接页面实现吧

**Comment by liuzhenji** [comment]
问题还是存在的。
`parent.wpy`
```
<template>
<chargePopup :show.sync='{{needToCharge}}'>
  <view style='height:100px;width: 100px' slot='content'>content</view>
</chargePopup>
</template>
```

`child.wpy`
```
props = {
    show: {
      type: Boolean,
      default: false
    }
  }
```

`<view class="pop {{show ? 'pop-show' : ''}}">`

如上，子组件的view并不会根据父组件的值变化而变化

**Comment by liuzhenji** [comment]
@Gcaufy  大神，麻烦看下props动态传值这点。
我关闭压缩上传代码了

**Comment by liuzhenji** [comment]
最终还是放弃:props.sync功能。改用$invoke事件触发。
此外，这里注意：
data中的属性名不可以跟自定义方法名同名，不然方法名会被data的中的属性覆盖。
因为data中的属性最终会被提升到page或者component实例的属性上，这也是为啥我们能this.xxx调用的原因

**Comment by wangmh1990** [comment]
我也有这个问题，子组件watch不能监听到props的更改。在工具上没问题，在真机上有问题

**Comment by hcmuhi** [comment]
+1 同问，工具没问题，真机有问题

**Comment by agoodcoolman** [comment]
[另外一个回复了答案](https://github.com/Tencent/wepy/issues/647)
