### ISSUE TITLE
typescript编译，约束数据格式无效

### ISSUE THREAD

**Issue by hanwenbo** [Tencent/wepy#1376]
配合typescript编译使用，发现传入值错误 并未提示

**Comment by bokire** [comment]
typescript的错误提示自己看看就好了

**Comment by hanwenbo** [comment]
@bokire 要严谨

**Comment by bokire** [comment]
@hanwenbo wpy文件中用src的方式引入ts文件
`<script lang="typescript" src="./index.ts">
</script>`
能在index.ts中看到错误提示，但还是能正常编译,所以自己看看就好

**Comment by hanwenbo** [comment]
@bokire 嗯谢谢啊老铁  目前只能这样 后期希望官方能优化下这块
