### ISSUE TITLE
bindgetuserinfo该怎么在wepy里写

### ISSUE THREAD

**Issue by zhu5439peng** [Tencent/wepy#1379]
## Description

```
<button open-type="getUserInfo" bindgetuserinfo="bindGetUserInfo">用户授权</button>
```

微信团队修改了wx.getUserInfo 接口，要求使用button组件，
wepy使用@来绑定事件，我试过@getuserinfo和@bindgetuserinfo，这两种方式都不能 用
请问bindgetuserinfo在wepy该怎么写

**Comment by BaranWang** [comment]
@getuserinfo 可以的啊

**Comment by zhu5439peng** [comment]
试了试 @getuserinfo 的确可以，只是在开发者工具中没有看到显示，但是函数是正常执行的

**Comment by jason-zuo** [comment]
@BaranWang 你好为什么要加@呢，我之前还是可以的，但是现在突然什么都获取不到了button的getuserinfo
