### ISSUE TITLE
init 初始化项目后 wepy eslint 编译报错

### ISSUE THREAD

**Issue by cmqiong** [Tencent/wepy#1380]
## Description

 init 初始化项目后 wepy eslint 编译报错

## Environment

  * wepy-cli version:1.7.2
  * wepy version: 1.6.0
  * wepy-eslint: 1.5.3

  * node version: 7.9.0
  * npm version: 4.2.0

## Reproduce

npm install wepy-cli -g //  wepy-cli@1.7.2

npm init standard test
// ? Use ESLint to lint your code? Yes
// ? Use Redux in your project? Yes
// ? Use web transform feature in your project? Yes

cd test
npm install
npm run dev 

## Relevant Code / Logs

终端报错信息如下：
/Users/cmq/Work/test/src/app.wpy
  23:3  error  'config' is not defined      no-undef
  35:3  error  'globalData' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)

[17:46:58] [写入] JSON: dist/app.json
[17:46:58] [拷贝] VUE : src/App.vue
[17:46:58] [拷贝] PNG : src/assets/logo.png
[17:46:58] [拷贝] VUE : src/components/HelloWorld.vue
[17:46:58] [编译] 组件: src/components/counter.wpy

/Users/cmq/Work/test/src/components/counter.wpy
  31:12  error  'connect' is defined but never used    no-unused-vars
  32:12  error  'INCREMENT' is defined but never used  no-unused-vars
  32:23  error  'DECREMENT' is defined but never used  no-unused-vars
  33:12  error  'asyncInc' is defined but never used   no-unused-vars
  49:5   error  'props' is not defined                 no-undef
  59:5   error  'data' is not defined                  no-undef
  61:5   error  'events' is not defined                no-undef
  68:5   error  'watch' is not defined                 no-undef
  74:5   error  'methods' is not defined               no-undef

✖ 9 problems (9 errors, 0 warnings)

[17:46:58] [编译] 组件: src/components/group.wpy

......(省略很多类似报错)

**Comment by kennir** [comment]
@cmqiong  碰到和你一样的问题, 请问解决了吗？

**Comment by Gcaufy** [comment]
可以再试一下吗？我并没有看到类似报错。

**Comment by Gcaufy** [comment]
@kennir 可以贴一下报错截图么？

**Comment by cmqiong** [comment]
@kennir 没有解决。。。

**Comment by cmqiong** [comment]
@Gcaufy 还是一样的报错。。。不知道这些有没有关系
node version: 7.9.0
npm version: 4.2.0

**Comment by kennir** [comment]
我解决了，uninstall掉 standard 就可以了

**Comment by cmqiong** [comment]
@kennir 什么意思？？我没懂。。。

**Comment by cmqiong** [comment]
我执行了 npm uninstall standard，可问题还在。。。
![image](https://user-images.githubusercontent.com/15047375/40476958-e4489914-5f77-11e8-8cbc-95468b0863ed.png)

**Comment by sshien** [comment]
没事不影响

**Comment by jswxwxf** [comment]
请问你们是怎么解决的呢？我现在也出这样的问题了~

**Comment by gb-6k-house** [comment]
怎么解决，遇到同样问题

**Comment by Helovebai** [comment]
同样的问题 ...    该怎么办...
