### ISSUE TITLE
子组件的onLoad方法比父页面的onLoad执行时机要早

### ISSUE THREAD

**Issue by x3852** [Tencent/wepy#1386]
wepy版本:1.7.1
页面A里面加了一个子组件a1，
页面A和子组件a1都拥有onLoad事件，但页面加载的时候都是先执行子组件a1的onLoad再去执行页面A的onLoad事件

**Comment by liuxingzhijian1320** [comment]
+1

**Comment by alsotang** [comment]
https://blog.csdn.net/blueblueskyhua/article/details/78024836
根据这篇文章的实验，vue的执行顺序是：
> 父组件beforeCreated ->父组件created ->父组件beforeMounted ->子组件beforeCreated ->子组件created ->子组件beforeMounted ->子组件mounted -> 父组件mounted。

**Comment by CXW0504** [comment]
+刚刚遇到。。。。。
