### ISSUE TITLE
对于components下的组件编译有问题，编译后文件缺失，不更新

### ISSUE THREAD

**Issue by Chris-wei** [Tencent/wepy#1390]
![image](https://user-images.githubusercontent.com/20335644/40228268-5fdf3682-5ac3-11e8-8994-f2ebd7153285.png)
截图表示，编译后并没有生成 list.wxml 文件...

**Comment by dlhandsome** [comment]
提供一下代码片段？否则我们无法定位问题

**Comment by Chris-wei** [comment]
components中的 list 组件

![1526888901 1](https://user-images.githubusercontent.com/20335644/40296315-e33e0b32-5d0e-11e8-9bab-323787bde75c.jpg)

页面引入

![1526888994 1](https://user-images.githubusercontent.com/20335644/40296329-e8e7e184-5d0e-11e8-9fcf-1acd54b04236.jpg)

**Comment by yurentle** [comment]
遇到同样的问题，新写了个组件，但是wepy不编译，一直报错组件未定义

**Comment by ityangyang** [comment]
遇到了同样问题，请问最后您是咋解决的
