### ISSUE TITLE
无法使用小程序新增的onPageNotFound监听函数

### ISSUE THREAD

**Issue by bluesky12** [Tencent/wepy#1391]
## Description

  小程序app.js新增了一个钩子函数onPageNotFound，访问不存在的页面时触发，可以进行重定向等操作。
  在app.wpy中使用该钩子，却并不生效。  

  查看编译后的app.js，打印传入App()函数的配置，发现只有onLaunch、onShow、onHide、onError被保留，onPageNotFound及其它全局函数均未传入原生App()函数，故而onPageNotFound未生效。

## Environment

  * Platform: 开发者工具、Andriod
  * wepy-cli version: 1.7.1
  * wepy version: 1.7.1
  
## Reproduce
1. app.wpy
```js
export default class extends wepy.app {
  config = {
    pages: [
      'pages/index/index',
    ],
  }

  onPageNotFound(res){
    console.log('onPageNotFound:', res);
  }
}
```

2. 访问一个不存在的页面，如 pages/nonExist/nonExist
3. 查看控制台输出

### Observed Results
  控制台未打印 onPageNotFound 相关日志
 
### Expected Results
  控制台打印 "onPageNotFound {path:xxx, query: xxx, isEntryPage: xxx}"

**Comment by Gcaufy** [comment]
先可以在wepy.config.js中配置

```
appConfig: {
   appEvents: ['onPageNotFound']
}
```

**Comment by bluesky12** [comment]
好的，谢谢
