### ISSUE TITLE
循环标签script值错误

### ISSUE THREAD

**Issue by hanwenbo** [Tencent/wepy#1394]
```
<repeat for="{{page_data}}" key="index" index="index" item="item">
        <block wx:if="{{item.type === 'image_ads'}}">
          <banner :dataSource="item" />
        </block>
        <block wx:if="{{item.type === 'image_nav'}}">
          <gridNavBar :dataSource="item"/>
        </block>
      </repeat>
```
传过去 你会发现 gridNavBar 的onLoad打印dataSource永远是page_data[0]，永远是第1条item值，但gridNavBar xml使用的值是正确的，但在组件的script里是错误的

**Comment by StevenKwan** [comment]
同遇到此问题。

      <repeat for="floors" key="index" index="index" item="item">
        <floorTemplateOne :templateData="item" :syncTemplateData.sync="item"
                          wx:if="{{item['template'] === 1}}"></floorTemplateOne>
      </repeat>

通过 this.$broadcast 调用 event 后，无论有没有 wx:if="{{item['template'] === 1}}" 都只拿到了 item[0] ， item[0] 的 template 不为 1 。

**Comment by StevenKwan** [comment]
同遇到此问题。能在 <template> 拿到传值，但是 script 里的不正确。

**Comment by hanwenbo** [comment]
放弃这个问题 短期内解决不了
