### ISSUE TITLE
生成的项目在微信6.6.0版本中报错。代码一句都没执行。

### ISSUE THREAD

**Issue by 5468sun** [Tencent/wepy#1403]
## Description

 wepy build 生成的项目在微信6.6.0版本中报如下错误：
Unexpected keyword 'const'.  const declarations are not supported in strict mode.

报错导致一行代码都没有执行。

## Environment

  * Platform: [微信开发者工具/iOS]
  * Platform version: [v1.02.1804120]
  * Wechat version: [6.6.0]
  * wepy-cli version: [1.7.2-alpha2]
  * wepy version: [^1.6.0]
  * other version: [如果是插件问题，请列出问题插件的版本号]

**Comment by BoleLee** [comment]
根据报错提示解决你的代码错误呀，这不是框架的问题，也不是建议，最好不要一遇问题就开issue，毕竟不是论坛，也不是提问

**Comment by panjiangyi** [comment]
你打字打错了，兄弟。
cosnt=>const

**Comment by 5468sun** [comment]
不好意思。描述问题时打错字了，但是问题是存在的。
项目引了query-string 6，是es6语法写的。
打包的时候，query-string 直接打包到npm目录中了。没有转成es5。然后在低版本的微信中不能运行。所以导致错误。

不知道wepy如何设置 让node_modules 目录下的js也 es6->es5？

对这个具体问题临时解决方法是 query-string降成版本5。

**Comment by Gcaufy** [comment]
@5468sun 暂时还没有直接es6的npm包。
