### ISSUE TITLE
如何自动同步globalData中的变量? vue里面是会自动同步的啊

### ISSUE THREAD

**Issue by lzl124631x** [Tencent/wepy#1407]
## Description

```
// me.wpy
  <view class="userinfo-nickname">{{ globalData.userInfo.nickName }}</view>

  data = {
    globalData: wepy.$instance.globalData
  };
```
我将异步获取的用户信息放到globalData中, 现在必须要在onLoad中加入setTimeout, 调用`this.$apply()`才能显示昵称.  请问如何能自动更新?

---
我现在想把一些数据放到全局, 比方说当前用户的信息, 这个没必要存在页面里, 应该放在全局. 但是我更新globalData里面的字段, 页面不自动更新, 怎么破?

**Comment by panjiangyi** [comment]
小程序还是wepy有个广播功能，父组件向子组件发布事件。你可以查查。

**Comment by lzl124631x** [comment]
@panjiangyi 谢谢. 但是Vue中, 变量(不管全局还是局部)只要变化了, 别的组件会自动更新. 这wepy还要手动`$apply`, 这么弱? 自己广播的话, 就失去了数据绑定的便利了.

**Comment by lzl124631x** [comment]
@dgburn 我刚刚接触wepy. 只是这几天的使用体验让我很失望, 我大大高估wepy了. 局部变量只有同步的修改可以反映到view上, 异步的也要apply, globalData作为一个文档里面写的字段看起来没有任何特殊处理, 还要自己更新.

我是冲着"类vue"来的, 但是没想到跟期望差这么远. 我不指望"完全vue"开发, 但是数据绑定只实现到这种程度实在没想到.

**Comment by lzl124631x** [comment]
@kdong007 谢谢, 之前用react的时候接触过. 昨天我把tab改成了微信自带的tabBar, component改成了page, 然后页面就神奇地能自动根据globalData更新了.
