### ISSUE TITLE
自定义组件渲染极慢

### ISSUE THREAD

**Issue by panjiangyi** [Tencent/wepy#1408]
小程序进入一个页面，凡是使用了**自定义组件**的地方，**都以肉眼可见的速度渲染出UI。**
而且页面是静态的，并不是先请求数据然后渲染UI.
没使用自定义组件，UI直接写在template的地方则渲染很快。

  * Platform: [iOS/Andriod]
  * wepy version:1.71

**Comment by panjiangyi** [comment]
刚刚看到，完全静态的组件，花了好几秒才渲染出来。甚至渲染错位，用手指点一下才正常。

**Comment by ystarlongzi** [comment]
贴下代码实现

**Comment by panjiangyi** [comment]
被引入的组件：
` 
<style lang="scss">
@import '../zanui/cell.scss';

.zan-field {
  padding: 7px 15px;
  color: #333;
}

.zan-field--wrapped {
  margin: 0 15px;
  background-color: #fff;

  &::after {
    left: 0;
    border-width: 1px;
    border-radius: 4px;
  }
}

.zan-field--wrapped + .zan-field--wrapped {
  margin-top: 10px;
}

.zan-field--error {
  color: #f40;
}

/* 圆角输入框时，将边框也置红 */
.zan-field--wrapped.zan-field--error::after {
  border-color: #f40;
}

.zan-field__title {
  color: #333;
  min-width: 65px;
  padding-right: 10px;
}

.zan-field__input {
  flex: 1;
  line-height: 1.6;
  padding: 4px 0;
  min-height: 22px;
  height: auto;
  font-size: 14px;
}

.zan-field__placeholder {
  font-size: 14px;
}

.zan-field__input--right {
  text-align: right;
}
</style>
<template>
  <view class="zan-cell zan-field {{ options.error ? 'zan-field--error' : '' }} {{ options.mode === 'wrapped' ? 'zan-field--wrapped' : '' }}">
    <view
      wx:if="{{ options.title }}"
      class="zan-cell__hd zan-field__title">{{ options.title }}</view>
    <textarea
      wx:if="{{ options.type === 'textarea' }}"
      auto-height
      name="{{ options.name || componentId || '' }}"
      value="{{ options.value }}"
      placeholder="{{ options.placeholder }}"
      class="zan-field__input zan-cell__bd {{ options.right ? 'zan-field__input--right' : '' }}"
      placeholder-class="zan-field__placeholder"
      bindinput="handleZanFieldChange"
      bindfocus="handleZanFieldFocus"
      bindblur="handleZanFieldBlur"
      data-component-id="{{ componentId || '' }}"></textarea>
    <input
      wx:else
      type="{{ options.inputType || 'text' }}"
      name="{{ options.name || componentId || '' }}"
      value="{{ options.value }}"
      placeholder="{{ options.placeholder }}"
      class="zan-field__input zan-cell__bd {{ options.right ? 'zan-field__input--right' : '' }}"
      placeholder-class="zan-field__placeholder"
      bindinput="handleZanFieldChange"
      bindfocus="handleZanFieldFocus"
      bindblur="handleZanFieldBlur"
      data-component-id="{{ componentId || '' }}"/>
  </view>
</template>
<script>
import wepy from 'wepy'

export default class zanField extends wepy.component {
  props = {
    options: {
      type: Object,
      default: {
        right: true,
        error: true,
        name: '',
        value: '',
        type: 'textarea',
        mode: 'wrapped',
        title: '消费总额',
        inputType: 'number',
        placeholder: '询问收银员后输入'
      }
    },
    componentId: String
  }
  data = {}
  methods = {
    clear() {
      this.options.value = '  '
      this.$apply()
      this.options.value = ''
      this.$apply()
    },
    handleZanFieldChange(event) {
      event.componentId = this.componentId

      // console.info('[zan:field:change]', event)

      return this.$emit('zanFieldChange', event)
    },

    handleZanFieldFocus(event) {
      event.componentId = this.componentId

      // console.info('[zan:field:focus]', event)

      return this.$emit('zanFieldFocus', event)
    },

    handleZanFieldBlur(event) {
      event.componentId = this.componentId

      // console.info('[zan:field:blur]', event)

      return this.$emit('zanFieldBlur', event)
    }
  }
}
</script>
`
使用上面组件的页面：
`<style lang="scss">
@import '../../components/zanui/btn.scss';
.notice {
  color: #34aad2;
  margin-left: 30rpx;
}
.receiverPluser {
  position: relative;
  .input {
    display: flex;
    align-items: center;
    padding: 7px 15px 7px 0;
    margin-left: 15px;
    border-bottom: 1px #f4f4f4 solid;
    .title {
      color: #333;
      min-width: 65px;
      padding-right: 10px;
    }
    .inputArea {
      flex: 1;
      color: #999;
    }
  }
  .pluser {
    position: relative;
    width: 50rpx;
    height: 50rpx;
    margin: auto;
    margin-right: 10rpx;
    border-radius: 50%;
    color: #fff;
    background-color: #4b0;
  }
  .pluser:before,
  .pluser:after {
    content: '';
    pointer-events: none;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    box-shadow: inset 0 0 0 1em;
  }
  .pluser:before {
    width: 1em;
    height: 2px;
  }
  .pluser:after {
    height: 1em;
    width: 2px;
  }
}
</style>
<template>
    <view class="container">
        <form bindsubmit='submit'>
            <view class="bgWhite">
                <view class="receiverPluser">
                    <view class="input">
                      <view class="title">收款人</view>
                      <input name="receiver" class="inputArea" value="{{defaultReceiver}}" placeholder="收款人姓名" >收款人身份证号</input>
                      <view @tap="chooseReceiver" class="pluser"></view>
                    </view>
                </view>
                <id  :value.sync="base_id" inputType='number' title='银行卡'  placeholder='收款人身份证号' componentId="id" />
                <bankCard :value.sync="base_bankCard" inputType='idcard' title='身份证号' placeholder='收款人银行卡号' componentId="bankCard" />
                <amount @zanFieldChange.user="inputHandler" inputType='number' title='总金额' placeholder='转账总金额' componentId="amount" />
            </view>
            <view class="retract greyText">可转账金额{{blance}}元
                <text class="notice" @tap="withdrawALl">全部转账</text>
            </view>
            <view class="btnCon">
                <button formType="submit" class="zan-btn btnColor">下一步</button>
            </view>
        </form>
    </view>
</template>

<script>
import wepy from 'wepy';
import { connect } from 'wepy-redux';
import Utils from '../../utils/utils';
import { clearDefaultReceiver } from '../../store/actions';
import zanField from '../../components/zan/zan-field';
import authCode from '../../components/authCode';
@connect(
  {
    defaultReceiver({ wallet }) {
      const result = wallet.defaultReceiver.realName;
      console.log(result)
      return result;
    },
    base_id({ wallet }) {
      const result = wallet.defaultReceiver.cardNo;
      console.log(result)
      return result;
    },
    base_bankCard({ wallet }) {
      const result = wallet.defaultReceiver.bankNo;
      console.log(result)
      return result;
    },
    blance({ wallet }) {
      const result = wallet.blance;
      console.log(result)
      return result;
    }
  },
  {
    clearDefaultReceiver
  }
)
export default class Transfer extends wepy.page {
  config = {
    navigationBarTitleText: '转账'
  };
  components = {
    bankCard: zanField,
    amount: zanField,
    id: zanField,
    authCode
  };
  data = {
    base_amount: {
      inputType: 'digit',
      value: '',
      title: '金额',
      placeholder: '转账金额'
    }
  };
  methods = {
    inputHandler(e) {
      if (e.componentId === 'amount') {
        const allIHad = this.blance;
        const inputValue = e.detail.value;
        if (inputValue > allIHad) {
          this.data.base_amount.value = ' ';
          this.$apply();
          this.data.base_amount.value = allIHad.toString();
          this.$apply();
        }
      }
    },
    chooseReceiver() {
      Utils.naviTo('./receivers');
    },
    withdrawALl() {
      this.autoFill({
        base_amount: this.blance
      });
    },
    submit(e) {
      const { value } = e.detail;
      const { id, receiver, bankCard, bank, amount } = value;
      if (this.needMoreValues(value)) return;
      Utils.naviTo(
        `./confirmTransfer?id=${id}&receiver=${receiver}&cardNumber=${bankCard}&amount=${amount}`
      );
    }
  };
  autoFill(obj) {
    const k_domain = [
      'base_receiver',
      'base_id',
      'base_bankCard',
      'base_amount'
    ];
    for (let k in obj) {
      if (k_domain.indexOf(k) === -1) continue;
      this[k].value = obj[k];
    }
    this.$apply();
  }
  needMoreValues(v) {
    const { id, receiver, bankCard, amount } = v;
    if (Utils.nameIsWrong(receiver)) {
      return true;
    } else if (Utils.bankcardNumIsWrong(bankCard)) {
      return true;
    } else if (Utils.idIsWrong(id)) {
      return true;
    } else if (Utils.amountIsWrong(amount)) {
      return true;
    }
    return false;
  }
  onUnload() {
    this.methods.clearDefaultReceiver();
  }
}
</script>
`

**Comment by panjiangyi** [comment]
看了下你们推荐的wepy项目例子，也有同样的问题。
不过他们先隐藏了页面和组件，需要时才显示，就避免了加载慢很丑的问题。
而且似乎微信更新后这个问题消失了，不过我只在我自己的手机上试了下。
这个issue我关了吧。
