### ISSUE TITLE
globalData字段有什么特殊待遇么?

### ISSUE THREAD

**Issue by lzl124631x** [Tencent/wepy#1411]
我想问wepy中的globalData字段有什么特殊待遇么? 跟自己创建一个对象自己维护有什么区别? 关于globalData字段的讲解, 文档里几乎没有.

**Comment by lzl124631x** [comment]
我现在想把一些数据放到全局, 比方说当前用户的信息, 这个没必要存在页面里, 应该放在全局. 但是我更新globalData里面的字段, 页面不自动更新, 怎么破?

**Comment by lzl124631x** [comment]
我发现小程序官方文档里面也有globalData, 看起来没什么特别的.

**Comment by ChangeZhang** [comment]
我更新globalData里面的字段, 页面不自动更新, 怎么破?

**Comment by lzl124631x** [comment]
@ChangeZhang 当页面onShow的时候加载自己想要的那部分吧, 页面可以响应自己的`data`字段的变化.
