### ISSUE TITLE
wepy-cli版本1.7.2编译出错

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#1416]
wepy版本：1.7.2-alpha1 
wepy-cli版本：1.7.2
![image](https://user-images.githubusercontent.com/12985781/40576076-33e29b94-6123-11e8-8130-73a9f5a68d38.png)

但是如果wepy-cli版本是1.7.2-alpha1 就不会报错

**Comment by Ryuurock** [comment]
😂😂😂😂😂😂
