### ISSUE TITLE
component能否引用page?

### ISSUE THREAD

**Issue by lzl124631x** [Tencent/wepy#1417]
我用component实现的Tab, 其中一个Tab, 名为me, 我想使用onShow事件, 所以我将Tab me从component改成了page, 然后我的tab组件就无法正确加载Tab me了. 

```
thirdScriptError 
 sdk uncaught third Error 
 module "pages/me.js" is not defined 
 Error: module "pages/me.js" is not defined
```
是因为component无法加载page么?

**Comment by towry** [comment]
你是想组件内嵌页面？我想框架肯定是不支持的。建议在组件外面监听组件的显示以及更改组件的状态数据。

**Comment by lzl124631x** [comment]
@towry 谢谢, 我还比较新手, 昨天看了一下小程序自己的文档, 好像也是不支持的. 需要从页面级别入手了.
