### ISSUE TITLE
关于globalData 获取 undefined

### ISSUE THREAD

**Issue by cam510** [Tencent/wepy#1418]
## Description

  各位好，我init项目后，在app.wpy上面添加了这一行代码：
  globalData = {
      userInfo: null, 
      globalText: 'globalText'
  }
  然后在index.wpy上面onLoad获取
  console.log('globalText is ' + this.$parent.globalText)
  控制台上面打印的信息是：globalText is undefined

## Environment

  * Platform: [开发者工具]
  * Platform version: [1.02.1805181]
  * Wechat version: [6.6.0]
  * wepy-cli version: [wepy-cli 1.7.2]
  * wepy version: [^1.6.0]

**Comment by towry** [comment]
查看这里的解答： https://segmentfault.com/q/1010000013102312 能不能帮助你。

**Comment by cam510** [comment]
@towry 哦，我漏了globalData，
可以了，谢谢
