### ISSUE TITLE
uploadFile上传文件监听问题

### ISSUE THREAD

**Issue by Chen120322** [Tencent/wepy#1419]
开启promise后，uploadFile就无法返回uploadTask对象，文档也没说明，请问开启promise后怎么解决监听上传问题

**Comment by cdll** [comment]
看了下测试用例在[这里](https://github.com/Tencent/wepy/blob/a60e44b3483740502f9b5d5293f95f99d3ec8466/packages/wepy/test/app.js#L259-L275), 不知道测试能不能通过的~

**Comment by dongfg** [comment]
今天也遇到这个问题了，看了下[源代码](https://github.com/Tencent/wepy/blob/0a8f6abe526e0a02f1b1a5e2d99d1a56f4cf9f30/packages/wepy/src/app.js#L196)，用 `progress` 这个方法
```
const uploadTask = wepy.uploadFile({
  url: 'http://localhost:20000/wechat/image/upload',
  filePath: image,
  name: 'file'
})

uploadTask.progress((res) => {
  console.log('上传进度', res.progress)
  console.log('已经上传的数据长度', res.totalBytesSent)
  console.log('预期需要上传的数据总长度', res.totalBytesExpectedToSend)
})
```
