### ISSUE TITLE
加载外部npm包时无法加载动态引入的文件

### ISSUE THREAD

**Issue by GreedyBlade** [Tencent/wepy#1425]
目前wepy中加载外部npm包时是根据依赖递归查找包，但是如果外部npm包中有一部分依赖是动态加载的，例如validatorjs中的语言文件，就会导致动态加载的部分无法被编译到dist目录下，希望能优化一下

**Comment by ericpengfan** [comment]
解决了没？也遇到这个问题，npm  加载一个包。编译一直报错。 想通过小程序去搞个钱包，引入WEB3.JS 一直报错
