### ISSUE TITLE
less 变量和 mixins 引用无效问题

### ISSUE THREAD

**Issue by Rubicker** [Tencent/wepy#1428]
## Description

目录如下：

```bash
├── src
│   ├── apis
│   │   └── homepage.js
│   ├── app.wpy
│   ├── components
│   │   └── todo.wpy
│   ├── icons
│   │   ├── icon-mypage-active.png
│   │   ├── icon-mypage-default.png
│   │   ├── icon-school-active.png
│   │   ├── icon-school-default.png
│   │   ├── icon-search-active.png
│   │   └── icon-search-default.png
│   ├── images
│   ├── mixins
│   │   └── test.js
│   ├── pages
│   │   ├── index
│   │   │   └── index.wpy
│   │   ├── jobs
│   │   │   └── jobs.wpy
│   │   ├── mypage
│   │   │   └── mypage.wpy
│   │   └── playground
│   │       └── playground.wpy
│   ├── styles
│   │   ├── _base.less
│   │   ├── _index.less
│   │   └── _mixins.less
│   └── utils
│       └── _common.js
```

在 `_base.less` 中定义了变量，在 `_mixins.less` 中定义了 mixins，在 `_index.less` 中引入两者：

```less
// ./src/styles/_index.less
@import '_base';
@import '_mixins';

// 这条规则是可以生效的
page {
  background-color: #000;
}
```

然后在 `app.wpy` 中引入 `_index.less`：

```html
 <!-- ./src/app.wpy -->
<style lang="less">
@import './src/styles/_index.less';
</style>
<script>
 // 省略
</script>
```

已知问题：

- 在任意一个 page `index.wpy`, `jobs.wpy`, `mypage.wpy` 或者 `playground.wpy` 中都无法获取到变量或者 mixins。

  报错 `某个变量 is not defined`， **但是 `page {
  background-color: #000;
}` 可以生效** 

- 如果在任意 pages 中直接引用 `_index.less` 的话是 ok 的。

如果这不是 bug 的话，请教各位有没有更好的引入变量或者 mixins 的方法（无需每个页面都引用一次）

## Environment

  * Platform: 开发者工具
  * Platform version: 1.02.1805150
  * Wechat version:  /
  * wepy-cli version: 1.7.2
  * wepy version: 1.7.1
  * other version: /
  
## Reproduce

   如上描述
  

## Relevant Code / Logs

   如上描述

**Comment by dlhandsome** [comment]
不能算bug吧，因为less本身不会检测Page与APP样式的依赖关系

**Comment by Rubicker** [comment]
@dlhandsome 噢噢，多谢，明白了。所以全局样式必须得每个页面文件都引入是吗？

**Comment by guobing1993** [comment]
我也遇到这个问题，期待的是定义的全局less变量在app.wpy中引入一次，在其他style中都可以访问到。

**Comment by hzysoft** [comment]
同问
