### ISSUE TITLE
Promse.all不能异步

### ISSUE THREAD

**Issue by mwanglur** [Tencent/wepy#1431]
![p a5y1imz2x yg x qg6np](https://user-images.githubusercontent.com/10104734/40763968-952aca02-64d9-11e8-93ef-cfc3ae0595a3.png)

在使用的过程中发现总耗时=trip+mylikes两个接口的时间

trip我模拟5s  mylikes模拟3s 期待的是5s内返回结果，即mylikes不用等到trip返回再执行，但是实际却是大于8s返回结果。

**Comment by Gcaufy** [comment]
实在是想去验证是不是Promise.all的问题，用两个简单的setTimeout去模拟就行了。

这个问题跟小程序没有半毛钱关系。纯粹的javascript的问题。
好好的去检查一下是不是接口延时模拟错了，还是后端阻塞了吧。
