### ISSUE TITLE
增加类似v-model功能

### ISSUE THREAD

**Issue by lak110110** [Tencent/wepy#1433]

**Comment by shiny** [comment]
期待

**Comment by Gcaufy** [comment]
v-model 会在2.0中支持到。

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/blob/2.0.x/packages/cli/core/plugins/template/directives/model.js#L191

**Comment by akiJoin** [comment]
checkbox radio 怎么实现v-model，2.x还是不行呀，提示checkbox不支持v-model
