### ISSUE TITLE
import scss in wpy

### ISSUE THREAD

**Issue by tinybright** [Tencent/wepy#1434]
splash.wpy
<style lang="css">
    @import "../../custom/splash.scss";
</style>

custom/splash.scss
...

这种情况必须要写import /custom/splash.wxss。
使用import /custom/splash.scss，build后import不会替换为wxss

**Comment by Gcaufy** [comment]
lang="css"时，不会编译内里的内容。

**Comment by fengxinming** [comment]
可以引入stylus
