### ISSUE TITLE
组件中的wxml不会自动编译

### ISSUE THREAD

**Issue by cheerylong** [Tencent/wepy#1438]
## Description

  wepy组件的template使用外部的wxml文件，修改wxml文件后，不会编译源文件，必须手动重新编译

## Environment

  * Platform: [开发者工具/]
  * Platform version: [v1.02.1805181]
  * wepy-cli version: [1.7.2]
  * wepy version: [查看node_modules为1.7.1]
  
## Reproduce

  [如何重现问题]
  使用wepy初始化一个项目,将任意组件的template中的wxml抽成单独的wxml文件，再引入这个单独的文件，例如叫test.wxml
  如果修改该wxml文件，项目不会将修改的部分编译至源码
![image](https://user-images.githubusercontent.com/13464852/40830411-f2dd2f34-65b8-11e8-938d-53b07565fb9b.png)

### Observed Results

  [实际表现]
  
### Expected Results

  [期望表现]
  可以正常编译组件中引入的wxml文件

**Comment by cheerylong** [comment]
还有人维护吗？？？？？？？？？？？？？？

**Comment by Jimexist** [comment]
related: https://github.com/Tencent/wepy/issues/1500
