### ISSUE TITLE
能否实现page的继承?

### ISSUE THREAD

**Issue by lzl124631x** [Tencent/wepy#1441]
~~我实现了page的script继承, 但是父page的template部分无法被子page继承. 或者没有办法让子page拓展父page的template. 现在我只能用父page去实现script部分的复用, template部分要做成component.~~

我发现page的script继承也有问题, 父page的data无法被子page继承.

**Comment by Gcaufy** [comment]
page 的继承只是指的script部分的继承，因此基类定义成一个js文件就好了。
继承就是OOP的继承的，没有区别。

**Comment by cgygd** [comment]
template可以实现继承吗？
