### ISSUE TITLE
如果引入 wepy-async-function ，导致编译到支付宝小程序报错（生成npm目录下wepy-async-function 下的两个js文件都没有内容）

### ISSUE THREAD

**Issue by nightost** [Tencent/wepy#1442]
# 问题描述
如果引入 wepy-async-function ，导致编译到支付宝小程序报错（生成npm目录下wepy-async-function 下的两个js文件都没有内容）
# 报错信息
```[WORKER] onerror Uncaught Error: Module build failed: TypeError: Cannot read property 'length' of null```

**Comment by minzhang2** [comment]
解决了么@nightost

**Comment by nightost** [comment]
没有，暂时不使用async，不影响

**Comment by shic** [comment]
wepy-async-function 是官方包么？官方guide 上 https://github.com/Tencent/wepy/wiki 是建议用这个，但是这个包的npm对应的GitHub地址都没有了。。。 这wepy 靠谱么？
