### ISSUE TITLE
小白请问，wepy有没有类似getElementById获取样式属性的方法？

### ISSUE THREAD

**Issue by cam510** [Tencent/wepy#1443]
## Description
请问wepy有没有类似getElementById获取样式属性的方法呢？
假设我有样式为：
css:
.style_class {
    width: 100px;
    height: 100px;
}
<template>
<view class="style_class"></view>
</template>

js:
onLoad() {
    ?? 怎么获取 宽高 100 x 100 ??
}

 
## Environment

  * Platform: [开发者工具]
  * Platform version: []
  * Wechat version: [6.6.0]
  * wepy-cli version: [1.7.2]
  * wepy version: [1.7.2]

**Comment by Gcaufy** [comment]
不好意思，小程序原生就无法支持这个需求，所以没有办法做到

**Comment by cam510** [comment]
@Gcaufy 好的，谢谢
