### ISSUE TITLE
props传值

### ISSUE THREAD

**Issue by ZhengKehang** [Tencent/wepy#1444]
props传值，在父组件中data中定义的数据可以在子组件的onLoad里面获取到。
现在：
data={
obj：{key：value}
}
支持：：props.sync="obj"并且在子组件onLoad里获取
但如果这样写：props.sync="obj.key"就传值失败
期望表现：
支持以对象的属性方式来传值。

**Comment by ZhengKehang** [comment]
props传值，如果传一个字符串，在子组件的onLoad里面可以获取到值。但如果以obj.name的形式传字符串，传值不成功也无法获取。同时尝试了一下，传Object时无法在onLoad里面获取到该对象。

**Comment by ZhengKehang** [comment]
好吧，再尝试了一下是，子组件先执行onLoad导致的，我写的对象是在父组件的onLoad里面获取的，只要把object写在data里面就可以了，但这样就做不到根据后台数据实时更新了吗？

**Comment by ZhengKehang** [comment]
支持父组件动态传值，能够在父组件onLoad里更新传值，限制就是不能以对象属性的形式传值

**Comment by cji03** [comment]
1. 提issue前你可以搜索一下有无相同issue，这个问题被提了无数次了。
2. 提问前先做好准备工作，你这描述看的很难受。
