### ISSUE TITLE
invoke使用时，填写的路径跟官方介绍的不一样

### ISSUE THREAD

**Issue by shiran1992** [Tencent/wepy#1447]
看完源码之后，突然感觉invoke的使用，跟官方说的不一样，而且按照官方介绍的路径不行。
很明显，是将我们填写的路径按照‘/’来拆分成数组，而com的值主要是根据数组的第一位，而且一定要理解‘’，‘.’，‘..’的不同含义。
![1528090042 1](https://user-images.githubusercontent.com/16955920/40957469-faf84728-68c7-11e8-8442-52833aa13fcc.jpg)

**Comment by Gcaufy** [comment]
哪里有问题？

**Comment by shiran1992** [comment]
![1528421554 1](https://user-images.githubusercontent.com/16955920/41134445-ec559e30-6afe-11e8-8ee8-0156d5b9c177.jpg)
组件ComA中调用组件ComG的某个方法
官方提供方案：this.$invoke('./../ComB/ComG', 'someMethod', 'someArgs');我试了一下，这样并没有调用成功；
看完源码，我使用了：this.$invoke('/ComB/ComG', 'someMethod', 'someArgs');则可以

**Comment by shiran1992** [comment]
我理解的应该跟你一样，应该是由数组的第一位来选择，是parent，root还是this，所以才觉得官方给的这个方法（this.$invoke('./../ComB/ComG', 'someMethod', 'someArgs');）应该有问题；

**Comment by panjiangyi** [comment]
我试了下，路径的点和点点，只能用一次回溯一层。
不知道为什么这么弄，可能是因为不在一个目录里的组件还没创建或已经被销毁了，没必要回溯那么多吧
