### ISSUE TITLE
引用组件库 wepy 编译 dist 目录并没有正确追踪依赖

### ISSUE THREAD

**Issue by Onlylonger** [Tencent/wepy#1449]
想基于wepy 开发个ui 库, 已经发布到 npm 上
npm: [wepy-ui-ydj](https://www.npmjs.com/package/wepy-ui-ydj)
github: [wepy-ui-ydj](https://github.com/YDJ-FE/wepy-ui-ydj)
但是 wepy init empty xx 项目中引入，编译的dist 文件并未引入 wpy 后缀组件:

![image](https://user-images.githubusercontent.com/19505200/40974969-f22114ac-68fb-11e8-9041-7d8c727112c0.png)

求解，谢谢🙏
@Gcaufy

**Comment by Onlylonger** [comment]
自顶下

**Comment by Gcaufy** [comment]
```
import Button from 'wepy-ui-ydj/src/components/Button.wpy'
```

**Comment by Onlylonger** [comment]
我这边还是找不到相关依赖:
![image](https://user-images.githubusercontent.com/19505200/41134705-6407f440-6b00-11e8-8fed-2e7eb62f5398.png)

github地址: https://github.com/Onlylonger/wepy-demo

**Comment by Gcaufy** [comment]
Fixed in: https://github.com/Tencent/wepy/commit/2de1187f0332b30f6a7600037cad4ce42e3da168
Released in: wepy-cli@1.7.3-alpha2

**Comment by Gcaufy** [comment]
两种使用方式：

1. 直接引用路径
```
import Button from 'wepy-ui-ydj/src/components/Button'
```

2. 使用mainFields

在`wepy-ui-ydj` 的npm 包的 package.json 中加入
```
"wepy": {
    "./Button": "./src/components/Button.wpy"
 },
```
代码中引用 
```
import Button from 'wepy-ui-ydj/Button'
```
