### ISSUE TITLE
formId  主动触发表单提交的问题

### ISSUE THREAD

**Issue by heath-l** [Tencent/wepy#1452]
`<form class="formClick" report-submit='true' @tap.submit='fanliBtnClick'>

        <view class="btn-container">

            <button formType="submit"></button>

            <view class="top-fanli-btn" @tap="ddd">dianji

            </view>
        </view>
    </form>`

`methods = {

      fanliBtnClick(e) {

          console.log(e);

          saveFormId.saveFormId(e.detail.formId);

      },
}`

这里点击可以走提交这个方法，拿到e。。。但是我怎么在onLoad里面已经来就主动提交一次，拿到这个e呢？。

**Comment by robinv8** [comment]
这是不行的，formId必须通过用户点击才能生成

**Comment by heath-l** [comment]
@robinv8 那我onload后 做一个用户点击这个表单提交的事件。。这种方法可以实现吗？

**Comment by robinv8** [comment]
可以，只要通过用户点击，就能获得formId

**Comment by heath-l** [comment]
@robinv8 不是。。。我是想在onload开始里面模拟一个点击事件来触发这个提交事件

**Comment by robinv8** [comment]
不可以的
