### ISSUE TITLE
$wxapp 获取globalData 的问题

### ISSUE THREAD

**Issue by suchao2007** [Tencent/wepy#1453]
## Description

 在page页面用this.$wxapp.globalData 获取不到 globalData？

用this.$parent.globalData 可以

============app.wpy
globalData = {
    userInfo: {a: 999}
  }

============index.wpy
console.log(this.$wxapp.globalData)

**Comment by panjiangyi** [comment]
```js
        if (this.$isComponent) {
            this.$root = $root || this.$root;
            this.$parent = $parent || this.$parent;
            this.$wxapp = this.$root.$parent.$wxapp;
        }
```
