### ISSUE TITLE
wepy 调用原生api fail／complete的回调怎么处理

### ISSUE THREAD

**Issue by xuweikang** [Tencent/wepy#1459]
请教下，wepy怎么处理调用原生api fail的回调

例如：wx.chooseImage({}) 原生的api里面出了success的回调，还有fail/complete的回调
如果我想用async/await 去调api
`let res = await wepy.chooseImage({});`
怎么去写 fail/complete的回调呢

**Comment by Gcaufy** [comment]
fail 就用 try catch 
没有complete, 需要complete 的话还是用 wx.xxxx吧
