### ISSUE TITLE
关于cliLogs导致IOS8.1.3版本出现非法字符报错的问题

### ISSUE THREAD

**Issue by coolhwm** [Tencent/wepy#1460]
## Description

开启cliLogs=true， npm run build编译后，IOS8.1.3真机提示非法字符错误，程序无法启动
![image](https://user-images.githubusercontent.com/20462043/41187876-3b2088da-6be6-11e8-95ab-8868342bacac.png)

经过观察是生成的`_wepylogs.js`文件中，使用了字符串模板，在低版本中无法执行导致启动直接报错

```
console.log('WePY开启错误监控');
console.error(`CLI报错：
F:\\Development\\workspace\\leshare\\leshare-food-weapp\\src\\components\\bargain\\bargain_info_bar.wpy
  90:30  error  Infix operators must be spaced  space-infix-ops

✖ 1 problem (1 error, 0 warnings)
`);
```

## Environment

  * Platform:  Windows
  * Platform version: IOS8.1.3
  * Wechat version:  6.6.7
  * wepy-cli version: 1.7.0
  * wepy version: 1.7.0
  
## Reproduce

-   开启cliLogs: true
-   编译程序 npm run build
-   真机扫码预览

### Observed Results

启动提示非法字符错误
  
### Expected Results

生产编译无需注入cliLogs，或不使用字符串模板的语法

**Comment by Gcaufy** [comment]
先在wepy.config.js 里把cli 设置成false
