### ISSUE TITLE
自定义组件 observer问题

### ISSUE THREAD

**Issue by xuweikang** [Tencent/wepy#1461]
使用动态属性传值，能发现此时属性值发生了改变，但是没有执行observer函数
![image](https://user-images.githubusercontent.com/17662706/41217936-00f19166-6d8c-11e8-8b31-e9e089b0ec1d.png)

![image](https://user-images.githubusercontent.com/17662706/41217964-205f49b2-6d8c-11e8-93a3-0a0f69a31114.png)

**Comment by xuweikang** [comment]
可以发现，2s后 selectDocIndex的值已经变成22222(这部分就没截图了)，但是observer没执行

**Comment by xuweikang** [comment]
@Gcaufy

**Comment by Gcaufy** [comment]
不存在`observer`这个方法，试试 `coerce`

**Comment by lingsang2** [comment]
@Gcaufy coerce没绑定this
