### ISSUE TITLE
ext.json不在replace插件的替换范围么?

### ISSUE THREAD

**Issue by fitcong** [Tencent/wepy#1465]
我这边需要动态更换ext.json的内部内容,应该怎么配置呢

**Comment by Gcaufy** [comment]
看一下你的文件结构，以及你如何配置replace插件的。

**Comment by fitcong** [comment]
![image](https://user-images.githubusercontent.com/23007631/41272909-c3240454-6e49-11e8-9cf0-9dc1b7a445e8.png)
![image](https://user-images.githubusercontent.com/23007631/41272925-dd46dce4-6e49-11e8-99bc-95a2b1cc76da.png)
按照这个配置只能检测到app.json
