### ISSUE TITLE
已解决--swiper 通过wepy赋值 动态指定current无效

### ISSUE THREAD

**Issue by SuperKevinZhang** [Tencent/wepy#1466]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
         swiper 通过wepy赋值 动态指定current无效
  [Description of the issue]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号] v 1.02 
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里] 1.6.0
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]

 template:
swiper  current="{{currentIndex}}" class="swiperH"

javascript:
  this.currentIndex=1;
  this.$apply();

  [实际表现]
  current 没有更新成1 

  [期望表现]
   <swiper  current="1" class="swiperH">
  

## Relevant Code / Logs
解决方法:
 通过原生赋值的方式绑定
this.setData({ currentIndex:1});

**Comment by Gcaufy** [comment]
是不是因为 currentIndex 没有在 data 中声明？
如果有的话，那么与 setData 效果是一样的。

**Comment by SuperKevinZhang** [comment]
data={
      author:null,
      currentIndex:1,
声明過了.你可以試一下

**Comment by Gcaufy** [comment]
建议提供代码片断这样我比较方便调试。
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
