### ISSUE TITLE
页面引入mixins后，onShareAppMessage的参数被包在了数组里面

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#1468]
如图所示：mixins里没有定义onShareAppMessage，页面定义了。
![image](https://user-images.githubusercontent.com/12985781/41275690-492dc79c-6e54-11e8-93b9-b3a51c0bbff5.png)

**Comment by nigelvon** [comment]
和楼主的问题一样。

**Comment by nigelvon** [comment]
开发人员为啥不来回复一下呢？
