### ISSUE TITLE
$apply 渲染结束回调

### ISSUE THREAD

**Issue by bluesky12** [Tencent/wepy#1470]
## Description
  小程序原生语法中 setData 支持传入一个回调函数，可以监听数据渲染结束的时机，便于进行一些有界面依赖的交互。
  wepy的$apply似乎没有提供对应的能力，是否可以考虑予以添加？
 
## Reproduce
1. 原生小程序
```js
onReady: function () {
    //修改数据
    let imgs = [];
    for (let i=0; i<100; ++i)
      imgs.push(`https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940&v=${i}`);

   //使修改生效
    console.log('about to setData'); //开始setData
    this.setData({
      imgs
    }, ()=>{
      console.log('setData render over callback'); //视图层渲染结束回调
    });

    console.log('setData over'); //逻辑层setData结束
  },
```

2. wepy
```js
  async onReady(){
      //修改数据
      this.imgs = [];
      for (let i=0; i<10; ++i)
        this.imgs.push(`https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940&v=${i}`);

      //使修改生效
      console.log('about to apply'); //开始apply
      this.$apply(()=>{
        console.log('apply callback'); //apply回调
      });
      console.log('apply over'); //逻辑层apply结束
    }
```
### Observed Results
1. 原生小程序
控制台输出：
![image](https://user-images.githubusercontent.com/10047420/41290877-b74ad900-6e80-11e8-9fb2-67472bdb2cc7.png)

2. wepy
控制台输出：
![image](https://user-images.githubusercontent.com/10047420/41290362-3e5c22fc-6e7f-11e8-87df-7063d6a27cd7.png)

可以看到，setData中传入的回调函数是在视图层渲染完毕后才回调执行的（setData与callback日志输出间隔了约80毫秒），而$apply中传入的函数则是立刻执行，并没有去监听视图层渲染进度。

### Expected Results
$apply回调时序跟setData一样，在视图层渲染完毕后再执行。

**Comment by BelinChung** [comment]
`this.$nextTick()`

**Comment by panjiangyi** [comment]
this.$$nextTick();

**Comment by bluesky12** [comment]
**this.$nextTick 也是立刻回调的，并没有等待视图层渲染结束。**

**Reproduce**
------------------------------------------------------------------
wepy
```js
async onReady(){
      //修改数据
      this.imgs = [];
      for (let i=0; i<100; ++i)
        this.imgs.push(`https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940&v=${i}`);

      //使修改生效
      console.log('about to apply'); //开始apply
      this.$apply(()=>{
        console.log('apply callback'); //apply回调
      });
      this.$nextTick(()=>{   //nextTick回调
        console.log('nextTick callback');
        wx.pageScrollTo({  //回调中将页面滚至底部
          scrollTop: 65*99,
          duration: 0
        });
      });
      console.log('apply over'); //逻辑层apply结束
    }
```

**Observed Results**
-------------------------------------------
1.  控制台输出：
![image](https://user-images.githubusercontent.com/10047420/41335544-b9cee824-6f1b-11e8-9c51-f07d94e2c6d9.png)
可以看到nextTick回调跟$apply只相差了几毫秒，并没有像setData一样等待视图层渲染（至少几十毫秒）。

2. 页面行为：  
    wepy：图片从0张变为100张，页面始终处于顶部，未滚动至底部
    原生： 图片从0张变为100张，然后页面滚至底部  

    可以看到，setData时序为：数据更新 - 渲染结束 - setData回调 - 设置滚动位置 - 滚至页面底部；  
    而nextTick的时序为：数据更新 - $nextTick回调 - 设置滚动位置 - 文档高度不足，滚动失败 - 数据渲染结束 - 图片更新，页面仍处于顶部 

**Conclusion**
---------------------------
所以，this.$nextTick并没有满足监听视图层渲染结束时机的需求。

**Comment by Gcaufy** [comment]
@bluesky12 
https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy/src/component.js#L625-L647

apply时，如果没有脏数据，nextTick 是直接被调用。如果有脏数据时，nextTick 是会当成 setData 的callback参数调用的。

**Comment by bluesky12** [comment]
发现先后连续调用this.$apply、this.$nextTick，或先后连续调用this.$nextTick、this.$apply，都会导致nextTick立刻回调；  
单独调用this.$nextTick，则效果符合预期。  
谢谢各位。
