### ISSUE TITLE
使用redux引入lodash依赖，lodash压缩以后也太大了，有什么办法优化减小lodash依赖的体积

### ISSUE THREAD

**Issue by ChenHui15** [Tencent/wepy#1471]
使用redux引入lodash依赖，lodash压缩以后也太大了，有什么办法优化减小lodash依赖的体积

**Comment by ChenHui15** [comment]
已有方案解决

**Comment by sharpzhao** [comment]
请问什么方案解决的呢？？我也遇到同样的问题

**Comment by ChenHui15** [comment]
@sharpzhao  我修改了redux-actions放弃使用除handleAction以外其他的方法，lodash依赖大概能减小为200k左右，修改package.json执行dev和bulid前用修改后的js替换掉node_modules中redux-actions/lib/index.js。

**Comment by samuraime** [comment]
文件系统查看的代码会偏大。开发者工具压缩后代码实际上只有50k左右的样子，不过确实比redux-actions.min.js的30k大一些。可以考虑直接引入压缩后的。
