### ISSUE TITLE
小白请教：为什么js文件在项目src 跟 dist 上面大小不一样

### ISSUE THREAD

**Issue by cam510** [Tencent/wepy#1474]
## Description
   各位好，小白请教一个问题：我在项目上加入了极光的小程序js文件，改文件96k，然后项目离奇大了很多，找了很久发现编译后发现dist下的极光的小程序js文件占了400k+。想请教一下有什么方法压缩一下或者避免该问题吗？
## Environment

  * Platform: [开发者工具]
  * Platform version: []
  * Wechat version: [6.6.0]
  * wepy-cli version: [1.7.2]
  * wepy version: [1.7.2]

**Comment by Gcaufy** [comment]
一般都是因为生成了sourcemap 导致的。。。
建议你了解一下 wepy.config.js 中的配置。
你运行`npm run build` 会压缩
