### ISSUE TITLE
关于本地音乐mp3不能播放

### ISSUE THREAD

**Issue by cam510** [Tencent/wepy#1476]
## Description

  今天突然发现放一个mp3文件在src里面是显示正常大小，但是dist里面的mp3文件为0byte，而且调用innerAudioContext不能播放且不报错

## Environment

  * Platform: [开发者工具]
  * Platform version: []
  * Wechat version: [6.6.0]
  * wepy-cli version: [1.7.2]
  * wepy version: [1.7.2]

**Comment by Gcaufy** [comment]
```
 $ ls -la dist/*.mp3
-rw-r--r--  1 gcaufy  staff  1305 Jun 13 16:41 dist/app.mp3
```

刚才试了一下，并不能还问题

**Comment by cam510** [comment]
@Gcaufy 今天突然有显示正常大小了，但是使用innerAudioContext 还是不能播放资源哦

**Comment by Gcaufy** [comment]
对比一下内容 看看有没有变化 ，看看是不是文件被破坏。

**Comment by cam510** [comment]
@Gcaufy 没有变化，执行play() 连 onPlay（）的监听都不执行 onError（）也没有执行到

**Comment by Gcaufy** [comment]
看看是否原生的问题，看起来问题好像和wepy关系不大。

**Comment by cam510** [comment]
@Gcaufy 好的，谢谢
