### ISSUE TITLE
升级了wepy到1.7.2，编译出错，提示 ：CLI报错：TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by wmbox001** [Tencent/wepy#1477]
使用1.7.0写的小程序，修改之后，提示升级wepy-cli，升级之后，编译出错。

## Environment

  * Platform: [开发者工具]
  * Platform version: [1.02.1803210]
  * Wechat version: [6.5]
  * wepy-cli version: [wepy-cli -v 1.7.2]
  * wepy version: [在package.json里 ^1.60]
  * other version: [如果是插件问题，请列出问题插件的版本号]

使用1.7.0写的小程序，修改之后，提示升级wepy-cli，升级之后，编译出错。
  CLI报错：TypeError: Cannot read property 'toString' of undefined
    at new Input (C:\Users\weishaoming\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\postcss\lib\input.js:51:24)
    at parse (C:\Users\weishaoming\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\postcss\lib\parse.js:21:17)
    at new LazyResult (C:\Users\weishaoming\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\postcss\lib\lazy-result.js:70:24)
    at Processor.process (C:\Users\weishaoming\AppData\Roaming\npm\node_modules\wepy-cli\node_modules\postcss\lib\processor.js:117:12)
    at scopedHandler (C:\Users\weishaoming\AppData\Roaming\npm\node_modules\wepy-cli\lib\style-compiler\scoped.js:19:63)
    at C:\Users\weishaoming\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile-style.js:114:49
    at <anonymous>

  [实际表现]
  如上报错信息

  [期望表现]
  
能让我的项目正常执行。

**Comment by wmbox001** [comment]
我重新创建项目，然后把原来项目的src完全拷贝到新项目中，再加上wepy-compiler-sass ，就可以了。

**Comment by Gcaufy** [comment]
可以给查看一下
 C:\Users\weishaoming\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile-style.js:114:49
这附近代码么？
我看看是什么问题

**Comment by wmbox001** [comment]
[https://www.wsmbox.com/static/cs.jpg](url)

**Comment by Gcaufy** [comment]
所以就应该在114行打个断点，然后看看是不是css的值为空，如果是，那继续看为什么css的值为空。

**Comment by Gcaufy** [comment]
这种undefined的错误能还原的话 一分钟 就能定位到问题的。可以尝试自己定位一下。

因为我没有办法还原问题。只能通过源码猜测。

调用postcss 是因为你在添加 了scope 属性。 报错信息可以看出应该是 这里的 css 为undefined.

https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy-cli/src/compile-style.js#L99

所以看一下是不是因为传入的css content 为undefined呢？

**Comment by chenillen** [comment]
去掉 scoped 之後就沒問題了，但是在1.7.2之前的版本是沒有這個錯誤的。並且在 scoped 屬性下的 css 都完整。

```
<style lang="scss" scoped>
@import "../assets/styles/variables";
@import "../assets/styles/mixins";

.page-header {
    position: relative;
    z-index: 1001;
    width: 100%;
    height: 86rpx;

    .page-menu {
        position: absolute;
        width: 54rpx;
        min-width: 54rpx;
        max-width: 54rpx;
        height: 36rpx;
        min-height: 36rpx;
        max-height: 36rpx;
        left: 40rpx;
        top: 24rpx;

...
</style>
```

**Comment by chenillen** [comment]
這個問題找到了，是 wepy-sass-compiler 的版本低了，記得升級到1.7.2的時候，同時升級 compiler
`"wepy-compiler-sass": "^1.3.12",`
