### ISSUE TITLE
wepy 中使用了echarts-for-weixin 编译web后报错，wx.version不存在，

### ISSUE THREAD

**Issue by acegank** [Tencent/wepy#1478]
错误消息：index.js:1778 Uncaught TypeError: Cannot read property 'version' of undefined

定位了下跑到 const version = wx.version.version.split('.').map(n => parseInt(n, 10));  

 请问怎么解决

**Comment by acegank** [comment]
把wx打印出来后发现里面没有version方法。。。

**Comment by acegank** [comment]
@Gcaufy ec-canvas.js

**Comment by Gcaufy** [comment]
编译web时，事实上不存在 wx 的基础库的。所以 wx.version.version 也就没有了意思。
所以建议你在业务代码中对他进行一下赋值

```
if (wepy.platform !== 'weapp') {
   wx.version.version = '1.9.2';
}
```

**Comment by acegank** [comment]
@Gcaufy 即使这样规避掉，ec-canvas里还是有大量的wx，比如：wx.createCanvasContext 就报错了

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/tree/2.0.x/packages/wepy-web

这是一个比较大的工程，这里有目前以实现的 API. 没有实现的可以提交issue 或者 帮助 pr 一起完善这个功能。
