### ISSUE TITLE
提供原生组件demo

### ISSUE THREAD

**Issue by samuraime** [Tencent/wepy#1479]
## Description

  不能使用原生组件，或者是我的姿势不对、开发环境不正确，烦劳能细化文档  
 看了 [文档](https://github.com/Tencent/wepy/blob/component/docs/md/doc.md#%E7%BB%84%E4%BB%B6)还是不甚明了组件声明方式，是用wepy方式还是原生组件方式生命。我都写过相关的demo去测试。并且从1.7.2-alpha1 ~ 1.7.2-alpha4都尝试过。

## Environment

  * Platform: [开发者工具]
  * Platform version: [1.02.1805181]
  * Wechat version: [微信版本号]
  * wepy-cli version: [1.7.2]
  * wepy version: [1.7.1]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

页面`index.wpy`
```
<template>
  <view>
    <text>Hello</text>
    <world text="world" />
  </view>
</template>

<script>
  import wepy from 'wepy'
  import world from './world';

  export default class Index extends wepy.page {
    config = {
      navigationBarTitleText: 'test'
    }
    components = {
      '@world': world,
    }
  }
</script>
```

组件`world.wpy`
```
<template>
  <view>
    world
  </view>
</template>

<script>
  import wepy from 'wepy'

  export default class Index extends wepy.component {
  }
</script>
```

### Observed Results

![image](https://user-images.githubusercontent.com/2203205/41388337-118ba1cc-6fbe-11e8-8efc-313c117a609c.png)
存在world组件标签，但是内容为空

### Expected Results

  能正确引入原生组件

**Comment by samuraime** [comment]
wepy@1.7.2-alpha1 wepy-cli@1.7.2-alpha1 下可以

**Comment by jimmyrogue** [comment]
@samuraime 朋友，我也遇到问题了，可否提供一个demo参考一下？我连编译都通不过，提示我组件not defined

**Comment by samuraime** [comment]
@jimmyrogue https://github.com/samuraime/wepy-native-component-demo
