### ISSUE TITLE
在使用wx.navigateBack()返回上一页的时候，修改上一页面data后视图没有刷新，this.$apply()也没有用。

### ISSUE THREAD

**Issue by Veexx** [Tencent/wepy#1481]
//在点击后返回上一页，用的原生的方法，修改上一页data后，上一页data绑定视图没有变化，查看page栈后发现data确实更新了，但是视图没有变化
    

     backProPage(lng,lat,title){

               wx.navigateBack();
                // 往上一级页面传参
    var pages = getCurrentPages();
    var currPage = pages[pages.length - 1]; // 当前页面
    var prevPage = pages[pages.length - 2]; // 上一级页面
    console.log(prevPage);
    //  prevPage.data.baselocation.longitude=lng;
    //  prevPage.data.baselocation.latitude=lat;
     prevPage.data.baseposition.startPlace=title;
    
     this.$apply();
     
      //这里使用prevPage.$apply();也会报错。不知道为啥......

           },

**Comment by Gcaufy** [comment]
this.$apply() 是用 会 this.$wxpage.setData， 而 this.$wxpage 是当前 page..
所以如果你需要这么写的话，那应该是
```
let bak = this.$wxpage;
this.$wxpage = prevPage;
this.$apply();
this.$wxpage = bak;
```

**Comment by Veexx** [comment]
@Gcaufy  
<img width="741" alt="1526bcef-9aea-4e50-ab00-a62b9916a36a" src="https://user-images.githubusercontent.com/32189627/41455915-6ec4085e-70b1-11e8-9c8a-f54d1afe9cce.png">
大大，那文档讲动态传值这个地方，这样写也是会报错的吧..
<img width="503" alt="873f2ef3-f8fe-43d3-91fe-eca4ba0e23d1" src="https://user-images.githubusercontent.com/32189627/41456019-d342ff88-70b1-11e8-8b84-bfabf8d95482.png">

**Comment by Gcaufy** [comment]
如果是在子组件，那么 this.$parent 是父组件， 如果是在页面， 那this.$parent 就是 app了， app 没有apply方法

**Comment by Veexx** [comment]
还是用的this.$parent来获取全局对象管理页面间的数据，直接修改页面栈怕后期维护起来困难。

**Comment by bootywind** [comment]
`let bak = this.$wxpage
this.$wxpage = prevPage
this.$apply()
this.$wxpage = bak`
没有用啊
控制台显示`prevPage.data`改变了，但是跳转后没变化
setData()也只到视图层，appData根本没更新

**Comment by bootywind** [comment]
`let bak = this.$wxpage`
`this.$wxpage = prevPage`
`this.$apply()`
`this.$wxpage = bak`
控制台显示prevPage.data改变了，但是跳转后没变化
setData()也只到视图层，appData根本没更新

**Comment by XingtianXin** [comment]
@Veexx ,请问，您最后的解决办法就是把数据放到app的data里么？

我也遇到了相同的问题，页面A->页面B,然后在B页面修改了一些A页面数据，navigateBack回到A页面后，在A的onShow里根据修改的数据做一些判断，然后修改数据，显示到页面A。
但是明明页面A的Appdata中显示的数据都改变了，onShow中直接console打印输出该修改过的变量，数据没有改变。
原生开发是没有问题的。

**Comment by Gumow** [comment]
@XingtianXin  最后有解决吗？我也是直接显示有，打印没有

**Comment by XingtianXin** [comment]
> @XingtianXin 最后有解决吗？我也是直接显示有，打印没有

我没解决，最后我就是用一个global的appdata文件来管理，或者用storage
