### ISSUE TITLE
[non-writable] write wx is not allowed when using plugins at app.json.

### ISSUE THREAD

**Issue by kiwenlau** [Tencent/wepy#1483]
## Description

我在项目中使用了[微信同声传译](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=0004aa70d609e099c1d671b2a56009)插件。

```javascript
export default class extends wepy.app {
  config = {
    plugins: {
      WechatSI: {
        version: '0.0.7',
        provider: 'wx069ba97219f66d99'
      }
    }
  }
}
```

并且使用了[Fundebug](https://www.fundebug.com/)的[小程序错误监控服务](https://docs.fundebug.com/notifier/wxjs/)：

```
var fundebug = require('fundebug-wxjs')
fundebug.apikey = 'API-KEY'
```

发现出现了这样的报错：

```
[non-writable] write wx is not allowed when using plugins at app.json.
[non-writable] write App is not allowed when using plugins at app.json.
[non-writable] write Page is not allowed when using plugins at app.json.
```

[fundebug.0.5.0.min.js](https://wxjs.fundebug.cn/fundebug.0.5.0.min.js)重写了wx, App以及Page。

当我将微信同声传译注释掉，这个错误就不会出现了。另外，不使用wepy框架的话也不会有这个问题。

## Environment

  * Platform: 开发者工具
  * Platform version: v1.02.1806120
  * wepy version: 1.7.1
  * other version: 微信同声传译 0.0.7

**Comment by Gcaufy** [comment]
那这个问题是不是应该在官方论坛上提呢？

**Comment by kiwenlau** [comment]
不使用wepy框架的话不会出现这个问题，所以这个问题有可能与wepy有关。

**Comment by Gcaufy** [comment]
wepy 框架没有进行 wx, App, Page 的写操作。

**Comment by kiwenlau** [comment]
不好意思，这个问题确实与Wepy无关。基础调试库2.0.9和2.1.0会导致这个问题。

**Comment by luqiuan** [comment]
请问下楼主  wepy怎样引用小程序的插件
