### ISSUE TITLE
如果 onPrefetch 是一个异步函数，那么 onLoad 将无法得到 data.prefetch

### ISSUE THREAD

**Issue by mind029** [Tencent/wepy#1486]
https://github.com/Tencent/wepy/blob/934f41fefaddb3b0c15f6aacef2c16a1149ec4a8/packages/wepy/src/page.js#L77

如果 `goTo.onPrefetch(params, {from: this, preload: preloadData});` 。这里面是异步函数的话，那么下链接里面 onLoad 就无法得到 prefetch 了。

https://github.com/Tencent/wepy/blob/43c192453c0b8efb960cfd78312de80493becf0e/packages/wepy/src/base.js#L148

这样预查询是否就没有意义了。只能是同步的。

伪代码：
page1
```
this.$navigate(`/pages/页面2`, {id:1})
```

page2:
```
async onPrefetch (params) {
   //  this.getCarList()是promise包装好的。
   return await this.getCarList()
}


async onLoad (params, data) {
    console.log('接收到 onPrefetch 返回数据', data.prefetch) // 异步的话这里就为undefined了
 }

```

**Comment by Gcaufy** [comment]
```
onPrefetch(params) {
    return Promise.resolve({mydata});
}

onLoad (parmas, data) {
   data.prefetch.then(data => {console.log(data)});
}
```

**Comment by mind029** [comment]
可能你没理解到我的意思。如果就按你的代码逻辑来说
如果 page2 的 onPrefetch 返回的是一个Promise
```
onPrefetch(params) {
    return Promise.resolve({mydata});
}
```
那么 `page.$prefetchData 就是Promise` ， 你现在条件判断第二个条件`Object.keys(page.$prefetchData).length > 0`  永远都不会成立
你的判断代码：
``` if (page.$prefetchData && Object.keys(page.$prefetchData).length > 0) { ```

因为`Object.key()`用在promise上肯定返回为空的。所以就进不去这个if判断了。

https://github.com/Tencent/wepy/blob/43c192453c0b8efb960cfd78312de80493becf0e/packages/wepy/src/base.js#L148

如果进不去这个if。onload何来的 `data.prefetch`属性呢？

**Comment by mind029** [comment]
@Gcaufy 下一版，什么时候更新到npm仓库呢。
