### ISSUE TITLE
数据绑定data为object时，ios下页面不更新，android和ios 远程调试时正常

### ISSUE THREAD

**Issue by HackerLongo** [Tencent/wepy#1487]
## Description

数据绑定data为object时，ios下页面不更新，android和ios 远程调试时正常

## Environment

  * Platform: [iOS]
  * Platform version: [ios 11.4]
  * Wechat version: [6.6.7]
  * wepy-cli version: [1.7.2]
  * wepy version: [1.7.1]
  
## Reproduce
小程序页面如下代码，在anroid及开发者工具中点击按扭后，“显示数据”正常显示和隐藏，但是在ios无法实现。但是在ios 微信小程序【远程调试模式】下又可以正常显示和隐藏。

### Observed Results
ios 下 “显示数据”不随按键的点击而改变
  
### Expected Results
ios 下 “显示数据”随按键的点击而改变
## Relevant Code / Logs

  ```
<template>
    <view hidden="{{!lv.show}}">显示数据</view>
    <view class="btn-box">
        <button size="mini" type="primary" bindtap="submit">提 交</button>
    </view>
</template>
<script>
  import wepy from 'wepy'
  export default class TeamList extends wepy.page {
    data = {
      lv: {show: true}
    }
    submit() {
      this.lv.show = !this.lv.show;
    }
  }
</script>
  ```

**Comment by Gcaufy** [comment]
看一看是不是没有把开发者工具的压缩选项给关掉

**Comment by Gcaufy** [comment]
具体原因还是不太清楚，似乎是压缩工具对某些代码的压缩导致了一些兼容性问题。
