### ISSUE TITLE
触发 onReachBottom 后页面消失

### ISSUE THREAD

**Issue by ECer23** [Tencent/wepy#1489]
## Description

页面滑动到底部之后，用 `wx:for` 渲染的组件消失，只剩下非 `wx:for` 渲染的部分

## Environment

  * Platform: 开发者工具
  * Platform version: 1.0.2
  * wepy-cli version: 1.7.2
  * wepy version: 1.6.0
  
## Reproduce

滑动到底部就消失了

### Observed Results

![GIF（可能需要互联网）](https://i.loli.net/2018/06/16/5b24ad815388f.gif)

### Expected Results

不要消失！

## Relevant Code / Logs

```html
<template>
  <scroll-view class="container">
    <view wx:for="{{recommendation_list}}">
      <navigator url="/pages/today-detail?recommendationId={{item.recommendation_id}}" >
        <view class="card">
          <view class="card-text">
            <text class='card-tag'>{{item.tag}}\n</text>
            <text class='card-title'>{{item.title}}</text>
          </view>
          <view class="card-image" style="background-image: url({{item.image}}"></view>
          <view class="card-bg-blur" style="background-image: url({{item.image}})"></view>
        </view>
      </navigator>
    </view>
  </scroll-view>
</template>
```

**Comment by dlhandsome** [comment]
请先确认触底后```recommendation_list``` 是否是因为某些操作清空导致列表消失

**Comment by ECer23** [comment]
再次检查了一下，发现在 `onShow` 和 `onReachBottom` 开始时用 `console.log(this.data.recommendationList)` 结果都是一个空列表，但是页面一开始是可以正常显示的

```js
data = {
  recommendationList: []
}
onLoad() {
  var that = this
  wepy.request({
    url: 'https://easy-mock.com/mock/5afbe65c3e9a2302b68981e5/recommendation',
    method: 'GET',
    data: {},
    header: {
      Accept: 'application/json'
    },
    success: function(res) {
      console.log(res.data.data)  // 此时是有数据的
      that.setData({
        recommendationList: res.data.data
      })
    }
  })
}
onShow() {
  console.log(this.data.recommendationList)  // []
}
onReachBottom() {
  console.log(this.data.recommendationList)  // []
}
```

P.S. 我是从原生小程序迁移到 wepy 上，原生的时候都没有这个问题

**Comment by Gcaufy** [comment]
可以发代码包或者代码片段我帮忙调试一下。

**Comment by ECer23** [comment]
谢谢，代码已经发到邮箱！

**Comment by DsAco** [comment]
知道什么原因了吗？  我也出现了类似的问题

**Comment by Gcaufy** [comment]
我使用你的代码打开空白，应该是没有mock数据的原因

**Comment by Gcaufy** [comment]
不过看代码是有几个问题，我修改如下：
```
async getRecommendationList() {
      let res;
      try {
        res = await api.getRecommendationList();
      } catch(e) {
        console.log(e);
      }
      if (res) {
        this.recommendationList = res.data.data;
        this.$apply();
      }
    }
```

**Comment by DsAco** [comment]
![1bd55673-db5f-47de-a672-19bdce4b31f7](https://user-images.githubusercontent.com/12523637/41767871-5a217684-763d-11e8-8876-a1ab39e7180b.png)
异步函数里需要this.$apply() 应该是这个问题了   
但是 this.setData 和 this.xx = xx  不一样的吗？ 为什么用setDate就会出现 数据消失的情况呢 文档里没有找到相关的

**Comment by DsAco** [comment]
看文档不推荐使用 setDate  我也不是必须用这个方法 
但是如果多个对象赋值的话 
感觉  this.setDate({xx:xx,yy:yy}) 会比  this.xx = xx  this.yy = yy 会更好一点

**Comment by Gcaufy** [comment]
已经fix了吗？
this.setData 和 原生小程序的 this.setData 的封装，直接使用 this.setData 不会改变备份数据。会破坏赃检查。

**Comment by DsAco** [comment]
我不是提issue的人  我的问题解决了  我只是好奇这个东西。。

**Comment by ECer23** [comment]
fix 了！谢谢 @Gcaufy 和 @DsAco 

> 用setData之后 调用 $apply 页面会瞬间有数据然后消失 不调用 $apply的话 屏幕滑到底部数据会消失

所以就用

```js
this.xxx = yyy
this.$apply()
```

就好了
