### ISSUE TITLE
build打包有多余文件

### ISSUE THREAD

**Issue by jiujiuzhang99** [Tencent/wepy#1492]
![tim 20180617223207](https://user-images.githubusercontent.com/24930493/41508952-d4535cfa-727e-11e8-90c3-88cf07c90d05.png)
如上图components和store、service文件夹都是在src下删掉了的，build后出现在了dist下，而buid时console输出的日志却没有相关信息。
——————————————————————————————————————
![tim 20180617223540](https://user-images.githubusercontent.com/24930493/41508965-09ab1122-727f-11e8-93c8-a2f67419408d.png)
如上图，右边是构建后的app.json，左边是pages目录，出现了红框所示的多余文件。

尝试过删除dist目录，删除.wepycache文件，未果。
wepy版本: 1.7.1
cli版本: 1.7.2

**Comment by Gcaufy** [comment]
目前它并不是入口检测，而是文件检测编译
对不需要编译的文件可以加到`.wepyignore`中。

**Comment by xialvjun** [comment]
所以为什么不做入口检测呢？app.wpy 和每个 pageXXX.wpy 都是一个 entry。。。然后大家共用一个 common。。。这不正好
