### ISSUE TITLE
wepy.request参数使用

### ISSUE THREAD

**Issue by endingman** [Tencent/wepy#1499]
wx.request 接收参数修改，你的示例是这个样子的：
// 原生代码:

wx.request({
    url: 'xxx',
    success: function (data) {
        console.log(data);
    }
});

// WePY 使用方式, 需要开启 Promise 支持，参考开发规范章节
wepy.request('xxxx').then((d) => console.log(d));

// async/await 的使用方式, 需要开启 Promise 和 async/await 支持，参考 WIKI
async function request () {
   let d = await wepy.request('xxxxx');
   console.log(d);
}

然后，假如需要使用更多参数的话是否这样使用：
// 原生代码:

wx.request({
    url: 'xxx',
data: {
     x: '' ,
     y: ''
  },
  header: {
      'content-type': 'application/json' // 默认值
  },
method:‘xxx’,
    success: function (data) {
        console.log(data);
    }
});

// async/await 的使用方式
async function request () {
   let d = await wepy.request(url,data,header,method);//url为接口地址参数，data为请求数据参数后面两个类似。
   console.log(d);
}

也就是有没有对wx.request封装过？如果可以的话，data又是什么格式？

**Comment by Gcaufy** [comment]
```
wepy.request({
    url: url
    data: data
});
```

**Comment by endingman** [comment]
@Gcaufy 
明白。希望文档可以加下详细说明，看到类似这样wepy.request('xxxxx')说明在需要扩展的时候有点懵。

**Comment by kaneyj** [comment]
wepy.request不支持header参数的传递是吗？即便我赋值，始终都是默认的'content-type': 'application/json' 。

**Comment by poberwong** [comment]
> ```
> wepy.request({
>     url: url
>     data: data
> });
> ```

This method signature doesn't return a promise.

**Comment by link-cathy** [comment]
文档真垃圾，也不说个参数怎么传，传那些。就直接WePY 使用方式, 需要开启 Promise 支持，参考开发规范章节这样？也是醉了

**Comment by poberwong** [comment]
@link-cathy 冷静，可以参与进来一同维护
