### ISSUE TITLE
如何隐藏一个view

### ISSUE THREAD

**Issue by bzqadmin** [Tencent/wepy#1511]
` <view class="item weui-uploader__input-box" hidden="{{hideAddPic}}" >`
在data中设置hideAddPic=false,
在程序逻辑中设置hideAddPic=true，但是页面中相应的view没有隐藏，用不用this.$apply()都不行
请问是不是隐藏不用这个思路啊？我用原生代码开发是可以的。

**Comment by Jinlixian** [comment]
<view wx:if="{{hideAddPic}}" class="item weui-uploader__input-box">
这样搞。

**Comment by Jinlixian** [comment]
`<view wx:if="{{hideAddPic}}" class="item weui-uploader__input-box">`
这样隐藏。

**Comment by Gcaufy** [comment]
hideAddPic=true  换成 hideAddPic=1 和 0 去试试，
我记得我以前碰到过 hidden 在处理 true/false 时 处理成了 'true'/'false' 的问题
