### ISSUE TITLE
在wxs里引入另一个wxs出现的问题

### ISSUE THREAD

**Issue by xuweikang** [Tencent/wepy#1512]
我在a.wxs中引入了另一个b.wxs文件，模拟器中没问题，但是在真机上预览时候出现了问题，定位到的原因就是 a.wxs没有成功引入b.wxs  @Gcaufy

**Comment by womendi** [comment]
看样子
wepy这github没人维护

**Comment by womendi** [comment]
看样子
wepy这github没人维护

**Comment by Gcaufy** [comment]
能否给出复现代码？
a.wxs没有成功引入b.wxs好像与wepy的关系不大，wepy并没有对这一部分做特殊处理。
