### ISSUE TITLE
使用wepy-cli1.70进行分包，从主包页面跳转到分包页面，分包页面卡主，不能渲染，报错

### ISSUE THREAD

**Issue by echoLC** [Tencent/wepy#1513]
## Description

 使用wepy-cli1.70进行分包，从主包页面跳转到分包页面，分包页面卡主，不能渲染，报错，
报错VM4551:2 Uncaught ReferenceError: $guessSwiper$index is not defined，页面已经跳转成功了，但是没有渲染出跳转后的页面，内容还是跳转之前的页面

## Environment

  * Platform: [开发者工具]
  * wepy-cli version: [1.7.0]
  * wepy version: [1.7.0]

**Comment by wutianmei** [comment]
请问解决了吗，我也碰到了这个问题
