### ISSUE TITLE
请问：wepy 支持 new Blob的用法吗，我写进去好像不支持的样子

### ISSUE THREAD

**Issue by cam510** [Tencent/wepy#1518]
## Description

    请问：wepy 支持 new Blob的用法吗？
    如果不支持有什么方法像blob一样吧数据变成文件呢？

**Comment by Gcaufy** [comment]
这个和 wepy 无关， 小程序 支持那么就支持，小程序不支持就不支持。

**Comment by cam510** [comment]
@Gcaufy 好像是小程序本身不支持
