### ISSUE TITLE
调用wx.onCompassChange报错

### ISSUE THREAD

**Issue by zwwon** [Tencent/wepy#1521]
[luopan.txt](https://github.com/Tencent/wepy/files/2126974/luopan.txt)
onLoad(){
           var h=0;
            wx.onCompassChange(function(res) {
                // res.direction
                if (res.direction > -1) {
                    this.lpnum = res.direction.toFixed(0); //res.direction;
                }
            })
       };

错误是：
cannot set property 'lpnum' of null

**Comment by Gcaufy** [comment]
js基础问题，this没有理解到
```
onLoad(){
           var h=0;
           var self = this;
            wx.onCompassChange(function(res) {
                // res.direction
                if (res.direction > -1) {
                    self.lpnum = res.direction.toFixed(0); //res.direction;
                    self.$apply()
                }
            })
       };
```

**Comment by zwwon** [comment]
问题解决，谢谢Gcaufy
