### ISSUE TITLE
关于打包成web后wx.login()错误警告如何处理

### ISSUE THREAD

**Issue by acegank** [Tencent/wepy#1524]
打包成web后，会有个警告提示  ‘wx.login is only implemented in browser’
源码在wepy-web/lib/wx.js
wx.login = wx.login || function login(o) {
    console.error('wx.login is only implemented in browser');
};

请问如何处理，打包后的web作为公众号页面。

**Comment by Gcaufy** [comment]
```
wepy build --output web --platform wechat
```
会多引入一层 wepy-web-wechat 去实现 login方法的。。。
但是wepy-web这里并没有经过大量的测试，还存在很多问题。所以仅作为体验功能。
