### ISSUE TITLE
install wepy-cli error

### ISSUE THREAD

**Issue by renjunlincn** [Tencent/wepy#1525]
## Description

npm install wepy-cli Unexpected end of JSON input while parsing near '...o.org/async/download/'

## Environment

  * wepy-cli version: [1.7.2-alpha2]
  * wepy version: [1.7.2]
  
## Reproduce

npm install wepy-cli

### Observed Results

npm ERR! Unexpected end of JSON input while parsing near '...o.org/async/download/'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-06-24T11_27_51_347Z-debug.log

**Comment by Gcaufy** [comment]
```
npm -v
```
看看

**Comment by renjunlincn** [comment]
npm: 5.6.0
node: 8.11.3

**Comment by Gcaufy** [comment]
```
npm install wepy-cli -g
```
再试试看？

**Comment by renjunlincn** [comment]
还是报这个错，好像是源的问题。registry.npmjs.org没有问题，registry.npm.taobao.org有问题

**Comment by Gcaufy** [comment]
我无法重现问题，请给出下列命令的截图
```
node -v
npm -v
npm i wepy-cli -g
npm i vue-cli -g
```

**Comment by renjunlincn** [comment]
![ms_9 9p0 yv pxkyt 8f50](https://user-images.githubusercontent.com/20872230/42418515-b43140fc-82d4-11e8-9639-e69d8b3c9877.png)

**Comment by renjunlincn** [comment]
不知道是不是我电脑的原因，其他电脑我也无法重现

**Comment by Gcaufy** [comment]
建议卸载 Node 和 npm 然后重装吧。似乎所有的包都无法安装 。

**Comment by Trgree** [comment]
把源换成taobao的就可以了
```
npm config set registry https://registry.npm.taobao.org/
npm install @wepy/cli -g
```
