### ISSUE TITLE
能否支持antv/f2，图表组件？

### ISSUE THREAD

**Issue by sunguide** [Tencent/wepy#1526]

**Comment by Gcaufy** [comment]
暂无计划

**Comment by dntzhang** [comment]
期待一下cax next！ https://github.com/dntzhang/cax @sunguide

**Comment by Onlylonger** [comment]
@sunguide 我这边刚根据 wx-f2 官方antv f2小程序的项目，移植到了 wepy 组件，你可以参考下

github: https://github.com/Onlylonger/wepy-antv-f2

**Comment by dntzhang** [comment]
@sunguide 姿势参考下
https://github.com/dntzhang/wechart/tree/master/packages/weapp-line

**Comment by sunguide** [comment]
@dntzhang @Onlylonger @guotie @Gcaufy 感谢
