### ISSUE TITLE
小程序官方组件picker-view默认选中不管用

### ISSUE THREAD

**Issue by laravelup** [Tencent/wepy#1528]
在onLoad里面赋值，或者直接给定默认值都是不行的
相同的问题请看：https://github.com/Tencent/wepy/issues/1414

**Comment by shannuo** [comment]
这样解决了= =
onLoad() {
    setTimeout(() => {
      this.value = [10, 11, 29] 
      this.$apply()
    }, 0);
  }

**Comment by savioryu** [comment]
shannuo 的方法是可以的，这里还要注意三个问题：
- 在 data 中设置默认值时两个列表还是空的，所以设置多少都没用，需要在 onLoad 中延时设置
- 异步是将任务加到队列的末尾去执行，timeout 设置为 0 就可以
- data 中定义的 value 与 picker-view 的初始值要不一致才能生
