### ISSUE TITLE
Android 中2个页面来回切换7-8次后会出现卡死问题，问题很严重，求解决方案

### ISSUE THREAD

**Issue by 5468sun** [Tencent/wepy#1531]
## Description

 wepy 中新建两个页面，index页面data中绑定400K数据，detail页面是空的页面，
index页面中放一个按钮，点击按钮wx.navigateTo detail页面。

从index页点击按钮跳转到detail页，然后detail页面上点击左上角返回箭头返回到index页面。
重复操作7，8次后，页面跳转会出现变慢卡顿。然后经常是 首页卡住不跳转然后多点击几次按钮，过了一会儿回连续跳转到多个detail页面。

监测小程序的性能数据中的【页面切换耗时】，发现这个时间会从200ms 慢慢涨到 2000ms。偶尔回出现小程序崩掉的情况。

用原生方式做过测试，没有这样的问题。
  
  [Description of the issue]

## Environment

  * Platform: [iOS]
  * Platform version: [10.13.3]
  * Wechat version: [6.6.7]
  * wepy-cli version: [1.7.3]
  * wepy version: [^1.6.0]

  
## Reproduce

代码很简单：
wechatide://minicode/px9zTsmx77xq

### Observed Results

  多次操作后变慢或页面死掉
  
  
### Expected Results
切换页面时跟原生一样顺滑，不出现卡顿
  
  [Expected Results]
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs here to reproduce the problem
  // 可以使用小程序代码片段功能，方便其它人帮助你定位代码问题
  // 详情可参考这里：https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
  ```

**Comment by panda912** [comment]
同问，我是从列表页跳转详情页，当列表数据量大的时候，跳转时卡顿好久，甚至二三十秒，起初怀疑是onHide时触发$apply导致，修改base.js中的源码，忽略onHide时$apply，效果甚微。
![wx20180626-142443](https://user-images.githubusercontent.com/5298742/41893301-f739acf8-794d-11e8-87a4-8b2ab5605926.png)

**Comment by 5468sun** [comment]
我在列表页中数据大概40K。只存在在内存中，没有做页面渲染。点几下会慢慢变卡。iphone中没有这个问题。感觉是底层数据处理的问题。

**Comment by panda912** [comment]
应该就是$apply()导致的，我刚刚试了一下，把`node_modules/wepy/lib/base.js`中涉及到`page.$apply()`的代码注释掉，一点都不卡了，这只是定位问题，不敢这样改源码，不知道会造成什么问题😂

**Comment by 5468sun** [comment]
#1090 查到这样一个issue，似乎相关

**Comment by 5468sun** [comment]
index页加上如下代码，问题缓解了。
`onShow () {
      this.disableDigest()
    }

    onHide () {
      this.disableDigest()
    }

    onShareAppMessage () {
      this.disableDigest()
    }

    disableDigest () {
      this.$$phase = true

      setTimeout(() => {
        this.$$phase = false
      })
    }`

**Comment by coolhwm** [comment]
我也遇到这个问题，列表大小20K左右，

**Comment by coolhwm** [comment]
@5468sun 加了你的代码感觉有所缓解？什么原理？会不会有什么副作用？

**Comment by panda912** [comment]
@5468sun 可以看看wepy官网的脏数据检查流程

**Comment by fanchaot** [comment]
> index page加上如下代码，问题缓解了 .`onShow（）
> { 
> this.disableDigest（）
> }
> 
> ```
> onHide () {
>   this.disableDigest()
> }
> 
> onShareAppMessage () {
>   this.disableDigest()
> }
> 
> disableDigest () {
>   this.$$phase = true
> 
>   setTimeout(() => {
>     this.$$phase = false
>   })
> }`
> ```

这个 我放到 app.wpy 中吗  我的是 安卓 滚动会特别的卡
