### ISSUE TITLE
wepy使用picker-view 部分安卓手机@chang或bindChange时间获取事件缓慢或获取不到，原生的却好着呢。

### ISSUE THREAD

**Issue by ChenHui15** [Tencent/wepy#1533]
wepy使用picker-view 部分安卓手机@chang或bindchange时间获取事件缓慢或获取不到，原生的好着呢。

现在测试到三星S6 魅族5有这个问题

<view class="birthday-box">
          <view class="birthday-label">生日</view>

          <picker-view indicator-style="height: 50px;" mask-style="fost-size:28rpx" class="select-birthday" value="{{value}}" @change="bindChange">

            <picker-view-column>
              <view wx:for="{{ years }}" wx:key="year" style="line-height: 50px;text-align: center">{{item.year}}年</view>
            </picker-view-column>

            <picker-view-column>
              <view wx:for="{{ months }}" wx:key="month" style="line-height: 50px;text-align: center">{{item.month}}月</view>
            </picker-view-column>

            <picker-view-column>
              <view wx:for="{{ days }}" wx:key="day" style="line-height: 50px;text-align: center">{{item.day}}日</view>
            </picker-view-column>
          </picker-view>
        </view>

**Comment by Gcaufy** [comment]
这里并没有做什么特殊处理，对比着查看dist代码有何不同。

**Comment by ChenHui15** [comment]
@Gcaufy dist都是转译成es5的,无法对比，如果让他不转译

**Comment by Gcaufy** [comment]
主要是看wxml是否有问题，js的话下断点调试就可以了。
或者看是否能提供一个[代码片断](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)方便我去调试一下。

**Comment by ChenHui15** [comment]
@Gcaufy 问题解决了，是我们这边的问题，谢谢

**Comment by Gcaufy** [comment]
建议简单写下问题原因，方便碰到类似问题的人。
