### ISSUE TITLE
子组件 extends wepy.page props传值为undefined

### ISSUE THREAD

**Issue by lessaber** [Tencent/wepy#1534]
## Description

  子组件 extends wepy.page props 传值为 undefined，改为 extends wepy.component 后成功

  官方文档，可能为会造成误解

``` 
由于Page页面实际上继承自Component组件，即Page也是组件。除扩展了页面所特有的config配置以及特有的页面生命周期函数之外，其它属性和方法与Component一致，因此这里以Page页面为例进行介绍。
 ```

  在这里提一下，防止有人也有犯这个错误

**Comment by fonglezen** [comment]
你的意思是指子组件改为 extends wepy.component？
子组件本来就是extends wepy.component，也会报的undefined。

**Comment by Gcaufy** [comment]
子组件一定要 extends wepy.component
这句话的意思其实是， page 也是一个组件。

**Comment by beyondverage0908** [comment]
被这个问题困恼了一天，以防止有人入坑。请继承自wepy.component.
