### ISSUE TITLE
组件的props除了字符串类型以外，都必须通过data中的变量才能传值吗？

### ISSUE THREAD

**Issue by flashliu** [Tencent/wepy#1538]
比如我想直接传入Boolean值
`<component visible='false'></component>`
`<component visible='{{false}}'></component>`
`<component :visible='false'></component>`
以上三种方式均不可行

**Comment by Gcaufy** [comment]
1.7.x 中的 props 是不支持表达示的。

**Comment by Athrunsky** [comment]
@Gcaufy 也就是说无论组件还是repeat循环渲染组件，都只能传递字符串过去是么，而且传过去的也没法在组件标签上做wx:if等判断？
现在有一个问题是repeat循环出组件以后，我在组件上的标签对传入的数据做了wx:if判断结果编译报错了

**Comment by sunkehappy** [comment]
@Gcaufy 现在是什么情况？能更新下吗？
