### ISSUE TITLE
wepy-redux  dispatch 到 watch到结果 中间间隔太久，会阻塞后面代码执行

### ISSUE THREAD

**Issue by jinmincr** [Tencent/wepy#1539]
## Description

```  
    var starttime = new Date().getTime();
    console.log('start catlog1: ' + starttime)

    store.dispatch({ type: REQUEST_CHAPTER_LIST })

    var endtime = new Date().getTime()
    console.log('start catlog2: ' + (endtime - starttime))
```
在执行上面这段代码时，dispatch之后，会有watch 、action  REQUEST_CHAPTER_LIST的步骤，之后才会进行第二个console。

但在部分安卓手机，如红米note3、 魅族MX4 pro上这段时间会很久，而且经过多次页面切换后 会更久，导致整个页面一直处于loading态。
  
不知道为什么修改状态需要这么就时间，真机测过有时候需要4、5秒，这样一个页面有多个状态修改的话就很慢

**Comment by sharpzhao** [comment]
同样的问题，安卓手机上延迟好几秒，七八秒都来了。已经不知道怎么处理这个问题了。

**Comment by sharpzhao** [comment]
我的情况是，不考虑watch。 dispatch 从开始到结束的时间就会越来越长。如果连续点击，后面的时间能达到7、8秒，dispatch开始到结束的间隔时间。

**Comment by sharpzhao** [comment]
@Gcaufy 感谢辛劳付出，麻烦看看这个是问题么。还是我使用有问题。安卓机器上才会有问题

**Comment by Gcaufy** [comment]
可以提供代码片段么？
不调试的话看不出来问题在哪。

**Comment by sharpzhao** [comment]
console.log('addItem' + new Date().getTime());
      this.methods.dispatchAddItem({
           ....
      });
      console.log(' end addItem' + new Date().getTime());

前后文应该没啥影响，而且太多了 如果需要，我可以给更多片段，我在这个方法前后打印了时间。两者相差 7、8秒。
以下是我的 connect / action 和ruducer

**Connect**
```
@connect({}, {
    dispatchAddItem: AddItem
});
```
**Action**
```
export const AddItem = createAction(
  ADD_ITEM,
  item => ({
    item
  })
);
```
**Reducer**
```
  [ADD_ITEM](state, action) {
    let newState = cloneDeep(state);
    .....
    return newState
  }
```

Thanks @Gcaufy

**Comment by jinmincr** [comment]
```
store.dispatch({ type: REQUEST_CHAPTER_LIST })
service.getChapterList().then() ....
```
其实就是dispatch的执行时间很久，向server发请求前 先dispatch，修改state，就会阻塞后面的server请求

**Comment by sharpzhao** [comment]
@jinmincr Have you fix this by other approaches?

**Comment by jinmincr** [comment]
@sharpzhao 因为项目紧急，没有找到比较好的办法。然后对比了我们另外一个项目，是使用小程序原生代码写的，原生state管理，完全不卡顿。后来我们也就改成第一次打开程序，不依赖wepy redux，也去掉了watch，直接用server获取的数据，等渲染所需的数据都准备好了，再执行dispatch，这里只是起到备份的作用（下次不用重新获取了）。 直接把框架去掉 改动就太大了……你有什么好办法吗？

**Comment by sharpzhao** [comment]
@jinmincr 暂时没有，我试图看wepy-redux的代码，但是看不出问题啊。很多依赖wepy-redux的。所以如果去掉的话，很麻烦。
不过如果没有别的方法的话，我也会去掉wepy-redux。

**Comment by sharpzhao** [comment]
@Gcaufy 

我尝试在redux 的 this.$apply() 里面打印时间 (最后两行）
**
```JavaScript
  var onStateChange = function onStateChange() {
      var _this = this;

      var store = (0, _store.getStore)();
      var hasChanged = false;
      var ownProps = Object.assign(_helpers.wrapOwnPropsFunc.call(this), injectedProps);
      var states = mapStateToProps(store.getState(), ownProps);
      var data = this.$data || {};
      Object.keys(states).forEach(function (key) {
        if (_this.computed) {
          _this.computed[key] = function mappedState() {
            return states[key];
          };
        }
        if (!data.hasOwnProperty(key)) _this.$data[key] = undefined;
      });
      Object.keys(states).forEach(function (k) {
        var newV = states[k];
        if (_this[k] !== newV) {
          // 不相等
          _this[k] = newV;
          hasChanged = true;
        }
      });
      var _s_time = new Date().getTime(); // get start time()
      hasChanged && this.$apply();
      console.log("apply change: " + (new Date().getTime() - _s_time)) //log apply cost
  };
```
发现延迟时间主要是 this.$apply() 的时候花费的。
正常是200毫秒左右（华为）
连续点击会 上升到 2秒、3秒 甚至6秒。
不知道这个信息能不能有所帮助。

**Comment by Gcaufy** [comment]
这个数据多大？

**Comment by sharpzhao** [comment]
35K 左右。 10K的时候都没啥问题。数据量一大就变卡（安卓） 而且这个数据是没有变的。

**Comment by Gcaufy** [comment]
太大了，看看有没有可能弄小一点数据吧，
你这个数据你setData试试，一样很慢吧。

**Comment by sharpzhao** [comment]
我试过直接使用setData， 没有问题的。因为我这个数据不是每次都会变，实际上很少会变。
但是wepy每次都会检查这个数据有没有变。我看检查的过程很慢。
导致了整体被block了。而且这个数据会通过props传递给子组件，就导致了效率更低了。
以上是我的猜测（打印运行时间看的）不一定对。所以麻烦各位帮忙看看~

**Comment by Gcaufy** [comment]
刚测试了一个38kb的json的例子
```
$ node index.js
Require JSON file: 2ms
Stringify JSON: 1ms
JSON length: 38.5kb
Deep copy takes: 1ms
Is deep equal: 1ms
```

如果你觉得是这里的问题的话你可以把相关函数单独copy出来进行测试。

**Comment by jinmincr** [comment]
我觉得和数据大小没太大关系，我这边根本就没什么数据，就是修改state的一个值而已 就卡了 @sharpzhao

**Comment by sharpzhao** [comment]
@Gcaufy 感谢回复。
确实有点迷。 我试了下，我这边是只有多点几次之后才会出现block的情况。但是打印的时间表明，确实是在判断对象是否改变那个地方消耗的时间。
我也有点迷了。

**Comment by sharpzhao** [comment]
@jinmincr 也有可能，但是我这边用一个小一点的数据，情况没有那么恶劣。但是点击10多次之后也会出现这个情况，不会延迟那么久。很神奇。感觉跟迷信一样。

**Comment by Slngle** [comment]
@Gcaufy 我也遇到同样的一个问题 如果连续点击加购 我dispatch一个方法 前面点7 8下是好的，后面触发加购到页面渲染的时间能达到7、8秒，然后继续点击 切换页面 整个小程序页面就假死了

**Comment by sharpzhao** [comment]
@Slngle 我基本上解决了这个问题：
1. 尽量不用 component （ 因为只要涉及到某些属性变化，涉及到的component都要各种apply一遍）
2. 不变的数据 我直接setData，防止wepy检查这个数据。

**Comment by Slngle** [comment]
@sharpzhao 不用component你是怎么处理公用的情况呢？

**Comment by Slngle** [comment]
你是怎么写组建的啊？

**Comment by Slngle** [comment]
我这边在安卓上将 isDeepEqual 变成浅比较 直接 return a===b 安卓上的性能会好一些 至少不会点击下就卡死
