### ISSUE TITLE
【建议】wepy-cli plugin apply方法执行时可以放入编译前的源码

### ISSUE THREAD

**Issue by andypinet** [Tencent/wepy#1540]
## Description

编写wepy-plugin，发现缺少原始code, 比如我想使用jsdoc分析原来的js, 但是编译后的js, 已经失去分析的意义   
同理 sass 文档也无法编译
现在有op.code  如果有 op.originCode  就好了

## Environment

  * wepy-cli version: [1.7.3]

**Comment by Gcaufy** [comment]
这个在1.7中可能不会再作调整，在2.x中plugin会允许用户处理编译的任意一个阶段。可以期待一下。
