### ISSUE TITLE
为什么同一页面引用多个相同组件时会给最后一个组件的数据全覆盖了呢

### ISSUE THREAD

**Issue by yangbys** [Tencent/wepy#1542]
![image](https://user-images.githubusercontent.com/5164085/42123034-a3612f24-7c7d-11e8-8fb7-d11f98a883a8.png)
![image](https://user-images.githubusercontent.com/5164085/42123036-af4ac110-7c7d-11e8-8404-e2a49a2348d5.png)
给最个一个组件的数据全覆盖了，这是怎么回事呢~~

**Comment by Gcaufy** [comment]
组件名是维一标识，这种情况下需要声明两个组件， groupitem1, gorupitem2
