### ISSUE TITLE
在插件wepy-compiler-stylus中，很难设置一些高级参数，请修复之后再关闭issues

### ISSUE THREAD

**Issue by fengxinming** [Tencent/wepy#1544]
## Description

  使用现有的插件很难定义define、import等高级参数

## Environment

  wepy-compiler-stylus@1.3.12
  
## Reproduce

  配置wepy.config.js文件
```
module.exports = {
  compilers: {
    styl: {
      compress: true,                                 // 压缩
      includeCSS: true,                               // 支持导入css
      supportObject: true,                            // 支持以下参数
      define: {                                       // 外部传入全局变量和函数
        isProd: process.env.NODE_ENV === 'production' // 举例：控制不同环境的样式处理
      },
      include: [],                                    // 等价于 paths: [__dirname, __dirname + '/utils']，将目录暴露给全局
      import: [                                       // 导入自定义的functions和mixins等，千万不要导入全局公共样式，否则你懂的哦
        path.join('src', 'css', 'utils', '**/*.styl')
      ],
      url: 'inline-url',                              // 使用base64将图片转码
      url: {
        name: 'inline-url',
        limit: 30000,                                 // 限制多少B以内的图片被压缩
        paths: []                                     // 从指定的目录下查找图片
      },

      // ============= stylus 内部参数 =============
      globals: {                                      // 外部传入全局变量
        isProd: process.env.NODE_ENV === 'production'
      },
      functions: {}                                   // 外部传入全局函数
      use: [],                                        // 导入插件nib、poststylus等
      paths: [],                                      // 将目录暴露给全局
      filename: [],                                   // 设置文件名
      Evaluator: Object                               // 没用过，我也不知道
    }
  }
};
```

### Observed Results

  [实际表现]
  
  参数被覆盖
  
### Expected Results

  [期望表现]
  
  配置生效
  

## Relevant Code / Logs

你没有任何修改就关闭了我的问题，还要我pr进来，我下午提交了代码上来也没见你合并进来呀

**Comment by Gcaufy** [comment]
哪个问题，哪个pr?

**Comment by fengxinming** [comment]
@Gcaufy 就是wepy下面的wepy-compiler-pug和wepy-compiler-stylus，我之前自己单独重写了这两个编译插件，运行稳定，我上次把的代码pull到你的1.7x分支，然后就没有然后了

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/issues/1163
https://github.com/Tencent/wepy/issues/1162

这两个？为什么不给上链接？

提issue的时候尽可能的要方便别人给更多的信息出来.
这里pr和issue都上千了，不可能每个都处理得非常仔细，如果没处理看看这个issue和pr本身是不是有什么问题。

另外，你这两个都不是pr啊。建议了解一下如何做pr:https://github.com/geeeeeeeeek/git-recipes/wiki/3.3-%E5%88%9B%E5%BB%BA-Pull-Request

**Comment by fengxinming** [comment]
@Gcaufy 我不是只这两天，我就是提issues那天下午，修改了你1.7x分支上的代码，然后pull几个新分支，然后就被你们删掉了，要不还是我把代码给你来合并？

**Comment by Gcaufy** [comment]
给link！！
pull request 并没有收到你的请求，github 也不提供能力去把你的代码删掉。

**Comment by fengxinming** [comment]
@Gcaufy 我上次push了6个分支，后面发现还是没有合并进去
https://github.com/fengxinming/wepy-compiler-stylus
https://github.com/fengxinming/wepy-compiler-pug (这个要把里面默认的jade改成pug)

**Comment by Gcaufy** [comment]
建议了解一下如何做pr:
https://github.com/geeeeeeeeek/git-recipes/wiki/3.3-%E5%88%9B%E5%BB%BA-Pull-Request

你在自己repo 里面改的代码我怎么合？你要先fork，然后再改，然后再提交pr

**Comment by fengxinming** [comment]
@Gcaufy 那我周日花点时间合并进来

**Comment by fengxinming** [comment]
@Gcaufy 已经pull一个新分支 issues-1544
