### ISSUE TITLE
关于wepy循环自定义组件的发现

### ISSUE THREAD

**Issue by yz-xlame** [Tencent/wepy#1549]
1、所有循环出来的组件中的数据是共用的
2、不管你有多少，始终以arr[0]为基准(其他的都是按照arr[0]渲染出来的，那还要加key做什么用？)
3、只有template可以获取到对应的props,如果不是把item传进来，在JS中，所有props都是undefined，但是文档中好像说过:组件使用的是静态编译组件,不支持在 repeat 的组件中去使用 props, computed, watch 等等特性,emmmm.......那我难道动态的手写？
4、只有如果传入item则可以在onload、onready之后获取到item的各属性以及值
5、（突然忘记了(-__-)b）
所以，如果需要循环自定义组件，只需要相对静态来说，可以直接传入值，如果需要其返回一些什么，就需要在传入item，在如tap事件中，对item的某些所需的属性以及值进行操作
小弟也刚接触，如果有什么不对的地方，还望大佬告知，我真的求更好的办法来解决这个问题

**Comment by iniself** [comment]
其实作为静态组件，最恼火的是repeat子组件后，所有的子组件共享一套data数据，也就是说如果你的子组件的template里有data中的某个{{}}值，那么所有repeat出来的子组件都会响应。我现在不知道如何解决这个问题，不要说在父组件中引入多个components以不同ID的区分同一子组件，这肯定能解决问题，但肯定是最不正常的解决之道

**Comment by yz-xlame** [comment]
@iniself 我现在的做法是:把需要显示的数据先传递过去,然后,把整个item传递过去,这样在比如tap这样的事件中就可以读取到item,以及他的属性这样的,如果单独把item的一个属性传递给子组件,那么在子组件的JS中是无法读取到那个属性的

**Comment by August-Z** [comment]
WePY 1.x 版本中，组件使用的是静态编译组件，即组件是在编译阶段编译进页面的，每个组件都是唯一的一个实例，目前只提供简单的 repeat 支持。不支持在 repeat 的组件中去使用 props, computed, watch 等等特性

```html
<!-- 错误使用 -->
// list.wpy
<view>{{test.name}}</view>

// index.wpy
<repeat for="{{mylist}}">
   <List :test.sync="item"></List>
</repeat>

<!-- 推荐用法 -->
// list.wpy
<repeat for="{{mylist}}">
    <view>{{item.name}}</view>
</repeat>

// index.wpy
<List :mylist.sync="mylist"></List>
```

来自官方文档对于目前 wepy 1.x 静态组件存在的问题的解决方案

**Comment by iniself** [comment]
@yz-xlame 问题不是传递props，而是当我们repeat一个<child></child>子组件，那么这些子组件是共享一个实例的。假设child子组件有一个tap事件，这个事件的作用是让一段文字变色
```
//child子组件
<template>
     <a  @tap="toggle"><text class="{{color}}"></text></a>
</template>

<script>
data = {color:"normal"}
methods = {
      "toggle":function () {
            this.color="red"
        }
}        
</script>
```

以上只是简单举个例子。我的问题是当tap其中一个child组件时，所有的child组件都会变色，至于父组件传入子组件的props问题我可以搞定

@August-Z 你说的，我明白，但几乎跟我的问题没有多大关系

**Comment by yz-xlame** [comment]
@iniself 如果是你这个的话,还是我说的,你应该把需要改变的颜色写在 data中:
 items:[
    {color: '#aaa'},
    {color: '#bbb'},
    {color: '#ccc'},
  ],
然后在repeat的时候把整个item传入,随后在child中的如tap时间中可以获取this.item.color
@August-Z 恕我冒昧,我文档有看,不需要您复述一遍-_-||

**Comment by iniself** [comment]
@yz-xlame 我所指出的问题是：在子组件中绑定一个data值后(比如我的例子里的this.data.color)，如果改变其中任何一个子组件中data中的color值，所有repeat出来的子组件都会进行响应。你的解决办法应该不能解决我提出的这个响应式问题的(我刚也测试过了)，或则我没有了解你解决办法中的关键点？

**Comment by yz-xlame** [comment]
@iniself我的关键是把整个item传入子元素,而不是item的某个属性,因为item的属性在子元素的js中是无法读取的,而传入item本身是可以在子元素中获取的

**Comment by gg343917542** [comment]
跟repeat应该没关系，我试过同一父组件用2个相同的子组件也会出现这种情况

**Comment by yz-xlame** [comment]
@gg343917542 你是否在组件的components里面声明同一组件的不同名称呢如：
components:{
A : compa,
B: compa,
}
如果不这样，那么就是你的问题了

**Comment by gg343917542** [comment]
@yz-xlame 是的，最后我是用这办法解决的，但是遵循vue的逻辑是不需要这样做的

**Comment by yz-xlame** [comment]
@gg343917542 如果你仔细看wepy文档就知道了

**Comment by amoydavid** [comment]
循环组件里的data也是共享的。所以在1.7.x版本下的循环组件还不太舒服。比如我有一个列表。然后修改列表中的某一项的某个data的时候，其它项data都会修改。
这就有点吐血了。

**Comment by amoydavid** [comment]
惊喜地发现 2.0.x 添加了对原生 Component 的支持。这样就很666了！

**Comment by Thinking80s** [comment]
所有循环出来的组件数据是共用的，页面中多个组件循环很蛋疼

**Comment by Nisus-Liu** [comment]
> 惊喜地发现 2.0.x 添加了对原生 Component 的支持。这样就很666了！

wepy 最新版还是 1.7.2 吧, 什么时候出 2.0.x 呀
