### ISSUE TITLE
使用条件判断注册事件的写法，如果给方法传参时编译不通过

### ISSUE THREAD

**Issue by mmmaming** [Tencent/wepy#1550]
## Description

  使用三元运算符给tap事件增加chooseAddress方法时，如果chooseAddress方法不传参数，则可以正常使用 `@tap="{{from == 'order' ? 'chooseAddress' : ''}}"`。 如果给chooseAddress方法增加括号传参，则编译报错不通过。 `@tap="{{from == 'order' ? 'chooseAddress()' : ''}}"`

## Environment

  * wepy version: 1.7.3

**Comment by fonglezen** [comment]
使用方法的问题吧，参数都是通过标签中使用data-xxx="123"，然后在绑定的事件中：
```
chooseAddress (e) {
  //参数在此, xxx = 123
   let xxx = e.target.dataset.xxx;
}
```

**Comment by mmmaming** [comment]
![image](https://user-images.githubusercontent.com/12390314/42202545-6115a30e-7ece-11e8-8cef-28c230a49df7.png)

这个wepy做了优化啊
@fonglezen
