### ISSUE TITLE
wepy动态组件的问题？

### ISSUE THREAD

**Issue by Chris-wei** [Tencent/wepy#1554]
之前看文章说 wepy 里面支持动态组件，

`<component id="com" path="com"></component`        ,

我都引入并在 components 里面声明了，为什么还是组件未找到？

**Comment by Gcaufy** [comment]
什么需求场景

**Comment by Chris-wei** [comment]
动态渲染页面，通过后台配置参数来渲染页面的样式 @Gcaufy

**Comment by Gcaufy** [comment]
写两个组件，然后通过 wx:if 去控制 。
