### ISSUE TITLE
wepy开发者你好，我想请问 组件循环 不同写法对性能、页面渲染出的时间 是否有影响

### ISSUE THREAD

**Issue by clevok** [Tencent/wepy#1561]
### 场景
- 首页 index.wpy
- 组件 child.wpy

### 1. `index页面` 循环 渲染 `child组件`
代码
`index.wpy`
```
<repeat for="{{list}}" key="index" index="index" item="item">
        <!-- 插入<script>脚本部分所声明的child组件，同时传入item -->
        <child :item="item"></child>
</repeat>
```
外部循环list, 将单个 `item` 传入到 `组件` 内渲染出来, 这是第一种做法

### 2.`index`直接将 `list` 传入到 `child组件`内
`index.wpy`
```
<child :list.sync="list"></child>
```
`child.wpy`
```
<template>
<repeat for="{{list}}" key="index" index="index" item="item">
     .......
</repeat>
</template>
```
这种方法主要是 直接将list传入到`child`内，有`child`内循环渲染

## 问题
上述两个方案，哪个能是小程序 view 视图更快的更新出来，因为小程序没有类似performance工具，不知道该怎么测，直觉告诉我应该是第一中方法快，因为第二中存在，将list一个大数据传入到组件内这一步，因此想问问开发者这两者是否有区别

## 主要领导对目前小程序渲染出来的速度不太满意，因此在找办法解决
如果不采用组件化开发，揉成一团，我感觉很糟糕，这是最后解决的办法

**Comment by clevok** [comment]
## emmm 没有人回复码
性能方面的问题, 大家还是蛮关注的才对

**Comment by Gcaufy** [comment]
你看编译出来的dist代码吧。你这两种情况 编译出来的代码几乎是一样的。
另外，建议用第二种方，第一种在repeat中使用props 可能还是有一些总是

**Comment by clevok** [comment]
@Gcaufy 这样，好的，谢谢
