### ISSUE TITLE
使用wepy绑定带参数的事件，且参数是根据数组下标取的某个元素，代码高亮出现问题

### ISSUE THREAD

**Issue by panda912** [Tencent/wepy#1564]
RT，且使用原生事件绑定方式没问题。

[实际表现]
  
![wx20180704-174724](https://user-images.githubusercontent.com/5298742/42270800-4f99f404-7fb4-11e8-8edd-a5ffde166f71.png)

[期望表现]

![wx20180704-174622](https://user-images.githubusercontent.com/5298742/42270810-57b970b0-7fb4-11e8-8c13-17084334dbf9.png)

**Comment by Gcaufy** [comment]
对比一下编译出来的代码吧。。。
理论上这两种都是可以的。

**Comment by panda912** [comment]
@Gcaufy 编译出来的代码没问题的，可以运行，只是高亮出问题了，应该就是中括号导致的。
