### ISSUE TITLE
还是setTimesetout赋值问题

### ISSUE THREAD

**Issue by lunaticnotcrazy** [Tencent/wepy#1568]
问题:变量赋值后再用setTimeout修改变量并不能修改对应的变量而是其他变量
在使用组件中组件赋值时在使用setTimeout再次赋值同一变量不能正确赋值
![image](https://user-images.githubusercontent.com/21071051/42313475-773f963c-8075-11e8-857e-0d0628e13662.png)
![image](https://user-images.githubusercontent.com/21071051/42313494-815fb840-8075-11e8-8ff7-f2a1434e5a20.png)
我点击第二个点击改变先是改成Parent... 预期是1s左右后改成13313，但是并不是第二个点击改变成13313，而是第一个变成了13313，打印this发现this指向的是第一个组件，所以不能正确赋值，如果我还是想只是让第二个点击改变 再次赋值 应该怎么写？

**Comment by lunaticnotcrazy** [comment]
![image](https://user-images.githubusercontent.com/21071051/42315798-e80930da-807a-11e8-858b-c9516c4f64df.png)
![image](https://user-images.githubusercontent.com/21071051/42315812-ef74cc6c-807a-11e8-92ac-1a8d33b0a826.png)
神奇的指向问题 换思路再次赋值了 setTimeout的this指向怎么能改 箭头函数应该就行啊 实在是想不出来了

**Comment by Gcaufy** [comment]
应该是在apply阶段 this的值就被改变了。

**Comment by Gcaufy** [comment]
尽量不要在Repeat中使用component 吧，建议你看一下他的实现。是通过事件获取index 来更新 对应该的值。所以在一些其它场景下可能出现问题。
把repeat写在component里面吧。这样就不会有问题了

**Comment by lunaticnotcrazy** [comment]
好的 多谢 我试下哈

**Comment by whatthecole** [comment]
我在onShow里写了一个异步请求，当第二次赋值的时候就开始失效了，绑定的变量并没有更新，最后用setData()解决
