### ISSUE TITLE
<input type="text" :value="msg" /> 被转换成  v-bind:value.once="msg" 导致报错？

### ISSUE THREAD

**Issue by jimmydong** [Tencent/wepy#1572]
## Description

api.wpy:

    <input type="text" :value="msg" />

转换成： api.wxml

    <input type="text"  v-bind:value.once="msg"/>

导致微信开发工具报错：

    unexpected attribute name, near \\`.once\`

## Environment

  * Platform: 开发者工具
  * Platform version: 1.02
  * wepy-cli version: [wepy-cli -v]
  * wepy version: 1.7.2

**Comment by Gcaufy** [comment]
不支持 :value 属性， 请写成 value="{{msg}}"
