### ISSUE TITLE
升级vue后， 编译web报错： Uncaught TypeError: router.map is not a function

### ISSUE THREAD

**Issue by jimmydong** [Tencent/wepy#1573]
## Description

    wepy build -o web

之前生成的页面可以正常访问。升级vue以后，报错：

    VM726 index.js:2810 Uncaught TypeError: router.map is not a function
    at Object.$createApp (VM726 index.js:2810)
    at Object.<anonymous> (VM726 index.js:199)
    at __webpack_require__ (VM726 index.js:22)
    at VM726 index.js:36
    at VM726 index.js:37

## Environment

  * Platform: Chrome
  * Platform version: 67.0
  * wepy version: 1.7.3

**Comment by Gcaufy** [comment]
不要随意升级 vue, vue-router，除非你知道怎么去修复， 不同版本之间的特性都不一样。。
