### ISSUE TITLE
引用fs模块build报错

### ISSUE THREAD

**Issue by forMine** [Tencent/wepy#1577]
群聊涉及加解密的几个第三方js库，js库中使用fs模块，require("fs")方式去引用的，这样，在使用框架的时候，如果进行build，那个就会报错，missing file fs in .......；

请问这个问题如何解决，如果是原生小程序框架去，是没有build这个步骤，所以使用是没问题的，现在使用框架重构，出现问题，请指导下如何解决。

**Comment by Gcaufy** [comment]
小程序 不是node. 不是所有模块都可以引用的。

**Comment by forMine** [comment]
明白了，好好看了一下源码，有node环境判断，删除了就正常使用了。谢谢
