### ISSUE TITLE
不能在页面的config中设置自定义导航栏吗？比如在a.wpy中的config中设置navigationStyle=”custom“无效。。。

### ISSUE THREAD

**Issue by Hugohui** [Tencent/wepy#1581]
不能在页面的config中设置自定义导航栏吗？比如在a.wpy中的config中设置navigationStyle=”custom“无效。。。

**Comment by Hugohui** [comment]
如果在app.wpy中设置该属性，在页面中启用下拉刷新时，页面整体下拉了，也就是自定义导航栏页被下拉。

**Comment by Gcaufy** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/ui.html
