### ISSUE TITLE
repeat嵌套循环，内循环子组件中无法打印对象型的props

### ISSUE THREAD

**Issue by mylesshie** [Tencent/wepy#1584]
![image](https://user-images.githubusercontent.com/4142212/42515149-aa435656-848d-11e8-855e-5ec536797749.png)

子组件：
![image](https://user-images.githubusercontent.com/4142212/42515178-ba136922-848d-11e8-8e10-f03c09b1da79.png)

遇到的问题：子组件的methods方法中，无法通过this.item打印出props中item的值，现在打印出来均是undefined，但是可以在template中渲染出item的属性

**Comment by mylesshie** [comment]
现在只能通过绑定方法时传入item的属性来做，请问这是bug吗？单层循环没有这种问题，也是第一次使用嵌套循环

**Comment by shenyiling** [comment]
我也遇到了这个问题 不知道该怎么解决。。。 @mylesshie 请问你说的绑定方法时传入item的属性是怎么操作的，可以贴个小示例么

**Comment by shenyiling** [comment]
我也遇到了这个问题

**Comment by Rebornnn** [comment]
我也遇到了这个问题

**Comment by kyyblabla** [comment]
遇到的同样的双重循环问题，目前已经解决。
解决方法其实很简单，只需按照官方文档字面意思去理解，把内循环整体定义为一个新组件（新组件内部可以继续使用repeat）
