### ISSUE TITLE
Android系统下从列表页进入详情页后返回，帧率下降，变卡。

### ISSUE THREAD

**Issue by guanzhentian** [Tencent/wepy#1586]
## Description

在Android系统下从列表页（与列表数据量多小无关）进入详情页（或其他页面）后返回列表页，帧率下降，变卡。iOS系统下表现正常。

## Environment

  * Platform:小程序开发者工具/iOS/Andriod
  * Platform version: Andriod 7.1
  * Wechat version: 6.6.7
  * wepy version: 1.7.3
  
## Reproduce

  在Android系统下:
  在列表页点击新闻进入详情页面后返回，可复现。
  访问其他页面亦可复现。

### Observed Results
  
  在不切换页面的情况下，随着列表数据的增加不会出现性能下降的情况。
  
  在Android系统下:
  切换页面后返回列表页，性能下降，帧率下降。
  随后不断进入其他页面后返回，性能可能回复正常，原因未知。
  
### Expected Results
  
  Android系统的表现与iOS一致。

**Comment by zhengguorong** [comment]
redux connect.js抢占后台资源了，可以参考我的解决方案
https://juejin.im/post/5b67b07ef265da0fa21aa51a
