### ISSUE TITLE
wepy.login未定义

### ISSUE THREAD

**Issue by lzl124631x** [Tencent/wepy#1587]
`wepy.login()`之前跑得好好的, 今天突然` _wepy2.default.login is not a function `. 感觉应该不是你们的问题, 但我也实在想不到我可能做了什么导致这个问题. 有没有思路...

我看了一下wepy的代码好像没有login这个方法??

@Gcaufy wepy 还有 login这个方法么? 我在node_modules里面搜了一遍, 只能看到wepy的readme里面出现了login

wepy版本: 1.7.1

**Comment by lzl124631x** [comment]
好吧... 发现问题了, 你们改成`wx.login`了, 麻烦更新下https://tencent.github.io/wepy/document.html#/?id=%E9%92%88%E5%AF%B9%E5%8E%9F%E7%94%9Fapi%E8%BF%9B%E8%A1%8C%E4%BC%98%E5%8C%96

**Comment by lzl124631x** [comment]
为什么改成`wx.login`之后无法promise化了...
```
Cannot read property 'then' of undefined 
```
你们在搞啥...

**Comment by lzl124631x** [comment]
好好的`wepy.login`搞没了. 不懂.

```
function wechatLogin() {
    return new Promise((resolve, reject) => {
        wx.login({
            success: resolve,
            fail: reject
        });
    }).then(res => {
        return _wechatLogin(res.code);
    });
}
```
临时方案.

**Comment by Meowzz95** [comment]
@lzl124631x 
我这边的`wepy.login`没有问题

**Comment by Gcaufy** [comment]
@lzl124631x 
文档搜索一下
```
this.use('promisify')
```

**Comment by lzl124631x** [comment]
@Gcaufy @Meowzz95 我的app.wpy. 我一直在用promisify啊.
```
  constructor() {
    super();
    this.use('requestfix');
    this.use('promisify');
  }
```

**Comment by Gcaufy** [comment]
@lzl124631x 
```
 constructor() {
    super();
    this.use('requestfix');
    this.use('promisify');
    
   // wepy.login是在 init 阶段才生成的，因此在 constructor 中打 console.log 肯定是 undefined
   setTimeout(function () { console.log(wepy.login)}, 1000);
  }
```
