### ISSUE TITLE
config中不能使用变量的问题

### ISSUE THREAD

**Issue by cnahliu** [Tencent/wepy#1592]
## Description

config 中 不能使用变量。

使用场景，批量开发小程序时，期望有地方可以配置小程序标题名，供其他页面调用。
 

## Environment

  * Platform:-
  * Platform version: -
  * Wechat version: -
  * wepy-cli version: 1.7.2
  * wepy version: 1.7.1
  * other version: -
  
## Reproduce

  [如何重现问题]
  
  运行下面代码。

### Observed Results

  [实际表现]
  
```
[11:06:43] [错误] WPY : src/pages/template.wpy
[Error] 解析config出错，报错信息：ReferenceError: APP_NAME is not defined
{
    navigationBarTitleText: APP_NAME
  }
```
  
### Expected Results

  [期望表现]
  
 config 中能正常使用变量
  

## Relevant Code / Logs

  ```
<template>

</template>
<script>
import wepy from 'wepy'
// import { HOST_DOMAIN, APP_NAME } from '@/utils/config'
const HOST_DOMAIN = 'https://api.com'
const APP_NAME = '小小小'
export default class Index extends wepy.page {
  config = {
    navigationBarTitleText: APP_NAME
  };
  data = {
    HOST_DOMAIN,
    APP_NAME
  };
}
</script>

<style lang="less" scoped>
</style>

  ```

**Comment by Gcaufy** [comment]
使用 replace 插件去实现这个需求

**Comment by cnahliu** [comment]
OK.

**Comment by FuDesign2008** [comment]
> OK.

能搞定么？试了几次，都没有成功

**Comment by FuDesign2008** [comment]
> 使用 replace 插件去实现这个需求

看起来很简单，但试了几次没有成功，能给一个成功的例子么？
