### ISSUE TITLE
动态渲染底部 tabbar

### ISSUE THREAD

**Issue by gauseen** [Tencent/wepy#1593]
需求：  
有两个角色，每个角色有不同的权限，所以要根据角色显示不同的 tabbar ，不知道是否支持动态渲染`tabbar`啊？  或者有没有其他好的实现方式？
谢谢！

**Comment by Gcaufy** [comment]
自己实现这个tabbar

**Comment by gauseen** [comment]
但要是自己写Tabbar组件，wepy不像vue router 可以嵌套路由，那用到tabbar组件的页面都要引入注册这个组件，感觉不怎么优雅，而且当页面切换，tabbar 会有闪动。不知大神有没有优雅些的方式，谢谢！

**Comment by zhongbo320** [comment]
请教一下大神是如何打包上传到微信公众平台的 我是用wepy build --watch 编译后直接上传 但是报index.template.html未打包 万分感谢

**Comment by gauseen** [comment]
@zhongbo320 通过微信开发工具直接上传的dist目录，我用的自己公众号测试发布的：体验版，无报错
