### ISSUE TITLE
如何引用插件的组件（非本地组件）

### ISSUE THREAD

**Issue by Tingwei-Justin** [Tencent/wepy#1594]
## Description
Import 正常的组件可以用import name from ...
但是如何import一个插件的组件呢？

![image](https://user-images.githubusercontent.com/33661382/42627138-b902f4ea-85fe-11e8-8dd4-573225a58946.png)
这样貌似不可以？
求大神帮忙

**Comment by PatrickSR** [comment]
在wepy引用插件的方式
1、在app.wpy文件里的config对象增加plugin的引用
```javascript
export default class extends wepy.app {
  config = {
    pages: [
      'pages/index'
    ],
    plugins: {
      weather: {
        version: '1.0.2',
        provider: 'wx60d306fd175fe556'
      }
    }
  }
}
```

2、在使用插件的页面（继承wepy.page）里的config对象补充usingComponents
```javascript
export default class Index extends wepy.page {
    config = {
      navigationBarTitleText: 'test',
      usingComponents: {
        weather: 'plugin://weather/weatherlist'
      }
    }
}
```

3、使用插件就直接在template的代码使用就好
```html
<view class="container">
  <weather />
</view>
```

**Comment by Bantes** [comment]
在app.wpy文件里的config对象增加plugin的引用后：

VM36000:1 [non-writable] modification of global variable "App" is not allowed when using plugins at app.json.
VM36000:1 [non-writable] modification of global variable "Page" is not allowed when using plugins at app.json.
