### ISSUE TITLE
安装wepy-cli失败

### ISSUE THREAD

**Issue by Yingkaixiang** [Tencent/wepy#1596]
nodejs: v8.11.2
npm: v5.6.0
os: MacOS 10.13.5

npm ERR! Unexpected end of JSON input while parsing near '..."~0.10.0","oauth-sign'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ykx/.npm/_logs/2018-07-13T03_33_29_255Z-debug.log

使用 Yarn 安装成功，cnpm也会失败。

**Comment by Trgree** [comment]
把源换成taobao的就可以了
```
npm config set registry https://registry.npm.taobao.org/
npm install @wepy/cli -g
```
