### ISSUE TITLE
组件样式无法传递的bug

### ISSUE THREAD

**Issue by SoyMeng** [Tencent/wepy#160]
如果子组件中有定义<style></style>标签,当父组件引用子组件时,如果父组件不添加空的<style></style>，页面无法引用到子组件定义的样式

**Comment by magicwallboy** [comment]
我也遇到这个问题了，我在一个page里调用一个组件A,然后组件A调用组件B，这时候组件B的样式在组件A里边没法显示，我必须在page里边再次import组件B才行。

**Comment by Gcaufy** [comment]
是存在这个问题，下个版本修复。暂时先写个空的`style`吧

**Comment by SoyMeng** [comment]
@magicwallboy 如果你的情况跟我一样，可以看看组件A是否有<style></style>标签

**Comment by magicwallboy** [comment]
@SoyMeng 恩恩，我之前没写<style></style>标签，现在加一个空的可以了。

**Comment by cytle** [comment]
这个解决了吗，发现`v1.5.8`存在此问题。 @Gcaufy

**Comment by Gcaufy** [comment]
@cytle 的确存在，现在才处理。

**Comment by baisheng** [comment]
1.6 版本这个问题又重现了
