### ISSUE TITLE
wepy.showModal确认框点击“确认”和“取消”无法获取状态

### ISSUE THREAD

**Issue by devinxia** [Tencent/wepy#1606]
static confirm(text, title = '确认') {
    return new Promise((resolve, reject) => {
      wepy.showModal({
        title: title,
        content: text,
        showCancel: true,
        success: (res) => {
          if (res.confirm) {
            resolve(true)
          } else if (res.cancel) {
            resolve(false)
          }
        },
        fail: res => {
          resolve(false)
        }
      })
    })
  }
将wepy.showModal改成wx.showModal，问题解决。请尽快修复。。。

**Comment by Gcaufy** [comment]
promisify
