### ISSUE TITLE
能否更新wepy-redux对redux4.0的依赖

### ISSUE THREAD

**Issue by mingenesis** [Tencent/wepy#1608]
redux4.0已经发布有一段时间了，也不再依赖lodash了。wepy-redux能否相应更新支持redux4.0呢？

感谢 @Gcaufy 对wepy项目的辛勤付出

**Comment by Gcaufy** [comment]
@dlhandsome @ystarlongzi

**Comment by ystarlongzi** [comment]
@Gcaufy @dlhandsome 

看了下代码，目前 wepy-redux 应该和 redux 4.0 不冲突

然后，把 [package.json#L17-L18](https://github.com/Tencent/wepy/blob/2.0.x/packages/wepy-redux/package.json#L17-L18) 依赖声明给移除掉，有开发者自行安装 redux ？

**Comment by ystarlongzi** [comment]
@mingenesis 功能使用上应该没什么问题吧

**Comment by ystarlongzi** [comment]
@mingenesis 

你现在 wepy-redux 版本是多少？尝试升级到 `1.5.9` 看下，我看这个版本里已经有把 `peerDependencies ` 给移除掉了
