### ISSUE TITLE
是否可以支持小程序的原生组件在框架中调用？

### ISSUE THREAD

**Issue by angel8731** [Tencent/wepy#1609]
你好，我们开发了一套小程序的组件库，希望可以在wepy的框架中使用，但是看了文档，现在并不支持第三方组件以小程序原生的方式引入，而且现在编译工具也还不提供像webpack的插件（copy-webpack-plugin）这样，把npm包里的文件copy到目标目录中。想了解下，我们怎么样能以正确的方式引入到wepy的框架中呢？组件地址：https://github.com/Mitoo-FE/Mitoo-weapp

**Comment by Gcaufy** [comment]
暂时没有比较优雅的方法去引入。后面会考虑已经开发好了的组件如何快速引用的。

**Comment by songguangyu** [comment]
请问有不优雅的解决方案吗？

**Comment by hydra1983** [comment]
![image](https://user-images.githubusercontent.com/488235/44076366-8f0c324e-9fd2-11e8-815a-98fcdd24f98d.png)

直接拷贝过来貌似就可以用了

![image](https://user-images.githubusercontent.com/488235/44076383-9d551ce4-9fd2-11e8-8c32-90b81d9f313a.png)

**Comment by zjhiphop** [comment]
没办法数据双向同步， sync不work
