### ISSUE TITLE
scss 的 @import 不支持alias？

### ISSUE THREAD

**Issue by JRliu** [Tencent/wepy#1610]
## Description

  scss 的 @import 使用 alias 报错

## Reproduce

@import "~@/style/var.scss";
 

### Observed Results

 [Error] Error: File to import not found or unreadable: ~@/style/var.scss.
    at options.error (D:\项目\wepy_demo\myproject\node_modules\node-sass\lib\index.js:291:26)
  （使用相对路径的话，能正确引入）

**Comment by Gcaufy** [comment]
@dlhandsome

**Comment by jilaokang** [comment]
一样问题

**Comment by zcandlyx** [comment]
这个问题我也遇到了，楼主解决了没有

**Comment by dream2023** [comment]
没人理吗？

**Comment by linkaibin** [comment]
可以使用wepy.config设置`sass`的`includePaths`

**Comment by jumpDuckEgg** [comment]
> 可以使用wepy.config设置`sass`的`includePaths`

请问你是怎么配置的

**Comment by FreeRide-Joe** [comment]
> 可以使用wepy.config设置`sass`的`includePaths`

@linkaibin 请问如何配置？能否提供一个有效的代码看看，我这边测试的不行..

**Comment by callmesoul** [comment]
都没解决关毛线啊

**Comment by zcandlyx** [comment]
什么鬼呀




------------------ 原始邮件 ------------------
发件人: "CallMeSoul"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 下午3:42
收件人: "Tencent/wepy"<wepy@noreply.github.com>; 
抄送: "1052261772"<1052261772@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Tencent/wepy] scss 的 @import 不支持alias？ (#1610)




都没解决关毛线啊
