### ISSUE TITLE
wepy.scancode 不返回任何数据

### ISSUE THREAD

**Issue by SkinsTY** [Tencent/wepy#1614]
使用wepy.scancode不返回任何数据，在开发者工具跟手机上都不返回。只能用原生的方法wx.scancode才能返回数据，想确认下这个问题

**Comment by Gcaufy** [comment]
promisify?

**Comment by Zhang-WJ** [comment]
我也遇到这样的请况哦，怎么解决？

**Comment by rocco0505** [comment]
> 我也遇到这样的请况哦，怎么解决？

wepy.scanCode({}).then(res => {
          console.log(res)
        })
