### ISSUE TITLE
.wepyignore 失效

### ISSUE THREAD

**Issue by hereisfun** [Tencent/wepy#1615]
## Description
原本需求：使用vim做开发，中间会出现很多临时的.swp文件，触发wepy build --watch导致多次重新编译。后面在.wepyignore中加入**/*.swp后，.swp文件仍旧会触发重新编译

**/*.swp规则在.gitignore中能生效，同时还验证了wepy使用的ignore插件能识别这条规则：
```js
const ignore = require('ignore');
const ig = ignore().add(['**/*.swp']);
ig.ignores('src/.app.wpy.swp');       // true
```

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: 1.7.3
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce
1. 用wepy初始化一个项目
2. 在.wepyignore中加入规则**/*.swp
3. 执行npm run dev
4. 在另一个shell用vi打开一个文件`vi src/app.wpy`
5. 编译窗口显示`[变更] 文件: src/.app.wpy.swp`

### Observed Results

  [实际表现]
  
没有忽略.swp文件

  [期望表现]
  
忽略.swp文件
  

## Relevant Code / Logs

无

**Comment by hereisfun** [comment]
看了源码后发现是我理解有误，.wepyignore只负责忽略哪些文件不编译到dist文件夹
如果想在run dev的时候不监听某些文件，可以在项目根目录的wepy.config.js文件中加入选项watchOption:
```js
module.exports = {
    // ...
    watchOption: {
        ignored: '**/*.swp'      // 以忽略.swp文件为例
    }
}
```

其他的监听规则可以查阅[chokidar的文档](https://github.com/paulmillr/chokidar)

建议在文档加上相应说明～

**Comment by Gcaufy** [comment]
@hereisfun 定位到原因了？
