### ISSUE TITLE
scroll-view组件bindscrolltoupper事件加载列表，页面自动至最顶

### ISSUE THREAD

**Issue by forMine** [Tencent/wepy#1618]
使用scroll-view组件上拉加载列表，新加载的列表天添加至当前列表前面渲染，页面会自动跳至最顶端，若需再次触发，需要下拉再去触顶。
请教，如何保持在列表更新之前的位置，如同下拉加载一样！

**Comment by Gcaufy** [comment]
看官方文档，有个onReachBottom和，onPullRefesh

**Comment by forMine** [comment]
您理解错我的意思了，这两个时间我明白，开发一直会用到。。。现在是上拉加载，使用scroll-view组件的bindscrolltoupper事件，添加新加载的列表并且渲染，页面胡滚动至最顶端，跟下拉加载效果不一样。
下拉加载重新渲染后列表会在添加位置停留，因为是改变的列表内容才会触发修改，这样，还可以继续往下滑继续触发事件。
但是上滑加载不一样。难道是我写法有问题么？请指教

**Comment by zhongbo320** [comment]
请教一下大神是如何打包上传到微信公众平台的 我是用wepy build --watch 编译后直接上传 但是报index.template.html未打包 万分感谢

**Comment by 627443839** [comment]
> 请教一下大神是如何打包上传到微信公众平台的 我是用wepy build --watch 编译后直接上传 但是报index.template.html未打包 万分感谢

请问下. 最后你解决了吗. 采用的是什么方案啊

**Comment by 627443839** [comment]
> 您理解错我的意思了，这两个时间我明白，开发一直会用到。。。现在是上拉加载，使用scroll-view组件的bindscrolltoupper事件，添加新加载的列表并且渲染，页面胡滚动至最顶端，跟下拉加载效果不一样。
> 下拉加载重新渲染后列表会在添加位置停留，因为是改变的列表内容才会触发修改，这样，还可以继续往下滑继续触发事件。
> 但是上滑加载不一样。难道是我写法有问题么？请指教

请问下. 最后你解决了吗. 采用的是什么方案啊

**Comment by zhaobinglong** [comment]
使用bindscrolltoupper实现上拉加载历史页面，滚动条停留在当前视图，关键在于生成新的id，scroll-into-view进入指定id的视图，而在生成新id的过程中，旧id不能被重置
https://developers.weixin.qq.com/community/develop/article/doc/000ac0870c0050549bb82185451813
