### ISSUE TITLE
在onShow中动态给this绑定方法

### ISSUE THREAD

**Issue by wangmh1990** [Tencent/wepy#1619]
## 问题描述
 需要在onShow中动态的绑定一个方法到this上（在wepy中使用cfca的密码键盘，需要动态的绑定一个handleInput方法），绑定后提示方法不存在（Do not have handleInput handler in current page）,是不是使用wepy都需要预先定义好方法才行？

**Comment by Gcaufy** [comment]
小程序的this和wepy的this是不一样的，你需要研究一下如何去动态绑定才行，单纯的 this.xxxx = handler 肯定是不行的。
