### ISSUE TITLE
wepy-plugin-imagemin 安装报错 

### ISSUE THREAD

**Issue by YufJi** [Tencent/wepy#1622]
初始化项目后 安装依赖一直loading，后来发现是wepy-plugin-imagemin有问题，求证实

**Comment by Gcaufy** [comment]
依赖的`imagemin`库经常会出问题的，你可以手动安装一下试试。

**Comment by YufJi** [comment]
好的👌 可能也是家里网的问题 谢谢啦




| |
YufJi
邮箱：ji19090213@126.com
|

Signature is customized by Netease Mail Master

在2018年07月22日 14:47，Gcaufy 写道：

依赖的imagemin库经常会出问题的，你可以手动安装一下试试。
