### ISSUE TITLE
connect进去的值是undefined

### ISSUE THREAD

**Issue by kennir** [Tencent/wepy#1623]
在项目中connect到组件的state有概率是undefined， 是不是有可能组件的初始化比store的初始化还要早？我发现这种情况往往是发生在template里需要用到computed的值，而参与compute的值是connect过来的，这种情况下就很有可能会undefined

请问这个情况可以避免吗？还是只能先判断一下connect过来的值是否为undefined ？

**Comment by Gcaufy** [comment]
单线程里不会存在这种概率，你看一下是不是你有什么异步赋值之类的动作。

**Comment by kennir** [comment]
连接根state也会
`@connect({ list: 'list" })`
 这样写也会undefined

**Comment by songguangyu** [comment]
看完了代码 在component里 检测到了computed 就会立刻执行如果先执行到了你自己写的计算属性 并且引用了其他计算属性 就会报错 理论上计算属性引用另一个计算属性是没问题的 只要没有循环引用。

**Comment by songguangyu** [comment]
computed 实现的太粗糙 还是照vue搞一下吧 收集依赖 watcher
