### ISSUE TITLE
可以增加针对wpy单文件的代码混淆功能吗？

### ISSUE THREAD

**Issue by WangShuXian6** [Tencent/wepy#1624]
## Description

>目前的代码混淆功能似乎必须分离出javascript文件[为测试]

>wpy单文件不会混淆其中的javascript部分。

>如果可以直接将wpy单文件内的javascript进行混淆就可以防止小程序被抓包了。
这样可以尽可能降低代码被克隆的风险.

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/tree/2.0.x/packages/wepy-plugin-uglifyjs
