### ISSUE TITLE
关于wepy-redux和components的两个问题

### ISSUE THREAD

**Issue by cq-guojia** [Tencent/wepy#1625]
问题1：关于wepy-redux

```
@connect({
    num(state) {
      return state.counter.num
    },
    inc: 'inc'
  }, {
    addNum: INCREMENT,
    asyncInc
  })
```

这一段必须写到每一个wpy页面上吗？能把它写到mixins里或是app.wpy里，每一个页面都可以直接调用吗？

比如我在redux维护的一个用户信息，每一个页面都要把昵称输出或记录在线时间什么的。这样我每一页都要去写一个同样的@connect的内容，太麻烦了。这个有办法解决吗？

-------------------------------------------------------

问题2：components问题

还有像components也是每一页都要去在页面里 <xxxxx></xxxxx> 引用进去吗？
比如我写了一个显示用户基本信息弹窗的components。我80%的页面都有这个功能。我还必须得每一页都去复制一个<xxxxx></xxxxx> 放大<template></template>里，我能把这个统一放在app.wpy里还是放在哪，到时我在一个utils.js之类的文件里写一个统一的$invoke方法把它调起来就可以了。。。这个又该怎么做呢？

**Comment by Gcaufy** [comment]
1. 全局状态的问题，理论上可以实现的。
2. 全局组件问题，小程序本质上不请允许，但可以通过编译手段时间

这两点在下个大版本里会优先考虑。

**Comment by cq-guojia** [comment]
感谢 @Gcaufy ，期待下个大版本

**Comment by tony0511** [comment]
@Gcaufy 请问一下怎样在 app.wpy 中更新 redux 中 state 的状态，非常感谢！
