### ISSUE TITLE
相同页面返回数据data数据错误

### ISSUE THREAD

**Issue by fitcong** [Tencent/wepy#1627]
页面:A,B
复现步骤:
A(1) -> B      
B -> A(2)
A(1)在data中有userId=234,
A(2)在data中有userId=987,
按照页面栈返回至A(1),
页面A(1)的userId变成了987,

检查A(1)发现this.userId=987,但是this.$wxpage.data.userId却还是原来的234;
大概就是这么个情况!!!

wepy版本   "wepy": "^1.7.0",

这个问题直接导致我返回刷新的页面数据错乱

@Gcaufy

**Comment by liling0726** [comment]
我也遇到这个问题了，有好的解决办法吗

**Comment by fitcong** [comment]
@zhongbo320 这个文件要是没用可以进行删除的,是开发者工具报的吧,报这个警告就证明代码已经上传上去了
