### ISSUE TITLE
watch中1个值会改变另一个的情况下，$apply会报错

### ISSUE THREAD

**Issue by L-x-C** [Tencent/wepy#1628]
![image](https://user-images.githubusercontent.com/4329120/43066272-caf04bf8-8e96-11e8-990f-8878d48a8520.png)
比如这个情况下,chooseAll被改变触发chooseAll的watch方法，
在这个方法中，会改变selectedValues，从而触发selectedValues的watch方法

然后就会报错，应该是第一个apply还没完成
![image](https://user-images.githubusercontent.com/4329120/43066342-f97b1570-8e96-11e8-921f-9046828a7836.png)

如果这时我给selectedValues中的apply加个延时，就不会报错，但这显然不是我想要的...
![image](https://user-images.githubusercontent.com/4329120/43066380-15a67a32-8e97-11e8-9c1b-124aaaad735f.png)

所以请问这种情况下应该如何去解决？
或者说有没有办法判断出chooseAll的apply完成了？

**Comment by EdwinMei** [comment]
$$phase的值为false的时候apply就完成了
