### ISSUE TITLE
循环组件传值问题

### ISSUE THREAD

**Issue by SoyMeng** [Tencent/wepy#163]
根据cli生成的工程模板中,如果groupList值为动态的,会出现undifined的错误。
### 关键测试代码：
```
<repeat for="{{groupList}}">
  <group :value="item"></group>
</repeat>
```
```
data = {
     groupList = []
}
```
```
onLoad(){
     setTimeout(() => {
       this.groupList = [      {
          id: 2,
          name: '点击改变',
          list: [
            {
              childid: '2.1',
              childname: '子项，点我改变'
            }, {
              childid: '2.2',
              childname: '子项，点我改变'
            }, {
              childid: '2.3',
              childname: '子项，点我改变'
            }
          ]
        }]
    })
}
```

**Comment by Gcaufy** [comment]
刚用同样的DEMO测试了一下，并没有发现问题。

**Comment by Jonham** [comment]
undefined可能是因为，你没有设初始值。
再者，你的“动态赋值”，是用异步操作，应该调用this.$apply() 才会起作用。

**Comment by SoyMeng** [comment]
因为group组件使用的是${grouplist.list}，是支持"."取值的。
如果grouplist初始化值为[]就会出现异常，如果初始值是[list:[]]就没有问题。
所以循环取值的时候应该加一个判断。

**Comment by Jonham** [comment]
好的，谢谢。

**Comment by Gcaufy** [comment]
无法还原问题， 不了解是什么原因 。

**Comment by SoyMeng** [comment]
@Gcaufy 之前以为可以规避这个问题所以没去跟进，现在由于这个问题引发了其他bug，现在想确认一下，只修改`groupList = []`,发生异常
![qq 20170621110502](https://user-images.githubusercontent.com/6083582/27365238-91b30dfc-5671-11e7-85fe-4821da1e0653.png)

没有人跟我一样吗？

**Comment by CuriosityLxn** [comment]
这是一个bug，repeat传给子组件的值只能在子组件的template中渲染出来，子组件的script无法获取，会显示undefined，在这里困扰好久了，还在寻求解决方法。

**Comment by holysky5** [comment]
这是一个bug，repeat传给子组件的值只能在子组件的template中渲染出来，子组件的script无法获取，会显示undefined，在这里困扰好久了，还在寻求解决方法。
