### ISSUE TITLE
source map可以排除某些文件吗？

### ISSUE THREAD

**Issue by Fundebug** [Tencent/wepy#1634]
Fundebug的微信小程序错误监控插件[0.6.1](https://wxjs.fundebug.cn/fundebug.0.6.1.min.js)本来只有**84KB**，但是wepy build之后，dist目录中的fundebug.0.6.1.min.js变成了**444KB**

<img width="726" alt="2018-07-26 11 32 53" src="https://user-images.githubusercontent.com/26496557/43240240-141ecf2e-90c8-11e8-843b-c4ccfb9bfc18.png">

查了一下，是由于Source Map导致的。dist目录中的fundebug.0.6.1.min.js多了一行**sourceMappingURL**。

把wepy.config.js中的"sourceMap: true"改成"sourceMap: false"之后：

```javascript
    babel: {
      sourceMap: false,
      presets: [
        'env'
      ],
      plugins: [
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions',
      ]
    }
```

dist目录中的fundebug.0.6.1.min.js没有sourceMappingURL了，大小也变成了**107KB**，小了很多。

这样的话source map完全关闭了，是否可以只排除特定文件，比如Fundebug插件呢？另外在生产环境中，似乎没有必要开启source map吧？

**Comment by ly351204778** [comment]
楼主请问这个问题你这边解决了吗？

**Comment by Fundebug** [comment]
@ly351204778 木有解决

**Comment by liguobao** [comment]
最新版本SourceMap是被移除了吗？

**Comment by someoneiscoding** [comment]
sourceMap 设置为 true 不生效，改为 sourceMap: 'inline' 之后解决。
