### ISSUE TITLE
app.wpy 使用变量问题

### ISSUE THREAD

**Issue by layen520** [Tencent/wepy#1635]
想在app.wpy动态设置标题信息，但是发现编译不通过，这是为何呢，是我有写法有问题还是不支持呢
![image](https://user-images.githubusercontent.com/19701056/43251546-c2d01102-90f2-11e8-901f-46216bb8c455.png)

![image](https://user-images.githubusercontent.com/19701056/43251504-aced7a3c-90f2-11e8-993c-fff690252a06.png)

**Comment by EdwinMei** [comment]
这里你把变量写在了class对象外边，所以无法引用，报了not defined

**Comment by layen520** [comment]
@EdwinMei 变量我就是要从另外的文件import 进来的  但是也是报这个错误 相当于动态设置
