### ISSUE TITLE
打包上传到微信服务器 不是上传dist里面的所有文件么

### ISSUE THREAD

**Issue by zhongbo320** [Tencent/wepy#1639]
提交ISSUE前请确保已认真阅读以下内容

*Please read the following information carefully before you open an issue.*

在提交issue之前必须确认以下问题：

*Please make sure you understand the following points:*

* 必须是一个bug或者功能新增。

* *It must be a bug or a feature request*

* 必须是WePY相关问题，原生小程序问题去[开发者论坛](https://developers.weixin.qq.com/)。

* *It must be a WePY issue.*

* 已经在issue中搜索过，并且没有找到相似的issue或者解决方案。

* *I searched issue already but I did't find any relevant issues or solutions.*

* 完善下面模板中的信息

* *Please filled out the following template*

阅读完后请在提交的issue中删除以上内容，包括分割线

DELETE THE INFORMATION ABOVE(INCLUDE THE SEPARATION LINE) BEFORE YOU OPEN AN ISSUE

------------------------
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs here to reproduce the problem
  // 可以使用小程序代码片段功能，方便其它人帮助你定位代码问题
  // 详情可参考这里：https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
  ```
我打包上传所有的dist文件  但是报index.template.html文件没有被打包上传 请大神指点一下

**Comment by chenyuwulu** [comment]
wepy的机制就是这样，src下是我们写逻辑代码的地方，往里面拷入非js文件，wepy的解决方式都是复制一个到dist下。所以你看dist下是不是有html文件。另外，小程序只接受json，wxml，wxss，js这些文件，其他文件，都会忽略不压缩上传，所谓的报错，就是一个警告而已，要么一开始创建wepy项目的时候别去全部true，要么就自己手动删掉，不影响使用

**Comment by qqjt** [comment]
楼上说得对，将 src 下的 index.template.html 删掉，清空 dist 文件夹重新 wepy build 就可以了。
