### ISSUE TITLE
子页面继承父页面无法正常显示component

### ISSUE THREAD

**Issue by e8wow** [Tencent/wepy#1641]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

  希望通过mixin或es6的继承去继承一个基类页面，实现全局组件，子页面components属性已经继承或混合到但却无法正常显示组件

## Environment

  * Platform: [开发者工具]
  * Platform version: [1.02.1807200]
  * Wechat version: [2.2.0]
  * wepy-cli version: [1.7.3]
  * wepy version: [1.6.0]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

  在BasePage页面中引入继承了wepy.component的组件，并填写了对应的components属性或使用mixin混合components属性

### Observed Results

  [实际表现]
  
  [Observed Results]

  子Page无法正常显示组件
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  
  子组件继承父组件的组件，并正常展示

## Relevant Code / Logs

  ```html
<!-- BasePage -->
<script>
    import wepy from 'wepy';

    import Copyright from './Copyright'
    import PrimaryButton from './PrimaryButton'

    export default class BasePage extends wepy.page {
        components = {
            copyright: Copyright,
            'primary-button': PrimaryButton
        }
    }
</script>

<!-- 子页面 -->
<script>
 import BasePage from '../../../components/common/BasePage'

    export default class QRCodeLogin extends BasePage {
        constructor() {
            super()
        }
    }
</script>

```

或使用混合

```javascript
// Base-mixin
import wepy from 'wepy';

import Copyright from '../components/common/Copyright.wpy'
import PrimaryButton from '../components/common/PrimaryButton.wpy'

export default class BaseBaseMixin extends wepy.mixin {
    components = {
        copyright: Copyright,
        'primary-button': PrimaryButton
    }
}

// 子页面
import BasePage from '../../../components/common/BasePage'

export default class QRCodeLogin extends BasePage {
    constructor() {
        super()
    }
    mixins = [BaseMixin]
}

```

子页面console.log打印实例后发现components属性已经继承过来了，但还是无法正常显示组件，在DOM中PrimaryButton组件就为
```html
<primary-button></primary-button>
```

**Comment by solgh** [comment]
遇到同样的问题

**Comment by zhuqling** [comment]
Page继承只能继承js内容，这个有说明
Mixins混合不能继承components，这个是bug
