### ISSUE TITLE
有关 repeat 动态自定义组件 和 原生自定义组件引入的问题

### ISSUE THREAD

**Issue by WynnLin** [Tencent/wepy#1643]
repeat 的各种问题都已经知道了，如果是纯静态的显示作用的list, 各种hack 都能绕，但是现在遇到一个动态的list 的问题，就是在list 的item 里面有倒计时的组件，每个item 里的倒计时时间都有可能是不一样的，基于component 在渲染的时候只会触发一次onLoad方法，现在没找到解决方法。
然后想尝试把倒计时组件做成原生引入，升级到了1.7.2-alpha1，然后改变引入方式，如下
`
components = {
      '@count-down': Countdown
}
`
结果发现只有空白的占位元素
不知道是不是还需要做什么样的升级

以下几个问题
1. 原生组件的引入需要怎么样的具体操作？ 依照官方文档的来好像行不通，希望能有个demo和具体的方案
2. 有大大知道上面那样的倒计时方式可以怎么做
3. 官方说的2.x版本会解决repeat, 请问有具体的上线时间吗？

感谢wepy的开发人员的辛苦开发，让我们可以轻便了很多，希望以上问题有大大能帮忙解答下，有任何不清楚的，我可以再具体描述
感谢

**Comment by 738579138** [comment]
我也遇到了跟你一样的问题： 我的问题是一个倒计时模块，在一个页面中多次渲染出来多个相同模块，这个几个相同模块公用一个实例，所以使用下面1的方法拿到的到计时数据都是相同的。

1.我的办法是父组件请求到数据后，进行$broadcast发布，然后在子组件中 event 中写 方法，在这个方法里面用this.$parent获取父级的data里面的数据，在根据你在repeat 渲染组件时候的判断是否显示的值，来获取数据，但是这样因为这个判断条件的值是写死的，所以有多个这个数据的时候就出现了，所有的模块都是相同的倒计时时间。
2.这个时候应该不是用判断组件显示的值去获取对应数据，而是直接把所有符合组件渲染值的数据都提取出来弄成一个数据，然后在用for 循环这个数据，对这个数据里面所有的数据进行倒计时处理，然后在组件的 dom 元素上在用repeat 循环 这个for 循环处理后的数据，因为元素的渲染部分是可以获取到外面传进来的值，这时候就用这个值里面的唯一id 跟for 循环处理好的数据进行比对。

这是我的方案希望对你有所帮助
