### ISSUE TITLE
如何wpy里做data中值计算

### ISSUE THREAD

**Issue by zzwar2009** [Tencent/wepy#1644]
## Description

 开发者们你们好 ，首先谢谢你们的框架提供的便利，有一个一直困扰我的问题 我开发了一整个小程序项目也没整明白就导致代码写的很拖沓，如何wpy里做计算（比如格式化数字，两个属性的关联计算等），例子如下，想请教一下如何写

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]  
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里] ^1.6.0
  
## Reproduce

 ```
<style lang="less">
</style>
<template>
    <text class="info">{{plus({{a}},{{b}})}}</text>
    <text>上面这个肯定是不对 ，不知道怎么写</text>
</template>

<script>
  import wepy from 'wepy'
  function plus(a,b){
      return a+b
  }
  export default class Test extends wepy.page {
    config = {
      navigationBarTitleText: 'test----'
    }
    data = {
        a:1,
        b:2
    }
    onLoad() {
      
    }
  }
</script>
```

**Comment by Windancer** [comment]
<style lang="less">
</style>
<template>
   <text class="info">{{plus}}</text>
   <text>上面这个肯定对</text>
</template>

<script>
 import wepy from 'wepy'
 export default class Test extends wepy.page {
   config = {
     navigationBarTitleText: 'test----'
   }
   computed = {
     plus(){
        return this.a + this.b
     }
   }
   data = {
       a:1,
       b:2
   }
 }
</script>

**Comment by zzwar2009** [comment]
首先谢谢，不是这个意思，
比如 我就想算plus(4,5) ,4和5不是data的值 ，<text>{{plus(a,b)}}</text>  类似这样的写法 怎么写？
或者 plus({{a}},5)  这种

**Comment by Windancer** [comment]
模板不应该承载计算的任务，那是计算属性的任务。但是计算属性不接受参数。
所以，你需要在使用前通过js计算好再插值。
如果是函数计算，通过自定义函数
`
<pre><code><style lang="less">
</style>
`<template>
   <text class="info">{{a}}</text>
   <text>上面这个肯定对</text>
</template>`

<script>
 import wepy from 'wepy'
 export default class Test extends wepy.page {
   config = {
     navigationBarTitleText: 'test----'
   }
  data = {
       a:1,
       b:2
   }
   onShow (option) {
     this.a = this.plus(1,2);
     // this.a = this.plus(1,this.b);
   }
   plus(a,b){
        return a + b
     }
 }
</script>
</code></pre>
`

**Comment by savioryu** [comment]
建议使用小程序原生的 wxs。示例如下：
```
<style lang="less">
</style>
<template>
  <text class="info">{{patch.plus(a,b)}}</text>
</template>

<script>
  import wepy from 'wepy'
  import patch  from '../wxs/patch'

  export default class Test extends wepy.page {
    config = {
      navigationBarTitleText: 'test----'
    }
    wxs = {
      patch
    }
  data = {
    a: 1,
    b: 2
  }
  onShow (option) {}
  }
</script>

<!--patch.wxs-->
module.exports = {
  plus: function(a, b) {
    return a + b
  }
}
```

**Comment by zzwar2009** [comment]
谢谢楼上，我觉得这个是我想要的答案 虽然不理解 为啥还要非得写到wxs里 但是能解决很多问题了
