### ISSUE TITLE
[feature] wepy-cli 能否给个选项: use npm or yarn 

### ISSUE THREAD

**Issue by chenyeah** [Tencent/wepy#1653]
## Description

  问题描述：因为我一直使用`yarn`,按照正常步骤开发，yarn 安装包 ，开发没有问题，但是当我 `yarn build` 时 提示我缺少包 ，这是会自动帮我安装包 ，但是自动安装的包是使用 npm 的 这会出现连个lock 文件 而且也会打包错误

### Expected Results
当生成模板时 额外加个选项 使用 yarn 或者 npm 这样打包缺少模块时 可以按照之前的的选择 使用对应方式安装

**Comment by Gcaufy** [comment]
你ctrl+c之后 再手动用yarn安装一下就可以了。
