### ISSUE TITLE
跨页面调用方法报错

### ISSUE THREAD

**Issue by forMine** [Tencent/wepy#1658]
跨页面栈调用其他页面的方法，
获取所有页面栈，然后调用方法所在页面实例，调用方法。
比如：
var page = getCurrentPages()[0];
**page.getUserInfo()**  
如果getUserInfo不传参调用，报错，错误提示缺少type，编译报错，不是代码本身报错，方法中随便传递参数，只要不为空。方法就可以正常调用（ps:参数为函数执行无关参数）

求解：是什么问题？

**Comment by JohnPion-Zhang** [comment]
你在dom事件处理函数中调用试试

**Comment by Riant** [comment]
无语了，issue 没人响应就直接关闭了？

试试
```
var page = getCurrentPages()[0]
page.$wepy.getUserInfo()
```
