### ISSUE TITLE
【源码阅读】关于异步赋值的一点意见

### ISSUE THREAD

**Issue by Inori-Lover** [Tencent/wepy#1666]
## Description

如[#536](https://github.com/Tencent/wepy/issues/536)，[#443](https://github.com/Tencent/wepy/issues/443)描述；
简单总结一下：
页面A、B，A页面只有跳转一个功能，B页面在onLoad函数定义异步赋值；
在快速进行A与B页面之间跳转之后可以持续观察到B页面onLoad函数中的异步函数的赋值效果，该效果在原生中并不存在

## Environment

  * Platform: 开发者工具（仅测试开发者工具了）
  * Platform version: `window10 1803`
  * Wechat version: `web开发者工具 1.02.1807200`
  * wepy-cli version: null
  * wepy version: `1.7.2`
  * other version: null
  
## Reproduce

  [如何重现问题]

  https://github.com/Inori-Lover/temp_bug_report

  clone下来并导入开发者工具就好（代码并未做清理所以package.json可能有很多奇奇怪怪的依赖……

### Observed Results

  已经关闭的页面的初始化函数 **持续** 影响新打开的页面（路径`/pages/pageB`表现）
  
### Expected Results

  已经关闭的页面的初始化函数 **不应该** 影响新打开的页面（路径`/pages/pageBFix`表现）
  

## Personal message
1. 关于代码小片段的问题，我尝试在项目代码基础上新建代码片段（在项目管理界面也确实分类在代码片段分区），但工具栏上并没有正常的分享按钮，个人估计是代码体积问题，所以选择新建一个项目供clone复现
2. 关于标题（终于要聊到标题的东西了）提到异步赋值bug，我认为关键是在 [setData](https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy/src/component.js#L271) 的实现函数上，该函数每次运行都以当前页面栈（我猜的- -整个项目有点庞大暂时没精力或者说能力全部理解）为基础运行，导致运行在微信的emit事件时取到的`this.__wxWebviewId__`一直都是当前页面的所以并未过滤掉多余的赋值行为。（我认为原生没有这个问题就是依靠`__wxWebviewId__`与当前激活页面并不匹配然后过滤赋值操作）
3. 由此引发出的顾虑是，假设这个问题无法修复的话，那么wepy的异步赋值将变得不可信，也不排除我个人因此转框架应付工作。（保留意见，临时出现的想法）
4. 不清楚这个问题是否在2.x分支依然存在。
5. 激发这次探究主要也是对上边两个issue中作者受到的待遇抱有不平。国内大公司做开源并不简单（很可惜这也是猜，并没有机会进大公司😂），看看旁边ali就知道。提出issue并不是用来发泄你对框架的不满或者换取作者对你issue的承诺。鬼都知道软件写出来就很多bug，linux尚且需要bug收集，不能说你提出issue就一定会换来bug修复，只能说这是一个反馈渠道。当你没法提供更多的见解时我觉得点到为止就好，大家良性互动一下多好。

以上。期望得到回复

**Comment by Gcaufy** [comment]
感谢回复，当前的精力都放在2.x的开发当中，2.x是不存在这个问题的。
1.7的问题会暂缓处理，抱歉。
