### ISSUE TITLE
关于在微信开发者工具与真机行为差异的问题~·····

### ISSUE THREAD

**Issue by Kidwind** [Tencent/wepy#1669]
## Description

  之前的开发人员在项目中写了一个Tab组件，项目发布时没有问题，最近需要修改一部分代码，将项目拉取下来，构建后发现在PC端的微信开发者工具中，组件的行为表现正常，但我使用预览功能在手机上查看时，选项卡切换效果无效，更奇怪的是当我使用远程调试功能在手机上调试时，又是正常的，一旦断开远程调试，又异常了。

## Environment

  * Platform: Android及IOS平台微信
  * Platform version: Android 微信6.6.7，IOS 微信 6.7.1
  * Wechat version: 6.6.7
  * wepy-cli version: 1.7.3
  * wepy version: 1.7.2
  
## Reproduce

  1、获取示例代码
  [wepy_project.zip](https://github.com/Tencent/wepy/files/2259374/wepy_project.zip)

  2、解压

  3、使用微信开发者工具打开项目的 dist 文件夹

  4、在微信开发者工具中测试项目，切换顶部选项卡，或点击 1 2 3 按钮，选项卡均正常切换。

  5、使用微信开发者工具的预览功能在手机端进行预览，切换顶部选项卡，或点击 1 2 3 按钮，选项卡均无法正常切换。

  6、使用微信开发者工具的远程调试功能在手机端进行调试，切换顶部选项卡，或点击 1 2 3 按钮，选项卡均正常切换，但比较卡。

### Observed Results

  在微信开发者工具中预览表现正常，但在手机端预览选项卡均无法正常切换，而使用远程调试功能在手机端调试又表现正常，只是会比较卡。
  
### Expected Results

  在微信开发者工具中预览与手机中预览表现一至。

**Comment by Inori-Lover** [comment]
我这边帮你试了一下没毛病……lg g5

**Comment by Inori-Lover** [comment]
另外Platform一般是指运行环境- -你直接写是什么平台的微信以及在下一行指定微信版本就好

**Comment by Kidwind** [comment]
@Inori-Lover 不可能吧，我们这里所有手机试都存在这问题哦。

**Comment by Inori-Lover** [comment]
就是真机……说了lg g5了

**Comment by Kidwind** [comment]
@Gcaufy 这个和开启压缩有关系吗？
