### ISSUE TITLE
请问2.0版本大概的公开时间是？

### ISSUE THREAD

**Issue by hareluya** [Tencent/wepy#1670]
一直有看到在更新，不知有没有最新的可公开的时间表呢？

**Comment by hawkefly** [comment]
我也想知道

**Comment by coolhwm** [comment]
表示关注

**Comment by lihuangshuaige** [comment]
+1

**Comment by luandapipi** [comment]
+1

**Comment by Devtll** [comment]
+1

**Comment by songguangyu** [comment]
现在很多issue都不回了 没信心继续用1x版本

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy-wechat-demo/tree/2.0

**Comment by mangoooooo** [comment]
@Gcaufy  请问 如果项目从1x版本升级到2.0版本的话  会有很大改变吗？

**Comment by ycc3000** [comment]
试了一下2.0的app.wpy，wepy.app({}) 但是编译不过去，那个demo是咋弄的。
[编译] 入口: src\app.wpy
\npm\node_modules\wepy-cli\lib\compile-wpy.js:478
var mainPages = wpy.config.pages.map(function (v) {
                                                          ^
TypeError: Cannot read property 'map' of undefined

**Comment by CodArs-van** [comment]
啥时候能开放呢？

**Comment by memotail** [comment]
求开放

**Comment by Gcaufy** [comment]
@ycc3000 2.0的编译程序还没开放，所以你用1.x 的编译去编译是肯定不通过的。

**Comment by ycc3000** [comment]
大家都望眼欲穿了，可以开放α版或者β版呀，大家几千人肯定会比团队几个人的更能发现问题，这也也有助于项目的质量。

**Comment by chenillen** [comment]
關注此問題，可以開放α版本出來嘛？看了看demo，整個寫法都有大的變化，希望能即時用到新的 Project 裡面。這樣之後升級會更好些。

**Comment by cmideal** [comment]
1.0升级到2系列，有没有工具实现还是说不可能？
还有2.0大约啥时候公布呢？老大们

**Comment by chenillen** [comment]
沒有wepy-cli，玩不動。

**Comment by jswxwxf** [comment]
现在还有消息吗？2.0 到底什么时候出啊？

**Comment by chuyun** [comment]
+1 waiting...

**Comment by Gcaufy** [comment]
内测阶段，有兴趣可以私聊我参与内测。

**Comment by ycc3000** [comment]
让我加群先啊，加了几年都没加上，那个助手是弱智。。。

**Comment by cmideal** [comment]
> 内测阶段，有兴趣可以私聊我参与内测。

咋加入内测呢？

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/issues/1802
