### ISSUE TITLE
wepy init 无法输入 appid

### ISSUE THREAD

**Issue by CooCOccO** [Tencent/wepy#1672]
## Environment

  * Platform: mac os
  * Platform version: 10.13.5 (17F77)
  * wepy version：1.7.2/1.7.3
![image](https://user-images.githubusercontent.com/19894388/43704067-27c163e4-9991-11e8-92a4-1cf31ba03396.png)

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/44010213-b3a005ee-9ee3-11e8-9f47-d845c3bf24e6.png)
