### ISSUE TITLE
wepy版本不符合要求,正在尝试更新,请稍等

### ISSUE THREAD

**Issue by shenmashi** [Tencent/wepy#1675]
执行npm run dev 出现以下提示  然后无法正常编译运行
版本
![image](https://user-images.githubusercontent.com/8580637/43831739-b11ac110-9b37-11e8-8e9e-9ec36d07ddc1.png)

wepy版本不符合要求,正在尝试更新,请稍等

**Comment by Gcaufy** [comment]
package.json 里面的wepy 的版本不会，更新 一下就好了
