### ISSUE TITLE
有没有类似Vue的路由守卫钩子可以使用？

### ISSUE THREAD

**Issue by ycc3000** [Tencent/wepy#1678]
要实现一个页面切换显示loading图的功能，Vue的路由有beforeEach和afterEach可以使用，wepy好像没有找到。

**Comment by Gcaufy** [comment]
onRoute

**Comment by ycc3000** [comment]
不能达到预期，一个loading状态应该从未进入页面就开始转圈。。OnRoute就晚了，如果OnLoad里在有点逻辑，就更不好了。。
