### ISSUE TITLE
旧版本iOS（9.3.5）小程序编译出错

### ISSUE THREAD

**Issue by Realzzz1874** [Tencent/wepy#1685]
thirdscripterror sdk uncaught third error syntaxerror unexpected token '>'；
安卓机和10.x以上的iOS版本没有这个问题。

**Comment by d393911462** [comment]
这个问题 应该是需要用es5 编译才可以把

**Comment by Realzzz1874** [comment]
> 这个问题 应该是需要用es5 编译才可以把

转es5编译之后会出现其它报错，而且同试了很多其它的在开发的小程序，没开es5也没有问题。
