### ISSUE TITLE
引入带命名空间@的第三方依赖，若路径为多层会报错

### ISSUE THREAD

**Issue by sunOpar** [Tencent/wepy#1687]
## Description

同这个问题 [#1272](https://github.com/Tencent/wepy/issues/1272)

当引用第三方node_modules包时，若该包带命名空间，且为多层路径，会报错

###  问题代码
https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy-cli/src/compile-script.js#L75

若引入的代码格式为

```
import @xxx/xxx/xxx
```
此时会报错，报错代码地址：https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy-cli/src/compile-script.js#L86

### 原因

```
lib[0] === '@' && lib.indexOf('/') !== -1 && lib.lastIndexOf('/') === lib.indexOf('/')
```

是上面的代码只判断路径为一层的情况，即`@xxx/xxx`，若为多层则会进入下一层逻辑判断。

## 期望
希望能正常引入带有@命名空间且多层路径的第三方依赖。

**Comment by lili21** [comment]
这个问题解决了吗？还是没有解决啊？
