### ISSUE TITLE
[Bug Report] wepy中使用camera + cover-view有bug, 原生则正常

### ISSUE THREAD

**Issue by BoleLee** [Tencent/wepy#1690]
## Description

使用camera + cover-view, IOS使用有Bug, 安卓有轻微bug, 已使用原生方式测试，原生表现则正常，后面为详细信息，以及问题重现

## Environment

  * Platform: [iOS / Andriod]
  * Platform version: [IOS: 11.4 / Android: 7.0]
  * Wechat version: [IOS: 6.7.1 / Android: 6.7.0]
  * wepy-cli version: [1.7.3]
  * wepy version: [1.7.2]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

[问题重现：https://github.com/BoleLee/wepy-camera](https://github.com/BoleLee/wepy-camera) 因为代码包稍微大了点，发不了代码片段，所以发了个项目，还麻烦clone测试下

原生小程序表现正常，可测试代码片段：[wechatide://minicode/iFZ5CEml7h1B](wechatide://minicode/iFZ5CEml7h1B)

### Observed Results

  [实际表现]
  
 IOS：（第二次进入拍摄页面即可重现）
- 进入拍摄页面很慢，大约需要10s
- 拍摄页面`cover-view`不显示
- 在上一个问题的同时，拍摄页面按钮点击无反应

安卓：（必现）
- 摄像头初始为后置，但应该为默认的前置摄像头的
  
### Expected Results

无以上问题，拍摄流程顺畅

## Relevant Code / Logs

[问题重现：https://github.com/BoleLee/wepy-camera](https://github.com/BoleLee/wepy-camera)

[wechatide://minicode/iFZ5CEml7h1B](wechatide://minicode/iFZ5CEml7h1B)

**Comment by BoleLee** [comment]
@Gcaufy 我这边目前为止做了小程序原生和wepy开发的demo，原生表现正常，wepy则重现了实际项目使用中的问题，还麻烦帮忙定位下问题，提供解决的方案，我这边功能等着上线使用，谢谢了～

**Comment by anOrange** [comment]
@BoleLee 原生的dome没问题，这个页面用原生先做着不就好了？

**Comment by BoleLee** [comment]
@anOrange  额，这不表示问题就可以不解决了呀，折中可以考虑混用原生开发，但有其他更好的方案，我为什么要这么做

**Comment by anOrange** [comment]
@BoleLee 是的，用原生的只是上线前的暂缓之计。
不过如果不是框架的问题还好，如果是框架的问题，修复这个问题，可能会引起其他问题。没有充分测试之前，原生的会比较稳定。

**Comment by anOrange** [comment]
@BoleLee 你把  device-position="{{camera}}"  改成  device-position="{{camera || 'front'}}" 试试。

**Comment by pscj** [comment]
遇到相同问题。原生正常，wepy会首次初始化会有问题
