### ISSUE TITLE
wepy-eslint@1.5.4 requires a peer of eslint@>=1.6.0 <4.0.0

### ISSUE THREAD

**Issue by ycc3000** [Tencent/wepy#1692]
Dear,
咱们能不能升级一下支持最新版的Eslint？

npm WARN wepy-eslint@1.5.4 requires a peer of eslint@>=1.6.0 <4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN wepy-eslint@1.5.4 requires a peer of eslint-friendly-formatter@>=2.0.0 < 3.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by huturen** [comment]
版本陈旧，需要更新下

**Comment by DaLiuSam** [comment]
怎么更新呢
