### ISSUE TITLE
wepy build --output ant在支付宝中报错

### ISSUE THREAD

**Issue by wisdomQiuqiu** [Tencent/wepy#1695]
## Environment
支付宝小程序
  * Platform: 蚂蚁开发者工具
  * Platform version: Beta v0.20.0-beta.0
  * wepy-cli version:1.7.3
  * wepy version: 1.7.0
  
## Reproduce
wepy build --output ant之后在支付宝小程序开发者工具里面打开报错 
 Cannot read property 'Promise' of undefined
使用wepy build --watch在微信小程序里面是可以正常运行的。已经加入了this.use('promisify');

**Comment by delayhsiao** [comment]
同问

**Comment by delayhsiao** [comment]
@Gcaufy

**Comment by SpringHgui** [comment]
使用插件实现编译为支付宝小程序代码 [compile2ant](https://github.com/SpringHgui/compile2ant)
