### ISSUE TITLE
在手机中movable-area下的 movable-view在传入x,y坐标后不能定位.

### ISSUE THREAD

**Issue by xiaoyuhao0716** [Tencent/wepy#1700]
------------------------
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]

在开发者工具下可显示 ,
在手机中movable-area下的 movable-view在传入x,y坐标后不能定位.传入值可显示却无法生效.
开发者工具是2.2.2,但是现在微信端版本2.2.3

## Environment

  * Platform:  ios
  * Platform version: 11.4.1
  * Wechat version: 6.7.2
  * wepy-cli version:  1.7.3
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
在手机中运行就会出现

### Observed Results

  [实际表现]

  在手机中movable-area下的 movable-view在传入x,y坐标后不能定位.
 但是在开发者工具情况下可定位
  
### Expected Results

  [期望表现]
  
定位成功  

## Relevant Code / Logs

图片载入...

![](http://ot2duac3w.bkt.clouddn.com/WechatIMG16.jpeg)
![](http://ot2duac3w.bkt.clouddn.com/WechatIMG18.jpeg)
![](http://ot2duac3w.bkt.clouddn.com/WechatIMG17.jpeg)

[代码地址GitHub](https://github.com/xiaoyuhao0716/wxapp-wepy-test/blob/master/src/pages/two.wpy)

**Comment by Teemwu** [comment]
之前写的时候遇到类似赋值无效的问题，用$data重置一遍再赋值就可以了。

**Comment by xiaoyuhao0716** [comment]
@Teemwu  具体怎么实现先重置,在赋值,这样?this.$data = '';this.$data = this.$data;

**Comment by Teemwu** [comment]
应该是版本问题：https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=0004c02a4240508b8837dc57256000&highline=movable-area
