### ISSUE TITLE
wepy框架是否支持小程序插件开发

### ISSUE THREAD

**Issue by lvzirui** [Tencent/wepy#1701]
如果支持的话，怎么整合？

**Comment by Naico** [comment]
可以尝试一下。理论上说都是编辑成原生代码。应该可以的。但是可能要改改编译的逻辑，毕竟文件夹结构不同。还有配置文件。

**Comment by lvzirui** [comment]
求demo

**Comment by Gcaufy** [comment]
我测试了一下，没有冲突，能给可有冲突的demo么。

**Comment by saucedmeat** [comment]
在开发者工具添加插件项目的时候 wepy项目不识别为插件😲

**Comment by milixie** [comment]
求demo

**Comment by milixie** [comment]
> 求demo

有demo了吗，求demo
