### ISSUE TITLE
自定义组件Component生命周期问题？

### ISSUE THREAD

**Issue by pinguo-zhouwei** [Tencent/wepy#1705]
在自定义组件时，Component只有onLoad生命周函数,当切换tab的时候，需要在自定义组件中做一些逻辑操作就不行了，因为这个时候不会执行onLoad(只有第一次启动才会执行),为什么Component不引进和page一样的onShow生命周期方法呢？

**Comment by drawing-snail** [comment]
我也想要在页面的onShow生命周期里触发组件的组件刷新，发现组件不支持onShow， 但是onLoad又不会触发，这样我就需要在页面的onShow去手动调用组件的刷新

**Comment by belerweb** [comment]
需要支持，没人维护了？

**Comment by xiaomizhou66** [comment]
pageLifetimes: {
    show() {},
    hide() {
      // 页面被隐藏
    },
    resize(size) {
      // 页面尺寸变化
    }
  },
这个是什么意思？

**Comment by Jialufeng** [comment]
看了1天的wepy 决定抛弃
就算搞好了，然后过两年 再跑这个项目 不一定能跑起来

**Comment by callmesoul** [comment]
我靠，被坑了，原生组件那么多生命周期，你就只给一个？

**Comment by Gcaufy** [comment]
@callmesoul 1.7 的 wepy 组件是伪组件，那时候 原生还没有自定义组件功能。 所以完全不是一个概念的。

**Comment by callmesoul** [comment]
所以就不用兼容了，就这样了？

**Comment by Gcaufy** [comment]
@callmesoul wepy2 使用的是原生组件。你可以查看 wepy2 的相关 issue 试用看看。

**Comment by callmesoul** [comment]
算了吧，我赶紧迁移算了

**Comment by hiwanz** [comment]
wepy2组件的生命周期同原生组件，见文档[https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/lifetimes.html](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/lifetimes.html)

示例如下：
```html
<style lang="less">
.hello {
    color: green
}
</style>
<template>
  <h1 class="hello">{{text}}</h1>
</template>
<script>
import wepy from '@wepy/core'

wepy.component({
  data: {
    text: 'Hello world!'
  },
  created() {
    console.log('com created')
  },
  ready() {
    console.log('com ready')
  }
})
</script>

```

**Comment by qianyx21** [comment]
> wepy2组件的生命周期同原生组件，见文档https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/lifetimes.html
> 
> 示例如下：
> 
> ```
> <style lang="less">
> .hello {
>     color: green
> }
> </style>
> <template>
>   <h1 class="hello">{{text}}</h1>
> </template>
> <script>
> import wepy from '@wepy/core'
> 
> wepy.component({
>   data: {
>     text: 'Hello world!'
>   },
>   created() {
>     console.log('com created')
>   },
>   ready() {
>     console.log('com ready')
>   }
> })
> </script>
> ```

支持原生的pageLifetime里的show方法吗
