### ISSUE TITLE
使用Mixin时，为什么我的程序会先执行mixin中的函数，再执行组件本身的函数？

### ISSUE THREAD

**Issue by oceansblue** [Tencent/wepy#1706]
## Description

  问题描述：使用Mixin时，我的程序会先执行mixin中的函数，再执行组件本身的函数，但官方文档是：“注意，这里事件的执行顺序跟Vue中相反，Vue中是先执行mixin中的函数， 再执行组件本身的函数。”，但tap又是正常的。
  

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [1.6.0]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

执行基本的
```
npm install wepy-cli -g
npm install
wepy init standard myproject
cd myproject
npm install
wepy build --watch
```

代码直接改成官方的

```
// mixins/test.js
import wepy from 'wepy';

export default class TestMixin extends wepy.mixin {
    methods = {
        tap () {
            console.log('mixin tap');
        }
    };
    onShow() {
        console.log('mixin onshow');
    }
}

// pages/index.wpy
import wepy from 'wepy';
import TestMixin from '../mixins/test';

export default class Index extends wepy.page {

    mixins = [TestMixin];
    methods = {
        tap () {
            console.log('index tap');
        }
    };
    onShow() {
        console.log('index onshow');
    }
}
```

### Observed Results

  [实际表现]
  
 先执行mixin中的函数，再执行组件本身的函数
  
```
mixin onshow
index onshow
// ----- when tap正常
index tap
mix tap
```

### Expected Results

  [期望表现]
  
  [先执行组件本身的函数，再执行mixin中的函数]
  
```
index onshow
mixin onshow
// ----- when tap正常
index tap
mix tap
```

**Comment by CMonoceros** [comment]
1.7.1版本也有这个问题

**Comment by codenamenebula** [comment]
我也遇到了, 请问有解决办法了吗
