### ISSUE TITLE
如何获取原生的Page.route？

### ISSUE THREAD

**Issue by mangoooooo** [Tencent/wepy#1709]
## Description

 小程序文档中 page有个属性route，
但是我通过this.route获取不到，值为undefined，
请问改如何获取？

![qq 20180821172517](https://user-images.githubusercontent.com/16449593/44393601-b44d9d00-a567-11e8-85d8-54d791a7aa8a.png)

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * 调试基础库: [2.2.3]
  * Wechat version: [6.7.2]
  * wepy-cli version: []
  * wepy version: [1.7.2-alpha1]

**Comment by Metallicbai** [comment]
可以使用 getCurrentPages() 获取，最后一个元素表示当前的页面
