### ISSUE TITLE
真心难用

### ISSUE THREAD

**Issue by jilaokang** [Tencent/wepy#1710]
真的

**Comment by wangyequn** [comment]
我之前没感觉那么难用,直到有一天,用VUE写了一个项目,感觉再也 回不来了

**Comment by banxi1988** [comment]
那么 mpvue 这个坑可以尝试跳一下

wangyequn <notifications@github.com>于2018年8月22日周三 上午11:45写道：

**Comment by qinshou** [comment]
每个坑都不一样，入了mpvue你就会发现也是各种坑。wepy好得有个像样的组件支持

**Comment by jilaokang** [comment]
@qinshou 对的，感谢你指出的方向，我去选个组件玩

**Comment by jilaokang** [comment]
@wangyequn Vue的双向绑定确实爽，语法糖吃惯了后果

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy-wechat-demo/tree/2.0

@jilaokang  wepy 2 已经支持到了双向绑定，可以期待一下。

**Comment by jilaokang** [comment]
@Gcaufy 感谢，期待新版本
