### ISSUE TITLE
wepy中支持vue中的条件渲染么

### ISSUE THREAD

**Issue by npm-ued** [Tencent/wepy#1726]
如题：
wepy中使用v-if和v-else不起作用，文档中也没有说相关逻辑判断是什么，是不支持么只能使用wx:if 么

**Comment by Howell5** [comment]
可以使用 wx:if wx:else wx:elif
[代码链接](https://github.com/Tencent/wepy/blob/084ad3bd3c2aceda04f18b5366059da1841fd967/packages/cli/test/core/fixtures/template/assert/v-if.wxml)

**Comment by Ceeson** [comment]
v-if和v-else是vue的吧，wepy的没看到可以这么写啊
