### ISSUE TITLE
wx:if="{{true}}"  无效呢

### ISSUE THREAD

**Issue by liqinhua** [Tencent/wepy#1730]
wx:if="{{true}}"  无效呢

**Comment by liqinhua** [comment]
wx:if="{{true}}"  无效呢

**Comment by Naico** [comment]
用变量试试。变量值设置为true

**Comment by liqinhua** [comment]
变量是可以         wx:if="a ? a == b : true"这样的需求，还要加个变量，感觉有点麻烦了
