### ISSUE TITLE
父组件的传值子组件，对象的某个值改变时，子组件不更新

### ISSUE THREAD

**Issue by liqinhua** [Tencent/wepy#1731]
:aaa.sync="currentFillter.aaa"              手动在父组件改aaa，子组件没有跟着改，组件也没有跟着渲染

**Comment by Ceeson** [comment]
:aaa.sync="currentFillter.aaa"，你把currentFillter.aaa改一下，好像传值到子组件的时候，你改动之后是不会更新，你改成单独一个变量试试，不要用.xx这样的。印象中是这样的，说错望指正。

**Comment by liqinhua** [comment]
变量是可以，整个对象也行，唯一的缺点是对象的某个值传不行，但是vue是可以的
