### ISSUE TITLE
Component 不可以nest Component

### ISSUE THREAD

**Issue by cyc115** [Tencent/wepy#1738]
## Description
在一个component里 使用另一个component会出现 `Uncaught SyntaxError: Invalid or unexpected token` 报错。
<img width="370" alt="image" src="https://user-images.githubusercontent.com/2107333/45003273-6e9cc580-afa6-11e8-9b89-f90dc3818fcf.png">

## Environment

  * Platform: [开发者工具]
  * Platform version: [1.7.2]
  * Wechat version: [2.2.5]
  * wepy-cli version: [1.7.3]
  * wepy version: [1.7.2]
  * other version: []
  
## Reproduce
两个component nest 到一起
### Observed Results

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/2107333/45003339-04385500-afa7-11e8-9eb8-55a6eeb0f1b7.png">

### Expected Results

  child component 会在parent component 内显示

## Relevant Code / Logs
```vue


    <popup
      :visibility.sync="calendarVisibility"
      @onShow.user="onCalendarShow"
      @onHide.user="onCalendarHide"
      type="center">
     <view slot="content">
        
        <view class="calendar-time-picker-container">
          <calendar :checks.syncs="selectedDates" ></calendar>
          <picker class="weui-btn" mode="time" value='{{time}}' @change="onCalendarTimeChange">
            <button>{{i8n.timeSelectionBtnLabel}}</button>
          </picker>
        </view>
      </view>
    </popup>
```

**Comment by Naico** [comment]
<calendar :checks.syncs="selectedDates" ></calendar>
这行的sync写错了吧。。

**Comment by cyc115** [comment]
@Naico  求解释
