### ISSUE TITLE
eval is not a function

### ISSUE THREAD

**Issue by toywei** [Tencent/wepy#1760]
let a =3
let b = {}
while(a){
 eval('b.tag_'+(a-1)+'='+a*a)
 a--
}

**Comment by toywei** [comment]
<script>
    import wepy from 'wepy'
    export default class biz extends wepy.page {
        onLoad() {}
        eval() {
            return eval
        }
        biz() {
            let str
                ...
                this.eval(s)
                ...
        }
    }
</script>

**Comment by toywei** [comment]
`<script>
    import wepy from 'wepy'
    export default class biz extends wepy.page {
        onLoad() {}
        eval() {
            return eval
        }
        biz() {
            let str
                ...
                this.eval(s)
                ...
        }
    }
</script>`

**Comment by toywei** [comment]
biz.wpy	  

    import wepy from 'wepy'
    export default class biz extends wepy.page {
        onLoad() {}
        eval() {
            return eval
        }
        biz() {
            let str
            let target
            for () {
                this.eval(str)
            }
        }
    }

**Comment by toywei** [comment]
biz.wpy	  

    import wepy from 'wepy'
    export default class biz extends wepy.page {
        onLoad() {}
        eval() {
            return eval
        }
        biz() {
            let target
            for () {
                this.eval(str)
            }
        }
    }

**Comment by toywei** [comment]
biz.wpy	  

    import wepy from 'wepy'
    export default class biz extends wepy.page {
        onLoad() {}
        eval() {
            return eval
        }
        biz() {
            let target
            for () {
                eval(str)
            }
        }
    }

**Comment by Gcaufy** [comment]
eval is not support in mini-application
