### ISSUE TITLE
getCurrentPages 获取到上级页面，怎么给上级页面属性传值

### ISSUE THREAD

**Issue by Chen120322** [Tencent/wepy#1762]
getCurrentPages 获取到上级页面，怎么给上级页面属性传值

**Comment by Chen120322** [comment]
getCurrentPages 获取到上级页面，怎么给上级页面属性传值

**Comment by zhuxiwen** [comment]
@Chen120322 这个问题你怎么解决的? 目前我还是没发现合适的方法 = =
