### ISSUE TITLE
修改完代码，编译没问题，但是开发者工具里面拿不到最新代码

### ISSUE THREAD

**Issue by zhouweiming** [Tencent/wepy#1769]
wepy: 1.7.3
开发者工具：1.02.1808101    已开启disable cache

每次修改完代码，都得手动清除所有缓存，或者重新执行wepy build --watch，才能在开发者工具中看到最新代码。

**Comment by DomenLee** [comment]
+1，组内三个人已经遇到这个问题，GG

**Comment by CBCzed** [comment]
所以，楼主的问题解决了吗

**Comment by zhouweiming** [comment]
没解决，但是最近好像又没问题了

**Comment by omeletteWithEgg** [comment]
> @CBCzed 重新安装微信开发者工具，开发的代码包换一个目录，重新加入微信开发者工具，可以这样尝试一下，现在我们这边的前端组已经没有出现了。

我也遇到了。。不晓得是怎么回事，重装微信开发者工具也没用。。
