### ISSUE TITLE
怎么在程序中使用project.config.json 中配置的 appid？

### ISSUE THREAD

**Issue by peizhijie** [Tencent/wepy#1777]
**怎么在程序中使用project.config.json 中配置的 appid？**

- 我想在组件或者page中以调用方式使用的当前小程序配置的appid
- 而不是直接在使用的地方写上`wx123abc14124abc` 这样的字符串

**Comment by faith-hb** [comment]
var accountInfo = wx.getAccountInfoSync();
var appId = accountInfo.miniProgram.appId

**Comment by peizhijie** [comment]
> var accountInfo = wx.getAccountInfoSync();
> var appId = accountInfo.miniProgram.appId

非常感谢
