### ISSUE TITLE
async wepy.login() 没有返回code？

### ISSUE THREAD

**Issue by JasonBoy** [Tencent/wepy#1783]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
`await wepy.login()`替代了原生的`wx.login(options)`, 但是原始的login回调是有code给到app， 然后获取`session_key`的, 但是wepy.login() resolve的结果为undefined，那应该如何去拿到code？

## Environment

  * Platform: 开发者工具
  * Platform version: 开发者工具1.02.1808300
  * Wechat version: [微信版本号]
  * wepy-cli version: 1.7.2
  * wepy version: 0.0.2
  * other version: 
  
## Reproduce

  [如何重现问题]
  ```javascript
  const codeRes = await wepy.login();
  console.log(codeRes) //undefined
  ```

### Observed Results

  [实际表现]
  
  无code
  
### Expected Results

  [期望表现]
  
  能够resolve成原始callback的结果

**Comment by JasonBoy** [comment]
@lettgers 貌似是新版本默认没有promise化，需要手动在`constructor`里加：
https://github.com/Tencent/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await

**Comment by lettgers** [comment]
嗯 确实是这样的 我之前也是加了这些代码的 谢谢

**Comment by Calvin-he** [comment]
This problem still exists.
