### ISSUE TITLE
无法引入第三方css库

### ISSUE THREAD

**Issue by dream2023** [Tencent/wepy#1787]
安装 animation.css 后，
在 app.wpy 中 JS 部分引入， 报错：不是JS模块
`module "npm/animation.css/main.css.js" is not defined 
Error: module "npm/animation.css/main.css.js" is not defined`

在scss中引入： 
@import 'animation.css';
报错：
![wx20180918-181528](https://user-images.githubusercontent.com/19297757/45681144-6086a180-bb6f-11e8-909e-323819b10665.png)
相对路径引入也是报错：
@import './node_modules/animation.css/main.css';
@import './npm/animation.css/main.css';

到底怎么才能引入成功（不拷贝出来）？

**Comment by chinanse-noob** [comment]
路径没写错吧？

**Comment by dream2023** [comment]
> 路径没写错吧？

没有，你试试看看能不能引入animation.css

**Comment by xusion** [comment]
把css改为less，再在style里使用import引用less，试一下
<style lang="less">
@import "../style/weui.less";
@import "../style/iconfont.less";
@import "../style/base.less";
</style>

**Comment by dream2023** [comment]
> 把css改为less，再在style里使用import引用less，试一下
> 
> <style lang="less"> @import "../style/weui.less"; @import "../style/iconfont.less"; @import "../style/base.less"; </style>

但是我是用npm install 的，还用手动改吗？还有我是用的scss不是用的less，还非得使用less吗

**Comment by xusion** [comment]
> > 把css改为less，再在style里使用import引用less，试一下
> > <style lang="less"> @import "../style/weui.less"; @import "../style/iconfont.less"; @import "../style/base.less"; </style>
> 
> 但是我是用npm install 的，还用手动改吗？还有我是用的scss不是用的less，还非得使用less吗

scss应该也是可以的。我的只是把css简单改为less。

**Comment by xiaoxinwu** [comment]
把css库下载到本地，通过scss引入。你用npm i安装的模块应该只能在js中引入，而<style></style>中不支持js的语法。
