### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by gumutianqi** [Tencent/wepy#1788]
使用的 wepy 版本：1.7.2

使用 `wepy init standard my-project` 创建了项目；
之后执行 `npm install ` 报如下错误

![image](https://user-images.githubusercontent.com/1057589/45684170-13f39400-bb78-11e8-9a70-7f13d8a555a1.png)

**Comment by Gcaufy** [comment]
尝试升级或者重装一下 node 或者 npm 试试。

**Comment by gumutianqi** [comment]
@Gcaufy 测试后发现目前不支持 node 10.x 的版本，降级到8.x 版本后可以正常 npm install

**Comment by Gcaufy** [comment]
本地测试通过
```
➜  /tmp/test
 $ node -v
v10.11.0
➜  /tmp/test
 $ npm -v
6.4.1
```
