### ISSUE TITLE
wepy使用wxparse解析富文本，图片无法自适应屏幕宽度

### ISSUE THREAD

**Issue by Elder-Wu** [Tencent/wepy#1790]
我如果直接在微信开发者工具里使用wxParse，解析富文本，图片是可以自适应宽度的。但是用wepy的话，图片就会靠左边。请问如何让图片自适应宽度，有人知道吗？
![image](https://user-images.githubusercontent.com/19809616/45735879-fd067d80-bc1b-11e8-8178-b2c0e0d7f789.png)

**Comment by fitcong** [comment]
自己动手改一下wxParse的css
