### ISSUE TITLE
npm run build 图片压缩出现warning

### ISSUE THREAD

**Issue by dream2023** [Tencent/wepy#1791]
npm run build错线如下错误：

![wx20180920-095453](https://user-images.githubusercontent.com/19297757/45791277-9173ed00-bcbb-11e8-93ad-4c32e05f820c.png)

**Comment by dream2023** [comment]
100%出现

**Comment by dream2023** [comment]
没人吗

**Comment by shenyiling** [comment]
同遇见。。。本来以为有未使用的图片，看了下都使用了

**Comment by Thinking80s** [comment]
遇到同一问题

**Comment by dream2023** [comment]
> 尝试关闭imagemin 插件看是否还是报错，
> 看起来这个错误像是[imagemin](https://www.npmjs.com/package/imagemin)
> 建议重装一下看看。

还真的好了，重装，把node_modules
