### ISSUE TITLE
getImageInfo 无效

### ISSUE THREAD

**Issue by billyshen26** [Tencent/wepy#1796]
wepy.getImageInfo({
          src: 'src', //图片的路径，可以是相对路径，临时文件路径，存储文件路径，网络图片路径,
          success: res => {},
          fail: () => {},
          complete: () => {}
        });
上面的代码  success fail complete 都不执行，将wepy换成wx则可以。

"wepy": {
      "version": "1.7.2",
      "resolved": "https://registry.npmjs.org/wepy/-/wepy-1.7.2.tgz",
      "integrity": "sha512-22Q338OY2wV1kuINAtQQmO6V9r00wNTgLPOOOASZe8tdq0lGxv9FnFWxA7SqJihQJEeWXERFd/gN7GKQQ1CU1w=="
    },
    "wepy-async-function": {
      "version": "1.4.6",
      "resolved": "https://registry.npmjs.org/wepy-async-function/-/wepy-async-function-1.4.6.tgz",
      "integrity": "sha512-UuRb7GfnkZw5aunnUVhT6ULrA3NpPaH93wo2zj3brL0WcxszLfXwtXrIBRRFe6oY1afXtzSzhAqtNWRHylke2g==",
      "requires": {
        "promise-polyfill": "^6.0.2",
        "regenerator-runtime": "^0.10.3"
      }
    },

**Comment by jingxinxin** [comment]
这样使用wepy.getImageInfo({}).then().catch()

**Comment by billyshen26** [comment]
明白了 ，多谢指点
