### ISSUE TITLE
如果不再维护是不是要在首页标明下，不然还有人入坑怎么办？

### ISSUE THREAD

**Issue by tinybright** [Tencent/wepy#1800]

**Comment by Naico** [comment]
并没有不再维护，而是作者在竭尽全力的升级2.0版本。由于是个比较大的升级，而且人手有限，所以进度比较慢。如果有问题可以提出来，大家一起研究一下。1.7.X版本是不再进行较大的升级了，我的理解是这样的。

**Comment by tinybright** [comment]
@coolhwm 
[https://github.com/Tencent/wepy/issues/1696](https://github.com/Tencent/wepy/issues/1696)
复杂点的小程序，这个性能问题没法优化

**Comment by Naico** [comment]
@xianziljl 我觉得你应该贴出代码，或者描述你遇到的坑，而不是一句话笼统地说都是坑……

**Comment by tinybright** [comment]
@xianziljl 不可能没法使用 唯一的问题就是卡而已

**Comment by Gcaufy** [comment]
维护不维护看commit一目了然。

1.7 会处理bug, 但不会进行功能迭代。我们自己的业务项目都是wepy在开发。不可能说不维护了。

至于 @tinybright 提到的数据更新问题太过笼统了，假如这个问题是你有几十M数据要去更新，结果卡钝了，那我只能告诉你，用不用WePY他都卡，我也无能为力去帮你解决这种问题。

**Comment by tinybright** [comment]
@Gcaufy  我没实际测试过性能 ，但是很多issue都在说卡。 新做的项目没多少数据 也是卡 。以前类似的原生的不卡。1.7 如果不进行功能迭代就只能开发功能简单的程序，需要文档里说明下。
