### ISSUE TITLE
WePY 2.0 内测招募

### ISSUE THREAD

**Issue by dlhandsome** [Tencent/wepy#1802]
# WePY 2.0 内测招募

亲爱的 WePY 用户：

你们好，为了配合 ```WePY``` 2.0 正式版发布需要，现招募一批内测用户。

### 招募条件

```WePY``` 1.x 用户，有用```WePY```开发的上线小程序（名额已满）

### 参与方法
添加下方微信，备注格式：
> WePY 2.0 内测 - xxx（上线小程序名称）- xxx（github用户名）

### 参与须知
- 内测用户应积极反馈内测版本遇到的 bug 至项目维护者或内测交流群
- 内测用户应积极配合项目维护者改善 2.0 内测版本，并能够参与进来（完善文档、修复```bug```、新增```feature```等）
- 参与内测，并使用 ```WePY``` 2.0 内测版本上线的小程序项目，有机会在```WePY``` 2.0正式发布时作为案例展示

### 不建议参与的情形
- 我们有个小程序项目急需上线，我希望使用内测版本快速上线这个项目
- 接受不了 bug，不希望在内测版本上遇到 bug
- 我只是来打个酱油，了解了解而已，嘿嘿
- 求你们别更新了，我学不动了

**Comment by leeseean** [comment]
招小程序开发吗？

**Comment by Slngle** [comment]
已申请

**Comment by vudiy** [comment]
已申请

**Comment by guoooofu** [comment]
WePY 2.0 内测 - 奇点精选、医者神探- guoooofu

**Comment by chen-dou** [comment]
期待

**Comment by jerexyz** [comment]
WePY 2.0 内测 - 小美拼购-chilpig

**Comment by WinjayYu** [comment]
WePY 2.0 内测 - 百姓网本地服务-winjayyu

**Comment by zjcboy** [comment]
WePY 2.0 内测 - 智慧新民居 - zjcboy

**Comment by dlhandsome** [comment]
# WePY 2.0 内测步骤

### 克隆 Tencent/wepy 仓库

```bash
# $ pwd
# /Users/sail/Desktop/opensource/

git clone https://github.com/Tencent/wepy.git
```
### 生成本地cli命令

```bash
# $ pwd
# /Users/sail/Desktop/opensource/
cd wepy
# 生成本地 wepy-dev 命令
npm install
npm run bootstrap
```

### 生成基于 2.0 语法的模板

``` bash
# $ pwd
# /Users/sail/Desktop/opensource/
wepy-dev init standard standard-2.0
```

### 修改 standard-2.0 包描述文件

- 修改 ```dependencies['@wepy/core']``` 字段值指向本地 ```Tencent/wepy``` 仓库的 ```wepy/packages/core```
```json
"@wepy/core": "/Users/sail/Desktop/opensource/wepy/packages/core"
```

- 修改 ```dependencies['@wepy/babel-plugin-import-regenerator']```字段值，指向本地 ```Tencent/wepy``` 仓库的 
```wepy/packages/babel-plugin-import-regenerator```
```json
"@wepy/babel-plugin-import-regenerator": "/Users/sail/Desktop/opensource/wepy/packages/babel-plugin-import-regenerator"
```

- 修改 ```script.dev```字段值，指向本地 ```cli``` 命令：
```json
"dev": "wepy-dev build --watch"
```
或
```json
"dev" :"node /Users/sail/Desktop/opensource/wepy/packages/cli/bin/wepy.js build --watch"
```

![image](https://user-images.githubusercontent.com/16918885/46122865-ad443980-c24d-11e8-93fa-7ac17d2c8f53.png)


### 运行项目

```bash
# $ pwd
# /Users/sail/Desktop/opensource/
cd standard-2.0
npm i && npm run dev
```

**Comment by crossjs** [comment]
内测名额满了？希望能够参加，想把 1.x 的用 2.x 改版。

**Comment by amoydavid** [comment]
2.0 的语法有改变吗？

**Comment by amoydavid** [comment]
@dlhandsome 是否有一个略完整的语法说明，看了standard2.0里的应该还是有一些改动的。比如用了 vue 生命周期的 created，但我不是太清楚对应的是原生里的 onLoad/onShow/onReady 或是我可以不用created 而直接用原生的生命周期事件吗？

**Comment by CryQ** [comment]
WePY 2.0 内测 - 小区拼单-CryQ

**Comment by fwl66** [comment]
有想做区块链底层技术内测，成为新世界探索者的人吗？可以加我微信：w13572503419

**Comment by Nick742037091** [comment]
WePY 2.0 内测 - 学乐乐+ - Nick742037091

**Comment by kdong007** [comment]
WePY 2.0 内测 - 拼室友 - kdong007

**Comment by NidMo** [comment]
> 按照内测步骤，但是报错了
> node 8.11.2
> npm run bootstrap 报错
> ![image](https://user-images.githubusercontent.com/16449593/49681411-27116280-fadc-11e8-9ed2-289c07b725e6.png)
> 
> 请问是什么原因？

你可以将命令改成 cd scripts && install_dev.sh  ,至于是什么原因，我也没太过深究。反正我是这么解决的。

**Comment by mangoooooo** [comment]
> > 按照内测步骤，但是报错了
> > node 8.11.2
> > npm run bootstrap 报错
> > ![image](https://user-images.githubusercontent.com/16449593/49681411-27116280-fadc-11e8-9ed2-289c07b725e6.png)
> > 请问是什么原因？
> 
> 你可以将命令改成 cd scripts && install_dev.sh ,至于是什么原因，我也没太过深究。反正我是这么解决的。

请你是指 把
./node_modules/.bin/lerna bootstrap --loglevel silly && ./scripts/install_dev.sh
改成下面这样吗？
 ./node_modules/.bin/lerna bootstrap --loglevel silly && cd scripts && install_dev.sh

**Comment by NidMo** [comment]
> > > 按照内测步骤，但是报错了
> > > node 8.11.2
> > > npm run bootstrap 报错
> > > ![image](https://user-images.githubusercontent.com/16449593/49681411-27116280-fadc-11e8-9ed2-289c07b725e6.png)
> > > 请问是什么原因？
> > 
> > 
> > 你可以将命令改成 cd scripts && install_dev.sh ,至于是什么原因，我也没太过深究。反正我是这么解决的。
> 
> 请问 你是指把
> ./node_modules/.bin/lerna bootstrap --loglevel silly && ./scripts/install_dev.sh
> 改成下面这样吗？
> ./node_modules/.bin/lerna bootstrap --loglevel silly && cd scripts && install_dev.sh

是啊 ，对了后面一步我记得还会有个报错的。，好像是package路径不对，到时你把package复制到那个路径就好了

**Comment by foxpsd** [comment]
请问测试如何了？正式版有定发布时间吗？

**Comment by XBCS** [comment]
> 请问测试如何了？正式版有定发布时间吗？

+1

**Comment by Gcaufy** [comment]
@fox
@XBCS  内部测试 ok 文档已更新，提交 alpha 版本使用，待文档完善后发布 beta 版本。
