### ISSUE TITLE
请问这是什么回事啊？应该怎么解决啊？ xxx is not defined no-undef

### ISSUE THREAD

**Issue by jswxwxf** [Tencent/wepy#1841]
[16:15:50] [编译] 组件: src/components/zan-actionsheet.wpy

/Users/wangxifeng/Programs/VSCProjects/woof/minacts/src/components/zan-actionsheet.wpy
  121:3  error  'props' is not defined     no-undef
  124:3  error  'data' is not defined      no-undef
  127:3  error  'methods' is not defined   no-undef
  233:3  error  'computed' is not defined  no-undef

✖ 4 problems (4 errors, 0 warnings)

[16:15:50] [编译] 组件: src/components/zan-capsule.wpy

/Users/wangxifeng/Programs/VSCProjects/woof/minacts/src/components/zan-capsule.wpy
  58:3  error  'props' is not defined    no-undef
  76:3  error  'data' is not defined     no-undef
  77:3  error  'methods' is not defined  no-undef

✖ 3 problems (3 errors, 0 warnings)

[16:15:50] [编译] 组件: src/components/zan-dialog.wpy

/Users/wangxifeng/Programs/VSCProjects/woof/minacts/src/components/zan-dialog.wpy
  138:3  error  'props' is not defined    no-undef
  139:3  error  'data' is not defined     no-undef
  143:3  error  'methods' is not defined  no-undef

✖ 3 problems (3 errors, 0 warnings)

[16:15:50] [编译] 组件: src/components/zan-field.wpy

/Users/wangxifeng/Programs/VSCProjects/woof/minacts/src/components/zan-field.wpy
   91:3  error  'props' is not defined    no-undef
  108:3  error  'data' is not defined     no-undef
  109:3  error  'methods' is not defined  no-undef

✖ 3 problems (3 errors, 0 warnings)

**Comment by dtboy1995** [comment]
贴一下 `zan-actionsheet.wpy`的代码兄弟

**Comment by jswxwxf** [comment]
不好意思，现在又好了，npm uninstall standard 就好了。 ：）
