### ISSUE TITLE
wepy build --watch启动后 修改文件会报找不到文件的错

### ISSUE THREAD

**Issue by tinybright** [Tencent/wepy#1844]
[16:07:45] [变更] 文件: src\pages\user\statis.wpy___jb_tmp___
[16:07:45] [拷贝] WPY___JB_TMP___: src\pages\user\statis.wpy___jb_tmp___

会报错

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'Y:\a_project\a_php\kroc\app\src\pages\user\statis.wpy___jb_tmp___'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! turtle_user@1.0.0 buildwatch1: `wepy build --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the turtle_user@1.0.0 buildwatch1 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-10-15T08_07_45_660Z-debug.log

**Comment by Gcaufy** [comment]
重复问题，issue列表搜索一下

**Comment by tinybright** [comment]
@Gcaufy 直找到一个类似问题 还是没解决的@
Duplicate of #1579

**Comment by coffee4code** [comment]
Maybe you have are running another(or some others) process of `wepy build --watch`, just kill all `Nodejs` process via your  task manager(such as Windows Task Manager) and start a new one only.

**Comment by coffee4code** [comment]
Maybe you are running another(or some others) process of `wepy build --watch`, just kill all `Nodejs` process via your task manager(such as Windows Task Manager) and start a new one only.
