### ISSUE TITLE
组件化开发时，列表循环中括号([])表达式，子组件中this无法读到props的值

### ISSUE THREAD

**Issue by coocssweb** [Tencent/wepy#1846]
## Description

  [问题描述：用wepy开发小程序是，发现一个隐藏的很深的bug。做列表循环时，<repeat/> 组件中如果for中用类似\<repeat for="order[‘all’].list" /> 的表达式，会发生，子组件可以正常渲染，但是，在方法中this完全读不到props的值undifined 
用“.”符号则，完全正常。\<repeat for="order.all.list" /\>]。
 

## Environment

  * Platform: [开发者工具mac版]
  * Platform version: [v1.02.1809260]
  * Wechat version: [微信版本号]
  
## Reproduce

  [做列表循环就可以重现]

**Comment by wangyequn** [comment]
这个隐藏的不深,就酱紫的,props里面的属性再js代码中取不到

**Comment by coocssweb** [comment]
> 这个隐藏的不深,就酱紫的,props里面的属性再js代码中取不到

我发现用wepy.component 把设置属性twoWay、sync 。是可以读到props的。但是就发现了上面的问题，
用<repeat for="order.all.list" /> 这种表达式是可以的，<repeat for="order[‘all’].list" />用这种表达式就不行，有点奇怪

**Comment by Gcaufy** [comment]
wepy1 不支持props 中什么表达示，新项目的话建议直接用2启动
