### ISSUE TITLE
prop无法接收到对象属性值，只能接受整个对象

### ISSUE THREAD

**Issue by dream2023** [Tencent/wepy#1847]
如标题所示，prop无法传递对象的属性值，只能把整个对象传过去，加.sync了，文档中没有写，请问这是bug吗？

**Comment by cji03** [comment]
已知陈年老问题，兄dei提问前可以搜搜issue。
修复的话，应该下个版本吧。

**Comment by dream2023** [comment]
> 已知陈年老问题，兄dei提问前可以搜搜issue。
> 修复的话，应该下个版本吧。

我的锅，我仔细思考了一下，还是用原生开发吧，实在受不了了，mpvue bug满天飞，没人管，wepy也没人管吗，受不了了

**Comment by fsy0718** [comment]
可以试试wepy2.x版本，正在内测中

**Comment by dream2023** [comment]
> 可以试试wepy2.x版本，正在内测中

等新版本出来吧，只能这样用着了，wepy比mpvue好的地方就是有人一直维护，虽然wepy在动态组件和组件id的上处理是真的无语

**Comment by Gcaufy** [comment]
@dream2023 这两个问题在2中都不存在.

**Comment by dream2023** [comment]
> @dream2023 这两个问题在2中都不存在.

这么好，什么时候能出稳定版，期待！

**Comment by dlhandsome** [comment]
@dream2023 目前2.x除了功能性的问题（优化、调整），还有文档、测试用例需要去做。可以参与进来加速稳定版的推出~

**Comment by dream2023** [comment]
> @dream2023 目前2.x除了功能性的问题（优化、调整），还有文档、测试用例需要去做。可以参与进来加速稳定版的推出~

还没看过源码呢，我先看看源码去，看看有没有能力帮助完善😂
