### ISSUE TITLE
为什么当页面触碰到底部，会触发所有的计算属性，有什么必要吗？

### ISSUE THREAD

**Issue by dream2023** [Tencent/wepy#1850]
如标题所示，今天突然发现，当页面下拉到底部会触发所有的计算属性，请问是怎么回事，是有必要设计的，还是没必要的，求解。PS：enablePullDownRefresh为false的情况下也是一样

**Comment by Gcaufy** [comment]
wepy1 中计算属性存在性能优化空间，只要进入apply阶段就会重新计算一次计算属性。
因为你只知道有脏数据，但不知道 哪个计算属性需要再计算一次。
