### ISSUE TITLE
await wepy.request 服务器500后，没有走catch？

### ISSUE THREAD

**Issue by dtboy1995** [Tencent/wepy#1866]
```js
try {
  let res = await wepy.request(`xxxxxxxxxxxxxx`);
  // 如果报500的错
} catch(err) {
 // 没有走到这里
}
```

请问是专门这样设计的吗？还是

**Comment by dtboy1995** [comment]
@Meowzz95

**Comment by nanzihan** [comment]
try . 里面有异常才会 进 catch   500 是服务器错误 不会进 catch

**Comment by Meowzz95** [comment]
你可以用 red.statusCode去检查500哟

**Comment by europeancastle** [comment]
这是微信request 设计的，看
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/network.html

**Comment by europeancastle** [comment]
只要成功接收到服务器返回，无论 statusCode 是多少，都会进入 success 回调。请开发者根据业务逻辑对返回值进行判断。

**Comment by dtboy1995** [comment]
@europeancastle 谢谢兄弟
