### ISSUE TITLE
page与page之间如何交互呢？不是page和component

### ISSUE THREAD

**Issue by dtboy1995** [Tencent/wepy#1869]
只能通过$parent.$pages -> page -> method 这样去找吗

**Comment by dtboy1995** [comment]
@realeve, 谢谢回复。

**Comment by realeve** [comment]
假设pageA想调用 pageB的方法然后让pageB中的数据 dataB改变进而让视图更新，实质仍是对数据的修改，你可以用redux，或者用  app 里面的 globalData来更改（pageB直接调用 globalData或者用 computed）。
如果是 immutable 的方法，只做数据的计算，建议放到  自定义的  util.js中调用。
