### ISSUE TITLE
在模板里如何调用自定义函数？

### ISSUE THREAD

**Issue by cfanbo** [Tencent/wepy#1881]
在模板里如何调用自定义函数？

**Comment by Meowzz95** [comment]
小程序不支持这个的哦

**Comment by assmdx** [comment]
@Meowzz95  不支持 
``` 
<image  src="{{item.img ? "a/png" : "b.png"}}"></image> 
```
这样的写法吗？

**Comment by Meowzz95** [comment]
@assmdx 

这样是支持的，不支持function call

**Comment by Meowzz95** [comment]
@qilovehua
用wxs吧 可以实现format date

**Comment by agoodcoolman** [comment]
[document](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxs/)
官方文档说明，里面有个部分说到了，1.7后面的版本是wxs的
