### ISSUE TITLE
A页面使用 wepy.redirectTo({ url: 'b' }) 转到另一个页面后，为什么A页面的js仍然在执行，没有销毁？

### ISSUE THREAD

**Issue by cfanbo** [Tencent/wepy#1888]
为什么使用在A页面使用  wepy.redirectTo({ url: 'b' }) 转到B页面，而B页面的 js 脚本(倒计时脚本，每秒执行一次)还在执行？结果导致到时间后两个页面一直在发送请求？

**Comment by cfanbo** [comment]
如果再次打开a页面的话，会受上次页面的变量的影响，很严重的问题

**Comment by aokihu** [comment]
嘿嘿，没错，这就是这个框架神奇的地方，很多地方都是莫名其妙的坑

**Comment by muxiaoqi** [comment]
最好手动清除一下 记得文档有建议
