### ISSUE TITLE
repeat 不渲染 onload 加载的 data

### ISSUE THREAD

**Issue by Blindingend** [Tencent/wepy#1895]
在 onload 里把 globalData 赋值给了局部变量，而且log 出来也是正常的，但是就是不渲染东西
![image](https://user-images.githubusercontent.com/23724924/47976508-b7c7dd80-e0ed-11e8-90ef-c770cfd0028e.png)
![image](https://user-images.githubusercontent.com/23724924/47976514-bd252800-e0ed-11e8-9d94-dfe801a39006.png)
![image](https://user-images.githubusercontent.com/23724924/47976518-c44c3600-e0ed-11e8-9478-40d124b102d1.png)
![image](https://user-images.githubusercontent.com/23724924/47976545-ef368a00-e0ed-11e8-9762-baf947321e85.png)

**Comment by aokihu** [comment]
放心，你的问题很常见，因为Wepy的组建是静态的，所以不能动态传入属性值

**Comment by aokihu** [comment]
我把我以前的方法再写一下

Repeat中的组件似乎无法动态的获取数据，因此导致了computed没发使用，而onLoad的时候props还没有初始化，要实现动态改变repeat中组件的内容似乎变得非常困难。

要实现repeat中组件动态更新的办法，我临时找到一个，那就是在Page层级中对数据进行更新，而不是在component中对数据做出反应，对于数组这样的数据可以使用map，或者reduce进行二次处理，似乎，repeat中组件的数据都是延迟静态绑定的，因此你能修改的是组件上一级的数据源，不能对组件本身的数据修改

好像后面支持原生组建后能够动态绑定了

**Comment by ThinkDJW** [comment]
把dist目录删除，重新编译看看

**Comment by ThinkDJW** [comment]
> 
> 
> > 把dist目录删除，重新编译看看
> 
> 不 OK 啊，还是不行

尝试调用$apply，在数据赋值后调用。
![default](https://user-images.githubusercontent.com/16541671/48112350-0eb9e800-e291-11e8-9c0b-22e90200ffcf.png)

**Comment by Blindingend** [comment]
> > > 把dist目录删除，重新编译看看
> > 
> > 
> > 不 OK 啊，还是不行
> 
> 尝试调用$apply，在数据赋值后调用。
> ![default](https://user-images.githubusercontent.com/16541671/48112350-0eb9e800-e291-11e8-9c0b-22e90200ffcf.png)

试了this.$apply，依然不行，快哭了。。本来挺简单的事儿啊觉得

**Comment by Blindingend** [comment]
最迷的就是this.$apply()不行，@tap 里面更改一个元素 console 出来是改掉了的，但是显示一动不动，有没有大佬救救我

**Comment by Weipengzhou** [comment]
我今天遇到了这个问题，子组件渲染的时候父组件还没要完成请求，导致子组件拿不到动态传的值。
是有这个对象的，但是通过键值去取值就取不到
![f dtchd kt k6p cpqzik4](https://user-images.githubusercontent.com/13349980/48833985-8de20c80-edb7-11e8-8b12-176c49dc35f0.png)

**Comment by duxianzhang** [comment]
this.data.sentenceList = ... 改为this.sentenceList = ...

**Comment by aokihu** [comment]
放弃吧，都一年了居然还没有更新版本

**Comment by davidloveengles** [comment]
> 放弃吧，都一年了居然还没有更新版本

哎。。。

**Comment by Lhhpw0204** [comment]
Singlesentence  标签后边换成:item.sync="item"试试

**Comment by ThomasHang** [comment]
你在请求接口的方法里，给数据赋值的后，输一行this.$apply();
亲测有用
