### ISSUE TITLE
每次修改后，需要去微信开发者工具中手动点击编译

### ISSUE THREAD

**Issue by gaoqiang19514** [Tencent/wepy#1911]
有什么办法让微信开发者工具自动监听我在vscode中的代码修改，然后自动编译吗？

**Comment by Gcaufy** [comment]
设置-》编辑-》保存时自动编译小程序

**Comment by gaoqiang19514** [comment]
设置了啊，只对微信开发者工具里面的保存有效啊，我在vscode里面修改好后，还要再跑到微信开发者工具里面保存一遍，才会编译

**Comment by lyzzz0101** [comment]
你解决了吗？我也有这样的问题
