### ISSUE TITLE
wepy-compiler-less中的less版本过低

### ISSUE THREAD

**Issue by liudonghua123** [Tencent/wepy#1927]
## Description

wepy中使用的wepy-compiler-less中的less版本过低，为2.7.3，不支持 [Properties as Variables](http://lesscss.org/features/#variables-feature-properties-as-variables-new-)，这个特性是3.0.0添加的。

## Environment

  * wepy version: 1.7.3
  * wepy-cli version: 1.7.3
  
## Reproduce

在wpy的style属性中引用同级属性值，例如以下代码中，我想计算font-size的值为相邻height的值减去一个变量值

### Observed Results
  
 `npm run dev` 出错
```
TypeError: msg.replace is not a function
    at Object.writeLog (C:\Users\ldh\AppData\Roaming\npm\node_modules\wepy-cli\lib\util.js:570:23)
    at Object.error (C:\Users\ldh\AppData\Roaming\npm\node_modules\wepy-cli\lib\util.js:513:14)
    at C:\Users\ldh\AppData\Roaming\npm\node_modules\wepy-cli\lib\compile-style.js:209:28
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
[Error] {"type":"Parse","filename":"input","index":487,"line":28,"callLine":null,"column":19,"extract":["        height: 40rpx;","
       font-size: $height - @fontSizeFix;","        font-weight: bold;"],"message":"Unrecognised input"}

```
  
### Expected Results

可以正常编译
  

## Relevant Code / Logs

```
<style type="less">

 @fontSizeFix: 8rpx;

.list-container {
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    .title {
        height: 40rpx;
        font-size: $height - @fontSizeFix;
        font-weight: bold;
    }
}
</style>
```

**Comment by liudonghua123** [comment]
我查看了相关代码，只需要修改 `packages/wepy-compiler-less/package.json` 这里的less依赖版本，经过测试是可以的，也提交相应的 https://github.com/Tencent/wepy/pull/1928 pr

**Comment by liudonghua123** [comment]
对于等不及修复的，可以在package.json中添加
```
  "resolutions": {
    "wepy-compiler-less/less": "^3.8.1"
  }
```
然后使用 yarn 安装依赖，之后用npm或者yarn都可以

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/commit/758337483428ffbc5546d7331132fe86f77de1b9

**Comment by GodEngine** [comment]
同样的问题，按以上步骤试过了也不行

**Comment by GodEngine** [comment]
样式中有错误话也会报这个错，遇到这个错误可以检测下是否是样式问题，比如是否多写了一个括号之类的。

**Comment by liudonghua123** [comment]
@GodEngine 样式没有问题的，升级less即可。

**Comment by GodEngine** [comment]
> @GodEngine 样式没有问题的，升级less即可。

是的~报错提示定位不是很清楚。我这边情况是样式里多写了一个括号，也是报同样的“TypeError: msg.replace is not a function”的错误，只是具体异常描述里提到了括号的问题。修复了css样式问题以后，这个异常就好了。在这个括号写错之前是没有问题的。

**Comment by liudonghua123** [comment]
@GodEngine 我上面代码里使用了 Properties as Variables (NEW!) ( http://lesscss.org/features/#variables-feature-properties-as-variables-new- )，这个是 v3.0.0 才提供的。之前底层依赖的2.x的less，太旧了。

```
<style type="less">

 @fontSizeFix: 8rpx;

.list-container {
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    .title {
        height: 40rpx;
        font-size: $height - @fontSizeFix;
        font-weight: bold;
    }
}
</style>
```
