### ISSUE TITLE
Mac端，安装wepy后 command not found: wepy

### ISSUE THREAD

**Issue by ericzhou2008** [Tencent/wepy#1930]
1、用1.7.0后的方法安装wepy：npm install -g wepy-cli
运行结果：
npm install -g wepy-cli
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/lib/node_modules/node/bin/wepy -> /usr/local/lib/node_modules/node/lib/node_modules/wepy-cli/bin/wepy.js
+ wepy-cli@1.7.3
updated 1 package in 22.895s

2、查看wepy和wepy-cli版本
wepy -v
wepy-cli -v
结果分别返回command not found: wepy   command not found: wepy-cli

## Environment
MacOs 10.14
node v8.11.2
npm 5.6.0
babel 6.26.0 (babel-core 6.26.3)
Mac 微信版本：Version. 2.3.18 (11382)

**Comment by learner-0994** [comment]
Mac下添加 sudo
sudo npm install -g wepy-cli

**Comment by ericzhou2008** [comment]
sudo npm install -g wepy-cli也是解决不了的
我的解决方案是：
1、升级node到稳定版本和最新版本都不能正常安装wepy
2、卸载node，重装node（node -v v11.2.0、npm -v 6.4.1）后再运行npm install -g wepy-cli就可以安装成功了

**Comment by learner-0994** [comment]
好吧，之前遇到过，重新加载了遍就没遇到过这情况

**Comment by plimerence** [comment]
emmm实在不想降 node 版本   我的wp路径是/usr/local/Cellar/node/13.2.0/bin/wepy    所以直接
echo 'alias wepy=/usr/local/Cellar/node/13.2.0/bin/wepy' >> ~/.bash_profile      暂且先用吧
