### ISSUE TITLE
wepy2.0  TypeError: _core.default.component is not a function

### ISSUE THREAD

**Issue by huixisheng** [Tencent/wepy#1944]
## Description
![image](https://user-images.githubusercontent.com/1518967/48977672-c21c3c80-f0d9-11e8-94a9-b977a56aad20.png)

![image](https://user-images.githubusercontent.com/1518967/48977674-c47e9680-f0d9-11e8-8803-f05b9f0cdd60.png)

## Environment

 `wepy2.0`
  
## Reproduce

经常出现，具体的重现步骤还未找到。常见于多次连续保存

 
### Expected Results

实际应该编译生成的文件:
![image](https://user-images.githubusercontent.com/1518967/48977685-f09a1780-f0d9-11e8-9828-2aee0fdf192b.png)

**Comment by neo4dev** [comment]
把weapp目录删掉后，重新npm run dev一下就好了

**Comment by Benny-Chan** [comment]
TypeError: _core.default.page is not a function 我这个错误 用你的建议解决了

**Comment by Benny-Chan** [comment]
> 把weapp目录删掉后，重新npm run dev一下就好了

TypeError: _core.default.page is not a function 我这个错误 用你的建议解决了
