### ISSUE TITLE
安装wepy后，运行提示缺少less模块，还有运行报错

### ISSUE THREAD

**Issue by MrJiangZhiGuo** [Tencent/wepy#1950]
安装wepy后，运行提示缺少less模块，还有运行命令 wepy build --watc 生成的dist，目录，用微信开发者编辑器打开报错。
![image](https://user-images.githubusercontent.com/26242617/49030187-a0a67800-f1e1-11e8-9ed6-0dbbed837516.png)

**Comment by syuenkei** [comment]
"wepy-compiler-less": "1.3.10", 这个版本没问题

**Comment by fitcong** [comment]
npm i less -D

**Comment by MrJiangZhiGuo** [comment]
less 我已经装了额，然后wepy build --watch运行之后，在小程序中打开生成的dist目录发现就我截图那些错，请问这是什么原因啊？

**Comment by MrJiangZhiGuo** [comment]
> “wepy-compiler-less”：“1.3.10”，这个版本没问题

less我已经装了额，然后wepy build --watch运行之后，在小程序中打开生成的dist目录发现就我截图那些错，请问这是什么原因啊？

**Comment by MrJiangZhiGuo** [comment]
> npm i less -D

less我已经装了额，然后wepy build --watch运行之后，在小程序中打开生成的dist目录发现就我截图那些错，请问这是什么原因啊？

**Comment by Gcaufy** [comment]
less 的问题已fix, 建议重新init一次template再试一下，

**Comment by MrJiangZhiGuo** [comment]
> less 的问题已fix, 建议重新init一次template再试一下，

OK好多，多谢我再试下
