### ISSUE TITLE
组件的cover-view中使用slot插槽无效

### ISSUE THREAD

**Issue by zhangjya** [Tencent/wepy#1958]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  [Description of the issue]

  在wepy.component中，需要在cover-view中插入插槽slot，在页面中使用组件时，插槽内容无法插入

## Environment

  * Platform: [开发者工具]
  * Platform version: [开发者工具 1.02.1811150]
  * Wechat version: [6.7.3]
  * wepy version: [^1.7.2]
  
## Reproduce

  [如何重现问题]
  [How to reproduce the issue]

```
component

<template>
  <cover-view>
      <slot name='test'></slot>
  </cover-view>
</template>
```

```
page

<template>
  <component >
    <view slot='test'>插槽内容</view>
  </component>
</template>
```

### Observed Results
  [实际表现]
  [Observed Results]

```
page

<template>
  <cover-view>
  </cover-view>
</template>
```
  
### Expected Results

  [期望表现] 
  [Expected Results]
  
```
page

<template>
  <cover-view>
      <view>插槽内容</view>
  </cover-view>
</template>
```

**Comment by XdYangXiaoRong** [comment]
我也遇到了整个问题
