### ISSUE TITLE
缩进只能用两个空格么？

### ISSUE THREAD

**Issue by 1lin24** [Tencent/wepy#1959]
env:
* windows10
* wepy1.7.4
* sublime text3
* 微信开发者工具 1.02.1811280

sublime text 使用的缩进是 tab，wepy编译强制要求使用两个空格，如何配置支持tab或者四个空格进行缩进的？

我尝试着修改了 .editorconfig 文件为：
```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

但并没有生效。

**Comment by Gcaufy** [comment]
wepy 如何强制你的格式？
你修改一下配置就可以了的。
