### ISSUE TITLE
onShareAppMessage 在 component 中使用，title，path和回调都无效

### ISSUE THREAD

**Issue by badbye** [Tencent/wepy#1965]
## Description

自定义了底栏 tab，为了 tab 间平滑切换，把整个小程序做成了一个单页面。每个子页面都变成了一个 component。

其中一个子页面设置分享功能，在相应的component定义了`onShareAppMessage`方法，实际操作时可以会出现分享页面，但分享出来的地址跟方法里定义的`path`不一样，而且方法里定义的回调函数一直未执行。在微信开发者工具和真机上测试都是如此。

## Environment

  * Platform: [开发者工具/Andriod]
  * Wechat version: 6.7.3
  * wepy version: 1.7.3

**Comment by dtboy1995** [comment]
您`onShareAppMessage`这个方法没有打上async吧

**Comment by badbye** [comment]
> 你的`onShareAppMessage`这个方法没有打上async吧, `onShareAppMessage`这个是一个完全同步的函数，分享按钮点击后，微信会同步调用，我不知道你是不是这个问题，可千万别在里面搞事情，有异常估计也会失败，如果不是我说的这个，你就再看看代码，最好能贴一下

跟这个没关系。已经解决了，把`onShareAppMessage`方法搬到主页面(index)，每个分页面可以有各自的`share button`。主页面的`onShareAppMessage`方法，根据当前显示的子页面来设置不同的 `title` 和 `path`即可。
