### ISSUE TITLE
wepy2.0正式版预计什么时候发布，另外wepy2.0有计划兼容wepy1.x的语法么？

### ISSUE THREAD

**Issue by cl412350533** [Tencent/wepy#1973]

**Comment by cl412350533** [comment]
公司有计划把mpvue框架的小程序统一成wepy
如果现在改的话，只能改成wepy1.x，所以我想问下标题描述的两个问题。

**Comment by Gcaufy** [comment]
2.0 现在在内部使用在，因为文档还不健全所以暂时没有对外开放
不过你可以参考内测指引去使用，mpvue 迁移至 wepy 应该说还是比容易的。
它有的功能基本这里都有

**Comment by cl412350533** [comment]
那wepy2.0有计划兼容wepy1.x的语法么

**Comment by cl412350533** [comment]
因为公司内部用的还是wepy1.x的版本，相关的公共库和组件库也都是基于1.x的版本做的。

**Comment by Gcaufy** [comment]
不能做到完全兼容，毕竟实现机制完全不一样了。
后面会给到升级指南。

**Comment by zantop** [comment]
> 公司有计划把mpvue框架的小程序统一成wepy
> 如果现在改的话，只能改成wepy1.x，所以我想问下标题描述的两个问题。

很难用，问题还是比较多，还没mpvue好用
