### ISSUE TITLE
props 静态传值undefined

### ISSUE THREAD

**Issue by jy1989** [Tencent/wepy#1983]
## Description

  参考文档里props的用法
  https://tencent.github.io/wepy/document.html#/?id=props-%E4%BC%A0%E5%80%BC
  
  发现拿不到props的值

## Environment

  * Platform: [开发者工具]
  * wepy version: [1.6.0]
  

父组件 discoverTab:
![image](https://user-images.githubusercontent.com/1291756/49849966-ca34e580-fe16-11e8-963b-962226c1913e.png)

子组件 discover:
![image](https://user-images.githubusercontent.com/1291756/49850097-4cbda500-fe17-11e8-8dac-056659188de3.png)

子组件输出：
![image](https://user-images.githubusercontent.com/1291756/49850342-0caaf200-fe18-11e8-9155-f23faa68ea1a.png)

**Comment by zzyhdu** [comment]
我也碰到一样的问题了，怎么回事啊，老铁

**Comment by AdamSD1** [comment]
我去，都没人解决吗？我也一样的问题，不知几位解决了没

**Comment by jy1989** [comment]
> 我去，都没人解决吗？我也一样的问题，不知几位解决了没

那是我的component写错了 -_-

**Comment by ismumu** [comment]
我也遇到了这个问题。。

父组件：
![image](https://user-images.githubusercontent.com/8435569/56008920-7d9fdf00-5d10-11e9-9efe-c030d7cd23ec.png)

子组件：
![image](https://user-images.githubusercontent.com/8435569/56008926-82649300-5d10-11e9-9cbd-846dced9b57d.png)

子组件里的console.log(this.mytitleabc); 是undefined

**Comment by jy1989** [comment]
> 我也遇到了这个问题。。
> 
> 父组件：
> ![image](https://user-images.githubusercontent.com/8435569/56008920-7d9fdf00-5d10-11e9-9efe-c030d7cd23ec.png)
> 
> 子组件：
> ![image](https://user-images.githubusercontent.com/8435569/56008926-82649300-5d10-11e9-9cbd-846dced9b57d.png)
> 
> 子组件里的console.log(this.mytitleabc); 是undefined

你这样定义props就是动态了吧
`mytitleabc:{
type:string
}`
改成这样试试
`mytitleabc:string`

**Comment by ismumu** [comment]
> > 我也遇到了这个问题。。
> > 父组件：
> > ![image](https://user-images.githubusercontent.com/8435569/56008920-7d9fdf00-5d10-11e9-9efe-c030d7cd23ec.png)
> > 子组件：
> > ![image](https://user-images.githubusercontent.com/8435569/56008926-82649300-5d10-11e9-9cbd-846dced9b57d.png)
> > 子组件里的console.log(this.mytitleabc); 是undefined
> 
> 你这样定义props就是动态了吧
> `mytitleabc:{ type:String }`
> 改成这样试试
> `mytitleabc:String`

并没有用~~

**Comment by denghf** [comment]
> 我也遇到了这个问题。。
> 
> 父组件：
> ![image](https://user-images.githubusercontent.com/8435569/56008920-7d9fdf00-5d10-11e9-9efe-c030d7cd23ec.png)
> 
> 子组件：
> ![image](https://user-images.githubusercontent.com/8435569/56008926-82649300-5d10-11e9-9cbd-846dced9b57d.png)
> 
> 子组件里的console.log(this.mytitleabc); 是undefined

子组件js 需要改变 继承 为component 而不是page
