### ISSUE TITLE
看到这么多issue没解决，不知道这个项目还维不维护，但我还是要提个issue

### ISSUE THREAD

**Issue by MackieLee** [Tencent/wepy#1985]
wepy-cli 初始化的项目会报一个错误 ：「未发现相关 less 编译器配置，请检查wepy.config.js文件」，解决方法是运行 npm i less less-loader --save-dev。
然后运行 wepy build 报错「找不到组件：wepy-com-toast」，手动安装 wepy-com-toast 。
然后运行 wepy build 报错「ReferenceError: Unknown plugin "transform-class-properties" specified in "base" at 0」。
初始化个项目太糟心了。。

**Comment by Yexiaoxing** [comment]
`wxpy init` 之后，你需要使用 `npm` 或者 `yarn` 安装依赖。`package.json` 已经写好，直接` npm install` / `yarn` 就好。

**Comment by byq1213** [comment]
**哈哈兄弟 你太有意思了**

**Comment by yazhengwang** [comment]
我也想问问在维护不，文件路径引用错误这个有解决办法吗

**Comment by Gcaufy** [comment]
@MackieLee 初始化完成后需要先运行一下 npm install 然后再跑

**Comment by Gcaufy** [comment]
@yazhengwang 非同一个问题吧。

**Comment by yazhengwang** [comment]
@Gcaufy 不是同一个问题，我看到关于文件路径引用问题没有找到有回复解决办法.....不知道是什么情况
