### ISSUE TITLE
.wepyignore 的作用问题

### ISSUE THREAD

**Issue by FreeRide-Joe** [Tencent/wepy#2003]
https://github.com/Tencent/wepy/issues/237#issuecomment-343790329 中提到说：.wepyignore是指有些文件不希望通过wepy编译。

我这边测试的时候配置了一个 图片文件夹 `/src/static/images/*`，在build的时候，该文件夹中的图片被拷贝到dist中，并且被压缩了。

1. 想确认下，.wepyignore中的配置 的作用 是否是：**文件不编译，但是会拷贝到 dist 文件夹中**

2. .wepyignore 更新后 是否需要 执行清空缓存操作（类似.gitigonre）以使新配置生效。

3. 如果需要src中文件不拷贝到 dist 中，是否有相关配置可用。

**Comment by Gcaufy** [comment]
1. .wepyignore 不会拷贝文件至dist
2. 如果是在watch中，需要关闭再开启watch
3. .wepyignore

**Comment by FreeRide-Joe** [comment]
> 1. .wepyignore 不会拷贝文件至dist
> 2. 如果是在watch中，需要关闭再开启watch
> 3. .wepyignore

感谢回复！
`/src/static/images/*` 改成 `/static/images/*` 后生效了。
