### ISSUE TITLE
wepy.setStorage don't return a promise

### ISSUE THREAD

**Issue by Calvin-he** [Tencent/wepy#2031]
`wepy.setStorage({key: mykey, data: myData}).then(()=>myData)`
report error below:

> Uncaught (in promise) TypeError: Cannot read property 'then' of undefined

”

**Comment by Calvin-he** [comment]
在wepy.app的constructor中使用 this.use('promisify');

```
constructor() {
    super()
    this.use('requestfix')
    this.use('promisify');
}
```

**Comment by Lynn-cc** [comment]
为什么主文档里都没有这块的说明？
