### ISSUE TITLE
wepy2.0 数据双向绑定改了吗

### ISSUE THREAD

**Issue by NidMo** [Tencent/wepy#2034]
## Description
  自定义组件的按文档那样写props属性里加了twoway，但子组件数据改变了，父组件并没有改变，是2.0版本改了实现方式吗，我对比了下源码，好像2.0版本里没有了twoway这个字段了。还有2.0的demo那里有实现v-model，是只有原生的input组件实现了吗？

## Environment

  * Platform: [开发者工具]
  * wepy version: [2.0]

**Comment by Gcaufy** [comment]
2.0 里不存在 props 的 twoway, 组件数据传递是单向的。

v-model 实现了， input, text-area, checkbox, radio 之类的可用

**Comment by NidMo** [comment]
> 2.0 里不存在 props 的 twoway, 组件数据传递是单向的。
> 
> v-model 实现了， input, text-area, checkbox, radio 之类的可用

那自己写的组件是不能用v-model吗。。。要用Redux来实现变换吗？

**Comment by superlbr** [comment]
2.0 redux还没弄好

**Comment by coderjiav** [comment]
用this.$parent 吧，亲测可用
