### ISSUE TITLE
wepy2.0 wxs文件的引用问题

### ISSUE THREAD

**Issue by NidMo** [Tencent/wepy#2041]
## Description

  wepy2.0不能正确引用wxs文件

## Environment

  * Platform: [开发者工具]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [2.0.0-alpha.1]
  
## Reproduce

  用import的方式导入
![image](https://user-images.githubusercontent.com/24955673/51163638-58e4c880-18d5-11e9-8516-276a6e2217b4.png)
会报错
![image](https://user-images.githubusercontent.com/24955673/51163671-6e59f280-18d5-11e9-9dfc-49375eb7892e.png)
用原生的方式
![image](https://user-images.githubusercontent.com/24955673/51163708-8598e000-18d5-11e9-9b1f-c90089bb7bb6.png)
编译后的文件会丢失 src属性值
![image](https://user-images.githubusercontent.com/24955673/51163729-99444680-18d5-11e9-9476-151125bb14bf.png)

**Comment by jsGood** [comment]
不能用不要出这个好不
