### ISSUE TITLE
wepy2.x引入有赞vant组件报错

### ISSUE THREAD

**Issue by dhj2020** [Tencent/wepy#2069]
![image](https://user-images.githubusercontent.com/11954087/52110288-20feb480-263b-11e9-9051-d3c138407434.png)

wepy2.x引入有赞vant组件报错

**Comment by superlbr** [comment]
![图片](https://user-images.githubusercontent.com/8142164/54805293-7eb19380-4cb1-11e9-810e-1fa6b42f20fa.png)

**Comment by superlbr** [comment]
这里有两点：
1. 在vant下wxs这个文件夹没有自动引入weapp下面，应该是检测没有import之类的导入，其实是有wxs的src引入
2. wxs的src的引入，只是单一层级的导入文件内容，没有考虑到wxs文件里的引用的文件的路径变化
@Gcaufy

**Comment by TuffyLiu** [comment]
关注

**Comment by zmGitHub** [comment]
同问

**Comment by zmGitHub** [comment]
呃 我用了各种方式引入 在 2.0中就是不行 之前我用 1.7.x 可以把 iview 引入进来 但是 2.0 完全不能用 如果是正式项目还是别用 2.0了

**Comment by superlbr** [comment]
@zmGitHub 引入可以的，就是麻烦，有什么报错可以贴上来看看

**Comment by zmGitHub** [comment]
唉 还是用回 1.7.X了 2.0 ......

**Comment by Gcaufy** [comment]
@dhj2020 @zmGitHub @superlbr 

问题应该是修复了，安装新版本试试。

```
npm i @wepy/cli@2.0.0-alpha.12
```

**Comment by superlbr** [comment]
yeah
