### ISSUE TITLE
getUserInfo无效

### ISSUE THREAD

**Issue by keyiis** [Tencent/wepy#2078]
这样的语法错误提示在调试时总是出现，怎么关闭呢?另外this.$parent.getUserInfo在真机调试时无法获得用户信息，我用的是默认生成的代码，自己没有做过修改
![image](https://user-images.githubusercontent.com/7766085/53226550-589ad280-36b6-11e9-8442-d7697642d484.png)

**Comment by aalexlin** [comment]
1.这是eslint的提示，可以去看一下eslint文档，或者在wepy.config.js里面关掉eslint（不建议）
2.getUserInfo需要用button组件触发事件才能获取

**Comment by keyiis** [comment]
@aalexlin 谢谢！已解决。
