### ISSUE TITLE
WePY 2.0 support appConfig

### ISSUE THREAD

**Issue by Gcaufy** [Tencent/wepy#2094]
## Description

  WePY 1 支持 appConfig 参数，可以在编译阶段注入一些环境变量相关配置，WePY2 暂不支持。

## Relevant Link

https://github.com/Tencent/wepy/wiki/WePY%E6%A0%B9%E6%8D%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E6%9D%A5%E6%94%B9%E5%8F%98%E8%BF%90%E8%A1%8C%E6%97%B6%E7%9A%84%E5%8F%82%E6%95%B0

**Comment by Gcaufy** [comment]
@dlhandsome @gcwlucky

**Comment by superlbr** [comment]
@Gcaufy appConfig 怎么调用？

**Comment by qij1995** [comment]
@Gcaufy 所以应该怎么调用appConfig呢？

**Comment by chenyu445** [comment]
> @Gcaufy 所以应该怎么调用appConfig呢？

找了一个取巧的办法，
1. wepy.config.js内添加以下代码
`
resolve: {
    alias: {
      '@': path.join(__dirname, 'src'),
      '@config': path.join(__dirname, 'src', 'config', process.env.NODE_ENV)
    },
    aliasFields: ['wepy', 'weapp'],
    modules: ['node_modules']
  },
`
2. src内创建config文件夹，文件夹内放置stage/dev/prod三个JS 分别输出env
`
export default const env = 'dev'
`
3. 在需要使用环境变量的地方 
`
import env from '@config'
`

**Comment by mikasaYw** [comment]
> > @Gcaufy 所以应该怎么调用appConfig呢？
> 
> 找了一个取巧的办法，
> 
> 1. wepy.config.js内添加以下代码
>    `resolve: { alias: { '@': path.join(__dirname, 'src'), '@config': path.join(__dirname, 'src', 'config', process.env.NODE_ENV) }, aliasFields: ['wepy', 'weapp'], modules: ['node_modules']   },`
> 2. src内创建config文件夹，文件夹内放置stage/dev/prod三个JS 分别输出env
>    `export default const env = 'dev'`
> 3. 在需要使用环境变量的地方
>    `import env from '@config'`

👍
@wepy/plugin-define 已经可用了
