### ISSUE TITLE
mixin 中 computed 的方法一直被触发 即使我没变更任何属性

### ISSUE THREAD

**Issue by yucccc** [Tencent/wepy#2098]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: 1.7.2
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
定义一个mixin 
computed = {
    xx() { 
      console.log('xx 触发')
      return 1
    }
  }
该方法被一直触发
  
  [How to reproduce the issue]

### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs here to reproduce the problem
  // 可以使用小程序代码片段功能，方便其它人帮助你定位代码问题
  // 详情可参考这里：https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
  ```

**Comment by luotingv1** [comment]
是这样的  你页面任何一个属性改变都会触发计算属性

**Comment by yucccc** [comment]
> 是这样的 你页面任何一个属性改变都会触发计算属性

仔细看了文档 确实是这样 这也太坑了
