### ISSUE TITLE
macos 安装 wepy-cli 1.7.3 报错

### ISSUE THREAD

**Issue by Jewill** [Tencent/wepy#2110]
macos版本：10.14.3 
node版本：v11.10.0
npm版本：6.7.0

使用sudo命令安装wepy-cli，安装结果是added，但是安装过程中报错，日志如下：

Wills-MacBook-Pro:~ WillJiang$ sudo npm install -g wepy-cli
Password:
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/Users/WillJiang/.nvm/versions/node/v11.10.0/bin/wepy -> /Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/bin/wepy.js

> fsevents@1.2.7 install /Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.7 and node@11.10.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/WillJiang/.nvm/versions/node/v11.10.0/bin/node" "/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/WillJiang/.nvm/versions/node/v11.10.0/bin/node /Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:984:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/Users/WillJiang/.nvm/versions/node/v11.10.0/bin/node" "/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v11.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/Users/WillJiang/.nvm/versions/node/v11.10.0/bin/node /Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/WillJiang/.nvm/versions/node/v11.10.0/lib/node_modules/wepy-cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/wepy-cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ wepy-cli@1.7.3
updated 1 package in 25.126s

这个报错是否会影响使用？

**Comment by TuffyLiu** [comment]
用cmpn。

**Comment by yifan-blog** [comment]
yarn
