### ISSUE TITLE
没有实现getTabBar方法？

### ISSUE THREAD

**Issue by jackzhum** [Tencent/wepy#2118]
添加了一个自定义TabBar，显示没问题了，但是跳转的时候会切回原来的标签。
        
        所以需要在页面的show() 里获取TabBar实例，然后设置选中项。
 
        但是好像Wepy不支持原生中的getTabBar方法，以至于获取不到TabBar实例。

**Comment by Jialufeng** [comment]
我这边显示 都不显示。。。
`Component is not found in path "custom-tab-bar/index"`

**Comment by jackzhum** [comment]
已解决

**Comment by yizenghui** [comment]
@jackzhum  你好，请问你是如何获得 getTabBar 实例。 如果能回复，十分感谢。

**Comment by jackzhum** [comment]
> @jackzhum 你好，请问你是如何获得 getTabBar 实例。 如果能回复，十分感谢。

我在写在page里的onShow 里的：
`
onShow() {
            if (typeof this.$wxpage.getTabBar === 'function' &&
                this.$wxpage.getTabBar()) {
                this.$wxpage.getTabBar().setData({
                    selected: 3
                })
            }
        }
`

**Comment by jackzhum** [comment]
@yizenghui 
页面里必须加入配置：
config = {
            usingComponents: {}
        }

**Comment by yizenghui** [comment]
@jackzhum  十分感谢，解决了我遇到的问题。

**Comment by biliGates** [comment]
@jackzhum 请问一下这个问题你是怎么解决的 `Component is not found in path "custom-tab-bar/index"`

**Comment by jackzhum** [comment]
@biliGates 
删除掉dist目录，重新编译下试试。

**Comment by biliGates** [comment]
@jackzhum 谢谢，我已经解决这个问题了。

**Comment by jc840031139** [comment]
@biliGates  @jackzhum  您好 我想问一下 我在custom-tab-bar 创建了index.wpy文件 顺利编译之后 还是报 Component is not found in path "custom-tab-bar/index"
 有解决的办法吗

**Comment by Bai2White** [comment]
@jackzhum @biliGates 
同求问

**Comment by zhaobinglong** [comment]
`
onShow() {
if (typeof this.$wxpage.getTabBar === 'function' &&
this.$wxpage.getTabBar()) {
this.$wxpage.getTabBar().setData({
selected: 3
})
}
}
`

**Comment by blankqwq** [comment]
非常感谢

**Comment by fengyihang** [comment]
wepy2.0里
if (typeof this.$wx.getTabBar === 'function' && this.$wx.getTabBar()) {
        this.$wx.getTabBar().setData({
          selected: 2
        })
      }

第一个条件城里,  第二个条件, 获取不到实例. 遇到这样的问题的吗?

**Comment by fengyihang** [comment]
wepy2.0,  这样解决了, 修改引入的组件里的data
onShow() {
      this.$wx.$wepy.$children[1].selected = 1
    },

**Comment by lxf-soul** [comment]
我这边报了了个getCurrentPages is not a constructor，这是啥原因啊

**Comment by lxf-soul** [comment]
请问我的tabbar直接不显示图标和文字是什么问题啊

**Comment by lxf-soul** [comment]
图标还是没变色请问是啥问题
