### ISSUE TITLE
2.0版本什么时候发布啊？

### ISSUE THREAD

**Issue by renzhao1113** [Tencent/wepy#2137]
如题

**Comment by tdlrobin** [comment]
同求

**Comment by robin901118** [comment]
同问

**Comment by nxboo** [comment]
再不发，就只能byby了

**Comment by dhj2020** [comment]
不用问了，这尿性还不如用mpvue

**Comment by jiangdexiao** [comment]
估计是放弃了，真让人蛋疼，都他妈的1年了还没点消息

**Comment by nishino-tsukasa** [comment]
希望能给一个时间表

**Comment by Gcaufy** [comment]
非常抱歉，主要还是个力精力的原因。因为维护团队都是在挤个人时间去维护这个项目。公司的项目紧急时，时间完全不可预测。
2.0 alpha 版本内外部都有一些人在体验使用了，我这段时间也会尽可能的去挤时间把 2.0 alpha 的文档补充上。
十分抱歉。

**Comment by zmGitHub** [comment]
> 非常抱歉，主要还是个力精力的原因。因为维护团队都是在挤个人时间去维护这个项目。公司的项目紧急时，时间完全不可预测。
> 2.0 alpha 版本内外部都有一些人在体验使用了，我这段时间也会尽可能的去挤时间把 2.0 alpha 的文档补充上。
> 十分抱歉。

非常理解 能不能给份文档 我们先用用

**Comment by nishino-tsukasa** [comment]
> 非常抱歉，主要还是个力精力的原因。因为维护团队都是在挤个人时间去维护这个项目。公司的项目紧急时，时间完全不可预测。
> 2.0 alpha 版本内外部都有一些人在体验使用了，我这段时间也会尽可能的去挤时间把 2.0 alpha 的文档补充上。
> 十分抱歉。

公司这么不支持吗，这么多人在用，还不让全职

**Comment by Gcaufy** [comment]
https://wepyjs.github.io/wepy-docs/
