### ISSUE TITLE
已经压缩过的文件编译后会被格式化，导致文件变大

### ISSUE THREAD

**Issue by lmf** [Tencent/wepy#2139]
## Description

  一个.min.js文件，代码被压缩在一行内，在其他文件中会import它，编译到dist后，这个min.js文件会被格式化成多行，在wepy.config.js关掉uglifyjs和ignore这个文件都不行
  
  [Description of the issue]

## Environment

  * Platform: 开发者工具
  * Platform version: 1.02.19
  * wepy-cli version: 1.7.3
  * wepy version: 1.7.2
  
### Expected Results

  直接复制这个文件，不格式化

**Comment by dtboy1995** [comment]
在`wepy.config.js`中
找到这块
```js
compilers: {
		less: {
			compress: prod
		},
		sass: {
			outputStyle: 'compressed'
		},
		babel: {
			sourceMap: false,
			presets: [
				'env'
			],
			plugins: [
				'transform-class-properties',
				'transform-decorators-legacy',
				'transform-object-rest-spread',
				'transform-export-extensions',
			]
		}
	},
```
把这个`sourceMap: false`设置就好，你那里应该是true

**Comment by lmf** [comment]
正解！
