### ISSUE TITLE
如何迁移到其他框架?

### ISSUE THREAD

**Issue by yucccc** [Tencent/wepy#2146]
目前有提供迁移方案吗？

**Comment by callmesoul** [comment]
bug这么多还没修，那可能还有迁移方案给你

**Comment by yucccc** [comment]
佛了

**Comment by LiJiangPeng** [comment]
> 佛了

你碰到啥问题了，要迁移代码

**Comment by callmesoul** [comment]
@LiJiangPeng 我也在迁移啊。
1.太笨重，性能差
2.对原生小程序不兼容，后面小程序更新，估计也很难兼容上
3.现有很多无法填的坑。
4.在开发2.0. 但应该无法兼容现有版本，兼容的话，现在的bu都修好了。

**Comment by callmesoul** [comment]
5.可扩展性太差了，维护也没怎么维护了

**Comment by LiJiangPeng** [comment]
> @LiJiangPeng 我也在迁移啊。
> 1.太笨重，性能差
> 2.对原生小程序不兼容，后面小程序更新，估计也很难兼容上
> 3.现有很多无法填的坑。
> 4.在开发2.0. 但应该无法兼容现有版本，兼容的话，现在的bu都修好了。

你怎么迁移呀，重新写代码呢？

**Comment by yucccc** [comment]
@leafOfTree 楼上基本都说了 不可否认作者做出的贡献 但是实在坑得不知从何而说起
组件通信: 各种奇特的写法  值未被更新 值错乱 值未销毁 computed无量更新 mixin只做了一半 留下一句代码简单 欢迎pr
性能: 当项目规模到一定程度下, 用户小程序闪退报警的情况特别严重 当被劫持的data过大时基本爆炸
莫不知名的bug: 尝试过同一个文件导出使用箭头函数在A文件下能找到该函数 在B文件下就找不到了 得使用函数声明才行 各种奇怪的问题...
最让开发者恶心的是写了满天的this.$apply()进行值更新 怎么能总保证都是同步函数呢 稍微不注意都不知道为啥没更新

**Comment by yoyo837** [comment]
看了你们的讨论，作为一个还未参与过小程序开发的若干年开发，决定直接使用小程序基础来做。

**Comment by QinZhen001** [comment]
同样准备迁移代码，大家有好的方案吗。。。

**Comment by yucccc** [comment]
> 看了你们的讨论，作为一个还未参与过小程序开发的若干年开发，决定直接使用小程序基础来做。

2.0已经出来 全新的版本 另外一个mpvue

**Comment by VicenLaw** [comment]
> > 看了你们的讨论，作为一个还未参与过小程序开发的若干年开发，决定直接使用小程序基础来做。
> 
> 2.0已经出来 全新的版本 第二个mpvue

有试用了吗

**Comment by callmesoul** [comment]
@VicenLaw 感觉mpvue和taro一样都是改动比较大的，有自己的东西，但一般微信以后有些改动就很难兼容回来。就像wepy。用了wepy1.0很多bug都没修，就出2.0.几乎抛弃了1.0的用户，所以表示不敢再用了。mpvue个人感觉更新比较慢。taro和mpvue都在搞一套代码生成多小程序，但转化的效果并不是很好。感觉中心还是应该放在微信小程序的开发上。

**Comment by Gcaufy** [comment]
1.0 上线的太早了，很多东西都考虑得不周道，设计上出了很多问题，留一下了太多坑。修复1.0的坑无异于拆了东墙补西墙，意义并不是很大。要解决1.0遗留下来的所有问题只能推翻重新设计。这也就是2.0做的事情，也并非我不想去兼容 1.0。 2.0 到上线花了 1 年多的时间，相对于 1.0 只花了一个多星期就上线了。就是为了保证不会再出现 1 的那些问题。

**Comment by yucccc** [comment]
@VicenLaw 不试用了 如果项目不要求多平台的话都建议使用原生
