### ISSUE TITLE
关于 wepy 2.x 组件中的class属性和style属性不传递

### ISSUE THREAD

**Issue by TuffyLiu** [Tencent/wepy#2147]
## Description

 试用了wepy2.x, 组件开发，发现在渲染的时候class属性,和style属性是不传递到具体的有用结构上，而是在#shadow-root的上一层。

`<bean-button style="color: #897" class="test" > 授权登陆 </bean-button>`

渲染后的结构是

![image](https://user-images.githubusercontent.com/14903912/57057388-e6102980-6cda-11e9-99c8-4dbb654adf1a.png)

也就说说在引用组件的时候写class或者style,不能影响到真实有用的结构，而是一层未知的编译后的结构。不知道这样设计的考虑是什么？感觉用起来有些难受。

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: ^2.0.0-alpha.8
  * wepy version: 1.6.0
  * @wepy/core: ^2.0.0-alpha.7,
  
## Reproduce

  2.x 测试开发版本

### Observed Results

![image](https://user-images.githubusercontent.com/14903912/57057388-e6102980-6cda-11e9-99c8-4dbb654adf1a.png)
  
### Expected Results

在bean-button上的class属性和style属性，传递到真正有用的结构button上。
  

## Relevant Code / Logs

  ```
  // 子组件结构
<template>
    <button>
        <slot />
    </button>



//父组件结构
<template>
<div class="container">
    <bean-button style="color: #897" class="test" > 授权登陆 </bean-button>
</div>
</template>
<config>
{
   usingComponents: {
        'bean-button': '~@/components/bean/button/index'
    }
}
</config>

  ```

**Comment by TuffyLiu** [comment]
额。。原来小程序的所有引用组件都是这样的。。。。。

**Comment by Gcaufy** [comment]
刚测试了一下，发现在小程序里实现这个需要使用`externalClasses` 来实现。
参考这里：
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html
