### ISSUE TITLE
wepy.request POST变为GET请求

### ISSUE THREAD

**Issue by Opali123** [Tencent/wepy#2158]
在用 wepy.request 请求的时候，method用的POST请求方式，如果rul 用变量的话，network里面的请求方式就变成了GET,如果url是常量的话，network里面的请求方式是POST,求助啊，不知道什么原因造成的

**Comment by 330132662** [comment]
> 在用 wepy.request 请求的时候，method用的POST请求方式，如果rul 用变量的话，network里面的请求方式就变成了GET,如果url是常量的话，network里面的请求方式是POST,求助啊，不知道什么原因造成的

请问是怎么解决的？


我的问题：
npm run build 后，所有的请求全部变成了get，因此原先类似于登录这样的post类型api，都请求失败了

**Comment by Opali123** [comment]
不好意思，不经常查看邮件，今天刚看到，我的问题出在https请求写成了http
