### ISSUE TITLE
建议项目明显位置打上停止维护，谨慎使用的公告把

### ISSUE THREAD

**Issue by callmesoul** [Tencent/wepy#2159]
建议项目明显位置打上停止维护，谨慎使用的公告把。
防止其他人再掉坑了，
看到还有新人说学wepy来着...

**Comment by LiJiangPeng** [comment]
> 建议项目明显位置打上停止维护，谨慎使用的公告把。
> 防止其他人再掉坑了，
> 看到还有新人说学wepy来着...

这个已经停止维护了？现在还使用着，组件动态传值一直搞不定，还指望着提问能得到回复

**Comment by qilovehua** [comment]
项目开发好了，准备要上线了。。。 以为还能升级2.0呢
你们以后准备用什么框架开发小程序？Taro吗？

**Comment by LiJiangPeng** [comment]
> 项目开发好了，准备要上线了。。。 以为还能升级2.0呢
> 你们以后准备用什么框架开发小程序？Taro吗？

你有用到动态传值吗，我这边一直没办法正确传递

**Comment by Fitz-Wen** [comment]
是不维护了吗？

**Comment by Gcaufy** [comment]
@Fitz-Wen 在维护的。

**Comment by zmGitHub** [comment]
2.0想用 但是没法用 可不可以让我们用用
