### ISSUE TITLE
目前我有一个需求就是需要在组件外使用repeat ，repeat里的组件是否有方法在js中获取到props传过来的值？

### ISSUE THREAD

**Issue by guggit** [Tencent/wepy#2172]
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
![image](https://user-images.githubusercontent.com/34000909/58601003-78dfbc00-82b9-11e9-988d-84879577990b.png)

目前我有一个需求就是需要在组件外使用repeat ，repeat里的组件是否有方法在js中获取到props传过来的值？

**Comment by Gcaufy** [comment]
在 repeat 拿 props 会存在一些问题，这里建议 使用 wx:for 的方式。

**Comment by kcb1157801085** [comment]
我也碰到了这个问题，但我没有使用repeat,而是使用的wx:for 也是拿不到props里面的值
