### ISSUE TITLE
how to use amap in wepy?

### ISSUE THREAD

**Issue by nguyenhuutinh** [Tencent/wepy#2183]
hello,

I searched but not find document related to map in wepy.
please help

**Comment by Gcaufy** [comment]
What map is it? It's a Map component like Echart?

**Comment by Fucntion** [comment]
这样的需求只能使用wap来做，然后利用小程序的<web-view>组件来完成了,参见https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html

**Comment by nguyenhuutinh** [comment]
thanks
