### ISSUE TITLE
VM3411:1 Do not have gotoNext handler in current page！！

### ISSUE THREAD

**Issue by victorliuboom** [Tencent/wepy#2184]
<view class="mini_head_v_top_right" @tap="gotoNext">
        
</view>

<script>
  import wepy from 'wepy'
  console.log('000')

  export default class Mine extends wepy.page {
    config = {
      navigationBarTitleText: '我的'
    }
    data={
    }
    method={
      gotoNext() {
        console.log('---')
      }
    }
  }

</script>
为什么会报这个错误啊，app.wpy也添加了，app.json里面也有。网上也查不到解决办法 求助

**Comment by Fucntion** [comment]
@victorliuboom  我同样的代码尝试了，没有发现这个问题。你把你的代码打包发到function@qingclouds.cn我看下。只发src文件夹就行

**Comment by victorliuboom** [comment]
> @victorliuboom 我同样的代码尝试了，没有发现这个问题。你把你的代码打包发到[function@qingclouds.cn](mailto:function@qingclouds.cn)我看下。只发src文件夹就行

已解决 谢谢你了
