### ISSUE TITLE
wepy2.0 如何使用wepy-redux呢

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#2190]
2.0入口改了，数据绑定机制也改了
所以如何使用redux呢

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/tree/2.0.x/packages/x

**Comment by nishino-tsukasa** [comment]
@Gcaufy 我这边用的是redux + redux-saga，整个业务层的代码都依赖这一套
改成Vuex成本太高了，而且saga很多能力Vuex也做不到

**Comment by Gcaufy** [comment]
按道理来说可以根据 wepy-redux 库的方式来进行封装来实现相同的效果的。

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/tree/2.0.x/packages/redux

**Comment by KarnaughK** [comment]
@Gcaufy 您好，为什么wepy/x的文档挂了？ 404

https://wepyjs.github.io/wepy-docs/2.x/#/others/state
