### ISSUE TITLE
wepy2.0 mixins策略和vue的mixins不一致

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#2197]
看了core/weapp/init/mixins源码，以及wepy文档说参考vue官方文档，发现针对非钩子外的字段混入策略不一致。
vue官方文档：两个键名冲突时，取组件的键值对
而通过看源码和测试发现，wepy是：两个键名冲突时，取混入的键值对

**Comment by Gcaufy** [comment]
Open a new one. Close this one.

**Comment by DragonCat1** [comment]
大佬们，这个问题是不是又复现了？2.1.0版本 @Gcaufy

**Comment by wil-x** [comment]
这个问题很严重啊....

**Comment by wil-x** [comment]
method 的合并仍然有问题，如果组件的 methods 和 mixin 的 methods 存在相同方法，会优先取 mixin 的 methods

**Comment by wil-x** [comment]
data 也一样，版本号 2.1.0.....
