### ISSUE TITLE
wepy2.0 注册页面时，在非data字段定义数据，this里没有

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#2198]
如题，有些数据可能数据量很大，所以进入到数据绑定机智里，不想执行setData
发现定义：wepy.page({_x: 123})
this._x拿不到，看了源码确实是初始化的时候没有合并。想问下原因是什么

**Comment by dlhandsome** [comment]
非 `data`、`computed`、`methods`字段内定义的数据，通过 `this.$options.xxx` 获取到

**Comment by Gcaufy** [comment]
这种情况建议这样使用

```
let _x = 123;
wepy.page({
  created() { console.log(_x) }
});
```

wepy.page 会创建一个实例。
属于实例中的数据可以在 data 中定义。
不属于示例数据的建议放在外面定义，也就没有必要合并到实例当中去了，合并的话还得考虑 变量冲突等问题。

**Comment by nishino-tsukasa** [comment]
@Gcaufy 这种方式当然是可以。但很明显变量作用域是有些不一样的。
我的理解是：
最外层：页面全局作用域，同个页面的每个实例都共享。
实例里非data：实例自身变量，但是不参与数据绑定检测也不会被setData，某些极端情况下为了性能考虑或者变量不是纯JSON的。
实例里data：实例自身变量，参与数据绑定检测也会被setData。
数据量过大的时候setData是会对性能有影响，这个微信官方也特意做了说明。
我提这个issue并不是说现在不能做到，就像@dlhandsome 说的，可以this.$options.xxx。但很明显不是最好的方案。
关于变量冲突的问题应该是更多的让开发者来权衡吧，像vue里也只是说在开发环境下给出警告。
