### ISSUE TITLE
使用wepy init empty 创建的empty模板项目wepy build --watch报错

### ISSUE THREAD

**Issue by chenyudev** [Tencent/wepy#2199]
## Description
  
  使用wepy init empty myproject创建的empty模板项目wepy build --watch报错，报错信息如下：

## Environment

  * Platform: 开发者工具
  * Platform version: 1.02.1904090
  * Wechat version: 7.0.4
  * wepy-cli version: 2.0.0-alpha.10
  * wepy version: "@wepy/core": "2.0.0-alpha"
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

使用wepy init empty myproject创建新项目

### Observed Results

  执行npm run dev命令时，出现错误。无法完成wepy build操作

➜  myproject npm run dev

> myproject@0.0.1 dev /Users/chen/WeChatProjects/myproject
> wepy build --watch
> 
> [18:04:00] info app building App
> [18:04:00] ERR! Message:
> [18:04:00] ERR!   Missing wepy entry. A .wpy file should have "wepy.app", "wepy.page" or "wepy.component"
> [18:04:00] ERR! File:
> [18:04:00] ERR!   /Users/chen/WeChatProjects/myproject/src/app.wpy
> [18:04:00] ERR! compile Compile failed. Add "--log trace" to see more details
> [18:04:00] info watching...

### Expected Results

  期望新的empty工程可以正常编译运行

**Comment by yifan-blog** [comment]
我用2.0的empty模板也是依赖错误

**Comment by chenyudev** [comment]
wepy init empty和wepy init standard生成的项目wepy.config.js和package.json文件不一致，改了下可以运行了，如果可以的话，请同步维护下empty模板

**Comment by Horton8** [comment]
同样的问题

**Comment by kinm** [comment]
me too

**Comment by YvongYang** [comment]
me too..

**Comment by tank2014gz** [comment]
同样问题，怎么没解决能否帮我解答一下~~感谢感谢
https://developers.weixin.qq.com/community/develop/doc/000a044d5085106dcf5ad386d5b800?highLine=wepy%2520entry.%2520A%2520.wpy%2520file%2520should%2520have%2520%2522wepy.app%2522
