### ISSUE TITLE
wepy2.0.x 图片素材打包问题：tabBar 配置中引用图片没有正确打包 

### ISSUE THREAD

**Issue by hezzze** [Tencent/wepy#2200]
------------------------
## Description

好像只有代码 .wpy 中被引用的素材才会正确被打包进入编译后的路径，默认为 `weapp/`，wepy 1.x 没有这个问题。

#### 案例1:
比如说如果我的代码里有一段动态的素材引用：

`<image  src="../images/pic-{{n}}.png"></image>`

相关的素材 `pic-1.png`, `pic-2.png`, `pic-3.png` 都没有被打包到最终的 weapp 文件夹下
  

#### 案例2:

如下 `app.wpy` 中tabBar 配置，引用过的`icon.png` 以及  `icon-selected.png` 没有正确被复制到对应的输出文件夹（weapp/）

  ```
<config>
{
...
 tabBar: {
    color: '#7A7E83',
    selectedColor: '#32c1ba',
    borderStyle: 'black',
    backgroundColor: '#ffffff',
    list: [
      {
        pagePath: 'pages/p1',
        iconPath: 'images/icon.png',
        selectedIconPath: 'images/icon-selected.png',
        text: 'page1'
      }
    ]
  }
...
}
</config>
  ```

**Comment by laravuel** [comment]
确实有这个问题，我的tabbar引入的图标也没有被打包

**Comment by dlhandsome** [comment]
可以在 ```wepy.config.js``` 中配置 ```static``` 路径:

```javascript
module.exports = {
  wpyExt: '.wpy',
 static: ['./src/images']
}
```

**Comment by laravuel** [comment]
> 可以在 `wepy.config.js` 中配置 `static` 路径:
> 
> ```js
> module.exports = {
>   wpyExt: '.wpy',
>  static: ['./src/images']
> }
> ```
管用，老哥

**Comment by Gcaufy** [comment]
已在文档中添加说明
