### ISSUE TITLE
wepy2.0不支持sass吗？npm install提示找不到，该怎么来引入呢？

### ISSUE THREAD

**Issue by laravuel** [Tencent/wepy#2203]
![image](https://user-images.githubusercontent.com/12763586/59912261-42c0d280-9448-11e9-819f-a64a1b5a8535.png)

**Comment by hezzze** [comment]
同样问题，目前貌似只能手动引用，好像相关npm包没有publish？

**Comment by laravuel** [comment]
> 同样问题，目前貌似只能手动引用，好像相关npm包没有publish？

这个怎么来手动引用呢？

**Comment by Gcaufy** [comment]
已 release
