### ISSUE TITLE
wepy2.x 单文件里的 config 和 wxs 有办法高亮吗

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#2218]
如题：
在 webstorm 里，wepy2.x 单文件里的 config 和 wxs 有办法高亮吗

**Comment by lilywang711** [comment]
附议， @Gcaufy

**Comment by DarkToLight** [comment]
在下附议 @Gcaufy

**Comment by Gcaufy** [comment]
并没有什么很好的办法。

1. 找到 webstorm 的高亮插件代码，贡献代码让其支持 config  和 wxs 的高亮
2. 使用 src 外链文件，单独设置高亮

**Comment by lilywang711** [comment]
webstorm 下解决办法：
![image](https://user-images.githubusercontent.com/17040010/61586211-1e6c2900-aba1-11e9-9672-1ceb5559ae2c.png)
![image](https://user-images.githubusercontent.com/17040010/61586212-29bf5480-aba1-11e9-9627-7b0ecb4844af.png)
![image](https://user-images.githubusercontent.com/17040010/61586219-422f6f00-aba1-11e9-914f-9b04a5db9c78.png)

@Gcaufy @DarkToLight

**Comment by axolo** [comment]
同求vscode和微信开发者工具高亮插件

**Comment by jialuchun** [comment]
> 同求vscode和微信开发者工具高亮插件

同求vscode

**Comment by Teemwu** [comment]
vscode 可以安装 [Wepy](https://marketplace.visualstudio.com/items?itemName=mengj.wepy) 扩展试下 @axolo @jialuchun
