### ISSUE TITLE
wepy2.x 关于打包 log

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#2220]
wepy1.x 会有详细每个文件的打包 log
![image](https://user-images.githubusercontent.com/12985781/60696401-2a58b980-9f18-11e9-84c3-edf105afeb8a.png)
wepy2.x 这些 log 都没了
![image](https://user-images.githubusercontent.com/12985781/60696386-1f9e2480-9f18-11e9-9e84-b772f6e2e521.png)

wepy2.x 能像 1 那样显示 log 吗

**Comment by nishino-tsukasa** [comment]
能不能改回之前的打包方式，不要这种依赖打包
我没有跨平台的需求

**Comment by Gcaufy** [comment]
可以使用日志级别去控制显示更多的日志内容 
```
wepy build -l sill
```

**Comment by Gcaufy** [comment]
https://wepyjs.github.io/wepy-docs/2.x/#/cli/intro?id=build

**Comment by nishino-tsukasa** [comment]
@Gcaufy 颜色为什么是全红呀

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/61173877-a499d580-a5cb-11e9-9083-287df0ea9565.png)


不太清楚为什么你那边颜色全是红色的，不知道是否与你的 terminal 的配置有关。

**Comment by lilywang711** [comment]
@Gcaufy 
wepy 2.0 编译非常的慢，每次文件修改保存之后，需要隔个三四秒才能走到下面的 ` app building App`，
```
[21:20:57] info app building App
[21:21:03] info component building components
[21:21:03] info component building components
[21:21:03] info vendor building vendor
[21:21:03] info assets building assets
[21:21:03] info process finished
[21:21:03] info watching...
[21:21:08] info app building 
```
目前代码量并不多都这么慢，开发起来很痛苦，有没有什么办法优化这速度呢
