### ISSUE TITLE
wepy2使用wxParse【遇到的问题已经解决】

### ISSUE THREAD

**Issue by DarkToLight** [Tencent/wepy#2223]
wepy2使用wxParse，提示that.setData方法不存在。
![图片](https://user-images.githubusercontent.com/21941108/60751502-a9b5be00-9fe8-11e9-89e8-3178f632e85a.png)

**Comment by DarkToLight** [comment]
在wepy2中的wepy.page 这个对象中的this并不原生的page，使用this.$wx 即可指向原生的page

**Comment by DarkToLight** [comment]
wepy在编译的时候，会将template标签替换成view标签。从而导致wxParse没法使用，解决方案：打开编译后的文件，将view标签换回template标签即可。但是这样很不好，希望作者能解决这个问题。
![图片](https://user-images.githubusercontent.com/21941108/60753232-ee9a1e80-a001-11e9-90b8-68cf89ec329e.png)
![图片](https://user-images.githubusercontent.com/21941108/60753237-01145800-a002-11e9-979d-1bb3e7d0aff3.png)
![图片](https://user-images.githubusercontent.com/21941108/60753249-0c678380-a002-11e9-8513-3588c482178a.png)
![图片](https://user-images.githubusercontent.com/21941108/60753259-1e492680-a002-11e9-9f35-a410334746e8.png)
![图片](https://user-images.githubusercontent.com/21941108/60753265-37ea6e00-a002-11e9-8da3-73bcf2e06fcc.png)

**Comment by DarkToLight** [comment]
**<wx-template>就可以编译为<template>标签**
上述问题已经解决。只不过官方文档到底什么时候完善啊

**Comment by chenyi221111** [comment]
请教个问题我也是使用2.0起初是import引用的模板无法被编译，然后配置了静态文件，但接着wxParse.js文件中报错 Uncaught SyntaxError: Unexpected identifier 要怎么解决

**Comment by chenyi221111** [comment]
import showdown from './showdown.js';
import HtmlToJson from './html2json.js';
报错的是这里引用的错误，但资源文件和wxParse都在同级目录里案例让说应该是正确的吧

**Comment by chenyi221111** [comment]
import showdown from './showdown.js';
import HtmlToJson from './html2json.js';
报错的是这里引用的错误，但资源文件和wxParse.js都在同级目录里案例让说应该是正确的吧

**Comment by chenyi221111** [comment]
import showdown from './showdown.js';
import HtmlToJson from './html2json.js';
报的是这里引用错误，但脚本文件和wxParse.js是在同级目录呀应该是正确的 纳闷了

**Comment by chenyi221111** [comment]
wxml文件未被编译你是怎么解决的

**Comment by lininn** [comment]
es6转es5打开

**Comment by wangjian1119** [comment]
> **`<wx-template>就可以编译为<template>标签`**
> 上述问题已经解决。只不过官方文档到底什么时候完善啊

我弄了这个也不管事还是报错，
![image](https://user-images.githubusercontent.com/23162975/69536324-beefb100-0fb8-11ea-9142-64ffe4817ce2.png)
