### ISSUE TITLE
无法新建程序

### ISSUE THREAD

**Issue by wxlacw** [Tencent/wepy#2227]
2.0新建程序的时候出现以下警告
输入：D:\myProject\wechat>wepy init standard myproject
输出：/ downloading template   wepy-cli · Failed to download repo standard: connect ETIMEDOUT 151.101.24.133:443
然后

**Comment by Gcaufy** [comment]
命令行网络不通导致的。试试 ping, telnet, curl 等命令测试一下，确保网络正常
