### ISSUE TITLE
希望在wepy2.0中添加interceptor拦截器

### ISSUE THREAD

**Issue by coldblue123** [Tencent/wepy#2229]
## 希望在wepy2.0中添加interceptor拦截器的功能

![image](https://user-images.githubusercontent.com/52703779/60886565-ea316800-a284-11e9-8afb-b62d38f14dd2.png)

如上图,在wepy1.0中的拦截器可以实现在原生api执行前，加一个token或者是进行文件校验，或者是请求后的结果做一些统一处理,在开发过程中这种体验非常棒
希望在wepy2.0中作者大大们可以增加这个功能,,Thanks

**Comment by ruiyong-lee** [comment]
+1

**Comment by songxianling** [comment]
+1

**Comment by kbqncf** [comment]
+1

**Comment by longjiahui** [comment]
+1

**Comment by lisiyuan1993** [comment]
+1

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/tree/2.0.x/packages/use-intercept
