### ISSUE TITLE
wepy2.0.x 中 sitemap.json 不会打包进 weapp

### ISSUE THREAD

**Issue by lich-yoo** [Tencent/wepy#2231]
## Description

在 app.wpy 中的 `<config>` 标签中配置 `sitemapLocation` 可以生效到 `/weapp/app.json` 中。
但是 sitemap.json 无论放置到 `根目录` 还是 `/src` 中，build 后都不会打包进去。

之前在 1.x 版本中 应该是 /src 下文件都会跟随 copy 到编译目录下。

## Environment
  * wepy-cli version: 2.0.0-alpha.10
  * wepy version: @wepy/core: 2.0.0-alpha.8

**Comment by dlhandsome** [comment]
#2200 配置 static

**Comment by guopz** [comment]
怎么生成到根目录的

**Comment by Yinux** [comment]
@guopz ` static: ['static','src/sitemap.json'],`
