### ISSUE TITLE
子组件向父组件$emit 值，父组件无法监听

### ISSUE THREAD

**Issue by cielu** [Tencent/wepy#2235]
```
    <van-nav-bar
        title="我的位置"
        left-arrow="{{true}}"
        fixed="{{true}}"
        border="{{false}}"
        v-on:click-left="onClickBack"
    />
```

       以下是 van-nav-bar 组件, $emit 回来的事件监听不到...

```
        onClickLeft: function () {
            this.$emit('click-left')
        },
```
这是小程序生成的代码
![image](https://user-images.githubusercontent.com/13715811/60977791-a2810e00-a362-11e9-9493-bc967ce2c510.png)
如果把  bindclick-left 改成 bind:click-left 就可以监听到 emit 事件

**Comment by cielu** [comment]
@lvanboy  没有一点用。。。

**Comment by Gcaufy** [comment]
这样试试
```
<van-nav-bar @click-left.user="onClickBack" />
```

**Comment by cielu** [comment]
@Gcaufy  还是不行。。。难道其他人没有遇到吗。。。这么久了[Facepalm][Facepalm]

**Comment by kinm** [comment]
> @Gcaufy 还是不行。。。难道其他人没有遇到吗。。。这么久了[Facepalm][Facepalm]

不是在组件里加bind:或者@ ，是在编译过后的WXML代码中添加，亲测可行
![image](https://user-images.githubusercontent.com/7105727/63744077-d7283500-c8d0-11e9-8d03-02eb96f3a93b.png)

**Comment by cielu** [comment]
@kinm  编译后的有什么用嘞

**Comment by twdp** [comment]
1、bind:click-left改成bind:click.left就可以了。。。
2、或者修改原组件，把click-left改成不带-的，clickleft, 然后bind:clickleft也是可以的。。。

**Comment by twdp** [comment]
> 1、bind:click-left改成bind:click.left就可以了。。。
> 2、或者修改原组件，把click-left改成不带-的，clickleft, 然后bind:clickleft也是可以的。。。

这个-很特殊啊。。

**Comment by Trgree** [comment]
组件如果使用wepy.page() 定义，父类也会接收不到，要使用wepy.component()，我就是掉入这个坑，费了不少时间

**Comment by weimingxinas** [comment]
https://github.com/Tencent/wepy/commit/4fd87d2e83afed437aaf8280bdca0428aa24504d
