### ISSUE TITLE
wepy2.x 引入 polyfill 运行时报错

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#2236]
引入 @babel/polyfill、babel-polyfill、core-js 的任意一个，运行时都会报错
在 wepy1.x 中没有问题，是不是 vendor 生成有问题
![image](https://user-images.githubusercontent.com/12985781/60982193-3d311b00-a36a-11e9-89ac-21df2d0f3f15.png)

**Comment by Gcaufy** [comment]
更新一下 cli 的版本试试看
```
npm i @wepy/cli@next
```

**Comment by nishino-tsukasa** [comment]
@Gcaufy 这个 cli 不行
会导致打包出来的 vendor 有问题
![image](https://user-images.githubusercontent.com/12985781/61180626-fb46f400-a64b-11e9-880a-0ff3d0964ac2.png)
原因是你的这个 commit
fix: fixed erro require in npm component Gcaufy 2019-07-13 23:51
不太懂你这个属性 ctx.component 是想处理什么
是想把 npm 纯 js 打包到 vendor，npm 的 component 就不打包？

**Comment by Gcaufy** [comment]
是的。 npm 的 js 会打包到 vendor.js ，npm 的 weapp component 会打包到 $vendor/xxx 中去

**Comment by Gcaufy** [comment]
是否有demo 方便我还原一下？

**Comment by nishino-tsukasa** [comment]
@Gcaufy 
就你给的 demo，然后
先安装：npm i -S ramda
在 app 里：
import * as R from 'ramda'
运行，你就能看到报错
也可以去 vendor.js 里搜索：__wepy_require(undefined)

**Comment by Gcaufy** [comment]
@nishino-tsukasa 这个问题是否解决了呢？

**Comment by nishino-tsukasa** [comment]
@Gcaufy 你没有发版吧，现在 cli 是 alpha.14

**Comment by nishino-tsukasa** [comment]
@Gcaufy 升到了 16 还是没有解决

**Comment by nishino-tsukasa** [comment]
@Gcaufy 升到 17 解决了，关贴
