### ISSUE TITLE
WePy引入Vant组件，其中wxml嵌套require的文件没有完整拷贝到weapp目录导致Bug

### ISSUE THREAD

**Issue by JerryLeam** [Tencent/wepy#2239]
## Description
利用npm引入Vant组件之后，编译后的组件中require的文件并没有拷贝到对应的$vendor文件夹中，导致错误。
调用层次为：index.wpy -- button.js -- utils.wxs（成功require） -- bem.wxs（失败，没有拷贝到对应的位置）

## Environment

  * Platform: 开发者工具
  * wepy-cli version: 2.0.0-alpha.10
  * wepy version: 2.0.0-alpha.8

## Reproduce

创建Standard模板，npm install 后在index页面中引入vant组件：
`"van-button": "module:vant-weapp/lib/button/index"`
在该页面任意地方添加一个按钮
`<van-button type="primary">123123</van-button>`

### Observed Results

1.按钮没有变成想要的样式，控制台报错：
`TypeError: Cannot read property 'bem' of undefined
    at ./$vendor/vant-weapp/lib/button/index.wxml:utils`
2.在weapp/$vendor/vent-weapp/lib/button/index.wxml中，其引用的utils.wxs被成功导入，但是utils.wxs依赖的bem.wxs没有导入到相应的文件。
weapp/$vendor/vent-weapp/lib/button/index.wxml中的内容
```<!----------   wxs start ----------->
<wxs module="utils">
var bem = require('./bem.wxs').bem;//bem.wxs的代码没有被导入到文件中！！！！！
var memoize = require('./memoize.wxs').memoize;

function isSrc(url) {
  return url.indexOf('http') === 0 || url.indexOf('data:image') === 0 || url.indexOf('//') === 0;
}

module.exports = {
  bem: memoize(bem),
  isSrc: isSrc,
  memoize: memoize
};
</wxs>
<!----------   wxs end   ----------->


<button id="{{ id }}" class="custom-class {{ utils.bem('button', [type, size, { block, r 
```
  
### Expected Results

生成一个绿色的按钮
没有报错

**Comment by JerryLeam** [comment]
2.0.0-alpha.13中问题已经修复

**Comment by JerryLeam** [comment]
后来发现是因为使用了WebStorm内置的Terminal进行编译的缘故，这个是一个非常诡异的问题，用Vscode一切正常

**Comment by Gcaufy** [comment]
看看是不是不同的 terminal 使用的 cli 的版本不一样导致的吧。
这个问题是修复过了的。

另外，建议更新到 @wepy/cli@next 版本

**Comment by JerryLeam** [comment]
后来检查了版本，似乎是一样的，但是WebStorm的Terminal似乎是JetBrain自己魔改过，Vscode里的PowerShell是原版的，这会造成问题吗？

**Comment by Gcaufy** [comment]
@JerryLeam  `wepy -v` 查看 wepy 的版本是否一致。

有可能不同的terminal  使用了不同的环境变量，导致使用了不同的 node.

**Comment by pixel2012** [comment]
@Gcaufy @JerryLeam 我的还是不行，已经升级到wepy@2.0.0-alpha.14版本了，目前只是在测试，引入vant-button组件。在webstorm，vscode，powershell都试过了都会报错TypeError: Cannot read property 'bem' of undefined
    at ./components/vant/button/index.wxml:utils；现在不知道怎么解决，急！
index.wepy
`<template>
    <van-button type="default">默认按钮</van-button>
    <van-button type="primary">主要按钮</van-button>
    <van-button type="info">信息按钮</van-button>
    <van-button type="warning">警告按钮</van-button>
    <van-button type="danger">危险按钮</van-button>
</template>`
`<config>
{
    navigationBarTitleText: 'WePY 2.0 Feature Demo',
    usingComponents: {
      "van-button": "../components/vant/button/index"
    }
}
</config>`

**Comment by JerryLeam** [comment]
@pixel2012 你这个引用是引用的vant-weapp/lib那里的组件吗？Wepy只能用ES5的组件，Vant专门留了ES5版本的组件，你看看文档有没有引用正确的地方。

**Comment by JerryLeam** [comment]
@Gcaufy 我检查了，终端什么的都一样，WebStorm的Terminal就是用不了。估计是他们魔改了不知道什么东西，但是也不碍事，日常都单用PowerShell，只不过可能要在文档里面标注标注。

**Comment by pixel2012** [comment]
> @pixel2012 你这个引用是引用的vant-weapp/lib那里的组件吗？Wepy只能用ES5的组件，Vant专门留了ES5版本的组件，你看看文档有没有引用正确的地方。

我是复制的时node_modules\vant-weapp\dist下的文件，放到了src\components\vant下，把dist改成了vant

**Comment by JerryLeam** [comment]
应该不是这样子引用的，你看看我issue的引用



------------------ 原始邮件 ------------------
发件人: "Leehu"<notifications@github.com>; 
发送时间: 2019年7月15日(星期一) 中午12:53
收件人: "Tencent/wepy"<wepy@noreply.github.com>; 
抄送: "Jerry"<397332857@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Tencent/wepy] WePy引入Vant组件，其中wxml嵌套require的文件没有完整拷贝到weapp目录导致Bug (#2239)



 
@pixel2012 你这个引用是引用的vant-weapp/lib那里的组件吗？Wepy只能用ES5的组件，Vant专门留了ES5版本的组件，你看看文档有没有引用正确的地方。
  
我是复制的时node_modules\vant-weapp\dist下的文件，放到了src\components\vant下，把dist改成了vant

**Comment by pixel2012** [comment]
> 应该不是这样子引用的，你看看我issue的引用
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Leehu"<notifications@github.com>; 发送时间: 2019年7月15日(星期一) 中午12:53 收件人: "Tencent/wepy"<wepy@noreply.github.com>; 抄送: "Jerry"<397332857@qq.com>; "State change"<state_change@noreply.github.com>; 主题: Re: [Tencent/wepy] WePy引入Vant组件，其中wxml嵌套require的文件没有完整拷贝到weapp目录导致Bug (#2239) @pixel2012 你这个引用是引用的vant-weapp/lib那里的组件吗？Wepy只能用ES5的组件，Vant专门留了ES5版本的组件，你看看文档有没有引用正确的地方。 我是复制的时node_modules\vant-weapp\dist下的文件，放到了src\components\vant下，把dist改成了vant — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the threa

改成"van-button": "module:vant-weapp/lib/button/index"还是不行，能提供es5地址吗

**Comment by JerryLeam** [comment]
你可以去vant官方文档里面看看，里面有很清楚的介绍。




------------------ 原始邮件 ------------------
发件人: "Leehu"<notifications@github.com>; 
发送时间: 2019年7月15日(星期一) 中午1:10
收件人: "Tencent/wepy"<wepy@noreply.github.com>; 
抄送: "Jerry"<397332857@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [Tencent/wepy] WePy引入Vant组件，其中wxml嵌套require的文件没有完整拷贝到weapp目录导致Bug (#2239)



 
应该不是这样子引用的，你看看我issue的引用
 …
 ------------------ 原始邮件 ------------------ 发件人: "Leehu"notifications@github.com; 发送时间: 2019年7月15日(星期一) 中午12:53 收件人: "Tencent/wepy"wepy@noreply.github.com; 抄送: "Jerry"397332857@qq.com; "State change"state_change@noreply.github.com; 主题: Re: [Tencent/wepy] WePy引入Vant组件，其中wxml嵌套require的文件没有完整拷贝到weapp目录导致Bug (#2239) @pixel2012 你这个引用是引用的vant-weapp/lib那里的组件吗？Wepy只能用ES5的组件，Vant专门留了ES5版本的组件，你看看文档有没有引用正确的地方。 我是复制的时node_modules\vant-weapp\dist下的文件，放到了src\components\vant下，把dist改成了vant — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the threa
  
改成"van-button": "module:vant-weapp/lib/button/index"还是不行，能提供es5地址吗

**Comment by pixel2012** [comment]
> 你可以去vant官方文档里面看看，里面有很清楚的介绍。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Leehu"<notifications@github.com>; 发送时间: 2019年7月15日(星期一) 中午1:10 收件人: "Tencent/wepy"<wepy@noreply.github.com>; 抄送: "Jerry"<397332857@qq.com>; "State change"<state_change@noreply.github.com>; 主题: Re: [Tencent/wepy] WePy引入Vant组件，其中wxml嵌套require的文件没有完整拷贝到weapp目录导致Bug (#2239) 应该不是这样子引用的，你看看我issue的引用 … ------------------ 原始邮件 ------------------ 发件人: "Leehu"notifications@github.com; 发送时间: 2019年7月15日(星期一) 中午12:53 收件人: "Tencent/wepy"wepy@noreply.github.com; 抄送: "Jerry"397332857@qq.com; "State change"state_change@noreply.github.com; 主题: Re: [Tencent/wepy] WePy引入Vant组件，其中wxml嵌套require的文件没有完整拷贝到weapp目录导致Bug (#2239) @pixel2012 你这个引用是引用的vant-weapp/lib那里的组件吗？Wepy只能用ES5的组件，Vant专门留了ES5版本的组件，你看看文档有没有引用正确的地方。 我是复制的时node_modules\vant-weapp\dist下的文件，放到了src\components\vant下，把dist改成了vant — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the threa 改成"van-button": "module:vant-weapp/lib/button/index"还是不行，能提供es5地址吗 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

执行
`wepy build --no-cache --watch`
清除缓存好了，这个问题可太难找了

**Comment by DarrenHou1993** [comment]
依然存在这个问题啊
wepy-cli 版本是 2.0.0-alpha.15
@wepy/core 版本是 2.0.0-alpha.9
vant-weapp 版本是 0.5.17
哎....

**Comment by DarrenHou1993** [comment]
升级wepy-cli 到2.0.0-alpha.15。 我的eventHub引入还报错了 
![image](https://user-images.githubusercontent.com/9291785/62132968-9c060680-b310-11e9-92da-83e2c15067c3.png)  要哭了。
