### ISSUE TITLE
有没办法升级1.72到2.X版本？除了项目代码全部重写

### ISSUE THREAD

**Issue by superadmini** [Tencent/wepy#2241]
如题
大家给个升级方案吧。
现在2.X优化了狠多，1.X以后不维护了，怎么弄？

**Comment by MKC-Mankii** [comment]
不至于全部重写，但是官方居然不提供系统一点的方法吗？

**Comment by Gcaufy** [comment]
暂时没有比较好的升级方案或者是工具。

1.x 版本 和 2.x 版本身就是两个东西，低层实现原理不一样，所依赖的小程序基础库版本也不一样。
因此不建议直接从1.x 升级 2.x

建议老的项目继续使用 1.x。在进行项目重构或者一些新的项目启动时再使用2.x.
