### ISSUE TITLE
wepy2.x 修改 .less 文件后页面样式不会实时变化

### ISSUE THREAD

**Issue by lilywang711** [Tencent/wepy#2248]
**版本**： "@wepy/cli": "^2.0.0-alpha.13", "@wepy/core": "^2.0.0-alpha.8"
 **问题**：如题，page.wpy 中引入 mixins.less ，修改 mixins.less  文件，页面的样式并没有实时更新，需要重新 wepy build 才可以

**Comment by Gcaufy** [comment]
修复了，升级一下 compiler-less 应该就可以了

**Comment by lilywang711** [comment]
@Gcaufy 感谢，但是 npm 仓库里看到的 版本依旧是 2.0.1
https://www.npmjs.com/package/@wepy/compiler-less

**Comment by lilywang711** [comment]
@Gcaufy 
我像你在 @wepy/compiler-less/createPlugin.js 里加了 `compliation.involved[rst.path] = 1;`，但依旧没解决

**Comment by endfish** [comment]
.... 并没有任何解决的迹象...
