### ISSUE TITLE
子组件获取元素高度异常2.0版本

### ISSUE THREAD

**Issue by wuxx0526** [Tencent/wepy#2251]
let query = wx.createSelectorQuery().in(this)
        let _this = this
        console.log(query.select)
        query.select('#move-box').boundingClientRect(function (rect) {
          console.log(rect)
          _this.maxWidth = rect.width
          console.log(_this.maxWidth)
        }).exec(res => {
          console.log(res)
        })

ready生命周期中，在子组件获取元素高度， 控制台

An SelectorQuery call is ignored because no proper page or component is found. Please considering using `SelectorQuery.in` to specify a proper one.

如果不使用in(this), 获取的rect是null

**Comment by wuxx0526** [comment]
2.0版本

**Comment by wuxx0526** [comment]
let query = wx.createSelectorQuery().in(this.$wx)  改成this.$wx就行

**Comment by Gcaufy** [comment]
this 拿到是是 wepy 实例，  this.$wx 才是小程序的实例
