### ISSUE TITLE
wepy2.x 修改 .less 文件后页面样式不会实时变化 

### ISSUE THREAD

**Issue by lilywang711** [Tencent/wepy#2254]
版本： "@wepy/cli": "^2.0.0-alpha.13", "@wepy/core": "^2.0.0-alpha.8"
问题：如题，page.wpy 中引入 mixins.less ，修改 mixins.less 文件，页面的样式并没有实时更新，需要重新 wepy build 才可以

这个之前提过一个 issue #2248，作者给了解决方案，但是并没有效，只好重新开一个 issue

**Comment by Gcaufy** [comment]
```
npm install @wepy/compiler-less@2.0.2 --save-dev
```

尝试一下升级试试看， 因为我本地测试是 fix 了。

**Comment by lilywang711** [comment]
@Gcaufy 我升级了，但是依旧不会变化。
找到原因了，和页面中是否注入 wxs 有关系。
如何复现：在你给的 demo  index.wpy 中把 wxs 相关代码删除后，就不会变化了 =。=
也就是说，页面中没有 wxs 代码，就不会实时更新 less....

**Comment by lilywang711** [comment]
希望官方快点能解决这个问题吧

**Comment by dingjibang** [comment]
+1，同样的问题

**Comment by Gcaufy** [comment]
```
npm install @wepy/compiler-less@2.0.2 --save-dev
```
这个不能解决么？
我这里测试已经 fix 了呀

**Comment by lilywang711** [comment]
@Gcaufy 升级到 2.0.2，还是没有解决。你可以按照这里复现一下



> @Gcaufy 我升级了，但是依旧不会变化。
> 找到原因了，和页面中是否注入 wxs 有关系。
> 如何复现：在你给的 demo index.wpy 中把 wxs 相关代码删除后，就不会变化了 =。=
> 也就是说，页面中没有 wxs 代码，就不会实时更新 less....

**Comment by lilywang711** [comment]
问题在于页面中没有 wxs 就不更新了

**Comment by lilywang711** [comment]
@Gcaufy 
你在官方给的 demo 中删除掉 wxs 部分代码就可以复现了，并不是“unconfirmed”

**Comment by Gcaufy** [comment]
@lilywang711 奇怪，我还是不能复现这里的问题。

**Comment by Gcaufy** [comment]
```
npm install @wepy/cli@next --save
npm install @wepy/compiler-less@2.0.3 --save
```
