### ISSUE TITLE
2.0 数组绑定严重BUG

### ISSUE THREAD

**Issue by dingjibang** [Tencent/wepy#2256]
## Description
这个真是个痛苦的bug……希望官方能早点看看……

**我先定义两个词**
一个是【纯值】，就是一个单纯JS对象
一个是【脏值】，就是被wepy监控的、带有observer属性化后的JS对象

假设：
data中有个数组叫做【items】，然后我现在对items【重新赋值】，这个值还是一个数组，但是这个值里【包含了之前array里的脏值】

然后，我现在对这个新array里的任何元素，【修改一下他们的属性】，都会产生莫名其妙的情况
  

## Environment

"@wepy/cli": "^2.0.0-alpha.14",
"@wepy/core": "^2.0.0-alpha.8",
  
## Reproduce

 以下是最精简代码，可以直接复制粘贴运行
```js
<template>
  <div v-for="item in items" :class="{selected: item.selected}">
    <span class="text" @tap="toggle(item.id)">{{item.name}}</span>
    <span class="remove" @tap="remove(item.id)">-remove</span>
  </div>
</template>

<style>
  .text{font-size: 30px;}
  .selected{color: green;}
</style>

<script>
  import wepy from '@wepy/core'

  wepy.page({
    data: {
      items: [
        {id: 1, name: "aaa", selected: true},
        {id: 2, name: "bbb", selected: true},
        {id: 3, name: "ccc", selected: true},
        {id: 4, name: "ddd", selected: true},
        {id: 5, name: "eee", selected: true}
      ]
    },
    methods: {
      toggle(itemId){
        const item = this.items.filter(i => i.id === itemId)[0]
        item.selected = !item.selected
      },
      remove(itemId){
        const newItems = this.items.filter(i => i.id !== itemId)
        this.items = newItems
      }
    }
  });
</script>

```

![image](https://user-images.githubusercontent.com/8450073/61437081-d6fe5680-a96e-11e9-9931-d7afa0ee191d.png)

 首先点击ccc右边的“-remove”，ccc正常的删除了，从微信开发者工具中可以看到items只有4个元素了。

然后点击一下“ddd”这个字，切换selected属性

![image](https://user-images.githubusercontent.com/8450073/61437221-1c228880-a96f-11e9-9aaf-d8151997304b.png)

然后神奇的事情就出来了，items又变成5个了，而且特别混乱，多出一个迷之item，而ddd.selected并没有成功更改

到这里就都乱了，初步认为是observer的逻辑有混乱。

## 临时解决办法
目前唯一临时丑陋解决办法就是，在remove方法里，把
```js
this.items = newItems
```
替换成
```js
this.items = JSON.parse(JSON.stringify(newItems))
```

这样this.items就接受到了一个【纯值】，而不是之前混乱的【脏值】

## 题外话
wepy这个框架真·用了很久，今天真心被这个bug弄的心态爆炸……希望官方快点能解决这个问题吧

**Comment by laravuel** [comment]
是的，遇到过，用的是和你一样的解决方法。。。蛋疼啊

**Comment by Gcaufy** [comment]
```
npm install @wepy/core@next 
```
