### ISSUE TITLE
TypeError: _x.default.Store is not a constructor

### ISSUE THREAD

**Issue by 13380320462** [Tencent/wepy#2270]
这个问题反复几次了，无法定位，前天测试好好的，第二天开机去运行就会出现这样，然后把app.wpy 代码清空保存 (npm run dev 一直运行着)，再还原保存，错误没有了，反复几天都是这样，

**Comment by Gcaufy** [comment]
提交的信息很难去分析错误的原因。
需要更多的报错信息。看看错误栈 _x.default.Store 是究竟是什么。
