### ISSUE TITLE
使用vue-touch组件， 编译报错 Tag must be paired, no start tag: [ </v-touch> ]

### ISSUE THREAD

**Issue by feliciaZH** [Tencent/wepy#2271]
## 使用vue-touch组件， 编译报错 Tag must be paired, no start tag: [ </v-touch> ]

  [在一个结构中既有点击事件又有左右滑动事件，这里想到用vue-touch组件，但是如果v-touch标签里面还有其他标签，这样就会报上面的错，难道wepy组件支持组件名里面不包含其他tag标签的吗？求支持vue组件！！！]
  
  [Description of the issue]

## 微信开发者工具

  * Platform: [开发者工具]
  * Platform version: [v1.02.1907160]
  * Wechat version: [7.0.5]
  * wepy-cli version: [wepy-cli -2.0.0-beta.4]
  * wepy version: [1.7.2]
  * other version: ["vue-touch": "^2.0.0-beta.4"]
  
## 重现步骤

  [1.在项目中npm install  vue-touch]
  [2.在页面的config中加入配置："v-touch": "module:v-touch"]
  [3.在页面的template中使用组件]

### 实际表现

  [编译报错：  Tag must be paired, no start tag: [ </v-touch> ]]
 
  
### 期望表现

  [编译通过，并且能正常使用这样的第三方组件]

  

## Relevant Code / Logs

  ```
<v-touch> <image class="avatar" mode="aspectFill" src="https://avatars1.githubusercontent.com/u/14292134?s=88&v=4"/></v-touch>
  ```

**Comment by littlexiang** [comment]
这个问题应该是<image />这类自闭合标签的解析问题. 会偶发出现, 再次编译又通过了

**Comment by feliciaZH** [comment]
用官方的slide-view组件代替了，感谢！
