### ISSUE TITLE
wepy2编译插件开发有没有官方文档可以参考？

### ISSUE THREAD

**Issue by Vwings** [Tencent/wepy#2280]
## Description
wepy2编译插件开发有没有官方文档可以参考？
https://wepyjs.github.io/wepy-docs/2.x/#/cli/config?id=plugins
 
### Expected Results

期望提供官方文档，编译时期钩子说明等相关内容。

**Comment by Gcaufy** [comment]
目前来说还是只能参考其它插件，或者通过看源码的方式进行插件开发

**Comment by lxf-soul** [comment]
用wepy2开发插件完全没有头绪
