### ISSUE TITLE
使用vuex更新对象时报错，value.observer本身是undefined

### ISSUE THREAD

**Issue by twdp** [Tencent/wepy#2284]
使用wepy 2创建工程后，看到示例里面都是简单的增删，而实际场景中需要的是对一个复杂对象渲染，如下：

`{
id: 1,
created_at: {
...
}
}`
而vendor.js在680行获取属性时会报错
![image](https://user-images.githubusercontent.com/42972631/62418609-af61fa80-b69f-11e9-98dd-4e332efa6b13.png)

**Comment by twdp** [comment]
![image](https://user-images.githubusercontent.com/42972631/62418611-d28caa00-b69f-11e9-806e-a9b3a5e520b9.png)

**Comment by Gcaufy** [comment]
已 fix 的bug, 更新一下 core 的版本

```
npm i @wepy/core@next
```
