### ISSUE TITLE
wepy 2.0 页面中怎么调用组件的方法？

### ISSUE THREAD

**Issue by hpyer** [Tencent/wepy#2286]
## Description

wepy 2.0 页面中怎么调用组件的方法？

## Environment

  * Platform: mac
  * Platform version: 1.02.1907160
  * Wechat version: [微信版本号]
  * wepy-cli version: 2.0.0-alpha.10
  * wepy version: 2.0.2
  * other version: [如果是插件问题，请列出问题插件的版本号]
  

### Observed Results

this. selectComponent  和 this.$wxpage. selectComponent 都提示不是方法
  
### Expected Results

期望是 this. selectComponent('#componentId').customFunc();

**Comment by zhangshuai** [comment]
this.$wx.selectComponent('#id')

**Comment by coderjiav** [comment]
> this.$wx.selectComponent('#id')
这个ID是啥啊？   是component 配置里面那个吗？

**Comment by foolchen** [comment]
```javascript
// ...
methods: {
  func(){
    // ...
  }
}
```

```html
<template>
  <component ref="ref"></component>
</template>
```

```javascript
// ...
methods: {
  invoke() {
    this.$refs['ref'].func()
  }
}
```

**Comment by coderjiav** [comment]
> component：
> 
> ```js
> // ...
> methods: {
>   func(){
>     // ...
>   }
> }
> ```
> 
> ```
> <template>
>   <component ref="ref"></component>
> </template>
> ```
> 
> script:
> 
> ```js
> // ...
> methods: {
>   invoke() {
>     this.$refs['ref'].func()
>   }
> }
> ```

请问你用的是什么版本，还有这个用法在哪里看到的呢，我2.0 版本，没有看到这个

**Comment by foolchen** [comment]
> > component：
> > ```js
> > // ...
> > methods: {
> >   func(){
> >     // ...
> >   }
> > }
> > ```
> > 
> > 
> > ```
> > <template>
> >   <component ref="ref"></component>
> > </template>
> > ```
> > 
> > 
> > script:
> > ```js
> > // ...
> > methods: {
> >   invoke() {
> >     this.$refs['ref'].func()
> >   }
> > }
> > ```
> 
> 请问你用的是什么版本，还有这个用法在哪里看到的呢，我2.0 版本，没有看到这个

2.0.0-alpha8

**Comment by coderjiav** [comment]
> > > component：
> > > ```js
> > > // ...
> > > methods: {
> > >   func(){
> > >     // ...
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > > ```
> > > <template>
> > >   <component ref="ref"></component>
> > > </template>
> > > ```
> > > 
> > > 
> > > script:
> > > ```js
> > > // ...
> > > methods: {
> > >   invoke() {
> > >     this.$refs['ref'].func()
> > >   }
> > > }
> > > ```
> > 
> > 
> > 请问你用的是什么版本，还有这个用法在哪里看到的呢，我2.0 版本，没有看到这个
> 
> 2.0.0-alpha8。
> wepy的文档里貌似没有，这个是参考vue来的：[访问子组件实例或子元素 ](https://cn.vuejs.org/v2/guide/components-edge-cases.html#%E8%AE%BF%E9%97%AE%E5%AD%90%E7%BB%84%E4%BB%B6%E5%AE%9E%E4%BE%8B%E6%88%96%E5%AD%90%E5%85%83%E7%B4%A0)

我这2.0.0-alpha.17 没有看到这个属性了，坑

**Comment by hpyer** [comment]
> component：
> 
> ```js
> // ...
> methods: {
>   func(){
>     // ...
>   }
> }
> ```
> 
> ```
> <template>
>   <component ref="ref"></component>
> </template>
> ```
> 
> script:
> 
> ```js
> // ...
> methods: {
>   invoke() {
>     this.$refs['ref'].func()
>   }
> }
> ```

这个应该是正确的，但是2.x显然还是在开发阶段，然后官方文档还不完善，建议项目中暂时还是用1.x来开发吧～

**Comment by twinklexp** [comment]
> > this.$wx.selectComponent('#id')
> > 这个ID是啥啊？   是component 配置里面那个吗？

this.$wxpage.selectComponent('#id')
id是组件标签id属性值
