### ISSUE TITLE
wepy2.0版本引用vant报错 'bem' of undefined

### ISSUE THREAD

**Issue by cj-17** [Tencent/wepy#2292]
usingComponents: {
      "van-button": '../components/vant/button/index'
    }
引用一个button就报错：Cannot read property 'bem' of undefined

**Comment by cj-17** [comment]
usingComponents: {
      "van-button": '../components/vant/button/index'
    }
引用一个button就报错：Cannot read property 'bem' of undefined

**Comment by superlbr** [comment]
升级下版本 ```@wepy/cli": "^2.0.0-alpha.17```

**Comment by xmt2018** [comment]
引入WeUI也会报错，“'page{line-height:1.6;font-family:-apple-system-font,Helvetica Neue,sans-serif}icon{vertical-align:middle}.”。。郁闷呀

**Comment by xmt2018** [comment]
升级了最新的也不行啊

**Comment by superlbr** [comment]
弄了个vant的demo， 你看下https://github.com/superlbr/wepy-vant

**Comment by superlbr** [comment]
weui实例也加上了

**Comment by xmt2018** [comment]
感谢superlbr大神的demo，demo下载以后运行确实正常，我正在对比和我的项目区别是由于什么原因导致的，在次感谢

**Comment by superlbr** [comment]
不客气，开源需要大家的努力

**Comment by twdp** [comment]
--no-cache暂时能解决这个问题。。
wepy build --no-cache --watch

**Comment by changziyu** [comment]
最近学习，顶一个，感谢分享
