### ISSUE TITLE
此框架已死, 请勿入坑

### ISSUE THREAD

**Issue by msdog** [Tencent/wepy#2297]
一大堆bug, 谁用知道

**Comment by deepfunc** [comment]
冷静，2.0 在某些方面还是挺好的。很多人都在贡献代码，会越来越好的。

**Comment by xmt2018** [comment]
v2.0引入vant有赞组件会报“Cannot read property 'bem' of undefined”，引入WEUI也会报错，你们有遇到过吗，各位大佬

**Comment by jiangz153202** [comment]
> v2.0引入vant有赞组件会报“Cannot read property 'bem' of undefined”，引入WEUI也会报错，你们有遇到过吗，各位大佬

升级cli版本 npm i @wepy/cli@next  很多问题 升级最新的试试

**Comment by twdp** [comment]
> v2.0引入vant有赞组件会报“Cannot read property 'bem' of undefined”，引入WEUI也会报错，你们有遇到过吗，各位大佬

--no-cache可以解决这个问题。。。前段时间遇到了
wepy build --no-cache --watch

**Comment by xmt2018** [comment]
有推荐样式库吗，除了ColorUI外，才发现WeUI for 小程序和 weui in wepy原来是两个东西，weui in wepy早都没维护了，WeUI for 小程序以不能在wepy中用

**Comment by zsh3384027** [comment]
这么纠结UI框架干嘛，原生组件基本上够用了，不能满足的自己参考第三方的代码重写一下，也不是难事。好处：一方面可以减少包大小，一方面有利于后期的维护扩展。
