### ISSUE TITLE
wepycom

### ISSUE THREAD

**Issue by zhangaofei** [Tencent/wepy#2303]
请问一下这个是2.x中用wepy-com-toast组件出的错吗，我发现在2.x里面没法用这个组件，发现这个组件用道1.想的this.invoke方法，但是2.x不支持这个了，怎么解

**Comment by Gcaufy** [comment]
2.x 中是没有这个组件的，也没有 invoke 方法。
可以用原生 toast 代替，
然后 invoke 用 eventbus 去实现。

**Comment by zhangaofei** [comment]
你说的eventbus 是指eventHub吗
