### ISSUE TITLE
使用async/await简化wx.request返回的是一个空对象，还有使用wepy.request会报错，只能使用wx.request

### ISSUE THREAD

**Issue by liqiangl** [Tencent/wepy#2304]

**Comment by Gcaufy** [comment]
https://wepyjs.github.io/wepy-docs/2.x/#/extension/plugin

请使用 `use-promisfy`

**Comment by liqiangl** [comment]
> https://wepyjs.github.io/wepy-docs/2.x/#/extension/plugin
> 
> 请使用 `use-promisfy`

已解决，我对wx.request进行了一次封装，直接上手2.0感觉有点懵，而且1.X和2.X差异还是蛮大的，希望作者大大能尽快完成2.0的详细使用文档，感谢作者大大！
