### ISSUE TITLE
多个组件事件传递问题 

### ISSUE THREAD

**Issue by pasBone** [Tencent/wepy#2307]
## Description

 A 页面 引用了3次 B 组件。通过不同的组件名来区分了。
在 A 页面通过 $broadcast 通知 B组件,  B组件会重复收到3次通知，查看$event参数发现所有的数据都是一样的，有什么办法可以区分开吗？
this.$destroy() 方法报错，版本 1.7.2

![image](https://user-images.githubusercontent.com/18027183/63247660-28647300-c298-11e9-99a0-4b06ad9cf521.png)

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]

**Comment by Gcaufy** [comment]
broadcast 是全局广播，收到三次我猜测是这个组件被引用了三次。

**Comment by pasBone** [comment]
是引用了3次啊，我问题描述上面写了哦

**Comment by pasBone** [comment]
被迫放弃使用组件的形式...close了
