### ISSUE TITLE
wxs不能用来绑定事件处理，编译有问题（wepy 2.0）

### ISSUE THREAD

**Issue by T-Mach** [Tencent/wepy#2310]
## Description

问题描述：将wxs函数绑定到bindtouchmove这样的事件上时，报错

```
...
<wxs module="test" lang="babel">
function touchMove(event, instance) {
  console.log(JSON.stringify(event))
}
module.exports = {
  touchMove: touchMove
}
</wxs>
<template>
  <view bindtouchmove="{{test.touchMove}}">...</view>
</template>
...
```
Error: Cannot read property 'touchMove' of undefined;

编译结果:
//xxx.wxml
```
<!----------   wxs start ----------->
<wxs module="test">
"use strict";

function touchMove(event, instance) {
  console.log(JSON.stringify(event));
}

module.exports = {
  touchMove: touchMove
};
</wxs>
<!----------   wxs end   ----------->

<view bindtouchmove="_proxy">...</view>
```

把      `<view bindtouchmove="_proxy">...</view>`
改成`<view bindtouchmove="{{test.touchMove}}">...</view>`
就可以了

## Environment

  * Platform: 开发者工具
  * wepy-cli version: @wepy/cli: 2.0.0-alpha.10
  * wepy version: @wepy/core: 2.0.0-alpha.9

**Comment by dlhandsome** [comment]
使用wxs绑定事件时需要在事件后加上.wxs修饰符，如 `@touchmove.wxs="test.touchMove"`，稍后我在文档中加一下

**Comment by T-Mach** [comment]
多谢！
