### ISSUE TITLE
wepy2.x 给data内属性push数据会出现数据错乱

### ISSUE THREAD

**Issue by laravuel** [Tencent/wepy#2311]
之前用的`@wepy/cli  2.0.0-alpha.13`和`@wepy/core 2.0.0-alpha.8`没遇到这个问题。
现在升级到`@wepy/cli  2.0.0-alpha.17`和`@wepy/core 2.0.0-alpha.9`就有这个问题了。

**直接上图吧：**
![image](https://user-images.githubusercontent.com/12763586/63398105-1bae5f00-c3ff-11e9-81db-8e92bb8e1243.png)
![image](https://user-images.githubusercontent.com/12763586/63398137-2ff25c00-c3ff-11e9-8241-ac94683df8d2.png)

**可以看到数组第一个元素不见了。
必须借用另外的变量来push数据才行：**
![image](https://user-images.githubusercontent.com/12763586/63398274-a3946900-c3ff-11e9-804e-38b9a3b0cacb.png)
![image](https://user-images.githubusercontent.com/12763586/63398283-ab540d80-c3ff-11e9-9dc6-eabc2611f5ca.png)

**Comment by Gcaufy** [comment]
已知问题，准备周末发一个新版本解决。如果想先修复的话，可以先用 pr 的内容修复 一下。

**Comment by laravuel** [comment]
@Gcaufy OK

**Comment by Gcaufy** [comment]
修复已发布
```
npm install @wepy/core@next
```
更一下版本
