### ISSUE TITLE
请求wepy2如何获取app.js里的方法以及globalData

### ISSUE THREAD

**Issue by yemeihanxing** [Tencent/wepy#2316]
请求wepy2如何获取app.js里的方法以及globalData

**Comment by yemeihanxing** [comment]
const app = getApp();
app.$wepy.$options.globalData

**Comment by superlbr** [comment]
除了app.wpy, 其余页面可以通过```this.$app.$options.globalData```

**Comment by yemeihanxing** [comment]
> 除了app.wpy, 其余页面可以通过`this.$app.$options.globalData`

Thank you. You've been a great help already.

**Comment by Gcaufy** [comment]
this.$app 是拿到 App() 的实例。
this.$app.$options 就是 实例的入参

**Comment by Gcaufy** [comment]
建议把 globalData 用单独的 js 文件储存，不必要放在 app 中。

**Comment by Gumow** [comment]
请问如何获取上级页面的传参呢

**Comment by superlbr** [comment]
@Gumow onLoad(params)

**Comment by Gumow** [comment]
好吧，还是用onload。我还在created里找this.$wx.xx，难怪没有（>○<） @superlbr  谢谢。
