### ISSUE TITLE
build/npm run dev 出错

### ISSUE THREAD

**Issue by LuhangRui** [Tencent/wepy#2327]
> os
 
windows 10

> 复现流程

按照文档指引，init->install->run dev

```bash
ergou@DESKTOP-LUENRTC /d/develop/mini/zx
λ wepy build --watch --log trace
[15:13:32] ERR! TypeError: Cannot read property 'update' of undefined
[15:13:32] ERR!     at less.render.then.rst (D:\develop\mini\zx\node_modules\@wepy\compiler-less\index.js:30:22)
[15:13:32] ERR!  { TypeError: Cannot read property 'update' of undefined
[15:13:32] ERR!     at less.render.then.rst (D:\develop\mini\zx\node_modules\@wepy\compiler-less\index.js:30:22)
[15:13:32] ERR!   stack:
[15:13:32] ERR!    'TypeError: Cannot read property \'update\' of undefined\n    at less.render.then.rst (D:\\develop\\mini\\zx\\node_modules\\@wepy\\compiler-less\\index.js:30:22)' }
[15:13:33] ERR! compile Compile failed.
[15:13:33] info watching...
```

**Comment by bundlejs** [comment]
mac 10.14.6
node 10.16
wepy 2.0.0-alpha.17
也是同样的问题
[16:17:58] ERR! Cannot read property 'update' of undefined
[16:17:58] ERR! compile Compile failed. Add "--log trace" to see more details

**Comment by superlbr** [comment]
貌似跟compile-less有关，版本降到2.0.3

**Comment by LuhangRui** [comment]
> 貌似跟compile-less有关，版本降到2.0.3

You are right . 原来package.json 写的`^2.0.1`我改成`2.0.3`就好了

**Comment by luo2096** [comment]
我昨天就把项目里自己写的组件换了一下，微信开发者工具那边就报错了，把文件还原也不行，实在没办法就想着代码也没写多少，新建个项目把wpy文件复制过去，结果发现按照官网的步骤初始化项目，run dev 就出现这种情况了：Cannot read property 'update' of undefined
@wepy/cli@2.0.0-alpha.17更新到@wepy/cli@2.0.0-alpha.18也是不行

**Comment by LuhangRui** [comment]
> 我昨天就把项目里自己写的组件换了一下，微信开发者工具那边就报错了，把文件还原也不行，实在没办法就想着代码也没写多少，新建个项目把wpy文件复制过去，结果发现按照官网的步骤初始化项目，run dev 就出现这种情况了：Cannot read property 'update' of undefined
> @wepy/cli@2.0.0-alpha.17更新到@wepy/cli@2.0.0-alpha.18也是不行

嗯，看楼上哪个大哥说的，对compile-less版本修改就好了

**Comment by luo2096** [comment]
> 
> 
> > 我昨天就把项目里自己写的组件换了一下，微信开发者工具那边就报错了，把文件还原也不行，实在没办法就想着代码也没写多少，新建个项目把wpy文件复制过去，结果发现按照官网的步骤初始化项目，run dev 就出现这种情况了：Cannot read property 'update' of undefined
> > @wepy/cli@2.0.0-alpha.17更新到@wepy/cli@2.0.0-alpha.18也是不行
> 
> 嗯，看楼上哪个大哥说的，对compile-less版本修改就好了

请问是直接在package.json里面改版本就可以了吗，试了一下还是不行

**Comment by LuhangRui** [comment]
> > > 我昨天就把项目里自己写的组件换了一下，微信开发者工具那边就报错了，把文件还原也不行，实在没办法就想着代码也没写多少，新建个项目把wpy文件复制过去，结果发现按照官网的步骤初始化项目，run dev 就出现这种情况了：Cannot read property 'update' of undefined
> > > @wepy/cli@2.0.0-alpha.17更新到@wepy/cli@2.0.0-alpha.18也是不行
> > 
> > 
> > 嗯，看楼上哪个大哥说的，对compile-less版本修改就好了
> 
> 请问是直接在package.json里面改版本就可以了吗，试了一下还是不行

我是直接改的，`^2.0.1`我改成`2.0.3`就OK了

**Comment by jk2K** [comment]
packages 里 `@wepy/compiler-less` 从 `^2.0.1` 改成 `2.0.3`  后，得更新下依赖，如果是用 yarn 装的依赖，可以执行 `yarn install`, 如果是 npm, 得执行 `npm install`

**Comment by Gcaufy** [comment]
```
npm i @wepy/cli@next 
```

更新 一下 cli 应该解决了， 不用再对 compiler-less 进行降级

**Comment by superlbr** [comment]
@Gcaufy 貌似没有解决

**Comment by superlbr** [comment]
@Gcaufy compiler-less也release下?

**Comment by superlbr** [comment]
@Gcaufy 
引入vant的button又报错了
```
Error: Can't resolve './bem.wxs' in '/Users/dva/small/src/static/vant/button'
at /Users/dva/small/node_modules/enhanced-resolve/lib/Resolver.js:180:19
...
/Users/dva/small/src/static/vant/button/bem.wxs doesn't exist
```
而bem.wxs是wxs/utils.wxs里嵌套的`var bem = require('./bem.wxs').bem;`
wxs的嵌套依赖，相对路径取得是第一个的，不是当前嵌套的这个
