### ISSUE TITLE
wepy2.0版本中npm run dev 报ERR! Cannot read property 'update' of undefined 和ERR! compile Compile failed. Add "--log trace" to see more details的错误信息，怎么解决？

### ISSUE THREAD

**Issue by ttoling** [Tencent/wepy#2329]
提交ISSUE前请确保已认真阅读以下内容

*Please read the following information carefully before you open an issue.*

在提交issue之前必须确认以下问题：

*Please make sure you understand the following points:*

* 必须是一个bug或者功能新增。

* *It must be a bug or a feature request*

* 必须是WePY相关问题，原生小程序问题去[开发者论坛](https://developers.weixin.qq.com/)。

* *It must be a WePY issue.*

* 已经在issue中搜索过，并且没有找到相似的issue或者解决方案。

* *I searched issue already but I didn't find any relevant issues or solutions.*

* 完善下面模板中的信息

* *Please fill out the following template*

阅读完后请在提交的issue中删除以上内容，包括分割线

DELETE THE INFORMATION ABOVE(INCLUDE THE SEPARATION LINE) BEFORE YOU OPEN AN ISSUE

------------------------
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs here to reproduce the problem
  // 可以使用小程序代码片段功能，方便其它人帮助你定位代码问题
  // 详情可参考这里：https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
  ```

**Comment by kinm** [comment]
npm i wepy-compiler-less即可

**Comment by ttoling** [comment]
@kinm 试了一下依旧报同样的错误

**Comment by phpnobody** [comment]
同问该问题，一个之前创建的项目可以跑，新创建的项目跑不起来，报一样的错误，都是通过`wepy init standard myproj`命令行创建的项目，之前创建项目时wepy/cli版本alpha10，所以自己测试过降低wepy版本到2.0.0-alpha10，都是一样报这个错

**Comment by superlbr** [comment]
compile-less 锁定到2.0.3，跟https://github.com/Tencent/wepy/issues/2327 重复

**Comment by phpnobody** [comment]
> compile-less 锁定到2.0.3，跟#2327 重复

谢谢大佬，确实是这个问题

**Comment by ttoling** [comment]
@superlbr 多谢，compile-less 锁定到2.0.3，再把@wepy/cli更新到@wepy/cli@2.0.0-alpha.18，重新npm run dev 就OK了

**Comment by AngleWangwang** [comment]
compile-less 已经锁定到2.0.3，@wepy/cli也已经更新到@wepy/cli@2.0.0-alpha.18，还是不行，请问是为什么

**Comment by AngleWangwang** [comment]
上面的方法都试了，报错this.fileDep.update is not a function， compile Compile failed. Add "--log trace" to see more details，这是为什么

**Comment by superlbr** [comment]
@AngleWangwang 锁到@wepy/cli@2.0.0-alpha.16

**Comment by higboys** [comment]
上述所有方法都试了，都失败了，不知道为啥？

**Comment by superlbr** [comment]
@higboys 
问题在node_modules/@wepy/complier-less/index.js第30行
`this.fileDep. update` => `this.fileDep.addDeps`

**Comment by 731751218** [comment]
同样的问题 两天了网上也搜不到

**Comment by superlbr** [comment]
@731751218 因为有连续报错.
这个改完，会遇到style undefined，还要删node_modules/@wepy/complier-less/createPlugin.js 第41行。
如果用了vant,还要把2个PR手动打上

**Comment by Gcaufy** [comment]
更新到 2.0.6 版本

**Comment by zhaoshuanglong** [comment]
this.fileDep.update is not a function 
解决方法 
找到 node_modules/@wepy/complier-less/index.js
把 this.fileDep.update 改为 this.fileDep.addDeps 
附赠wepy官方真TM坑  一大批人都卡在这里 也许他们压根不想对外推广新框架 所以搞这么一出
浪费3天时间 TMD能入门一门新语言了....艹

**Comment by captaintzm** [comment]
Cannot read property 'parsed' of null
 Compile failed. Add "--log trace" to see more details
