### ISSUE TITLE
wepy 转换的 html5 是否可以成功疑问！

### ISSUE THREAD

**Issue by siYuanJun** [Tencent/wepy#2346]
wepy 转换的 html5你们有成功运行的吗?
生成的 index.html 是直接打开吗？ _可能这句话问的没有头脑_ 但是真的很纳闷，**官方说可以不就是ok吗** ！

我的生成之后打开直接提示 index.js 错误 

> 是个children的语法错误

**现在就想知道 wepy 框架到底能不能转换成 html5**

**Comment by Gcaufy** [comment]
1.7.3 版本中包含有转html功能，但这一功能仅仅是实验性的。
我们内部有几个项目在同时维护小程序版本和HTML版本
但是即便可以转成功，后续的维护成本还是很高。所以这一实验性的功能就没有在2.0中保留下来。

所以结论是 1.7.3 可以转，但需要很高的问题定位和代码维护的成本 。
