### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by hfjll28** [Tencent/wepy#2350]
D:\workspace\web\myproject>wepy build --watch
[13:55:13] ERR! Cannot read property 'update' of undefined
[13:55:13] ERR! compile Compile failed. Add "--log trace" to see more details
[13:55:13] info watching...
怎么破！！！

**Comment by seasky777** [comment]
遇到同样的问题 
执行 wepy build -w --log trace  发现报错是因为/node_modules/@wepy/compiler-less/index.js 里面的第30行 this.fileDep.update(file, node.compiled.dep);  比对了一下compiler-less 2.0.3 版本 把这行注释掉 可以执行npm run dev 但是不知道有没有别的问题

**Comment by liuhuanzhu** [comment]
我也是出现这个情况，3天过去了，官方没有给解决方案吗？

**Comment by singleparty** [comment]
"@wepy/compiler-less": "2.0.3",
修改为2.0.3可以，固定版本

**Comment by Gcaufy** [comment]
2.0.3 和 2.0.6 都是正常工作的版本
