### ISSUE TITLE
<TypeError: undefined is not an object(evalusting 'vm.$app.hooks')>

### ISSUE THREAD

**Issue by feliciaZH** [Tencent/wepy#2356]
## 代码结构

  ```
// comment-list组件里面用at-user组件
 // comment-list.wpy
<template>
  <at-user :filters="['emoji']" :summary="nickname"></at-user>
</template>
<config>
{
  "component": true,    //声明组件
  "usingComponents": {        //可以使用的组件
    "at-user": "~@/components/at-user"
  }

}
</config>


看node_modules\@wepy\core\dist\wepy.js
function callUserHook (vm, hookName, arg) {

    var pageHook = vm.hooks[hookName];
    var appHook = vm.$app.hooks[hookName];

    arg = isFunc(pageHook) ? pageHook.call(vm, arg) : arg;
    arg = isFunc(appHook) ? appHook.call(vm, arg) : arg;



  return arg;
}
分析，如果传入的vm是个Component，那么$app是不存在的，还请加个try{}catch(e){}!!!
  ```

**Comment by feliciaZH** [comment]
![image](https://user-images.githubusercontent.com/14292134/64087182-84d29280-cd6e-11e9-821c-5ba44d41e409.png)

**Comment by LiuHD** [comment]
这个问题怎么样了？有什么临时的解决办法么？现在遇到了同样的问题，小程序一旦触发就会失去响应，挺严重的

**Comment by Q-Qplus1s** [comment]
同问 遇到同样的问题，有时候vm 为 WepyComponent 有$app 属性 有时候没有，没有的时候调用hook直接报错，程序崩溃

> PS 扫描加群N次 没有回复是什么问题呢？

**Comment by Q-Qplus1s** [comment]
找到临时解决方案：
注释掉 node_modules 下 @wepy/core/dist/wepy.js 的钩子：
```javascript
      // if (vm._init) {
      //   dirty = callUserHook(vm, 'before-setData', dirty);
      // }
```

同时 app.wpy 不使用 before-setData

**Comment by shuaibird** [comment]
> 找到临时解决方案：
> 注释掉 node_modules 下 @wepy/core/dist/wepy.js 的钩子：
> 
> ```js
>       // if (vm._init) {
>       //   dirty = callUserHook(vm, 'before-setData', dirty);
>       // }
> ```
> 
> 同时 app.wpy 不使用 before-setData

手动去操作还是挺麻烦的，这里写了个插件 [wepy-remove-before-set-data](https://www.npmjs.com/package/wepy-remove-before-set-data)

**Comment by Gcaufy** [comment]
Duplicates: https://github.com/Tencent/wepy/issues/2486


这个问题之前定位到了，并且在这个版本 `@wepy/core@2.0.0-alpha.14`
中有处理。
