### ISSUE TITLE
为什么我的input事件多了一层$wx

### ISSUE THREAD

**Issue by jinyang1994** [Tencent/wepy#2361]
我的代码如下：

```html
<template>
  <view>
    <input @input="input" />
  </view>
</template>

<script>
  import wepy from '@wepy/core';

  wepy.component({
    methods: {
      input(e) {
        console.log(e.$wx);
        console.log(e.detail.value);
      }
    }
  });
</script>
```

多了一层`$wx`

**Comment by Gcaufy** [comment]
e.$wx 才是小程序所提供最原始的事件参数的

e 是 wepy 包装的 事件参数， 这个事件参数是要与 H5 的事件响应 event 保持一致的。。

**Comment by jinyang1994** [comment]
> e.$wx 才是小程序所提供最原始的事件参数的
> 
> e 是 wepy 包装的 事件参数， 这个事件参数是要与 H5 的事件响应 event 保持一致的。。

那么怎样使用，才可以达到`e.detail.value`的目的，目前我访问`e.detail`是`undefined`

**Comment by HuiLuan** [comment]
> > e.$wx 才是小程序所提供最原始的事件参数的
> > e 是 wepy 包装的 事件参数， 这个事件参数是要与 H5 的事件响应 event 保持一致的。。
> 
> 那么怎样使用，才可以达到`e.detail.value`的目的，目前我访问`e.detail`是`undefined`

e.$wx.detail

**Comment by jinyang1994** [comment]
谢谢
