### ISSUE TITLE
Page onLoad的时候this.$parent undefined

### ISSUE THREAD

**Issue by UICJohn** [Tencent/wepy#2364]
## Description
我在app.wpy设置了一个globalData变量userInfo, 希望能够在index.wpy page的onLoad函数里面通过this.$parent.globalData 获取这个变量, 但是 运行的时候程序报错了，提示Cannot read property 'globalData' of undefined;at "pages/index" page lifeCycleMethod onLoad function
 
## Environment

  * Platform: [开发者工具]
  * 开发工具版本:  [1.02]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [2.0.0-alpha.18]

    

  ##代码段
  ```
  ## app.wpy
  wepy.app({
     globalData: {
       userInfo: null,
     },

    onLaunch() {
    }
  });     

   ##index.wpy

   wepy.page({
    onLoad() {
      console.log(this.$parent) //undefined
    }
  });
  ```

**Comment by chenyi221111** [comment]
wepy2.0必须一层层往下找，控制器输出this的实例你就知道了 this.$app.$options.globalData

**Comment by chenyi221111** [comment]
wepy2.0必须一层层往下找，你可以控制台输出this的实例 this.$app.$options.globalData

**Comment by UICJohn** [comment]
好的，谢谢！
