### ISSUE TITLE
自定义轮播图小圆点的样式，如果轮播图代码写在组件里面样式无效，如果轮播图代码写在pages里面会有效，wepy版本2.0

### ISSUE THREAD

**Issue by RidingACodeToStray** [Tencent/wepy#2365]
[问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
轮播图位置src/components/chosen.wpy
代码：
<swiper class="swiper_box" indicator-dots="true" autoplay="true" >
            <block wx:for="{{swiper_data}}" wx:key="id">
              <swiper-item class="swiper_item" @tap="slideDetails">
                <image src="{{item.img_url}}" class="slide_img"></image>
              </swiper-item>
            </block>
</swiper>

自定义原点样式位置src/common/style/common.less
//自定义轮播图点样式
.swiper_box{
    .wx-swiper-dot{
        width:38rpx;
        display: inline-flex;
        height: 6rpx;
        margin-left: 7rpx;
        justify-content:space-between;
    }
    .wx-swiper-dot::before{
        content: '';
        flex-grow: 1;
        background: #CCCCCC;
        border-radius: 3rpx;
    }
    .wx-swiper-dot-active::before{
        background:#FF6000;
    }
}

引入组件位置
src/pages/index.wpy

如果直接把轮播图代码写在pages/index.wpy里面样式有效，如果写在组件里面，再index.wpy里面引入该组件，样式会失效

求解

**Comment by jiangz153202** [comment]
是有这个问题 放在公共样式类里面吧
