### ISSUE TITLE
官方新出的功能组件recycle-view貌似不能正常使用

### ISSUE THREAD

**Issue by syz737** [Tencent/wepy#2366]
## Description

  [问题描述：官方退出的长列表组件无法正常使用]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [1.7.2]
  * other version: [recycle-view]

![1](https://user-images.githubusercontent.com/47617201/64238085-497fc180-cf30-11e9-8049-c349d6d2dfda.png)
![2](https://user-images.githubusercontent.com/47617201/64238087-497fc180-cf30-11e9-8174-899dac67a4d3.png)

    
recycle-view组件被放在components/test目录下，<recycle-view>可以正常渲染，RecycleContext也能正常获取，
createRecycleContext.append渲染后回调中的‘====’日志也能打印，但是<recycle-item>无法渲染，
感觉是recycleList的值没有被自定义组件正常接收，这个组件官方也提醒不要使用setData方法更新，
要用RecycleContext来管理，可是现在也无法正常管理。
  
### Expected Results

  希望能获得使用recycle-view组件的一些帮助

**Comment by jimmyrogue** [comment]
请问你能编译成功吗？用npm run build方法，我失败了，卡在使用这个组件的页面上的wxml文件上

**Comment by swen624** [comment]
我能正常使用，你说的“recycleList的值没有被自定义组件正常接收”是什么表现呢？
貌似wepy1里用recycle-view有这几项要注意
1. page的data里面先放个空的recycleList
2. 创建的时候把它放在page实例里（不确定是不是一定要这么写，反正我试出来这样可以）
```
this.$wxpage.ctx = createRecycleContext({
            id: 'recycleId',
            dataKey: 'recycleList',
            page: this.$wxpage,
            itemSize: {
                width: 343,
                height: 92
            },
            placeholderClass: ['recycle-placeholder'],
        });
        setTimeout(() => {
            this.$wxpage.ctx.append(list)
        }, 0);
```
3. `createRecycleContext`调用要等于或晚于`onReady`，不然节点可能还没渲染
4. 后续调用的时候都是`this.$wxpage.ctx.xxx()`，设置数据、取数据之类的都用recycle-view这个组件的方法。

**Comment by syz737** [comment]
> 我能正常使用，你说的“recycleList的值没有被自定义组件正常接收”是什么表现呢？
> 貌似wepy1里用recycle-view有这几项要注意
> 
> 1. page的data里面先放个空的recycleList
> 2. 创建的时候把它放在page实例里（不是一定要这么写，试过保存在this里也行，全局变量忘记行不行了）
> 
> ```
> this.$wxpage.ctx = createRecycleContext({
>     id: 'recycleId',
>     dataKey: 'recycleList',
>     page: this.$wxpage,
>     itemSize: {
>         width: 343,
>         height: 92
>     },
>     placeholderClass: ['recycle-placeholder'],
> });
> setTimeout(() => {
>     this.$wxpage.ctx.append(list)
> }, 0);
> ```
> 
> 1. `createRecycleContext`调用要等于或晚于`onReady`，不然节点可能还没渲染
> 2. 后续调用的时候都是`this.$wxpage.ctx.xxx()`，设置数据、取数据之类的都用recycle-view这个组件的方法。

我使用的有问题，直接复制了官方文档上的页面结构，但是没注意它那个代码里没声明迭代对象item。。。
