### ISSUE TITLE
wepy2.0 自定义tabBar报错

### ISSUE THREAD

**Issue by T-Mach** [Tencent/wepy#2377]
## Description

 问题描述：wepy2.0可以用官方的方式自定义tabBar吗，即在根目录建立custom-tab-bar文件夹的方式。这种方式不需要在页面中引用，导致不会被wepy编译，如果我引用的话，可以编译并显示出来，但是运行的时候js会报错：
```
Cannot read property '$rel' of undefined; [Component] Lifetime Method Error @ custom-tab-bar/index#(anonymous)
Cannot read property 'hooks' of undefined; [Component] Event Handler Error @ custom-tab-bar/index#proxyHandler
```

## Environment

  * Platform: 开发者工具
  * wepy-cli version: 2.0.0-alpha.17
  * wepy version: 2.0.0-alpha.9
  
### Expected Results

  希望能得到解决方案，多谢

**Comment by pyl1995825** [comment]
请问下这个问题有解决吗？同样遇到这样的问题

**Comment by T-Mach** [comment]
已经解决，把 `node_modules/@wepy/cli` 和 `node_modules/@wepy/core` 替换下试试,
用法可以参考我写的 https://github.com/T-Mach/wepy-classic-template

**Comment by pyl1995825** [comment]
> 已经解决，把 `node_modules/@wepy/cli` 和 `node_modules/@wepy/core` 替换下试试,
> 用法可以参考我写的 https://github.com/T-Mach/wepy-classic-template

赞~ 👍👍

**Comment by pxohlqo** [comment]
> 已经解决，把 `node_modules/@wepy/cli` 和 `node_modules/@wepy/core` 替换下试试,
> 用法可以参考我写的 https://github.com/T-Mach/wepy-classic-template

老哥能说下是怎么解决的？我试了你的项目wepy也是不编译custom-tab-bar

**Comment by T-Mach** [comment]
> > 已经解决，把 `node_modules/@wepy/cli` 和 `node_modules/@wepy/core` 替换下试试,
> > 用法可以参考我写的 https://github.com/T-Mach/wepy-classic-template
> 
> 老哥能说下是怎么解决的？我试了你的项目wepy也是不编译custom-tab-bar

把 `node_modules/@wepy/cli` 和 `node_modules/@wepy/core` 替换成库里最新的就可以了

**Comment by pxohlqo** [comment]
> > > 已经解决，把 `node_modules/@wepy/cli` 和 `node_modules/@wepy/core` 替换下试试,
> > > 用法可以参考我写的 https://github.com/T-Mach/wepy-classic-template
> > 
> > 
> > 老哥能说下是怎么解决的？我试了你的项目wepy也是不编译custom-tab-bar
> 
> 把 `node_modules/@wepy/cli` 和 `node_modules/@wepy/core` 替换成库里最新的就可以了

已经不用wepy了，但还是感谢回复😃

**Comment by qilovehua** [comment]
1.7.2转成百度小程序，报类似的问题，该怎么解决？
谢谢！
