### ISSUE TITLE
我的页面每保存一次js就会追加一段代码，造成项目体积无限增大

### ISSUE THREAD

**Issue by Tony-Code** [Tencent/wepy#2383]
wepy2.X
页面中引用了组件，编译一切正常，也不卡顿。但是每保存一次代码所有引用过组件的js就会追加一段代码。需要退出命令行再重新编译才正常。如图：
![微信截图_20190911214004](https://user-images.githubusercontent.com/12890795/64702448-27141800-d4dd-11e9-91cd-21a29dd32bd1.png)
![微信截图_20190911214019](https://user-images.githubusercontent.com/12890795/64702458-2b403580-d4dd-11e9-9f71-3e7fb012ec9a.png)

有谁能帮忙指点一下吗？

**Comment by foolchen** [comment]
每次编译的时候clean一下吧，这个貌似是单文件组件的Bug。
随着你对组件的引用增加，生成的代码也会增多，最终还会报错。
之前报过这个Bug了。

**Comment by Tony-Code** [comment]
> 每次编译的时候清理一下吧，这个貌似是单文件组件的错误。
> 随着你对组件的引用增加，生成的代码也会增多，最终还会报错。
> 之前报过这个错误了。

好的

**Comment by Tony-Code** [comment]
@foolchen 好的，希望能尽快修复
