### ISSUE TITLE
在使用wepy-cli初始化项目的时候显示无法链接151.101.40.133

### ISSUE THREAD

**Issue by guanjiangtao** [Tencent/wepy#2390]
## Description

![image](https://user-images.githubusercontent.com/23498943/64902021-aae32580-d6d2-11e9-8a0f-6169bf3aa522.png)
在使用wepy-cli初始化项目的时候，显示无法链接到上图那个ip地址；试过设置了代理，也不行。
 我尝试过这篇文章https://blog.csdn.net/u010598111/article/details/85343962提供的修改方案，还是不行。
错误信息
downloading template   wepy-cli · Failed to download repo standard: connect ETIMEDOUT 151.101.40.133:443
  [Description of the issue]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  我是在移动网卡的环境下，按照如下教程进行。
![image](https://user-images.githubusercontent.com/23498943/64902068-4eccd100-d6d3-11e9-8dbe-06dc9de2fae0.png)
![image](https://user-images.githubusercontent.com/23498943/64902069-57bda280-d6d3-11e9-9005-ab1bda939c4f.png)

最后出现结果如下
![image](https://user-images.githubusercontent.com/23498943/64902072-62783780-d6d3-11e9-8551-8c0fc2ee5695.png)

这是我的网络环境
![image](https://user-images.githubusercontent.com/23498943/64902076-7de34280-d6d3-11e9-95d6-b8b26fdf9070.png)

### Observed Results

  [实际表现]
  
无法初始化
  
### Expected Results

  [期望表现]
  
能够初始化成功，进行开发。
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs here to reproduce the problem
  // 可以使用小程序代码片段功能，方便其它人帮助你定位代码问题
  // 详情可参考这里：https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
  ```

**Comment by Gcaufy** [comment]
应该是网络问题，npm init 是下载 github 的包
你可以尝试一下 wget https://github.com/wepyjs/wepy-templates/archive/2.0.x.zip
看网络是否能通。

**Comment by guanjiangtao** [comment]
> 应该是网络问题，npm init是下载github的包
> 你可以尝试一下wget https://github.com/wepyjs/wepy-templates/archive/2.0.x.zip
> 看网络是否能通。

我试过了，是可以的。

**Comment by xo1988** [comment]
然后呢，我也是可以但是还报连接不上的错误，telnet也是通的。

**Comment by Gcaufy** [comment]
@xo
 see： https://github.com/Tencent/wepy/issues/2522
