### ISSUE TITLE
2.X 版本有 Pug 插件的开发计划吗？

### ISSUE THREAD

**Issue by Riant** [Tencent/wepy#2393]
## Description

1.X 版本有对 Pug 的支持，2.X 版本目前没有发现相关官方插件，有支持的计划吗？

谢谢。

**Comment by Riant** [comment]
@dlhandsome 

能否在文档中说明一下 cli 插件的运行机制啊，这样的话，社区也有能力扩展相关支持。

我参考 @wepy/compiler-sass 尝试新增 @wepy/compiler-pug 如下：
```
const _pug = require('pug');

function createPugPlugin (compilation, type, options) {
  return function (node, ctx) {
    return new Promise ((resolve, reject) => {
        var fn = _pug.compile(node.content, options);
        var html = fn({});
        console.log('html >>> ', html )
        node.compiled = {
          code: html
        }
        resolve(node)
    });
  }
}

exports = module.exports = function (options) {
  return function () {
    ['pug', 'jade'].forEach(type => {
      this.register(`wepy-compiler-${type}`, createPugPlugin(this, type, options));
    });
  }
}
```

`console.log` 的 `html >>>` 及其后边 pug 编译之后的内容也都正常打印出来了，但是查看 weapp 里边的 wxml 文件，还是 pug 源码，又是什么道理呢？

谢谢。

**Comment by Riant** [comment]
写惯了 pug 之后，如果又要回到 html 的写法，真的是毋宁回到 1.x 啊。还请体谅这个支持的急迫。如若清楚 cli 的 loader 机制，想来这个支持是不复杂的，可能甚至半个小时也都不需要就能实现了。

还望官方尽快实现一下，或者完善一下相关文档，好让社区也能顺利参与。谢谢。

**Comment by Riant** [comment]
终于实现了，需要的同学： https://github.com/Riant/wepy2-compiler-pug

**Comment by Gcaufy** [comment]
@Riant 建议加上test case 然后 pr 到 wepy 2.0 分支 。
