### ISSUE TITLE
computed 和 watch 在 repeat 组件下失效，onLoad 也是，怎么解决？

### ISSUE THREAD

**Issue by yeahliv** [Tencent/wepy#2402]

**Comment by yeahliv** [comment]
我叼你妈的，这尼玛也叫做 vue 开发风格？vue 什么时候computed 会失效啊？什么时候 watch 不能用啊？什么时候 created 不能用啊，我草你妈死全家的开发组浪费我的青春，你妈死了。我叼你妈！

**Comment by yeahliv** [comment]
微信开发组尼玛就是垃圾，全组都是垃圾，从JSSDK到小程序，全是你麻痹的废物

**Comment by Gcaufy** [comment]
1.7 的版本在组件 repeat 下会导致数据绑定失效，这个是已知问题，请升级 2.0 吧。
