### ISSUE TITLE
WePY 2.0 不支持vant-weapp ui框架, 引入报错

### ISSUE THREAD

**Issue by neveryielding** [Tencent/wepy#2404]
VM705:1 ./pages/vant-weapp/button/index.wxml
../wxs/utils.wxs not found from ./pages/vant-weapp/button/index.wxml
  1 | 
> 2 | <wxs module="utils" src="../wxs/utils.wxs"></wxs>
    | ^
  3 | 
  4 | 
  5 |

**Comment by neveryielding** [comment]
已解决

**Comment by HeiShanLaoYao889** [comment]
怎么解决的?
