### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by chenyx886** [Tencent/wepy#2410]
npm run dev

> ycfw@1.0.0 dev /Users/Chenyx/Workspaces/chat/ycfw
> wepy build --watch

[WARNING] 找不到编译器：wepy-compiler-less。
[21:55:13] [信息] 检测到有效NPM包资源，正在尝试安装，请稍等。
up to date in 7.271s
[21:55:22] [完成] 已完成安装 wepy-compiler-less，重新启动编译。
[21:55:22] [编译] 入口: src/app.wpy
[WARNING] 未安装wepy-eslint，执行npm install wepy-eslint --save-dev 或者在wepy.config.js中关闭eslint选项
[21:55:22] [写入] JSON: dist/app.json
[WARNING] 找不到编译器：wepy-compiler-less。
[Error] 未发现相关 less 编译器配置，请检查wepy.config.js文件。

**Comment by chenyx886** [comment]
在网上查找了很多资料 都按照他们所说的解决步骤，但是最后都没用啊

**Comment by Gcaufy** [comment]
npm install 没有执行吧。

**Comment by Gumow** [comment]
npm run   @@dev启动后，不能实时编译吗，一直卡着 @Gcaufy
