### ISSUE TITLE
赋值操作日志显示setData canceled, setData dirty:  false

### ISSUE THREAD

**Issue by GitHubWuYi** [Tencent/wepy#2413]
源码：
    methods: {
      onChange(event) {
        this.active = event.$wx.detail;
        console.log(event);
      },
  }

控制台输出：
setData canceled
app.js:20 setData dirty:  false
事件被触发后，active值没有改变。

**Comment by GitHubWuYi** [comment]
自己代码的问题

**Comment by liuzhaoxu1996** [comment]
我也遇到了这个问题，感觉代码没有错误呀

**Comment by JimmytheMouth** [comment]
默认生成的index.wpy中有以下这段代码，看下是不是被个hook给捕捉了。
`      // Page 级别 hook, 只对当前 Page 的 setData 生效。
      'before-setData': function(dirty) {
        if (Math.random() < 0.2) {
          console.log('setData canceled')
          return false // Cancel setData
        }
        dirty.time = +new Date()
        return dirty
      }`

**Comment by JimmytheMouth** [comment]
默认生成的index.wpy中有以下这段代码，看下是不是被个hook给捕捉了。

![Uploading image.png…]()


`      // Page 级别 hook, 只对当前 Page 的 setData 生效。
      'before-setData': function(dirty) {
        if (Math.random() < 0.2) {
          console.log('setData canceled')
          return false // Cancel setData
        }
        dirty.time = +new Date()
        return dirty
      }`

**Comment by JimmytheMouth** [comment]
默认生成的index.wpy中有以下这段代码，看下是不是被个hook给捕捉了。

![微信图片_20200125124939](https://user-images.githubusercontent.com/38430707/73116436-2ef6c500-3f71-11ea-9ee7-87059d9c8e24.png)
