### ISSUE TITLE
关于wepy 1.x 和wepy 2.x之间的关系 ？

### ISSUE THREAD

**Issue by MoxTY** [Tencent/wepy#2426]
wepy 1.x的项目，现阶段有没有办法在原有基础上升级为 wepy 2.x，因为目前项目迭代越来越大 ，不适合重新搭建一个 wepy 2.x 的框架

**Comment by Gcaufy** [comment]
升级的话，要做的改动可能会比较大。

wepy2 是 wepy1 的重写的版本，核心实现机制都是重写的。 wepy2 是基于 Component 实现的组件化。所以比较难去做到向下兼容。

建议新的项目可以以 wepy2 启动。
