### ISSUE TITLE
1.X版本 编译报错

### ISSUE THREAD

**Issue by 315674376** [Tencent/wepy#2430]
C:\Users\31567\AppData\Roaming\npm\node_modules\@wepy\cli\core\parseOptions.js:98
        throw `Unexpected type: ${k} expect a ${defaultItem.type.name}`;
        ^
Unexpected type: plugins expect a Array
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

试过删除依赖重新 yarn 也不行  求助

**Comment by Gcaufy** [comment]
这个是使用了 wepy2 的cli。。 不是 1.x 的版本
