### ISSUE TITLE
wepy2 独立分包报错，不独立不报错

### ISSUE THREAD

**Issue by snoobcn** [Tencent/wepy#2435]
## Description

独立分包报错，如果不使用独立分包仅仅是分包不报错。

## Environment

  * Platform: 开发者工具
  * Platform version:  RC v1.0.2.1907300]
  * wepy-cli version: 2.0.0-alpha.10
  * wepy version: 2.0.0-alpha.9
  
## Reproduce

app.wpy中配置分包
    subPackages:[
      {
        root: 'subDemo', 
        pages: [
          'pages/demo',
        ],
        independent: true // 注释该行不报错，一旦使用就报错
      },
    ],

### Observed Results

WAService.js:1 Uncaught Error: module "vendor.js" is not defined
    at require (WAService.js:1)
    at window.require (appservice.js:202)
    at WAService.js:1
    at VM15057 paying.js:3
    at require (WAService.js:1)
    at window.require (appservice.js:202)
    at <anonymous>:1227:9
    at HTMLScriptElement.scriptLoaded (appservice?t=1570777558164:2607)
    at HTMLScriptElement.script.onload (appservice?t=1570777558164:2618)
  
### Expected Results

独立分包能够正常且不报错

**Comment by Gcaufy** [comment]
WePY 运行必须依赖 core 库。如使用使用独立分包的话。
也就是说每个独立分包都必须单独编译一个 core 库。
所以 WePY 暂无计划去支持独立分包。

如果想使用独立分包，建议独立的分包可以直接使用原生。这样就可以了。

后续，这里会优化一下编译提示。

**Comment by Gcaufy** [comment]
另开一个 issue 处理 warning 事宜
