### ISSUE TITLE
page里面怎么获取到app实例？

### ISSUE THREAD

**Issue by luo2096** [Tencent/wepy#2450]
[##] [Description]

  [问题描述：
我的wepy文件里 所有wepy点出来的方法都是报错的，不如wepy.$apply(),都是
]
  
  [Description of the issue]

## Environment

  * Platform: [开发者工具/vscode]
  * Platform version: [wepy2/小程序基础库版本2.0.4]
  * wepy-cli version: [2.0.0-alpha.10]
  * wepy version: [2.0.0-alpha.9]
  
## Reproduce

  [如何重现问题]
  只要在wepy页面文件用page实例点出来的方法都会报错

### Observed Results

  [实际表现]
  开发者工具报错  that.$apply is not a function;
  [Observed Results]
  
### Expected Results

  [期望表现]
  不报错，正常调用
  [Expected Results]
  

## Relevant Code / Logs

import wepy from '@wepy/core'

wepy.page({
data:{
      testdata: 1,
},

methods:{
      login() {
         this.testdata: = 1
         this.$apply() //这里就会报错或者按照文档中page实例访问app实例this.$parent也同样报错都是        //that.$xxx is not a function;
      }
}
})
`

**Comment by luo2096** [comment]
> 
> ## Description
> 
> [问题描述：
> 我的wepy文件里 所有wepy点出来的方法都是报错的，不如wepy.$apply(),都是
> ]
> 
> [Description of the issue]
> ## Environment
> 
>     * Platform: [开发者工具/vscode]
> 
>     * Platform version: [wepy2/小程序基础库版本2.0.4]
> 
>     * wepy-cli version: [2.0.0-alpha.10]
> 
>     * wepy version: [2.0.0-alpha.9]
> 
> 
> ## Reproduce
> 
> [如何重现问题]
> 只要在wepy页面文件用page实例点出来的方法都会报错
> ### Observed Results
> 
> [实际表现]
> 开发者工具报错 that.$apply is not a function;
> [Observed Results]
> ### Expected Results
> 
> [期望表现]
> 不报错，正常调用
> [Expected Results]
> ## Relevant Code / Logs
> 
> 
> <script> import wepy from '@wepy/core' wepy.page({ data:{ testdata: 1, }, methods:{ login() { this.testdata: = 1 this.$apply() //这里就会报错或者按照文档中page实例访问app实例this.$parent也同样报错都是 //that.$xxx is not a function; } }, onLoad() { wx.checkSession({ success: ()=>{ wx.reLaunch({ url: '../home/home' }); } }); } }) </script>
> 
>

**Comment by qilovehua** [comment]
wepy.$instance
wepy.$instance.globalData

**Comment by Gcaufy** [comment]
2.0 中
```
this.$app
```

**Comment by europeancastle** [comment]
getApp()

**Comment by bestK** [comment]
2.0.0-alpha.23

上面的方法都无效，提示is not a function

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/74585468-f306cb00-5017-11ea-8f9c-f8cf13ad844b.png)

**Comment by truexu0529** [comment]
this.$wx.$app

**Comment by yamlling** [comment]
this.$app.$options.globalData 可以获取到globalData的数据 感谢 @Gcaufy
