### ISSUE TITLE
转成百度小程序 bindtap传参数无效

### ISSUE THREAD

**Issue by qilovehua** [Tencent/wepy#2452]
版本：wepy-cli@1.7.3-alpha6

wepy写法：
`<image class="search-empty" bindtap="bindClear({{orderId}})" src="../image/cancel.png" />`

`<image class="search-empty" bindtap="bindClear" src="../image/cancel.png" data-wpybindclear-a="orderId"/>`

wepy build -o baidu -w转成百度小程序后，输出的swan文件是上面的，点击后orderId并没有传给bindClear。
wepy build 转成微信小程序，orderId能正常拿到

应该怎么写？

**Comment by Gcaufy** [comment]
抱歉，因为暂时没有 baidu 小程序相关的开发诉求。所以 1.7 版本中的同构不在维护计划当中。
