### ISSUE TITLE
async/await 在事件生命周期函数中使用无效

### ISSUE THREAD

**Issue by europeancastle** [Tencent/wepy#2469]
## Description

使用 async onLoad()、async onShow()、、async onHide()、、async created()等生命事件周期函数时，await 的语句提前执行，相当于没有异步效果。
但使用开发者工具时正常，但小程序SDK2.9.1版本无效，2.9.0版本有效，2.8.3有效。
在真机上都无效。

## Environment

  * Platform: VSCode
  * Platform version: Android, IOS
  * Wechat version: 7.0.7
  * wepy-cli version: "@wepy/cli": "^2.0.0-alpha.20",
  * wepy version: "@wepy/core": "^2.0.0-alpha.11",
  * other version: "@wepy/use-promisify": "^2.0.0",
  
## Reproduce

```
data: {
    offices: [],
    laboratories: []
},
async onLoad() {
    await this.getList('office');
    await this.getList('laboratory');
},
methods: {
    async getList(type) { this.offices =  await ... }
}
```

### Observed Results

在开发者工具上，this.offices 有值，真机上没有值。
  
### Expected Results

期望在真机上，onLoad事件执行时，await 请求一些数据，并赋值到 this.offices
  
## Relevant Code / Logs

pages/department/door/index: onLoad have been invoked
[publib]:1 pages/department/door/index: onShow have been invoked
[publib]:1 Invoke event onReady in page: pages/department/door/index
[publib]:1 pages/department/door/index: onReady have been invoked

**Comment by Gcaufy** [comment]
生命周期函数并不会影响 async/await 的。
看看是不是其它地方的代码逻辑有问题呢？

**Comment by europeancastle** [comment]
确实是别的代码问题，wx.hideLoading() 方法不能加await，在真机ios会导致永远执行，不抛出异常，是个BUG，已报官网。
