### ISSUE TITLE
$apply()不能重新渲染页面

### ISSUE THREAD

**Issue by chenyuanluck** [Tencent/wepy#247]
设有A页面，A1页面跳A2页面，返回到A1时，$apply()不能重新渲染页面

**Comment by coolhwm** [comment]
的确有这个问题，原生小程序不会出现

**Comment by Gcaufy** [comment]
代码是怎么写的呢？

**Comment by chenyuanluck** [comment]
@Gcaufy 就是相同的一个页面A，A1跳到A2，再跳回A1后修改数据就不能渲染到页面了，$apply()和setData都是不行的，我把整个项目都换成了wepy，几个月的业务。。。后来没办法
![image](https://user-images.githubusercontent.com/13072539/28000507-b6cf8e76-6558-11e7-82dd-d83fd26b973e.png)
把框架里的几句代码改了下，就没出现这问题了，我感觉这个地方不能随便改，但是我项目急，没时间了。。。求大神快解决这个问题。我感觉问题大多出现在很多地方用了同一个实例上。

**Comment by Gcaufy** [comment]
你这里的意思是 wxpage 永远取 当前页面，说明你的问题是在于，你在apply时， this.$wxpage 指向不对。
this.$wxpage 是在 $init 中赋值的。$init 是在 onLoad 函数中处理的，也就是说只要你的页面onLoad 事件发生了，那么 this.$wxpage 肯定指向是对的。
而你的描述，A1->A2->A1， 这样也会触发A1的onLoad吧，也会将 this.$wxpage 赋值的。所以理论上不应该出错的。

**Comment by chenyuanluck** [comment]
`<style lang="less">
  navigator, view {
    width: 100%;
    text-align: center;
    height: 80rpx;
    line-height: 80rpx;
    background: #F00;
    color: #FFFEFE;
    margin-top: 60rpx;
  }
</style>
<template>
  <view  @tap="go({{'./test?a=' + currentMenu}})">
    跳转到/pages/course/test?a={{currentMenu}}
</view>
  <view @tap="changeMenu"> 这是一个测试{{currentMenu}}</view>
</template>

<script>
  /**
   * 描述:我的动态
   * 版权: Copyright (c) 2017
   * 公司: 深圳市虾美科技有限公司
   * 作者: 陈元
   * 版本: 1.0.0
   * 创建时间: 2017/6/29 11:48
   */

  import wepy from 'wepy'

  export default class Details extends wepy.page {
    config = {
      
    }

    data = {
      // 当前选中菜单
      currentMenu: 0
    }

    computed = {}

    methods = {
      // 切换菜单
      changeMenu: () => {
        this.currentMenu++
        this.$apply()
      },
      go:(url) => {
        this.$navigate(url)
      }
    }

  }
</script>
`

请测试一下如上代码，看是不是我写的有问题，谢谢！ @Gcaufy

**Comment by Gcaufy** [comment]
不能重新渲染页面是什么意思，我测试了，返回后点下面的按钮数字一样会增加。

**Comment by chenyuanluck** [comment]
你是直接用的我的代码吗？你用的wepy是哪个版本的？ @Gcaufy

**Comment by Gcaufy** [comment]
直接copy你的代码，你是 返回后点下面的按钮数字不会增加了？
我的是1.5.7版本，好久没有更新这里的逻辑了，所以这个跟版本应该没有太大关系

**Comment by blusewang** [comment]
[T_T] 我也遇到了！。。。。。。

**Comment by wangqianjun** [comment]
我也出现了同样的问题，apply方法不起作用。但是只是在体验版里有问题，微信开发模式下没有问题。

**Comment by johnshwang** [comment]
我也出现了同样的问题，MyPage(A) navigateTo MyPage(B) 之后，点击左上角返回 ，在MyPage(A) 页面里面下拉刷新之后调用 $apply() 没有任何效果。（另外，返回到MyPage(A) 之后MyPage(A) 里 data 数据已经被切换到 MyPage(B)  里 data 数据 ）

**Comment by johnshwang** [comment]
我也出现了同样的问题，MyPage(A) navigateTo MyPage(B) 之后，点击左上角返回 ，在MyPage(A) 页面里面下拉刷新之后调用 $apply() 没有任何效果。

另外，还有 2 点情况：
1、返回到 MyPage(A) 之后 MyPage(A) 里 data 数据已经被设置成 MyPage(B) 里 data 数据 。
2、如果使用 data 被 watch 绑定了，数据会视图会被切换。

**Comment by Gcaufy** [comment]
@johnshwang 可以提供代码片段方便调试么？

**Comment by johnshwang** [comment]
`<style lang="less">

</style>
<template>
  <view>pageId: {{ pageId }}</view>
  <button @tap="tapNext">next()</button>
</template>

<script>
  import wepy from 'wepy'

  export default class Test extends wepy.page {
    config = {
      navigationBarTitleText: 'test',
      enablePullDownRefresh: true
    }

    data = {
      pageId: 0,
      reqOptions: {}
    }

    methods = {
      tapNext (e) {
        wepy.navigateTo({
          url: '/pages/test?id=2'
        })
      }
    }
    watch = {

    }

    onShareAppMessage (res) {

    }

    async onLoad (options) {
      let self = this
      self.reqOptions = options
      self.pageId = self.reqOptions.id ? self.reqOptions.id : 1
      console.log('onLoad', self.reqOptions)
    }

    async onShow () {
      console.log('onShow', this.reqOptions)
    }

    onPullDownRefresh () {
      let self = this
      console.log('onPullDownRefresh', self.reqOptions)
    }
  }
</script>
`

**Comment by johnshwang** [comment]
```
<style lang="less">

</style>
<template>
  <view>pageId: {{ pageId }}</view>
  <button @tap="tapNext">next()</button>
</template>

<script>
  import wepy from 'wepy'

  export default class Test extends wepy.page {
    config = {
      navigationBarTitleText: 'test',
      enablePullDownRefresh: true
    }

    data = {
      pageId: 0,
      reqOptions: {}
    }

    methods = {
      tapNext (e) {
        wepy.navigateTo({
          url: '/pages/test?id=2'
        })
      }
    }
    watch = {

    }

    onShareAppMessage (res) {

    }

    async onLoad (options) {
      let self = this
      self.reqOptions = options
      self.pageId = self.reqOptions.id ? self.reqOptions.id : 1
      console.log('onLoad', self.reqOptions)
    }

    async onShow () {
      console.log('onShow', this.reqOptions)
    }

    onPullDownRefresh () {
      let self = this
      console.log('onPullDownRefresh', self.reqOptions)
    }
  }
</script>
```
@Gcaufy 就这个 page 了，可以简单 run 一下

**Comment by FEpccBo** [comment]
同问，请问有解决办法么

**Comment by FEpccBo** [comment]
@chenyuanluck

**Comment by chenyuanluck** [comment]
@FEpccBo 当时由于公司对小程序的性能、体验、功能、小程序体积等要求比较高，没有使用框架了。所以后面还是没有能处理这个问题。不知道框架有没有修复这个问题，或者是你的写法有没有什么问题。

**Comment by chenyuanluck** [comment]
@FEpccBo 当时使用wepy时，主要是看重它的组件化、对现代web前端代码语法的支持，比如编译less，好像还有await语法支持之类的能力。现在小程序出了组件化，还是用小程序的吧，语法什么的，忍一忍也就过去了。。

**Comment by sw-wang** [comment]
我的解决方法：
`onShow(){
        let pages = getCurrentPages();
        let selfPage = pages[pages.length - 1]
        this.user = selfPage.data.user
        this.$apply()
    }`
我发现getCurrentPages里面的数据是最新的， 所以在返回onShow的时候再去取getCurrentPages的内容重新赋值

**Comment by yangfandashuaige** [comment]
@sw-wang 那如果是页面的数据过多怎么办 也要这么赋值吗？还有就是数据如果不在不同的组件怎么办?

**Comment by yangfandashuaige** [comment]
@Gcaufy
