### ISSUE TITLE
初始化生成项目时报错

### ISSUE THREAD

**Issue by TangShunwu** [Tencent/wepy#2470]
在执行 wepy init standard demo后报如下问题。
downloading template   wepy-cli · Failed to download repo standard: connect ETIMEDOUT 74.86.17.48:443

**Comment by 854776249** [comment]
我也是，npm install就直接报错，什么时候解决啊

**Comment by ywx6265** [comment]
我也是，什么原因啊？？我原本还没问题的

**Comment by fastCreator** [comment]
我也是啊，听说是网络问题；难道这么多人网络问题啊？我正常上网啥问题都没有啊？

**Comment by ywx6265** [comment]
> 我也是啊，听说是网络问题；难道这么多人网络问题啊？我正常上网啥问题都没有啊？

我现在可以了（等了一个晚上，第二天早上就可以了）

**Comment by lcb1208** [comment]
同样，init失败

**Comment by mrzsping** [comment]
毫无头绪

**Comment by Enoliu** [comment]
+1

**Comment by lylogan** [comment]
+1

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/issues/2522
