### ISSUE TITLE
wepy2.0使用@wepy/plugin-uglifyjs

### ISSUE THREAD

**Issue by guopz** [Tencent/wepy#2472]
"@wepy/cli": "^2.0.0-alpha.19",
"@wepy/plugin-uglifyjs": "^0.0.2"

错误提示
You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.

tabBar 图片未生成

**Comment by Gcaufy** [comment]
build的时候是吗，有尝试过将 NODE_ENV 设置成 production 呢？

**Comment by guopz** [comment]
不管用，只要不使用uglifyjs就没有问题

**Comment by mikasaYw** [comment]
> 不管用，只要不使用uglifyjs就没有问题

看下wepy.config

**Comment by Q-Qplus1s** [comment]
问题还是存在 有解决办法吗？ @Gcaufy

**Comment by Gcaufy** [comment]
```
[19:59:12] info build app start...
[19:59:12] info app building App
[19:59:13] info component building components
[19:59:13] info component building components
[19:59:13] info component building components
[19:59:13] info component building components
[19:59:13] info vendor building vendor
[19:59:13] info assets building assets
[19:59:14] info uglifyjs Compressed File: 26, Original Size: 174.73 KB, Compressed Size: 68.75 KB, Ratio: 0.39%
[19:59:14] info build finished
```

我这里工作正常无法还原，你们能提供可还原的代码测试包么？

**Comment by guopz** [comment]
压缩是可以正常执行的，你把打包的文件全部删除，在重新执行，控制台显示完全正常，但是 tabBar 图片未生成，浏览器控制台报；

**Comment by Gcaufy** [comment]
@guopz 

还原步骤如下：

1. 创建 standard 模板
2. 给 app.wpy 添加 tabBar 选项
3. 补充 tabBar 页面
4. 给添加静态资源 `static` 指向 tabbar 图片文件。
5. 反复删除 weapp 目录并反复编译

结果都是 tabBar 图片可以正常显示。因此问题无法复现。



建议检查一下是否配置静态资源目录吧。

**Comment by dosicker** [comment]
@Gcaufy 
G大你好，我就是创建的默认standard版本，真机的控制台会输出[You are currently using minified code outside of NODE_ENV === "production"...](https://github.com/Tencent/wepy/issues/2472#issue-516002604)这样的错误...

而另外走build 时却并不会出现该错误，只有在watch模式下才会报此错...
![image](https://user-images.githubusercontent.com/29482340/169090051-ca645a03-19f1-4519-b810-86601be0e5cf.png)

求解救~(╯﹏╰)~

**Comment by dosicker** [comment]
> @Gcaufy G大你好，我就是创建的默认standard版本，真机的控制台会输出[You are currently using minified code outside of NODE_ENV === "production"...](https://github.com/Tencent/wepy/issues/2472#issue-516002604)这样的错误...
> 
> 而另外走build 时却并不会出现该错误，只有在watch模式下才会报此错...
> 
> ![image](https://user-images.githubusercontent.com/29482340/169091297-1f4e5cf4-8582-42d9-9d88-39173f382336.png)
> 
> 求解救~(╯﹏╰)~
> 
> 环境条件： node：10.24.1 == npm => 6.14.12 wepy：（wepy init standard demo 默认：1.6.0）直接启动standard的项目就会出现该错误

鉴于当前项目看没多少人维护，我这里对这个方法的处理是这样的：

因为只有非production环境才会出现，故：
![image](https://user-images.githubusercontent.com/29482340/220541843-c8b77e52-4502-48a6-b628-f7d5d7ceefd3.png)
该启动命令原为：wepy build --watch → cross-env NODE_ENV=production wepy build --watch

使项目启动时以production环境给到wepy内部一个障眼法错误识别，对我们的项目实际开发不会造成任何影响损害

至此......要是后面后面有更好的方式直接从根源上解决掉的话，麻烦踢我一下...o(╥﹏╥)o
