### ISSUE TITLE
全局配置使用组件无效

### ISSUE THREAD

**Issue by NineSwordsMonster** [Tencent/wepy#2477]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  在app.wpy文件中增加
```json
  usingComponents: {
    'van-icon': 'module:vant-weapp/dist/icon'
  },
```
生成的app.json 没有该配置

## Environment

  * Platform: [开发者工具]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [7.0.8]
  * wepy-cli version: [2.0.0-alpha.17]
  * wepy version: [@wepy/core": "^2.0.0-alpha.11]
  
## Reproduce

   在app.wpy文件中增加
```json
  usingComponents: {
    'van-icon': 'module:vant-weapp/dist/icon'
  },
```

### Observed Results

 生成的app.json 没有该配置
  
### Expected Results

 生成的app.json 有该配置

**Comment by daiyifei** [comment]
确实有这个问题，只能在每页单独配置，十分麻烦

**Comment by Gcaufy** [comment]
module 类型的 components 在 app 中声明无效。其它类型的 components 可以正常工作 。
在 next 版中已 fix.
```
npm i @wepy/cli@2.0.0-alpha.22 --save-dev
```

**Comment by Lolingew** [comment]
> module 类型的 components 在 app 中声明无效。其它类型的 components 可以正常工作 。
> 在 next 版中已 fix.
> 
> ```
> npm i @wepy/cli@2.0.0-alpha.22 --save-dev
> ```

2.1.0版本又没法用module了，还能咋整？
