### ISSUE TITLE
wepy2在开发者工具调用最新基础库2.9.3时 v-model指令功能失效

### ISSUE THREAD

**Issue by WebChenSir** [Tencent/wepy#2484]
## Description
wepy2在开发者工具调用最新基础库2.9.3时 v-model指令功能失效，其他低版本的都正常

## Environment

  * Platform: 开发者工具
  * Platform version: 1.02.1910120
  * wepy-cli version: 2.0.0-alpha.19
  * wepy version: 2.0.0-alpha.20

**Comment by onlonely** [comment]
的确如此,不知道是哪个版本修复...

**Comment by WebChenSir** [comment]
> 的确如此,不知道是哪个版本修复...

已经确认是微信小程序官方那边的问题，等官方修复
