### ISSUE TITLE
Error in nextTick: "TypeError: Cannot read property 'hooks' of undefined"

### ISSUE THREAD

**Issue by Q-Qplus1s** [Tencent/wepy#2486]
环境
```
    "@wepy/core": "^2.0.0-alpha.9",
    "@wepy/redux": "^2.0.1",
    "redux": "^4.0.4",
    "redux-actions": "^2.6.5",
    "redux-saga": "^1.1.3",
```

进入的 page 相关 hook

```javascript
  data: {
    folderId: '-1',
  },
  onLoad(param) {
    this.folderId = param.folderId;
  },

  onShow() {

    this.$store.dispatch({ type: T.UD_SUB_FILE_LIST_REQUEST, folderId: this.folderId });
  },
```

问题：
1. 点击进入后页面数据加载正常
2. 多次点击有时候出现问题描述的error，不知道哪里hook有问题

log：
```
VM614:1 TypeError: Cannot read property 'hooks' of undefined
    at callUserHook (vendor.js:2019)
    at WepyComponent.<anonymous> (vendor.js:2158)
    at Watcher.get (vendor.js:1580)
    at Watcher.run (vendor.js:1658)
    at vendor.js:1461
    at Array.forEach (<anonymous>)
    at flushSchedulerQueue (vendor.js:1459)
    at flushSchedulerQueue (vendor.js:1469)
    at Array.<anonymous> (vendor.js:528)
    at flushCallbacks (vendor.js:462)
```

**Comment by Gcaufy** [comment]
是否方便提供一个可还原的测试包呢？

**Comment by feliciaZH** [comment]
遇到同样的问题，怎么解？

**Comment by viki719632** [comment]
the same question.
For example,I use the subscript of redux at page 1.
when I redirect to the same page next time,the issue occured.
Then,I unsubscript the redux onUnload,the issue go away

**Comment by chenillen** [comment]
> the same question.
> For example,I use the subscription of redux at page 1.
> when I redirect to the same page next time,the issue occured.
> Then,I unsubscript the redux at the lifecycle of onUnload,the issue go away

same situation here. thinking about component sync data problem

**Comment by chenillen** [comment]
感謝 @Gcaufy ，已經解決問題。

主要的問題是由component造成的：
unload 之后的页面上面 setData ，如果会使得这个页面上创建出自定义组件，那依然会创建，即使它已经 unload。

**Comment by Gcaufy** [comment]
正常流程
```
组件 create (原生事件) -> attach (原生事件) -> 组件 init （wepy 事件，在这个阶段初始化 $app) 
state 变更 (wepy) -> callHook (wepy) -> setData （原生)
```
正常情况下， state 变更一定是在 组件 init 之后的。所以 callHook 中 $app.hooks 一定是存在的。这也是为什么一直没有定位的问题的原因。

感谢 @chenillen  提供的示例还原了问题。
代码中在 unLoad (原生) 事件中进行 state 变更，同时触发了一个带有 `wx:if` 标签的 Component 的显示状态以及其数据 state 变更。结果直接导致在新的组件的 state 变更在 组件的 create 之后， attach 之前，这时候 $app 并未初始化完成。所以导致 `$app.hooks` 抛出异常。

因此，对于这个问题，我加上了一个 warning 提示，而非抛出异常。
如果出现 warning, 就可能说明代码本身还是存在类似问题需要自己定位。

**Comment by chenillen** [comment]
把 v-if(wx:if) 改為 v-show就不會在attach之前觸法。
