### ISSUE TITLE
npm install 之后npm run dev 报这个错误Cannot find module 'tty-table'

### ISSUE THREAD

**Issue by githubyang312** [Tencent/wepy#2491]
## Description

wepy init standard 项目，npm install 之后npm run dev 报这个错误 Cannot find module 'tty-table'

## Environment

  * wepy-cli version: 2.0.0-alpha.17

  
## Reproduce

  [如何重现问题]
  
  wepy init standard 项目，npm install 之后npm run dev

  [期望表现]
  
希望尽快恢复

**Comment by superlbr** [comment]
npm install tty-table --save-dev

**Comment by Gcaufy** [comment]
@githubyang312 
的确是个 bug, 先通过这种方式手动 fix 吧。 
```
npm install tty-table --save-dev
```
