### ISSUE TITLE
刚下载完wepy，试了一下input的v-model，不能双向绑定。

### ISSUE THREAD

**Issue by gipal** [Tencent/wepy#2493]
刚下载完wepy，试了一下input的v-model，不能双向绑定。然后试了@input和bindinput的方法也不能触发表单输入事件。这是怎么回事，现在表单要如何双向绑定。第一次使用wepy请多指教

**Comment by gipal** [comment]
刚刚听说在微信开发工具里不要用2.9.3，所以改成用2.8.3就好了。

**Comment by heavenshow01** [comment]
我也遇到同样的问题，请问怎么解决的？

**Comment by Gcaufy** [comment]
https://developers.weixin.qq.com/community/develop/doc/0008e473ca0e40c5d879b16065b000

来自 2.9.3 原生 input 的 bug.
测试 2.9.3 以上和以下 都是 ok 的。
