### ISSUE TITLE
downloading template   wepy-cli · Failed to download repo standard: connect ECONNREFUSED 151.101.0.133:443

### ISSUE THREAD

**Issue by liuxy0551** [Tencent/wepy#2494]
执行命令  wepy init standard myproj 的时候会报错，目前无法初始化新项目，求帮助

**Comment by flatpig** [comment]
我也遇到这个问题了，请问怎么解决的？

**Comment by liuxy0551** [comment]
> 我也遇到这个问题了，请问怎么解决的？

DNS 添加了一个 8.8.8.8 后可以了

**Comment by EuniceShaw** [comment]
> > 我也遇到这个问题了，请问怎么解决的？
> 
> DNS 添加了一个 8.8.8.8 后可以了

我电脑设置了，还是不行

**Comment by liuxy0551** [comment]
> > > 我也遇到这个问题了，请问怎么解决的？
> > 
> > 
> > DNS 添加了一个 8.8.8.8 后可以了
> 
> 我电脑设置了，还是不行

再添加 114.114.114.114 试试，我这边是因为 DNS

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/issues/2522

**Comment by gzgogo** [comment]
不要使用淘宝镜像，将镜像切换回npm
