### ISSUE TITLE
非原生组件自定义事件 @click-right=“functionName” 不生效

### ISSUE THREAD

**Issue by galikeoy** [Tencent/wepy#2497]
#1768  Description

 问题描述：非原生组件自定义事件 `@click-right=“functionName”` 不生效
  
  [Description of the issue]

## Environment

  * Platform: [微信开发者工具]
  * Platform version: [1.02.1910120]
  * Wechat version: [7.0.7]
  * wepy-cli version: [2.0.0-alpha.20]
  * wepy version: [^2.0.0-alpha.9]
  *微信基础库版本 2.9.4
  
## Reproduce

  当在一个非原生组件中绑定一个自定义事件
```javascript
@click-right="rightNavbar"
```

### Observed Results

  它编译为
```javascript
bindclick-right="rightNavbar"
```
然而这在实际预览中并没有触发`rightNavbar`   

而当我把编译后得到的index.wxml文件，将其`bindclick-right`加上了冒号
```javascript
bind:click-right="rightNavbar"
```
 `rightNavbar` 成功的被触发了
### Expected Results

摘自[微信官方文档 ](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/event.html)
>自基础库版本 1.5.0 起，在大多数组件和自定义组件中， bind 后可以紧跟一个冒号，其含义不变，如 bind:tap 。基础库版本 2.8.1 起，在所有组件中开始提供这个支持。

wepy是否有在非原生组件绑定事件语法，加上冒号呢 麻烦大佬回答一下，非常感谢！

**Comment by daochouwangu** [comment]
自定义事件名中间有横杆,即 `kebab-case`的事件名，必须要使用`bind: `目前官方我测试了也是这样。你可以先把`event-name`改成`camelCase `形式的，比如`eventName`或者全部小写 `eventname`

**Comment by galikeoy** [comment]
> 自定义事件名中间有横杆,即 `kebab-case`的事件名，必须要使用`bind: `目前官方我测试了也是这样。你可以先把`event-name`改成`camelCase `形式的，比如`eventName`或者全部小写 `eventname`

谢谢，这个确实是一个方法  
但是我用的vant-weapp的组件，他们的事件名也已经定好暴露出来的，我也不想改他们的源码了(懒，菜)  
而且放弃了vant的组件，使用原生组件来重写，是暂时解决了，希望官方尽快解决把

**Comment by Asces** [comment]
将@wepy/core升级到  @wepy/core@2.0.0-alpha.14以上版本

**Comment by Asces** [comment]
微信运行库版本要求 2.8.0 bind:xxxx 这种写法 针对自定义事件与非自定义事件 才通用支持
