### ISSUE TITLE
wepy2.0 无法调用 intercept 

### ISSUE THREAD

**Issue by galikeoy** [Tencent/wepy#2500]
[问题描述：wepy2.0 无法调用 intercept ]
  
2.0后的版本怎么用intercept？1.0的版本文档都是用类写的。而2.0版本则不用类写了，无论我怎么用都是not a function

![img](https://ws1.sinaimg.cn/large/006qqcX8gy1g9zps6hqnfj30cd08djrm.jpg)

**Comment by Gcaufy** [comment]
2.0 暂时还没支持 intercepter. 后续考虑加上

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/commit/3d94fc3004d4a9a8024f2f238bd90a656e0e0098
