### ISSUE TITLE
 wepy-中文乱码

### ISSUE THREAD

**Issue by winner66** [Tencent/wepy#2504]
<view class="loginTitle">
            <view class="{{currentTab==0?'select':'default'}}" data-current="0" @tap="switchNav">商业贷</view>
            <view class="{{currentTab==1?'select':'default'}}" data-current="1" @tap="switchNav">税贷</view>
            <view class="{{currentTab==2?'select':'default'}}" data-current="2" @tap="switchNav">公积金贷</view>
            <view class="{{currentTab==3?'select':'default'}}" data-current="3" @tap="switchNav">组合贷</view>
        </view>

编译后dist中

   <view class="loginTitle">
            <view class="{{currentTab==0?'select':'default'}}" data-current="0" bindtap="switchNav">��ҵ��</view>
            <view class="{{currentTab==1?'select':'default'}}" data-current="1" bindtap="switchNav">˰��</view>
            <view class="{{currentTab==2?'select':'default'}}" data-current="2" bindtap="switchNav">�������</view>
            <view class="{{currentTab==3?'select':'default'}}" data-current="3" bindtap="switchNav">��ϴ�</view>
        </view>

**Comment by winner66** [comment]
<view class="loginTitle">
            <view class="{{currentTab==0?'select':'default'}}" data-current="0" bindtap="switchNav">��ҵ��</view>
            <view class="{{currentTab==1?'select':'default'}}" data-current="1" bindtap="switchNav">˰��</view>
            <view class="{{currentTab==2?'select':'default'}}" data-current="2" bindtap="switchNav">�������</view>
            <view class="{{currentTab==3?'select':'default'}}" data-current="3" bindtap="switchNav">��ϴ�</view>
        </view>

**Comment by winner66** [comment]
"<view class="loginTitle">
            <view class="{{currentTab==0?'select':'default'}}" data-current="0" bindtap="switchNav">��ҵ��</view>
            <view class="{{currentTab==1?'select':'default'}}" data-current="1" bindtap="switchNav">˰��</view>
            <view class="{{currentTab==2?'select':'default'}}" data-current="2" bindtap="switchNav">�������</view>
            <view class="{{currentTab==3?'select':'default'}}" data-current="3" bindtap="switchNav">��ϴ�</view>
        </view>"

**Comment by Gcaufy** [comment]
看一下源码的文件格式，是不是非 utf-8 的。
wepy 编译都是使用的 utf8 格式。

**Comment by winner66** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Gcaufy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午2:44
收件人:&nbsp;"Tencent/wepy"<wepy@noreply.github.com&gt;;
抄送:&nbsp;"彭霞"<1248178733@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/wepy]  wepy-中文乱码 (#2504)




看一下源码的文件格式，是不是非 utf-8 的。
 wepy 编译都是使用的 utf8 格式。
 
感谢感谢，没有想到您会这么快回复我消息，

我是在下载的wepy 模板然后就在模板上的基础上改的

其中写了



<view class="loginTitle"&gt;
    <view class="{{currentTab==0?'select':'default'}}" data-current="0" @tap="switchNav" &gt;商业贷</view&gt;
    <view class="{{currentTab==1?'select':'default'}}" data-current="1" @tap="switchNav"&gt;税贷</view&gt;
    <view class="{{currentTab==2?'select':'default'}}" data-current="2" @tap="switchNav"&gt;公积金贷</view&gt;
    <view class="{{currentTab==3?'select':'default'}}" data-current="3" @tap="switchNav"&gt;组合贷</view&gt;
</view&gt;wepy实时编译出来就是乱码，刚刚在学习wepy,望指导一下，  在百度找了很久都没有看到解决办法

**Comment by Gcaufy** [comment]
通常情况下，模板都是 utf-8 编码的。你使用的什么命令生成的模块，我去 double check 一下，看看格式。
你那里也确认一下文件编码。有可能是 IDE 自动把编码转成了其它格式。

**Comment by winner66** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Gcaufy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午3:07
收件人:&nbsp;"Tencent/wepy"<wepy@noreply.github.com&gt;;
抄送:&nbsp;"彭霞"<1248178733@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/wepy]  wepy-中文乱码 (#2504)




通常情况下，模板都是 utf-8 编码的。你使用的什么命令生成的模块，我去 double check 一下，看看格式。
 你那里也确认一下文件编码。有可能是 IDE 自动把编码转成了其它格式。
 
—按官网上的步骤

**Comment by Gcaufy** [comment]
请问 问题还存在吗？
