### ISSUE TITLE
wepy.component()做的组件不能使用具名插槽吗？

### ISSUE THREAD

**Issue by gipal** [Tencent/wepy#2513]
"@wepy/core": "^2.0.0-alpha.9",
子组件：
<template>
    <div class="toast-wrap" @tap="clickConfirm" v-if="showToast">
    
      
      <slot name="header"></slot>
        {{content}}
      
    </div>

</template>

父组件：
 <toast :showToast="true" :content="123">
  
        <view slot="header" style="color:yellow;">我爱学习前端</view>
    
      </toast>

我爱学习前端没有显示出来，只显示了123

**Comment by fudiwei** [comment]
具名插槽需要在子组件的中配置：`multipleSlots: true`

``` JavaScript
wepy.component({
  options: {
    multipleSlots: true // 在组件定义时的选项中启用多slot支持
  }
})
```

> REF: https://wepyjs.github.io/wepy-docs/2.x/#/component/slot
