### ISSUE TITLE
使用WePY2时，使用腾讯视频插件不成功，有什么好的解决办法没？

### ISSUE THREAD

**Issue by leader318** [Tencent/wepy#2519]
```
<config>
{
  navigationBarTitleText: '平台',
  usingComponents: {
    "txv-video": "plugin://tencentvideo/video"
  }
}
</config>
```

项目编译后，产生是json文件里面的内容
```

{
    "navigationBarTitleText": "平台",
    "component": true,
    "usingComponents": {
        "txv-video": "./plugin://tencentvideo/video"
    }
}

```

`"txv-video": "./plugin://tencentvideo/video"`

路径前面加了 './' ,导致找不到插件

**Comment by WebChenSir** [comment]
app -> plugins 也要配置

**Comment by leader318** [comment]
app -> plugins 已经配置了
问题不在这，是编译后，路径变了
正确的路径：plugin://tencentvideo/video
编译后是：./plugin://tencentvideo/video
导致报错，如果把./ 去掉是正常的

就是"txv-video": "plugin://tencentvideo/video" 经过编译后，怎么不让它改变路径

**Comment by Gcaufy** [comment]
@SpringHgui 
定位到了，这个是这个 PR 引入的问题：https://github.com/Tencent/wepy/pull/2461
可以手动修改这里的代码。
稍后我再看看怎么处理这里问题

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/pull/2517
