### ISSUE TITLE
构建的时候能否先删除原来构建好的再生成新的

### ISSUE THREAD

**Issue by JamesCZF** [Tencent/wepy#2521]
现在是如果删除某个文件，构建的内容还是会有已经被删除的文件

**Comment by Gcaufy** [comment]
这个事情建议放在 build 中去做

```
"build": "rm -rf weapp/ && wepy build"
```

**Comment by mikasaYw** [comment]
正如作者所言 这种放在构建中去做
`"build": "rm -rf weapp && cross-env NODE_ENV=production ./node_modules/.bin/wepy build --no-cache",`

**Comment by JamesCZF** [comment]
谢谢
