### ISSUE TITLE
无法创建项目

### ISSUE THREAD

**Issue by bweib** [Tencent/wepy#2522]
创建项目一直报：
Failed to download repo standard:read ECONNRESET

搭了梯子也不行。

**Comment by bweib** [comment]
1.  npm install @wepy/cli@next -g
2.  wepy init standard myproject
第二步就不行了

**Comment by andyleftzhang** [comment]
同样问题

**Comment by Gcaufy** [comment]
这个通常都是网络问题。本身就是访问 github raw 内容。
可以用以下命令测试一下看看：
```
wget https://raw.githubusercontent.com/wepyjs/wepy-templates/2.0.x/README.md
```

**Comment by evan2020** [comment]
试了各种方法,一直报Failed to download repo standard:read ECONNRESET

**Comment by EuniceShaw** [comment]
请问你们解决这个问题了吗？

**Comment by lh9403** [comment]
同

**Comment by lgd8981289** [comment]
wepy 2.x 因为是 alpha 版本，所以一直不是很稳定，包括 init project。 建议依然使用 1.x 版本， 即 wepy-cli ，不要使用 @wepy/cli

**Comment by Gcaufy** [comment]
@evan2020 @EuniceShaw @lh9403 @lgd8981289 

测试一下这个命令
```
wget https://raw.githubusercontent.com/wepyjs/wepy-templates/2.0.x/README.md
```

**Comment by lh9403** [comment]
@Gcaufy 
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... 失败：Connection refused。
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|151.101.64.133|:443... 已连接。

wepy init standard myfolder
⠴ downloading template   wepy-cli · Failed to download repo standard: connect ECONNREFUSED 151.101.0.133:443

**Comment by Gcaufy** [comment]
@lh9403  这应该就是问题所在，无法访问 raw.githubusercontent.com.
如果是这样的话 vue-cli 应该也是用不了的。

**Comment by Gcaufy** [comment]
做了以下调整：
1. 添加了腾讯云的 COS 模板源
2. 下载优先访问腾讯云的模板源
3. 下载失败时访问 github raw 的模板源
4. 添加了更加详细的报错信息

**Comment by xo1988** [comment]
wepy小程序模版的下载地址是
https://raw.githubusercontent.com/wepyjs/wepy_templates/${branch}/zips/${templateName}.zip
根据自己想要的版本可以是
https://raw.githubusercontent.com/wepyjs/wepy_templates/2.0.x/zips/standard.zip

把这个下载到本地，然后用
wepy init 本地路径/standard 项目名来创建项目就行了

**Comment by Gcaufy** [comment]
```
$ npm install @wepy/cli@next -g
$ wepy -v
$ wepy init standard myproj --log verbose
```

添加 `--log verbose` 查看完整细节

**Comment by gzgogo** [comment]
不要使用淘宝镜像，将镜像切换回npm

**Comment by Hanson** [comment]
我设置了 npm 代理就可以了

`npm config set proxy=http://127.0.0.1:1080`

前提是你有代理就可以了
