### ISSUE TITLE
TypeError: Cannot read property '$rel' of undefined，在调用 initEvents(vm) 函数时报错

### ISSUE THREAD

**Issue by Kenquiet** [Tencent/wepy#2524]
在程序调用initEvents 函数时，vm 里面是没有 找不到$parent, 因此undefined
![image](https://user-images.githubusercontent.com/48983353/73632167-f56f3980-4695-11ea-8b8a-1ea2dbb232cd.png)
![image](https://user-images.githubusercontent.com/48983353/73632245-1768bc00-4696-11ea-8188-a40e444fd1b9.png)
希望能够尽快解决！谢谢！

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/blob/2.0.x/packages/core/weapp/init/lifecycle.js#L142-L160

只有子组件 Component 才会调用 initEvents, 而 子组件是一定存在 $parent 的。所以不应该出现这种 undefined 的情况 。

是否可以方便把 test case 发来我这边帮助定位 一下呢？

**Comment by Kenquiet** [comment]
我现在随便建立一个test 带有component 都是有问题的，跳转到子页面就会报这个错误，我现在都不确定是不是环境的问题了？
![image](https://user-images.githubusercontent.com/48983353/74118497-9ca02380-4bf6-11ea-9777-da270c98c03f.png)

**Comment by Kenquiet** [comment]
> https://github.com/Tencent/wepy/blob/2.0.x/packages/core/weapp/init/lifecycle.js#L142-L160
> 
> 只有子组件 Component 才会调用 initEvents, 而 子组件是一定存在 $parent 的。所以不应该出现这种 undefined 的情况 。
> 
> 是否可以方便把 test case 发来我这边帮助定位 一下呢？

![image](https://user-images.githubusercontent.com/48983353/74216443-73a78d80-4cdf-11ea-8a89-a3a6d477d667.png)
我进行了添加，就可以了，但是具体有什么影响我还不知道

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/blob/2.0.x/packages/core/weapp/init/lifecycle.js#L105

此处已处理~

**Comment by longjiahui** [comment]
我也遇到了这个问题
我发现 引用了这个子组件的父组件没有写script标签，写上并调用wepy.page({}) 就不报错了。
