### ISSUE TITLE
能否使用官方的 API TypeScript 声明？

### ISSUE THREAD

**Issue by fudiwei** [Tencent/wepy#2529]
官方本身提供了 [miniprogram-api-typings](https://github.com/wechat-miniprogram/api-typings)，但 wepy 2.x 本身内置的 TS 声明版本已经过旧、且项目中同时依赖两者的情况下只有 wepy2.x 的声明会生效，导致很多新的 API 会报错。

能否直接依赖官方的 TS 声明？

> REF: https://developers.weixin.qq.com/miniprogram/dev/extended/utils/api-typings.html

**Comment by Gcaufy** [comment]
建议使用官方 typings.

**Comment by fudiwei** [comment]
@Gcaufy 可是同时引入 `wepy` 和 `miniprogram-api-typings`，只有 `wepy` 内置的 TS 声明会生效，难道每个项目都需要去 node_modules 下把 `wepy` 的 TS 声明文件手动删掉吗？

能不能 `wepy` 就干脆别内置小程序 API 的 TS 声明了、仅仅只保留 wepy 自身框架所需的？

**Comment by Gcaufy** [comment]
这里 ts 的相关代码很久没有调整了，因为没有相应的使用场景。
不过非常欢迎 PR

**Comment by fudiwei** [comment]
@Gcaufy 已发 PR，辛苦 Review~
