### ISSUE TITLE
scss import后编译不过去

### ISSUE THREAD

**Issue by NiLinli** [Tencent/wepy#2531]
## Description

只要使用在 scss 中 @import 其他scss 就会编译不过去，卡在
[16:43:31] info build app start...

## Environment

    "@wepy/babel-plugin-import-regenerator": "0.0.2",
    "@wepy/cli": "^2.0.0-alpha.23",
    "@wepy/compiler-babel": "^2.0.1",
    "@wepy/compiler-sass": "^2.0.2",
    "@wepy/plugin-define": "^2.0.3",
  

## Relevant Code / Logs

  ```
  <style lang="scss">
  @import "./scss/variable"
  view {
    box-sizing: border-box;
  }

  .container {
    padding: $page-padding;
    background-color: $color1;
    min-height: 100vh;
  }
</style>
  ```

**Comment by xugongyang** [comment]
怎么解决的

**Comment by liuhongjian0316** [comment]
same question
