### ISSUE TITLE
wepy.request api 怎么用的

### ISSUE THREAD

**Issue by neozhu** [Tencent/wepy#2533]
Google 半天都是18年前的写法，而且现在版本的中都无法使用了，我现在只能用wx.request 代替，但wx.request() 不支持async / await 写法。
唉，官方的文档真的太简单了，更新也太慢了。

**Comment by weimingxinas** [comment]
https://github.com/Tencent/wepy/blob/2.0.x/packages/use-promisify/index.js#L171

**Comment by weimingxinas** [comment]
https://github.com/Tencent/wepy/blob/2.0.x/packages/use-promisify/index.js#L171

**Comment by weimingxinas** [comment]
https://github.com/Tencent/wepy/blob/2.0.x/packages/use-promisify/index.js#L171
可以看一下 use-promisify ，对部分wx的api的进行了promise的包装
wepy.wx.request 返回的是一个promise对象
```

import wepy from '@wepy/core';
import promisify  from '@wepy/use-promisify';
wepy.use(promisify);

// wepy.wx.getStorage({ key: 'mykey' });
wepy.wx.getStorage('mykey');

// wepy.wx.request({ url: myurl });
wepy.wx.request(myurl);

// wepy.wx.openLocation({ latitude: 0, longitude: 0 });
wepy.wx.openLocation(0, 0);
```

![image](https://user-images.githubusercontent.com/17585166/75090895-86a14400-55a2-11ea-8717-91f51719b17f.png)

**Comment by neozhu** [comment]
import promisify  from '@wepy/use-promisify';
编译错误
ERR! Can't resolve '@wepy/use-promisify' in '/Users/mac/Projects/wepytutorial/src'

**Comment by neozhu** [comment]
ok,搞定了，谢谢你的及时回复。非常感谢。

**Comment by weimingxinas** [comment]
npm install @wepy/use-promisify
