### ISSUE TITLE
在单独的js文件中封装了promise，引入函数时，undefined

### ISSUE THREAD

**Issue by wangkaiChen1118** [Tencent/wepy#2536]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  
  [Description of the issue]
  在单独的js文件中对 wepy.request() 做了promise的封装，在index.wepy中使用 import 引入，
此时引入的函数时undefined

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]  vscode 和 微信开发者工具
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号] 
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里] ^1.6.0
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]
1，在 api/index.js 封装了一个 post请求 的 promise
![image](https://user-images.githubusercontent.com/51146877/75406878-8f03d100-594c-11ea-9f73-838bee0839e3.png)

2，在 api/qpi.js 中放入请求
![image](https://user-images.githubusercontent.com/51146877/75406925-b6f33480-594c-11ea-8c8b-5e2c3c21b663.png)

3，在index.wepy 中引入使用 
![image](https://user-images.githubusercontent.com/51146877/75407066-0a658280-594d-11ea-8e75-f7c51e847f9e.png)

4，运行后，请求报错，显示这两个引入的函数为 undefined 
![image](https://user-images.githubusercontent.com/51146877/75407144-397bf400-594d-11ea-8d1b-370e669b8990.png)

5，在 onload() 生命周期中打印这两个函数，doush都是undefined
![image](https://user-images.githubusercontent.com/51146877/75407213-66300b80-594d-11ea-8f8d-3463e2d808f2.png)
![image](https://user-images.githubusercontent.com/51146877/75407224-6d571980-594d-11ea-93ad-c872ef9859ac.png)

6，再三检查了项目路径，附上项目结构和引入路径
![image](https://user-images.githubusercontent.com/51146877/75407250-7ea02600-594d-11ea-8cff-68089f1d82ca.png)

![image](https://user-images.githubusercontent.com/51146877/75407305-98da0400-594d-11ea-8b84-094160ad1fed.png)

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/75627430-06668880-5c0b-11ea-9b89-eabbe0e35268.png)

改成 export {} 吧。
或者修改 import 的引入方式。

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/import

**Comment by wangkaiChen1118** [comment]
> ![image](https://user-images.githubusercontent.com/2182004/75627430-06668880-5c0b-11ea-9b89-eabbe0e35268.png)
> 
> 改成 export {} 吧。
> 或者修改 import 的引入方式。
> 
> https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/import

感谢，之前还真不知道 export 和 export default 的区别 
 这是找了一篇文章  https://www.cnblogs.com/sherrycat/p/11152994.html
