### ISSUE TITLE
wepy2.0 怎么监听globalData里的userinfo变化

### ISSUE THREAD

**Issue by may6288** [Tencent/wepy#2537]
wepy2.0 怎么监听globalData里的userinfo变化？
页面上的接口要等到userinfo获取到了才能去加载数据。
琢磨了几天没搞定，网上也找不到相关资料，有些是wepy1.0的，根本不适用。

**Comment by neozhu** [comment]
感觉现在用wepy 开发问题很多，网上又找到对应的解决方法。看来是回到原始的开发工具吧

**Comment by Gcaufy** [comment]
不能直接监听 globalData 里的数据变化

这种情况需要换个思路去做

如：加个 mixin，检测登陆状态，登陆后触发一个页面事件

再或者使用 状态管理等

**Comment by may6288** [comment]
> 感觉现在用wepy 开发问题很多，网上又找到对应的解决方法。看来是回到原始的开发工具吧！
> 难道腾讯也还没有复工，

你说得对，wepy1.0生态还要好些，现在升级2.0了，文档又各种不齐全，网上也很少有相关技术文章，很多东西要自己去看1.0的然后自己琢磨再加揣测，我这个项目算是入坑了。

**Comment by neozhu** [comment]
> > 感觉现在用wepy 开发问题很多，网上又找到对应的解决方法。看来是回到原始的开发工具吧！
> > 难道腾讯也还没有复工，
> 
> 你说得对，wepy1.0生态还要好些，现在升级2.0了，文档又各种不齐全，网上也很少有相关技术文章，很多东西要自己去看1.0的然后自己琢磨再加揣测，我这个项目算是入坑了。

优点也是有的，使用vue，组件化的开发架构，和vscode的开发工具，就coding的效率是明显提高了，但微信小程序的 js 库还是不能完全兼容通用的js，比如axios，真希望腾讯的程序员能多加加班

**Comment by rongran** [comment]
最近的项目里采用了原生语法和wepy2混合开发的模式，在原生语法文件中获取wepy设置的globalData，需要用getApp().$wepy.$options.globalData

**Comment by zhushuanglong** [comment]
如果很想用globalData ,  这个方法 this.$root.$app.$options.globalData  可以的
