### ISSUE TITLE
this.$apply is not a function

### ISSUE THREAD

**Issue by neozhu** [Tencent/wepy#2539]
------------------------
## Description

 我在使用wepy.page onload 方法 或是wepy.component ready 方法 中调用this.$apply() 
异常
this.$apply is not a function;at "pages/index" page lifeCycleMethod onLoad function
TypeError: this.$apply is not a function
 这里顺便问一下为什么 wepy.component  onload 事件无法触发

## Environment

  * Platform: 最新版本
  * Platform version: 开发工具
  * Wechat version: 最新版本
  * wepy-cli version: 最新版本
  * wepy version: 最新版本
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
 
## Relevant Code / Logs

  ```
  onLoad() {
      this.draw()
      this.$apply()
    }
  ```

**Comment by Gcaufy** [comment]
2.0 无 $apply 方法
