### ISSUE TITLE
wepy.component onLoad 事件不会被触发

### ISSUE THREAD

**Issue by neozhu** [Tencent/wepy#2540]
使用的是最新的版本
"dependencies": {
    "@vant/weapp": "^1.0.6",
    "@wepy/core": "^2.0.0-alpha.9",
    "@wepy/x": "^2.0.2",
    "miniprogram-slide-view": "0.0.3",
    "weapp-qrcode": "^1.0.0",
    "wepy-async-function": "^1.4.7"
}
代码如下
  ```
wepy.component({
  store,
  props: {

  },
 onLoad() {
    console.log('onLoad')
  },
  ready() {
    console.log('ready')
  },
  created() {
    console.log('created')
  }
})
  ```

**Comment by nishino-tsukasa** [comment]
组件本来就没 onLoad

**Comment by neozhu** [comment]
那 在组件里 执行 this.$apply() 提示没有这个方法，我看文档中说都是有的，当然文档估计也是1.0以前的

**Comment by nishino-tsukasa** [comment]
看 2.0 的文档
https://wepyjs.github.io/wepy-docs/2.x/#/
