### ISSUE TITLE
关于微信开发者工具原生支持async/await的问题！

### ISSUE THREAD

**Issue by neozhu** [Tencent/wepy#2544]
目前最新版最新framwork都是支持async/await 
但必须把ES6 to ES5 的勾去掉，可微信小程序框架提供wx.request 任然不支持 await的写法，
网上有人用promise封装了可以实现，但如果用比较流行 axios这个 adapter 又和ES6 to ES5 有冲突，axios adapter 必须ES6 to ES5 打勾了才能用，一打勾原生的async/await 关键字又不能用了。
强烈建议，既然微信小程序支持了async/await 那么能不能让wx.request也支持await 的调用。
当然最新的wepy 下面是原生支持async/await 包括wepy.wx.request,但还是很不稳定，总有莫名其妙的问题又找不到解决方法，很郁闷，只能用原始的开发者工具做开发。
希望能得到大家的帮助

**Comment by Gcaufy** [comment]
你使用的版本是？

**Comment by neozhu** [comment]
我知道问题了，已经解决，没有开启增强编译
