### ISSUE TITLE
自定义组件事件无法获取父组件传递的参数

### ISSUE THREAD

**Issue by JamesCZF** [Tencent/wepy#2545]
@amount-tap="onAmountTap($event, storeIndex, goodsIndex)"
类似这样

vue是可以这样的

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/pull/2538

这个问题在讨论中。

**Comment by Gcaufy** [comment]
这里 PR 已处理完成


```
npm i @wepy/cli@2.0.0-alpha.26 --save-dev
npm i @wepy/core@2.0.0-alpha.15 --save
```

文档如下：

https://wepyjs.github.io/wepy-docs/2.x/#/base/event
https://wepyjs.github.io/wepy-docs/2.x/#/component/event
