### ISSUE TITLE
2.0打包遗漏wxml

### ISSUE THREAD

**Issue by superlbr** [Tencent/wepy#2546]
以vant-weapp为例，1.0.7中, picker组件中的toolbar.wxml。
由于未识别这种wxml依赖，会导致toolbar.wxml打包时遗漏

**Comment by aymfx** [comment]
``` html
VM26:1 ./components/vant/picker/index.wxml
 Path `./toolbar.wxml` not found from `./components/vant/picker/index.wxml`.
   7 | </wxs>
   8 | <!----------   wxs end   ----------->
>  9 | <import src="./toolbar.wxml" />
     |  ^
  10 | 
  11 | <view class="van-picker custom-class">
  12 |   <template is="toolbar" wx:if="{{ toolbarPosition === 'top' }}" data="{{ showToolbar, cancelButtonText, title, confirmButtonText }}"></template>
```
我也遇到了 ，我现在只能先把toolbar直接放到文件中了，望解决

**Comment by Gcaufy** [comment]
@aymfx 能给到一个可以复现 的包么？
我这里看到的是另外一个错误

**Comment by superlbr** [comment]
https://github.com/superlbr/wepy-vant

**Comment by Gcaufy** [comment]
看到这里用 static 的方式引入，挺不错的。

文件缺失的问题我去定位 看看。

**Comment by zgia** [comment]
遇到同样的问题，也是使用的临时解决办法：把toolbar直接放到index文件中。

我还在这里提了一个issue： https://github.com/youzan/vant-weapp/issues/2994

**Comment by yahon** [comment]
用了wepy和vant 各种踩吭啊

**Comment by Gcaufy** [comment]
这个是因为 vant 组件里使用了 template/ import 语句。而 wepy 本身是不支持 template/ import 的。
因此这个现在还没办法处理。
这里先关掉这个 issue, 新开一个 feature issue 去支持 template / import 吧。参考这里： https://github.com/Tencent/wepy/issues/2577

现阶段，对于这个问题的处理建议是将 vant 放入 static，不需编译直接拷贝至输出目录

```
npm i @vant/weapp
cp -r node_modules/@vant/weapp ./static/@vant/weapp
```

**Comment by Asher-Ding** [comment]
遇到了同样的问题，我导入的tdesign，这都2023了，还没有解决吗？
