### ISSUE TITLE
编译后在微信开发者工具显示 'xxx' is not defined

### ISSUE THREAD

**Issue by TonyLiuYan** [Tencent/wepy#2548]
版本："wepy": "^1.7.2"

截图信息
![image](https://user-images.githubusercontent.com/12442097/76718256-19cc3480-6771-11ea-92b8-ebd57ff81a40.png)

**Comment by Gcaufy** [comment]
是不是编译出错了，建议重新编译看看？

**Comment by TonyLiuYan** [comment]
> 是不是编译出错了，建议重新编译看看？

编译没有出错，程序可以正常运行，猜测应该是eslint的设置问题，但是初始化程序后不应该这样啊

**Comment by Gcaufy** [comment]
这个是 eslint 的问题，并且我重新初始化了一个小程序，并无法复现问题
