### ISSUE TITLE
如何动态更新data中的属性，并实时反映到视图上

### ISSUE THREAD

**Issue by zgia** [Tencent/wepy#2557]
## Description

假设data有个属性 a：
```
wepy.page({
  data: {
    a: {}
  },
  sayHi: function () {
    this.a.hi  = 'hello world'
  }
})
```

希望调用**sayHi**时，视图可以显示**hello world**。

https://wepyjs.github.io/wepy-docs/2.x/#/base/instance?id=%e6%95%b0%e6%8d%ae%e4%b8%8e%e6%96%b9%e6%b3%95

链接中说“需要设置一些初始值”，不过项目中有些属性是延迟生成的。在这种情况下，如何做到实时更新呢？

wepy2已经取消了$apply，有其他方法吗？

## Environment

  * Platform: [开发者工具]
  * Platform version: [RC v1.02.2003121]
  * Wechat version: [7.0.12]
  * wepy-cli version: [2.0.0-alpha.26]
  * wepy version: [2.0.0-alpha.26]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

```
wepy.page({
  data: {
    a: {}
  },
  sayHi: function () {
    this.a.hi  = 'hello world'
  }
})
```

### Observed Results

无法获取到 this.a.hi 的值
  
### Expected Results

期望可以动态更新  this.a.hi 的值，并反映到视图上

## Relevant Code / Logs

  无

**Comment by weimingxinas** [comment]
try it
```
this.$set(this.a, 'hi', 'helloworld')
```

**Comment by zgia** [comment]
`this.$set(this.a, 'hi', 'helloworld')`

搞定了，多谢多谢
