### ISSUE TITLE
wepy-redux里如何使用context？

### ISSUE THREAD

**Issue by kiradea** [Tencent/wepy#2566]
RT

**Comment by Gcaufy** [comment]
可以这里说明一下问题答案，以帮助其它有类似问题的人。

**Comment by Demo-lcj** [comment]
wepy怎么优雅的使用weui组件库



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gcaufy"<notifications@github.com&gt;; 
发送时间: 2020年4月14日(星期二) 上午10:13
收件人: "Tencent/wepy"<wepy@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [Tencent/wepy] wepy-redux里如何使用context？ (#2566)





 
可以这里说明一下问题答案，以帮助其它有类似问题的人。

**Comment by Gcaufy** [comment]
@Demo-lcj 与此issue 无关。
