### ISSUE TITLE
请问能用框架开发组件，将编译后的组件页面，直接给原生的小程序调用吗？

### ISSUE THREAD

**Issue by z-lionel** [Tencent/wepy#2567]
如题将开发编译后，在weapp文件夹里面的组件， 能在原生的小程序直接调用吗？有提供这个功能吗？

我测试了一下好像是不能直接调用的，
比如组件传值，在weapp里面传递的是prop，但是在原生小程序里面是用的properties。

想达到的目的是想用wepy开发个原生小程序组件，直接提供给第三方使用

**Comment by weimingxinas** [comment]
wepy的组件也可以用properties

**Comment by Gcaufy** [comment]
依赖于 wepy core. 所以不用，除非你把调用的 wepy core 的方法抽出来。

**Comment by z-lionel** [comment]
好的，谢谢各位
