### ISSUE TITLE
ext.json 会自动拷贝吗？

### ISSUE THREAD

**Issue by yokingma** [Tencent/wepy#2568]
## Description
微信第三方平台开发小程序需要ext.json 文件，目前我在项目/src目录下创建ext.json 编译后**不会自动拷贝到小程序项目根目录。**
考虑到通过wepy.config.js配置文件设置static实现，但是static不支持拷贝单个静态文件吧？

## Environment
  * wepy-cli version: 2.0.0-alpha.20
  * wepy version: 2.0.0-alpha.14

**Comment by fudiwei** [comment]
支持的。

**Comment by Gcaufy** [comment]
建议通过 static 属性去配置。
static 属性目前只支持文件夹拷贝，不支持文件拷贝。已修复，在下一个版本中支持到。
