### ISSUE TITLE
wepy-cli 全局安装后, 不能 init项目?

### ISSUE THREAD

**Issue by OldKwan** [Tencent/wepy#2572]
之前都是用mpvue开发, 打算周末好好补一下 wepy的知识, 结果 wepy-cli全局安装好了, init项目时候却失败, 上网百度了好久也没有解决方法;

然后在 github下载了个基于 wepy的项目, 打算借人家的壳学习; 结果还是不行, start的时候报错;

回归正题, 其实本质问题时 wepy init empty/standard name 报错了(笔记本和台式电脑都是一样的报错); 希望能尽快解决
```js
D:\code-demo\wepy-demo>wepy -v
1.7.3

D:\code-demo\wepy-demo>wepy init empty mydemo
| downloading template   wepy-cli · Failed to download repo empty: getaddrinfo ENOENT raw.githubusercontent.com
```

**Comment by superlbr** [comment]
看[文档](https://wepyjs.github.io/wepy-docs/2.x/#/base/getstart)
```
$ npm install @wepy/cli -g # 全局安装 WePY CLI 工具
$ wepy init standard myproj # 使用 standard 模板初始化项目
$ cd myproj # 进入到项目目录
$ npm install # 安装项目依赖包
$ npm run dev # 监听并且编译项目
```

**Comment by TDcloud** [comment]
> 之前都是用mpvue开发, 打算周末好好补一下 wepy的知识, 结果 wepy-cli全局安装好了, init项目时候却失败, 上网百度了好久也没有解决方法;
> 
> 然后在 github下载了个基于 wepy的项目, 打算借人家的壳学习; 结果还是不行, start的时候报错;
> 
> 回归正题, 其实本质问题时 wepy init empty/standard name 报错了(笔记本和台式电脑都是一样的报错); 希望能尽快解决
> 
> ```js
> D:\code-demo\wepy-demo>wepy -v
> 1.7.3
> 
> D:\code-demo\wepy-demo>wepy init empty mydemo
> | downloading template   wepy-cli · Failed to download repo empty: getaddrinfo ENOENT raw.githubusercontent.com
> ```

楼主解决了吗？遇到同样的问题了

**Comment by OldKwan** [comment]
@TDcloud 并没有, 刚刚重新安装了 wepy-cli 还是一样不行, 之前加了 wepy 微信群; 我询问一下, 有答复了回你
error msg: 
C:\Users\Administrator\Desktop\code-word>wepy init standard demowepy
/ downloading template   wepy-cli · Failed to download repo standard: getaddrinfo ENOENT raw.githubusercontent.com

**Comment by OldKwan** [comment]
@TDcloud 刚解决了, 首先没找到问题所在; 只是按照官网重装了一遍 [链接](https://wepyjs.github.io/wepy-docs/2.x/#/base/getstart)
```js
$ npm install @wepy/cli -g # 全局安装 WePY CLI 工具
$ wepy init standard myproj # 使用 standard 模板初始化项目
$ cd myproj # 进入到项目目录
$ npm install # 安装项目依赖包
$ npm run dev # 监听并且编译项目
```
应该是官方更新了

> 当然, 你要是还不行可以去我GitHub clone一份 链接[https://github.com/OldKwan/wepy-init](url)

**Comment by OldKwan** [comment]
> 看[文档](https://wepyjs.github.io/wepy-docs/2.x/#/base/getstart)
> 
> ```
> $ npm install @wepy/cli -g # 全局安装 WePY CLI 工具
> $ wepy init standard myproj # 使用 standard 模板初始化项目
> $ cd myproj # 进入到项目目录
> $ npm install # 安装项目依赖包
> $ npm run dev # 监听并且编译项目
> ```

谢谢, 刚解决了

**Comment by OldKwan** [comment]
> > 之前都是用mpvue开发, 打算周末好好补一下 wepy的知识, 结果 wepy-cli全局安装好了, init项目时候却失败, 上网百度了好久也没有解决方法;
> > 然后在 github下载了个基于 wepy的项目, 打算借人家的壳学习; 结果还是不行, start的时候报错;
> > 回归正题, 其实本质问题时 wepy init empty/standard name 报错了(笔记本和台式电脑都是一样的报错); 希望能尽快解决
> > ```js
> > D:\code-demo\wepy-demo>wepy -v
> > 1.7.3
> > 
> > D:\code-demo\wepy-demo>wepy init empty mydemo
> > | downloading template   wepy-cli · Failed to download repo empty: getaddrinfo ENOENT raw.githubusercontent.com
> > ```
> 
> 楼主解决了吗？遇到同样的问题了

@TDcloud 刚解决了, 首先没找到问题所在; 只是按照官网重装了一遍 链接

$ npm install @wepy/cli -g # 全局安装 WePY CLI 工具
$ wepy init standard myproj # 使用 standard 模板初始化项目
$ cd myproj # 进入到项目目录
$ npm install # 安装项目依赖包
$ npm run dev # 监听并且编译项目
应该是官方更新了

当然, 你要是还不行可以去我GitHub clone一份 链接https://github.com/OldKwan/wepy-init

**Comment by TDcloud** [comment]
> > > 之前都是用mpvue开发，打算周末好好补一下wepy的知识，结果wepy-cli分段安装好了，init项目时候却失败，上网百度了好久也没有解决方法; 
> > > 然后在github下载了一个基于wepy的项目，打算借人家的壳学习; 结果还是不行，start的时候报错; 
> > > 回归正题，实质上本质问题时wepy init empty / standard name报错了（笔记本和台式电脑都是一样的报错）; 希望能尽快解决
> > > ```js
> > > d ： \码-演示\ wepy -演示> wepy - v
> > >  1.7。3
> > > 
> > > D ： \ code - demo \ wepy - demo > wepy初始化为空mydemo
> > >  | 正在下载模板wepy - cli·无法下载仓库为空： getaddrinfo ENOENT  raw。githubusercontent。com
> > > ```
> > 
> > 
> > 楼主解决了吗？遇到同样的问题了
> 
> @TDcloud刚解决了，首先没找到问题所在; 只是按照官网重装一遍遍链接
> 
> $ npm install @ wepy / cli -g＃批量安装WePY CLI工具
> $ wepy init standard myproj＃使用标准模板初始化项目
> $ cd myproj＃进入到项目目录
> $ npm install＃安装项目依赖包
> $ npm run dev＃监听并编译项目
> 应该是官方更新了
> 
> 当然，你要是还不行可以去我GitHub clone链接https://github.com/OldKwan/wepy-init

我找了很久找到办法解决的：
其原因都是连不上 Github 的服务器
解决方法（三选一，最后一个方法一定可以）：

如果你是用的移动的网络，请更换至电信或者联通的网络重试
使用全局代理（梯子）
手动下载 wepy 的初始化 template
wepy 小程序模版的下载地址是
https://raw.githubusercontent.com/wepyjs/wepy_templates/${branch}/zips/${templateName}.zip
那么对应的 standard 模板的下载地址是（假设你要用 2.0.x 的版本）
https://raw.githubusercontent.com/wepyjs/w...
下载到本地后解压
wepy init 本地路径/standard 项目名 即和 wepy init standard 项目名 效果相同

**Comment by Gcaufy** [comment]
wepy init 后面做了优化，优先使用 github 模板，如果网络不通的话会去切换至腾讯云上的 cos 模板。

如果init 还是有问题的话就看看
1. 是不是到 github 网络不通 （可 curl github raw 文件测试），解决办法就是翻墙。
2. 是不是最新版本的 cli ，`wepy -v`查看。只有最新版本 cli 才支持腾讯 云 cos 模板

**Comment by TDcloud** [comment]
> wepy init 后面做了优化，优先使用 github 模板，如果网络不通的话会去切换至腾讯云上的 cos 模板。
> 
> 如果init 还是有问题的话就看看
> 
> 1. 是不是到 github 网络不通 （可 curl github raw 文件测试），解决办法就是翻墙。
> 2. 是不是最新版本的 cli ，`wepy -v`查看。只有最新版本 cli 才支持腾讯 云 cos 模板

全局外网都不可以init,这就是个问号

**Comment by chris-shao30** [comment]
downloading template   wepy-cli · Failed to download repo standard: certificate has expired

**Comment by Gcaufy** [comment]
@TDcloud 
新项目使用 2.0 试试

**Comment by Gcaufy** [comment]
@chris-shao30 你的版本是？

**Comment by TDcloud** [comment]
安装不上用起来比较麻烦，目前原生了，到时候再试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gcaufy"<notifications@github.com&gt;; 
发送时间: 2020年5月16日(星期六) 晚上8:38
收件人: "Tencent/wepy"<wepy@noreply.github.com&gt;; 
抄送: "BaiYongYu"<yongyubai@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Tencent/wepy] wepy-cli 全局安装后, 不能 init项目? (#2572)





 
@TDcloud
 新项目使用 2.0 试试
