### ISSUE TITLE
【Feature】WePY wxml 支持 template / import 语法

### ISSUE THREAD

**Issue by Gcaufy** [Tencent/wepy#2577]
原计划是不需要支持此语法的，使用组件完全可以实现 template / import 的全部功能。

但因为需多第三方组件可能会依赖这个特性，因此还是考虑支持这个特性。

https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html

**Comment by endsh** [comment]
wxml 没有支持编译原有的语法么？

**Comment by ManfredHu** [comment]
求问这个特性支持了吗？

**Comment by aaaaa1414514** [comment]
@wepy/cli@2.1.0-alpha.11 版本
使用腾讯trtc-room 原生组件   
import的组件打包遗漏
