### ISSUE TITLE
无法上报日志，wx.getRealtimeLogManager无效

### ISSUE THREAD

**Issue by xingkai17** [Tencent/wepy#2582]
## Description

 微信小程序有上报日志的api，使用原生开发是可以上报日志的，但是用wepy2无法上报日志
https://developers.weixin.qq.com/miniprogram/dev/api/base/debug/wx.getLogManager.html

## Environment

  * Platform: 开发者工具
  * Platform version: 1.03.2005141
  * Wechat version: 基础库2.11.0
  * wepy-cli version: 2.0.x
  * wepy version: 2.0.0-alpha.16
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

在入口文件app.wpy，onLaunch生命周期中添加wx.getRealtimeLogManager().info('234')方法

### Observed Results

network 中没有发现有上报日志
  
### Expected Results

希望和微信小程序原生一样可以使用wx.getRealtimeLogManager()上报日志
  

## Relevant Code / Logs
这是用wepy2中使用wx.getRealtimeLogManager()的代码片段：
https://developers.weixin.qq.com/s/yuO0JymL7phk

这是微信小程序官方提供的上报日志的代码片段：https://developers.weixin.qq.com/s/aFYw1BmC7eak

**Comment by Gcaufy** [comment]
你上面的代码片段无法说明问题，
wepy 是上报放在 app onLaunch 中，而原生的放在跳转的 onLoad 中。
我把原生小程序的代码片段的 log 方法放在 onLaunch 当中，原生也没有发现上报。

另外， wepy 是非侵入的。不会改变 wx 原生 api. 原来 api 什么效果他就应该是什么效果
