### ISSUE TITLE
自定义组件，vm.$parent没有导致报错

### ISSUE THREAD

**Issue by chinagzcp** [Tencent/wepy#2583]
在issues里看到有人提，说已经解决了，但是还是有这个bug啊.
vm的$app也出现找不到
还有经常出现警告， does not have a method "__initComponent" to handle event "_init".

**Comment by Gcaufy** [comment]
把 cli 版本和 core 的版本贴出来看看。

**Comment by chinagzcp** [comment]
"@wepy/core": "^2.0.0-alpha.14",
"@wepy/cli": "^2.0.0-alpha.25",

**Comment by chinagzcp** [comment]
导致这个问题的原因就是 initComponent没调用，我看了生成的wxml，上面是又bind_init="__initComponent"的，为啥就触发不了呢

**Comment by chinagzcp** [comment]
不好意思，我昨晚升级了这两个版本的，没删掉weapp, 似乎不起效，现在我删掉了编译的后的weapp,重新编译，就不报错了
