### ISSUE TITLE
wepy1.7.2转百度小程序 tabbar报错

### ISSUE THREAD

**Issue by qilovehua** [Tencent/wepy#2584]
<img width="493" alt="bd" src="https://user-images.githubusercontent.com/12076175/83245930-00fde780-a1d4-11ea-8fd4-7e21cd2a822b.png">
转微信小程序是正常的，转成百度小程序，报错编译不过（如图）。
有大神知道怎么解决吗？

```
    "redux": "^3.7.2",
    "wepy": "^1.7.2",
    "wepy-baidu": "^1.7.2-alpha3",
    "wepy-redux": "^1.5.9"
```

**Comment by qilovehua** [comment]
[baidu.zip](https://github.com/Tencent/wepy/files/4701145/baidu.zip)
上传代码，yarn start后用百度开发工具打开dist

**Comment by Gcaufy** [comment]
1.7.2 没有维护转百度小程序的功能。

**Comment by qilovehua** [comment]
@Gcaufy 
2.0.0有的吗？我可以升级的
