### ISSUE TITLE
创建项目的时候报错  connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by PoorBE** [Tencent/wepy#2588]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
使用wepy init standard cc 创建项目的时候报错
   downloading template   wepy-cli · Failed to download repo standard: connect ECONNREFUSED 127.0.0.1:443
  [Description of the issue]

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]1.7.3
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]

**Comment by Gcaufy** [comment]
```
ECONNREFUSED 127.0.0.1:443
```

报错提示无法连接到本地的443端口。所以看看是不是配置了本机代理。

**Comment by kiradea** [comment]
try this! ,It work to me
https://blog.csdn.net/weixin_38674371/article/details/105990449

**Comment by kiradea** [comment]
@PoorBE Have you solve it ? check up comment

**Comment by Gcaufy** [comment]
2.0 的版本应该没有了这个问题。

**Comment by PoorBE** [comment]
> @PoorBE你解决了吗？检查评论

OK了
