### ISSUE TITLE
wepy 1.7 版本 是否有强制竖屏的"deviceOrientation":"po"，

### ISSUE THREAD

**Issue by agoodcoolman** [Tencent/wepy#2603]
wepy 中有[强制竖屏]的配置吗，我都没找到。(https://developers.weixin.qq.com/miniprogram/dev/framework/view/resizable.html)

"deviceOrientation":"landscape"， 这个配置要放在哪里，我都没收到。

**Comment by Gcaufy** [comment]
这个和 wepy 无关，是小程序配置，正常放在对应的 config 中即可
