### ISSUE TITLE
使用pug后，模板中的条件判断if里，使用"&"符号会被错误转义成"&amp;"

### ISSUE THREAD

**Issue by xiexiaotian9527** [Tencent/wepy#2612]
## Description

  [问题描述：使用pug后，模板中的条件判断if里，使用"&"符号会被错误转义成"\&amp;"]
  

## Environment

  * Platform: [开发者工具]
  * wepy-cli version: ^2.0.0-alpha.20
  * wepy version: 0.0.2
  * other version: "@wepy/compiler-pug": "https://github.com/Riant/wepy2-compiler-pug.git#master"
  
## Reproduce

 [如何重现问题]
wpy文件内：
`view(v-if='a && b')`

### Observed Results

  [实际表现]
编译后的wxml文件中：
  `<view wx:if="{{ a &amp;&amp; b }}"></view>`

### Expected Results

  [期望表现]
希望编译后"&"符号不被转义成“ \&amp;”
  `<view wx:if="{{ a && b }}"></view>`

**Comment by chenyu445** [comment]
PUG 官方文档里面有，这个问题是一个普遍现象。解决方案是 在解析时前面增加!符号 
`
 #错误示例
div.class(v-if = " expressionA && expressionA ")

#正确写法
div.class(v-if != " expressionA && expressionA ")
`

这个问题也有pr正在处理
#2600
