### ISSUE TITLE
有关wepy1.7构建2.0的问题？

### ISSUE THREAD

**Issue by lzhsus** [Tencent/wepy#2614]
![image](https://user-images.githubusercontent.com/27983884/84874391-19687000-b0b7-11ea-912e-cd5f2497263b.png)
![image](https://user-images.githubusercontent.com/27983884/84874422-24bb9b80-b0b7-11ea-8988-3ad8cfeb4002.png)
![image](https://user-images.githubusercontent.com/27983884/84874440-2c7b4000-b0b7-11ea-99a4-e96b7f604ff8.png)

**Comment by Gcaufy** [comment]
报错说得比较清楚了 网络问题导致的。。
两种办法，
1 是用代理
2 是升级最新版，最新版在 github 网络不通时切换至腾讯云 cos
