### ISSUE TITLE
wepy1.7中无法直接使用 this.animate()

### ISSUE THREAD

**Issue by guorouxp** [Tencent/wepy#2616]
## 环境：
* wepy1.7
* 微信开发工具 1.02
* 调试基础库 2.11.1

## 无法直接调用 this.animate() 接口
报错信息：
```
this.animate is not a function;
```

检查微信文档，原生版本只需要2.9之后的版本之后就可以使用

需要使用 this.$wxpage.animate() 才能正常使用该接口，求更新

**Comment by Gcaufy** [comment]
请使用
```
this.$wxpage.animate()
```

**Comment by guorouxp** [comment]
> 请使用
> 
> ```
> this.$wxpage.animate()
> ```

好的，谢谢。
