### ISSUE TITLE
wepy框架 小程序在pc windows上报错 mac上运行正常

### ISSUE THREAD

**Issue by zhuweilong** [Tencent/wepy#2623]
wepy框架 小程序在pc windows上报错 mac上运行正常

**Comment by Gcaufy** [comment]
有更具体一点的描述吗？

**Comment by zhuweilong** [comment]
可能是运行时环境不同吧  在windows上报运行打包npm目录里 __microtask.js有个 var node = document.createTextNode('');报createTextNode 未定义， 显然是没有document， 如果删除这个把node 赋值为 ' ', 还会报别的错

**Comment by Gcaufy** [comment]
1.7 的版本吗？

是引入了不兼容的 npm 包吧。小程序端是无法使用 document 的。

**Comment by zhuweilong** [comment]
是1.7版本 但是我升级了cli 2.x版本 就init 生成一个demo 直接在windows 运行也是报错

**Comment by Gcaufy** [comment]
@zhuweilong 有截图吗？请提供更多有效信息，不然我们无法去定位 。

2.x init 出来的 demo 应该是不会有问题的

**Comment by zhuweilong** [comment]
@Gcaufy 你们就init 一个项目 在windows上的 开发者工具上 选启动pc自动预览 应该会报错的

**Comment by zhuweilong** [comment]
@Gcaufy 2.1.0-alpha.7 我用的版本

**Comment by weimingxinas** [comment]
window下wepy-cli1.7.3执行
```
wepy init standard myapp
```
是正常的呢。
报什么错呢？有截图么？ @zhuweilong

**Comment by zhuweilong** [comment]
@weimingxinas app-service.js: TypeError: Cannot read property 'createTextNode' of undefined
at module.exports (file://7.js/:13408:477)
at file://7.js/:13640:378
at file://7.js/:13640:3658
at require (file://6.js/:2:1720385)
at file://6.js/:2:1719995
at file://7.js/:13216:140
at require (file://6.js/:2:1720385)
at file://6.js/:2:1719995
at file://7.js/:13088:25
at require (file://6.js/:2:1720385)
这是在微信pc windows上报的错
我认为是transform-runtime里的core的js文件报的错 document是不存在的
为啥mac就能运行正常呢

**Comment by Gcaufy** [comment]
因为使用了不当的 npm 包导致的问题。该问题已在微信中沟通清楚了。
