### ISSUE TITLE
wepy2如果.wpy文件引入了.wxss样式文件，则直接会把编译进程卡没了

### ISSUE THREAD

**Issue by Bulandent** [Tencent/wepy#2651]
wepy2如果.wpy文件引入了.wxss样式文件，这个时候再去终端执行 `npm run dev`：
控制台会有如下输出：

``` 
> zzodr-wx@0.0.2 dev /Users/ccp/Sites/zzodr-wx-new
> cross-env NODE_ENV=dev ./node_modules/.bin/wepy build --watch
[14:10:46] info build app start...
[14:10:48] info app building App
ccp:zzodr-wx-new ccp$ 
```
然后编译进程就会突然停止。且 `weapp` 目录下只生成了3个文件：`app.js`、`app.json` 和 `app.wxss`。
如果把引入的 `.wxss` 注释掉，则能正常编译。

**Comment by Gcaufy** [comment]
引入代码是？

**Comment by Bulandent** [comment]
> 引入代码是？

随便引入一个 `wxss` 文件都会呀，比如在 `app.wpy`：
``` css
<style lang="scss" type="text/scss">
@import './styles/aaa.wxss';
</style>
```
`aaa.wxss` 内容：
``` css
.bg {
    background-color: #fff;
}
```

**Comment by FreeRide-Joe** [comment]
> > 引入代码是？
> 
> 随便引入一个 `wxss` 文件都会呀，比如在 `app.wpy`：
> 
> ```css
> <style lang="scss" type="text/scss">
> @import './styles/aaa.wxss';
> </style>
> ```
> 
> `aaa.wxss` 内容：
> 
> ```css
> .bg {
>     background-color: #fff;
> }
> ```

将style标签里 `lang="scss" type="text/scss"` 去掉即可，这样 引入的 wxss 会直接复制进 `app.wxss`中

**Comment by Bulandent** [comment]
> > > 引入代码是？
> > 
> > 
> > 随便引入一个 `wxss` 文件都会呀，比如在 `app.wpy`：
> > ```css
> > <style lang="scss" type="text/scss">
> > @import './styles/aaa.wxss';
> > </style>
> > ```
> > 
> > 
> > `aaa.wxss` 内容：
> > ```css
> > .bg {
> >     background-color: #fff;
> > }
> > ```
> 
> 将style标签里 `lang="scss" type="text/scss"` 去掉即可，这样 引入的 wxss 会直接复制进 `app.wxss`中

不能去掉呀，就是全局的样式有 `scss` 的，也有 `wxss` 的，所以都希望引入。
不过我现在的做法是写了2个 `style` 也是能解决问题:
``` css
<style lang="scss" type="text/scss">
@import "./btn.scss";
</style>

<style lang="wxss" type="text/wxss">
@import "./icon.wxss";
</style>
```

**Comment by Riant** [comment]
@Bulandent 
本来就是这么分开玩的哈。

**Comment by Gcaufy** [comment]
scss 是无法识别` import './xxxx.wxss' `的
