### ISSUE TITLE
onShareTimeline 里 return 的结果无效

### ISSUE THREAD

**Issue by DanielChan27** [Tencent/wepy#2653]

**Comment by Gcaufy** [comment]
如何使用的？是否可以给出 demo code?

**Comment by 986990092** [comment]
onShareTimeline() {
      return {
        title: '分享到朋友圈',
        query: '?type=2333',
        imageUrl: 'https://avatars0.githubusercontent.com/u/14899145?s=80&v=4'
      }
    }
就官网的这种写法

**Comment by weimingxinas** [comment]
@986990092 @DanielChan27 
![image](https://user-images.githubusercontent.com/17585166/87906601-85167200-ca95-11ea-85f8-a443de273d44.png)
小程序文档上，该接口需要 基础库2.11.3，并且只支持安卓呢。看下是否满足这两个条件？

**Comment by Gcaufy** [comment]
@DanielChan27 @986990092 

这个函数在 wepy 中现在还不存在： https://github.com/Tencent/wepy/blob/master/packages/core/shared/constants.js
这个我们后面迭代中加上。

可以考虑使用这个生命周期补充的方式给他添加上试试看

https://wepyjs.github.io/wepy-docs/2.x/#/base/instance?id=%e7%94%9f%e5%91%bd%e5%91%a8%e6%9c%9f%e5%87%bd%e6%95%b0%e8%a1%a5%e5%85%85%e4%b8%8e%e4%bf%ae%e6%94%b9

**Comment by qilovehua** [comment]
1.7.2的能加下吗？ @Gcaufy

**Comment by Gcaufy** [comment]
@qilovehua  可以的.

1 的方式不太一样，
在 wepy.config 中配置 `appConfig` 

https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy-cli/src/compile-script.js#L277

https://github.com/Tencent/wepy/blob/1.7.x/packages/wepy/src/base.js#L111

**Comment by lubobill1990** [comment]
@Gcaufy 我在 wepy.config.js 中的 appConfig 里添加了`pageEvents: ['onShareTimeline'],`，不起作用，仍然显示当前页面未设置分享。可以详细描述解决方案吗？

**Comment by lubobill1990** [comment]
> 1.7.2的能加下吗？ @Gcaufy

我看你在下面点了赞，请问你是怎么解决问题的呢？

**Comment by qilovehua** [comment]
@lubobill1990 
我试了是有用的。
把dist目录删了，重新yarn start；
把微信开发者工具关了，重新打开。

**Comment by lubobill1990** [comment]
> @lubobill1990
> 我试了是有用的。
> 把dist目录删了，重新yarn start；
> 把微信开发者工具关了，重新打开。

感谢。我发现是被开发者工具坑了，我在手机上预览就能显示分享到朋友圈，在开发者工具里就不行。

**Comment by qilovehua** [comment]
如果有页面不希望开启朋友圈分享，
需要修改源码 /node_modules/wepy/lib/base.js
```
  if (!page.onShareAppMessage) {
    delete config.onShareAppMessage
  }
  
  // 新增
  if (!page.onShareTimeline) {
    delete config.onShareTimeline;
  }
```

**Comment by SamWan9** [comment]
> @DanielChan27 @986990092
> 
> 这个函数在 wepy 中现在还不存在： https://github.com/Tencent/wepy/blob/master/packages/core/shared/constants.js
> 这个我们后面迭代中加上。
> 
> 可以考虑使用这个生命周期补充的方式给他添加上试试看
> 
> https://wepyjs.github.io/wepy-docs/2.x/#/base/instance?id=%e7%94%9f%e5%91%bd%e5%91%a8%e6%9c%9f%e5%87%bd%e6%95%b0%e8%a1%a5%e5%85%85%e4%b8%8e%e4%bf%ae%e6%94%b9

lifecycle: {
    page: ['onShareTimeline']
  },

app里加了这段代码也不行

**Comment by iniaks** [comment]
用2.0.x的，试着把onShareTimeline方法写到methods下面，而不是写到page的生命周期里面
