### ISSUE TITLE
reqiure.context都没有了

### ISSUE THREAD

**Issue by happyqu** [Tencent/wepy#2654]
如题

**Comment by huhansome** [comment]
阿里云服务器，限时秒杀价低至102/年
http://weibo.ws/zZNbxG

阿里云企业级服务器1折限时特惠
http://weibo.ws/SIyDRE

阿里云建站 速成美站 - 千套模板，价格低至500元
http://weibo.ws/yVQAYW

**Comment by Gcaufy** [comment]
@happyqu 有没有更详细一点的说明 ？
