### ISSUE TITLE
wepy 文档页面无法打开

### ISSUE THREAD

**Issue by jayxiangnan** [Tencent/wepy#2676]
wepy文档页面 无法打开
ERR_CONNECTION_REFUSED

wepy init 初始化项目也无法创建
failed: 貌似也是CONNECTION_REFUSED的原因

**Comment by carrieguo** [comment]
也遇到了这个问题，wepy服务器在哪呀是不是被和谐掉了

**Comment by chenyu445** [comment]
被墙了，爬梯子就好了

**Comment by Gcaufy** [comment]
github pages 的问题，大家先用着 这个
https://github.com/wepyjs/wepy-docs
