### ISSUE TITLE
请问 wepy2 本身支持微信小程序 API promise 化吗？

### ISSUE THREAD

**Issue by ximuli** [Tencent/wepy#2679]
## Description

根据最新的[文档介绍](https://wepyjs.github.io/wepy-docs/2.x/#/base/getstart)新建了一个项目，在这个项目中可以直接在原生 API 后使用 .then() .catch() 等操作。

比如 
```
wx.checkSession().then(() => {
  console.log('success')
  // session_key 未过期，并且在本生命周期一直有效
}).catch(() => {
  console.log('fail')
  // session_key 已经失效，需要重新执行登录流程
  wx.login().then(res => {
   console.log('login', res)
  })
})

```

1. 请问 wepy2 本身支持微信小程序 API promise 化吗？
2. 我查 issue 时看到官方有提供一个  @wepy/use-promisify 的 npm 包，那这个包其实是不需要使用的？
3. 初始化后生成的 wepy.config.js 的文件中有 `appConfig: {
    noPromiseAPI: ['createSelectorQuery']
  }` 这样的配置项，但是我在文档中并没有查到相关的介绍。请问这个配置和前面的问题是否有关联？ `appConfig` 这个配置项是否还有其他的不为人知的配置呢？

如有空解惑，不胜感激，谢谢！

## Environment

  * Platform: 开发者工具/iOS
  * Platform version: 开发者工具  1.03.2006090   iOS 13.6
  * Wechat version:  7.0.15
  * wepy-cli version: 2.1.0
  * wepy version: 2.1.0

**Comment by ximuli** [comment]
最近也有一直在搜索问题，找到一些答案，上来简单总结下。

1. wepy2 本身支持微信小程序 API promise 化吗？
自答：并不。是微信小程序本身已经提供了  API promise 化的能力。
> 异步 API 返回 Promise
> 基础库 2.10.2 版本起，异步 API 支持 callback & promise 两种调用方式。当接口参数 Object 对象中不包含 success/fail/complete 时将默认返回 promise，否则仍按回调方式执行，无返回值。
详情见[官方文档 API 章节](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/api.html#API)

2. @wepy/use-promisify 的 npm 包是否还有使用的必要？
自答：目前来看是不需要使用的。官方提供了 API Promise 化的方案，可参考[官方文档 API Promise化 ](https://developers.weixin.qq.com/miniprogram/dev/extended/utils/api-promise.html)。

3.  wepy.config.js 的文件中有 `appConfig: { noPromiseAPI: ['createSelectorQuery'] }` 的问题。
自答：暂未找到合适的解答。我倾向于认为是 wepy1.x 时期留下的无用代码在 standard 模板里尚未删去。

**Comment by Gcaufy** [comment]
如果你仅仅是用 promisify 的话，那大可使用官方的 api promisify 的功能

当然， `use-promisify`  其中还包含了 simplify 功能

就是

`wx.getStorage('mykey')` 和 `wx.getStorage({ key: 'mykey'});` 的区别

**Comment by Riant** [comment]
自己实现了一个，虽然简陋点，但也基本满足绝大部分场景了：
``` js
export const wxPromiseOf = (name, options = {}) => {
  return new Promise(function(resolve, reject) {
    wx[name](Object.assign({
      success(res) {
        resolve(res)
      },
      fail(err) {
        reject(err)
      },
    }, options))
  })
}
```

使用
``` js
wxPromiseOf('login').then(data => {})
wxPromiseOf('getImageInfo', {src: 'xxx'}).then(res => {})
```
