### ISSUE TITLE
wepy2 不能通过useExtendedLib扩展的方式引入weui

### ISSUE THREAD

**Issue by in9966a** [Tencent/wepy#2680]
wepy2 中   app.wpy  config  配置以下内容
"useExtendedLib": {
      "kbone": true,
      "weui": true
    }
在index.wpy config 中配置
"mp-icon": "weui-miniprogram/icon/icon"
html 中
<mp-icon icon='star'></mp-icon>

编译时会出现
Can't resolve './weui-miniprogram/icon/icon'

**Comment by jc840031139** [comment]
请问老哥解决了吗

**Comment by Gcaufy** [comment]
有更完整的代码片段吗？

**Comment by xiaohua001** [comment]
刚刚看到的 我自己还没测试https://github.com/superlbr/wepy-vant

**Comment by SpringHgui** [comment]
这个问题还没解决吗，我也遇到了

**Comment by SpringHgui** [comment]
使用这个插件解决 [wepy-cli-extend](https://www.npmjs.com/package/wepy-cli-extend)
