### ISSUE TITLE
wepy $emit Cannot read property 'triggerEvent' of undefined

### ISSUE THREAD

**Issue by TZ-TimZhang** [Tencent/wepy#2684]
import Wepy from '@wepy/core'

let eventHub = new Wepy()

eventHub.$emit('testEvent')

报错
vendor.js:6402 Uncaught TypeError: Cannot read property 'triggerEvent' of undefined
    at WepyComponent.$emit (vendor.js:6402)
    at <anonymous>:1:7

**Comment by TZ-TimZhang** [comment]
@wepy/core 版本2.1.0

**Comment by GitHubWuYi** [comment]
怎么解决的？

**Comment by ceeyang** [comment]
同遇到这个问题....
