### ISSUE TITLE
【问题】引入Vuex, page页面commit数据后关闭, 再重新进入, mapState中的数据会多次触发setData脏检查,造成卡顿

### ISSUE THREAD

**Issue by bytekent** [Tencent/wepy#2687]
这个问题困扰我2天,一直在找原因, 没办法,最后上删除大法,把写的功能全部删完,只剩一个空架子,结果依然存在问题。
于是官网下载DEMO,新建A/B, 2个页面, 引入Vuex,从A页面进入B页面,再返回重新进入B页面,问题依旧存在, setData触发次数越来越多。

![image](https://user-images.githubusercontent.com/18659436/91841422-edf02d00-ec84-11ea-95c2-94a1b02161c2.png)
![image](https://user-images.githubusercontent.com/18659436/91841744-71aa1980-ec85-11ea-8d98-448a09a90d02.png)

模拟器和真机都存在此问题。

页面A:
```html
<template>
  <div class="container">
    <div @tap="goDetail()">我是A页面</div>
  </div>
</template>

<script>
import wepy from '@wepy/core';
import { mapState } from '@wepy/x';
import store from '../store';

wepy.page({
  store,
  methods: {
    goDetail() {
      const url = './test';
      this.$navigate({ url });
    },
  },
});
</script>

```

页面B
```html
<template>
  <div class="page-b">
 我是B页面
  </div>
</template>

<script>

import store from '@/store/index.js';
import wepy from '@wepy/core';
import { mapState } from '@wepy/x';
wepy.page({
  store,
  computed: mapState(['counter','time']),
  onLoad() {
    console.log(`onload事件触发,第${this.counter}次进入页面, 开始提交commit`)
     store.commit('setCounter');
     store.commit('setTime',+new Date())
  }

});
</script>
```

store.js
```javascript
import Vuex from '@wepy/x';

export default new Vuex.Store({
  state: {
    counter: 1,
    time:0,
  },
  mutations: {
    setCounter(state) {
      state.counter++;
    },
    setTime(state, val) {
      state.time=val;
    },
  },
});

```

**Comment by bytekent** [comment]
@Gcaufy  求解答,这种问题有办法避免吗,数据比较多的时候, 页面次数越开越多, 明显卡顿起来了

**Comment by Gcaufy** [comment]
已定位到问题，是因为 @wepy/x 在页面回退时，页面实例已销毁，但是 store 是全局的，并不会跟着页面销毁而销毁。
因此虽然 setData 的 hook 会被多次执行，但是因为历史实例已被销毁，并不会真正的去执行 setData 操作的。


我去更新一下 @wepy/x 包代码，应该可以处理掉这个问题

**Comment by Gcaufy** [comment]
try this: `@wepy/x@2.1.1-alpha.0`

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/92263410-30c53580-ef0f-11ea-85c9-274b7ea10a9b.png)

**Comment by bytekent** [comment]
好的 谢谢老哥,我试试, 之前跑性能测试,多开几个页面之后, 显示1秒setData 20多次了,可能不是这个原因引起的 我再排查下
