### ISSUE TITLE
wepy2.0中如何使用globalData全局变量?

### ISSUE THREAD

**Issue by ajaxcom** [Tencent/wepy#2694]
this.$parent.globalData ?
 Cannot read property 'globalData ' of undefined

const app = getApp()
app.globalData 

几种方法都不能使用? 文档也没有找到

**Comment by Gcaufy** [comment]
globalData 本就不是一个功能或者能力。为什么需要文档说明呢？

你可以这样写

```
// globalData.js
exports = { a: 1 };
```
```
// index.wpy
const globalData = require('./globalData.js');
console.log(globalData);
```
