### ISSUE TITLE
v-model 显示会慢一拍

### ISSUE THREAD

**Issue by questionlin** [Tencent/wepy#2720]
<img width="187" alt="WX20210106-115803@2x" src="https://user-images.githubusercontent.com/1535231/103727647-c1736580-5016-11eb-91aa-796702e276ba.png">
左边已经清空了，右边还留一个字母。我用console.log打印出来也是空的

**Comment by weimingxinas** [comment]
麻烦提供一下小程序基础库版本

**Comment by questionlin** [comment]
@weimingxinas 2.14.1

**Comment by questionlin** [comment]
搞清楚了，demo里有一段
      // Page 级别 hook, 只对当前 Page 的 setData 生效。
      'before-setData': function (dirty) {
        if (Math.random() < 0.2) {
          console.log('setData canceled');
          return false; // Cancel setData
        }
        dirty.time = +new Date();
        return dirty;
      }
