### ISSUE TITLE
按照文档使用，各种报错，不维护的话，就不要放在文档里

### ISSUE THREAD

**Issue by z-golly** [Tencent/wepy#2737]
## Description

  作为新人，今天尝试了一下小程序本地开发，发现官方文档存在一些问题，链接404，按照文档程序报错，搞不懂一个腾讯，文档质量这么差
  
  [Description of the issue]

## Environment

  * Platform: [Web]
  * Platform version: [Windows10]
  * Wechat version: [2.16.0]
  * wepy-cli version: [1.7.3]
  * wepy version: [0.0.2]
  * other version: ["@wepy/use-promisify": "^2.1.0"]
  
## Reproduce
[官方文档](https://wepyjs.gitee.io/wepy-docs/2.x/#/extension/plugin?id=%e6%8f%92%e4%bb%b6) 插件链接404

[插件文档](https://github.com/Tencent/wepy/tree/master/packages/use-promisify)，按照文档完全不能运行

### Observed Results

1. 链接404
2. 代码异常
  
### Expected Results

 能够找到链接，代码能够正常运行
 

## Relevant Code / Logs

  ```

  ```

**Comment by Lyfei** [comment]
很久没更新  issue也没人关就知道不再维护了，谁还管文档了

**Comment by z-golly** [comment]
退了
