### ISSUE TITLE
升级Mac 最新系统，微信基础库2.16.1

### ISSUE THREAD

**Issue by kiradea** [Tencent/wepy#2741]
![image](https://user-images.githubusercontent.com/12182992/116215275-1aa80600-a77a-11eb-92df-af6d774f20b0.png)

**Comment by kiradea** [comment]
@Gcaufy

**Comment by kiradea** [comment]
能给个准信吗？不维护的话，我真的考虑换第三方框架了

**Comment by zhuojy666** [comment]
你这个我也遇到过，好像要把微信开发工具的es6转es5的勾选去掉

**Comment by kiradea** [comment]
> 你这个我也遇到过，好像要把微信开发工具的es6转es5的勾选去掉

试过了，不管用

**Comment by Lyfei** [comment]
早该换了

**Comment by kiradea** [comment]
> 早该换了

你换什么框架了

**Comment by 1977474741** [comment]
> > 早该换了
> 
> 你换什么框架了

现在一直维护的就剩uni-app了
