### ISSUE TITLE
$navigate('a1/a',{'key':'134'}) 跳转到a，第一次会进入a的onload方后，重新进入不执行

### ISSUE THREAD

**Issue by jiabinbin** [Tencent/wepy#275]
如题，因为我是在b页面跳转到a页面，要带上这个参数，就用这个方法
发现永远只会触发一次a页面的onlad方法。。。

**Comment by Genuifx** [comment]
老铁，onLoad只再初始化完成触发一次啊，要每次进去页面都执行操作的话，在onShow执行即可

**Comment by RORlcl** [comment]
为什么我用this.$navigate 跳转到 a , 然后从a 回退， 再次用this.$navigate 跳转 a  , a每次都执行onLoad 方法？ 能否只让a 执行一次onLoad 方法，目的是为了让它自动缓存， 但我的不行啊。

**Comment by jiabinbin** [comment]
@Genuifx 但是我带的参数得去onLoad里面取= =

**Comment by Gcaufy** [comment]
那你用$redirect试试

**Comment by jiabinbin** [comment]
@Gcaufy redirect是可以的，我试过，但是这样就没有办法返回了。。。。

**Comment by Gcaufy** [comment]
重复navigate 本就不会重复执行onLoad，二者不可兼得，你可以用onShow或者onRoute
