### ISSUE TITLE
touchmove事件监听报错

### ISSUE THREAD

**Issue by 476421978** [Tencent/wepy#2756]
## Environment
  * Platform: [开发者工具]
  * wepy-cli version: [^2.0.0-alpha.28]
  * wepy version: [^2.0.0-alpha.16]
 
## Relevant Code / Logs
 TypeError: Cannot read property 'apply' of undefined

## Repetition code：代码复现
  ```
  <template>
    <div
      @touchmove="touchmove"
    >
      move移动事件监听
    </div>
  </template>
<script>
import wepy from '@wepy/core'
wepy.page({
    methods: {
        touchmove(e) {
            console.log('touchstart-->>', e)
       }
    }
})
</script>
```

**Comment by yangbinji** [comment]
是不是因为 methdos 拼写错误，正确的应该是 methods

**Comment by yangbinji** [comment]
@476421978 是不是因为 methdos 拼写错误，正确的应该是 methods

**Comment by 476421978** [comment]
不是的

**Comment by 476421978** [comment]
![image](https://user-images.githubusercontent.com/38882528/125016944-c5a33d00-e0a4-11eb-9284-b66f0a295fc2.png)

**Comment by 476421978** [comment]
没人遇到过吗？？？呃呃呃

**Comment by weimingxinas** [comment]
无法复现，能提供代码看看么

**Comment by 476421978** [comment]
<template>
    <div
      @touchmove="touchmove"
      style="width:300rpx;height:200rpx;border:1rpx solid red;"
    >
      move2
    </div>
</template>

<script>
import wepy from '@wepy/core'
wepy.page({
  data: {
  },
  methods: {
    touchstart(e) {
      console.log('touchstart-->>')
    },
    touchmove(e) {
      console.log('touchstart-->>', e)
    }
  }
})
</script>

<style lang='less'>
</style>

**Comment by 476421978** [comment]
没人复现过吗？感觉只有我一个人遇到这种情况呢

**Comment by weimingxinas** [comment]
请提供[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)看看

**Comment by 476421978** [comment]
> 请提供[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)看看

<template>
    <div
      @touchmove="touchmove"
      style="width:300rpx;height:200rpx;border:1rpx solid red;"
    >
      move2
    </div>
</template>

<script>
import wepy from '@wepy/core'
wepy.page({
  data: {
  },
  methods: {
    touchstart(e) {
      console.log('touchstart-->>')
    },
    touchmove(e) {
      console.log('touchstart-->>', e)
    }
  }
})
</script>

<style lang='less'>
</style>

**Comment by weimingxinas** [comment]
> > 请提供[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)看看
> 
> ```
> <template>
>     <div
>       @touchmove="touchmove"
>       style="width:300rpx;height:200rpx;border:1rpx solid red;"
>     >
>       move2
>     </div>
> </template>
> 
> <script>
> import wepy from '@wepy/core'
> wepy.page({
>   data: {
>   },
>   methods: {
>     touchstart(e) {
>       console.log('touchstart-->>')
>     },
>     touchmove(e) {
>       console.log('touchstart-->>', e)
>     }
>   }
> })
> </script>
> 
> <style lang='less'>
> </style>
> ```

https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
按照这个提供下呢

**Comment by 476421978** [comment]
> > > 请提供[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)看看
> > 
> > 
> > ```
> > <template>
> >     <div
> >       @touchmove="touchmove"
> >       style="width:300rpx;height:200rpx;border:1rpx solid red;"
> >     >
> >       move2
> >     </div>
> > </template>
> > 
> > <script>
> > import wepy from '@wepy/core'
> > wepy.page({
> >   data: {
> >   },
> >   methods: {
> >     touchstart(e) {
> >       console.log('touchstart-->>')
> >     },
> >     touchmove(e) {
> >       console.log('touchstart-->>', e)
> >     }
> >   }
> > })
> > </script>
> > 
> > <style lang='less'>
> > </style>
> > ```
> 
> https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
> 按照这个提供下呢

小程序原生是没问题，可是在wepy框架上使用有问题呀。https://developers.weixin.qq.com/s/RHc6mOm370rI

**Comment by 476421978** [comment]
> > > > 请提供[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)看看
> > > 
> > > 
> > > ```
> > > <template>
> > >     <div
> > >       @touchmove="touchmove"
> > >       style="width:300rpx;height:200rpx;border:1rpx solid red;"
> > >     >
> > >       move2
> > >     </div>
> > > </template>
> > > 
> > > <script>
> > > import wepy from '@wepy/core'
> > > wepy.page({
> > >   data: {
> > >   },
> > >   methods: {
> > >     touchstart(e) {
> > >       console.log('touchstart-->>')
> > >     },
> > >     touchmove(e) {
> > >       console.log('touchstart-->>', e)
> > >     }
> > >   }
> > > })
> > > </script>
> > > 
> > > <style lang='less'>
> > > </style>
> > > ```
> > 
> > 
> > https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
> > 按照这个提供下呢
> 
> 小程序原生是没问题，可是在wepy框架上使用有问题呀。https://developers.weixin.qq.com/s/RHc6mOm370rI

我不懂怎么创建wepy的代码片段。

**Comment by 476421978** [comment]
经复现是编译后的缓存问题，请重删除weapp文件后重新编译即可
