### ISSUE TITLE
导入样式框架Tdesign-miniprogram不能resolve

### ISSUE THREAD

**Issue by Asher-Ding** [Tencent/wepy#2844]
## Description

在使用wepy过程中，试图导入腾讯的tdesign npm框架，提示resolve错误。通过修改路径导入成功后，运行时提示找不到对应的文件。

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs

index.wpy
  ```json
    ...
    "navigationBarTitleText": 'WePY 2.0 Feature Demo',
    "usingComponents": {
      "slide-view": "module:miniprogram-slide-view",
      "t-button": "module:tdesign-miniprogram",
    }
   ...
 ```

**Comment by kpsanmao** [comment]
babel版本的问题，参考https://www.02405.com/archives/12043
