### ISSUE TITLE
开启this.use('promisify')后. 结合七牛开发的sdk无法使用了.. 

### ISSUE THREAD

**Issue by 627443839** [Tencent/wepy#291]
[Qiniu-wxapp-SDK](https://github.com/gpake/qiniu-wxapp-sdk)

当没有开启 this.use('promisify') 是正常的. 能正常上传

开启后就不能了 

![image](https://user-images.githubusercontent.com/13928296/28814126-f1fddd68-76ce-11e7-9a8d-992012b36dda.png)

**Comment by rijn** [comment]
wx的方法都变成promise了啊。

```
wx.chooseImage().then()
```

**Comment by Gcaufy** [comment]
问题解决了吗？
