### ISSUE TITLE
wepy-cli 升级到 1.5.8 编译 scss 报错

### ISSUE THREAD

**Issue by cmzz** [Tencent/wepy#303]
```
{ Error: Invalid CSS after ".f8 {": expected "}", was "{"
    at options.error (/Users/steve/www/xiaochengxu-projects/weapp-pigtk/node_modules/node-sass/lib/index.js:291:26)
  status: 1,
  file: '/Users/steve/www/xiaochengxu-projects/weapp-pigtk/src/assets/scss/base.scss',
  line: 3,
  column: 6,
  message: 'Invalid CSS after ".f8 {": expected "}", was "{"',
  formatted: 'Error: Invalid CSS after ".f8 {": expected "}", was "{"\n        on line 3 of src/assets/scss/base.scss\n>> .f8 { {\n   -----^\n' }
```

代码: base.scss 
```
.f8 {
  font-size: 16rpx !important;
}
.f9 {
  font-size: 18rpx !important;
}
```

app.wpy
```
<style lang="scss">
  @import "assets/scss/base.scss";
</style>
```

**Comment by cmzz** [comment]
1.5.7 正常

**Comment by leCapsimRy** [comment]
同问题，bug会在1.5.9中改动还是对1.5.8直接调整？

**Comment by coolhwm** [comment]
同问题

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy-wechat-demo/commit/d85fae6e2873866bc26791881d25f7b952dfe1b7
刚把这个使用sass的项目升级成为1.5.8了，没有发现有任何问题。
或者谁能提供一份简单的实例代码发给我参考一下。

**Comment by Gcaufy** [comment]
@leCapsimRy 
如果其它模块的BUG，如 wepy-compilers-sass， 那么直接发布一下这个模块就可以了，
如果是wepy-cli的BUG，并且影响到用户正常使用，那么紧急发布下个版本。

**Comment by leCapsimRy** [comment]
ok
我这边可以了，把lang="sass"改成“scss”就编译过去了，出现这个问题的可以试下

**Comment by leCapsimRy** [comment]
@Gcaufy 
好的  我这边问题已经解决了  感谢解答

**Comment by cmzz** [comment]
@leCapsimRy  我的已经是 lang="scss"

**Comment by leCapsimRy** [comment]
@cmzz 你把样式文件写到wpy里试一下，我这样没有问题，如果还不行的话，可以把sass的包删掉，build重新载入一下试试看
`<style lang="scss">
  .articard{
    background: #fff;
    // border-bottom: 1px solid #c7c7c7;
    box-shadow: 0 5rpx 10rpx #dcdcdc;
    width: 90%;
    margin-bottom: 20rpx;
    padding: 5%;
    padding-bottom: 1%;
    display: inline-block;
    .title{
      font-size: 45rpx;
      color: #333;
      width: 100%;
      display: inline-block;
    }
    .author{
      color: #9d9d9d;
      font-size: 30rpx;
      width: 100%;
      display: inline-block;
    }
    image{
      width: 100%;
      height: 382rpx;
      display: inline-block;
      margin-top: 10rpx;
    }
    .introduce{
      color: #9d9d9d;
      font-size: 30rpx;
      width: 100%;
      display: inline-block;
    }
    .others{
      width: 100%;
      display: inline-block;
      margin: 10rpx 0;
      .time{
        color: #c1c1c1;
        font-size: 24rpx;
        display: inline-block;
      }
      .right{
          float: right;
          .wine{
            display: inline-block;
            margin-right: 30rpx;
            .num{
              color: #c1c1c1;
              font-size: 24rpx;
              display: inline-block;
              margin-right: 5rpx;
            }
          }
          .iconfont{
            color: #c1c1c1;
            font-size: 32rpx;
            display: inline-block;
          }
      }
    }
  }
</style>
<template>
  <view class="articard" @tap="tap({{articlelist.id}})">
    <text class="title" >{{articlelist.title}}</text>
    <text class="author">{{articlelist.author}} /文</text>
    <image src="{{articlelist.img}}"></image>
    <text class="introduce">{{articlelist.introduce}}</text>
    <view class="others">
      <text class="time">{{articlelist.time}}</text>
      <view class="right">
        <view class="wine">
          <text class="num">{{articlelist.num}}</text>
          <text class="iconfont icon-baijiu"></text>
        </view>
        <text class="iconfont icon-zhuanfa"></text>
      </view>
    </view>
  </view>
</template>
<script>
  import wepy from 'wepy'
  export default class Articard extends wepy.component {
    props = {
      articlelist: {},
      indexa: {}
    }
    methods = {
      tap(id) {
        this.$emit('intoInfo', id)
      }
    }
  }
</script>
`

**Comment by Gcaufy** [comment]
@cmzz 找到问题了，问题是使用import xxx.scss 时，还是按sass的方式编译去了。所有有两种解决方案。
1. scss格式文件改成sass文件。
2. 参照上述commit修改一行代码。

**Comment by cz848** [comment]
改了之后报错，文件为scss
{ SyntaxError: unknown: Unexpected token (1:0)
> 1 | .member-card {
    | ^
  2 |   .card {
  3 |     position: relative;
  4 |     width: 335 * 2rpx;
    at Parser.pp$5.raise (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/tylerchao/Sites/offline-wepy/node_modules/babylon/lib/index.js:1906:19)
  pos: 0,
  loc: Position { line: 1, column: 0 },
  _babel: true,
  codeFrame: '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[33m.\u001b[39mmember\u001b[33m-\u001b[39mcard {\n \u001b[90m   | \u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 2 | \u001b[39m  \u001b[33m.\u001b[39mcard {\n \u001b[90m 3 | \u001b[39m    position\u001b[33m:\u001b[39m relative\u001b[33m;\u001b[39m\n \u001b[90m 4 | \u001b[39m    width\u001b[33m:\u001b[39m \u001b[35m335\u001b[39m \u001b[33m*\u001b[39m \u001b[35m2\u001b[39mrpx\u001b[33m;\u001b[39m\u001b[0m' }

**Comment by Gcaufy** [comment]
参考一下我上面的回复

**Comment by afarwind** [comment]
@Gcaufy 目前npm上直接安装的wepy-cli 1.5.8仍然存在这个问题，不过我参照你的上面的回复中的commit已经自己改了，希望有时间可以更新下npm上的包，谢谢……

**Comment by Gcaufy** [comment]
预计下周或者下下周可能会发一个大版本

**Comment by happyhero0** [comment]
@Gcaufy 希望尽快更新npm, 换掉1.5.8  👍

**Comment by Gcaufy** [comment]
@happyhero0 可以升级成 `npm install wepy-cli@1.5.9-0`
