### ISSUE TITLE
wxParse 使用问题 

### ISSUE THREAD

**Issue by stt04521** [Tencent/wepy#313]
wepy 结合 wxParse 使用出现问题，
  @import "../wxParse/wxParse.wxss";

<import src="../wxParse/wxParse.wxml" />
<template is="wxParse" data="{{wxParseData:productdesc.nodes}}" />

let WxParse = require('../wxParse/wxParse.js')

WxParse.wxParse('productdesc', 'html', this.productdesc, this, 16)

完成如上操作 页面报 Do not have wxParseImgLoad handler in current page

**Comment by stt04521** [comment]
<import src="../wxParse/wxParse.wxml" />
 <template is="wxParse" data="{{wxParseData:productdesc.nodes}}" />
还有这一步

**Comment by stt04521** [comment]
<import src="../wxParse/wxParse.wxml" />
 <template is="wxParse" data="{{wxParseData:productdesc.nodes}}" />

**Comment by stt04521** [comment]
‘<import src="../wxParse/wxParse.wxml" />’
‘<template is="wxParse" data="{{wxParseData:productdesc.nodes}}" />’

**Comment by baozigit** [comment]
我也是同样的问题哈，至今还没解决

**Comment by shellteo** [comment]
使用import啊，
`import WxParse from '../wxParse/wxParse';`

**Comment by XylitolLin** [comment]
在 WxParse.wxParse 这个方法中有这样两句代码：
````javascript
that.wxParseImgLoad = wxParseImgLoad;
that.wxParseImgTap = wxParseImgTap;
````
目的就是把这两个方式赋给 page，从而在 template 中可以使用。但是可能是因为 wepy 和原生小程序的运行方式有些出入，导致 `wxParseImgLoad` 和 `wxParseImgTap` 没有在 page 中顺利运用。

我在项目是这样修改的：

````javascript
// 在 wxParse.js 中需要把 function wxParseImgLoad() 和 function wxParseImgTap() export 出去
module.export = {
  //...
  wxParseImgLoad: wxParseImgLoad,
  wxParseImgTap: wxParseImgTap,
}
````

````javascript
// 在 page 中将 wxParseImgLoad  和 wxParseImgTap 放进 methods

import WxParse from '../../wxParse/wxParse'

export default class extends wepy.page {
  methods = {
    wxParseImgLoad: WxParse.wxParseImgLoad.bind(this),
    wxParseImgTap: WxParse.wxParseImgTap.bind(this)
  }
}
````

**Comment by Lizhilin** [comment]
引入的样式字体设置是中文会导致编译wxss出错

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/issues/733
