### ISSUE TITLE
css 中的calc 计算属性异常

### ISSUE THREAD

**Issue by cjfff** [Tencent/wepy#340]
用calc的时候 比如我写个 width:calc(100vw - 100rpx)  它会把rpx单位编译成vw 结果width为0

**Comment by Gcaufy** [comment]
你期望的结果是？

**Comment by CarsonXin** [comment]
我也遇到这个问题，当style的lang为“less”/“sass”时，单位带rpx的calc就会编译出错。设置为“css”则不会

**Comment by c4cat** [comment]
@ccc865553742 @CarsonXin 
在less下要这样 width: e("calc(100% - 30rpx)");

**Comment by ystarlongzi** [comment]
less 下这样也可以，`width: clac(~"100vw - 100rpx")`，这个是 less 编译器的问题

**Comment by lichangwei** [comment]
@ccc865553742 启用less的严格模式，在wpy.config.js中修改如下
 compilers: {
        less: {
            compress: true,
            strictMath: true, /* 添加这一行 */
        }
}
