### ISSUE TITLE
import npm 模块 报错

### ISSUE THREAD

**Issue by xutm** [Tencent/wepy#342]
### 引用npm模块fecha报错
`index.js:1  Uncaught SyntaxError: Unexpected token export
factory.js:1  Uncaught SyntaxError: Unexpected token import`

`import fecha from 'fecha'`

### 引用自己定义的npm模块报错
`WAService.js:9  Uncaught Error: module "npm/@xhs/http/index.js" is not definedrequire @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ app.js [sm]:5require @ WAService.js:9(anonymous function) @ app.js:130
base.js:137 Uncaught TypeError: Cannot read property '$pages' of undefined`

`import http from '@xhs/http'`

### 
**在线等待回复**

**Comment by Gcaufy** [comment]
这是两个错误？没太看懂你的描述

第一个好像是没有编译的问题，dist里的代码不可能有import
第二个你的看看dist/npm中有没有对应的文件，然后看看require路径对不对。

**Comment by xutm** [comment]
- 第一个问题，是在代码里面import  fecha from  ‘fecha’，然后运行wepy build --watch 微信开发者工具中报的错
- 第二个问题，我在代码里面import http from '@xhs/http'，然后运行wepy build --watch，微信开发者工具中报的错误
### 两个问题之间的区别在于，第一个npm包是开源的fecha，第二个是我自己构建的npm包

**Comment by Gcaufy** [comment]
编译完后都不会有 import关键字的。。怎么会报`Unexpected token import`
你看一下编译完后的代码先。

**Comment by xutm** [comment]
### 第二个问题的可能原因
- wepy build --watch 获取node_modules中的包，无法识别，node_modules对应的包中的 import
`export { default as dualColumnCardTransform } from './src/dualColumnCardTransform'
export { default as getItemStockStatus } from './src/getItemStockStatus'
export { default as urlUtils } from './src/url-utils'
export { default as dateUtils, formatNumber, formatter, dateStringToTimestamp } from './src/date-utils'
export { default as priceUtil } from './src/price'
export { default as couponUtil } from './src/coupon'`
> 上面的代码是node_modules中index.js中，所引入的模块，均没有被解析

**Comment by xutm** [comment]
@Gcaufy  第二个问题，能否重现？

**Comment by xutm** [comment]
看了下源码，确实只支持但文件引入
`getPkgConfig (lib) {
        let pkg = util.readFile(path.join(modulesPath, lib, 'package.json'));
        try {
            pkg = JSON.parse(pkg);
        } catch (e) {
            pkg = null;
        }
        return pkg;
    },`
` let pkg = this.getPkgConfig(lib);
                if (!pkg) {
                    throw Error('找不到模块: ' + lib);
                }
                let main = pkg.main || 'index.js';
                if (pkg.browser && typeof pkg.browser === 'string') {
                    main = pkg.browser;
                }
                source = path.join(modulesPath, lib, main);
                target = path.join(npmPath, lib, main);
                lib += path.sep + main;
                ext = '';
                needCopy = true;`
**@Gcaufy 给我一个回复？这个问题你们后续会解决吗？还是。。。**

**Comment by Gcaufy** [comment]
依然不太明白问题，
是wepy的问题，后续肯定会修复的。
介意发份简单的DEMO代码给我重现一下。

**Comment by wulunyi** [comment]
貌似跟我的引用私有 npm 包一样
下面是我的解决可试一下
这个问题我找到了问题的地点：
对于带 scopes 的私有组件——像我自己的 @jt/jt-wepy-h-video 组件;
通过 npm 安装的引用写法为 import Hvideo from “@jt/jt-wepy-h-video”;

问题出现在以下两个地方:
1、在  complie-wpy.js 源码 229 行 get imports 时使用正则表达式 /import\s*([\w\-\_]*)\s*from\s*['"]([\w\-\_\.\/]*)['"]/ig 无法匹配带有“@”符号的情况;

我的调整:：/import\s*([\w\-\_]*)\s*from\s*['"]([\w\-\_\.\/\@]*)['"]/ig;
 
2、在 util.js 中 findComponent 方法中 124 行使用了 com.indexOf(path.sep) !== -1 进行判断是否是 node_modules 中的模块，忽略了 私有库中带有"@"符号这种情况，导致找不到这个组件;

我的调整：添加 com.indexOf('@') === -1 判断条件来命中带"@"符号这种情况;
