### ISSUE TITLE
组件引用路径问题

### ISSUE THREAD

**Issue by bannermiao** [Tencent/wepy#345]
项目目录如下：
![1](http://m.yodoing.com/Public/temp/1.png)

**组件components里面loading.wpy 引入一个 本地图片 loading.gif**

![2](http://m.yodoing.com/Public/temp/2.png)

然后在brand.wpy引入loading.wpy，运行brand.wpy时，发现图片路径引入报错，以前没有这个问题
wepy 1.5.8

![3](http://m.yodoing.com/Public/temp/3.png)

**Comment by Gcaufy** [comment]
好像的确是存在这样的问题。components 是静态编译直接注入到page里的，所以暂时先把路径做成page的相对路径吧，后面我再看一下这里的问题怎么处理。

**Comment by Gcaufy** [comment]
是否可以安装验证一下这个问题呢？
```
npm install wepy-cli@1.5.9-4 -g
```

**Comment by woleicom** [comment]
我也没找到解决办法 ，目前我是这么解决的
调用
`tip.alert(this,'没有更多商品了');`
定义
`static alert(t,title) {
    let i = t.$wxpage.route.match('/').length,n=0;
    let s = '';
    while (n<i){
      s+='../';
      n++;
    }
    wx.showToast({
      title: title,
      image: s+"images/icon_alert.png",
      mask: true,
      duration: 1500
    });
  }`

**Comment by Gcaufy** [comment]
这个问题是已经release的问题了

>### 1.6.0 (2017-10-25)
>`F` 修复了组件中引用相对路径在某些情况下不准确的问题。[ISSUE 345](#345)

**Comment by besfro** [comment]
貌似页面引用嵌套组件还有问题

子组件有一个图片 ./icon.jpg
父组件引入子组件 
页面引入父组件 

打印的地址是 form/checkbox/icon.jpg
预期应该是 ../components/form/checkbox/icon.jpg

这个问题 貌似是因为 父组件引入子组件的时候就打印了这个路径
所以页面引用是错误

**Comment by Gcaufy** [comment]
可以给出你的路径看看吗？

**Comment by besfro** [comment]
![image](https://user-images.githubusercontent.com/28135679/35205100-a95a49b6-ff6d-11e7-8ae0-f1f24b3552f3.png)

子组件
`<template>
  <repeat for="{{Array.isArray(datas) ? datas : [datas]}}" index="index" item="item">
    <view class="checkbox" @tap="tap({{index}})">
      <image src="./icon.png" mode="aspetFix" wx:if="{{!item.checked}}"></image>
      <image src="./icon-checked.png" mode="aspetFix" wx:if="{{item.checked}}"></image>
    </view>
  </repeat>
</template>`

父组件
`<view class="weui-media-box__hd weui-media-box__hd_in-appmsg" wx:if="{{isCheckbox}}">
          <checkbox :datas.sync="item"></checkbox>
        </view>`

页面
`  <checkbox :datas.sync="orderCheckbox" type="0"></checkbox>
  <checkboxAll :datas.sync="orderCheckbox" type="1"></checkboxAll>
  <panel :datas.sync="testdata" :attrAlias.sync="testdir"></panel>`

页面2种引用
1. 直接引用了checkbox组件 （路径正常）
2. 引用了panel, panel里边引用了checkbox组件 （错误路径）

结果
![image](https://user-images.githubusercontent.com/28135679/35205197-6cd4f3a0-ff6e-11e7-8bb0-93d815ee32d3.png)

**Comment by ehomecd** [comment]
今天使用wepy1.7.3版本,仍然出现这个问题,求解决办法.

![1](https://user-images.githubusercontent.com/16703612/47256520-706a0c00-d4b4-11e8-953d-a78ea7f467c0.png)
