### ISSUE TITLE
组件的Props在页面重载(onRoute)的情况下没有更新

### ISSUE THREAD

**Issue by jchbh-duplicate** [Tencent/wepy#351]
用component做了一个tab条。
程序使用redux绑定数据，

在index page里面的tab的props设置上值（使用:value.sync定义）以后，
切换到另一个页面，修改tab中的依赖的state的数据。

当返回到index page时，页面加载以后，程序正确执行了
connect中对应的取state的指令，并且成功的将更新内容显示在页面中（我做了一个debug的text放在index page中，显示tab数据中的改动数据），但tab条内的数据仍然是原来的样子。

怀疑是component的.sync绑定，在重新加载页面（onRoute）的时候无法正确判断其值已经改变并刷新。

**Comment by jchbh-duplicate** [comment]
操作前
<img width="418" alt="screen shot 2017-08-24 at 10 00 02 pm" src="https://user-images.githubusercontent.com/785571/29695187-b4feb74c-8917-11e7-9e19-497f177e200d.png">
操作完毕返回后

<img width="402" alt="screen shot 2017-08-24 at 10 00 17 pm" src="https://user-images.githubusercontent.com/785571/29695199-c05eff02-8917-11e7-986e-77bb855ab4bf.png">

**Comment by jchbh-duplicate** [comment]
tabbar的绑定：
<tabbar @tap.user="onTap" :define.sync="tabBar"></tabbar>
测试部分的定义：
<text>{{tabBar[3].iCount}}<text>

connect的定义
  @connect({
    tabBar(state) { return state.tabbar },

**Comment by Gcaufy** [comment]
能否提供简单的demo示例给我还原重现呢？
