### ISSUE TITLE
两次repeat组件报错

### ISSUE THREAD

**Issue by fantasthu** [Tencent/wepy#386]
## 数据: 
```
cartList: [
      {
        id: 1,
        name: '郑州保税仓',
        list: [
          { id: 1, title: '美丽说', price: '122.23', number: 2, hasChecked: true },
          { id: 2, title: '美丽说', price: '122.23', number: 1, hasChecked: false },
          { id: 3, title: '美丽说', price: '122.23', number: 1, hasChecked: false },
          { id: 4, title: '美丽说', price: '122.23', number: 1, hasChecked: false }
        ]
      }
    ]
```

## dom结构:
```
<view class="carts">
      <repeat for="{{cartList}}" key="key" index="index" item="data">
        <view class="header">
          <checkbox checked="{{allchecked}}" />{{data.name}}
        </view>
        <repeat for="{{data.list}}" key="key" item="inneritem">
          <CartGood :good="inneritem" :houseid="item.id" @update.user="updateGood" />
        </repeat>
        <view class="discounts">优惠:¥0.00</view>
        <view class="total">本仓合计:¥124</view>
      </repeat>
    </view>
```

## 定义CartGood 属性方式:
```
 props = {
    good: Object,
    houseid: {
      type: String,
      default: ''
    }
  }
```

## 报错
```
WAService.js:3 thirdScriptError
Cannot convert undefined or null to object;at pages/shoppingcart page lifeCycleMethod onLoad function
TypeError: Cannot convert undefined or null to object
    at Function.constructor.keys (<anonymous>)
    at http://1281427308.appservice.open.weixin.qq.com/npm/wepy/lib/component.js:169:56
    at CartGood.$init (http://1281427308.appservice.open.weixin.qq.com/npm/wepy/lib/component.js:176:35)
    at http://1281427308.appservice.open.weixin.qq.com/npm/wepy/lib/component.js:213:39
    at Array.forEach (<anonymous>)
    at Index.$init (http://1281427308.appservice.open.weixin.qq.com/npm/wepy/lib/component.js:212:22)
    at Index.$init (http://1281427308.appservice.open.weixin.qq.com/npm/wepy/lib/page.js:60:104)
    at e.config.onLoad (http://1281427308.appservice.open.weixin.qq.com/npm/wepy/lib/base.js:149:18)
    at e.<anonymous> (http://1281427308.appservice.open.weixin.qq.com/WAService.js:9:6232)
    at A (http://1281427308.appservice.open.weixin.qq.com/WAService.js:8:26409)
```

**Comment by fantasthu** [comment]
上面虽然报错,至少子组件是可以渲染出来的
![image](https://user-images.githubusercontent.com/9922079/30385486-f1d433d6-986c-11e7-881f-8f9df93ffa9a.png)

==========
![image](https://user-images.githubusercontent.com/9922079/30385408-a661808e-986c-11e7-9b0c-24e02f54cd2e.png)
后来更换成wx:for 组件就渲染不出来了
![image](https://user-images.githubusercontent.com/9922079/30385440-c9981388-986c-11e7-8460-a9855b0187fb.png)

**Comment by Gcaufy** [comment]
参考一个demo示例看看，那个也是两次repeat。

**Comment by fantasthu** [comment]
@Gcaufy  你好像在一个issue中说不要repeat两次,而且修复了bug貌似,我在文档中也没有看到两次repeat的demo,可以给个链接么

**Comment by Gcaufy** [comment]
wepy new demo

**Comment by fantasthu** [comment]
@Gcaufy 好的,先谢谢,我看看

**Comment by fantasthu** [comment]
@Gcaufy  你好,你的demo中都是repeat一次的,没有两次的,而且很多issue 中repeat存在问题

**Comment by fantasthu** [comment]
@Gcaufy  我现在把页面分成了两个组件分别repeat

## 代码如下
页面中:
```
<view class="shopping-cart">
    <view class="carts">
      <repeat for="{{cartList}}" key="key"  item="data">
        <Bin :data="data"/>
      </repeat>
    </view>
```

Bin组件中
```
 <repeat for='{{data.list}}' index='index' key='key' item='item'>
      <CartGood :good="item" @update.user="goodUpdate" />
    </repeat>
```

## 报错内容
(CONTENT_SCRIPT context for ikhdnebglabgeplgnhnjgldiemdflddf) extensions::guestViewContainer:8: Uncaught Natives disabled{<stack trace unavailable>}
VM140 extensions::extensionView:7 Uncaught TypeError: Cannot read property 'GuestViewContainer' of undefined
    at VM140 extensions::extensionView:7
(anonymous) @ VM140 extensions::extensionView:7
VM139 extensions::extensionOptionsAttributes:40 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at VM139 extensions::extensionOptionsAttributes:40
(anonymous) @ VM139 extensions::extensionOptionsAttributes:40
/appservice?load:1 (CONTENT_SCRIPT context for ikhdnebglabgeplgnhnjgldiemdflddf) extensions::event_bindings:8: Uncaught Natives disabled{<stack trace unavailable>}
/appservice?load:1 (CONTENT_SCRIPT context for ikhdnebglabgeplgnhnjgldiemdflddf) extensions::binding:5: Uncaught TypeError: Cannot read property 'Event' of undefined{TypeError: Cannot read property 'Event' of undefined
    at extensions::binding:5:38
    at extensions::chromeWebViewInternal:5:15
    at extensions::chromeWebView:8:21}
/appservice?load:1 (CONTENT_SCRIPT context for ikhdnebglabgeplgnhnjgldiemdflddf) extensions::chromeWebViewInternal:5: Uncaught TypeError: Cannot read property 'Binding' of undefined{TypeError: Cannot read property 'Binding' of undefined
    at extensions::chromeWebViewInternal:5:33
    at extensions::chromeWebView:8:21}
VM146 extensions::chromeWebView:8 Uncaught TypeError: Cannot read property 'ChromeWebView' of undefined
    at VM146 extensions::chromeWebView:8
(anonymous) @ VM146 extensions::chromeWebView:8
/appservice?load:1 (CONTENT_SCRIPT context for ikhdnebglabgeplgnhnjgldiemdflddf) extensions::event_bindings:8: Uncaught Natives disabled{<stack trace unavailable>}
/appservice?load:1 (CONTENT_SCRIPT context for ikhdnebglabgeplgnhnjgldiemdflddf) extensions::binding:5: Uncaught TypeError: Cannot read property 'Event' of undefined{TypeError: Cannot read property 'Event' of undefined
    at extensions::binding:5:38
    at extensions::extensionViewInternal:7:5
    at extensions::extensionViewAttributes:12:5}

**Comment by fantasthu** [comment]
刷新了一遍,渲染是可以了,但是点击事件触发之后,
thirdScriptError
Maximum call stack size exceeded;at pages/shoppingcart page $Bin$CartGood$minus function
RangeError: Maximum call stack size exceeded
这样了

**Comment by Autumnwater** [comment]
嗯，我发现好像是数据源的方面吧，我倒是发现了几个不同的解决方法。
拿你的第一个举例子 
<view class="carts">
      <repeat for="{{cartList}}" key="key" index="index" item="data">
        <view class="header">
          <checkbox checked="{{allchecked}}" />{{data.name}}
        </view>
        <repeat for="{{data.list}}" key="key" index="index" item="inneritem">
          <CartGood :good="data.list[index]" :houseid="data.list[index].id" @update.user="updateGood" />
        </repeat>
        <view class="discounts">优惠:¥0.00</view>
        <view class="total">本仓合计:¥124</view>
      </repeat>
    </view>

或者说 手动把 data.list赋值成其他的 一个值

**Comment by nishino-tsukasa** [comment]
我也遇到了这个问题，调试了一下午，代码实在没有写错
原来这么多人遇到了
按照第一个方法是可以显示了，但是methods、computed这些全都取不到值
data.list赋值成其它是怎么写呀

**Comment by CoderXWChu** [comment]
最终有解决方案吗？
