### ISSUE TITLE
【建议】wepy-cli 是否可以暴露出 beforeCompiler 类似的钩子

### ISSUE THREAD

**Issue by ystarlongzi** [Tencent/wepy#400]
希望 `wepy-cli` 在构建编译前，可以让开发者修改目标文件内容。

比如现在有个这样的需求，项目目录结构如下：
```
project
└── src
    ├── pages
    |   ├── index
    |   |   ├── index.less
    |   |   ├── index.wpy
    |   |   ├── index.wxml
    └──app.wpy 
```
因为 `/page/index/` 页面的样式、逻辑比较复杂，考虑系统维护性、代码易读性，并没有采取官方推荐的「单文件模式」，而是拆分成多个文件。

但是，拆分成这样的目录结构时，还有一点麻烦，就是需要在 `/pages/index/index.wpy` 里手动引入`/pages/index/index.less`、`/pages/index/index.wxml`。如下：

```
<style lang="less" src="./index.less"></style>
<template lang="wxml" src="./index.wxml"></template>
<script>
  // ........
</script>
```
然后，感觉略麻烦些.........然后，现在想实现「`index.wpy` 自动加载同目录下的同名文件」的功能
```
<script>
  // ........
</script>
```
即当 `index.wpy` 内容如上时，然后在 `wepy-cli` 编译前，修改文件内容，在其前添加 `./index.less` 和 `./index.wxml`的引入。

但是根据 [/compile-wpy.js#L83](https://github.com/wepyjs/wepy/blob/master/packages/wepy-cli/src/compile-wpy.js#L83) 处的代码，假如官方能暴露出类似 `beforeCompile` 的钩子前，应该就可以实现这个功能了O(∩_∩)O~

**Comment by Gcaufy** [comment]
期望的接口行式是怎么样的呢？

**Comment by ystarlongzi** [comment]
```
module.exports = {
  wpyExt: '.wpy',
  eslint: true,
  beforeCompilers: {},
  compilers: {},
  plugins: {}
}
```
参照现有的`compilers`、`plugins`配置，然后添加 `beforeCompilers`，这样可行的不？

**Comment by ystarlongzi** [comment]
@Gcaufy 这个建议有被采纳的可能嘛？😄

**Comment by Gcaufy** [comment]
建议很好，可以考虑，但API没有那么简单。
