### ISSUE TITLE
【建议】是否可以支持 app.json 可以和 wepy.app 的 config 并存

### ISSUE THREAD

**Issue by ystarlongzi** [Tencent/wepy#402]
如题，假如存在如下目录：
```
-- src
  -- page
    -- index
      -- index.json
      -- index.wpy
  -- app.json
  -- app.wpy
```

如果发现存在 `/app.json` 或者 `/page/index/index.json` ，那就忽略或合并 `app.wpy` 或 `/page/index/index.wpy` 里的 config 内容

**Comment by Gcaufy** [comment]
这个意义在哪？使用场景呢？

**Comment by ystarlongzi** [comment]
@Gcaufy 
应用场景还是希望在 wepy 构建前，根据构建时不同的参数、环境变量等，动态修改 wepy 组件里的 `config` 属性 🤣🤣🤣，然后在实际操作中，发现在使用 `wepy-plugin-replace` 插件且配置正确的情况下，并不能替换 wepy 组件里的 `config` 属性🤣🤣。

所以，根据这个场景需求，才有了这两天我提的一些列的问题。比如：
1. [添加 `beforeCompile` 钩子](https://github.com/wepyjs/wepy/issues/400#issuecomment-331328369)。这个解决问题的出发点，是想在编译前就先把 `.wpy` 文件内容给修改掉，应该就可以满足我的需求

2. 支持 `app.json`文件 与组件的 `config` 属性，即本 issue。这个问题的出发点是在了解到 `.json` 文件是有构建工具动态生成的前提下，突然想到如果在构建前就存在了 `app.json`，这时候再用 `wepy-plugin-replace` 插件，应该也可以满足我的需求

3. [wepy-cli 在构建生成 .json 文件后，没有运行 plugins 插件](https://github.com/wepyjs/wepy/issues/403)。这个问题是昨天晚上有看了下相关代码，然后才了解到为什么 `config` 属性，没有被 replace 的真正原因

如果说，能解决第 3）个问题，那本 issue 的意义、及场景就不存在啦啦啦啦啦

**Comment by Gcaufy** [comment]
也就是说我让config也走plugins那问题就能解决对吧。

**Comment by ystarlongzi** [comment]
嗯嗯，是的呢😊

**Comment by Gcaufy** [comment]
好的。
