### ISSUE TITLE
使用wxParse插件时，在lang=“scss”情况下，@import "../wxParse/wxParse.wxss";报错

### ISSUE THREAD

**Issue by railgun20001** [Tencent/wepy#423]
如题，微信开发工具报错为unexpected "�" at pos 1

在dist的wxss文件中开头按backspace键，尽管看不见内容，仍可删除成功，删除之后微信不报错
![image](https://user-images.githubusercontent.com/22837283/31261014-5badc44c-aa84-11e7-9ecb-8dc92622ef58.png)

将lang换为less也可以成功

**Comment by coolhwm** [comment]
解决了么

**Comment by coolhwm** [comment]
@Gcaufy 
我也遇到这个，目测是编译出来的部分文件增加了UTF8 BOM头部，手工删掉头部就好了
在sass配置为压缩的时候，才有这个问题
```
 module.exports.compilers['sass'] = {outputStyle: 'compressed'};
```
编译报错：
![image](https://user-images.githubusercontent.com/20462043/32707641-5ef432ae-c860-11e7-918f-e65ff18deb06.png)
文件格式：
![image](https://user-images.githubusercontent.com/20462043/32707646-65cbcaf6-c860-11e7-8bb8-1f5434339586.png)
另外，只有部分文件会这样，源`.scss`文件我检查了，没有BOM头部

**Comment by wulunyi** [comment]
去掉	font-family: Courier, Calibri, "宋体";

**Comment by zongwong** [comment]
我在用了@import的时候 sass才会多出UTF8 BOM头部 ,要手动改,不知道怎么配置哦

**Comment by JoeZhangHao** [comment]
解决了吗，用了sass就不能用这个了吗

**Comment by Gcaufy** [comment]
加个replace插件，处理一下试试？
```
code = code.replace("\ufeff", "");
```

**Comment by jswxwxf** [comment]
我也遇到这个问题了，有什么办法可以解决啊？现在只能暂时把 {outputStyle: 'compressed'} 给关掉了~~

**Comment by garychenwei** [comment]
> 我也遇到这个问题了，有什么办法可以解决啊？现在只能暂时把 {outputStyle: 'compressed'} 给关掉了~~
除了关闭{outputStyle: 'compressed'}，还有什么方法吗？
