### ISSUE TITLE
使用repeat组件，更新数据后，事件缓存。

### ISSUE THREAD

**Issue by xmsz** [Tencent/wepy#428]
`<repeat for="{{createList}}"
 index="index"
										item="item"
										key="index">
							<CreateSection :item.sync="item"
														 :index.sync="index"></CreateSection>
						</repeat>`

这是外层循环
---

组件里有
`this.$emit('goCourse', this.item, index);`

---
当我执行了 
` this.createList.splice(index, 1);
          this.$apply();`
以后

---

数据和页面都更新了

---

但我再点击组件事件的时候

----

无论是从组件里log 还是组件外log
this.item 都是之前那个splice掉的那个值

**Comment by Fycho** [comment]
这个问题目前没发现好办法，我们是用wx:for和原生事件参数传递绕开此问题
