### ISSUE TITLE
wepy 中组件支持动态绑定吗

### ISSUE THREAD

**Issue by hankanon** [Tencent/wepy#429]
就像Vue中的
`<component v-bind:is="currentView">
  
</component>`
在wepy的文档中没找到例子，求教

**Comment by CFDylan** [comment]
目前不支持，如果支持，是在这里https://wepyjs.github.io/wepy/#/?id=_4-%e7%bb%84%e4%bb%b6%e4%bb%a3%e6%9b%bf%e6%a8%a1%e6%9d%bf%e5%92%8c%e6%a8%a1%e5%9d%97
```
<template>
    <component id="item"></component>
</template>
```
这里的`id`需要支持动态绑定。看了下源码，现在 id 是直接读属性的。
```
getComId(elem) {
        let tagName = elem.nodeName;
        let path = elem.getAttribute('path');
        let id = elem.getAttribute('id');
        if (tagName !== 'component')
            return tagName;
        if (id)
            return id;
        if (path && !id)
            return path;
    }
```

**Comment by JohnPion-Zhang** [comment]
你如果要动态组件，楼上是一种办法，但是确实目前版本不支持，我已经试过了。暂时我想到的办法是直接罗列所有组件，然后使用wx:if条件渲染，不用担心性能，wx:if不合条件的直接不会渲染。简单粗暴了点，如果大家有更好的办法，欢迎分享。

**Comment by Gcaufy** [comment]
不支持动态组件，wepy做的是运行前的编译，小程序不支持动态组件那wepy就不可能支持。
@CFDylan 打算在下个版本中弃用`<template`的写法，所以不要考虑。
