### ISSUE TITLE
能不能写一个typescript如何使用的例子？

### ISSUE THREAD

**Issue by qinyang1980** [Tencent/wepy#430]

**Comment by looch** [comment]
谁能用ts的，发个配置文件？

**Comment by jhcao23** [comment]
typescript的模块完全不知道咋用

**Comment by m8989** [comment]
我的情况是：lang=typescript可以编译出来。但生成的代码不对。也仔细对比了代码差别很大。
wepy.d.ts从网上找到了一份。忘了哪里来的了。也会出错。

**Comment by qinyang1980** [comment]
我这边确实可以用。但是感觉意义不大。因为木有智能提示。

**Comment by walter211** [comment]
有大佬知道怎么既觉tslint配置报错的问题吗

**Comment by hanwenbo** [comment]
不支持怎么写 文档写的支持 但你自己测试去  根本不支持

**Comment by hanwenbo** [comment]
每次编译 无论你是否写错  都可以编译成功  那还有什么意义 这不叫支持typescript吧

**Comment by jhcao23** [comment]
请求官方提供wepy.js的typescript定义 方便广大typescript爱好者(通常是纯JavaScript小白但又是typescript expert)的更多加入和深度热爱
