### ISSUE TITLE
repeat中的自定义组件，除了循环参数，其他页面级的参数编译有误。

### ISSUE THREAD

**Issue by bencode** [Tencent/wepy#439]
我的场景如下：

repeat中包含自定义组件，除了循环变量外还会传入一些页面级参数（来源于data），示例代码如下：

```html
<repeat for="{{sections}}" key="index" item="section">
  <block wx:if="{{section.component == 'Brief'}}">
    <Brief :section="section" :product="product" />  <!-- product 是 data -->
  </block>
```

此时编译器会将 product 也当作循环变量作同样处理， 即不按组件的方式编译，编译结果中product相关的变量都没有组件名字空间前缀。
这样Brief中的**子组件**就获取不了product信息， 因为编译器对Brief的子组件中的 product 变量会加前缀，这样就造成了不一致。

在寻求解决方案中，我把repeat改成使用wx:for语句碰到如下问题。

```html
<block wx:for="{{sections}}" wx:key="index" wx:for-index="index" wx:for-item="section">
  <block wx:if="{{section.component == 'Brief'}}">
    <Brief :section="section" :product="product" />  <!-- product 是 data -->
  </block>
```

此时编译器将针对Brief生成带名字空间的 section和product， 所以product参数能够正常使用，但section就获取不到了， 请问能否在编译wx:for时中的子组件时，其对循环变量做下特殊处理，或者提供一些建议我自己来修复也可以。

谢谢：）

**Comment by shiyafei** [comment]
这个问题也遇到过，但是不知道怎么解决
