### ISSUE TITLE
缓存没有清理

### ISSUE THREAD

**Issue by lx307697527** [Tencent/wepy#443]
当更改了样式,编译了后,dist里的文件并没有变更,还是原来的.
每次都只能退出后重新 运行 `wepy build --watch`命令后才能看到改变.
  #@作者能在改改吗?每次watch到变化后先把dist里的文件clean一下吗?

**Comment by Gcaufy** [comment]
watch有编译的日志么？文件一定会变更的。

**Comment by lx307697527** [comment]
不好意思,因为那条issue已经关闭了,所以我重新开了一个issue.
有的,日志有打印,但是文件并没有变更
![image](https://user-images.githubusercontent.com/11769863/31767070-5da0dbf4-b4fc-11e7-9a9e-6a6e52e760c5.png)
甚至我只要保存文件没有改代码,就会打印日志,

**Comment by lx307697527** [comment]
我又从新建立了一个项目试了一下.
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
新建了一个less文件.在里面写了一些样式.
然后在index页面的样式里引入.改动之后发现,样式文件确实是编译成功,也变化了.
但是dist目录下的页面样式文件里并没有变化.猜测可能是只编译了样式文件,但是并没有编译引入到页面样式 @Gcaufy

**Comment by wlchou** [comment]
遇到了同样的问题，并且只会在使用import时有问题。

例如a.wpy中import了base.wxss，那么在修改base.wxss之后，在日志中能看到只更新了dist中的base.wxss，并没有同步刷新a.wpy。在微信开发者工具中，也能看到base.wxss是最新的，但是a.wpy中
import的样式还是旧的。

原因应该和上面所说的一样，没有同步更新引入到页面的样式。

重启开发者工具解决不了问题，现在只能删除dist重新编译，或者手动保存一下a.wpy强制触发编译。

希望能尽快解决 @Gcaufy
