### ISSUE TITLE
repeat循环绑定props在子组件内不能输出绑定的props的值

### ISSUE THREAD

**Issue by zepang** [Tencent/wepy#445]
~~~
子组件
 onLoad() {
      console.log(this.planItem)
      console.log(this.title)
    }
~~~

~~~
父组件
<PlanListItem :planItem="planItem" :title="title"></PlanListItem>
~~~

**Comment by githbq** [comment]
我也发现这个有BUG repeat 里面的  组件传参数  没有用，只会把 整个item传进去  而不会根据实际 需求
例如
 <repeat for="{{demos}}" item="item" index="index">
        <Link :abc="item.url">{{item.text}}</Link>
      </repeat>
abc的值   始终是 item 而不是 item.url

**Comment by MinJieLiu** [comment]
@githbq 为什么我在 repeat 中的自组件的参数永远都是 undefined 呢

**Comment by CodArs-van** [comment]
这这这。。。组件A包含组件B，组件C显示一个组件A的列表，这个感觉是很常用的场景诶。不支持这个功能简直不能忍受啊。。。。啊。。。啊。。。
