### ISSUE TITLE
wpy  模板 内置 wxs  不能使用<

### ISSUE THREAD

**Issue by sailei1** [Tencent/wepy#456]
<template>
  <wxs module='format'>
    var filter = function(s,timer){
        var sec = s-timer;
          sec=typeof sec== 'number' ? sec : 0;
          var  _sec_ = parseInt(sec % 60), _min_ = parseInt(sec / 60);
          var __sec__='0'+_sec_,__min__='0'+_min_;
          var ten=10;
          **var rs=(_sec_<ten) ? _sec_ :__sec__;**
          var rm=(_min_>=ten)? _min_:__min__;
           return rm+":"+rs ;
    }
    module.exports.filter = filter;
  </wxs>

**Comment by sailei1** [comment]
小坑 不能使用小于号，可以避免

**Comment by Gcaufy** [comment]
抱歉。这个在 1.7 的版本没有修复计划，在后续的2的版本中会处理。
