### ISSUE TITLE
wepy 有数据单次绑定的概念嘛

### ISSUE THREAD

**Issue by ystarlongzi** [Tencent/wepy#459]
如题，在开发一个新闻类的小程序，有一个无限加载更多的列表，然后在加载几页后，明显感觉性能下降很快，请问 wepy 里可以对那些不会变动的数据进行单次绑定嘛？

另外，`this.$apply()` 是否会强制对组件内所有数据进行脏检测？

**Comment by ystarlongzi** [comment]
因为在项目里使用了 `wepy-redux`，然后发现曾经打开，但是现在被隐藏的页面，也会触发 `$apply`，然后觉得[这里的代码](https://github.com/wepyjs/wepy/blob/master/packages/wepy-redux/src/connect/index.js#L13-L25) 是否可以加入一些逻辑：
1. 对 `Page` 类型的组件，添加一个字段标记当前页面是否为显示状态（比如：__pageIsShow）
2. 然后在刚才那个 `onStateChange` 函数做个判断，如果发现当前组件是 `Page` 实例，并且是隐藏状态，那就不在比较，直接 return 出去

**Comment by ystarlongzi** [comment]
或者暴露一个类似 `shouldComponentUpdate` 的钩子，有开发者自己来做判断

**Comment by Gcaufy** [comment]
1. 组件的脏检查非常快，即便数据量特别大。
2. setData在数据量特别大的时候会很慢
3. $apply时，只对改变过的数据进行setData。

**Comment by ystarlongzi** [comment]
@Gcaufy 可能是我操作姿势不对，由于之前 react 用习惯了，然后现在在 connect 时，每次有 action 变化，都会返回一个新的对象（即两个对象 `JOSN.stringify` 会相同），这样会影响性能的不？

因为，现在我们有一个简单的新闻列表页，在默认加载的前 15 条时，点击新闻，进入到详情页时，详情页速度打开都很快，但是当下拉了七、八页时，然后在点击进入详情页时，手机就明显感觉很卡

另外，想请教下，除了官方的[性能 Trace 工具](https://mp.weixin.qq.com/debug/wxadoc/dev/framework/performance/tools.html)，你还有了解其它方法不？

**Comment by Gcaufy** [comment]
这种场景数据一样在改变，所以每次都会执行setData，即便是用原生的方式 去写也会卡的。
可能得想一些其它方案，比如不要一直往数组push，一个页面能显示十条，你在push新数据时把已经翻页上去了的数据 再delete掉等等
我也没有这方面的经验，可能还需要你自己再尝试一下。

**Comment by ystarlongzi** [comment]
嗯嗯，好的，谢谢

**Comment by ystarlongzi** [comment]
@Gcaufy 
> 或者暴露一个类似 shouldComponentUpdate 的钩子，有开发者自己来做判断

可以暴露出类似的接口嘛？

**Comment by ystarlongzi** [comment]
@Gcaufy 可以考虑下嘛？😏😏

**Comment by Gcaufy** [comment]
原理不一样，不是一回事。

**Comment by ystarlongzi** [comment]
我想表达的是：暴露出一个接口给开发者，然后有开发者控制 `onStateChange` 的逻辑判断

**Comment by nishino-tsukasa** [comment]
我也遇到了这个问题，也用了connect
列表数据多了之后就很卡，可不可以给些钩子或者参数，主动过滤掉一些属性不走脏检查setData。

**Comment by Gcaufy** [comment]
@nishino-tsukasa apply只会对当前组件中的数据进行脏检查。。。
不想走脏检查的数据可以直接 `delete this.$data[somekey]`

**Comment by skyFi** [comment]
React风格goto: https://github.com/skyFi/weapp-native
