### ISSUE TITLE
wepy new project 安装依赖出错

### ISSUE THREAD

**Issue by lenvonsam** [Tencent/wepy#462]
wepy版本： 1.5.9-6
node版本：6.11.4
npm版本： 5.5.1
运行 wepy new projectname
出现安装依赖错误
![image](https://user-images.githubusercontent.com/10168476/31929797-e0fb5240-b862-11e7-9842-94f04829a37a.png)

**Comment by Gcaufy** [comment]
```
npm cache clean --force
```

**Comment by Gcaufy** [comment]
可以了么？还有问题吗？
