### ISSUE TITLE
wpy  改成 vue 后缀 后 编译报 css 语法错误

### ISSUE THREAD

**Issue by janjon** [Tencent/wepy#475]
亲们确定能改成.vue么, config也改了 但是就是不行

**Comment by lyh2668** [comment]
你可以让wpy后缀的支持vue的语法高亮，一般编辑器都能设置，还有就是issues不是提问的...请勿滥用issues

**Comment by microspaze** [comment]
需要把 .eslintrc.js 文件里面的settings 的 html/html-extensions 里面加上 .vue, 这样就不会报错了
