### ISSUE TITLE
repeat循环子组件问题

### ISSUE THREAD

**Issue by fireflylight66** [Tencent/wepy#476]
场景
```javascript
<repeat for='{{list}}' item='item'>
<child :item='item' :url='item.url' />
</repeat>
```
child
```javascript
{{url}} // 有数据展示
{{item}} // 展示空
{{item.url}} // 有数据展示
<child2 :url='url' />

onLoad(){
console.log(this.url)  // undefined
console.log(this.item)  // undefined
}
```

child2
```javascript
{{url}}  // 展示空
```

具体描述下问题
1. repeat里的child1在onLoad中获取不到  但是模板字面量里是有值的
2. repeat child1里的child2获取不到值

**Comment by Gcaufy** [comment]
repeat在和props混合使用时是有一些问题，这类情况建议直接使用wx:for

**Comment by MinJieLiu** [comment]
@Gcaufy 
> 当想在 `wx:for` 中使用组件时，需要使用辅助标签 `<repeat>`

这是官方文档

目前遇到的问题就是：只要是在 `<repeat>` 中，组件的参数都无法传递，在` wx:for` 中也不行。怎么解？

**Comment by CoderAFI** [comment]
@Gcaufy 同样的问题

**Comment by js571** [comment]
+1

**Comment by Jmingzi** [comment]
+1

**Comment by fireflylight66** [comment]
一点建议
repeat如果需要循环子组件的话 最好用map把list转换成可以直接展示的对象 这样在child中就不用动态计算值了

**Comment by Fycho** [comment]
微信已经在公测自定义组件了，可以用这种方式，https://mp.weixin.qq.com/debug/wxadoc/dev/framework/custom-component/

**Comment by CoderAFI** [comment]
@fireflylight66 thanks.

**Comment by fantasy525** [comment]
+1，我还以为自己写的不对呢，原来这是bug,求官方赶快解决吧，我想像写vue一样写wepy

**Comment by Gcaufy** [comment]
@fantasy525 wepy 的旨意是让小程序更像Vue，但几乎没可能做到和Vue一样。。毕竟受限于原生。。
这个问题就是实现机制的问题，在1.x的版本中几乎解决不了。尽量避免这个问题吧。2.x会重写这一部分。

**Comment by yucopowo** [comment]
这种bug简直都不能正常开发了

**Comment by kirkcola** [comment]
@Gcaufy 
> repeat在和props混合使用时是有一些问题，这类情况建议直接使用wx:for

可是`wx:for`在重复渲染同一个组件时似乎是共享同一个组件实例 会有数据显示上的问题 这也是我只能用`<repeat>`的原因，请问这一点没什么解决方法吗？年前要发版本了可是被这个bug搞得无法继续了...

**Comment by BoleLee** [comment]
在没有使用```wepy```, 小程序官方也还没有出自定义组件的时候，[wux](https://github.com/skyvow/wux)的做法是给组件命名不同，比如循环使用的组件，可以命名com1, com2，组件数据都在com1, com2下属的对象里，不知道这种思路能不能应用到wepy里来 @Gcaufy

**Comment by BoleLee** [comment]
补充：使用repeat循环渲染组件，并使用props传值，其实并没有报错，只是在开发者工具AppData面板无法看到组件上挂载的通过props传值的变量；
- 组件中计算属性使用传入的props变量时报错，报错原因，传入的props变量undefined；
可重现代码：
```
<repeat for="{{list}}" key="index" index="index" item="item">
    <view>{{ item.id }} {{ item.title }}</view>
    <child :arr="item.arr"></child>
  </repeat>

list: [{id: 1, title: 'title1', arr: ['title1-1', 'title1-2']}, {id: 2, title: 'title2', arr: ['title2-1', 'title2-2']}]

child.wpy
<template>
  <view wx:for="{{arr}}" wx:key="index">
    {{ item }}
  </view>
</template>
<script>
  import wepy from 'wepy'

  export default class Child extends wepy.component {
    props = {
      arr: {
        type: Array,
        default: []
      }
    }

    data = {
    }

    computed = {
      total () {
        return this.arr.length
        // return 2
      }
    }
  }
</script>
```

**Comment by BoleLee** [comment]
@Fycho 请问你的意思是说可以在wepy的开发方式下使用小程序自定义组件吗？

**Comment by WingMrL** [comment]
同样的问题，repeat把item.xxx传到子组件this.xxx为undefined。把item直接传过去就几个子组件共同一份数据。。

**Comment by BoleLee** [comment]
@WingMrL  以下是文档中写明的“存在的问题”，要改用别的方式实现你的需求了

> WePY 1.x 版本中，组件使用的是静态编译组件，即组件是在编译阶段编译进页面的，每个组件都是唯一的一个实例，目前只提供简单的 repeat 支持。不支持在 repeat 的组件中去使用 props, computed, watch 等等特性。

**Comment by SycamoreYC** [comment]
@WingMrL 遇到了一样一样的问题，请问你最后是怎么解决的？

**Comment by simdd** [comment]
1. repeat组件props多层传递问题：
解决方法：子组件也用repeat渲染，参数包装成数组，组件取数组第一项

2. repeat组件无法用computed问题:
解决方法：数据在父组件处理好

// 蛋疼

**Comment by vivatoviva** [comment]
> @Gcaufy
> 
> > repeat在和props混合使用时是有一些问题，这类情况建议直接使用wx:for
> 
> 可是`wx:for`在重复渲染同一个组件时似乎是共享同一个组件实例 会有数据显示上的问题 这也是我只能用`<repeat>`的原因，请问这一点没什么解决方法吗？年前要发版本了可是被这个bug搞得无法继续了...

老铁，现在有没有解决这个问题

**Comment by Strong-Man** [comment]
> 同样的问题，repeat把item.xxx传到子组件this.xxx为undefined。把item直接传过去就几个子组件共同一份数据。。

最后这个咋解决,我也遇见了 晕死了啊 啊啊 玩毛~~~~

**Comment by isWill** [comment]
2.0什么时候出来？

**Comment by WingMrL** [comment]
@SycamoreYC @vivatoviva @Strong-Man 

当时是多做了一个组件 ListWrapper 把 repeat 那部分的代码耦合起来。

**Comment by davidloveengles** [comment]
> 1. repeat组件props多层传递问题：
>    解决方法：子组件也用repeat渲染，参数包装成数组，组件取数组第一项
> 2. repeat组件无法用computed问题:
>    解决方法：数据在父组件处理好
> 
> // 蛋疼

问题1按照你的ok，问题2的我的解决方式：
wepy1.7之后支持wxs（文档中有说明），把要计算的方法放在wxs文件中，这样template中就可以调用了！
