### ISSUE TITLE
page 组件的 mixins 的执行时间晚于组件

### ISSUE THREAD

**Issue by ystarlongzi** [Tencent/wepy#482]
在 React、Vue 里的 mixins 执行时间都是早于组件的生命周期，但 wepy 里却是相反，请问这样设计的出发点是什么？

**Comment by ystarlongzi** [comment]
@Gcaufy 可以解答下嘛？

**Comment by Gcaufy** [comment]
这里并没有特殊意图要这么去做，现在是遇到什么问题了或者有什么需求么？有需要的话我觉得调整至组件前运行也是可以的。

**Comment by ystarlongzi** [comment]
@Gcaufy 
现在项目上对所有的页面组件抽象出了一个 mixin，对页面组件添加了一些属性、方法，并且希望在页面组件 onLoad（或其它生命周期） 前执行 mixin 的 onLoad （或其它生命周期），然后 mixin 里会根据业务执行某些方法、或修改某些属性

但是，因为现在 mixin 是晚于组件执行的，所以，就导致在组件内就无法获取正确的属性值

**Comment by excaliburhan** [comment]
@ystarlongzi mixin不操作生命周期，而是抽象自定义的方法与属性，在具体页面的生命周期中，使用this.xxx去访问方法与属性，执行顺序可以根据业务自定义

**Comment by ystarlongzi** [comment]
@excaliburhan 
嗯嗯，你这也是一个问题解决思路👍👍

但因为抽象出的这个 mixin，就是专门给 page 用的，所以希望在引入 mixins 后，就可以完成一些列的初始化操作，并不希望手动在每个 page 的声明周期里执行对应的逻辑

**Comment by Gcaufy** [comment]
通过继承呢？这样可行吗？
```
class myPage extends wepy.page {
    onLoad () {
        // doSomething...
    }
}

class Index extends myPage {
    onLoad () {
        super.onLoad();
        // doSomething...
    }
}

```

**Comment by ystarlongzi** [comment]
@Gcaufy 
个人感觉这个和 @excaliburhan 思路类似，也是需要在 page 组件里手动「调用***下***」。

然后如果没有特别的场景考虑，还是倾向于 mixins 执行时机尽量和社区（React、Vue）常见的做法保持一致会好一点，避免了大家使用时的迷惑、困扰😁😁

**Comment by Gcaufy** [comment]
好的。这个问题你可以PR。
或者我在后面的版本中改过来，问题应该不是很大。

**Comment by ystarlongzi** [comment]
嗯嗯，那我晚上来个 PR 吧
