### ISSUE TITLE
建议：组件名称的大小写问题

### ISSUE THREAD

**Issue by lyh2668** [Tencent/wepy#483]
template里面使用的组件标签名必须和component声明的一致，无法自动根据驼峰式的命名转化成html短横杠的方式，比如tabBar是无法使用<tab-bar>的形式的，Tab也无法使用<tab>的形式。如能实现，体验上会好一些。

**Comment by aben1188** [comment]
驼峰式可以正常使用吧？我使用的就是驼峰式，目前一切正常。

**Comment by lyh2668** [comment]
```
components = {  
  tabBar
}
```
```
<tab-bar></tab-bar>
```
这样使用标签是会出错的，如果无法使用这样标签的形式，在代码的规范上就会感觉不舒服，让我在html里面写驼峰式的标签有些难以接受。

**Comment by aben1188** [comment]
抱歉，前面没看清楚你的要求。现在明白你的意思了，看来你就是传说中的“重度强迫症患者”，哈哈...

不过组件标签名用驼峰式，也有一个额外的好处，那就是一眼就可以看出来这是个WePY组件标签，而不是一个其他普通标签，在WePY框架暂时还不支持转换为html短横杆命名方式的情况下，就这样自我安慰下吧，或许感觉上就会更舒服些、更好接受些了？

**Comment by lyh2668** [comment]
@aben1188 只能这样安慰自己了，主要是vue里面这种方式写惯了有些不舒服^.^将来有充裕的时间可以考虑把这个做进去。

**Comment by Gcaufy** [comment]
这个是已经支持了的，可以参看CHANGELOG

**Comment by lyh2668** [comment]
又去尝试了一下发现可以使用，应该是我自己不够仔细造成的...

**Comment by Gcaufy** [comment]
```
        <group-parent :grouplist="itemccc" :indexa="indexccc" ></group-parent>

    components = {
      'group-parent': ParentGroup,
    }
```

sorry， 抱歉，代码是这样的。等有空了我看一下是否能兼容你这种情况 。

**Comment by lyh2668** [comment]
目前采用的就是上述方法命名的，这个只是小问题，不过主要是写错了没有任何提示，捕获一些异常会友好一些。
