### ISSUE TITLE
编译出错时，能否在界面上加个出错提示？

### ISSUE THREAD

**Issue by yeyifen** [Tencent/wepy#484]
如果编译出错，只会在命令行里提示。开发中我一般不会去关注命令行，导致经常一个错误改了又改，还是有问题，最后才发觉是因为编译出错了，编译后的文件一直是旧的。
    希望能像目前开发vue项目一样，一旦编译报错，直接在当前渲染的页面加个编译出错的遮罩提示

**Comment by grepug** [comment]
小程序又不能插入dom

**Comment by yeyifen** [comment]
小程序叫 wxml，其实不就是dom么？换个叫法而已

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/32541260-140669f6-c4aa-11e7-9327-9f9f0cdeba5d.png)

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/32544404-5770a824-c4b3-11e7-87ed-381fa777619d.png)

**Comment by Gcaufy** [comment]
添加也
```
cliLogs: true // 开启时CLI的warning和error会注入到代码中。
```
