### ISSUE TITLE
在wepy-cli v1.5.9的时候, 事件传递参数, 拿到的是event对象, 在v1.5.9-2没有问题

### ISSUE THREAD

**Issue by godfields** [Tencent/wepy#485]
![wechatimg2572](https://user-images.githubusercontent.com/21139434/32153185-e95c743a-bcf6-11e7-999e-78b452a57a7f.jpeg)

**Comment by Gcaufy** [comment]
升级一下wepy
```
npm install wepy --save
wepy build --no-cache
```

**Comment by ligan21** [comment]
执行 npm install wepy --save
wepy build --no-cache
后 `-- wepy@1.6.0‘
@tap 传递的参数，仍然是 event 对象。

**Comment by rodson** [comment]
我也遇到了这个问题，好像是获取方法参数的代码名称没有匹配对

**Comment by Gcaufy** [comment]
@rodson 升级最新的cli和wepy吧。

**Comment by rodson** [comment]
@Gcaufy 还是不行，而且wepy升级到1.7.0后会有这个问题https://github.com/Tencent/wepy/issues/986

**Comment by rodson** [comment]
@Gcaufy ok了，wepy-cli和wepy版本不一致会有问题

**Comment by iluozhiqiang** [comment]
![image](https://user-images.githubusercontent.com/7245622/41466690-f24227e0-7068-11e8-8e35-5dfff9646319.png)
都最新的了，还是出这个问题，参数为event。搞不懂   总有一些莫名其妙的问题

**Comment by Gcaufy** [comment]
看看
```
wepy -v
```
