### ISSUE TITLE
wepy-cli在处理apis配置时出错

### ISSUE THREAD

**Issue by vchenchong** [Tencent/wepy#492]
`build: {
    web: {
      apis: ['showToast', 'showActionSheet', 'showModal'],
      components: ['navigator', 'button', 'icon', 'progress', 'slider', 'radio', 'radio-group', 'checkbox', 'checkbox-group', 'switch'],
      htmlTemplate: path.join('src', 'index.template.html'),
      htmlOutput: path.join('web', 'index.html'),
      jsOutput: path.join('web', 'index.js')
    }
  }`

wepy-cli/lib/web/index.js 的toWeb方法，在处理webConfig.apis时，传给compile方法的参数是api对应文件的路径，最终导致在compile方法的wpys.forEach时报 ‘TypeError: wpys.forEach is not a function’ 错误。

**Comment by hcpzhe** [comment]
我也遇到了一样的问题. 请问怎么解决?

**Comment by hcpzhe** [comment]
@Gcaufy 来解决一下啊

**Comment by Gcaufy** [comment]
issue内容不可读，
这个issue先关闭了，有需要的话请严格按照 [ISSUE_TEMPLATE](https://github.com/Tencent/wepy/blob/master/.github/ISSUE_TEMPLATE.md) 重提issue

请见谅，因为issue过多，不再对issue内容一个一个修改校对，因此提供ISSUE_TEMPLATE, 节约彼此的时间。

**Comment by fenglui** [comment]
修改全局安装的npm\node_modules\wepy-cli\lib\web下的index.js

        if (webConfig.apis && webConfig.apis.length) {
            webConfig.apis.forEach(function (k) {
                var apiFile = _path2.default.join(wepyWebPkg.dir, 'lib', 'apis', k);
                if (_util2.default.isFile(apiFile + '.vue')) {
                    apiFile = apiFile + '.vue';
                } else {
                    apiFile = apiFile + '.js';
                }
                apis[k] = mmap.add(apiFile);
                tasks.push(_this.compile({
                    id: apis[k],
                    path: apiFile,
                    npm: wepyWebPkg
                }));
            });
        }
