### ISSUE TITLE
 Unknown plugin "transform-class-properties" specified in "base" at 0

### ISSUE THREAD

**Issue by frontHu** [Tencent/wepy#496]
使用wepy生成项目结构，然后使用命令**wepy build --watch**，执行如下报错：
![image](https://user-images.githubusercontent.com/19454392/32364647-fe899af0-c0b0-11e7-99db-9d4e9e3f28e9.png)

**Comment by jeatime6** [comment]
babel少了一些组件：
`npm install babel-plugin-transform-class-properties babel-plugin-transform-decorators-legacy babel-plugin-transform-object-rest-spread --save-dev`

wepy 1.6.0
node 8.0.0
npm 5.0.0

**Comment by jeatime6** [comment]
少了些包：

`npm install babel-plugin-transform-class-properties babel-plugin-transform-decorators-legacy babel-plugin-transform-export-extensions babel-plugin-transform-object-rest-spread babel-preset-env --save dev`

装完后编译通过，然后**重启**下 微信开发者工具，就OK啦。

**Comment by leecanzeng** [comment]
@jeatime6 谢谢你 搞定。
