### ISSUE TITLE
slot组件内容分发无法取到其对象

### ISSUE THREAD

**Issue by lyh2668** [Tencent/wepy#503]
在vue里面使用slot进行组件内容分发的时候往往会通过通过$slots的方式获取到当前组件下分发的内容，然后可以依据$slots.name的方式来确定父组件是否使用该slot，希望能够在this里面添加$slots
```
<span class="" v-if="icon || $slots.icon"></span>
```
比如这样可以方便判断父组件是否使用了slot

**Comment by Songkeys** [comment]
同求。
尤其在实现类似按钮组件的包装的时候。
```
<template>
  <button class="...">{{$slots.default}}</button>
</template>
```
