### ISSUE TITLE
repeat调用组件时组件的watch失效

### ISSUE THREAD

**Issue by mhy-web** [Tencent/wepy#510]
watch 直接没有反应

**Comment by hudongyang** [comment]
同问!
子组件中watch props中的数据无效，而只有第一个子组件中的onLoad会执行

**Comment by Gcaufy** [comment]
暂不支持在repeat中使用Watch

**Comment by hudongyang** [comment]
感谢作者的回复，我们的小程序现在已经上线了，完全基于wepy开发，虽然中间踩了好多坑，但是确认解决了第一版中存在的好多问题。
我们的小程序叫做“天天跟我买”，一个电商类的小程序，日均有一万以上的访问人数。

**Comment by Gcaufy** [comment]
@hudongyang 好的，可以PR在这里：
https://github.com/wepyjs/wepy#哪些小程序是用-wepy-开发的

**Comment by YaoKaiLun** [comment]
不支持在 repeat 中使用 watch，好多功能没法开发呀，希望能尽快支持 🙏

**Comment by Gcaufy** [comment]
@YaoKaiLun 没有开发不了的功能，可能需要换个思路，考虑一下，如果是原生应该怎么写。另外watch个人感觉是一个有些反模式的设计，建议不要太过依赖watch
