### ISSUE TITLE
无法 import redux-saga

### ISSUE THREAD

**Issue by TinkGu** [Tencent/wepy#521]
一旦 import redux-saga，微信开发者工具就报错：

```
WAService.js:14 Uncaught RangeError: Maximum call stack size exceeded
```

# 环境

- osx: latest
- 微信开发者工具：v1.01.1711020
- 微信基础库：1.6.4
- wepy：1.6.0
- redux-saga: 0.15.3 - 0.16.0

**Comment by chenqingspring** [comment]
any updates?

**Comment by dolymood** [comment]
这是因为在 redux-saga 中存在循环引用的逻辑，这个在 wepy-cli 中目前还没有处理循环引用场景， @Gcaufy  看 对于这种循环引用的场景怎么搞比较恰当

**Comment by Gcaufy** [comment]
这个问题可以简单测试一下，在目录下写两个循环引用的模块a.js, b.js
```
// a.js
var b = require('./b');
console.log('In a.js - ' + b);
module.exports = 'a';
```

```
// b.js
var a = require('./a');
console.log('In b.js - ' + a);
module.exports = 'b';
```

在Node环境下模块工作正常，但是在小程序环境下引入`var a = require('./a')`时，运行报
```
Maximum call stack size exceeded
```
而在 `redux-saga` 中正好存在类似的循环引用。因此这个循环引用的总是只能等原生小程序解决

另外，2.x版本中有计划会去修改npm的require机制，到时候应该是可以解决掉npm模块中的循环引用问题。

目前的话，因为`redux-saga`提供一个dist版本，你可以尝试使用一下dist版本看是否可用
```
import takeEvery from 'redux-saga/dist/redux-saga';
```

**Comment by dpzxsm** [comment]
这个问题已经解决了吗？
