### ISSUE TITLE
关于SCSS的常量修改，无法动态修改dist

### ISSUE THREAD

**Issue by lyh2668** [Tencent/wepy#523]
1. 在var.scss文件中定义了一个颜色常量
2. 某个组件@import 'var.scss' 文件
3. wepy build --watch
4. 修改该颜色常量，对应的组件颜色并未变化
5. 删除dist目录对应组件
6. 重新wepy build --watch
7. 该组件样式发生了变化

**结论**
wepy build --watch 没有监控到scss中常量的数值变化

**Comment by Gcaufy** [comment]
你这个结论太突然了。 =。=

wepy暂时没有监控到scss中import的文件的变化
不使用import, 改成这样写就可以被监听到了
```
<style src="var.scss" lang="scss"></style>
<style src="main.scss" lang="scss"></style>
```

**Comment by lyh2668** [comment]
@Gcaufy 习惯采用@import的方式引入了，不过重新watch就能生效了，也不算什么大问题，就是麻烦一点，哦对，还有个问题，就是删除文件的时候可能会没有watch到，导致的后果就是dist里面存在而实际已经删除，则会报错，而且重新wepy build也无效
