### ISSUE TITLE
props传参，父组件的参数更改无法传递到子组件，有人说是因为子组件的onLoad优于父组件onLoad

### ISSUE THREAD

**Issue by 1162257086** [Tencent/wepy#526]
父组件的list在接口请求后获取，此时动态绑定父组件的对象更改，但通过props，无法传递到子组件，请问怎么解决，不然props存在的灵活性就非常低了

**Comment by Gcaufy** [comment]
是不是没有加`.sync`

**Comment by 1162257086** [comment]
我试了下，这样可以，能说下两者在源码层实现的区别么，一个没有进行脏检测，还是什么

**Comment by HP-Ekrn** [comment]
我这边是onload里初次赋值 可以绑定，再次通过父组件点击事件更新绑定的值的话 不会同步至子组件，晕死了

**Comment by Gcaufy** [comment]
@1162257086 
`:num="mynum"` : 在子组件初始化时，会把$parents.mynum clone 给 this.num
`:num.sync="mynum"`:  初始化时处理一次，$digest时，也会再clone一次

**Comment by fanlide** [comment]
@Gcaufy 我这边遇到了类似的问题，但我是子组件渲染出来了的，也就是获取到了数据，但子组件的onLoad中this取不到值。是我数据在父组件的onLoad中初始化的原因吗？

**Comment by fanlide** [comment]
@Gcaufy 我看了下，的确是子组件onLoad先输出undefined，然后界面才渲染出数据的。我父组件onLoad中是异步获取的数据

**Comment by Gcaufy** [comment]
@fanlide 如果是异步sync过去的数据，onload中肯定是取不到值的。

**Comment by fanlide** [comment]
@Gcaufy 父组件渲染的时候是判断了的，应该是获取到数据后才渲染的子组件吧
`        <repeat for="{{module_infos}}" key="index">`
`                <eid :module.sync="item"/>`
`        </repeat>`
代码如上

**Comment by Gcaufy** [comment]
@fanlide repeat子组件时，onload中是拿不到数据 的。只能在tap等事件中取到数据

**Comment by ColMugX** [comment]
@Gcaufy 有个差不多的问题。我这边验证过确实是子组件渲染快过父组件导致父组件传来的值丢失，但是我用了`.sync`也无济于事

```js
total: {
    type: Array,
    default: 4
  },
```

每次都会直接取到`4`，如果没有默认值直接不渲染。

**Comment by Gcaufy** [comment]
@ColMugX 给的信息太少，看不出问题，建议新开ISSUE

**Comment by LuckyDing** [comment]
@Gcaufy 有些值要根据传过来的数据计算，在onload中如果用sync取不到，那要怎么处理呢

**Comment by duanduan2288** [comment]
在watch里面处理可以吗
