### ISSUE TITLE
repeat中组件初始化与子组件重复ID问题

### ISSUE THREAD

**Issue by fanlide** [Tencent/wepy#530]
1、用repeat循环渲染组件时，组件的onLoad方法为什么只有第一个执行了，后面渲染的组件都未执行？
我是想对props接收到的数据进行处理，在构造方法中会报错，onLoad方法又出现这个问题。往解决
2、用repeat渲染的组件中，它的子组件的ID是重复的，这就导致数据变化都一样了。这个很恼火，目前我把引用的子组件写在了引用它的组件中了，这样貌似就未出现数据变化一样的问题了。但这样做组件重用又有何用

**Comment by wulunyi** [comment]
#193
#198

**Comment by fanlide** [comment]
@wulunyi 这两个都是跟我第二个问题有关的吧，不过我的情况不一样。我这里举个例：

    **组件A中引入了组件B，然后在页面C中用repeat循环渲染了组件A。**
这样导致了页面C中的B组件（C未有直接组件B）数据变化重复。

我知道这是ID重复导致的，但是怎么解决呢？这种情况手动改不了ID呀

**Comment by fanlide** [comment]
都没人回复吗……问题一的组件数据初始化问题真的很需要呀，有个替换方法也行呀

**Comment by Gcaufy** [comment]
```
**组件A中引入了组件B，然后在页面C中用repeat循环渲染了组件A。**
```

这种比较复杂的场景，如果不熟悉repeat原理的话建议不要使用repeat。如果一定要使用的话请严格参考demo中的repeat实例。

**Comment by shmy** [comment]
@fanlide 请问你解决了吗？我也遇到这种问题

**Comment by fanlide** [comment]
@shmy 你说的是哪个问题？
第一个问题，后期我把数据处理好了再传过去的。
第二个问题，用的我上面写的方法，没有解决重复ID的问题。

注：这是我最后的时候的解决办法，但几个月没写过小程序了，不针对当前版本

**Comment by shmy** [comment]
@fanlide 第一问题，哎 props也不支持绑定对象属性，这下莫法搞了

**Comment by LuckyDing** [comment]
楼主这么问题解决没

**Comment by CodArs-van** [comment]
这这这。。。组件A包含组件B，组件C显示一个组件A的列表，这个感觉是很常用的场景诶。不支持这个功能简直不能忍受啊。。。。啊。。。啊。。。
