### ISSUE TITLE
tap传参数的问题

### ISSUE THREAD

**Issue by lyh2668** [Tencent/wepy#531]
1. tap传递参数感觉异常麻烦，如果参数多一点就特别不舒服
```
<view @tab="onTap({{p1}}, {{p2}}, {{p3}})">
```
2. 然后$emit出来的事件是无法传递参数的
```
child:
this.$emit('someEvent', params)
parent:
<view @someEvent.user="doSomething">

methods = {
  doSomething (params, event) {
    // 这里只能接受 child传递过来的params以及event
    // 如果我想在这个自定事件里面传递一些参数进来是无法实现的
  }
}

以下两种都是不行的
<view @someEvent.user="doSomething({{item}}, {{index}})"> // 报错
<view @someEvent.user="doSomething" data-index="index" data-item="item"> // 无法获取绑定的index & item
```

**Comment by Gcaufy** [comment]
1. 如果觉得麻烦那你可以使用原生的办法：
```
<view id="tapTest" data-hi="WeChat" bindtap="tapName"> Click me! </view>
```

2. 自定义方法只能接收$emit的参数

**Comment by lyh2668** [comment]
@Gcaufy 自定义事件若只能接受$emit的参数那对于循环组件的自定义事件就无法传递index从而判断是哪个组件触发的。

**Comment by cuijiemmx** [comment]
唉，也遇到这个坑了...
话说wepy什么时候更新？？

**Comment by cuijiemmx** [comment]
@lyh2668 有个办法和你分享下，repeat里通过:index.sync把index传到子组件里去，子组件$emit的时候再把这个index带上 - -||，我已经在这么用了唉...

**Comment by cuijiemmx** [comment]
@EliazTray 难受就对了，类似的workaround我还有一些，可以写一个跳坑自救专题了，你这都算小问题
友情提示试一下mpVue

**Comment by banxi1988** [comment]
我一开始写
`@tap="markDone({{index}})"` 传参无效，然后才搜索到这里来的。
微信的个类 Vue 的框架，跟 Vue 很多细节其实差距很大。

**Comment by cmdreay** [comment]
@banxi1988  我也遇到这个问题了 蛋疼

**Comment by banxi1988** [comment]
@cmdreay 
不知道我在这里推荐 mpvue 妥不妥， 不过实话，我已经放弃 wepy 转投 mpvue 了。

**Comment by chengpan168** [comment]
这样是可以生效的
<view class="item" @tap="onItemTap('{{item.id}}')">
          <view class="title">{{item.title}}</view>
          <view class="detail">{{item.content}}</view>
          <view class="foot">
            <view class="time">{{item.time}}</view>
          </view>
        </view>

**Comment by HenseyVenom** [comment]
<view class='handle flexC' @tap="phoneFun('{{courseDetail.telephone}}')" >
        <image src='/images/star_dark.png'></image>
        <text>收藏</text>
      </view>
phoneFun(phone) {
        console.log('phone:',phone)
      },
这样写并不能传递进来参数

**Comment by HenseyVenom** [comment]
原来是网络请求后需要调用this.$apply();来刷新页面数据，
然后页面中<view class='handle flexC' @tap="phoneFun('{{courseDetail.telephone}}')" >才会穿递成功正确的值

**Comment by jimStyle88** [comment]
> <view class='handle flexC' @tap="phoneFun('{{courseDetail.telephone}}')" >
> ![](/images/star_dark.png)
> 收藏
> 
> phoneFun(phone) {
> console.log('phone:',phone)
> },
> 这样写并不能传递进来参数

我也遇到同样的问题，但是异步请求的时候，我调用的this.$apply(), 拿到的还是
![image](https://user-images.githubusercontent.com/20588608/64471637-7cbb8e00-d186-11e9-8d1f-968c565cccce.png)
请问大佬应该如何解决
