### ISSUE TITLE
&npsb;会报错

### ISSUE THREAD

**Issue by EasonShen1989** [Tencent/wepy#535]
`   <text class="desc"
                decode="{{true}}"
                space="{{true}}">1.不限次数&npsb;2.每次骑行前60分钟免费
     </text>`
    TypeError: Cannot read property 'dir' of undefined

**Comment by Gcaufy** [comment]
错误信息和你贴的内容有必然联系么？

**Comment by zlm919** [comment]
我也遇到了
[Error] ERROR IN : src/components/statisticstable.wpy
[xmldom error]	entity not found:&nbsp;
@#[line:undefined,col:undefined]

statisticstable.wpy文件里面有这个&nbsp;
<text decode="true">&nbsp;</text>

**Comment by guider** [comment]
这个问题这么久了还没解决吗?

**Comment by zlm919** [comment]
@guider 
这样写 就可以了
 <text space="true">nbsp</text>

**Comment by zlm919** [comment]
@guider 这样写可以显示空格
` <text space="true">nbsp</text>`

**Comment by intome** [comment]
@zlm919 不可以的你这方法

**Comment by yangchaojiang** [comment]
我也出现了/

**Comment by Ceeson** [comment]
我的也是，效果出来了，但是报错！

**Comment by yangchaojiang** [comment]
有一个解决方法，，把你的&npsb; 做成变量就行了， 页面引用该变量就行了 @zlm919 @guider @Gcaufy

**Comment by OldisNewXrf** [comment]
所以怎么解决的 ？？？？ @ @Gcaufy
