### ISSUE TITLE
页面的数据缓存问题

### ISSUE THREAD

**Issue by jessjava** [Tencent/wepy#536]
wepy 
这个页面是详情,id 会通过 options.id 来传递
1.从列表进来这个页面的时候第一次传递 ID：1，查询到的 name 为111111111111；
 **然后点击左上角的返回，返回到列表，从列表点击另一项查看第二条数据：**
2. 加载ID 为2的商品时，页面会残留 ID 为1的商品数据（name）
 也就是说：
 第一次进来 console结果为“”空
 第二次进来首先输出了上一次的 name 值：1111111111111，通过 options.id查询之后视图中的 name才闪现变化为2222222.
3.当网络慢的时候，会有明显的闪烁痕迹
4.当有大段的文章和图片时，会让人抓狂

PS：小程序原生没有这种问题

```
export default class auth extends wepy.page {
     data={name:""}
     onLoad(options){
        console.error(this.data);
       //模拟请求,findById (options.id)
        setTimeout(res=>{
        if(options.id==1){this.data="1111111111111";}else if(options.id==2){this.data="2222222222";}
        this.$apply();
        },2000)
     }
}

```

**Comment by Gcaufy** [comment]
```
<template>
    <view @tap="go">{{id}}</view>
</template>

<script>
  import wepy from 'wepy';

  export default class Web extends wepy.page {
    data = {
      id: ''
    };
    methods = {
      go () {
        this.$redirect('./web', {id: +new Date()})
      }
    };
    onLoad (option, data) {
      setTimeout(res => {
          this.src = option.id;
          this.$apply();
      }, 2000)
    };
  }
</script>

```
经测试没有任何问题。

两个页面 `navigate -> back -> navigate` 也测试过

**Comment by jessjava** [comment]
您测试是在开发者工具的吧？
您可以在手机微信小程序中打开 console 模式，看看日志。
很多人提这个问题。是真的。（开发者工具没问题）


在2017年11月15日 17:31，Gcaufy<notifications@github.com> 写道：
<template>
    <view @tap="go">{{id}}</view>
</template>

<script>
  import wepy from 'wepy';

  export default class Web extends wepy.page {
    data = {
      id: ''
    };
    methods = {
      go () {
        this.$redirect('./web', {id: +new Date()})
      }
    };
    onLoad (option, data) {
      setTimeout(res => {
          this.src = option.id;
          this.$apply();
      }, 2000)
    };
  }
</script>



经测试没有任何问题。

两个页面 navigate -> back -> navigate 也测试过

**Comment by dgburn** [comment]
2017.02的帖子 现在是2018.01.24，一年了还没有解决掉这个问题么

**Comment by 86chenjie** [comment]
我也被这个问题坑死了

**Comment by Gcaufy** [comment]
@jessjava 

测试代码：
```
<template>
    <view @tap="go">{{id}}</view>
</template>

<script>
  import wepy from 'wepy';

  export default class Web extends wepy.page {
    data = {
      id: ''
    };
    methods = {
      go () {
        this.$redirect('./web', {id: +new Date()})
      }
    };
    onLoad (option, data) {
      this.src = 'loading';
      setTimeout(res => {
          this.src = option.id || 'unset';
          this.$apply();
      }, 2000)
    };
  }
</script>

```

真机测试表现符合预期

![ezgif com-crop](https://user-images.githubusercontent.com/2182004/35545555-950b895a-05aa-11e8-9a12-f85f1bd730e4.gif)

**Comment by Gcaufy** [comment]
@dgburn @86chenjie 

这个ISSUE我完全没有办法复现你们的问题，issue中请提供有效的信息方便我还原。

**Comment by 86chenjie** [comment]
@Gcaufy   这个我用原生方式测试过，原生没有问题。
您要使用性能差的手机，例如，内存512M或1个G的，页面多放点东西。

**Comment by Gcaufy** [comment]
@86chenjie DEMO的确是有问题的，但是我不知道代码是怎么写的。。
参考github的源码。我修改了一下，测试也是正常的。。。
你看看你是否能用那个github代码去还原这个问题呢。
https://github.com/Thunf/wepy-demo-bookmall/pull/2

**Comment by 86chenjie** [comment]
@Gcaufy 
链接: https://pan.baidu.com/s/1pNqSHwZ 密码: 26tb
您看看这个视频，相关代码我贴上来
page1有2个按钮，test1/test2，分别跳转到 test?from=1 / test?from=2
```Javascript```
methods = {
      test1 () {
        wepy.navigateTo({
          url: 'test?from=1'
        })
      },
      test2 () {
        wepy.navigateTo({
          url: 'test?from=2'
        })
      }
    }
```Javascript```

page2主要代码如下：
·```Javascript```
<style lang="less">
</style>

<template>
  <view class="weui-loadmore middle_loading" hidden="{{!loading}}">
      <view class="weui-loading"></view>
      <view class="weui-loadmore__tips">正在加载</view>
  </view>
  <view class="page" hidden="{{loading}}">
    <view class="page__hd">
        <view class="page__title">我的成绩单</view>
        <view class="page__desc">{{paper.name}}</view>
    </view>
  </view>
</template>

<script>
  import wepy from 'wepy'

  export default class Index extends wepy.page {
    config = {
      navigationBarTitleText: ''
    }
    components = {
    }
    mixins = []

    data = {
      paper: {},
      loading: true
    }
    computed = {
    }

    methods = {
    }

    events = {
    }

    async onLoad(options) {
      this.loading = true
      setTimeout(() => {
        if (options.from === '1') {
          this.paper = { name: '测试1111111111111111' }
        } else if (options.from === '2') {
          this.paper = { name: '测试222222222222222222' }
        }
        this.loading = false
        this.$apply()
      }, 2000)
    }
  }
</script>

```Javascript```

**Comment by jessjava** [comment]
还是存在问题 @86chenjie 你解决了没。

**Comment by jessjava** [comment]
@Gcaufy iphone上问题依旧。我现在处理的办法就是 onload 的时候把自己页面所有的 data 都重置一次。哎！！！

**Comment by jessjava** [comment]
@86chenjie 我看了很多 wepy 开源的工程代码、一般偷懒就是写 loading=true 页面上残留的地方用这个 boolean 变量控制显示。
原生有没有好的解决方案呢。比如组件事件传递、promise、页面间的通信

**Comment by jessjava** [comment]
@ @86chenjie 真的很奇怪，作者不重视这个问题。

**Comment by 86chenjie** [comment]
@jessjava 原生的就按照标准写法，没有任何问题。

**Comment by jessjava** [comment]
@86chenjie 不好取舍。。又想偷懒。

**Comment by 86chenjie** [comment]
@jessjava 还是用原生的吧  你不会想要和我一样，用wepy写完后，再重新用原生写一遍。

**Comment by jessjava** [comment]
@86chenjie 觉得其他都挺好，不知道这么多人用就没发现问题么。。

**Comment by tolerance-go** [comment]
@jessjava  https://github.com/tolerance-go/weapp-start

**Comment by hiblacker** [comment]
隔壁mpvue出现同样问题，气氛好像比我们这好很多
@Gcaufy  这个问题开发者解决不了（只能hack），而原生没问题，会产生强烈的不安全感
这是个很普遍且严重的问题，应该给一个解决方案，让开发者知道问题出在哪里，如何去解决，很有必要
https://github.com/Meituan-Dianping/mpvue/issues/140

**Comment by xiaochouyu2663** [comment]
我也遇到了这个问题 ，还没解决吗
