### ISSUE TITLE
TypeError: Cannot read property 'script' of null

### ISSUE THREAD

**Issue by jayconscious** [Tencent/wepy#538]
![image](https://user-images.githubusercontent.com/29750917/32870497-1b53a738-cab7-11e7-8aa0-5e007e8af9ba.png)
why?

**Comment by Gcaufy** [comment]
没有script标签？

**Comment by jayconscious** [comment]
![image](https://user-images.githubusercontent.com/29750917/32871485-417325ec-cabc-11e7-975b-c07c2f49aaf8.png)
在升级wepy-cli后，出现了这个问题

**Comment by Gcaufy** [comment]
能否提供代码给我测试还原一下？

**Comment by ppishero** [comment]
我今天也遇到了

**Comment by ppishero** [comment]
@jayconscious 我问题解决了，是因为有空内容的文件导致的

**Comment by Gcaufy** [comment]
@ppishero 感谢，后面会修复这个问题

**Comment by jayconscious** [comment]
@ppishero  thanks

**Comment by jingchaocheng** [comment]
@ppishero 谢谢

**Comment by towry** [comment]
问题真多

**Comment by Gcaufy** [comment]
```
npm install wepy-cli@1.6.1-alpha7 -g
```
