### ISSUE TITLE
[bug]组件样式使用less scoped后生成的hash和引用该组件的父组件不一致

### ISSUE THREAD

**Issue by lkspc** [Tencent/wepy#539]
我发现 wepy.component 并没有真正的组件化，build 后的代码是把自定义组件的结构（wxml）完整的拷贝到父组件（wepy.page）的位置，然后引用了子组件的 wxss 和 js 。
在子组件中使用 scoped less style，build 后子组件的 class 上有 hash， 比如是 a12345。
而父组件上却可能是 b12345，并且所有引用该子组件的页面，都有hash b12345。

1. wepy.component 能不能真正的组件化？这样应该会省很多空间。目前 build 后的 dist 目录里面，组件.wxml 其实是无用的。我看到小程序官网最近公测了[自定义组件](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=34fde56e6ee55dac840952f4bf46cbfb)，能否加入进来？ 
2. scoped 的问题请留意一下。

**Comment by lkspc** [comment]
@Gcaufy  scoped 问题能看一下吗。我看到最近的 issue 都有回复，就我这个没有。

组件 tabbar.wpy (wepy.component) 结构大致如下：
```xml
<template>
  <view class="tabbar">
    <view class="tabbar-tabs" style="border-color: {{style.borderColor}}">
      <repeat for="{{tabs}}" key="index" index="index" item="item">
        <view class="tabbar-tab" style="{{activeIndex === index ? activeTabStyle : tabStyle}}" bindtap="onTabChange({{index}})">
          <image class="tab-icon" src="{{activeIndex === index ? item.selectedIconPath : item.iconPath}}"/>
          <view class="tab-label">{{item.text}}</view>
        </view>
      </repeat>
    </view>
    <view class="tabbar-panels">
      <slot name="tab" class="tabbar-panel">
      </slot>
    </view>
  </view>
</template>
```
使用less scoped编译过后的 style 添加了 hash _7bef18a：
```css
.tabbar._7bef18a {
  height: 100%;
}

.tabbar .tabbar-tabs._7bef18a {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  height: 112rpx;
  border-top: 1rpx solid #000;
  background-color: #fff;
  display: flex;
}
```
然后有一个页面 index.wpy (wepy.page) 引用了这个 tabbar 组件:
```xml
<style>
page {
  height: 100%;
}
</style>

<template>
  <tabbar :tabs="tabs" :style="tabStyle" :activeIndex="activeIndex">
    <view slot="tab" class="tabbar-panel" hidden="{{activeIndex !== 0}}">
      <home/>
    </view>
    <view slot="tab" class="tabbar-panel" hidden="{{activeIndex !== 1}}">
      <exch/>
    </view>
    <view slot="tab" class="tabbar-panel" hidden="{{activeIndex !== 2}}">
      <records/>
    </view>
    <view slot="tab" class="tabbar-panel" hidden="{{activeIndex !== 3}}">
      <points/>
    </view>
    <view slot="tab" class="tabbar-panel" hidden="{{activeIndex !== 4}}">
      <my/>
    </view>
  </tabbar>
</template>
```
最后生成的 index.wxss 是这样的，它的 hash 和组件的 hash 不一致，导致样式无效：
```xml
<view class="tabbar _3ec90ac">
  <view class="tabbar-tabs _3ec90ac" style="border-color: {{$tabbar$style.borderColor}}">
  </view>
</view>
```

顺便问下，hash 能不能直接连接在 class 上面，比如 tabs_3ec90ac

**Comment by Gcaufy** [comment]
刚才测试了一下，com添加scope后，不会编译page. 因此page中的 hash 可能没生成。再次保存一下page就可以了。
测试过程中得到的hash都是一样的。不存在不一致的情况

**Comment by lkspc** [comment]
我提供了一个复现的例子，放到百度云了 [http://pan.baidu.com/s/1mhXvuR2](http://pan.baidu.com/s/1mhXvuR2)，麻烦你看一下。我已经打包好了2个版本，dist-with-scoped 和 dist-with-no-scoped

**Comment by lkspc** [comment]
@Gcaufy

**Comment by 1162257086** [comment]
@lkspc <style lang="less" scoped></style> 这种scoped样式不能被编译解析吧

**Comment by lkspc** [comment]
@1162257086 你可以试试我的例子

**Comment by 1162257086** [comment]
@lkspc 我用你的demo编译报错，我是1.6.0的版本

**Comment by lkspc** [comment]
@1162257086 我的也是 1.6.0 版本。编译过程应该和 wepy-cli 无关，关键是 package.json 里面的 devDependencies。我是用 yarn 来安装的，应该会和 npm install 表现不一致，我测试一下 npm install

**Comment by lkspc** [comment]
@1162257086 我用 npm install 还是一样的，有 hash， 但是不一致。报错倒没有，这个 demo 是用 wepy new demo 来生成的，然后修改了 pages/index 和增加了 components/tabbar

**Comment by 1162257086** [comment]
我用wepy-cli new一个，发现在style后面加入scoped，里面的样式也是解析不了，我一直很怀疑作者到底有没有针对子组件样式打包生成不同的hash值 @lkspc

**Comment by lkspc** [comment]
@1162257086 这个不是解析的问题，只是 hash 没处理好。wepy 的组件是用的文本替换，编译过后子组件是不存在的，它的内容完整的替换到了父组件中相应的位置。我遇到的问题是，子组件 scoped 编译的 hash 和 父组件编译后的 class 上的 hash 不一致。
比如 子组件编译后的 wxss 文件里面是 `.child._abcdefg`，但是 父组件 上对应的位置是 `<view class="child _xyzw"/>`。2个 hash 不一致，所以样式没有生效。更有意思的是，假设这个 子组件 被多个父组件引用，每个父组件的对应位置都是 `<view class="child _xyzw"/>`，也就是说所有父组件对子组件的引用都正确地使用了同样的 hash , 但偏偏就是和 子组件 hash 不一致

**Comment by 1162257086** [comment]
明白你的问题，hash值应该始终和子组件本身一致，父组件应该只是负责copy，而不应该单独在父组件里生成一个莫名奇妙的hash值

**Comment by 1162257086** [comment]
那现在就造成了子组件没办法不被父组件里的样式影响了，除非父组件与子组件class完全隔开

**Comment by lkspc** [comment]
是的，我现在的项目里面不可避免地用到相同的类名，就算用 less 来包裹过每个子组件的类名也容易冲突。如果这个bug一直不解决的话，最终只能手动把子组件的 hash 改来和父组件一致了

**Comment by 1162257086** [comment]
我一直思考想解决的也是这个问题，因为一个团队开发，很多不可避免的因素之一就是样式名会出现重复，现在我的做法，也是最外层用一个基本不会被覆盖的总样式来包裹，但是这终究不是一个好的结局方案，希望作者能给予重视并修复 @lkspc @Gcaufy

**Comment by Gcaufy** [comment]
@1162257086 抱歉，事情比较多，今天或者明天看看这个问题。

**Comment by Gcaufy** [comment]
@lkspc @1162257086 
这个问题是由于windows的路径问题造成的。。hash根据路径生成。
编译组件使用的路径是 e:\abc\com\coma.wpy
结果编译页面时，使用的路径是 e:\abc/com/coma.wpy
所以导致了hash不一样。
只需要修改一行代码即可。你们也可以参考commit修改对应位置代码验证一下。

**Comment by lkspc** [comment]
@Gcaufy 果然可以了，感谢。在这里顺便问几个问题
1。 可以将一个组件作为prop传递到另一个组件吗
2。style scoped 如何使用连接的 hash ，比如 `.className._hash` ，而不是 `.className  ._hash`

**Comment by Gcaufy** [comment]
1. 不行
2. 没太明白你的意思

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/527

**Comment by lkspc** [comment]
@Gcaufy 目前的 scoped 是在原 className 上添加一个 Hash 类名来做到的。
如：
```css
.example {
}
```
```xml
<view class="example"></view>
```
最后会编译成
```css
.example._hash12345 {
}
```
```xml
<view class="example _hash12345"></view>
```

事实上我觉得这种方式还是有和其他 style 冲突的可能，毕竟 className 可能重复使用。
我的意思是，如果将原来的 className 与 hash 拼接在一起来编译可以吗？
比如编译成如下：
```css
.example_hash12345 {
}
```
```xml
<view class="example_hash12345"></view>
```

**Comment by Gcaufy** [comment]
@lkspc 可以的，但是成本更高。
现在这种方式冲突的可能性还是非常小吧，谁会去定义一下带hash的class呢。

**Comment by lkspc** [comment]
@Gcaufy 这个 hash 是自动编译添加的，不影响开发，没啥成本吧。某些自定义组件就需要这种完全封闭的 style 环境。如果要做到的话，修改起来麻烦么？如果简单，你又有时间，就麻烦添加一下这个功能（我建议用 `combined-scoped` 来区分或者直接定义成默认行为）；或者我空闲的时候提个 PR。<br>
用这种方式主要是考虑到 className 冲突，以及避免 className 嵌套或者并列太多。
像目前的处理方式，假如有组件 tabbar， 定义了类名为 `.tabbar`，结果会编译成 `.tabbar._hash12345`。如果父组件又定义了非 scoped 的
```css
.tabbar {
  display: none;
}
```
那么 tabbar 组件肯定会受到影响。
而现在只需要把每个 className 都 replace 为 className + hash 的形式就可以完全杜绝这种行为了。
```css
.example {
}

.example .demo {
}

.example .demo .foo {
}
```
编译为：
```css
.example_hash1234 {
}

.example_hash1234 .demo_hash1234 {
}

.example_hash1234 .demo_hash1234 .foo_hash1234 {
}
```

**Comment by Gcaufy** [comment]
@lkspc 同意。那你可以尝试PR一下。

**Comment by dolymood** [comment]
@Gcaufy  @lkspc 
这个可能是scoped的理解问题吧。本质上来说scoped真正做的事情是样式局部化，也就是说是这个组件中的样式不会影响其他部分的样式，而不是说class会重复的问题；这个也是符合 scoped 样式相关规范的做法的。

在组件化的情况下，每个组件都应该有自己这个组件的class的，而不是A组件用a的class，B组件也是a的class，合理的是B组件用b的class。

如果采用 @lkspc  的编译结果的话，有一件事就没法做了，就是父组件去覆盖子组件样式，因为这种场景还是很常见的。

这里我的建议是：保留scoped现有的功能。如果说真的要支持  className + hash 的这种形式的话，应该是换一种特性，例如新增一个 solitary 属性，或者类似这种含义的。

**Comment by lkspc** [comment]
@dolymood  这个 scoped 的理解就是`局部作用域`，像一间封闭起来的小房子，外层不能也不应该影响到我，可以用 js 闭包 或者 es6 的作用域来理解这个问题：
```js
{
 // 这里的 scoped 就是封闭的，外界无法访问
 let scoped = 'scoped';
}
scoped = 'global'; // error, scoped is not defined
```
<br>
如果希望样式可以被修改，那么就不应该使用 scoped 。常见的一些 UI 库，每个组件类都带有自己的前缀，而不是使用 scoped ，这样能保证 className 不容易重复，同时也可以修改。

**Comment by dolymood** [comment]
@lkspc  scoped相关规范（虽然后来被remove了 http://w3c.github.io/html-reference/style.html#style.attrs.scoped）你可以看下，或者市面上 scoped 的实现，和你理解的还是不一样的。

**Comment by lkspc** [comment]
> Indicates that the specified style information is meant to apply only to the style element’s parent element, and that element’s child nodes. Otherwise, the specified styles are meant to apply to the entire document.

指定的样式仅用于其父元素及其子节点。这仅仅是一个概念，并不偏向你的理解或者我的理解。<br>
我觉得这个“仅用于”可以理解为“不可用于”其他元素，也就是这个类名是私有的，使用连接型的 hash 就能保证是私有的。如果希望样式可以被修改，就不应该使用 scoped 。确实目前大部分 scoped 的实现都是按你说的那种方式实现的，但是我个人认为会增加类的嵌套，而且无法避免真正意义上的 scoped 。<br>
这只是理解不同和主流实现方式不同，不过同时保留这2种方式也是可取的。

**Comment by dolymood** [comment]
@lkspc  私有的理解是没错的，但是私有并不是等同于类名是唯一的。

CSS 的一个基础就是继承机制，可以看规范的 https://www.w3.org/TR/css-cascade-3/#cascade-scope 这部分，注解里写的就是，正常声明的话，确实是scope中的样式会把外边的覆盖掉，但是如果是!important规则的话，依旧是外边的!important优先级比较高。注意是覆盖掉，而不是互不影响。

由于说 style 的 scoped 暂时被废弃了，css的scope部分还是保留了，他们是一一对应的。

scope所影响的不仅仅是类名 可以是任意选择器，所以不要纠结于这里的类名；这里的加一个额外的class或者加一个属性，利用他们达到一种效果就是：在scope中的样式比外边的优先级要高，同时不影响外层其他相同选择器的值。

**Comment by dolymood** [comment]
@1162257086  @lkspc  关于类名覆盖的问题，可以在应用层面选择所有组件都应用 scoped 就不用考虑互相影响的问题了。

**Comment by JourneyL** [comment]
@Gcaufy  我想问下wepy-cli这个文件夹在哪 我的node_modules里没有啊 我是mac也出现了如上问题 把scoped去掉就没错了 可是别的同事就没有问题 新买的电脑不太会用。。 v1.6.0
