### ISSUE TITLE
用wepy开发的小程序，提交微信审核，反馈页面打不开？

### ISSUE THREAD

**Issue by winglau14** [Tencent/wepy#545]
用wepy开发的小程序，提交微信审核，反馈页面打不开？

**Comment by Gcaufy** [comment]
看看是不是有一些兼容性问题，多测试一些机型
我们自己的WePY项目都已经上线了

**Comment by winglau14** [comment]
我按照你们说的关闭了ES6转ES5，自动补全，压缩那几项，提交过去微信那边还是说，页面打不开！请问下，微信那边测试是不是也是下载提交过去的包，然后用开发者工具打开预览扫码测试，然后他们是没有关闭那几个选项，然后就报错，打不开页面了

**Comment by winglau14** [comment]
提交审核包是直接运行wepy build --watch，生成的dist包提交到微信？

**Comment by Gcaufy** [comment]
建议用`npm run build`打包dist
另外，这个问题可能是兼容性问题，你用什么手机测试的？多找一些不同的机型测试一下试试。

**Comment by winglau14** [comment]
npm run build打包dist，试过了，还是一样，用了iphone6sp,iphone6,iphone5s,安卓oppo R9,vivo v3,小米6，都是能打开页面的，都没什么问题，提交到微信那边就说有问题了。
还有我有个检测用户是否有权限的方法用到了async await，后面我改了，勾选上es6转es5就不会报错了

**Comment by yuanyuanyuan** [comment]
你先走走微信 ide 自带的自动测试，是否也打不开第一页？  是否用了 webview？webview 做第一页的话微信审核会过不了，可能跟他们的测试检查机制有关，所以暂时不要用 webview 做第一页
