### ISSUE TITLE
wepy new myproject 编译失败

### ISSUE THREAD

**Issue by xiaoyedeng** [Tencent/wepy#556]
node 和npm都是最新的
![image](https://user-images.githubusercontent.com/7610852/33122434-2d6606be-cfb2-11e7-8639-dfe9d6626327.png)
可能是啥原因呢？

**Comment by xiaoyedeng** [comment]
版本
![image](https://user-images.githubusercontent.com/7610852/33122507-60cabef0-cfb2-11e7-81c8-8179face2781.png)

**Comment by Gcaufy** [comment]
第一次碰到，多试几次看看还有问题吗？

**Comment by ohYobbo** [comment]
可以用yarn试一下   我上次也是npm的依赖安装不成功   yarn就可以
