### ISSUE TITLE
支持  webpack aliasFields 选项

### ISSUE THREAD

**Issue by leeyeh** [Tencent/wepy#566]
接 https://github.com/wepyjs/wepy/issues/203#issuecomment-346315371

需求是这样的。我们维护了一些跨平台的 SDK，通过在 package.json 中指定不同平台下的入口来告诉打包工具应该解析到哪个文件。 这里有个例子： https://github.com/leancloud/javascript-sdk/blob/master/package.json#L76-L92

wepy 解决了小程序平台上对 npm package 缺少支持的问题。但是目前没有一个机制可以让 package 作者告诉 wepy 应该使用那个入口。

webpack 设计了一个 https://webpack.js.org/configuration/resolve/#resolve-aliasfields 的机制，可以指定 resolve 的时候将 package.json 中的哪些字段作为 alias 的配置来使用。wepy 可以使用类似的机制来允许用户指定 aliasFields。

进一步的，我提议在默认的情况下，约定使用 `['wepy', 'weapp', 'browser']` 作为默认值，那样用户便可以直接使用符合这一约定的 packages。

**Comment by Gcaufy** [comment]
合理。

**Comment by Gcaufy** [comment]
@leeyeh review看看这个PR是否可以满足需求，有什么问题吗？
