### ISSUE TITLE
能否支持官方小程序的自定义组件

### ISSUE THREAD

**Issue by wulunyi** [Tencent/wepy#568]

**Comment by zaxlct** [comment]
我试了下，正常引入自定义组件没问题。用 wepy 编写的话估计还没不支持吧

**Comment by hankanon** [comment]
可以用 试了下 性能还是不错的

**Comment by sconfield** [comment]
@hankanon 直接写原生代码吗，能用wepy的方式使用吗，请问下怎么写 child Component js file. 谢谢！

Component({
  properties: {
    // 这里定义了innerText属性，属性值可以在组件使用时指定
    innerText: {
      type: String,
      value: 'default value',
    }
  },
  data: {
    // 这里是一些组件内部数据
    someData: {}
  },
  methods: {
    // 这里是一个自定义方法
    customMethod: function () { }
  }
})
