### ISSUE TITLE
repeat 组件传参，子组件OnLoad获取不到props 的数据

### ISSUE THREAD

**Issue by Es201n** [Tencent/wepy#575]
repeat 组件传参，子组件OnLoad获取不到props 的数据，实际子组件已被渲染成功。这个问题很严重啊，我看之前也有人提交了。求告知解决办法。
父组件：
![image](https://user-images.githubusercontent.com/17695936/33247176-093dcfc6-d357-11e7-9aed-9254ce6dbc5c.png)
子组件：
![image](https://user-images.githubusercontent.com/17695936/33247162-f32a6528-d356-11e7-9e08-a0a962187c26.png)
最后渲染页面：
![image](https://user-images.githubusercontent.com/17695936/33247202-34948a2a-d357-11e7-8c6c-ce61e14e7c07.png)

**Comment by Es201n** [comment]
@Gcaufy

**Comment by ymqq** [comment]
他们的流程，onLoad是组件加载时就触发了，生命周期有问题。应该要提供一个组件数据进入时的事件。

**Comment by Es201n** [comment]
确实需要一个参数传递的事件钩子。onLoad onShow onReady 我都试过了，没用

**Comment by 1162257086** [comment]
.sync

**Comment by YaoKaiLun** [comment]
同样遇到这个问题，我的数据没有异步操作，也不修改 props ，按理说不需要 sync，即使加上了也是有这种情况

**Comment by kirkcola** [comment]
这个问题的确很严重啊 现在还找到解决方案 组件渲染时可以拿到props的参数正常显示 但是变量里始终是空的 组件的生命周期设计的的确有问题

**Comment by shenqihui** [comment]
我觉得 onLoad 事件不应该有参数，可以通过传输方式来获取，也可以通过 getCurrentPages 来判断获取。

**Comment by wangyequn** [comment]
问题解决了没有啊?

**Comment by yolo2013** [comment]
这个已经极大影响开发体验。。。
