### ISSUE TITLE
在onLoad函数内如何触发action内的函数

### ISSUE THREAD

**Issue by Chaunjie** [Tencent/wepy#578]
![image](https://user-images.githubusercontent.com/12093709/33259492-03419328-d398-11e7-91b7-17a0669074d6.png)
这样调用无法触发reducers的方法，但是使用按钮触发就可以

**Comment by Chaunjie** [comment]
@Gcaufy

**Comment by Chaunjie** [comment]
@dolymood

**Comment by dolymood** [comment]
两个方法：

1. `this.methods.initData({})`

2. `const store = getStore();store.dispatch(initData({}))`

**Comment by Chaunjie** [comment]
@dolymood 万分感谢

**Comment by Chaunjie** [comment]
@dolymood 我这样会连续调用两次action
`export const initData = createAction(INIT_DATA, () => {
	return new Promise(resolve => {
		console.log(6666);
		setTimeout(() => {
			resolve({num:100, name:'chaunjie'})
		}, 1000)
	})
})`

**Comment by dolymood** [comment]
你确实是调用了两次啊 你这是两种方法都用了 任选一种即可，建议使用方法1

**Comment by Chaunjie** [comment]
@dolymood 好的，谢谢了

**Comment by Mrzhangyu** [comment]
还好找到了，坑了我一下午了，感谢回答！！！
