### ISSUE TITLE
怎么生成web版本的

### ISSUE THREAD

**Issue by jmying** [Tencent/wepy#580]
看到案例有web版本的。

**Comment by Gcaufy** [comment]
```
wepy build --output web 
```

**Comment by bitqiang** [comment]
你们能正常生成web页面吗，我的报错了。
![image](https://user-images.githubusercontent.com/13163400/33801726-4f8746f4-dd9f-11e7-9e9f-ea4e0c06715f.png)
是哪儿配置不对吗？直接用的官方demo

**Comment by Gcaufy** [comment]
web版本很长时间没有维护了，出了一点点问题，已经修复了
```
$ npm install wepy-cli@1.6.1-alpha2 -g
$ wepy new demo
$ cd demo
$ wepy build --output web
$ wepy build --output web --platform wechat
$ wepy build --output web --platform qq
```

**Comment by saoyor** [comment]
转web 哪里有文档说明 现在看demo也是一头雾水

**Comment by Gcaufy** [comment]
@saoyor 因为web版原计划是2.x版本开放的功能，因此暂时没明确对外公告支持Web版本，所以也就没有文档

**Comment by 18514762400** [comment]
wx.getUserInfo is not supported in browser or you did add it in config.如何在web版解决调用小程序的一些方式

**Comment by jmying** [comment]
@Gcaufy 给你gmail发了一份邮件，麻烦查收下

**Comment by liminshen** [comment]
when npm run dev:web  build web file

**Comment by qi995971072** [comment]
期待2.0，已donate

**Comment by dengbaoling** [comment]
哪个大佬成功呢？`TypeError: Cannot read property 'modulePath' of undefined
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy-cli\lib\web\compile-script.js:116:54
    at String.replace (<anonymous>)
    at Object.resolveMap (C:\Users\Administrator\AppData\Roaming\npm\node_modules\wepy-cli\lib\web\compile-script.js:53:43)`

**Comment by dengbaoling** [comment]
@Gcaufy 给你gmail发了一份邮件，麻烦查收下

**Comment by dengbaoling** [comment]
> VM187 index.js:3872 Uncaught ReferenceError: process is not defined
    at Object.<anonymous> (VM187 index.js:3872)
    at __webpack_require__ (VM187 index.js:17)
    at Object.<anonymous> (VM187 index.js:290)
    at __webpack_require__ (VM187 index.js:17)
    at Object.<anonymous> (VM187 index.js:57)
    at __webpack_require__ (VM187 index.js:17)
    at VM187 index.js:31
    at VM187 index.js:32

**Comment by dengbaoling** [comment]
``
![](https://github.com/dengbaoling/wechat_images/blob/master/bug/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180424102934.png)
![](https://github.com/dengbaoling/wechat_images/blob/master/bug/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180424120631.png)

**Comment by dengbaoling** [comment]
`
![](https://github.com/dengbaoling/wechat_images/blob/master/bug/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180424102934.png)
![](https://github.com/dengbaoling/wechat_images/blob/master/bug/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180424120631.png)`

**Comment by Gcaufy** [comment]
升级一下 alpha2 的版本。

**Comment by dengbaoling** [comment]
![_20180424142250](https://user-images.githubusercontent.com/17171011/39169941-3a72288c-47cc-11e8-8b86-e66adad89622.png)

**Comment by shucheng** [comment]
![image](https://user-images.githubusercontent.com/4123301/40817832-f9e33d6e-6586-11e8-949a-e21e1f99e10d.png)
wepy init standerd demo
然后正常跑起来之后，npm run dev:web

可以成功输出来一个html，js
但是控制台中抛出报错比较多，不知道官方团队是否有解
