### ISSUE TITLE
repeat 循环组件中，子组件  style="background-color:{{component.setting.sliderColor}}" 绑定没成功

### ISSUE THREAD

**Issue by Es201n** [Tencent/wepy#583]
repeat 循环组件中，子组件  style="background-color:{{component.setting.sliderColor}}" 绑定没成功。
同样的绑定方式 在  <view>{{component.setting.sliderColor}}</view> 却有值了。
效果：
![image](https://user-images.githubusercontent.com/17695936/33366010-0242c65c-d525-11e7-809b-0ecd15d1cf74.png)
代码：
页面
![image](https://user-images.githubusercontent.com/17695936/33366086-2fbb0356-d525-11e7-96b6-8e0dc923cef6.png)
组件
![image](https://user-images.githubusercontent.com/17695936/33366126-4c0a65b0-d525-11e7-8afd-29e4b12429fa.png)

**Comment by Es201n** [comment]
@Gcaufy

**Comment by nervouself** [comment]
老铁这是为什么
