### ISSUE TITLE
sass 报错问题 以及sass相关问题

### ISSUE THREAD

**Issue by ziyziyziy888** [Tencent/wepy#586]
1.sass配置未找到相应步骤
2.如何在一个page中定义100%高度？
3.感谢！

![image](https://user-images.githubusercontent.com/22311977/33370720-5b985ae2-d533-11e7-9b2b-34a278c6070e.png)
![image](https://user-images.githubusercontent.com/22311977/33370735-6531249e-d533-11e7-9169-ad37f917adcd.png)

我已解决，感谢

**Comment by Gcaufy** [comment]
问题是？如何解决的简单说明一下，防止有人碰到类似问题。
