### ISSUE TITLE
孙组件使用子组件的props的值，取不到

### ISSUE THREAD

**Issue by wyk304443164** [Tencent/wepy#591]
`props = {
      cardIndex: {}
    }
`
`
    data = {
      cardIndex1: 111
    }`

`<flip :cardIndex1="cardIndex1"></flip>`

cardIndex1 正常取到，props内 cardIndex 不可以

`<flip :cardIndex1="cardIndex"></flip>`

**Comment by wyk304443164** [comment]
![image](https://user-images.githubusercontent.com/12638148/33476855-6d0776be-d6be-11e7-9f95-a4b24c530158.png)
![image](https://user-images.githubusercontent.com/12638148/33476880-83712382-d6be-11e7-98d7-5c58960c8ab1.png)

**Comment by wyk304443164** [comment]
![image](https://user-images.githubusercontent.com/12638148/33477129-779f61ee-d6bf-11e7-9653-14e5fc1e0453.png)
![image](https://user-images.githubusercontent.com/12638148/33477144-856ecda0-d6bf-11e7-82c0-b491f1835d32.png)

**Comment by lwenn** [comment]
今天也遇到这个问题了，有没有解决方案呢？

**Comment by wyk304443164** [comment]
我去掉了孙组件，改为子组件里面写

**Comment by fantasy525** [comment]
我也遇到啦，这是什么问题？目测跟repeat有关啊？怎么解决呢？

**Comment by Gcaufy** [comment]
repeat中的props, computed 等特性都有问题，先避免这样写。

**Comment by cuijiemmx** [comment]
很不幸今天我也遇到了这个坑...

**Comment by moyuanhua** [comment]
很不幸 我中招了

**Comment by moyuanhua** [comment]
bug没解决怎么就close了

**Comment by lwenn** [comment]
作者说避免在 repeat 中使用 props，我们目前的解决办法是，把需要在孙组件中使用的 props 通过对象传入子组件。

**Comment by moyuanhua** [comment]
props 能够支持传对象吗  前段时间看好像还不可以

**Comment by moyuanhua** [comment]
props 能够支持传对象吗 前段时间看好像还不可以@ @lwenn

**Comment by lwenn** [comment]
我这里试过是可以的，现在还是这么写的，wepy@1.6.0
