### ISSUE TITLE
引用外部npm的wepy组件时候，编译后的wxss的@import路径产生问题

### ISSUE THREAD

**Issue by tianye19941001** [Tencent/wepy#592]
两个wpy文件，在相同目录下。确定的是，编译过程中没有出错，js的引用也没有出错 直接是`./`。但是wxss文件的`@import`路径出现错误：
![image](https://user-images.githubusercontent.com/13199831/33477793-fc134bd2-d6c1-11e7-8848-c35362963b2d.png)
![image](https://user-images.githubusercontent.com/13199831/33477805-090a96b0-d6c2-11e7-999f-6213bcbe97d2.png)
![image](https://user-images.githubusercontent.com/13199831/33477813-0e024082-d6c2-11e7-8eca-075373143a52.png)

**Comment by Gcaufy** [comment]
我尝试安装并还原，发现样式正常

```
$ npm install wepy-hlj-comment --save
$ wepy build --no-cache
```

```
// index.wpy
<hlj></hlj>

// 编译后的 index.wxss
@import "./../npm/wepy-hlj-comment/commentItem.wxss";
```
