### ISSUE TITLE
可以获得后台服务器数据，不过页面显示不出来

### ISSUE THREAD

**Issue by skyrealmz** [Tencent/wepy#593]
![image](https://user-images.githubusercontent.com/8827438/33481242-9a26ba00-d6ce-11e7-8265-a15cca3743ed.png)

![image](https://user-images.githubusercontent.com/8827438/33481210-76fdfdb8-d6ce-11e7-85c6-24671cf92d0b.png)

获取后台数据的函数
![image](https://user-images.githubusercontent.com/8827438/33481290-d12a348c-d6ce-11e7-904b-aa3432df7076.png)
![image](https://user-images.githubusercontent.com/8827438/33481354-154b473c-d6cf-11e7-8160-d34b2522f8bd.png)

请问要怎么修改代码？谢谢了

**Comment by skyrealmz** [comment]
找到原因了
![image](https://user-images.githubusercontent.com/8827438/33494538-8c1436ce-d6fe-11e7-8bdd-16f1a265ac79.png)
因为我这里是 homepage.wpy 里调用了 components 的 carousel.wpy才加载不出来。
如果直接把代码写进 homepage.wpy，可以正常显示。

**Comment by Gcaufy** [comment]
不要用setData 多参考一下demo
