### ISSUE TITLE
wepy.request开发者工具里面报错

### ISSUE THREAD

**Issue by shanghui-yu** [Tencent/wepy#597]
使用官方文档的wepy.request('xxxx').then((d) => console.log(d));

项目设置里面 都按照使用手册提醒里面说的 
关闭上传代码时样式自动补全，关闭ES6转ES5，关闭代码压缩上传、

request里面输入正确的接口地址  在小程序运行报错 

![image](https://user-images.githubusercontent.com/16436050/33523708-2125a0aa-d848-11e7-90b7-6879dece15fc.png)

请问官方是为什么？

**Comment by Gcaufy** [comment]
this.use('requestfix') 加了么？

**Comment by Pumpe** [comment]
我也入到了同样的问题，在入口文件中添加了this.use('requestfix')，依然会报上述错误

**Comment by Gcaufy** [comment]
@Pumpe 
sorry, `this.use('promisify');`

**Comment by zhanghaoranas** [comment]
官方的教程在这里 https://github.com/Tencent/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8Promise
