### ISSUE TITLE
wepy出现空白

### ISSUE THREAD

**Issue by liling0726** [Tencent/wepy#601]
使用wepy在扫码进入首页时候，在首页页面渲染完成之后退出再扫码，一直重复出现（重复许多次，有点随机）页面空白，但实际数据已经加载，点击空白，可以进行相应的操作，跟踪发现与正常的没有区别

**Comment by liling0726** [comment]
使用wepy在扫码进入首页时候，在首页页面渲染完成之后退出再扫码，一直重复出现（重复许多次，有点随机）页面空白，但实际数据已经加载，点击空白，可以进行相应的操作，跟踪发现与正常的没有区别

**Comment by Gcaufy** [comment]
看看其它DEMO是否出现类似问题，如果不会出现，排查一下业务代码
