### ISSUE TITLE
组件通过 this.$emit 无法触发事件

### ISSUE THREAD

**Issue by cmzz** [Tencent/wepy#603]
# 组件

```
  <view  class="scroll-top" @tap="backToTop"></view>

   // js
    methods = {
      backToTop: () => {
        console.log('click')
        this.$emit('backToTopEventListener')
      }
    }
```

# 页面

```
<scrollTop />

import ScrollTop from '../components/scroll-top'

...

components = {
      scrollTop: ScrollTop
    }

events = {
      'backToTopEventListener': (p1, p2, p3, $event) => {
        console.log(`${this.name} receive ${$event.name} from ${$event.source.name}`)
      }
    }

...

```

请问 为啥事件触发不了呢。

**Comment by Gcaufy** [comment]
看代码好像是没有问题的。你看看demo有很多emit的示例。可以看一下

**Comment by cmzz** [comment]
请问哪儿有demo呢

**Comment by Gcaufy** [comment]
wepy new demo

**Comment by cmzz** [comment]
看样子代码好像是没问题，但不知怎么不能调

**Comment by forHeyin** [comment]
//组件
<view  class="scroll-top" @tap="backToTop"></view>
methods = {
  backToTop: () => {
    console.log('click')
    this.$emit('backToTopEventListener', 1, 2, 3, 4)
  }
}
//父组件
<scrollTop />
events = {
'backToTopEventListener': (p1, p2, p3, $event) => {
    console.log(111);
    console.log(p1) //1
  }
}
这样是可以触发的

**Comment by fitcong** [comment]
后面还需要一个空的对象,this.$emit('backToTopEventListener',{})入参最好一一对应

**Comment by lj0812** [comment]
你好，问题解决了么？
