### ISSUE TITLE
组件无法递归调用

### ISSUE THREAD

**Issue by YaoKaiLun** [Tencent/wepy#606]
打算实现一个组件，组件中递归调用自己
```
// tpl.wpy
<template>
    <block if="{{data.node == 'element'}}">
        <repeat for="{{data.nodes}}" item="n">
            <tpl :node.sync="n" />
       </repeat>
    </block>
</template>
```
tpl 即为我的组件。参考了 vue 中递归调用的方法，即在 component 中定义 name 属性，所以在 wepy 中我尝试了如下操作：
```
<script>
  export default class Tpl extends wepy.component {
     // name = 'tpl' 
     $name = 'tpl'
  }
</script>
```
无论我设 name 或者 $name 开发者工具都报下面的错误：

![image](https://user-images.githubusercontent.com/11460856/33600666-dc4be19e-d9e4-11e7-8966-7647b1c7e486.png)
但我发现，我将下面的 tpl 改为不存在的组件，wepy 构建的时候也不报错，因此，猜测上面的问题也是 实际上找不到 tpl 组件引起的。
```
<tpl :node.sync="n" />
```
所以，wepy 是不支持组件递归调用吗？

**Comment by Gcaufy** [comment]
不支持

**Comment by fengxinlu** [comment]
我也遇到了这个问题 怎么办
