### ISSUE TITLE
怎么在使用WEPY框架时同时使用WEUI-WXSS

### ISSUE THREAD

**Issue by Liqiankun** [Tencent/wepy#607]

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy-weui-demo

**Comment by xiaomlove** [comment]
@Gcaufy demo中是直接修改wepy项目的dist目录添加了一个style目录进去吗？package,json没有引入weui-wxss啊。

**Comment by xiaomizhou66** [comment]
我想知道怎么  wepy 中用 cdn 方式引入？
