### ISSUE TITLE
页面循环跳转与页面销毁的问题

### ISSUE THREAD

**Issue by Arweil** [Tencent/wepy#611]
现在有需求如下：
PageA 跳转到 PageB 跳转到 PageC(B.C) 跳转到 PageD 跳转到 PageC(D.C)
如果执行这个流程，在D.C中动画，状态都是可用的。但是从D.C返回到B.C页面后，动画，状态设置均无效，但是事件可以触发，请问怎么解决？

PS：这里的跳转指的是navigateTo，页面可以获取到data中的数据状态，但是设置后相应的UI并没有反应

**Comment by Gcaufy** [comment]
无效是什么意思？修改了数据，但没有绑定至页面还是说进入时初始数据不见了？

**Comment by jasperchou** [comment]
遇到相同问题。感觉data好像是static，全局一份，如果跳转多次相同页面，只会留最后一份data，导致前面页面无法操作。比较诡异。

**Comment by bthl21165** [comment]
1、设置相同的数据是不会触发UI更新的。2、“从D.C返回到B.C页面后”这个是通过navigateBack返回的话，只会触发页面的onShow方法，data不会重新初始化。

**Comment by ymqq** [comment]
这个问题应该是这样的：

A(1) -> B(1) -> C(1) -> A(2) -> B(2) -> C(2) 在这样的页面跳转下，使用小程序的返回按钮，逐层返回后

在返回到C(1)、B(1)、A(1)页面后，虽然页面展示的内容是正确的内容，但是后台的data中的对应数据，已经变成了C(2)、B(2)、A(2)的数据。

这时候在1的页面中点击内容调整，携带的数据就会发现是错误的。

我有线上的小程序《妈妈话题》，在用户头像点击后，进入个人信息，在该页面会有循环的跳转，然后返回就会出问题。

**Comment by Licoy** [comment]
但是感觉页面重定向之后，之前的页面中的数据不会被销毁，第二次进入那个页面还是之前的数据

**Comment by charmtiger** [comment]
你们问题解决了吗？我是这样 pageA?id=1 页面进到 B 再进到 pageA?id=2,然后按顺序返回到 pageA?id=1,这时data会混乱，而且onShow 执行的确实 pageA?id=2 中的方法

**Comment by jasperchou** [comment]
其实你用小程序开发工具自带的AppData跟踪一下页面数据就知道了。内部原因不太懂。感觉是根据路径存储数据，所以覆盖掉了。。。。所以我用了个很恶心的方法。本地建了个硬链，起了个名字 filename2......。将就用吧。期待大神出现。。。

**Comment by moyaying** [comment]
遇到相同问题，有什么办法解决吗？

**Comment by moyaying** [comment]
比如商品页1跳到商品页2，返回操作商品1就出bug。

**Comment by moyaying** [comment]
@ymqq 请问有什么办法解决吗？

**Comment by ymqq** [comment]
目前我将，有可能连续打开的页面都复制了多份，因为小程序打开页面页有10个页面，这样都限制，所以我有好几个页面都存在page_1, page_2,page_3这样都拷贝。

同时写一个用于跳转这种页面都统一方法，然后根据当前第几次打开相同的page，就打开对应数字下标的页面。

**Comment by TroyBi** [comment]
感觉确实存在后一个页面覆盖前一个页面数据（同路径）的情况。我是在每次页面onHide的时候把当前页面数据存到globalData[pageLength]中，当页面onShow的时候在判断globalData[pageLength]的数据赋值回去。非常不友好，但是算是一种解决办法

**Comment by Zhuxf1111** [comment]
@TroyBi 有用吗？我也试了但是 ios右滑退出页面的时候 还是会有问题
