### ISSUE TITLE
多次使用某个组件，构建后生成的代码量较大

### ISSUE THREAD

**Issue by YaoKaiLun** [Tencent/wepy#614]
遇到这种情况：

组件 A 调用两次组件 B
```
// a.wpy
<template>
  <b />
  <b />
</template>
```
```
// b.wpy
<template>
  <view>I am B!</view>
</template>
```
构建生成的 index.wxml 如下：
```
 <view>I am B!</view>
 <view>I am B!</view>
```
这在 A 调用 B 的次数不多，而 B 的 template 结构简单的时候是没什么问题的，但我目前的业务中，恰好在 A 中多处地方循环遍历多次 B，类似如下
```
// a.wpy
<template>
  <repeat for={{tenLengthArray}}>
    <b />
  <repeat>
  <repeat for={{tenLengthArray}}>
    <b />
  <repeat>
  <repeat for={{tenLengthArray}}>
    <b />
  <repeat>
  ...
</template>
```
组件 B 中也类似以上调用了 C，C 中调用 D……
按目前构建生成l代码的方式，index.wxml 的文件大小已经超出了小程序的要求了，而如果我换用原生的实现方式，我只要将 B，C,  D 这些被多次使用到的组件定义为 template 即可，代码量很小。因此，wepy 是否考虑对多次调用的组件，使用小程序的 template 来优化呢？

**Comment by Gcaufy** [comment]
```
<repeat for={{tenLengthArray}}>
    <b />
  <repeat>
```
会被编译为
```
<block wx:for="">
    <view>I am B!</view>
</block>
```
不会在编译过程中生成所有的代码

另外，在后期的2.x版本里，会陆续以小程序的原生组件去实现这里的功能，彻底解决这里的问题。
在现阶段，不会做调整。
