### ISSUE TITLE
动态模板应该如何来实现？？

### ISSUE THREAD

**Issue by IveChen** [Tencent/wepy#615]
未使用wepy之前我是用类似 下图的方式来实现动态模块，但是wepy不知道应该怎么写才能实现类似的效果
![image](https://user-images.githubusercontent.com/1736282/33693968-a2624386-db30-11e7-9510-9875630692d5.png)

**Comment by Gcaufy** [comment]
<test wx:if="{{item='test'}}"></test>
<test2 wx:if="{{item='test'}}"></test2>

**Comment by IveChen** [comment]
@Gcaufy 这样并不是动态了，因为我test和test2的位置要根据不同的权限可能顺序会不一样。。我之前再wepy尝试了你的组件的写法，是直接编译到wxml定死了位置的。

**Comment by wildcn** [comment]
同问，有动态组件吗？
