### ISSUE TITLE
自定义tabbar组件配置app.wepy

### ISSUE THREAD

**Issue by fantasthu** [Tencent/wepy#618]
自定义tabbar组件配置app.wepy

**Comment by Gcaufy** [comment]
问题是？

**Comment by fantasthu** [comment]
不好意思没有描述清楚,比如我要自定义一个组件,写成类似switchtab的跳转方式,但我发现要配置,但是一但配置,底部就和我写的组件一样了(写组件的目的是动态控制显示隐藏),但是没找到怎么动态隐藏tabbar的写法,一旦配置就生成

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy-wechat-demo

**Comment by fantasthu** [comment]
好的,谢谢
