### ISSUE TITLE
官方文档里面关于events的用法

### ISSUE THREAD

**Issue by YUANLIN327** [Tencent/wepy#622]
![image](https://user-images.githubusercontent.com/12224909/33811156-1421e932-dddd-11e7-8dda-9a39828b39e4.png)
如图 这第一张的关于组件之间通信的method是写在events里面.
![image](https://user-images.githubusercontent.com/12224909/33811160-2b593a6a-dddd-11e7-99d8-8241e33e2027.png)
到了这里就写到了method里面?为什么???

**Comment by Gcaufy** [comment]
@YUANLIN327 
你可以理解为
`$broatcase`和`$emit`的相关事件写在`events` 里
`@tap`, `@input`, `@userFn.user` 这一类事件写在`methods` 里
