### ISSUE TITLE
能否提供typescript的支持？

### ISSUE THREAD

**Issue by qinyang1980** [Tencent/wepy#624]
现在Vue2.x都增加了typescript的支持。是否可以提供一下ts的支持呢？或者添加说明，如何使用？

**Comment by Gcaufy** [comment]
wepy.config.js 中加入：
```
compilers: {
    typescript: {

    }
}
```

app.wpy 中修改为：
```
<script lang="typescript">
```

对比一下`dist/app.js`

**Comment by qinyang1980** [comment]
测试过，已经可以了。多谢！

**Comment by Gcaufy** [comment]
能提供一个完整的 typescript 的小程序 demo 么？很多用户有问到过。

**Comment by qinyang1980** [comment]
可以。弄完贴过来。

**Comment by aristotll** [comment]
发现支持貌似不太完美 如果单独一个外面的 typescript 相互导入 不能编译 (不是直接导入 如外面的类库
(和 vue 提供的 lang="ts"  有点差距

**Comment by aristotll** [comment]
我当前的 workaround 手动先编译 typescript 到 es6 然后让 wepy 的 command line 执行

**Comment by williambryan777** [comment]
现在这块支持typescript怎么样了呢，有什么进展呢

**Comment by FuDesign2008** [comment]
> 现在这块支持typescript怎么样了呢，有什么进展呢

+1

**Comment by chenyu445** [comment]
> 现在这块支持typescript怎么样了呢，有什么进展呢

+1
