### ISSUE TITLE
官方的自定义组件生命周期函数不起效，只有onLoad起效

### ISSUE THREAD

**Issue by oblank** [Tencent/wepy#627]
请问下面这些该怎么写才能有效，谢谢？

> 

created | Function | 否 | 组件生命周期函数，在组件实例进入页面节点树时执行，注意此时不能调用 setData
-- | -- | -- | --
attached | Function | 否 | 组件生命周期函数，在组件实例进入页面节点树时执行
ready | Function | 否 | 组件生命周期函数，在组件布局完成后执行，此时可以获取节点信息（使用 SelectorQuery ）
moved | Function | 否 | 组件生命周期函数，在组件实例被移动到节点树另一个位置时执行
detached | Function | 否 | 组件生命周期函数，在组件实例被从页面节点树移除时执行

[https://mp.weixin.qq.com/debug/wxadoc/dev/framework/custom-component/component.html](https://mp.weixin.qq.com/debug/wxadoc/dev/framework/custom-component/component.html)

**Comment by Gcaufy** [comment]
如果是官方问题，请在这里提问
https://developers.weixin.qq.com/

**Comment by wells1013** [comment]
+1

**Comment by Gcaufy** [comment]
@oblank wepy组件和官方的组件不是一回事。

**Comment by ddtramp** [comment]
@oblank 那到底 wepy 支持上面的方法不呢？

**Comment by ddtramp** [comment]
@Gcaufy 那到底wepy 支持上面所述的方法呢？

**Comment by Gcaufy** [comment]
@ddtramp wepy 1.x 的版本用的不是官方组件实现的，所以官方组件里面的些东西在这里都用不了。

1.7.2-alpha1 版本开始支持官方组件，有兴趣可以去了解一下。

**Comment by ddtramp** [comment]
1.7.2 ? 现在看不到源码， 仓库里面没有 啊

**Comment by lzl124631x** [comment]
这也太囧了.........吐血. 用了半天不是官方组件.

不过可以用`onLoad`代替一下`attached`, 别的就不知道了.

**Comment by AlingChen** [comment]
@Gcaufy wepy组件有代替原生 detached 生命钩子的方法吗

**Comment by xuweikang** [comment]
@Gcaufy  附议，  wepy组件有代替原生 detached 生命钩子的方法吗

**Comment by Gcaufy** [comment]
大家在使用这个框架时一定要先了解一下他的背景。
这个框架是16年11月份上线的，通过静态编译去解决小程序组件化开发的问题，
而官方的组件是17年11月份上线的。
因此两个组件完全不是一回事。不能混为一谈

回到问题：
@AlingChen @xuweikang 静态编译组件是编译阶段就把组件编译进去了，因此组件不存在移除，即便通过添加wx:if移除，那也没有办法拿到移除的回调，所有这里就不存在detached生命周期。

**Comment by lzl124631x** [comment]
@Gcaufy 不能指望开发者了解这些事情啊, 为了节约你们的时间, **这种信息应该放到文档里面强调**. 现在大家问这些问题说明大家不知道这回事.

**Comment by cz848** [comment]
同问，1.7.2是怎么解决这些生命周期函数的？

**Comment by Clearives** [comment]
只有onload可用吧，其他情况，用组件通信或者watch监听执行方法
