### ISSUE TITLE
error  Extra semicolon

### ISSUE THREAD

**Issue by wangqianjun** [Tencent/wepy#630]
build的时候为什么会出现分号（;）报错啊？

![4857dba9-ace3-455c-b534-b0cbfe9d4784](https://user-images.githubusercontent.com/8085482/33869804-ccc00474-df45-11e7-90ee-c1b0a135f64d.png)

**Comment by dlhandsome** [comment]
关掉eslint检查即可

**Comment by wangqianjun** [comment]
@dlhandsome 如何关闭？

**Comment by dlhandsome** [comment]
#420
