### ISSUE TITLE
repeat 子组件 watch 属性,  在method方法里面更改属性, watch会触发两次，而且有1次的属性不属于传入的属性

### ISSUE THREAD

**Issue by binlaniua** [Tencent/wepy#636]
![image](https://user-images.githubusercontent.com/5960462/33900583-ecb75b6a-dfa9-11e7-98bc-5d0635155169.png)
![image](https://user-images.githubusercontent.com/5960462/33900587-f2fa9000-dfa9-11e7-820d-ac6d804ae533.png)

**Comment by Gcaufy** [comment]
断点调试一下就可以找到原因的。

**Comment by binlaniua** [comment]
debugger过了，子组件脏数据检查后，到达父属性的脏数据检查，导致这个属性被改变了

是子组件不能修改属性吗

**Comment by binlaniua** [comment]
repeat子组件里面，把 this.$apply() 改成  this.$parent.$apply() 就可以准确的修改了
但是子组件里面如果还有setTimeout的话，如果属性修改了，一定拿的第一个属性值...

**Comment by Gcaufy** [comment]
在repeat中，组件实例只有一个，数据都是通过$index去控制的。
对于methods方法 ，在触发时会修改$index，就此可以拿到正确数据，对于其它的非methods方法 。比如setTimeout， $index会保留上次的值，不会被修改。
