### ISSUE TITLE
设置movable-area 的view无效

### ISSUE THREAD

**Issue by KingJeason** [Tencent/wepy#643]
官方: 
```
tap: function(e) {
    this.setData({
      x: 30,
      y: 30
    });
  }
```

wepy: 
```
this.x = 30 this.y = 30
```
但是wepy只能执行一次,而官方的demo无论怎么样点击后都可以回到 设置的位置,但是wepy只是可以运行一次,

**Comment by Gcaufy** [comment]
没太理解你的意思

**Comment by KingJeason** [comment]
hello, @Gcaufy .  重现Wepy bug步骤.:1. 拖拽方块到任一位置 2.点击按钮,(方块会移动到 30,30位置) 3. 再次拖拽方块到任一位置 4. 点击按钮 (方块不会移动到30 30位置) 

Gcaufy大大可以试一下,html用的是官方实例,js换成wepy的就不行了

**Comment by Gcaufy** [comment]
原因是多次点击 x,y的值依然是30， 所以在脏检查过程中，判断x,y的值未作改变，因此不会执行 setData
解决方案：
修改 copy 中的数据，让脏检查通过
```
this.$data.x = 0;
this.$data.y = 0;
this.x = 30;
this.y = 30;
```

后面再考虑这里是否有更好的解决方案

**Comment by Teemwu** [comment]
不知有没有解决方案了，现在遇到同时动态绑定x、y和scale-value，会默认缩放到0.5
