### ISSUE TITLE
computed、数组、脏检查的问题

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#644]
computed返回的是数组，computed逻辑是。
`
items () {
     return this.arrs.slice(0, this.size)
}
`
如果由于其它属性的改变触发了脏检查，this.size和this.arrs都没有改变，这个时候items会被setData吗？
因为现在出现了一个性能问题，怀疑是items被setData太频繁了。

**Comment by Gcaufy** [comment]
会

https://tencent.github.io/wepy/document.html#/?id=computed-%e8%ae%a1%e7%ae%97%e5%b1%9e%e6%80%a7

**Comment by Gcaufy** [comment]
担心性能问题的话就不要去使用computed 去实现。

**Comment by nishino-tsukasa** [comment]
再请问下，那脏检查对具体某个数组或者对象属性的新旧比较逻辑是怎样的？

**Comment by Gcaufy** [comment]
数据有会生一份copy
数据被修改后，在apply阶段，会与copy做比较， 不一样的会进入readyToSet 中。
当readyToSet有数据时，会计算所有watch 与 computed。并执行 setData操作。

**Comment by nishino-tsukasa** [comment]
还有1个问题
会计算所有watch 与 computed。并执行 setData操作。
也就是说computed计算得到的结果是不会生成copy的，不管这个结果的值有没有变化，都会被放到setData的操作里？

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/blob/master/packages/wepy/src/component.js#L506-L560
