### ISSUE TITLE
...  是什么情况额， 去掉就报错了。如图

### ISSUE THREAD

**Issue by IsSwm** [Tencent/wepy#645]
![image](https://user-images.githubusercontent.com/22268505/33977910-31ea9038-e0d8-11e7-9b6d-98a5370a4dad.png)
![image](https://user-images.githubusercontent.com/22268505/33977924-4a6d11ee-e0d8-11e7-8781-572989674e9b.png)

**Comment by Gcaufy** [comment]
去掉什么报错，提ISSUE的时候能否说具体一点。

**Comment by IsSwm** [comment]
@Gcaufy   去掉 “...”  这个是什么作用呢？  是复制数据的吗？  that.discoerList数据前面的...
![image](https://user-images.githubusercontent.com/22268505/33978197-8237f002-e0d9-11e7-84e8-5770e85bf355.png)

**Comment by Gcaufy** [comment]
去了解一下“ES6 解构”

**Comment by IsSwm** [comment]
谢谢，从Android转过来看来有很长的路。
