### ISSUE TITLE
wepy不支持在for循环下的slot插入？

### ISSUE THREAD

**Issue by rat1991** [Tencent/wepy#646]
个人有个组件需求，想在for循环下可以有slot的内容分发，但无论我用wepy的<repeat for>还是原生的wx:for都实现不了，是不支持还是我姿势不对？
`<view wx:for="{{list}}" wx:key="{{item.id}}">
      <slot name="index">默认内容{{index}}</slot>
</view>`

**Comment by Gcaufy** [comment]
slot 会做静态替换，所以是支持的，可以对比dist下生成的内容

**Comment by rat1991** [comment]
静态？ 如果我想slot根据for的index来创建呢？目前是实验不了的?
像这样
`<view wx:for="{{list}}" wx:key="{{item.id}}"> <slot name="item{{index}}">默认内容{{index}}</slot> </view>`

**Comment by xream** [comment]
@rat1991 请问这个问题你怎么解决的 谢谢

**Comment by Gcaufy** [comment]
@rat1991 不支持这种情况，这种情况请使用组件
