### ISSUE TITLE
watch 监听 props 值的变化

### ISSUE THREAD

**Issue by LewisLZ** [Tencent/wepy#647]
作者您好：
     我看你们的commit 中有关于监听props 变化的代码。
  
     但是为什么我一直监听不到呢？ 
     传值 都是以 :props.sync 方式传递   然后props定义是
     list: {
        type: Array,
        default: []
      }
      这样的方式，但是我一直监听不到值得变化

      帮忙看看  多谢

**Comment by SuperJolly** [comment]
+1

**Comment by LewisLZ** [comment]
@Gcaufy 回复一下 看看为什么吧。
这个很重要啊。。。
好多业务逻辑 绕行也不行。。
多谢啦

**Comment by SuperJolly** [comment]
目前只能在onLoad里加一个timer，来监听props变化后的值。。。

**Comment by LewisLZ** [comment]
问题是 监听不到props 的变化 
如果在computed 中写了计算 props 中属性的方法 
根本就不好使。。

**Comment by towry** [comment]
最新版本好像可以了，记得用 `$apply` 。

**Comment by Gcaufy** [comment]
watch  不会监听 props 的变化的。watch 只会监听 data 的变化。

如果想监听到 props 变化 的话，可以试着加一句
```
watch = {
    'myprop': function () {
        console.log('my prop is changed');
    }
}

this.$data['myprop'] = null;

```

**Comment by towry** [comment]
那就奇怪了。

**Comment by hanshou101** [comment]
为什么这么多人没有回答到点子上呢？

官方文档有说：
“在选项参数中指定 immediate: true 将立即以表达式的当前值触发回调。”

给你需要监听的props，在watch中加上这个属性，就可以了。
参考链接：https://cn.vuejs.org/v2/api/#vm-watch
