### ISSUE TITLE
repeat 循环子组件时，子组件的onload 和constructor 只执行一次，打印props只是第一个子组件的props

### ISSUE THREAD

**Issue by changyuwu** [Tencent/wepy#648]
<repeat for="{{list}}" index="index" key="index" item="item">
      <qaItem item="item"/>
    </repeat>
生成多个组件，在组件qaItem中
constructor() {
      super()
      console.log(this)
    }
log只执行了一遍
我想在computed中格式化一下props中的传值
computed = {
      get_record_time () {
      console.log('item2',this.item)
        return Math.ceil(this.item.record_time/1000)
      }
    }
但是这个log也只是执行了一次，并且所传的值是第一个子组件的props

有没有一个方法或者组件的生命周期 能让我打印出来每个组件的props？

**Comment by Gcaufy** [comment]
没有绑定。即使是在repeat中，也只有一个组件实例。
计划中的2.x版本应该可以解决这个问题

**Comment by cendechen** [comment]
这个只执行一次  真的有点坑

**Comment by zjhiphop** [comment]
坑大了....
