### ISSUE TITLE
repeat中包含自定义组件，组件中的computed的值不正确，始终返回了相同的值

### ISSUE THREAD

**Issue by AmosXu** [Tencent/wepy#651]
代码如下
## index.wpy
```html
<template>
  <view class="container">
      <view class="title" slot="title">测试组件Repeat</view>
      <repeat for="{{groupList}}" index="index" item="item" key="key">
        <group :grouplist="item"></group>
      </repeat>
    <toast />
  </view>
</template>
<script>
  import wepy from 'wepy'
  import Group from '../components/group'
  export default class Index extends wepy.page {
    config = {
      navigationBarTitleText: 'test'
    }
    components = {
      group: Group,
    }
    data = {
      groupList: [
        {
          id: 1,
          name: '点击改变1',
        },
        {
          id: 2,
          name: '点击改变2',
        },
        {
          id: 3,
          name: '点击改变3',
        }
      ]
    }
</script>
```
## group.wpy
```html
<template>
  <view class="group">
    <text class="id">{{newId}}. </text>
    <text class="name">{{grouplist.name}}</text>
  </view>
</template>
<script>
  import wepy from 'wepy'

  export default class Group extends wepy.component {
    props = {
      grouplist: {}
    }
    computed = {
      newId() {
        return this.grouplist.id + 1
      }
    }
  }
</script>
```
## 显示结果为

> 2.点击改变1
> 2.点击改变2
> 2.点击改变3

## 希望显示结果为
> 2.点击改变1
> 3.点击改变2
> 4.点击改变3

## 总结
组件中的computed的值始终拿的是页面上改组件的第一个值，不会实时变化，希望作者能给出解决的办法

**Comment by wlchou** [comment]
遇到了相同的问题，希望早日解决

**Comment by Gcaufy** [comment]
暂时不要在repeat中使用computed

**Comment by LewisLZ** [comment]
` <repeat for="{{groupList}}" index="index" item="item" key="key">
        <group :grouplist="item"></group>`

改成 
` <repeat for="{{groupList}}" index="index" item="item" key="key">
        <group :grouplist.sync="item"></group>`

应该就好了吧？

**Comment by binlaniua** [comment]
你可以试试在 子组件的methods做下setTimeout里面获取prop, 一样是同样的值，而且都是第一个值，目测是脏数据检查导致

**Comment by h1zsh1** [comment]
我也是相同的情况，自定义组件中，在methods中的函数里设置data中的属性值，所有循环渲染的组件中相同的data属性同时变化

**Comment by binlaniua** [comment]
目前我这边是不让子组件做脏数据检查，让父组件做，规避这个问题,  this.$parent.$apply()

**Comment by jasonsChen** [comment]
不知道楼主解决了没有，我也是这样，而且我通过tap增加data里面的数据，所有的其他数据也都会改变

**Comment by cuijiemmx** [comment]
也遇到了同样的问题，感觉wepy组件化这块bug不少...一路深坑

**Comment by AmosXu** [comment]
说实话有点后悔用wepy，问题很多，而且现在原生的一直在优化，目前我们项目中只是用到了它的文件管理方式

**Comment by Gcaufy** [comment]
非常抱歉
当前的组件实现原理导致了很多问题，wepy 毕竟不是 vue， 不能像玩vue一样玩wepy，尽量多参考放出的DEMO来写。
这个问题解决的话得放到2.x的版本。。

**Comment by wells1013** [comment]
@Gcaufy  2.x 计划什么时候出啊？

**Comment by cuijiemmx** [comment]
@Gcaufy 腾讯大神请问2.x要等到啥时候放出来？尽早造福我们吧！

**Comment by proto1994** [comment]
都知足吧，写原生的哪里舒服了，难受的一笔。。wepy挺好的，有点坑在所难免的。希望大佬们早日出2.x

**Comment by byk04712** [comment]
此 issues 关注 +1

**Comment by cuijiemmx** [comment]
@Gcaufy 
只要:prop.sync传值支持多级以及repeat内嵌组件computed值正确这两个期望能解决一个就能克服目前的窘境了，现在的情况是：prop.sync有时需要多级属性，因为不支持所以用computed属性绕过去，然而repeat内computed值又相同，蒙逼地无语堵死在这里，现在唯一的方案就是把data按内部组件结构准备好再传入，避开prop.sync需要使用多级属性的情况，然而这个方法太“脏”了...

**Comment by ployees** [comment]
I really was love

**Comment by ishen7** [comment]
@Gcaufy 加油！期待2.x大变化！

**Comment by ishen7** [comment]
@Gcaufy 加油！期待2.x大变化！目前也坑在repeat以及组件间传值上面

**Comment by Gcaufy** [comment]
大家可以试一下这个版本，应该能解决repeat下的一些问题：

安装使用：
```
npm install wepy-cli@1.7.2-alpha1 -g
npm install wepy@1.7.2-alpha1 --save
wepy build --no-cache
```
文档说明：https://github.com/Tencent/wepy/blob/component/docs/md/doc.md#%E7%BB%84%E4%BB%B6
迁移参考：https://github.com/wepyjs/wepy-wechat-demo/commit/5f84a3aed82547d7db4eb816f5c83f5ad35eba65

**Comment by ZhuRay** [comment]
坐等2.x

**Comment by zfan40** [comment]
貌似不止是compute的问题，组件里的交互方法也串了..

**Comment by xieyihao** [comment]
此 issues 关注 +1

**Comment by AnthonyACE** [comment]
@Gcaufy wepy@1.7.2-alpha1 解决了我的问题，感谢

**Comment by AnthonyACE** [comment]
@Gcaufy 但是使用wepy@1.7.2-alpha1 后，加入@符号可标识组件为小程序原生组件后，组件的computed在组件第一次渲染时，不会执行。而不加入@符号，会执行。
