### ISSUE TITLE
有办法能通知到 repeat循环生成的每个子组件吗？

### ISSUE THREAD

**Issue by changyuwu** [Tencent/wepy#653]
请问
`<repeat for="{{list}}" index="index" key="index" item="item">`
      `    <TestItem :item="item"/>`
`</repeat>`
我这里循环了很多TestItem， 有个需求是需要在父组件中通知到每个TestItem，告诉每个TestItem该做一些事情，我用invoke 或者 emit 发现不管有多少个 TestItem， 只是执行了一次通知事件， 还有其他方法吗？

**Comment by Gcaufy** [comment]
因为静态编译的机制问题，多个repeat也是一个实例，因此只会有一次事件。
