### ISSUE TITLE
props 值变化后 computed 不重新计算

### ISSUE THREAD

**Issue by LewisLZ** [Tencent/wepy#656]
组件中只用props 接收值
但是 如果直接在 view中显示可以显示，
但是 如果想通过 computed 中的计算方法 计算后再使用，就不可以了
只有值为空的时候 进入了 computed 中的方法， props 有值后 computed中的方法并不执行

**Comment by Gcaufy** [comment]
我在new出来的demo中测试，并不能复现问题。
computed 在每次 $apply 时，都会重新计算一次的。

**Comment by falstack** [comment]
如果是 repeat child-component，然后通过 computed 展示 props，那么 computed 不会在 props 获取到值的时候重新渲染

@Gcaufy

**Comment by skybluesky** [comment]
$apply之后，子组件computed不触发

**Comment by Gcaufy** [comment]
是因为没有添加 `.sync` 吗？

**Comment by shiran1992** [comment]
@Gcaufy 如果一个页面page的数据是来自于redux，然后将数据传递给子组件，这个时候computed并不会获取到真正的值。
