### ISSUE TITLE
组件init初始化的问题

### ISSUE THREAD

**Issue by phillyprr** [Tencent/wepy#657]
## Description
子组件关闭时需要把数据全部初始化一次，避免二次调用组件会有缓存问题，使用this.$init报setData的错，请问是什么问题？
Cannot read property 'setData' of undefined;at pages/user/myOrder/myOrder page $Appraise$closeCover function

**Comment by Gcaufy** [comment]
业务代码不应该使用setData
另外，信息太少，看不出什么问题

**Comment by phillyprr** [comment]
没有用setData，第一次用这个框架，看到里面有一个init，就想问下这个初始化调用方式，我在组件里面看到原型链里有一个$init方法，调用就报的这个错误，想请问这个方法的使用，还有这个报错不是我本身setData，是调用this.$init()这个方法报的错误，希望能帮我解答一下，谢谢

**Comment by Gcaufy** [comment]
`$init` 是在组件初始化过程中自行调用的，不要手动调用。
