### ISSUE TITLE
wepy.request()接口请求正确，前端无法获取返回数据，.then()中无法打印出任何字段

### ISSUE THREAD

**Issue by NingNingY** [Tencent/wepy#662]
app.wepy中已按照要求配置:

import wepy from 'wepy'
import 'wepy-async-function'
import Promise from 'promise-polyfill'

export default class extends wepy.app {
    constructor () {
       super()
       this.use('promisify')
       this.use('requestfix')
  }
}

**Comment by Gcaufy** [comment]
运行一下其它demo看看，判断一下是不是逻辑代码的问题
再换机器看一看，判断一下是不是手机的问题。

最后，请使用ISSUE_TEMPLATE

**Comment by NingNingY** [comment]
pages=>login.wpy页面中请求：
![image](https://user-images.githubusercontent.com/23693272/34088909-6d5dfc74-e3e7-11e7-86d9-1def6bdffa35.png)

**Comment by NingNingY** [comment]
使用开发者工具～

**Comment by qiao520** [comment]
then(res => console.log('这里不会打印'), res => console.log('这里可以打印'))

**Comment by czbczb** [comment]
![image](https://user-images.githubusercontent.com/23630100/41838102-fc6589a2-7891-11e8-814a-8513ac974801.png)
