### ISSUE TITLE
有关组件循环渲染的问题，repeat

### ISSUE THREAD

**Issue by ChazLun** [Tencent/wepy#665]
我的ui框架是选择了zanui这个框架，我再写购物车的时候，调用到zanui的计数器的组件；
<zanQuantity1 :quantity.sync="quantity1" :min="min1" :max="max1" componentId="quantity1" size="small"> </zanQuantity1>

quantity1，min1，max1主要是这三个值；
我用repeat去单独循环组件的时候没有问题，但是嵌入到block中，整个组件无法独立为单一。而且组件里面的所有事件，样式都没有了效果了。

期望的效果是每一个组件的计数器可以单独一对一。
现在是组件独立不出来。

**Comment by Gcaufy** [comment]
组件就是唯一实例
如果需要独立的组件，你需要写
```
<counter1 />
<counter2 />
```
