### ISSUE TITLE
[typescript] 当 lang="typescript" 时，编译后的 js 文件中缺少执行 Page() 代码

### ISSUE THREAD

**Issue by ciwyaitd** [Tencent/wepy#666]
## Description
  当 script lang="typescript" 时，编译后的 js 文件中缺少执行 Page()/ Component() 代码

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce
  在 script 中 加入 lang="typescript"

### Observed Results
  缺少执行 Page()/ Component() 代码
  
### Expected Results
  应该存在执行代码

## Relevant Code / Logs

  ```
  // TODO(you): code or logs ohere to reproduce the problem
  ```

**Comment by Gcaufy** [comment]
我生成demo后改成typscript编译没有出现问题
```
Page(require('./../npm/wepy/lib/wepy.js').default.$createPage(Index , 'pages/index'));
```

**Comment by ciwyaitd** [comment]
@Gcaufy 
请问 script 标签上面有加 lang=typescript 么？😢

**Comment by Gcaufy** [comment]
是的

**Comment by angrycans** [comment]
eslint: false
关闭eslint 即可

**Comment by ciwyaitd** [comment]
已解决。 主要问题是 compilerOptions。注释就好
compilers: {
        typescript: {
            // compilerOptions: {
                // module: "system"
            // }
        },
}

**Comment by Gcaufy** [comment]
@ciwyaitd 很多人会问到ts的问题，所以如果你正在使用ts开发，那能否贡献一些ts的DEMO出来？

**Comment by ciwyaitd** [comment]
@Gcaufy 
我们的一个基于 typescript 的 wepy-cli 项目 template。
https://github.com/MMF-FE/wepy-template

**Comment by buhe** [comment]
@ciwyaitd 有空看下 https://github.com/MMF-FE/wepy-template/issues/1 谢谢

**Comment by hanwenbo** [comment]
@ciwyaitd 你的方法无效  真正编译依然可以通过错误的ts

**Comment by ciwyaitd** [comment]
@hanwenbo 官方目前还没有支持 tslint 语法编译检查，目前只能通过编辑器做错误提示。

**Comment by hanwenbo** [comment]
@ciwyaitd 谢谢你 这块是官方的欺骗行为 建议改下文档  这样支持typescirpt没意义
