### ISSUE TITLE
如何在 page 和 component 中监控(绑定) globalData 变化

### ISSUE THREAD

**Issue by TimonPeng** [Tencent/wepy#667]
使用生命周期函数和 watch 都不行，如何监控或将 component data 与 globalData 进行绑定。

**Comment by TimonPeng** [comment]
redux?

**Comment by Gcaufy** [comment]
Redux 或者 将 globalData 赋值给组件的data

**Comment by zhenghongzhi** [comment]
试了将 globalData 赋值给组件的data不行，是我用错了还是只能用redux？
