### ISSUE TITLE
依赖文件的修改，没有重新编译依赖它的各文件

### ISSUE THREAD

**Issue by skyFi** [Tencent/wepy#668]
## Description

  外部依赖文件的修改，没有重新编译依赖它的各文件。
 如： 
```
// index.less
@import 'a.less'
```
```
// a.less
@import './b.less'
```
```
// b.less
@import './c.less'
```
```
// app.wepy
<style>
@import './src/style/index.less'
</style>
```
这时候，如果只修改文件`c.less`，新增去除样式等，依赖它的`a.less`,`b.less`,`index.less`,`app.wepy`都没有再编译，造成样式没有更新过来，需要手动把这一系列文件都编辑一下，或者重启工程才能解决。是否在监听编译的时候加上依赖？

## Environment

  * Platform: [开发者工具]
  * Platform version: [对应工具v1.01.1712150]
  * wepy version: [1.6.0]

**Comment by Gcaufy** [comment]
less中的依赖暂时没有处理依赖关系，不会被检测到，这是已知问题。

**Comment by skyFi** [comment]
@Gcaufy 在修复中吗？

**Comment by Gcaufy** [comment]
@skyFi 这个不在下一个小版本的修复计划中。
可以这样写避免这个问题
```
<style src="./a.less"></style>
<style src="./b.less"></style>
<style src="./c.less"></style>
```

**Comment by skyFi** [comment]
@Gcaufy 嗯嗯，谢了，先close这个issue了，你们纳入修复计划就好。
