### ISSUE TITLE
全局参数怎么直接渲染到页面模板？

### ISSUE THREAD

**Issue by callmesoul** [Tencent/wepy#669]
有方法全局参数直接在每个页面模板使用？比如app的userInfo,怎样才能直接在每个页面模板输出，而不用每页页面都取一下全局的值再渲染到页面模板

**Comment by Gcaufy** [comment]
在组件中加个userinfo的变量， 然后把全局的赋值给组件

**Comment by callmesoul** [comment]
@页面有二三十个，每个都这样弄么？

**Comment by callmesoul** [comment]
@Gcaufy
