### ISSUE TITLE
从1.5.8升级到1.6.0，出现白屏，降级后恢复

### ISSUE THREAD

**Issue by zhangchen91** [Tencent/wepy#670]
## Description

从wepy@1.5.8升级到1.6.0，出现白屏，降级后恢复
还请wepy团队帮忙推测下问题

## Environment

  * Platform: 开发者工具
  * Platform version: iOS 10.0.1
  * Wechat version: 6.5.6
  * wepy-cli version: 1.6.0
  * wepy version: 1.6.0
  * other version: [如果是插件问题，请列出问题插件的版本号]

  "dependencies": {
    "wepy": "1.6.0", // 跟wepy-cli一起降回1.5.8后白屏消失
    "wepy-async-function": "^1.4.4"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.1",
    "babel-plugin-syntax-export-extensions": "^6.13.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "cross-env": "^5.1.1",
    "eslint": "^3.18.0",
    "eslint-config-standard": "^7.1.0",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-plugin-html": "^2.0.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^2.0.1",
    "wepy-compiler-babel": "^1.5.1",
    "wepy-compiler-less": "^1.3.10",
    "wepy-eslint": "^1.5.2",
    "wepy-plugin-autoprefixer": "^1.0.0",
    "wepy-plugin-filemin": "^1.3.11",
    "wepy-plugin-uglifyjs": "^1.3.6"
  }
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

### Observed Results

![image](https://user-images.githubusercontent.com/1012304/34146111-a9474906-e4d3-11e7-8e78-08a62a61ff23.png)
  
### Expected Results
  
![image](https://user-images.githubusercontent.com/1012304/34145940-1b33a538-e4d3-11e7-9e9e-e550bd02bf99.png)

## Relevant Code / Logs

  ```
  // TODO(you): code or logs ohere to reproduce the problem
  ```

**Comment by Gcaufy** [comment]
没有复现代码我比较难定位这个问题。

**Comment by bluesky12** [comment]
wepy1.6.0下，computed函数中调用this.$apply()会导致小程序崩溃：页面白屏，控制台中输入showSystemInfo、console.log等均无响应。wepy1.5.8下正常。
复现代码：
```js
computed = {
    msg(){
        this.$apply();
        return '';
    }
}
```

**Comment by bluesky12** [comment]
wepy1.5.8之前的版本，不支持对组件的props进行watch，但支持在computed中进行引用，所以有时会用computed监听参数变化并进行相应处理。因而代码中会有computed中进行this.$apply()的现象。
但升级到wepy1.6.0之后，这部分代码就全崩了，如果在computed函数中进行console.log，会发现log日志输出数万次，然后停止输出，推测应该是陷入死循环了。

**Comment by Gcaufy** [comment]
@bluesky12 SEE: https://github.com/Tencent/wepy/issues/723

**Comment by bluesky12** [comment]
收到，谢谢。

**Comment by Gcaufy** [comment]
@bluesky12 ISSUE 已更新

**Comment by bluesky12** [comment]
好的，谢谢。
