### ISSUE TITLE
全局参数怎么直接渲染到页面模板？

### ISSUE THREAD

**Issue by callmesoul** [Tencent/wepy#675]
问：有方法全局参数直接在每个页面模板使用？比如app的userInfo,怎样才能直接在每个页面模板输出，而不用每页页面都取一下全局的值再渲染到页面模板

答：在组件中加个userinfo的变量， 然后把全局的赋值给组件

问：有二三十个页面都要用到，每个都这样弄么？有其他更好的方法么？

答：___________________________________________________________________________

**Comment by Gcaufy** [comment]
Mixin

**Comment by callmesoul** [comment]
@Gcaufy mixin 还不是要还没页面引入 跟每个页面赋值 差不多吧

**Comment by Gcaufy** [comment]
```
class BasePage extends wepy.page {}
class Page1 extends BasePage {}
class Page2 extends BasePage {}
```
这样呢。

**Comment by callmesoul** [comment]
@Gcaufy 可以有，但理想是一个类似与vuex的插件

**Comment by fantasy525** [comment]
hi 我看了回复貌似是要用继承实现，但是具体在代码里怎么写呢每个页面不是继承wepy.page么我们要全都混合到wepy.page类？

**Comment by Gcaufy** [comment]
@fantasy525 
弄一个basePage 继承 wepy.page 然后你们的page都继承 basepage就好了

**Comment by Gcaufy** [comment]
@callmesoul 
有wepy-redux

**Comment by callmesoul** [comment]
@Gcaufy 没用还是要在每个页面 @connect，工作量还是一样的。还不如吧挡redux的数据直接放在app，然后每个页面再从app拿。wepy-redux就没意义了

**Comment by Gcaufy** [comment]
另外应该还有个办法实现。
```
class BasePage extends wepy.page {
    data= {globalData: {g: 1}}
}

class Index extends BasePage {

     constructor () {
        this.data.mydata = 2;
    }
}
```
