### ISSUE TITLE
npm/wepy/lib/wepy.js" is not defined，跑不起来。是什么鬼

### ISSUE THREAD

**Issue by SnowFlowers** [Tencent/wepy#676]
![image](https://user-images.githubusercontent.com/16875486/34245396-ad1144b4-e664-11e7-8348-31acf4ded686.png)

**Comment by SnowFlowers** [comment]
我看了编译出来的代码，路径应该是正常的，但是就是报错

**Comment by Gcaufy** [comment]
ISSUE里很多这种问题最后是通过重启解决的。

**Comment by Liqiankun** [comment]
重启？@Gcaufy

**Comment by Gcaufy** [comment]
@Liqiankun 这个问题通常是因为开发者工具的缓存被破坏导致的。。通常情况下如果手动删除dist再build因为watch缓存原因导致重新build的代码不能被识别。这种情况杀掉进程重启一般能解决问题。

**Comment by lzl124631x** [comment]
我的情况是, 我尝试删除`dist`目录, 但是有些文件被占用没有删除成功. 然后就一直出现这个问题. 重启也没用. 最后关掉所有东西, 彻底删掉`dist`, 再重启就好了.

**Comment by Gcaufy** [comment]
重启，杀进程。。。
