### ISSUE TITLE
app onLaunch 方法没有执行完为什么就会执行 page 的onload呢

### ISSUE THREAD

**Issue by LewisLZ** [Tencent/wepy#680]
我使用 Promise 也测试了一下，都是相同的结果。
```
onLaunch(option) {
    this.testAsync()
}

sleep (s) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('promise resolved')
      }, s * 1000)
    })
  }

  async testAsync () {
    const data = await this.sleep(3)
    console.log(data)
  }
```

这条日志 会在page 页面都加载完后才打印出来
有什么办法可以 让app中 onShow或者onLaunch执行完 再去加载page 吗？

**Comment by Gcaufy** [comment]
没有办法去阻塞页面的加载的。
但是你可以在onLauch执行完后再去让page执行其它事情的。

**Comment by xiechao1211** [comment]
@Gcaufy 你好 请问如何在onlauch之后再去执行page中 onload里的相关方法？查询了蛮多资料，还没找到解决方案

**Comment by linjinying** [comment]
@xiechao1211 你找到方案了吗？我目前也遇到这个问题

**Comment by linjinying** [comment]
@Gcaufy 可以在onLauch执行完后再去让page执行其它事情的。具体的解决方案是？

**Comment by linjinying** [comment]
我举一个使用场景，比如内部有个通用`token`，我是在`app`的onLauch那里从服务端那里异步获取一个token，也加了**async/await**了，page/index的onLoad依赖这个token，但是好像onLauch没执行完，page/index的onLoad就触发了

**Comment by Gcaufy** [comment]
@linjinying 这个是JS的基础，回调机制的问题。。。可能跟之前的同步的思维有一些不一样。。
这里我没办法给你具体的解决办法。但是这里的思路是：
如果onLoad里的事件依赖于token，那么就把事件拿到获取到token的回调事件里面去。

**Comment by xiechao1211** [comment]
目前处理方式是 onlauch里不调用任何方法，需要用到登录信息的页面，在onload里单独调用。

**Comment by linjinying** [comment]
@xiechao1211 我现在也是这么处理的

**Comment by harrydengchao** [comment]
刚刚解决了这个问题。自己设计一套简单的事件总线就好了，需要token 的地方，绑定事件。请求道token 后，触发事件。
`bus.js`
```javascript
class Bus {
  constructor() {
    this.list = []
  }

  emit(functionName, args) {
    this.list.forEach((obj) => {
      if (obj.name === functionName && !obj.used) {
        obj.callback && obj.callback(args)
        obj.used = true
      }
    })
  }

  on(functionName, callback) {
    this.list.push({
      name: functionName,
      callback: callback,
      used: false
    })
  }
}

export default Bus
```

`app.wpy`
```javascript
wepy.$bus = new Bus()
```
