### ISSUE TITLE
关于使用wepy.request()返回的promise对象状态始终为false

### ISSUE THREAD

**Issue by psw386179555** [Tencent/wepy#682]
如题，不管request请求成功也是false
![image](https://user-images.githubusercontent.com/15834201/34316405-c6d6ee32-e7cf-11e7-990e-ca83e3adfe07.png)
![image](https://user-images.githubusercontent.com/15834201/34316410-e6675a66-e7cf-11e7-82e5-934f3ae26b1d.png)
不知道这个是不是对应的修复？
如果我加上promisify的话，那就没有网络请求了

**Comment by Gcaufy** [comment]
给出关键代码看看

**Comment by psw386179555** [comment]
就是照着文档关于wepy.request那段代码一样，报then没有定义错误

微末凡尘却也心向天空

**Comment by bigmeow** [comment]
@psw386179555 @Gcaufy 
这个问题是默认其实是没有开启promise，官方文档也没说到底怎么开启，翻了源码才知道：
在app.wpy文件里，找到`constructor`这个构造函数，里面代码如下：
```javascript
 constructor () {
    super()
    // 开启promise
    this.use('promisify')
    this.use('requestfix')
  }
```
算是个坑
