### ISSUE TITLE
引用有些npm package不成功

### ISSUE THREAD

**Issue by ron-liu** [Tencent/wepy#684]
## Description
* 有些package，install后，import后，编译无错，但`微信开发者工具`会报错。比如：`apollo-fetch` `apollo-link`, 等
* 还有些编译会报错，比如：`uuid`

## Environment
  * wepy-cli version: 1.6
  
## Reproduce
举例：apollo-fetch
1.  先安装包 `npm install apollo-fetch --save`
2. 再在`app.wpy`中添加`import {createApolloFetch} from 'apollo-fetch'`
3. 运行`npm run dev`
4. 打开`微信开发者工具`，报错：`module "npm/apollo-fetch/dist/bundle.umd.js" is not defined`

### Observed Results
在`dist/npm`目录下无`apollo-fetch`
  
### Expected Results
* 如果是因为小程序的环境中无所需的browser环境，应该尽量给详细的错误信息，比如`apollo-fetch`不成功，可能是因为需要`fetch`所致
* 应该不是所有的package都可以在wepy中使用，能否在文档中描述下，如果能说明下只有满足哪些条件的包才能被wepy使用

**Comment by Gcaufy** [comment]
刚测试了一下，编译报错，找不到`cross-fetch/polyfill`

我看了一下 apollo-fetch 的代码，他依赖去 `cross-fetch/polyfill`但是我打开cross-fetch 里面只有一个package.json文件。wepy暂时不支持之样的模块引用方式。

另外，我看了一下代码 ， apollo-fetch 是依赖 `node-fetch` 或者 `XMLrequest` 的，因此，即使是引用成功了，它也是无法在小程序都是无法运行的。

**Comment by Gcaufy** [comment]
对于一些库，可能是基于一些环境的基础东西去实现的，比如document, XMLrequest 等等，这一类库是没有办法在小程序端去运行的。因此你在引用这个库之前，需要知道这个库是怎么实现的。

**Comment by ron-liu** [comment]
我理解不能被调用因为依赖fetch，就是觉得应该有个警告。有可能是我刚才没有注意到，另外建议能把这些引用的规则写在doc里面。：)

**Comment by Gcaufy** [comment]
就好比如如果一个只支持node环境的npm包，你非要在web端去引用的话。那肯定是有问题的。。。
