### ISSUE TITLE
元素解析错误， attribute equal must after attrName

### ISSUE THREAD

**Issue by jimengchao** [Tencent/wepy#688]
wepy build --watch 后出现以下错误 ， line 和 col 都是undefined  无法定位哪一行

[Error] ERROR IN : src\pages\cart\index.wpy
[xmldom error]  element parse error: Error: attribute equal must after attrName
@#[line:undefined,col:undefined]

**Comment by Gcaufy** [comment]
xmldom的报错是有一些问题。建议先使用笨的方法，逐行删除来定位问题。

**Comment by MSunne** [comment]
在使用了三目运算符之后就会出现这个错误：
```html
<span class="{{(item.value<=item.maxV && item.value>=item.minV) ? 't-green' : 't-red'}}">{{(item.value<=item.maxV && item.value>=item.minV) ? "正常" : "异常"}}</span> 
```
