### ISSUE TITLE
无法使用正则表达式 (?<!)

### ISSUE THREAD

**Issue by wwhyes** [Tencent/wepy#693]
## Description
  问题描述：无法使用正则表达式 **(?<!)**

## Environment

  * Platform: 开发者工具
  * Wechat version: 1.6.0
  * wepy version: 1.6.0

### Observed Results
```javascript
// 去除样式中top|right|bottom|left
// 使用正则匹配
// ASCII表 | \55 - | \72 : | \73 ; |
let str = 'margin-top:12px;margin-bottom:12px;top:0;left:13px;' 
str.replace(/(?<!\55)(top|right|bottom|left)\72\w+\73/g, '') //  'margin-top:12px;margin-bottom:12px;'
```
报错: Invalid regular expression: /(?<!\55)(top|right|bottom|left)\72\w+\73/: Invalid group

**Comment by Gcaufy** [comment]
把代码复制到Chrom dev tool 运行试试

**Comment by wwhyes** [comment]
@Gcaufy  噢，好像是微信自己不行
