### ISSUE TITLE
'wepy' 不是内部或外部命令

### ISSUE THREAD

**Issue by nickHsiung** [Tencent/wepy#695]
[Description ]
'wepy' 不是内部或外部命令
## Environment
 windows 10 64位 dos
## Reproduce

  [如何重现问题]
  C:\Users\Administrator>**npm i  npm@latest -g**
D:\nodejs\node_global\npm -> D:\nodejs\node_global\node_modules\npm\bin\npm-cli.js
D:\nodejs\node_global\npx -> D:\nodejs\node_global\node_modules\npm\bin\npx-cli.js
+ npm@5.6.0
updated 1 package in 35.705s

C:\Users\Administrator>**npm install wepy-cli -g**
D:\nodejs\node_global\wepy -> D:\nodejs\node_global\node_modules\wepy-cli\bin\wepy.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\wepy-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ wepy-cli@1.6.0
updated 1 package in 47.913s
# 
_C:\Users\Administrator>**wepy new myproject**
**'wepy' 不是内部或外部命令，也不是可运行的程序**
或批处理文件。_

C:\Users\Administrator>
  [How to reproduce the issue]

**Comment by nickHsiung** [comment]
D:\nodejs\node_global 有个wepy.cmd 把它配到环境变量里就好了

**Comment by gauseen** [comment]
将 node 升级到 v8.0.0 就可以了
