### ISSUE TITLE
指定目录-s src/project热更新--watch报错

### ISSUE THREAD

**Issue by zichenmoshang** [Tencent/wepy#696]
运行命令wepy build -s ./src/project -o ./dist/project --watch
在修改某一个文件后，会报错文件不存在

<img width="514" alt="2017-12-26 4 32 02" src="https://user-images.githubusercontent.com/12508602/34351904-5a582d6a-ea5a-11e7-9e0f-83bb7aa9a3f0.png">

**Comment by zichenmoshang** [comment]
@Gcaufy 
源码中compile.js文件中生成config.file文件路径方法有误

<img width="897" alt="2017-12-27 11 30 28" src="https://user-images.githubusercontent.com/12508602/34369728-5d1614dc-eaf9-11e7-8843-1a2d58f45812.png">

**Comment by Gcaufy** [comment]
好的，欢迎PR
