### ISSUE TITLE
求问，双括号内能否调用函数？像这样： {{ caculate() }}

### ISSUE THREAD

**Issue by aim-leo** [Tencent/wepy#703]
因为需要将计算的逻辑分离开，这个在vue中是很普遍的功能，求问有没有办法实现？

**Comment by litongqian** [comment]
不支持,原生的也不支持,有一些情况可以使用computed解决, <wxs>也能解决一部分

**Comment by Gcaufy** [comment]
不支持，可以看一下原生 的wss
