### ISSUE TITLE
能否将组建实现为真正的Component

### ISSUE THREAD

**Issue by litongqian** [Tencent/wepy#704]
今天看了下官方的Component,发现一个页面可以多次使用,是多个实例,而且支持{{prop.value}},对于for循环组建也不会取不到值,实现了隔离,比wepy这种伪组建是不是更合理,希望能支持在编译后转为Component,
这样以后就可以实现强大的通用组建,提高开发效率

**Comment by JohnPion-Zhang** [comment]
在小程序component构造器出现之前我想这已经是让人惊艳实现方案了，但是template组件确实承担不起太多啦，期待作者更新

**Comment by Gcaufy** [comment]
计划在2.x的版本中，使用原生 组件实现。
