### ISSUE TITLE
promise的问题

### ISSUE THREAD

**Issue by KingJeason** [Tencent/wepy#706]
用了wepy的promise.
服务器返回的是422
用了全局拦截器,最后进入了success.
想问一下为什么不进入 fail里面呢

**Comment by Gcaufy** [comment]
这个应该改wepy无关，用原生试一下。

**Comment by bigmeow** [comment]
原生调用的还是原生的网络请求，不过注意这里的success的进入条件是指“只要请求发出去了，并且收到了服务端的响应，都算是一个成功的请求”
所以你还得自己判断状态码
