### ISSUE TITLE
关于小程序新增加的分包加载功能

### ISSUE THREAD

**Issue by fitcong** [Tencent/wepy#707]
我这边同样的使用方式,在原生框架上可以实现分包加载,并成功打开,但是在wepy框架下页面就是空白的,没有加载任何数据,前端小白的我也看不懂框架代码,求解答

**Comment by chen1zee** [comment]
我也遇到这个问题，改wepy的编译过程是有点难度，所以我是用gulp写了一个修改 dist/app.json 的 脚本，在作者还没更新支持分包前可以先试试   [https://github.com/chen1zee/gulp-tools-for-wepy](url)

**Comment by Gcaufy** [comment]
@fitcong @chen1zee 刚看了一下官方的分包功能，那个应该只是在app.wpy 里配置一下就可以了吧，是什么原因导致wepy不支持分包呢？能提供相关代码给我测试看看吗？

**Comment by fitcong** [comment]
@Gcaufy 原因我也是没看懂,小白见谅.测试代码就跟官方的一样. 就两个空页面一个是主包一个是分包.

**Comment by chen1zee** [comment]
@Gcaufy 编译过程中，cli好像会根据抓取到的app.json->pages:[]，数组来进行微信小程序的Page()调用，如这样子:Page(require('./../../npm/wepy/lib/wepy.js').default.$createPage(Home , 'pages/home/index'));
而分包之后，因为app.json->pages:[]无相关页面路径，对应的dist->page.js 就不会 调用 Page()函数，从而导致了分包出错。

**Comment by jimmyrogue** [comment]
我也遇到了同样的[问题](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=998271690&docid=000448cfa4468888c41668c4a5b800)

**Comment by Gcaufy** [comment]
@jimmyrogue 方便提供可复现代码么？

**Comment by jimmyrogue** [comment]
@Gcaufy 测试demo [demo](https://github.com/jimmyrogue/subpackage)
基础库版本1.7.4

**Comment by jimmyrogue** [comment]
@Gcaufy 老大 如何了

**Comment by Gcaufy** [comment]
@jimmyrogue 好的，现在比较忙，我周末看看

**Comment by jimmyrogue** [comment]
@Gcaufy 好的 辛苦了

**Comment by cmideal** [comment]
这个问题，确实存在，老大辛苦

**Comment by jayconscious** [comment]
望穿秋水

**Comment by Gcaufy** [comment]
@fitcong @chen1zee @jayconscious 

安装alpha包来体验看看分包功能还有问题吗？
```
npm install wepy-cli@1.6.1-alpha4
```

**Comment by fitcong** [comment]
@Gcaufy 刚刚测试了一下,可以进行分包加载了,大佬辛苦!

**Comment by jayconscious** [comment]
@Gcaufy @fitcong 
分包是没有问题了,但是工具上有一个报错
![image](https://user-images.githubusercontent.com/29750917/34659138-55e215a0-f470-11e7-965a-319d4ea24699.png)
在dist中相应的页面js没有 page 函数，不知道是不是我的分包写法有问题
![image](https://user-images.githubusercontent.com/29750917/34661135-91123738-f482-11e7-8853-94793b35af2c.png)

**Comment by jimmyrogue** [comment]
谢谢 已经可以使用了
@jayconscious 可以把配置和目录发上来看看 我没有出现这个错

**Comment by jayconscious** [comment]
@jimmyrogue 
![image](https://user-images.githubusercontent.com/29750917/34661650-0bfa2ad4-f486-11e7-9a51-6ec1046cb6b5.png)
![image](https://user-images.githubusercontent.com/29750917/34661756-ba0bfd1e-f486-11e7-897c-9d911a089e06.png)

**Comment by jayconscious** [comment]
![image](https://user-images.githubusercontent.com/29750917/34661839-3e93ed08-f487-11e7-9bb3-a915180da1da.png)

**Comment by jimmyrogue** [comment]
@jayconscious 文档里说：首页的 TAB 页面必须在 app（主包）内。那你的index应该就不能放分包里吧，我是这么理解的

**Comment by jayconscious** [comment]
@jimmyrogue   3Q,我在看看

**Comment by jayconscious** [comment]
@jimmyrogue  并不是写法问题,新版本的wepy-cli没有生效
npm install wepy-cli@1.6.1-alpha4 -g  必须全局安装

**Comment by callmesoul** [comment]
想问下是不是一定要有TAB ？
我没有tab，安装了npm install wepy-cli@1.6.1-alpha4 -g。
但还是不行，一直报：
`VM546:2 未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。`

**Comment by wells1013** [comment]
npm install wepy-cli@1.6.1-alpha7 -g。

**Comment by Gruidae** [comment]
wepy 1.7.1  也遇到 跳转分包页面空白的问题，分包的js代码都执行了，，手机预览也正常 就是开发工具报错，
Uncaught ReferenceError: $progress$index is not defined

**Comment by Gruidae** [comment]
@Gcaufy 
![snipaste_2018-04-04_10-29-13](https://user-images.githubusercontent.com/25906520/38285508-12510a64-37f3-11e8-9e8f-dd81a010bccf.png)

**Comment by Gruidae** [comment]
页面全是空白，，手机预览正常，，， wepy1.7.1

**Comment by Gruidae** [comment]
@Gcaufy  发现只要页面中有自定义组件（组件在主包里），分包开发者工具就会报这个错误 ，找不到页面，手机预览正常

**Comment by changyuwu** [comment]
请问下，我使用分包加载后，在别的包中增加了一个页面，为什么编译后导致主包的体积增大很多？

**Comment by jackywq** [comment]
@jimmyrogue ,我安装了v1.6.1-alpha4版本，并且进行分包配置，可还是报错了，
![4](https://user-images.githubusercontent.com/21954704/40155257-4243892e-59c5-11e8-9d99-30ffac03581b.png)
下图是分包配置的代码，帮忙看一下有没有什么问题？

![1](https://user-images.githubusercontent.com/21954704/40155194-e6bf81f2-59c4-11e8-9533-a5dcc26eacd0.png)
![2](https://user-images.githubusercontent.com/21954704/40155199-e89121fc-59c4-11e8-9c43-fb969c7d9e54.png)
![3](https://user-images.githubusercontent.com/21954704/40155202-ea8a6e14-59c4-11e8-983f-5bda9eca694a.png)

**Comment by jackywq** [comment]
@Gcaufy 大佬，按照你的方式结果还是报错了~

**Comment by jackywq** [comment]
问题解决了，是在编译的时候报错了，导致变成成功后，dist目录没有生成对应的js文件导致的
![2](https://user-images.githubusercontent.com/21954704/40162412-839b9940-59e6-11e8-9c24-d164b9435c9f.png)

![1](https://user-images.githubusercontent.com/21954704/40162346-5152caee-59e6-11e8-8bbc-0a209f75f3a9.png)

**Comment by wangjienihao** [comment]
有没有解决的啊 各位

**Comment by wangjienihao** [comment]
然后这个编译出来 主包跟分包文件不一样! 导致page未调用    怎么解决啊  各位大哥

**Comment by wangjienihao** [comment]
> @fitcong @chen1zee 刚看了一下官方的分包功能，那个应该只是在app.wpy 里配置一下就可以了吧，是什么原因导致wepy不支持分包呢？能提供相关代码给我测试看看吗？

**Comment by mllet** [comment]
你们都解决了吗？我分包页面加载了，但是还是是空白页面，是我什么地方没有设置好么

**Comment by yetianyes** [comment]
不行  ，子包页面一进去就是  VM4032:1 Page[packA/pages/public/orderInfo] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.

**Comment by Alaxkane** [comment]
分包页面可以进入，但是报这个错误，请问是什么问题
![image](https://user-images.githubusercontent.com/23330010/48757313-45532200-ecd7-11e8-801d-872e2108cd29.png)

**Comment by w19871029** [comment]
> 分包页面可以进入，但是报这个错误，请问是什么问题
> ![image](https://user-images.githubusercontent.com/23330010/48757313-45532200-ecd7-11e8-801d-872e2108cd29.png)
> ![image](https://user-images.githubusercontent.com/23330010/48757665-7aac3f80-ecd8-11e8-85d0-35ffbbcc268a.png)
> wxss和wxml都正常，就是js会报错，
> ![image](https://user-images.githubusercontent.com/23330010/48762127-53a83a80-ece5-11e8-8805-4ebf50a3e963.png)我安装的版本有问题吗
> ![image](https://user-images.githubusercontent.com/23330010/48762369-dd580800-ece5-11e8-9596-00255bec4744.png)
> app.json有问题吗编译出来的js里面
> ![image](https://user-images.githubusercontent.com/23330010/48763442-4a6c9d00-ece8-11e8-987f-564ac3ea4f47.png)是不是我的依赖有什么问题

我的也是出现这个问题 请问你的解决了吗 怎么解决的啊

**Comment by Alaxkane** [comment]
> > 分包页面可以进入，但是报这个错误，请问是什么问题
> > ![image](https://user-images.githubusercontent.com/23330010/48757313-45532200-ecd7-11e8-801d-872e2108cd29.png)
> > ![image](https://user-images.githubusercontent.com/23330010/48757665-7aac3f80-ecd8-11e8-85d0-35ffbbcc268a.png)
> > wxss和wxml都正常，就是js会报错，
> > ![image](https://user-images.githubusercontent.com/23330010/48762127-53a83a80-ece5-11e8-8805-4ebf50a3e963.png)我安装的版本有问题吗
> > ![image](https://user-images.githubusercontent.com/23330010/48762369-dd580800-ece5-11e8-9596-00255bec4744.png)
> > app.json有问题吗编译出来的js里面
> > ![image](https://user-images.githubusercontent.com/23330010/48763442-4a6c9d00-ece8-11e8-987f-564ac3ea4f47.png)是不是我的依赖有什么问题
> 
> 我的也是出现这个问题 请问你的解决了吗 怎么解决的啊

还没有解决，因为目前分包不是刚需，先搁置在这里了=。=

**Comment by Alaxkane** [comment]
@w19871029 没有，还是卡在这里，不太明白是哪里的问题=。=

**Comment by wangshaoqiu** [comment]
> @fitcong @chen1zee @jayconscious
> 
> 安装alpha包来体验看看分包功能还有问题吗？
> 
> ```
> npm install wepy-cli@1.6.1-alpha4 -g
> ```

大佬 麻烦再看看呢 ？这个问题还是没解决

**Comment by lsmtty** [comment]
通过手动修改打包出来的页面，貌似可以解决这种问题，期待官方修复
![image](https://user-images.githubusercontent.com/7869758/49004252-d0805c00-f19e-11e8-8681-29b2b4d19c8b.png)

**Comment by jimmyrogue** [comment]
> > 分包页面可以进入，但是报这个错误，请问是什么问题
> > ![image](https://user-images.githubusercontent.com/23330010/48757313-45532200-ecd7-11e8-801d-872e2108cd29.png)
> > ![image](https://user-images.githubusercontent.com/23330010/48757665-7aac3f80-ecd8-11e8-85d0-35ffbbcc268a.png)
> > wxss和wxml都正常，就是js会报错，
> > ![image](https://user-images.githubusercontent.com/23330010/48762127-53a83a80-ece5-11e8-8805-4ebf50a3e963.png)我安装的版本有问题吗
> > ![image](https://user-images.githubusercontent.com/23330010/48762369-dd580800-ece5-11e8-9596-00255bec4744.png)
> > app.json有问题吗编译出来的js里面
> > ![image](https://user-images.githubusercontent.com/23330010/48763442-4a6c9d00-ece8-11e8-987f-564ac3ea4f47.png)是不是我的依赖有什么问题
> 
> 我的也是出现这个问题 请问你的解决了吗 怎么解决的啊

wepy版本太低了吧。我用的是1.7.2-alpha4

**Comment by Alaxkane** [comment]
@jimmyrogue 和版本没关系，1.7.2的我也试过了，你的1.7.2可以用？

**Comment by Alaxkane** [comment]
@jimmyrogue 能不能发下你的app.js的配置，我看下是不是我哪里配错了

**Comment by jimmyrogue** [comment]
> @jimmyrogue 能不能发下你的app.js的配置，我看下是不是我哪里配错了

我注意到你的root目录是pages/inside，我记得是不允许在pages下面的，必须和pages同一级。
举个例子：
```
{
root: 'activities',
pages: [
    'activities/activityA',
    'activities/activityB'
  ]
},
```

**Comment by Alaxkane** [comment]
@jimmyrogue 好的，我稍晚时候试一下，万分感谢

**Comment by lsmtty** [comment]
wepy版本1.7.2,wepy-cli版本1.7.3打包后依然会出现未引用page的问题，查看wepy-cli源码断点调试。发现正常的页面中会用$createPage替换exports.default默认写法，但是分包中的页面走到这里的js编译后，下面判断type为空串，没有替换为目标代码，造成页面错误。
![image](https://user-images.githubusercontent.com/7869758/49798846-43342e80-fd7e-11e8-85e5-7f030c8edefc.png)
![image](https://user-images.githubusercontent.com/7869758/49798871-4d562d00-fd7e-11e8-8dfd-5b378b7e44d6.png)
暂时解决办法是，如果type为空赋值为page，经过测试打包正常，可以暂时解决这个问题，期待官方可以从根本上修复这个问题。
![image](https://user-images.githubusercontent.com/7869758/49798928-8393ac80-fd7e-11e8-805c-3681385af08c.png)

**Comment by lwzhang** [comment]
> wepy版本1.7.2,wepy-cli版本1.7.3打包后依然会出现未引用page的问题，查看wepy-cli源码断点调试。发现正常的页面中会用$createPage替换exports.default默认写法，但是分包中的页面走到这里的js编译后，下面判断type为空串，没有替换为目标代码，造成页面错误。
> ![image](https://user-images.githubusercontent.com/7869758/49798846-43342e80-fd7e-11e8-85e5-7f030c8edefc.png)
> ![image](https://user-images.githubusercontent.com/7869758/49798871-4d562d00-fd7e-11e8-8dfd-5b378b7e44d6.png)
> 暂时解决办法是，如果type为空赋值为page，经过测试打包正常，可以暂时解决这个问题，期待官方可以从根本上修复这个问题。
> ![image](https://user-images.githubusercontent.com/7869758/49798956-9908d680-fd7e-11e8-998f-5539c0a595de.png)

有效。
