### ISSUE TITLE
多个watch，里面改变了某个data，没有进行脏检查，在源码里有打log

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#711]
## Description
watch里修改了data的里的某个值，但是没有执行脏稽查把修改的值setData
  
代码:
watch
![image](https://user-images.githubusercontent.com/12985781/34475550-1468ea10-efc8-11e7-8747-a559717f10d0.png)

data：
translateY

wepy的component里的log:
![image](https://user-images.githubusercontent.com/12985781/34475562-27ba8420-efc8-11e7-81ae-1ce6f579198d.png)

log：
![image](https://user-images.githubusercontent.com/12985781/34475578-468ff574-efc8-11e7-8d12-d857d08ae5fc.png)

结论：
translateY改变了，但是没有放到readyToSt里，而且$$phase是$digest，所以
$$phase会变成false，while也会跳出。

这是个bug吗，还是说我哪个地方用错了？

**Comment by Gcaufy** [comment]
watch中不应该去改变data， 这个时候改变data,是没有办法加到readyToSet中的。。这个需求是否可以通过其它手段去实现呢？比如 computed 等等

**Comment by nishino-tsukasa** [comment]
computed开销有点大，所以才改用的watch
