### ISSUE TITLE
原生setData中有个渲染完成的callback回调

### ISSUE THREAD

**Issue by WarriorLau** [Tencent/wepy#712]
Wepy中绑定数据的方式或者修改后的setData方法都没有这个回调函数的入口(1.5.0新增)，能否添加或像vue中的nextTick一样使用的方法

**Comment by Gcaufy** [comment]
使用方法：

```
this.num++;
this.$nextTick(function () {
   // console.log('setdata callback');
});
```

或者
```
this.num++;
this.$nextTick().then(() => console.log('setdata callback'));
```

**Comment by BoleLee** [comment]
你好，我看文档说使用```$nextTick```需要wepy版本为v1.6.1，通过```npm install --save wepy@1.6.1``` 获取不到这个版本号的包，文档的更新日志也没有1.6.1版本的信息，请问如何获取1.6.1版本？ @Gcaufy

**Comment by richie523** [comment]
npm install wepy-cli@1.6.1-alpha7 -g

**Comment by BoleLee** [comment]
安装了```wepy-cli@1.6.1-alpha7``` 后，$nextTick 可以编译成功，但页面会报错：
```
thirdScriptError
this.$nextTick is not a function;
```
请问除了升级wepy-cli为1.6.1-alpha7, 是否还需要什么，才可以使用$nextTick ? 
附：
```
wepy-cli: 1.6.1-alpha7
wepy: 1.6.0
```

另外，升级wepy-cli@1.6.1-alpha7后，使用```wepy new project```无法创建项目
@richie523 @Gcaufy

**Comment by richie523** [comment]
推荐你检查下node_modules里面的wepy的版本号

**Comment by Gcaufy** [comment]
@BoleLee 
```
npm install wepy@1.6.1-alpha3 --save
```

**Comment by BoleLee** [comment]
wepy 版本号是 1.6.0
你的意思是要升级wepy版本吗 @richie523， 那么升级到哪个版本，我已经试过跟wepy-cli对应的版本号，但是获取不到
