### ISSUE TITLE
wepy会给wxs文件的filter添加“$组件名$”前缀，请问这个可不可以处理下

### ISSUE THREAD

**Issue by webKity** [Tencent/wepy#713]
使用wxs 做了一个filter，但是每次编译后都会出错。因为在编译过程中，wepy会给子组件添加“$组件名$”前缀，请问这个可不可以处理下，如果是filter关键字就不添加这个前缀

**Comment by Gcaufy** [comment]
是否可以提供相关代码方便参考一下呢？

**Comment by webKity** [comment]
编译后的代码：
![image](https://user-images.githubusercontent.com/8474916/34506682-f4858f12-f069-11e7-84c8-321f6b7088fc.png)

源码：
![image](https://user-images.githubusercontent.com/8474916/34506689-fef64eaa-f069-11e7-9eab-5cb405a78bb2.png)

这样就会导致我做编写的filter失效，因为模块名不一致了

**Comment by Gcaufy** [comment]
@webKity 这个问题没有那么快解决，建议先使用replace插件去做一下关键字替换，等真正的支持了filter再换回来。

因为filter比较特殊，所以考虑重新设计filter的语法，看看符合要求吗？

```
// page1.wpy
<template>
    <text>{{filter.doSomething(...)}}</text>
</template>
<script>
import filter from './../filter/filter1.wxs'
default class Page1 extends wepy.page {
   filters = {
       filter: filter
   }
}
</script>
```

**Comment by webKity** [comment]
没问题，下面这个语法是OK的，我目前就是发布的时候手动替换的

**Comment by AshaLiu** [comment]
这个还挺重要的 使用场景很高  求赶紧修正

**Comment by Gcaufy** [comment]
初步完成改功能，将语法修正为：

```
// page1.wpy
<template>
    <text>{{filter.doSomething(...)}}</text>
</template>
<script>
import filter from './../filter/filter1.wxs'
default class Page1 extends wepy.page {
   wxs = {
       filter: filter
   }
}
</script>
```

**Comment by Gcaufy** [comment]
@webKity @AshaLiu 

安装alpha包来体验看看wxs功能有没有问题？
```
npm install wepy-cli@1.6.1-alpha4
```

**Comment by webKity** [comment]
@Gcaufy  我这边暂时没有什么问题，可以正常运行

**Comment by AshaLiu** [comment]
我这里也OK
@Gcaufy   
小建议  咱们这个js引入  就没法儿用`import filter from '@/filters/Util.wxs'`
一定要`import filter from '../../filters/Util.wxs'`

另外wxs的高仿js语法有点糟心   要是有一个工具可以支持就更好了

**Comment by Gcaufy** [comment]
这里也考虑使用.js 或者 .ts 等。。。这样的话就没有高亮的问题了。

**Comment by richie523** [comment]
我更新了wepy-cli最新版1.6.1，wepy版本是1.6.0
import MathFr from '../filter/mathFr.wxs'引入会报错，"module "filter/mathFr.wxs.js" is not defined"
不知道是不是要单独做什么配置

**Comment by Gcaufy** [comment]
@richie523 
刚又测试了一遍，没有问题。
![image](https://user-images.githubusercontent.com/2182004/35496778-69a50f00-0502-11e8-96c7-cb0ce87d5e28.png)

打 wepy -v 验证一下版本吧

**Comment by richie523** [comment]
验证了版本，1.6.1-alpha7，我就觉得是不是要配置个什么，不然会自动给wxs结尾的文件补了一个js后缀，导致访问不到文件 
 
------------------ 原始邮件 ------------------
发件人: "Gcaufy"; 
发送时间: 2018年1月29日(星期一) 下午2:41
收件人: "Tencent/wepy"; 
抄送: "richie523"; "Mention"; 
主题: Re: [Tencent/wepy] wepy会给wxs文件的filter添加“$组件名$”前缀，请问这个可不可以处理下 (#713)

 

@richie523
 刚又测试了一遍，没有问题。
 
 
打 wepy -v 验证一下版本吧

**Comment by Gcaufy** [comment]
@richie523 
编译后的代码，js里是会注释到 import wxs的，然后在wxml里会有wxs的引用。
你看一下dist看看是哪一步出问题了？
无需配置，或者你提供一份demo我测试看看。

**Comment by maimake** [comment]
@Gcaufy 我这边试了下，用的是1.6.1-alpha8版本。发现一个问题：

page里设置组件的class，编译出来不见了。看了下编译出来的结果，跑到了wxs标签里了

page.wpy
```html
<homeitem class="l-item"></homeitem>
```

编译出来是这样了
page.wxml
```html
    <wxs src="../wxs/home.wxs" module="tools" class="_8bac0a6 l-item _b1f9678"/>
  <view class="homeitem _8bac0a6">
```

l-item 应该在view标签里才对

**Comment by Gcaufy** [comment]
@maimake 建议新开ISSUE,  https://github.com/Tencent/wepy/issues/907

**Comment by jiajiale** [comment]
wxs文件不能import其它文件么？引入会报如下错误：

> VM13525:2 ./wxs/filter.wxs
Expected LineFeed
> 1 | import util from '../utils/util';
    |           ^
  2 | module.exports = {
  3 |     isEmptyObject: function (obj) {
  4 |         return util.isEmptyObject(obj);

**Comment by tokenl** [comment]
> 我更新了wepy-cli最新版1.6.1，wepy版本是1.6.0
> import MathFr from '../filter/mathFr.wxs'引入会报错，"module "filter/mathFr.wxs.js" is not defined"
> 不知道是不是要单独做什么配置

请问你这个问题有解决吗，我也遇到了，但是我在开发者工具中是正常的，手机上会报这个错
