### ISSUE TITLE
ios设备杀进成后初次进入小程序页面中同时存在input和textarea，且绑定相同事件

### ISSUE THREAD

**Issue by Gruidae** [Tencent/wepy#715]
ios设备 : 在杀掉小程序重新进入时，最后一个input框输入完成后键盘消失时 textarea会自动触发change或者blur事件导致label变为textarea对应的参数，而e.detail.value未改变 导致的textarea中展示该input相同的内容 一起合并（input，textarea绑定相同的事件只是传入参数不同）
 // 表单数据双向绑定
    formInputChange(label, e) {
      let val = e.detail.value
      this.formdata = Object.assign({}, this.data.formdata, { [label]: val })
    },

**Comment by Gruidae** [comment]
额这个算wepy的还是小程序原生的bug？？

**Comment by Gcaufy** [comment]
建议用原生写个简单的测试试一下

**Comment by Gruidae** [comment]
测试了，是原生的bug，算是提错地方了。。
