### ISSUE TITLE
wepy.request用不了then

### ISSUE THREAD

**Issue by frontzhm** [Tencent/wepy#716]
wepy.request(...)使用之后用then报` thirdScriptError
Cannot read property 'then' of undefined;at pages/index onLoad function;at setTimeout callback function
TypeError: Cannot read property 'then' of undefined`

打印了wepy.request(...),发现就是undefined,但是在network中发现请求正确返回数据了

**Comment by frontzhm** [comment]
目前解决方案是
```js
wepy.request({
      url: 'xxxxxx',
      header: {
        'content-type': 'json' 
      },
      success: data => {
        console.log(data)
      }
    })
```

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/wiki/wepy%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8async-await

**Comment by Pacyx** [comment]
官网文档提供的 async-await 和promise 手动配置，都没有成效。为何升级后默认不支持该功能？？

**Comment by hcmuhi** [comment]
顶楼上，已解决
