### ISSUE TITLE
进入小程序返回微信再进入小程序watch不执行

### ISSUE THREAD

**Issue by nishino-tsukasa** [Tencent/wepy#717]
$data里的数据一直会保留，但是实例里的数据已经没了，导致watch无效。
举个例子，
有个组件:
prop:{a: -1}
data:{b:-1)
watch: a () {this.b = 10}
首页使用了这个组件，传值a为5.
因此watch检测到了a的变化，b变成了10.
但是返回微信，再进入小程序。
a再次赋值为5，但是$data里已经有了上一次的值，因此watch不会触发。这个时候b还是-1.。导致b的结果不正确

**Comment by Gcaufy** [comment]
能提供相关代码方便我还原问题么？

**Comment by nishino-tsukasa** [comment]
首页：
![image](https://user-images.githubusercontent.com/12985781/34488091-13f2bc38-f012-11e7-90e6-8dd9211a6f39.png)
![image](https://user-images.githubusercontent.com/12985781/34488094-1ce30d34-f012-11e7-89b0-3fbb7877004f.png)
![image](https://user-images.githubusercontent.com/12985781/34488116-3c271118-f012-11e7-9ce1-c044bdd52618.png)
panel：
![image](https://user-images.githubusercontent.com/12985781/34488228-982871e6-f012-11e7-8c6c-24b9218cf74b.png)
page1：
![image](https://user-images.githubusercontent.com/12985781/34488237-a325ba54-f012-11e7-96cc-77109efd58fc.png)
![image](https://user-images.githubusercontent.com/12985781/34488241-a8bd62be-f012-11e7-9f83-767a69cd7ffe.png)
点我：
![image](https://user-images.githubusercontent.com/12985781/34488345-1a15341e-f013-11e7-842e-53aba778ee5f.png)
再点一次点我：
![image](https://user-images.githubusercontent.com/12985781/34488360-26de8d1c-f013-11e7-84d3-4178953f5e8a.png)
这个和我上面描述的问题还不太一样。
上面那个问题需要引入了wepy-redux。页面中的a是@connect的a就会触发
