### ISSUE TITLE
子组件的repeat，props传值不正确

### ISSUE THREAD

**Issue by bobjiang1988** [Tencent/wepy#718]
## Description
`<repeat for="{{testList}}" key="path" item="page">
        <test :path.sync="page.path"></test>
      </repeat>`
在组建test中，path为undefined

**Comment by xialvjun** [comment]
path 在模板绑定中是有的吧，但是 js 去拿值时，拿到的是 undefined。。。。js 拿不到 动态传值。。。

**Comment by bobjiang1988** [comment]
#697 
原因在这里
