### ISSUE TITLE
关于mixins机制的改进意见

### ISSUE THREAD

**Issue by ChrisZ-B612** [Tencent/wepy#719]
## Description

当前mixins的功能不满足开发需求，主要有以下三点：

1. mixins中的方法和生命周期函数只能在页面之后执行，不能在页面之前执行；
2. mixins中的方法和声明周期函数，与页面中的方法和声明周期函数之间没有数据通信的方式；
3. mixins中定义onShareAppMessage函数无效。

我来说一下我们的业务场景：

比如说，我们需要在用户分享页面时，统一加上分享者的个人ID便于追踪，这时就需要改变页面中onShareAppMessage的返回参数，在分享链接上带上分享者的个人ID，这就需要在页面的onShareAppMessage执行之后拿到它的返回参数，然后执行一段自定义函数加上分享者的个人ID，所以我们需要mixins中的onShareAppMessage函数可以在页面的onShareAppMessage函数执行之后执行，并且能够拿到页面的onShareAppMessage函数的返回参数。

再比如说，用户打开上面分享的页面之后，我们需要在页面的onLoad函数执行之前拿到分享者的ID做一些事情，同时删掉分享者的ID等信息，这时我们就需要mixins中的onLoad函数要在页面的onLoad函数执行之前执行，同时可以改变传给页面的onLoad函数的参数。

---
为此，我有一个想法，希望你们可以认真考虑一下：
1. 首先是页面中声明mixins时，可以像这样声明mixins：
```javascript
mixins = {
    before: [BeforeMixin],  // before数组中声明的mixins的methods和生命周期函数会在页面执行之前执行
    after: [AfterMixin],    // after数组中声明的mixins的methods和生命周期函数会在页面执行之后执行
}
```
BeforeMixin和AfterMixin的代码如下：
```javascript
// BeforeMixin
<script>
import wepy from 'wepy';

export default class BeforeMixin extends wepy.mixin {
    methods = {
        tap (num) {
            console.log(num);   // 1
            num += 1;
            return num;
        }
    };

    onLoad(options) {
        options.from = 'before_mixin';
    }
}
</script>

// AfterMixin
<script>
import wepy from 'wepy';

export default class AfterMixin extends wepy.mixin {
    methods = {
        tap(num) {
            console.log(num);   // 4
        }
    };

    onLoad(options, another) {
        console.log(options.from);  // 'before_mixin'
        console.log(another);   // 'from_page'
    }
}
</script>
```

页面代码如下：
```javascript
<script>
import wepy from 'wepy';
import BeforeMixin from '../../common/mixins/BeforeMixin';
import AfterMixin from '../../common/mixins/BeforeMixin';

export default class Index extends wepy.page {
    mixins = {
        before: [BeforeMixin],  // before数组中声明的mixins的methods和生命周期函数会在页面执行之前执行
        after: [AfterMixin],    // after数组中声明的mixins的methods和生命周期函数会在页面执行之后执行
    }

    methods = {
        tap(num) {
            console.log(num);   // 2
            num += 2;
            return num;
        }
    };

    onLoad(options) {
        console.log(options.from);  // 'before_mixin'
        return [options, 'from_page']
    }
}
</script>

<template lang="wxml">
    <view @tap="onTap(1)">Hello wepy.</view>
</template>
```

其实就是一个过滤器的概念，总结一下上面这段代码包含的，也是我们的项目急需的功能点：
1. 在页面代码中，before数组中声明的mixins的methods和生命周期函数会在页面执行之前执行，而且是按before数组中声明的顺序执行，after数组同理，例如before数组中声明了3个mixins，每个mixin的onLoad分别打印出'before.mixin.1','before.mixin.2','before.mixin.3'，同样after数组中也声明了3个mixins，每个mixin的onLoad分别打印出'after.mixin.1','after.mixin.2','after.mixin.3'，页面中声明的onLoad打印出'page.onLoad'，那么输出的顺序应该是：'before.mixin.1','before.mixin.2','before.mixin.3','page.onLoad','after.mixin.1','after.mixin.2','after.mixin.3'。
2. 无论是mixins还是page中的methods和生命周期函数，参数的传递规则如下：
   1. 如果上一个函数没有返回值（没有return或者return undefined），那么将上一个函数接受的参数作为参数传递给下一个函数。
   2. 如果上一个函数有返回值且不是数组也不是undefined，那么将这个返回值作为下一个函数执行时的唯一参数；
   3. 如果上一个函数返回一个数组，那么将数组中的值按顺序传递给下一个函数，作为下一个函数执行时的参数。

我搜索过原来的issue list，发现有人提过issue要求将mixin中的函数执行时机改成在page之前执行，但是这样仍然不够完善（例如无法处理我上面提到的onShareAppMessage添加分享者ID的应用场景），所以如果能够按照上面这种设想做的话，那么wepy的mixin机制将会成为一个非常强大好用的功能！ @Gcaufy

**Comment by Gcaufy** [comment]
非常感谢你的意见。
Mixin的相关代码十分简单，你可以先尝试PR一下实现你想要的功能。
