### ISSUE TITLE
【建议】建议能在wepy中实现类似v-html的指令或者功能

### ISSUE THREAD

**Issue by webKity** [Tencent/wepy#724]
建议能在wepy中实现类似v-html的指令或者功能

**Comment by Gcaufy** [comment]
小程序原生能支持到么？

**Comment by webKity** [comment]
其实就是类似wxParse的一个功能:https://github.com/icindy/wxParse；这样又能多一个指令功能了，在微信中显示新闻之类的功能就方便很多了，不需要再去集成第三方的组件了

**Comment by Gcaufy** [comment]
原生不支持的功能没有办法去支持到

**Comment by webKity** [comment]
好吧
