### ISSUE TITLE
canvasContext.drawImage()，Android预览看不见图片,微信开发者工具可以看见

### ISSUE THREAD

**Issue by Haoz03** [Tencent/wepy#725]
------------------------
## Description

  [问题描述：canvasContext.drawImage(),在微信开发者工具上可以看到图片，但通过手机扫二维码预览却看不见图片]

## Environment

  * Platform: [开发者工具、Andriod]
  * Wechat version: [6.6.1]
  * wepy version: [1.6.0]

**Comment by Gcaufy** [comment]
这个应该是原生问题吧。请去开发者论坛提ISSUE

**Comment by Haoz03** [comment]
我用微信原生代码的写，在开发者工具和手机上浏览都没有问题
