### ISSUE TITLE
Uncaught Error: module "npm/wepy/lib/wepy.js" is not defined

### ISSUE THREAD

**Issue by SnowFlowers** [Tencent/wepy#726]
Uncaught Error: module "npm/wepy/lib/wepy.js" is not defined
![image](https://user-images.githubusercontent.com/16875486/34546734-d99a7614-f130-11e7-966e-b8c4b51b0352.png)
每一次打开都爆炸，动一下就爆炸。这个bug就不考虑fix一下吗

**Comment by JunedanVan** [comment]
![tim 20180104130416](https://user-images.githubusercontent.com/24771641/34550923-d93417d8-f14f-11e7-9a69-0b932b8718b8.png)
官方demo也跑不起来了，我的天啊！！！！！！！！！！！！

**Comment by Gcaufy** [comment]
这个问题出现过很多次了，建议搜索一下issue: https://github.com/Tencent/wepy/issues/676
