### ISSUE TITLE
分享事件

### ISSUE THREAD

**Issue by angelyu2014** [Tencent/wepy#729]
在页面如果有一个open-type=‘share’的button 别的鼠标交互都会默认走分享？
  
![image](https://user-images.githubusercontent.com/7630774/34570973-4f834dfc-f1a8-11e7-88bd-226cbc19da48.png)

**Comment by Gcaufy** [comment]
这个是原生问题吧。

**Comment by fitcong** [comment]
@angelyu2014 是不是你的页面有form表单的?

**Comment by narco001** [comment]
button的样式覆盖区域很大，调一下样式，button自带::after，display:none掉
