### ISSUE TITLE
调用this.$apply()之后，computed 没有重新计算值，但是UI更新了

### ISSUE THREAD

**Issue by SnowFlowers** [Tencent/wepy#732]
![image](https://user-images.githubusercontent.com/16875486/34599321-8fae9b3c-f22c-11e7-8e84-ced848d8b5ac.png)
![image](https://user-images.githubusercontent.com/16875486/34599328-988fbbaa-f22c-11e7-8728-e9856773aed2.png)
在方法里面调用之后，界面UI更新，但是compoted没有执行，computed值没有更新

**Comment by Gcaufy** [comment]
代码看起来并没有问题，建议debug一下看一下为什么compited 没有执行
