### ISSUE TITLE
onRoute函数回退键也会调用

### ISSUE THREAD

**Issue by tonycff** [Tencent/wepy#736]
看wiki说onRoute是为了解决某些情况下onShow会被调用的问题，比如回退键等。

现在实测发现点击左上的回退按钮也会调用此函数。不知是设定还是bug？

现在想实现的功能：
点击list页面上按钮到详情页，详情页提交后使用
          wepy.navigateBack({
            delta: 1
          });
返回上一页，并刷新页面，加载新提交的内容。但如果用左上角回退或者手机回退键不要刷新list页面。

**Comment by Gcaufy** [comment]
页面变了，就会调用onRoute
