### ISSUE TITLE
wx原生request 请求的回调 complete事件，在wepy的哪里？

### ISSUE THREAD

**Issue by JunYanchan** [Tencent/wepy#738]
success 是在 then中 ， fail是在catch中 那么complete是在哪里？

**Comment by jun1st** [comment]
用了await， 返回结果就肯定是 complete 的了

**Comment by Gcaufy** [comment]
只有`success` 和 `fail` 没有 `complete`， 感觉complete 这个设计比较鸡肋。
如果一定要用的话可以使用 `wx.request`
