### ISSUE TITLE
组件化使用方面bug太多啦哥

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#739]
如果连基本的repeat都存在各种问题，还怎么组件化编程？
我想在父组件里通过动态传值把数据传给子组件，wx:for没法动态传dict吧？好那我用repeat，子组件里无法通过:item="foo.bar"这样两级的方式动态传值到子组件的子组件，那就只好用computed属性减少一下层级了，然后computed的值又一样我去（bug得一脸蒙逼）...这下好了卡死了做不下去了...，我擦泪...
大神你说肿么办？用wepy就是想组件化编程结果嵌一层就有bug，再多嵌一层就做不下去，腾讯哥你为啥要发明个新框架呢？

**Comment by coolhwm** [comment]
page -> 组件的情况，用computed减少一层可以
repeat 组件 -> 子组件，用computed就不行了，在repeat的组件里面只有props是独立的吧

**Comment by Gcaufy** [comment]
@cuijiemmx 在组件repeat上会有一些坑，主要是实现原生导致，但并不是不可避免的。多层嵌套是没有什么问题的。

后面会考虑重写这一部分代码的。

**Comment by byk04712** [comment]
repeat 组件 -> 子组件，用computed，computed里每次获取到的值始终是数组的第一个，这个问题我也遇到了。
```
    <repeat for="[{prop:'valueA'},{prop:'ValueB'}]">
        <item :data="item"></item>
    </repeat>
```
**item.wpy**
```
<template>
    <!--这里值 property 一直是ValueA-->
    <text>{{property}}</text>
    <!--这样才正确-->
    <text>{{this.item.prop}}</text>
</template>


computed = {
    property() {
        return this.item.prop;
    }
}
```

希望快点修复这个bug吧

**Comment by hanwenbo** [comment]
@byk04712 永远是第一个
