### ISSUE TITLE
没有Import的文件为什么也会拷贝到dist目录中?

### ISSUE THREAD

**Issue by bobjiang1988** [Tencent/wepy#745]
## Description

没有Import的文件为什么也会拷贝到dist目录中?

### Expected Results

没有Import的文件可以不拷贝到dist中, 减小小程序代码体积

**Comment by Gcaufy** [comment]
两种情况：
1. 如果代码中存在类似代码会被考到dist中
```
// import a from 'a';
```
因此，请删除类似注释代码

2. import a, 但是a依赖b，那么a,b,都会考到dist

除此之外，不会有没有用到的代码被拷贝到dist
