### ISSUE TITLE
三方库错误，如何解析json文件

### ISSUE THREAD

**Issue by NoraGithub** [Tencent/wepy#747]
使用了 markdown-it 做渲染。
编译后代码（`dist/*`）里这条语句`module.exports = require('./../../../entities/maps/entities.json');`
导致`npm/entities/maps/entities.json.js" is not defined`错误
看起来是把`.json`文件识别成` json.js`了
其他项目我使用webpack用 `raw-loader` 可以解决。不知道这个如何解决

**Comment by Gcaufy** [comment]
JSON文件 改成 js 文件成本不高。

**Comment by NoraGithub** [comment]
这个文件在三方库里吖，我`npm install` 回来的。每次`npm run build`都重写我的dist吖。dist里修改没意义吧。
另一方面，简单阅读代码发现，这个`json`文件是代码动态创建的，这意味着要读懂源代码并修改之吗？不是一个正确的开发过程和良好的开发体验吧。

**Comment by NoraGithub** [comment]
@Gcaufy 可以重开下这个issue吗？

**Comment by Gcaufy** [comment]
具体是哪个库

**Comment by NoraGithub** [comment]
markdown-it
使用`import MarkdownIt from 'markdown-it/dist/markdown-it.min.js'`
解决。

**Comment by youxianbo** [comment]
我使用 mini-html-parse2这个库也出现这个情况，如何解决

**Comment by gui-che** [comment]
我使用axios这个库也出现了这种情况，如何解决呢 @Gcaufy
