### ISSUE TITLE
repeat 和 组件

### ISSUE THREAD

**Issue by LewisLZ** [Tencent/wepy#748]
什么时候能真正的支持repeat中循环 自定义组件呢？
现在的用法局限性太高了，写了一堆处理数据的代码
如果想在 组件中操作，更是麻烦。因为repeat 循环的组件中 在js 代码中拿到 props 数据都是相同的

**Comment by Gcaufy** [comment]
先避免使用repeat，会在2.x版本中处理这些问题

**Comment by LewisLZ** [comment]
@Gcaufy 2.x 预计什么时候 发布呢？
