### ISSUE TITLE
wepy 尝试使用wepy.request 可以发起请求但是获取不到response 值

### ISSUE THREAD

**Issue by assassin0905** [Tencent/wepy#751]
直接使用wepy 新建的一个项目 ，将10次请求换了一个连接，将success结果打印显示
![image](https://user-images.githubusercontent.com/1409506/34819396-953610dc-f6f8-11e7-8b64-687a05a564d3.png)

在开发工具中看不到打印的结果，若将wepy.request 改成wx.requst 就可以获取到success里面的结果了

**Comment by Gcaufy** [comment]
刚测试了一下，是没有问题的。

**Comment by Gcaufy** [comment]
看看是不是没有 promise化

**Comment by xufang2004007** [comment]
谢谢 确实是 我把promise 移除了 就可以收到response了！！！！谢谢
