### ISSUE TITLE
在onLaunch时如何获取到微信小程序实例（getApp()）？

### ISSUE THREAD

**Issue by etflly** [Tencent/wepy#753]
在原生的写法中，`onLaunch`中可以通过`this`指针获取到小程序实例。但是wepy里直接`getApp()`或者`wepy.$instance.$wxapp`获得的是`undefined`。

这种情形下有没有方法可以直接获得小程序实例？

**Comment by Gcaufy** [comment]
1. onLaunch 的阶段是拿不到小程序实例的
2. this 只 wepy.app 的实例而不是小程序实例

**Comment by etflly** [comment]
@Gcaufy 
原生的小程序是可以再onLaunch阶段拿到小程序实例的。如下图：
![1](https://user-images.githubusercontent.com/4463138/34877369-b8624e84-f7e0-11e7-9b50-d6d20a06de54.png)
运行得到：
![2](https://user-images.githubusercontent.com/4463138/34877378-c32dc91a-f7e0-11e7-9209-cb179636463f.png)

**Comment by JiajunW** [comment]
问题还没解决。使用 wepy 定义 app 时 this.$wxapp 是 undefined

原生小程序在定义 App 的时候并不能通过 getApp() 来拿到实例，而是需要直接用 this 来访问到。参考：https://mp.weixin.qq.com/debug/wxadoc/dev/framework/app-service/app.html

**Comment by wuzhuzhu** [comment]
这个问题同样困扰了我 登陆信息放在哪里很头疼

**Comment by jayconscious** [comment]
希望可以尽快解决哈，不过现在我是放在storage中的@wuzhuzhu

**Comment by frontbear** [comment]
@Gcaufy 麻烦下个版本解决下这个问题，谢谢

**Comment by ZhuoYitao** [comment]
@wuzhuzhu 自己定义个全局对象，放里面就好了

**Comment by iiewad** [comment]
this.$parent.globalData.userInfo

**Comment by fplun** [comment]
> @Gcaufy
> 原生的小程序是可以再onLaunch阶段拿到小程序实例的。如下图：
> ![1](https://user-images.githubusercontent.com/4463138/34877369-b8624e84-f7e0-11e7-9b50-d6d20a06de54.png)
> 运行得到：
> ![2](https://user-images.githubusercontent.com/4463138/34877378-c32dc91a-f7e0-11e7-9209-cb179636463f.png)

这是什么神仙操作
