### ISSUE TITLE
编译.wxml文件错误

### ISSUE THREAD

**Issue by vera0707** [Tencent/wepy#758]
node 6.10.3
![image](https://user-images.githubusercontent.com/15856998/34867345-bb11fcc2-f7ba-11e7-8e64-1ef0d6c3d97e.png)
新建项目之后就会酱婶 
已经尝试过好几次 node也换了几个版本 每次都有问题

**Comment by Gcaufy** [comment]
是不是删除过dist了？重启试试

**Comment by lin-hun** [comment]
删了重装

**Comment by YouYII** [comment]
重启微信开发工具就可以

**Comment by anlia260** [comment]
@YouYII 可以讲讲为什么吗？

**Comment by YouYII** [comment]
@anlia260 我也是遇到这个问题, 才来找解决方法的..
但是看起来应该是因为 dist 目录删除重建了, 但是微信开发工具对这种操作支持不好,可能是缓存了啥东西 , 我都删除项目了,然后重建都不行, 一定要重启开发工具!
我的微信开发工具是v1.02.1801081

**Comment by Gcaufy** [comment]
@anlia260 开发者工具会监听dist目录的修改，如果删除dist后，再生成dist。不会监听到新的dist文件

如果需要删除dist重建的话，请使用`rm -rf dist/*` 来代替 `rm -rf dist`
