### ISSUE TITLE
wepy-cli 问题：未定义 dir

### ISSUE THREAD

**Issue by ColMugX** [Tencent/wepy#759]
## Description

```
/usr/local/lib/node_modules/wepy-cli/lib/compile-wpy.js:67
                    _util2.default.error('ERROR IN : ' + _path2.default.relative(_util2.default.currentDir, _path2.default.join(opath.dir, opath.base)) + '\n' + x);
                                               ^

TypeError: Cannot read property 'dir' of undefined
```

在安装了`wepy-compiler-pug`和配置了`pug`之后出现的问题，前后没有其他操作。

写了一个`pug`的组件
```pug
view
  text HelloWorld
```

## Environment

  * wepy-cli version: v1.6

**Comment by Gcaufy** [comment]
什么原因呢？

**Comment by ColMugX** [comment]
重新new一个项目就没有这种情况了，挺奇怪的。现在已经解决了。

**Comment by GooeyNyan** [comment]
@Gcaufy 
大概是… () 里的动态属性 `:` 前得空空格，不能直接跟 `(`

谢谢，辛苦了！

🌰:
 ![编译正常](http://ow3n69arp.bkt.clouddn.com//18-3-15/75903775.jpg)
 ![编译错误](http://ow3n69arp.bkt.clouddn.com//18-3-15/16988067.jpg)

**Comment by GooeyNyan** [comment]
嗯，发现不只是 `:`
类似
```pug
view.send-btn( @tap="handleTapOnSendBtn") +
```
`@tap` 和 `(` 之间也需要空格

[类似的问题](https://github.com/Tencent/wepy/issues/1077)
issue 1077 应该也是这个原因。
