### ISSUE TITLE
小程序运行时如何在console中查看globalData

### ISSUE THREAD

**Issue by etflly** [Tencent/wepy#761]
现在有一个调试需求，在globalData中绑定的值想要在console中实时打印他的值。wepy似乎把globalData留在了wepyApp的实例里，wxApp实例里没有这个量。而wepyApp目前不知道怎样在console中索引到。

有什么优雅的方式解决这个问题？

**Comment by Gcaufy** [comment]
`this.$parent.globalData`

globalData 只是一个自己定义的变量你想定义在wepy.app实例或者 wx App 实例都行。。

**Comment by etflly** [comment]
@Gcaufy 

如果要定义在wxApp里的话就牵扯到定义wepyApp时如何拿到wxApp实例，我在 #753 提过这个问题

**Comment by Gcaufy** [comment]
已经fix了#753

**Comment by gzlboy** [comment]
@Gcaufy 没解决呀？刚试了下不行
