### ISSUE TITLE
wepy 编译里面注释报警告 build 结果为空

### ISSUE THREAD

**Issue by aristotll** [Tencent/wepy#763]
```
<!--有注释的文件...-->
<template>
    <repeat for="{{list}}" key="index" index="index" item="item">
        <child :item="item"></child>
    </repeat>
</template>

```

> [WARNING] WARNING IN : mini/builtin/repeat/RepeatTag.wpy
> [xmldom warning]	unclosed xml attribute
> @#[line:undefined,col:undefined]

生成的文件 为空 wcss wxml  之类的
然后我把注释移动到 wepy文件的最后 警告没了 文件也正常了...

**Comment by aristotll** [comment]
或是另外一个和注释相关的问题 
```
<!--<script lang="typescript">-->
<script>
```
components  无法编译 还是原来的东西 `<ComponentName/>`

然后把注释删了就可以了 ....

**Comment by yangfandashuaige** [comment]
我遇到过 wepy编译的时候会找你的文件路径 找不到的话 哪怕你注释也会报错
还有就是你在页面引用了你的组件，但是你没有用的话 也会报错
