### ISSUE TITLE
props 传递参数为动态时，使用 sync 标记也不能获取最新数据

### ISSUE THREAD

**Issue by chenillen** [Tencent/wepy#765]
## Description

Page 传 props 给 component 时，如果参数为动态获取，则不能传入，子 component 只能获取最出始的值。

```
<!-- in Page index.wpy  -->
<script>
import wepy from 'wepy'
import Tab from '@/components/Tab'

export default class Index extends wepy.page {
  ...

  components = {
    tab: Tab
  }

  data = {
    tabs = {
      height: '60rpx',
      currentTab: 'all',
      list: []
    }
  }

  ...

  async onLoad() {
    this.tabs.list = await fetch('xxxxx')
      .json()
  }

  ...
}
</script>
<template>
<tab :tab.sync="tabs"></tab>
</template>


<!-- in Component nav.wpy  -->
<script>
import wepy from 'wepy'

export default class Catenav extends wepy.component {

  props = {
    tab: {
      type: Object,
      default: {}
    }
  }
}
</script>

<template>
<view>
  <block wx:if="{{tab.list.length > 0}}">
    <scroll-view scroll-x="true" height="tab.height ? tab.height : 'auto'">
      <repeat for="{{tab.list}}" key="index" index="index">
        <view data-slug="{{item.slug}}">
          <text>{{item.name}}</text>
        </view>
      </repeat>
    </scroll-view>
  </block>
</view>
</template>
```

在 Component Tab 中，this.tab.height, this.tab.currentTab 都能獲取，但是 this.tab.list 獲取的但是 []，expected 的值是通過 async 獲取的數據。

## Environment

  * Platform: [iOS]
  * Platform version: [11.2.2]
  * Wechat version: [6.6.1]
  * wepy-cli version: [1.6.0]
  * wepy version: [1.6.0]

**Comment by chenillen** [comment]
Sorry for bothering.

應該是 `this.$apply()` 运用不当，已经解决。

在 onLoad 请求数据后， 应该 apply 脏数据。

**Comment by Gcaufy** [comment]
异步需要apply

**Comment by BoleLee** [comment]
props传值，获取数据后有使用$apply()，确认传入组件的值是有正常改变的，但组件内的props仍是最初的值，简化代码如下：
```
<barrage :comments="comments" :height="barrageHeight"></barrage>

data = {
    barrageHeight: 48,
    comments: []
}
onLoad() {
      var that = this
      wepy.getSystemInfo().then(function(res) {
        var rpxRatio = 750 / res.windowWidth
        that.barrageHeight = (96 / rpxRatio).toFixed(0)
        that.$apply()
      })
    }
```

**Comment by Niofh** [comment]
楼主你怎么解决的，我也是遇到你这个问题。加了$apply和.sync都不行！！！

**Comment by chenillen** [comment]
在获取异步数据并且赋值后，用 this.$apply() 检查脏数据就可以了。

**Comment by a24576946** [comment]
我也是加了sync和￥apply()不行啊

**Comment by jiangdianen** [comment]
我也遇到了 $apply和.sync 都不行

**Comment by liuzhenji** [comment]
我这里也不好使。。。是BUG么？我关闭自动压缩了。楼上的同志有解决了的吗？
@jiangdianen @a24576946

**Comment by BoleLee** [comment]
@liuzhenji  看看[文档中关于props传值部分](https://tencent.github.io/wepy/document.html#/?id=props-%E4%BC%A0%E5%80%BC), 静态传值与动态传值不同，其次，与Vue的使用方式也有所不同，可见[Vue文档Props](https://cn.vuejs.org/v2/guide/components-props.html), [.sync修饰符](https://cn.vuejs.org/v2/guide/components-custom-events.html#sync-%E4%BF%AE%E9%A5%B0%E7%AC%A6)

如果以上都了解清楚了，还有一条，如果你的自定义组件是循环使用的，WePY

> 不支持在 repeat 的组件中去使用 props, computed, watch 等等特性。
[WePY文档：存在的问题](https://tencent.github.io/wepy/document.html#/?id=%E5%AD%98%E5%9C%A8%E7%9A%84%E9%97%AE%E9%A2%98)

**Comment by BoleLee** [comment]
@liuzhenji 那就用wepy支持的写法呀，还有原生自定义组件，再不然你也可以不用wepy, 用mpvue

**Comment by liuzhenji** [comment]
不是不支持，是应该支持却不好用。我现在还不敢用wepy上原生。
不过也是的，这个wepy项目完了，打算使用weapp-start开发原生的了。

**Comment by LiJiangPeng** [comment]
> 动态传值，$apply和.sync 都加了，在开发者工具上好好的，但是放到真机上就不行了，现在已经不敢用这个动态传值了，还是直接调用组件方法靠谱

这可整啊，你最后怎么解决的？

**Comment by chenillen** [comment]
這個組件傳值是靜態的，所以如果在同一個 page 多次復用 compoennt（非 repeat `的），最好是單獨一個新的實例。這樣不容易出錯。例如：

```
import Header from '@/components/header'

export default class SomePage extends wepy.page {
  components = {
    header: Header,
    pageHeader: Header
  }
}
```

**Comment by kopuCoder** [comment]
> 动态传值，$apply和.sync 都加了，在开发者工具上好好的，但是放到真机上就不行了，现在已经不敢用这个动态传值了，还是直接调用组件方法靠谱

请问这个问题有解决办法吗，我这里也遇上了一模一样的问题，坑了好几天了

**Comment by aidaqiudeaqiao** [comment]
我是菜鸡一个，乱写的好像能成。
  <div class="loading"  v-if="!loadingFlag">
          
  </div>

 <div v-else>
     使用的子组件
   <mycop :data="list" />
</div>


data: {
   list: [],

},
onload() {

}

**Comment by aidaqiudeaqiao** [comment]
我是菜鸡一个，乱写的好像能成
子组件《mycop :list="list" v-if="loading" /》
 在给异步请求之前，先对子组件封装成v-if=“loading = false”，请求完成之后，对list赋值，再对loading=true
 应该能成
