### ISSUE TITLE
带有-的属性在模板中渲染出错

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#766]
如果属性名不包含-就没有问题，比如
```
<view hover-class="{{testClass}}">
...
export default class extends wepy.component {
  data = {
    'testClass': 'test'
  }
...
```
渲染出的效果是`<view hover-class="test">`

但是如果将testClass改成test-class
```
<view hover-class="{{test-class}}">
...
export default class extends wepy.component {
  data = {
    'test-class': 'test'
  }
...
```
渲染出的效果是`<view hover-class="NaN">`

你可能会建议我始终使用camel case，但是如果我是自定义组件的自定义属性名，有时为保持一致需要使用-而不是camel case，比如自定义一个组件，为保持和小程序组件的一致性，我需要定义一个名为hover-class的属性。

请问-的属性如何可以正确在模板中解析出来？或者这是一个bug？

**Comment by Gcaufy** [comment]
你用原生试试, 同样显示的是NaN, 所以不允许这样做
数据是变量，组件是标签，标签可以 a-b，但变量不行。
```
<text>
    {{test-num}}
</text>

this.setData({'test-num': '123'})
```
