### ISSUE TITLE
页面传递参数问题

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#767]
我有一个base64编码的id（id中带有=号，值为`‘VXNlci0xMA==’`）需要从一个页面传递到另一个页面，
`wepy.navigateTo('/pages/xxx?id=VXNlci0xMA==')`
这种写法运行时会报错，显然是因为id中的=导致的，所以很自然地想到先把id参数urlencode一下urlencode后请求变为
`wepy.navigateTo('/pages/xxx?id=VXNlci0xMA%3D%3D')`
嗯，这样可以跳转到目标页面了，然后打印出参数看看
```
onLoad(options) {
console.log(options)
}
```
打印出的结果是
`{id: "VXNlci0xMA"}`
发现问题没? 解析出的id比原始id少了两个末尾的=号...

一脸蒙逼。。

**Comment by Gcaufy** [comment]
似乎是原生问题，用原生 试试
另外，试试
```
this.$navigate('./xxxx', {id: xxxxx})
```

**Comment by cuijiemmx** [comment]
@Gcaufy 并没有这个方法，这样调用直接报错方法找不到

**Comment by Gcaufy** [comment]
```
this.$root.$navigate
```

**Comment by limingyang2012** [comment]
是不是哪里写错了啊，我本地实验是好的
`var pa = encodeURIComponent('sssww==');
    wx.navigateTo({
      url: '../inner/index?id='+pa
    })
`
`console.log(decodeURIComponent(options.id))`
输出来是sssww==

**Comment by cuijiemmx** [comment]
@limingyang2012 请直接用我给出的数值测试，这个bug和取值有关
