### ISSUE TITLE
引用组件，报Setting data field "$hotDesign$hotGoods" to undefined is invalid.

### ISSUE THREAD

**Issue by bulolo** [Tencent/wepy#768]
------------------------
## Description

![image](https://user-images.githubusercontent.com/10026498/34918116-202c99b2-f989-11e7-976c-2a4fa48149de.png)

 你好，引用了这两个组件，总是报这个错，无法确定是什么原因
![image](https://user-images.githubusercontent.com/10026498/34918166-5dc045d0-f989-11e7-9ab3-a9f7542e3699.png)

![image](https://user-images.githubusercontent.com/10026498/34918155-3eede270-f989-11e7-9e38-fffd1026d78f.png)

![image](https://user-images.githubusercontent.com/10026498/34918159-42dcaed4-f989-11e7-8bc7-8d0d9a215706.png)

```
props = {
      goodsType: {
        type: Object
      }
}
//报如上错误
```
```
props = {
      goodsType: Object
}
//报如上错误
```

```
props = {
      goodsType: {
        type: Object,
        default: {}
      }
}
//不报
```

**Comment by Gcaufy** [comment]
什么问题？
