### ISSUE TITLE
使用wepy的uploadFile和downloadFIle时，progress找不到

### ISSUE THREAD

**Issue by pinguo-weihaodong** [Tencent/wepy#769]
使用wepy的uploadFile和downloadFIle时，progress找不到

环境：
  * Platform: 开发者工具/iOS/Andriod
  * wepy-cli version: 1.6.1-alpha3
  * wepy version:  1.6.0

代码：
  ```
        wepy.downloadFile({
            url: 'http://www.baidu.com/img/bd_logo1.png'
        }).then(res => {
            console.log(res)
        }).catch(error => {
            console.log(error)
        }).progress(pro => {
            console.log(pro)
        })
  ```
报错：
```
       wepy_1.default.downloadFile(...).then(...).catch(...).progress is not a function
```

**Comment by Zettle** [comment]
我也遇到这个问题，要怎么解决

**Comment by nxboo** [comment]
对啊，怎么解决

**Comment by wangcash** [comment]
wepy 内只实现了request方法，没有uploadFile和downloadFile的实现
应该使用wx.uploadFile和wx.downloadFile

**Comment by Gcaufy** [comment]
可能参考这个：https://github.com/Tencent/wepy/pull/509
另外，使用 `wx.uploadFile` 和 `wx.downloadFile` 也是可以的。
