### ISSUE TITLE
真机上，page页面 拿不到onLaunch请求成功设置在globalData的数据

### ISSUE THREAD

**Issue by JunYanchan** [Tencent/wepy#773]
我在app onLaunch 里面执行了异步函数 返回的数据  设置在globalData里面 但是到了 index onLoad里面 this.$parent.globalData  发现数据 拿不到

**Comment by jayconscious** [comment]
+1

**Comment by zhw2590582** [comment]
会不会是因为globalData并不是像页面的data自动响应的，而index onLoad的时候异步还没执行完。

**Comment by JunYanchan** [comment]
是的 就是onload 的时候 异步还没执行完 那如何去处理这种情况呢

**Comment by zhw2590582** [comment]
我之前的做法是，在app写好异步函数和回调但不马上执行，然后在index的onLoad触发那个异步函数，在回调回来再做其他操作。

**Comment by xixiyang1216** [comment]
楼上的和cli初始案例那个getUserInfo方法执行是一样的，楼主可以去参考一下

**Comment by Gcaufy** [comment]
这个属于JS的知识了。
