### ISSUE TITLE
wxml 使用 变量的时候，canvas画图失败

### ISSUE THREAD

**Issue by NoraGithub** [Tencent/wepy#776]
# Description
1. 传变量给子组件失败
```
//father-page
...
<child :id.sync={{ch}}>
...
data = {
    ch: 3
  }
...
```
```
//child-component
{{id}}
...
```
2. 当在wxml使用变量作为标签时，canvas画图失败。

```
<template>
 ...
  <canvas canvas-id="{{id}}" />
...
</template>
<script>
...
const ctx = wx.createCanvasContext(this.id)
...
ctx.draw()
...
</script>
```
这里不使用变量，直接写死是没有问题的，但一使用变量就出错

# Environment
Platform: [开发者工具]
Platform version: [1.02.1801081]
wepy-cli version: [v1.6.0]
wepy version: [1.6.0]

代码demo地址在这里，恳请指教 https://github.com/NoraGithub/testwepybug

**Comment by NoraGithub** [comment]
@Gcaufy 可以判断下这个bug吗？ 已经提供了一个最简的 demo

**Comment by Gcaufy** [comment]
https://github.com/NoraGithub/testwepybug/pull/1

**Comment by NoraGithub** [comment]
@Gcaufy 问题 依然是存在的
1. `传变量给子组件失败``
![dingtalk20180117202349](https://user-images.githubusercontent.com/7700016/35042616-5e702bca-fbc4-11e7-8e8a-ebc3b7dc9be4.png)
父组件传递了id=3到子组件，子组件始终为默认id=1
如果不设置默认id，{{id}}将为空
2. `当在wxml使用变量作为标签时，canvas画图失败`
以下是我本地看到结果。希望能review下。
![dingtalk20180117200440](https://user-images.githubusercontent.com/7700016/35042027-e911b738-fbc1-11e7-927a-697e7ee13144.png)
![dingtalk20180117200512](https://user-images.githubusercontent.com/7700016/35042029-eb947554-fbc1-11e7-8c30-561d600e0430.png)

**Comment by Gcaufy** [comment]
```
   export default class CV extends wepy.component {
      data ={
 -      id: 1
      }
      props = {
        id: {
 -        type: String,
 +        type: [String, Number],
          twoWay: false
        }
      }
```

**Comment by NoraGithub** [comment]
@Gcaufy 问题2还是存在的
```
<template>
 ...
  <canvas canvas-id="{{id}}" />
...
</template>
<script>
...
const ctx = wx.createCanvasContext(this.id)
...
ctx.draw()
...
</script>
```
1. 当使用变量时

![dingtalk20180117204522](https://user-images.githubusercontent.com/7700016/35043729-a12bf8a0-fbc8-11e7-8b17-cd88be03e5b0.png)
![dingtalk20180117204509](https://user-images.githubusercontent.com/7700016/35043735-a63f47a2-fbc8-11e7-9386-051d598069ae.png)

2.  当直接写成  `<canvas canvas-id="3" />`时

![dingtalk20180117204559](https://user-images.githubusercontent.com/7700016/35043738-ad79e180-fbc8-11e7-8fd7-65ac19401707.png)
![default](https://user-images.githubusercontent.com/7700016/35043741-b33403bc-fbc8-11e7-98df-a44b03ceb195.png)


可见 appdata 和 wxml 都是（几乎）一样的，但是使用变量时并未正常画图
(PS: 如图，WXML实际是不一样的，但我不能解释为什么会导致这种情况)

**Comment by NoraGithub** [comment]
@Gcaufy 方便确认下这个问题吗:D

**Comment by Gcaufy** [comment]
在确认，有结果我再回复这里。

**Comment by NoraGithub** [comment]
@Gcaufy 请问有结果了吗？

**Comment by dlhandsome** [comment]
### 场景描述

#### 原生实现
- wxml
```html
  <canvas canvas-id="{{id}}" binderror="canvasError"></canvas>
```

- js

``` javascript
  Page({
      data: {
          id: 'canvas01'
      },
      //  canvas异常处理
      canvasError (e) {
          console.log(e.detail. errMsg)
      },
      onLoad () {
         const ctx = wx.createCanvasContext(this.data.id)
        // 绘制等等操作
     }
  })
```
canvas显示正常

#### wepy实现
``` javascript
    data = { 
         id: 'canvas01'
    }

    onLoad () {
         const ctx = wx.createCanvasContext(this.id)
        // 绘制等等操作
    }
```
显示不正常

### 分析
经wepy-cli编译后，是这样的：
![image](https://user-images.githubusercontent.com/16918885/35469676-534a0be0-0375-11e8-93cc-97e7c2dddfe1.png)
![image](https://user-images.githubusercontent.com/16918885/35469690-d2454892-0375-11e8-989c-7924eb8a448b.png)

$createPage创建出来的对象是没有data属性的，而是通过脏检查机制同步到视图，个人认为，应该是小程序原生的一个bug——通过setData方式改变canvas-id并不能实际改变视图中canvas的上下文

### 进一步验证
- 原生小程序

``` javascript
    Page({
      data: {
          id: 'canvas01',
          ctx: null
      },
      //  canvas异常处理
      canvasError (e) {
          console.log(e.detail. errMsg)
      },
      drawCanvas (id) {
           // 绘制canvas伪代码
           this.ctx = wx.createCanvasContext(id)
           this.ctx.drawImage(xxx)
           this.ctx.xxx()
           this.ctx.draw()
      },
      onLoad () {
         this.setData({
             id: 'canvas02'
         })
         console.log(this.data.id)   // canvas02
         this.drawCanvas(this.data.id)  // 此时无显示
         // this.drawCanvas('canvas01') 能够正常显示
     }
  })
```

**Comment by NoraGithub** [comment]
@Gcaufy 要上生产环境了，可以麻烦再确认下吗？

**Comment by Gcaufy** [comment]
@NoraGithub 已确认，暂时不会支持Canvas ID 为变量的场景，也没有计划支持这个问题。

**Comment by NoraGithub** [comment]
@Gcaufy  有替代方案吗？一个页面多幅图算是很正常的需求。这时候一般只能用变量吧？
