### ISSUE TITLE
如果实现filter的效果，例如时间搓转换

### ISSUE THREAD

**Issue by JunYanchan** [Tencent/wepy#777]
后端返回时间戳 我希望转为年月日 有没类似的 {{value | date}} 的方法？或者 该如何处理这种情况 较好 假如是一个数组中 每个对象都有时间戳的话。

**Comment by NoraGithub** [comment]
官方文档的 wxs 或者 script里定义一个函数然后，循环里使用都可以解决吧。

**Comment by Gcaufy** [comment]
wxs

**Comment by xixiyang1216** [comment]
请问解决了吗？方法定义在computed里还是直接写成私有方法。

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/issues/713
