### ISSUE TITLE
如果component, page存在空文件编译会停止

### ISSUE THREAD

**Issue by ColMugX** [Tencent/wepy#778]
这个位置：https://github.com/Tencent/wepy/blob/master/packages/wepy-cli/src/compile.js#L100

```js
 ['script', 'template', 'style'].forEach(t => {
                    if (wpy[t]) {
                        if (wpy[t].link === true) {
```

假设创建了一个空文件还没来得及初始化，并不存在这三个标签的情况下，编译会停止（提示找不到script）。

所以能不能做一个提示，或者空文件直接pass。我目前没找到哪里可以做提示。所以先提一个issue~

**Comment by zhw2590582** [comment]
这个bug之前有人提过，好像一直没修复

**Comment by Gcaufy** [comment]
> `F` 修复了源码目录里有空内容组件编译报错的问题。ISSUE #538
