### ISSUE TITLE
动态style报错，不支持 :style 

### ISSUE THREAD

**Issue by foooooouny** [Tencent/wepy#781]
```
在components 中给dom添加了 :style,然后报错 `near '.once'`，发现不支持动态的 style。

这个可以开放吗？毕竟有些style是需要js计算的。
```
<img width="567" alt="2018-01-16 8 44 13" src="https://user-images.githubusercontent.com/11987764/34989619-315b447e-fafe-11e7-98b3-529d1bf3afac.png">

![2018-01-16 8 44 32](https://user-images.githubusercontent.com/11987764/34989621-33fa553a-fafe-11e7-9743-691826bf68d9.png)

**Comment by jayconscious** [comment]
grammar error

**Comment by bulolo** [comment]
```
style="width: {{sysInfo.windowWidth*0.5}}px; height: {{sysInfo.windowWidth*0.5}}px;"
```

**Comment by foooooouny** [comment]
看了一个pr，可以支持 :class 了，所以就想是不是可以 :style，后面发现用法不同。。。 谢谢啦@bulolo
