### ISSUE TITLE
app config 单独引入 报错

### ISSUE THREAD

**Issue by kokiy** [Tencent/wepy#782]
![image](https://user-images.githubusercontent.com/15773714/34993729-44eea6da-fb0c-11e7-8dd3-7c8ebb1e4dcd.png)

**Comment by Gcaufy** [comment]
代码？

**Comment by Samlv9** [comment]
因为 wepy 用了正则表达式匹配 "config" 字段，所以你的 config 只能写在 js 文件里头并且需要左右大括号。比如：
```
const config = { pages: [] };
export default class myapp extends wepy.app {}
```
另外，config 的解析用了 new Function("config string") 的方式，因此 config 里面可以写一些函数，但是作用域的问题，里面不能用 `require`, `module` 等功能。比如：
```
const config = {
     pages: (() =>{ return ["pages/a", "pages/b"]; })()
}
```
但是我们可以另辟蹊径，结合 wepy.config.js 就能够做到动态生成 config 了。因为 new Function() 在 NodeJS 里头是可以访问到 global 对象的。
```
const config = {
     pages: (typeof global != "undefined" ? global.__PAGES__ || [] : [])
}
export default class myapp extends wepy.app {}
```

**wepy.config.js**
```
global.__PAGES__ = require("dynamicGetPages");
module.export = {
   /// wepy 配置。
}
```

**Comment by Gcaufy** [comment]
@Samlv9 厉害厉害。我都没想到还可以这么玩。

**Comment by Samlv9** [comment]
@Gcaufy 哈哈，我也是最近才接触小程序。还请多多指教～
