### ISSUE TITLE
wepy1.6.0配置ts

### ISSUE THREAD

**Issue by az114q** [Tencent/wepy#784]
在github上找到关于wepy-typescript的配置package.json包,但是添加依赖包及在wekpack.config.js文件中都按照wepy github上配置完成，无法使用。希望能给出一个简单的配置过程及小demo示例。是否使用方法像ng5+ts一样使用语法，以及ts的配置文件可以有智能提示

**Comment by hejinzhi** [comment]
同求  +1

**Comment by hanwenbo** [comment]
不支持
