### ISSUE TITLE
wx.draw 的回调无法触发

### ISSUE THREAD

**Issue by insub** [Tencent/wepy#786]
小程序 canvas 的 wx.draw 绘制函数有回调函数了，但是：

```
drawSome () {
      var ctx = wx.createCanvasContext('cardcanvas')
      ctx.setFillStyle("#ffffff")
      ctx.fillRect(0, 0, 690, 830)
      ctx.draw(true, function (e) {
        console.log('draw callback')
      })
 }
onLoad () {
   this.drawSome()
}
```
这样的话是不能触发 draw 回调的，但是如果调第二次，那么就可以触发了
不知道这个算不算 bug ?

**Comment by zhongyf** [comment]
我也遇到这个问题，但是目前已经解决。

let ctx = wx.createCanvasContext('canvas', this)

参数里多加this

详情：https://juejin.im/post/5af900185188254270641305
