### ISSUE TITLE
通过alias 配置的次级目录获取的组件无法生效

### ISSUE THREAD

**Issue by foooooouny** [Tencent/wepy#789]
### alias 配置：
<img width="498" alt="2018-01-18 2 16 47" src="https://user-images.githubusercontent.com/11987764/35083597-e46122fc-fc5a-11e7-8cdf-80e82b7bf75b.png">

### page/detail 页面：
`import 组件`
<img width="416" alt="2018-01-18 2 29 04" src="https://user-images.githubusercontent.com/11987764/35083846-0981cf5e-fc5c-11e7-9372-4a285fb14c4f.png">

`onLoad 打印`：
<img width="245" alt="2018-01-18 2 17 45" src="https://user-images.githubusercontent.com/11987764/35083669-3bf25f18-fc5b-11e7-84ad-bcaa071c3b6a.png">
`控制台输出结果`：
![2018-01-18 2 19 07](https://user-images.githubusercontent.com/11987764/35083700-4c34be02-fc5b-11e7-8c57-5c7ae241d8a4.png)

`项目打印报错`：
<img width="409" alt="2018-01-18 2 19 39" src="https://user-images.githubusercontent.com/11987764/35083742-93110b64-fc5b-11e7-84bd-3e2eb4e5aaef.png">

> 如图，alias配置了 c_weui 目录,然后在应用的时候，通过该路径获取的组件，在onLoad 中打印是存在的，但是引用在 components 中,就会显示找不到该组件，无法应用。
如果直接从根目录导入 eg：'@/components/c_weui/loading/loadmore' 就是可用的。
这个是什么原因导致的？

**Comment by Gcaufy** [comment]
版本是？
试试 aplha4 版本？
```
npm i wepy@1.6.1-alpha4 --save
```

**Comment by foooooouny** [comment]
```sh
npm ERR! code ETARGET
npm ERR! notarget No matching version found for wepy@1.6.1-alpha4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
不存在这个版本

`npm: v5.6.0 `

我的项目目前用的是 `wepy: v1.6.0`

**Comment by Gcaufy** [comment]
sorry 
```
npm i wepy-cli@1.6.1-alpha4 --save
```

**Comment by foooooouny** [comment]
wepy-cli ...
需要重新构建项目吗？

**Comment by Gcaufy** [comment]
重新build一下就可以了

**Comment by foooooouny** [comment]
还是不行

**Comment by Gcaufy** [comment]
new 出来的 demo 能编译通过吗？

**Comment by foooooouny** [comment]
正常build，和之前一样

**Comment by foooooouny** [comment]
使用 wepy-cli@1.6.1-alpha4 版本 new 出来的demo，也是找不到组件

**Comment by dddragon86** [comment]
这可能是个环境相关bug，我也遇到了而且只发生在mac os with wepy 1.6.0环境中，windows中没有这个问题。当你准备引用一个组件配到components中时，在头部使用自定义alias引入的组件会找不到，必须使用相对路径，例如:
`import LoadMore from '../../components/c_weui/loading/loadingmore'`
或者使用变相的方法解决相对路径问题:
`import LoadMore from '@/components/c_weui/loading/loadingmore'`
希望作者能看看是否和mac os相关

**Comment by Gcaufy** [comment]
提供一个能够复现的包吧，我这里并不能复现

**Comment by APPLLEJN** [comment]
我也碰到了这个问题，请问是怎么解决的

**Comment by chengpan168** [comment]
import wepy from 'wepy'
  import LoadMore from '../components/loadMore'
  import logger from '../mixins/logger'


不要带后缀，正常引入了

**Comment by wangrui97** [comment]
我也遇到了同样的问题。升级下wepy版本，1.6.1->1.7.3解决了我的问题。
