### ISSUE TITLE
eslint.execteAutofix invalid

### ISSUE THREAD

**Issue by yangbin1994** [Tencent/wepy#795]
IDE：vscode 
vscode 插件： eslint , vue

关联了 wpy 文件到 vue

用户配置
```json
{
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "vue",
    ],
}
```

**Comment by cccRaim** [comment]
+1

**Comment by yangbin1994** [comment]
auto fix 是我作为命令格式化工具来进行文件保存前的格式化用的，现在就很尴尬。
很想知道为什么会出现这种情况呢？

**Comment by Gcaufy** [comment]
@dolymood

**Comment by cccRaim** [comment]
@yangbin1994 我迁移项目也需要用到auto fix，现在的情况就是wepy只报错，没有auto fix确实影响进度

**Comment by cccRaim** [comment]
#818 相关问题

**Comment by aloneszjl** [comment]
@yangbin1994 这个是因为vscode 的规则覆盖了vetur的， 改一下vscode的规则就可以了，在vscode 设置那里加上 {
   "prettier.singleQuote": true,
   "prettier.semi": false,
   "vetur.format.defaultFormatter.html": "js-beautify-html",
   "vetur.format.defaultFormatterOptions": {
      "wrap_attributes": "force-aligned"
    }
} 就可以解决 单引号的报错和分号报错的问题，我是设置在工作区设置那里的，这样对其他项目就没影响了

**Comment by liudonghua123** [comment]
@aloneszjl 使用这种方式是相当于 prettier、vetur格式化代码的时候去掉分号、使用单引号等，不是使用eslintrc.js的配置autoFix的
