### ISSUE TITLE
switchTab before pages are registered 

### ISSUE THREAD

**Issue by JunYanchan** [Tencent/wepy#796]
我在app Show 的方法 里面 调用了 switchTab 到某个页面  就报这个错 有什么解决方法吗？还是有页面注册完 什么回调函数之类的

**Comment by Gcaufy** [comment]
page 的 onLoad方法 ？

**Comment by JunYanchan** [comment]
@Gcaufy 就是我默认小程序进入init 页面的 然后在app Show 方法里 将这个页面重定向去 index页面 但这个index页面是  tab页面 所以等于 这个index页面还没初始化 我就跳过去了 就报错了  这样的情况如何处理呢？

**Comment by aaaca20120** [comment]
重启工具就行了
