### ISSUE TITLE
多次repeat问题，第二个repeat里面拿不到值

### ISSUE THREAD

**Issue by Stevenjordison** [Tencent/wepy#802]
页面结构是
-- repeat
---- panel
------ title
------ repeat
-------- item

但是第二个repeat拿不到值，
但是换种方式就可以

-- panel
---- repeat
------ title
------ repeat
-------- item

具体代码是这样的。

![image](https://user-images.githubusercontent.com/18067543/35138959-f33b353e-fd2b-11e7-98f3-30d244514f06.png)

![image](https://user-images.githubusercontent.com/18067543/35138972-00eb8080-fd2c-11e7-844a-983a2a41d0be.png)

**Comment by Niofh** [comment]
这是什么问题 能解决吗？？？
