### ISSUE TITLE
resolve.alias如何对less文件生效？

### ISSUE THREAD

**Issue by etflly** [Tencent/wepy#803]
有两个场景：
1. 在less中import其他文件
2. 在style标签中绑定src

目前都无法正常解析alias

**Comment by Gcaufy** [comment]
目前不会支持

**Comment by etflly** [comment]
@Gcaufy 谢谢这么快回复。那有没有hack的方法或者best practice建议？

**Comment by Gcaufy** [comment]
可以用replace插件去hack

**Comment by etflly** [comment]
@Gcaufy 感谢。我了解下怎么用

**Comment by Gcaufy** [comment]
@etflly 按照这个commit修改一下代码尝试一下？现在只处理了 style,script,template 的src。但是还是不支持 less 中的import

**Comment by Gcaufy** [comment]
@dlhandsome

**Comment by etflly** [comment]
@Gcaufy 抱歉回复晚了，我怎么操作可以做这个验证？尝试修改了node_modules的代码，wepy build的时候回自动恢复

**Comment by XieShangxu** [comment]
测试下来好像template里面的src还是不支持alias

**Comment by Gcaufy** [comment]
@etflly 安装alpha版本应该就可以验证了。

**Comment by Gcaufy** [comment]
@XieShangxu 
是指 <template src=“xxx" 
还是指里面的 <image src="xxx" 呢？

**Comment by XieShangxu** [comment]
@Gcaufy <image src="xxx"

**Comment by Gcaufy** [comment]
对less import 的alias 已经支持到，对image src暂不支持。
