### ISSUE TITLE
组件内获取节点wx.createSelectorQuery()没反应

### ISSUE THREAD

**Issue by callmesoul** [Tencent/wepy#804]
```
var query =wx.createSelectorQuery().in(this);
      query.selectAll('.opera-item').boundingClientRect((rects)=>{
      }).exec()
```
根据官方文档加.in(this)，但是发现根本进去啊。什么问题？

**Comment by Gcaufy** [comment]
要了解一下this是什么 
wepy中的this. 是 wepy 的实例。和小程序不一样

**Comment by callmesoul** [comment]
我看官方文档in(component);

在wepy，this就是当前组件或页面吧。
是不是wx里的component和wepy的component不一样啊？

**Comment by Gcaufy** [comment]
完全不一样。 wepy的component是静态编译注入的。。看dist的内容就能明白了。

**Comment by callmesoul** [comment]
拿想问下这里应该怎么写啊？

**Comment by brucx** [comment]
直接 var query = wx.createSelectorQuery() 就可以了，Wepy的Component和原生的Component是两个概念，小程序文档里面涉及的Component概念在Wepy里面不适用。

**Comment by Guuuxu** [comment]
###  wepy2:
    var query = wx.createSelectorQuery();
    query.select('.wrap').boundingClientRect();
    query.exec(function (rect) {
        console.log(rect)
    });
同样的方法为什么在组件返回的是null，page中是有数据的

**Comment by guopeng27** [comment]
wx.createSelectorQuery().in(this.$wx).select('#xxx')
