### ISSUE TITLE
选型问题，麻烦解答

### ISSUE THREAD

**Issue by vipzhicheng** [Tencent/wepy#813]
你好，关于小程序的开发选型到底是用原生还是第三方，公司里面意见不统一，或者一面倒的倾向于用原生，我还想努力一下，这里我想问几个问题，麻烦帮我解答一下，也许其他人也关心我问的这几个问题。

1. wepy目前是放置在Tencent这个命名空间下，那请问wepy和Tencent是什么关系呢，这个项目能算是腾讯或者微信官方支持的项目么，这背后有什么故事？

2. 我公司同事担心微信小程序原生API变化速度很快，会导致可能开源项目不能很快跟上的问题，我想知道是否会出现这样的问题？

3. 听说小程序也支持了模块化的特性，我想知道wepy和小程序的模块化对比哪个更有优势。

4. 看文档说1.4.1开始默认不建议使用async/await了，因为会引起IOS某版本崩溃，这个崩溃是死机，死微信，还是死小程序呢？我看目前已经默认安装时又开始了，是问题已被修复了么？

5. 我看项目的Issues列表作者已经解决了相当多的问题，但是还有100多个问题，有的是不规范提问，我觉得需要有专人及时处理，留下的都是有价值的Issues，因为Issues的数量也是我们选型的一个参考指标。

**Comment by Gcaufy** [comment]
1. 由腾讯人开发维护，被腾讯开源组认可迁入腾讯源，暂时与微信小程序官方并不大太关联。属于比较独立的开源项目。
2. API的变化不会导致框架不可用，影响正常使用的功能会在第一时间升级，其它小的功能点也会在很快的时间支持到。
3. WePY在2016年11月开始支持组件化，但由于原和珠限制，实现机制是静态编译，在循环组件的时候会存在一些限制，原生小程序在2017年11月开始支持组件化，这才是真正的组件化。因为WePY考虑在2月份启动2.x版本基于原生组件化去优化。因此相对于1.x版本来说，原生组件化目前来说更有优势。
4. 我们自己团队也上线了一些个小程序，暂未发现还有类似问题存在。
5. 同意，同时也更希望有更多的人加入一起把项目做得更好。


最后，使用任何开源项目有风险，即便是Vue, React，最好是自己能有定位解决问题的能力，这样才能在碰到坑的时候才能最快的绕过。当然，这也是自我学习的一个过程。另外，在一些开发者的反馈当中我发现在一些问题，反馈比较好的开发者大多数是从原生迁到WePY的，直接上手WePY的反馈可能没有那么好。我的猜想是，从Web转向WePY时，开发者会拿Vue, React之类的来对比，因此会更多的看到的是WePY的不足，而原生切WePY的开发者更多的看到的是WePY的优势。

综上所述，顾虑相对比较多的情况下还是以原生为主吧，在有精力的时候可以去尝试一下WePY，看看有什么不同。
