### ISSUE TITLE
请问如何配置wepy.config.js才能修改dist下npm的生成目录

### ISSUE THREAD

**Issue by NTmemoir** [Tencent/wepy#815]

**Comment by Gcaufy** [comment]
为何有这样的需求？

**Comment by NTmemoir** [comment]
我就是想做成一个脚手架，譬如我在src下面新建了很多项目（项目1，项目2），目前我只想开发项目1，我进入到项目1文件下面，执行wepy build --watch ，那dist下面npm生成的目录不是我想要的
