### ISSUE TITLE
能否新增px转rpx的功能？

### ISSUE THREAD

**Issue by js5323** [Tencent/wepy#817]
关于css这块，能否新增px转rpx的plugins？？或者能新增自定义plugin的方式能力

**Comment by Gcaufy** [comment]
这个目前来说可以用replace插件 来实现

**Comment by taichenglu** [comment]
有个 bug，用 replace 只会替换第一个搜到的字符，比如 `height:70px;line-height:70px;`  只会把第一个 px 转换掉 `height:70rpx;line-height:70px; `配置代码如下 

`
replace: {
  filter: /\.wxss$/,
  config: {
    find: 'px',
    replace: 'rpx'
  }
}
`

**Comment by Gcaufy** [comment]
@taichenglu 
使用正则
```
replace: { filter: /\.wxss$/, config: { find: /px/ig, replace: 'rpx' } }
```

**Comment by taichenglu** [comment]
@Gcaufy 可以了，谢谢 👍

**Comment by panhezeng** [comment]
请问怎么配置replace插件？wepy.config.js 怎么配置，还需要nom install哪个吗？

**Comment by panhezeng** [comment]
上面的有问题，如果class name里面有px，或者图片名叫px都是误换，而且也不支持wxml，不过多谢@Gcaufy 提供的思路，我写了个完整的，如果有bug，请指教。
```
module.exports.plugins = {
  replace: [
    {
      filter: /moment\.js$/,
      config: {
        find: /([\w\[\]a-d\.]+)\s*instanceof Function/g,
        replace: function (matchs, word) {
          return ' typeof ' + word + ' ===\'function\' '
        },
      },
    },
    {
      filter: /\.wxss$/, config: {
        find: /:.*\d(px|rpx).*;(\s*\/\*no\*\/)?/ig, replace: function (matchs, $1, $2) {
          if ($2) {
            return matchs.replace($2, '')
          } else {
            return matchs.replace(/r?px/ig, 'rpx')
          }
        },
      },
    },
    {
      filter: /\.wxml$/, config: {
        find: /style=".*\dr?px.*"/ig, replace: function (matchs, $1) {
          return matchs.replace(/r?px/ig, 'rpx')
        },
      },
    },
  ],
}
```

**Comment by yugasun** [comment]
@taichenglu 可以尝试这个 `webpack` 工具 [px2rpx-loader](https://github.com/aOrz/px2rpx-loader)

**Comment by taichenglu** [comment]
@panhezeng @Gcaufy  我后来想，只要匹配 `[数字]px` 转成 `[数字]rpx` 就可以了

```
replace: {
  filter: /\.wxss$/,
  config: {
    find: /[0-9]px/ig,
    replace: function (matchs) {
      return `${matchs.slice(0, 1)}rpx`
    }
  }
}
```

**Comment by panhezeng** [comment]
@taichenglu 你这样除非能保证，css的background的url字符串,animation字符串,className字符串里面，不会出现类似这样的字符串 background: url("http://100px.jpg"),animation-name: toLeft100px;  .width100px {}，当前如果你在团队里面强制约定也可以，但是。。。

**Comment by Choicelin** [comment]
``` scss
@function rpx($px) {
   @return $px + 'rpx';
}
```

**Comment by taichenglu** [comment]
@panhezeng 取这样的类名和文件名，那一定是找喷的节奏

**Comment by WangLeto** [comment]
我来挖坟补充一点：`wepy.config.js` 里面有两部分 `module.exports`，配置 replace 不起作用的同学请检查一下是不是写错地方了（比如我）。

**Comment by 531431988** [comment]
为什么WEPY里面的style里手动设置的rpx给转成了px？

**Comment by rzp1** [comment]
wepy 2.0 怎么使用插件呢
![image](https://user-images.githubusercontent.com/43344910/69055806-9ceeaf80-0a49-11ea-935f-5fa8a1f207f6.png)
![image](https://user-images.githubusercontent.com/43344910/69055815-a2e49080-0a49-11ea-9757-bfc960b44e54.png)

**Comment by rzp1** [comment]
@Gcaufy 麻烦帮忙看下

**Comment by guojingwen** [comment]
2.0的项目不能用
