### ISSUE TITLE
./node_modules/.bin/eslint src 不会检查wpy文件

### ISSUE THREAD

**Issue by klouskingsley** [Tencent/wepy#818]
## Environment
  * wepy-cli version: [wepy-cli -v] v1.6.0
  * wepy version: [在package.json里] v1.6.0
  
## Reproduce

在src文件夹下任意的wpy文件中，定义一个变量a但不使用

### Observed Results

没有错误提示
  
### Expected Results

提示 `error  'a' is defined but never used            no-unused-vars`

**Comment by lydiafork** [comment]
./node_modules/.bin/eslint --ext .js,.wpy ./src
这样就可以检测wpy下的文件了

**Comment by yaowen2011** [comment]
> ./node_modules/.bin/eslint --ext .js,.wpy ./src
> 这样就可以检测wpy文件了

./node_modules/.bin/eslint --ext .js,.wpy ./src/pages/index.wpy --fix  加个--fix 空格等小问题自动修复掉了

**Comment by liqiuhui** [comment]
> ./node_modules/.bin/eslint --ext .js,.wpy ./src
> 这样就可以检测wpy文件了

我目前需要通过eslint检测单个.wpy文件，而不是项目中的所有.wpy文件。请问能提供一些建议吗？非常感谢！
