### ISSUE TITLE
使用wepy创建了一个示例项目，然后打开报错 --> Setting data field "$group$index" to undefined is invalid.

### ISSUE THREAD

**Issue by NoahSun** [Tencent/wepy#819]
## Description
今天看到wepy，然后根据文档配置了一顿，编译以后发现一个问题，不知道怎么回事，求解答
![image](https://user-images.githubusercontent.com/12728157/35216951-69bb9026-ffa4-11e7-9583-3ebb36737892.png)

## Environment

  * Platform: 开发者工具
  * Platform version: v1.02.1801081
  * Wechat version: 
  * wepy-cli version: v1.6.0
  * wepy version: ^1.6.0
  * other version:

**Comment by wyh888** [comment]
index.wpy 的 67 行，index 后面多了个字母 a，去掉就好了

**Comment by NoahSun** [comment]
@wyh888 好吧，谢谢。刚想说基础库调到1.7.3以上就会出现呢。

**Comment by Gcaufy** [comment]
这里有两个问题，分别对应我的两个commit
1. template 中 group.wpy 中的 props 是 index, 但是index.wpy中传入的props 是 indexa，这样就导致了 index 为undefined, 所以把indexa 改为 index 可以解决问题。
2. 1.9.0的版本的基础库中， setData 修改为不允许设置undefined数据，因此，在使用其它版本不会报错而这个版本报错了。

**Ref**
1.7.4
![image](https://user-images.githubusercontent.com/2182004/35265912-81cb6f8e-005c-11e8-9aca-fa0710d89da5.png)

1.9.0
![image](https://user-images.githubusercontent.com/2182004/35265917-86bcebc6-005c-11e8-92f2-70f72d7040ec.png)

**Comment by NoahSun** [comment]
@Gcaufy 好的，谢谢

**Comment by aalenliang** [comment]
求 wpy-cli 发个新版本

**Comment by Gcaufy** [comment]
@aalenliang 
```
npm install wepy-cli@1.6.1-alpha7 -g
```
