### ISSUE TITLE
mixins 定义 onShareAppMessage 无效

### ISSUE THREAD

**Issue by mylesshie** [Tencent/wepy#824]
------------------------
## Description

  [问题描述：mixin中定义了onShareAppMessage，但是在调用页面并没有触发到mixin中定义的onShareAppMessage事件]
  [Description of the issue]

## Environment
本地环境，直接使用wepy new project生成的demo代码

## Reproduce

  [如何重现问题]
  
minxis/test.js
![image](https://user-images.githubusercontent.com/4142212/35261738-978dd272-004c-11e8-83aa-f3bce33013c4.png)

index.wpy
![image](https://user-images.githubusercontent.com/4142212/35261752-a34c165a-004c-11e8-87b2-f996622e7d17.png)

### Observed Results

  [实际表现]
![image](https://user-images.githubusercontent.com/4142212/35261778-bc8df6ba-004c-11e8-8852-74e36d70a6c4.png)
  
### Expected Results

  [期望表现]
  控制台打印mixins/text.js中onShareAppMessage的信息
testMixin--share
  
## Relevant Code / Logs

请问为何？

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/blob/master/packages/wepy/src/mixin.js#L27

在一开始的设计中，mixin就不支持on事件。。
建议使用类的继承去实现
```
export MyPage extends wepy.page {}

export Index extends MyPage {}
```
