### ISSUE TITLE
初始化项目的时候报错，wepy版本1.6.0

### ISSUE THREAD

**Issue by pillosZ** [Tencent/wepy#826]
找不到组件：wepy-com-toast

**Comment by dyygtfx** [comment]
看下 package.json 里面有没有安装到 wepy-com-toast ，没有就自己手动安装一下

**Comment by Gcaufy** [comment]
应该是安装过程失败了，看一下conosle的日志，重新初始化一下或者手动安装一下

**Comment by pillosZ** [comment]
我是全局安装的wepy-cli ， 可是初始化一个新项目的时候会报 找不到组件：wepy-com-toast 这个错，但是还是会初始化成功，但执行wepy build编辑的时候又出现这个错误，并且项目无法运行起来！

**Comment by chenycu** [comment]
windows下 同样报这个错误，求解决
D:\MyProject\WeixinProject\my-project>wepy build
[21:05:25] [信息] 检测到wepy版本不符合要求，正在尝试更新，请稍等。
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN my-project@0.0.2 No repository field.

+ wepy@1.7.2
added 1 package in 1.583s
[21:05:28] [完成] 已完成更新，重新启动编译。
[21:05:28] [编译] 入口: src\app.wpy
[WARNING] 未安装wepy-eslint，执行npm install wepy-eslint --save-dev 或者在wepy.config.js中关闭eslint选项
[21:05:28] [写入] JSON: dist\app.json
[WARNING] 找不到编译器：wepy-compiler-less。
[Error] 未发现相关 less 编译器配置，请检查wepy.config.js文件。

**Comment by agoodcoolman** [comment]
npm install 试试
