### ISSUE TITLE
请问如何设置一个环境常量？ process.ENV is not defined

### ISSUE THREAD

**Issue by insub** [Tencent/wepy#835]
我看了这两个 issue:
https://github.com/Tencent/wepy/issues/231
https://github.com/Tencent/wepy/issues/223

但还是不太能理解，例如我现在有一个HOST参数，希望在 npm run build 的编译出来的版本取值是 abc.com ，但在 wepy build --watch 的时候取值是 localhost ，具体应该如何做呢？我在 wepy.config.js 里面根据 env 去设置的话，在 wpy 文件里取不到值

如果我自己写一个 setting.js ，在里面定义的话，又无法取得环境的值： process.ENV is not defined

**Comment by milkmeowo** [comment]
可以参考[这个](https://github.com/Tencent/wepy/issues/196#issuecomment-331127465)

1. `npm i -D babel-plugin-transform-node-env-inline`
2. 在[ `wepy.config.js`](https://github.com/Tencent/wepy/blob/master/packages/wepy-cli/templates/template/wepy.config.js#L42) 的 `babel` 配置中的 `plugins` 数组中加入 `'transform-node-env-inline'`

```
...

  babel: {
      sourceMap: !isProd,
      presets: [
        'env'
      ],
      plugins: [
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions',
        'transform-node-env-inline' // <--注意这行
      ]
    }

...
```
3. 在你的代码中 
```
// 判定现在的环境
const env = process.env.NODE_ENV === 'production' ? 'prod' : 'dev'

// development or production host
const hosts = {
  dev: 'https://dev.com',
  prod: 'https://prod.com'
}

module.exports = {
  env,
  host: hosts[env],
}
```

**Comment by insub** [comment]
@milkmeowo 谢谢！

**Comment by ZhaZhengRefn** [comment]
楼上的插件好像只支持process.env.NODE_ENV这个表达式。刚自己写了一份babel插件，可以配置多个全局常量，应该会方便点

1. npm i babel-plugin-global-define --save-dev //安装
2. 在wepy.config.js中配置
`    babel: {
      sourceMap: true,
      presets: [
        'env'
      ],
      plugins: [
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions',
        'transform-node-env-inline',
        ['global-define', {
          __ENV__: process.env.NODE_ENV,
          __VERSION__:  "1.0.2",
          __TITLE__: "global-define"
        }]
      ]
    }`
3.使用方法同

**Comment by Gcaufy** [comment]
很棒！
不过使用replace也能达到同样的效果。

```
module.exports.plugins = {
    'replace': [{
        filter: /*\.js$/,
        config: {
            find: /__ENV__/g,
            replace: process.env.NODE_ENV
        }
    }, {
        filter: /*\.js$/,
        config: [{
            find: /__VERSION__/g,
            replace: '1.0.2'
        },{
            find: /__TITLE__/g,
            replace: 'global-define'
        }]
    }]
};
```
