### ISSUE TITLE
可以 release 新版的 wepy-ant 吗？

### ISSUE THREAD

**Issue by jschyz** [Tencent/wepy#838]
## Description

  现在 wepy 核心代码版本为1.6.0 了，比如能在里微信小程序开发使用 watch 特性，在支付宝小程序 wepy-ant 里则 watch 脏检查失效。
  将 wepy-ant 里 component.js 替换成 wepy component.js，功能正常！

  希望能尽快 release 出 wepy-ant@1.6.0 版本😀😀

**Comment by Gcaufy** [comment]
因为我的业务重心不在支付宝小程序上，所以很难兼顾到小程序这边的更新改动，
所以还是希望有第三方支付宝小程序开发者能够将最新的wepy更新给同步到wepy-ant上去。理论上就是做一个compare然后copy过去测试 一下就差不多了。
