### ISSUE TITLE
关于1.6.1引入wxs问题

### ISSUE THREAD

**Issue by richie523** [Tencent/wepy#841]
我更新了wepy-cli最新版1.6.1，wepy版本是1.6.0
import MathFr from '../filter/mathFr.wxs'引入会报错，"module "filter/mathFr.wxs.js" is not defined"
不知道是不是要单独做什么配置

**Comment by richie523** [comment]
更新了wepy-cli@1.6.1-alpha7，一样的问题

**Comment by Gcaufy** [comment]
#713
