### ISSUE TITLE
两级页面为同一路由时，后者数据覆盖前者，切会被删除路由 （和被close的issue不同）

### ISSUE THREAD

**Issue by JourneyL** [Tencent/wepy#842]
例如 page1 -> page2 ->page1 相继navigateTo 然后back回page1 就会惊奇的发现所有涉及到data渲染都失效了

操作的过程中可以走微信开发工具的Appdata里清晰的看到 在page1第二次出现的时候 路由里并没有添加新的路由 而是覆盖了 然后在返回的时候page1的路由被删除了 所以返回到第一个page1的时候 操作任何data都不会进行任何渲染

搜索到了相关问题的issue 场景相同  但是他们可以换方案 我这里换方案的话就会很怪 
具体业务场景就是 商品详情->购物车->商品详情 

我们的版本是wpy 1.5.8 新建了个1.6的发现同样的问题还是存在 AppData里可以看到路由是被删掉的

**Comment by pws019** [comment]
@JourneyL  导向同一路由的问题，之前我也遇到过。会导致页面“死掉”。最后的解决方案是新建一个文件，吧代码复制过去，然后路由跳转到这个新文件对应的页面。不一定是WEPY的问题，感觉好像是小程序的问题。楼主可以自测下。

**Comment by JourneyL** [comment]
@pws019  这种方法的是可以 但是在我这个场景会非常繁琐 至于是谁的问题就不太清楚了 ，目前只能是杜绝二次访问了 详情->购物车访问详情是返回详情 刷新数据  。如果是wepy问题望解决

**Comment by Gcaufy** [comment]
建议提供测试代码方便复现。。。
并严格按照issue_template中的模板提问题，节省彼此的时间。
什么版本，什么原因，什么平台出现了什么问题。

**Comment by tony0511** [comment]
同一页面在不同的导航位置能不能保留道歉导航位置所在状态？

**Comment by tony0511** [comment]
同一页面在不同的导航位置能不能保留当前导航位置所在数据和页面状态？
