### ISSUE TITLE
怎么全局引入scss呢?

### ISSUE THREAD

**Issue by KingJeason** [Tencent/wepy#845]
我在scss下写了很多mixin,我目前是每个页面都引入,这样做有2个缺点,一是增加了很多css,二是,如果这个scss路径变了,那我岂不是要一个一个改...
我想请教大家的是如果全局引入这些mixin呢?

**Comment by KingJeason** [comment]
目前已知的vue是可以通过安装 sass-resources-loader然后进行配置.那么在wep应该怎么搞~~~
很急很急..

**Comment by kooriko** [comment]
现在没办法搞 sass-resources-loader 是 webpack 的 loader，同样的 DefinePlugin ProvidePlugin 也是没法用的……

**Comment by FreeRide-Joe** [comment]
@Gcaufy  你好，问下这个问题有什么 hack 的方法吗？
