### ISSUE TITLE
wepy文件中不能使用es6解构运算符

### ISSUE THREAD

**Issue by klouskingsley** [Tencent/wepy#846]
提交ISSUE前请确保已认真阅读以下内容

*Please read the following information carefully before you open an issue.*

在提交issue之前必须确认以下问题：

*Please make sure you understand the following points:*

* 必须是一个bug或者功能新增

* *It must be a bug or a feature request*

* 必须是WePY相关问题，原生小程序问题去[开发者论坛](https://developers.weixin.qq.com/)。

* *It must be a WePY issue.*

* 已经在issue中搜索过，并且没有找到相似的issue或者解决方案。

* *I searched issue already but I did't find any relevant issues or solutions.*

* 完善下面模板中的信息

* *Please filled out the following template*

阅读完后请在提交的issue中删除以上内容，包括分割线

DELETE THE INFORMATION ABOVE(INCLUDE THE SEPARATION LINE) BEFORE YOU OPEN AN ISSUE

------------------------
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  [Description of the issue]

  wepy文件中，使用[...obj, ...obj2]会报错，即使我安装了`babel-preset-es2015`和`babel-plugin-transform-object-rest-spread`并在wepy.config.js中配置了也无法使用

```js
// wepy.config.js babel部分
babel: {
      sourceMap: true,
      presets: [
        'env',
        'es2015',
        'stage-0'
      ],
      plugins: [
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions',
        'transform-object-rest-spread'
      ]
    }
```

```
[Error] SyntaxError: unknown: Unexpected token (82:7)
  80 |       var cmtList = []
  81 |       var userId = Mudu.User.GetUser().id
> 82 |       [...cmtArray, ...this.cmtList].map(v => {
     |        ^
  83 |         if (uniqueId.indexOf(v.id) < 0) {
  84 |           cmtList.push(v)
  85 |           uniqueId.push(v.id)
    at Parser.pp$5.raise (D:\workspace\mudu\wechat-live\node_modules\babylon\lib\index.js:4454:13)
```

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web] 
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v] v1.6.0
  * wepy version: [在package.json里] v1.6.0
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]

wepy文件中使用解构运算符
  
  [How to reproduce the issue]

### Observed Results

  [实际表现]
  
  [Observed Results]
  

如上述编译错误

### Expected Results

  [期望表现]
  
  [Expected Results]
  
编译无错误

## Relevant Code / Logs

  ```
  // TODO(you): code or logs ohere to reproduce the problem
  ```

**Comment by NoahSun** [comment]
hey, dude. definite 可以

**官方示例 --- index.wpy**
---
```javascript
data = {
  /*...*/
  groupList: [/*...*/],
  groupList2: [
      {
        id: 100,
        name: '点击改变',
        list: [
          {
            childid: '100.1',
            childname: '子项，点我改变'
          },
          {
            childid: '100.2',
            childname: '子项，点我改变'
          },
          {
            childid: '100.3',
            childname: '子项，点我改变'
          }
        ]
      }
    ]
}
/*...*/
onLoad() {
  /*...*/
  [...this.groupList, ...this.groupList2].map(group => console.log(group));
}
````
**结果**
---
```javascript
{id: 1, name: "点击改变", list: Array(3)}
{id: 2, name: "点击改变", list: Array(3)}
{id: 3, name: "点击改变", list: Array(1)}
{id: 100, name: "点击改变", list: Array(3)}
```

**Comment by NoahSun** [comment]
而且你还多加了一行 transform-object-rest-spread

**Comment by klouskingsley** [comment]
```js
var userId = Mudu.User.GetUser().id
[...cmtArray, ...this.cmtList].map(v => {
```

我刚有试了下，好像是因为这两行解析有点问题，我像下面这样加了个分号就好了

```js
var userId = Mudu.User.GetUser().id
;[...cmtArray, ...this.cmtList].map(v => {
```
