### ISSUE TITLE
view层不支持对循环中的列表项进行方法计算。

### ISSUE THREAD

**Issue by pws019** [Tencent/wepy#847]
[问题描述]

  在一个wx:for循环中，对每一项item，不支持wx:if="{{ calc(item)  }}"
  备注：calc是一个函数

  [期望表现]
  
  希望可以通过方法(function)对循环中的列表项进行计算。

**Comment by NoahSun** [comment]
我在[小程序开发者社区](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=1223975811&docid=000c4c29090460805726207555b400)提过，官方回答暂不可以，估计wepy也是不行的

**Comment by pws019** [comment]
@NoahSun 哦哦。这样。我以为wepy参考vue做的，vue做到了，wepy也可以的，就上来问问。。。
