### ISSUE TITLE
wepy怎么填写extjson

### ISSUE THREAD

**Issue by RenShine** [Tencent/wepy#849]
微信开放平台开发者如何填写extjson？
原版开发文档：https://mp.weixin.qq.com/debug/wxadoc/dev/devtools/ext.html

![image](https://user-images.githubusercontent.com/6385962/35429813-99d74a0c-02b0-11e8-8679-53023b9a02ab.png)

**Comment by coolhwm** [comment]
一样写，放在src目录下，会拷贝过去
