### ISSUE TITLE
包导入 有问题

### ISSUE THREAD

**Issue by leekangtaqi** [Tencent/wepy#852]
导入三方包
引入 发现 并没有 递归引入 需要的文件

引入：
===
![image](https://user-images.githubusercontent.com/5259489/35430324-bd5faa58-02b2-11e8-9c20-4efa301264ed.png)

nodule_modules有该文件
===
![image](https://user-images.githubusercontent.com/5259489/35430340-d12212f6-02b2-11e8-8945-c53047aa4bfb.png)

<b>但是dist文件夹下 npm中并没有我引入的文件</b>
===
![image](https://user-images.githubusercontent.com/5259489/35430350-da52519c-02b2-11e8-8b9f-c3e3a4dbff5e.png)

**Comment by shineSnow** [comment]
碰到同样的问题，官方快点解决呐

**Comment by KingDr** [comment]
一样的问题，目前是手动替换的。

**Comment by Gcaufy** [comment]
你们三个都是三样的问题吗？ 并不到找到那个库啊。
https://www.npmjs.com/search?q=pinyin-base
```
 $ npm info pinyin-base
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/pinyin-base
npm ERR! 404
npm ERR! 404  'pinyin-base' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gcaufy/.npm/_logs/2018-01-29T08_29_44_010Z-debug.log
```

**Comment by cuijiemmx** [comment]
@Gcaufy 也同样遇到类似的问题，虽然引入的包不同

@KingDr @shineSnow，一般node_modules/<package name>下有个dist目录，里面是编译的umd版本，可以复制到项目中使用，遇到第三方库的引入问题我采用这种work around方式，基本都能解决
