### ISSUE TITLE
wepy组件中使用wxs不执行

### ISSUE THREAD

**Issue by seveny** [Tencent/wepy#853]
原生小程序中可以使用wxs来实现类似vue中template中调用js方法，经尝试在wepy page中也可以使用，但是当page中引入组件，在组件中使用wxs的时候就无效了，查看了生成的wsxx文件发现，wepy在遇到有组件的时候生成的wsxx文件中会把组件中的变量都加上$,并在之前加上组件的名字，比如页面A中引入了组件B，并在import的时候名字叫questionList，组件B中使用wxs，这个时候生成的代码如下
![image](https://user-images.githubusercontent.com/953633/35445414-85d098f6-02ec-11e8-9945-86b16b2d60f7.png)
这样是不是意味着不可以在组件中使用wsx？

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/issues/713
