### ISSUE TITLE
包含alias符号的路径中如果带有点号，解析出错

### ISSUE THREAD

**Issue by heeroluo** [Tencent/wepy#857]
## Description

在代码中编写：
``` javascript
import ComponentA from '@/components/components-a/1.0/components-a';
```

控制台报错：
> [Error] 找不到组件：/Users/me/wxapp/demo/src/pages/index/@/components-a/1.0/components-a

「@」没有被解析。

## Environment

  * Platform: --
  * Platform version: --
  * Wechat version: --
  * wepy-cli version: 1.6.0
  * wepy version: 1.2.8

**Comment by Gcaufy** [comment]
我将new出来的demo修改为

```
import Panel2 from '@/components/1.0/panel' // alias example
```

测试没有问题的。。。

建议使用alpha 版本测试 一下。

```
npm i wepy-cli@1.6.1-alpha7 -g
```
