### ISSUE TITLE
mixin computed的bug

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#859]
/* mixin mymix.js/

// 很简单的一个mixin定义，只列出相关部分，一个test计算属性
```
...

computed = {
  test() {
    return true
  }
}

...
/* page MyPage.wpy */


<template>
<block wx:if={{test}}>
   hi man
</block
<template>

<script>
import mymix ...

export default class MyPage extends wepy.page {
  mixins = [mymix]
}
</script>
```

此时模板可以渲染成功输出hi man，page直接从mixin中获取了test()

现在做下改动: 在page中加入一个空的computed

```
...
mixins = [mymix]

computed = {
  // 一个没啥内容的computed，当然加入一个计算属性也不影响后面的结果
}

```
结果就是：此时无法渲染出hi man，也就是说test()并没有从mymix中拿到，感觉这个行为很奇怪，期望的结果是能渲染出hi man

**Comment by Gcaufy** [comment]
意思是让 mixins 也支持 computed?

**Comment by cuijiemmx** [comment]
@Gcaufy 当前的实现感觉不一致，要么在应用mixin的组件中完全无法访问mixin中的computed，要么可以使用的话不要因为应用mixin的组件中定义了新的computed而导致mixin中的computed无法访问

另外我觉得mixin支持computed是合理的需求，因为确实在实践中遇到了

**Comment by fjl716** [comment]
同意，为什么不支持呢？

**Comment by adsjkqhaoran** [comment]
我发现把wepy版本改为1.6.0 就没有这个问题了 蛋疼
