### ISSUE TITLE
编译压缩后$name被改变，导致代码中条件判读错误

### ISSUE THREAD

**Issue by xixiyang1216** [Tencent/wepy#864]
![wechatimg6480](https://user-images.githubusercontent.com/21260755/35501158-16404d18-0514-11e8-9d03-72115bc4b585.jpeg)

![wechatimg6481](https://user-images.githubusercontent.com/21260755/35501159-1676a886-0514-11e8-8d43-9fc8dc7b4226.jpeg)

![wechatimg6484](https://user-images.githubusercontent.com/21260755/35501160-16b6ac38-0514-11e8-9db1-ca372e288630.jpeg)

请问如何获取到上个页面的名字。如果用getCurrentPage，navigateBack过来的页面能正确获取到吗

**Comment by Gcaufy** [comment]
没太理解你的问题，

$name 的默认值是 className 吧，但是这个是不会压缩 的。

**Comment by xixiyang1216** [comment]
@Gcaufy npm run build后被压缩了如上图变成t了。问一下怎样可以获取到上一个页面绝对正确的不会被压缩的名称。
今天发现build后在onLoad里打印this。名称也会被替换

**Comment by Gcaufy** [comment]
我这边看到的没有被压缩过。。
或者你考虑在onLoad中给$name赋值一下？
