### ISSUE TITLE
wepy.component中 修改template界面的代码，界面不刷新

### ISSUE THREAD

**Issue by SnowFlowers** [Tencent/wepy#865]
# mac pro
# wepy 1.6.0
每次在page界面写界面都会刷新，但是每次在component中写界面不会微信开发工具不会刷新。每次都需要重新编译一遍才可以。很费时间

**Comment by Gcaufy** [comment]
这个问题理论上是不存在的，身边在用的人比较多，还没有碰到过这种情况。不清楚你这为什么你的代码没为被编译。。。
尝试其它代码也是这个结果么？

**Comment by leftjs** [comment]
通过 `wepy new` 出来的一个新的项目，我也遇到同样问题，
编辑components里面的wpy文件中的`<template>`，比如`counter.wpy`中我修改如下一行

![image](https://user-images.githubusercontent.com/8311633/35737166-958f6f50-0865-11e8-9951-4d48194d456b.png)

cmd + s 保存之后，触发watch重建，但是如图所示
![image](https://user-images.githubusercontent.com/8311633/35737024-1a254c36-0865-11e8-8b9f-fd0d7ed3073c.png)
只更新了`counter.js`,`counter.wxss`而`<template>`中的改动，理应是编译进`*.wxml`,在这里应该是`dist/pages/index.wxml`。
不知道是通病还是什么情况，如果是开发环境配置问题，望告知~

**Comment by Gcaufy** [comment]
@SnowFlowers 
抱歉，因为问题描述不够准确我没有正解理解你的意思，看到 @leftjs 的描述才明白是什么问题。
参见：https://github.com/Tencent/wepy/issues/903

可以先参考commit, 手动修改一下wepy-cli代码去解决这个问题。或者等下一个release.
