### ISSUE TITLE
毫秒级时间显示 性能问题

### ISSUE THREAD

**Issue by Onlylonger** [Tencent/wepy#866]
Q: 毫秒级显示时间，手机存在明显卡顿。

Code: 

```
export default class Demo extends wepy.component {
  data = {
    time: 10 * 1000
  }
  countDown() {
    if (this.time <= 0) {
      return
    }
    this.timer = setTimeout(() => {
      // view 上实时显示 time 的改变
      this.time -= 10
      this.$apply()
      this.countDown()
    }, 10)
  }
  onLoad() {
    this.countDown()
  }
}

```

Q: 请问有什么解决方案供参考吗？

**Comment by Gcaufy** [comment]
我在空项目中使用你的测试代码表现很流畅。。建议你测试一下。

可能原因是，你的page下的数据量太大。
在setDate({a: 1}) 的时候，并不是传输了{a:1} 这个数据，而是对page下的所有数据 进行json.stringify之后再进行传输的。所以在数据量大的情况下会有性能问题

**Comment by Onlylonger** [comment]
![image](https://user-images.githubusercontent.com/19505200/35546216-519d5a82-05ae-11e8-8bb8-53d824dfc51f.png)
@Gcaufy 实际上我这个组件中 data 数据挺多的，所以有可能是这种情况。
这种情况的话怎么优化好哦*_*？有没有办法只传输修改的 值，

**Comment by Gcaufy** [comment]
这里的数据不多，都是一些简单类型。。除了有一个gridAry， 不知道里面的内容有多少。。
另外，得看整个page下的数据有多少，而不是单个组件。

优化就是尽可能的减少绑定的数据。

**Comment by Onlylonger** [comment]
@Gcaufy 好的，谢谢.
