### ISSUE TITLE
wepyignore添加了之后watch卡住不动...

### ISSUE THREAD

**Issue by ziwenwen** [Tencent/wepy#868]
![75752dd535b9b3c471e6e1b74243dc5](https://user-images.githubusercontent.com/13036042/35516421-b6b72e2e-0546-11e8-8bf9-80cd11a0d74f.png)

wepyingore文件
node_modules
dist
.DB_store
*.wpy___jb_tmp___
*.wpy___jb_tmp___

**Comment by Gcaufy** [comment]
正常表象就是这样吧，这是watch编译完成的时候，再修改文件会继续触发编译。
