### ISSUE TITLE
如何写一个wepy插件呢，有没有文档？

### ISSUE THREAD

**Issue by fantasy525** [Tencent/wepy#874]
我看你们提供的插件中有个img2base64的，但是不太好用，作者也说了是跟他的项目耦合的，而且那个会把wxml中的图片转为base64,这不是增加了代码大小的么，我只想让css中的小图标转一下，所以需要写个插件，哪里有文档呢？

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/blob/master/packages/wepy-plugin-filemin/src/index.js

不出40行代码，按这个来写就行，很简单的，不需要什么文档。

**Comment by EdwardZZZ** [comment]
https://www.npmjs.com/package/wepy-plugin-parsecss

这个支持base64和自动前缀，不会有其它副作用
