### ISSUE TITLE
wxs 处理后结果 利用props传递给子组件

### ISSUE THREAD

**Issue by NoraGithub** [Tencent/wepy#875]
场景：
返回的文章内容里有url，需要从url里处理出来id传递给子组件。
问题：
`<son :id.sync="str.getID(url)"></son>`
無效。
最簡demo地址：https://github.com/NoraGithub/testwepybug2

**Comment by Gcaufy** [comment]
props中连复杂的数据类型都支持不了，你还想支持wxs.......
要知道wxs是运行在视图层的东西。 而props 是逻辑层的封装。。完全 不是一类东西。

**Comment by NoraGithub** [comment]
@Gcaufy 谢答复。
请问如果把<son :id.sync="url"></son> 传到子组件里，子组件再进行对应的getID提取是否可行？
我在 <repeat>里在样子做是失败的，始终获取的是第一个item值（之前有类似的[issue](https://github.com/Tencent/wepy/issues/323)提出过）。不知道是否同一个问题或者我使用方法出了问题？
如果用 wx:for 能解决吗？（如果只是repeat的问题）
demo地址：https://github.com/NoraGithub/testwepybug2

**Comment by NoraGithub** [comment]
当在wxml中以 `对象.属性` 传值时甚至无法获取props

https://github.com/NoraGithub/testwepybug2/tree/objectAsProps

请问有什么解决方案吗？

PS：`props中连复杂的数据类型都支持不了`这类信息作为一个使用者是无法得知的。
