### ISSUE TITLE
vuex or mobx?

### ISSUE THREAD

**Issue by zhangchen91** [Tencent/wepy#876]
## Description

https://github.com/Tencent/wepy/blob/d7bc02d16ea5d408c08b4a617500ce005cbdcf01/packages/wepy-redux/src/helpers/index.js#L1

既然最初是基于 vuex 来实现的 help，为何最后做成了类 redux? 为什么不优先考虑更接近 vuex 的 mobx? 或者直接参考 vuex 的原生语法糖，实现对广大开发者更友好更易迁移的状态管理工具?

相信应该有不少人会问类似的问题，没官方Q群 or 其它反馈渠道? PS：微信客服加不上

**Comment by yolo2013** [comment]
我作为wepy和redux的使用者来回答一下吧（vuex也用过）。
redux还是现在前端最主流的状态管理库，使用起来并不会有违和感。而且wepy和redux并没有强绑定关系，如果需要与vuex或者mobx配合使用，提个PR大家都会非常感激。

**Comment by zhangchen91** [comment]
同你所说，我也想有个vuex or mobx的轮子。但现在问题是这样，如何从已有的vue的web项目(如果我们是新项目直接用wepy写，我觉得redux没问题)，把逻辑尽量复用到小程序中。所以作为一个vue项目肯定少不了使用vuex，同理与对wepy的选择考量，也是因为考虑其类vue的特性(如果更类vue的mpVue开源了，或许会选择后者)。那么话题回到wepy-redux上来，明明看到最初的童鞋借鉴的是vuex，说明他跟我们跟大多数人的想法都是说，帮wepy做一个类vuex的状态管理工具。为何到最后官方提供的成品变成了redux版本？这个问题倒是让我忽然明白，几大状态管理工具因其都源自flux思想，在代码层面都能相通or相互借鉴(抄袭)。

**Comment by Gcaufy** [comment]
1. wepy 不是 vue， 只是在语法层面上比较像vue, Vue的web项目基本没有办法简单的迁移来wepy
2. vuex是为vue而生，与vue强耦合。但react相对比较独立，可以直接拿过来使用，这一点vuex做不到，除非写个wepy版本的vuex，成本比较高。
3. wepy的生态没有vue那么大，没有vue那么成熟，wepy需要状态管理的话已经有redux了，vuex的开发成本比较高，因此还是希望留给其它贡献者。自己把时间跟精力留在解决wepy的其它问题上。
