### ISSUE TITLE
bindtap 无法绑定超过21位的函数名，会导致编译出错

### ISSUE THREAD

**Issue by insub** [Tencent/wepy#879]
## Description

  [问题描述：在 template 元素上的 bindtap 超过21位的函数名，会导致编译出错
  [Description of the issue]

## Environment

  * Platform: [开发者工具]
  
## Reproduce
  当绑定一个超过21位的函数名时：
  <view class="reult_box" bindtap="showXxxxxxxCompleteTip()">
 开发者工具编译会报错：
 VM53323:2 ./pages/posts/show.wxml
 unexpected attribute name, near `data-wp...`
 
 把函数名改为21位以下就没问题了
<view class="reult_box" bindtap="showXxxxxxxCompleteTi()">

**Comment by Gcaufy** [comment]
这个应该是原生的限制吧，估计没有办法。
