### ISSUE TITLE
demo里面this.$parent.getUserInfo，把this.$parent改成wepy为啥不行呢？

### ISSUE THREAD

**Issue by azumia** [Tencent/wepy#882]
如题

**Comment by Gcaufy** [comment]
this.$parent 跟 wepy 有什么 关系 ？为啥不改成 windows

**Comment by azumia** [comment]
我打印出wepy，有getUserInfo这个方法，为啥不能用呢

**Comment by Gcaufy** [comment]
wepy.getUserInfo 是 wx.getUserInfo 的封装。

this.$parent.getUserInfo 只是我在 app.wpy 中定义的一个普通方法，只是方法名和那个一样而已。

**Comment by hanwenbo** [comment]
wepy. getUserInfo  为什么不返回内容呢？
