### ISSUE TITLE
$apply后，数据变更之后，repeat子组件，子组件下面无法拿到 props里的数据,求指点

### ISSUE THREAD

**Issue by skybluesky** [Tencent/wepy#883]
![image](https://user-images.githubusercontent.com/28983881/35620863-5ff3fd56-06bd-11e8-8be3-171ea6eedff6.png)

同样是这个组件，在别的页面，onLoad时更改数据，repeat后就能拿到props里的数据，
这个页面，onLoad之后用户触发的数据变更，repeat后拿不到props里的数据

**Comment by skybluesky** [comment]
已解决

**Comment by StephenCMZ** [comment]
请问如何解决的？

**Comment by Vultur** [comment]
子组件 onLoad 是没办法拿到 父组件异步数据的
