### ISSUE TITLE
如何修改page 根节点的css

### ISSUE THREAD

**Issue by wuzhuzhu** [Tencent/wepy#885]
## Description
在使用less布局的时候 希望可以让page height: 100%

## Environment
  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce
```
<template>
  <view class="wrapper">
...
  </view>
</template>

<style lang="less">
  .wrapper {
    height: 100%
}
</style>
```
### Observed Results

  [实际表现]
  
wrapper无法全屏幕
  
### Expected Results

  [期望表现]
  
page元素可以设定height: 100% 
 

## Relevant Code / Logs

  ```
  // TODO(you): code or logs ohere to reproduce the problem
  ```

**Comment by Gcaufy** [comment]
```
page 
  height: 100%;
.wrapper
  height: 100%;
```

**Comment by 531431988** [comment]
> ```
> page 
>   height: 100%;
> .wrapper
>   height: 100%;
> ```


自定义的弹出层筛选组件，打开筛选时，底层PAGE会滚动，WEPY里面怎么动态给PAGE添加CLASS 或 CSS
