### ISSUE TITLE
wepy.hideLoading报错

### ISSUE THREAD

**Issue by etflly** [Tencent/wepy#887]
不知道怎么上传报错截图，不过应该是很简单的错误，某处将`setTimeout`误写成了`setTimeoue`

复现方式
```
wepy.showLoading()
wepy.showToast()
wepy.hideLoading()
```

**Comment by Gcaufy** [comment]
复制图片，在这里粘帖就好了。。
wepy的代码中并没有使用过setTimeout之类的东西，这个你可以在wepy源代码中搜。

**Comment by etflly** [comment]
![image](https://user-images.githubusercontent.com/4463138/35670816-8d0a0f26-0774-11e8-8573-e95992709297.png)

按照主楼方式100%复现，而将wepy改为wx则无报错

**Comment by Gcaufy** [comment]
看看lib/app.js:198行的代码

**Comment by etflly** [comment]
似乎并没什么可疑代码……
![image](https://user-images.githubusercontent.com/4463138/35671714-3f94c47c-0777-11e8-8149-c0e26232c05c.png)

**Comment by harrydengchao** [comment]
我也有这个问题，全文搜了一下代码，没搜到

**Comment by harrydengchao** [comment]
已查到问题，在文件 WAService.js:5:6933 中搜到 setTimeoue。是微信开发工具的 代码BUG。 [-> 微信开发者社区关于setTimeoue的回复](https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=0000268f0c08c004592657f3d51800&highline=setTimeoue%20is%20not%20defined%3Bwx.hideLoading&token=&lang=zh_CN)

**Comment by etflly** [comment]
@harrydengchao 棒啊

以后提issue要带上基础库版本号了……
