### ISSUE TITLE
最新微信开发者工具（v1.02.1802010）不支持wepy编译的项目了？

### ISSUE THREAD

**Issue by maxcheers86** [Tencent/wepy#890]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  [Description of the issue]
最新微信开发者工具（v1.02.1802010）不支持wepy编译的项目了？原来的项目打开直接报错，新建一个空白项目也一样报错

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs ohere to reproduce the problem
  ```

**Comment by longlyboyhe** [comment]
如何解决的，同求
