### ISSUE TITLE
wepy-cli build bug

### ISSUE THREAD

**Issue by shengbeiniao** [Tencent/wepy#896]
![image](https://user-images.githubusercontent.com/3301995/35723405-1a429924-0835-11e8-8f78-0a7916c3b53a.png)

请修复wepy-cli/src/compile.js文件

```
#line 100
          ['script', 'template', 'style'].forEach(t => {
                    if (wpy[t]) {

改为
       if (wpy!==null&&wpy[t]) {

```

**Comment by shengbeiniao** [comment]
这个问题具有偶发性，一直没有修复

**Comment by Gcaufy** [comment]
版本？尝试安装最新的alpha版本看是否在存在这个问题，alpha版本中修复了一个空文件的UG。

这个问题不能简单的把wpy为null的排除掉，需要找到原因什么情况下 wpy为 null

**Comment by shengbeiniao** [comment]
有一个小伙伴把dist目录删除，重新执行命令的时候报这个错误

**Comment by Gcaufy** [comment]
刚测试并不能复现问题，删除dist理论上不会导致这个问题。。
另外，建议使用`npm run clean` 来代替 `rm -rf dist`
https://github.com/Tencent/wepy/blob/master/packages/wepy-cli/templates/template/package.json#L9
