### ISSUE TITLE
interceptor 以及小程序原生函数建议

### ISSUE THREAD

**Issue by malacca** [Tencent/wepy#897]
建议一：小程序原生函数添加 name 属性

比如我定义了一个函数

> function foo(method){
>     console.log(method.name)
> }

对于 wepy 新增函数是OK的，比如  foo(wepy.$has) 会正确返回  $has
但对于小程序原生的就不行了，比如 foo(wepy.login)， name 恒为空

建议二：interceptor 方法

比如：interceptor(method, filter)
目前的 filter

> filter = {
>     fail (p) {
>    }
> }

当两个不同 Method 使用同一个 filter, 在  filter 函数中无法感知当前拦截的接口
建议

> filter = {
>     fail (p, k) {
>         // k 可以返回 method 名称
>    }
> }

如果 filter 中可获取 method 名称，可否考虑支持全局注入，对于相似的拦截器，每个都写好费劲的

比如，直接
interceptor(filter)

**Comment by Gcaufy** [comment]
1. 原生小程序的问题请在开发者论坛提
2. wepy支持interceptor拦截器。

**Comment by malacca** [comment]
@Gcaufy 

我怎么觉得你误会我了我的问题呢

1、 wepy 对 wx 对象进行了封装， 并额外添加了一些方法

比如我有一个函数

```
function foo(method) {
  console.log(method.name)
   method.call()
}

foo(wepy.$has)
foo(wepy.login)
```

foo 函数中，如果是 wepy 自己添加的函数接口，可以正常获得 function name， 但对于 wepy 封装的 wx 的接口，获取不到，这跟原生小程序没关系


2、interceptor拦截器，我当然知道支持啊

我是希望拦截器回调，可以传递一个 key 参数。如果你们觉得合理，是否考虑添加一个全局 interceptor拦截器

```
filter = {
   success (p) {
          // do same thing
   }
    fail (p, k) {
         if (k === 'getUserInfo') {
               // do same thing
        } else {
              // do same thing
        }
    }
}

intercept('getUserInfo', filter)
intercept('getLocation', filter)

```


比如这样一给拦截器，两个函数拦截器只有些许不同，按目前的接口，我必须写两个 filter，因为 filter 函数回调的参数，只有 p， 没有 k。 我的建议是加一个 k 参数，可以把拦截器要拦截的函数名传递过去

如果可以传递  k 参数，是否考虑添加一个全局拦截器
```

filter = {
   success (p, k) {
        if (k === 'getUserInfo') {
               // do same thing
        } else {
              // do same thing
        }
   }
    fail (p, k) {
         if (k === 'getUserInfo') {
               // do same thing
        } else {
              // do same thing
        }
    }
}
intercept(filter)
```

这样就可以对所有通用的拦截函数放到一个 filter 里面了


我自己已经对现在的  wepy  改造成我想要的了，改造后，使用 intercept 可以省好多代码。所以来这里提个建议。难度是我之前表达不清楚？怎么会得到一个完全不是回答的回复

**Comment by galikeoy** [comment]
> @Gcaufy
> 
> 我怎么觉得你误会我了我的问题呢
> 
> 1、 wepy 对 wx 对象进行了封装， 并额外添加了一些方法
> 
> 比如我有一个函数
> 
> ```
> function foo(method) {
>   console.log(method.name)
>    method.call()
> }
> 
> foo(wepy.$has)
> foo(wepy.login)
> ```
> 
> foo 函数中，如果是 wepy 自己添加的函数接口，可以正常获得 function name， 但对于 wepy 封装的 wx 的接口，获取不到，这跟原生小程序没关系
> 
> 2、interceptor拦截器，我当然知道支持啊
> 
> 我是希望拦截器回调，可以传递一个 key 参数。如果你们觉得合理，是否考虑添加一个全局 interceptor拦截器
> 
> ```
> filter = {
>    success (p) {
>           // do same thing
>    }
>     fail (p, k) {
>          if (k === 'getUserInfo') {
>                // do same thing
>         } else {
>               // do same thing
>         }
>     }
> }
> 
> intercept('getUserInfo', filter)
> intercept('getLocation', filter)
> ```
> 
> 比如这样一给拦截器，两个函数拦截器只有些许不同，按目前的接口，我必须写两个 filter，因为 filter 函数回调的参数，只有 p， 没有 k。 我的建议是加一个 k 参数，可以把拦截器要拦截的函数名传递过去
> 
> 如果可以传递 k 参数，是否考虑添加一个全局拦截器
> 
> ```
> 
> filter = {
>    success (p, k) {
>         if (k === 'getUserInfo') {
>                // do same thing
>         } else {
>               // do same thing
>         }
>    }
>     fail (p, k) {
>          if (k === 'getUserInfo') {
>                // do same thing
>         } else {
>               // do same thing
>         }
>     }
> }
> intercept(filter)
> ```
> 
> 这样就可以对所有通用的拦截函数放到一个 filter 里面了
> 
> 我自己已经对现在的 wepy 改造成我想要的了，改造后，使用 intercept 可以省好多代码。所以来这里提个建议。难度是我之前表达不清楚？怎么会得到一个完全不是回答的回复

抱歉，打扰了，我想问下，2.0后的版本怎么用intercept？1.0的版本文档都是用类写的。而2.0版本则不用类写了，无论我怎么用都是not a function，无奈之下冒昧打扰
![image.png](https://ws1.sinaimg.cn/large/006qqcX8gy1g9zps6hqnfj30cd08djrm.jpg)
