### ISSUE TITLE
wepy模板不支持条件表达式？

### ISSUE THREAD

**Issue by ElderJames** [Tencent/wepy#900]
## Description

  [问题描述：站在其它人的角度尽可能清晰地、简洁地把问题描述清楚]
  [Description of the issue]

 模板中，循环元素中的条件表达式不起作用
```vue
      <repeat for="{{tabs}}" key="index" index="index" item="item">
        <view @tap="handlerTabTap" data-index="{{index}}" class="tab {{activeTab==index?'tab-active':''}}" style="width: {{stv.windowWidth/tabs.length}}px">
          <text>{{item}}</text>
        </view>
      </repeat>
```
源码：https://github.com/ElderJames/igdou-weapp/blob/master/src/components/tabView/tabview.wpy

## Environment

  * Platform: [开发者工具/iOS/Andriod/Web]
  * Platform version: [对应工具或者iOS或者Andriod的版本号]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [在package.json里]
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

  [如何重现问题]
  
  [How to reproduce the issue]

 运行这个项目：https://github.com/ElderJames/igdou-weapp，切换到学习tab，会有一个滑动tabview，tabview上的tab无法定位改变字体颜色

### Observed Results

  [实际表现]
  
  [Observed Results]
  
### Expected Results

  [期望表现]
  
  [Expected Results]
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs ohere to reproduce the problem
  ```

**Comment by Gcaufy** [comment]
什么 问题
