### ISSUE TITLE
getCurrentPages is not defined

### ISSUE THREAD

**Issue by insub** [Tencent/wepy#901]
如果使用到了 getCurrentPages 函数，编译的时候会报错：
getCurrentPages' is not defined

**Comment by Gcaufy** [comment]
请贴上关键代码

**Comment by insub** [comment]
大致是这样：
```
 onPullDownRefresh () {
      this.getPost()   
      if (getCurrentPages().length > 1) {
        this.backToIndex = false
      }
      this.$apply()
    }
```
代码跑起来是没有问题，只是 npm run build 的时候会报：
` 'getCurrentPages' is not defined                 no-undef``

**Comment by Gcaufy** [comment]
这个是eslint报错，。
关掉 eslint 或者将它加到global
https://stackoverflow.com/questions/39510736/eslint-dollar-is-not-defined-no-undef
http://eslint.cn/docs/rules/no-undef

**Comment by insub** [comment]
@Gcaufy 谢谢
