### ISSUE TITLE
component中template的变动，dist下的wxml没变化

### ISSUE THREAD

**Issue by leftjs** [Tencent/wepy#903]
通过 `wepy new` 出来的一个新的项目，我也遇到同样问题，
编辑components里面的wpy文件中的`<template>`，比如`counter.wpy`中我修改如下一行

![image](https://user-images.githubusercontent.com/8311633/35737166-958f6f50-0865-11e8-9951-4d48194d456b.png)

cmd + s 保存之后，触发watch重建，但是如图所示
![image](https://user-images.githubusercontent.com/8311633/35737024-1a254c36-0865-11e8-8b9f-fd0d7ed3073c.png)
只更新了`counter.js`,`counter.wxss`而`<template>`中的改动，理应是编译进`*.wxml`,在这里应该是`dist/pages/index.wxml`。
不知道是通病还是什么情况，如果是开发环境配置问题，望告知~

**Comment by Gcaufy** [comment]
因为counter使用了alias，然后导致检测父组件的时候出现了一个BUG，对于没有使用alias的组件来说，应该是正常的。

已修复这个问题，在下个release中发布。

**Comment by dongze1213** [comment]
我使用的1.7.0，编译component无法生成.wxml, 编译page可以生成.wxml,是不是bug 还没有解决？

**Comment by zhuqling** [comment]
1.7.3版本还是有问题，查看一下wepy-cli代码，已经和[commit](https://github.com/Tencent/wepy/commit/3e01756311ca7a48e8f1874275a042a05f6431ac)里是一样了

**Comment by bobsam** [comment]
@Gcaufy 现在该问题还没有修复。

**Comment by Qiuh-v** [comment]
只好手动改一下父页面，触发编译wxml
