### ISSUE TITLE
什么时候能解决下scss下的依赖编译问题

### ISSUE THREAD

**Issue by KingJeason** [Tencent/wepy#905]
我在asset在建立了好几个scss文件,然后 一个app.scss引入了这几个文件,
然后我在项目中引用了app.scss,但是我改变了样式,app.scss并不会改变

**Comment by cuijiemmx** [comment]
遇到了同样的问题，每次都需要重启...

**Comment by Gcaufy** [comment]
暂时处理，保存一下父scss文件就好了。
