### ISSUE TITLE
async/await 下wepy.getUserInfo偶尔的异步调用异常

### ISSUE THREAD

**Issue by liuzhenji** [Tencent/wepy#906]
## Description

  [问题描述：开启了promise化，并使用async/await实现同步调用wepy.getUserInfo接口，并未同步进行]

## Environment

  * Platform: [开发工具模拟器，IOS]
  * Platform version: [开发工具:v1.02.1802010 / 模拟器IOS6]
  * Wechat version: [微信版本号]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [^1.6.0]

  
## Reproduce
![image](https://user-images.githubusercontent.com/10750792/35775290-fb0e5cfe-09c0-11e8-8002-3d4f39e23482.png)

### Observed Results

![image](https://user-images.githubusercontent.com/10750792/35768717-84c12174-093b-11e8-8645-33d5c00dc01f.png)

  
### Expected Results

理应是一步一步同步输出日志
page:onLoad日志应该在
ers日志输出之后

## Relevant Code / Logs

  ```
  // TODO(you): code or logs ohere to reproduce the problem
  ```

**Comment by Gcaufy** [comment]
这个属于对async 的误理解。

**Comment by liuzhenji** [comment]
嗯嗯，是的，我算是new bee速成的，理解多有不准确之处，感谢
