### ISSUE TITLE
如何使用dotenv设置appsecret等敏感字符串为环境变量？

### ISSUE THREAD

**Issue by wuzhuzhu** [Tencent/wepy#908]
## Description

  目前issue中已经有设置process.env.NODE_ENV的多种做法，包括babel插件和replace等，但是这些方法貌似都不能和dotenv兼容。在开发过程中 客户端难免调用一些类似于app secret key之类的敏感信息，需要放到gitignore的dotenv文件里面管理。

## Environment

与环境无关

## Reproduce
```
npm install dotenv --save
```
创建一.env文件。定义test=1
yarn add -D babel-plugin-global-define
yarn add -D babel-plugin-transform-node-env-inline
wepy.config.js
```javascript
...
plugins: [
        'transform-class-properties',
        'transform-decorators-legacy',
        'transform-object-rest-spread',
        'transform-export-extensions',
        'transform-node-env-inline',
        ['global-define', {
          // __ENV__: process.env.NODE_ENV,
          __TEST__: process.env.test
        }]
      ]
...
```

### Observed Results

在程序script标签中调用 ```__TEST__```
是undefined
  
  
### Expected Results

```console.log(__TEST__)```

1

**Comment by Gcaufy** [comment]
敏感字符串不应该放在前端，app secret key 请放后台使用。。。放ignore也没用，也是会出现在代码里。

**Comment by wuzhuzhu** [comment]
比如使用lean_cloud的场景 官方示例就是secret放前端。放ignore并不会出现在代码里吧... 是用环境变量传递的 只有服务器运行环境里面有敏感字符串

**Comment by wuzhuzhu** [comment]
https://github.com/motdotla/dotenv
使用dotenv应该算是个常用需求...
