### ISSUE TITLE
拦截器都支持哪些原生小程序方法？

### ISSUE THREAD

**Issue by G-Veigar** [Tencent/wepy#914]
除了request，还可以拦截其他的api吗？ 比如uploadFile
`
    this.intercept('uploadFile', {
      config (p) {
        console.log('intercept', p)
        return p
      }
    })
`
我尝试加入如上拦截器，并没有打印出来结果是为什么呢。

**Comment by WangLeto** [comment]
实测 uploadFile 不被拦截

@Gcaufy
