### ISSUE TITLE
引入的js编译后出现undefined

### ISSUE THREAD

**Issue by tomfriwel** [Tencent/wepy#915]
`api(Object.assign({}, options, { success: resolve, fail: reject }), ...params);` 
编译后变成了：
`api.apply(undefined, [Object.assign({}, options, { success: resolve, fail: reject })].concat(params));`

这里的`undefined`在预览里报错

> Possible Unhandled Promise Rejection: TypeError: Cannot read property 'apply' of undefined

**Comment by Gcaufy** [comment]
代码这样翻译没有错，
```
Cannot read property 'apply' of undefined
```
是指
```
api === undefined
```

**Comment by tomfriwel** [comment]
发现是我在`export default class extends wepy.app {}`外面调用了`wepy.getUserInfo`, 就会报这个警告，如果我放在`export default class extends wepy.app {}`里才没有出现这个问题。
