### ISSUE TITLE
this.$apply不会触发嵌套的自定义组件中的$apply

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#916]
场景是父组件通过api请求获取到的返回值存到全局定义的一个store中，子组件UI要渲染store中的这个返回值中的变量到UI

很自然父组件在api返回后要手动调用$apply刷新自己的UI，然而此时并不会迭代调用子组件中的$apply，导致子组件UI未刷新，另外有趣的是，在子组件中定义了一个tap事件，在父组件点击子组件时发现UI更新了。父组件中的tap.user事件处理是空的..

目前的解决方案是在这种场景下手动调用内嵌自定义子组件中的$apply

希望对于自定义的子组件，父组件在$apply时也能自动调用自定义子组件中的$apply

**Comment by Gcaufy** [comment]
看一下`:props.sync`

**Comment by cuijiemmx** [comment]
@Gcaufy props.sync我也有用，但是和我说的这个不是一码事，我说的这个是通过全局自定义的store共享变量，并不是通过props.sync传值的

**Comment by Gcaufy** [comment]
redux
