### ISSUE TITLE
代码分离后，监听js文件后编译bug

### ISSUE THREAD

**Issue by BorelTung** [Tencent/wepy#917]
## Description

  page代码分离成`index.js`, `index.less`, `index.wpy`后，
修改`index.js`文件任意代码，报错：
```
出现脚本错误或者未正确调用 Page()
```
查看编译后dist文件，发现少了原本应该有的这行代码：
```
Page(require('./../../../npm/wepy/lib/wepy.js').default.$createPage(Test , 'pages/a/b/index'));
```
这时修改`index.wpy`文件任意代码，编译成功，`Page`这行代码又有了。

## Environment

  * Platform: 开发者工具(Mac)
  * Platform version: 1.02.1801081
  * wepy version: 1.6.0

**Comment by Gcaufy** [comment]
index.wpy 会被编译为index.js 所以与你的index.js 重名了。

**Comment by BorelTung** [comment]
@Gcaufy 用`typescript`就不会出现，是为什么呢

**Comment by Gcaufy** [comment]
index.js 改名为其它吧。不要与index.wpy重名。

**Comment by BorelTung** [comment]
试了下，改名的确不会报错了，但是dist目录下会多1个文件，变成`index.js`, `index.wxml`, `index.wxss`, `main.js`，其中，`main.js`的代码是多余的，`index.js`中有它的代码。

**Comment by BorelTung** [comment]
有个解决办法是改变代码分离的方式，分为：
`index.wxml`, `index.less`, `index.wpy`，
但是，这样的话，`index.wpy`中的代码就比较丑了，
```
<template lang="wxml" src="./index.wxml"><template/>
<style lang="less" src="./index.less"></style>
<script lang="babel">
  ...
</script>
```

**Comment by BorelTung** [comment]
@Gcaufy thank you for your reply, and waiting for a further one
