### ISSUE TITLE
请问如何正确引入 socket.io 包？

### ISSUE THREAD

**Issue by xiaoxin01** [Tencent/wepy#919]
你好，这边尝试引用 socket.io 包：

const io = require('../../node_modules/socket.io-client/dist/socket.io.js');

wepy build --no-cache可以编译通过，但是socket.io.js文件没有被copy到 dist/npm 下面，请问要如何正确引入，感谢～

**Comment by cuijiemmx** [comment]
@xiaoxin01 小程序有自己的websocket接口，socket.io不改代码能work我看不可能吧

**Comment by Gcaufy** [comment]
socket.io 应该是基于 websocket的，与小程序的websocket可能会有一些区别。所以没有办法直接在小程序端使用的。
