### ISSUE TITLE
block 和 repeat 中的 class 都没有 hash

### ISSUE THREAD

**Issue by xream** [Tencent/wepy#920]
## Description

block 和 repeat 中的 class 都没有 hash

## Environment

  * Platform: 开发者工具
  * Platform version: 1.9.5
  * Wechat version: [微信版本号]
  * wepy-cli version: 1.7.0
  * wepy version: 1.7.0
  * other version: [如果是插件问题，请列出问题插件的版本号]
  
## Reproduce

wepy-cli  1.7.0 可重现

wepy-cli 1.6.1-alpha8   正常

### Observed Results

![image](https://user-images.githubusercontent.com/1210282/35850292-3f06a192-0b5f-11e8-93cb-8353f7ff0350.png)

  
### Expected Results

![image](https://user-images.githubusercontent.com/1210282/35850327-60c09fe0-0b5f-11e8-973b-5ac693263d39.png)
  

## Relevant Code / Logs

  ```
  view.a
    block(wx:if="{{ cond }}")
      view.b
    repeat(for="{{ items }}" key="index" index="index" item="item")
      view.c {{ item }}
  ```

**Comment by kankungyip** [comment]
我也升级到1.7.0确实有这个问题，之前一切正常。
