### ISSUE TITLE
scroll-view组件Bug

### ISSUE THREAD

**Issue by czero1995** [Tencent/wepy#921]
scroll-view组件触发scroll-top事件，值为0时无法回到文档顶部，值为-1，可以回到顶部。
当scroll-view内容过多，将scroll-top的值为-1时，有时候无法触顶。

**Comment by Gcaufy** [comment]
看表象似乎与wepy关系不大，建议提供[代码片断](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)方便还原

**Comment by luotingv1** [comment]
<template>
<view class="searchLetter touchClass">
  <view class="thishotText" @tap="hotCity">
    <view style="margin-top:0;">当前</view>
    <view style="margin-top:0;">热门</view>
  </view>
  <view wx:for="{{searchLetter}}" style="color:#333;font-size:20rpx;" wx:key="index" data-letter="{{item.name}}" catchtouchend="clickLetter">{{item.name}}</view>
</view>
<block wx:if="{{isShowLetter}}">
  <view class="showSlectedLetter">
    {{showLetter}}
  </view>
</block>
<scroll-view scroll-y="true" style="height:{{winHeight}}px"  scroll-into-view="{{scrollTopId}}" @scroll="scroll" scroll-top="{{scrollTop}}">
  <view class="search-bar">
    <view   class="search-content"  @tap="toSearchProductPage">
      <label class="zan-icon zan-icon-search"></label><text class="text-sec">请输入城市名称</text>
    </view>
  </view>
  <view class="hotcity-common thisCity">最近位置</view>
  <view class="thisCityName">{{city}}</view>
  <view>
    <text class="hotcity hotcity-common">热门城市</text>
    <view class="weui-grids">
      <block wx:for-items="{{hotcityList}}" wx:key="{{index}}">
        <view class="weui-grid" data-cityCode="{{item.cityCode}}" data-city="{{item.city}}" @tap="bindHotCity">
          <view class="weui-grid__label">{{item.city}}</view>
        </view>
      </block>
    </view>
  </view>
  <view class="selection" wx:for="{{cityList}}" wx:key="{{item.initial}}">
    <view class="item_letter" id="{{item.initial}}">{{item.initial}}</view>
    <view class="item_city" wx:for="{{item.cityInfo}}" wx:for-item="ct" wx:key="{{ct.id}}" data-cityCode="{{ct.code}}" data-city="{{ct.city}}" @tap="bindCity">
      {{ct.city}}
    </view>
  </view>
</scroll-view>
</template>

<script>
import wepy from 'wepy'
import axios from '@/http/config'
import city from '@/utils/city.js';

export default class search extends wepy.page {
  config = {
    navigationBarTitleText: '定位'
  }

  data = {
    searchLetter: [],
    showLetter: "",
    winHeight: 0,
    // tHeight: 0,
    // bHeight: 0,
    cityList: [],
    isShowLetter: false,
    scrollTop: 0, //置顶高度
    scrollTopId: '', //置顶id
    city: "上海市",
    hotcityList: [{
      cityCode: 110000,
      city: '北京市'
    }, {
      cityCode: 310000,
      city: '上海市'
    }, {
      cityCode: 440100,
      city: '广州市'
    }, {
      cityCode: 440300,
      city: '深圳市'
    }, {
      cityCode: 330100,
      city: '杭州市'
    }, {
      cityCode: 320100,
      city: '南京市'
    }, {
      cityCode: 420100,
      city: '武汉市'
    }, {
      cityCode: 410100,
      city: '郑州市'
    }, {
      cityCode: 120000,
      city: '天津市'
    }, {
      cityCode: 610100,
      city: '西安市'
    }, {
      cityCode: 510100,
      city: '成都市'
    }, {
      cityCode: 500000,
      city: '重庆市'
    }]
  }

  onShow(){
    let that=this;
    wx.getLocation({
      type: 'wgs84', // 默认为 wgs84 返回 gps 坐标，gcj02 返回可用于 wx.openLocation 的坐标
    success: function(res){
        // success
        var longitude=res.longitude
        var latitude=res.latitude
        that.loadCity(longitude,latitude)
      }
    })
  }

  loadCity(longitude,latitude){
    var page =this
    wx.request({
      url: 'http://restapi.amap.com/v3/geocode/regeo?&location='+longitude+','+latitude+'&key=<用户的key>',
      data: {},
      header:{
        'Content-Type':'application/json'
      },
      success: function(res){
        // success
        console.log(res);
      },
    })
  }


  methods = {
    clickLetter(e) {
     let showLetter = e.currentTarget.dataset.letter;
      this.showLetter =showLetter;
      this.isShowLetter=true,
      this.scrollTopId=showLetter;
      var that = this;
      setTimeout(function() {
        that.isShowLetter=false
        that.$apply()
      }, 500)
    },
    //选择城市
    bindCity(e) {
      this.city=e.currentTarget.dataset.city
      wx.navigateBack()
    },
    scroll: function(e) {
        // this.scrollTop=e.detail.scrollTop;
     },
    //选择热门城市
    bindHotCity(e) {
      this.city=e.currentTarget.dataset.city
      wx.navigateBack()
    },
    //点击热门城市回到顶部
    hotCity() {
      this.setData({
       scrollTop: 0,
     })
    }
  }
  onLoad() { // 生命周期函数--监听页面加载
    var searchLetter = city.searchLetter;
    this.cityList = city.cityList();
    var sysInfo = wx.getSystemInfoSync();
    this.winHeight = sysInfo.windowHeight;
    this.itemH = this.winHeight / searchLetter.length;
    this.searchLetter = [];
    for (var i = 0; i < searchLetter.length; i++) {
      var temp = {};
      temp.name = searchLetter[i];
      temp.tHeight = i * this.itemH;
      temp.bHeight = (i + 1) * this.itemH;
      this.searchLetter.push(temp)
    }
  }


}
</script>

<style media="screen" lang="scss" scoped>

.search-content {
  width:690rpx;
  margin: 0 auto;
  padding: 0 20rpx;
  display: flex;
  height: 64rpx;
  align-items: center;
  background: #F4F4F4;
  color:#C6C6C6;
  border-radius: 4rpx;
  font-size:26rpx;
  .text-sec {
    margin-left: 12rpx;
  }
}

.searchLetter {
    position: fixed;
    right: 0;
    width: 50rpx;
    text-align: center;
    justify-content: center;
    display: flex;
    flex-direction: column;
    color: #666;
    z-index: 1;
    view {
       margin-top: 20rpx;
   }
}


.touchClass {
    background-color: #fff;
    color: #fff;
    padding-top: 46rpx;
}

.showSlectedLetter {
    background-color: rgba(0, 0, 0, 0.5);
    color: #fff;
    display: flex;
    justify-content: center;
    align-items: center;
    position: fixed;
    top: 50%;
    left: 50%;
    margin: -100rpx;
    width: 200rpx;
    height: 200rpx;
    border-radius: 20rpx;
    font-size: 52rpx;
    z-index: 1;
}

.selection {
    display: flex;
    width: 100%;
    flex-direction: column;
    margin-top: 10rpx;
}

.item_letter {
    display: flex;
    background-color: #f5f5f5;
    height: 40rpx;
    padding-left: 34rpx;
    align-items: center;
    font-size: 24rpx;
    color: #666;
}

.item_city {
    display: flex;
    background-color: #fff;
    height: 100rpx;
    padding-left: 34rpx;
    align-items: center;
    border-bottom: 1rpx solid #ededed;
    font-size: 24rpx;
}

.hotcity-common {
    font-size: 24rpx;
    color: #666;
    padding: 0 0 0 30rpx;
}

.thisCity {
    padding-top: 30rpx;
}

.thisCityName {
    display: inline-block;
    border: 1rpx solid #FF931E;
    border-radius: 8rpx;
    padding: 10rpx 0;
    font-size: 24rpx;
    color: #FF931E;
    text-align: center;
    min-width: 149.5rpx;
    margin: 20rpx 0 20rpx 30rpx;
}

.thishotText {
    color: #333;
    font-size: 20rpx;
    margin: 0 !important;
}

.slectCity {
    border-color: #2ab4ff !important;
}

.slectCity view {
    color: #2ab4ff !important;
}

.weui-grid {
    position: relative;
    float: left;
    padding: 10rpx 0;
    width: 149.5rpx;
    box-sizing: border-box;
    border: 1rpx solid #ececec;
    border-radius: 8rpx;
    margin: 10rpx 12rpx;
}

.weui-grid__label {
    display: block;
    text-align: center;
    color: #333;
    font-size: 24rpx;
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
}
</style>

**Comment by luotingv1** [comment]
`<template>
<view class="searchLetter touchClass">
  <view class="thishotText" @tap="hotCity">
    <view style="margin-top:0;">当前</view>
    <view style="margin-top:0;">热门</view>
  </view>
  <view wx:for="{{searchLetter}}" style="color:#333;font-size:20rpx;" wx:key="index" data-letter="{{item.name}}" catchtouchend="clickLetter">{{item.name}}</view>
</view>
<block wx:if="{{isShowLetter}}">
  <view class="showSlectedLetter">
    {{showLetter}}
  </view>
</block>
<scroll-view scroll-y="true" style="height:{{winHeight}}px"  scroll-into-view="{{scrollTopId}}" @scroll="scroll" scroll-top="{{scrollTop}}">
  <view class="search-bar">
    <view   class="search-content"  @tap="toSearchProductPage">
      <label class="zan-icon zan-icon-search"></label><text class="text-sec">请输入城市名称</text>
    </view>
  </view>
  <view class="hotcity-common thisCity">最近位置</view>
  <view class="thisCityName">{{city}}</view>
  <view>
    <text class="hotcity hotcity-common">热门城市</text>
    <view class="weui-grids">
      <block wx:for-items="{{hotcityList}}" wx:key="{{index}}">
        <view class="weui-grid" data-cityCode="{{item.cityCode}}" data-city="{{item.city}}" @tap="bindHotCity">
          <view class="weui-grid__label">{{item.city}}</view>
        </view>
      </block>
    </view>
  </view>
  <view class="selection" wx:for="{{cityList}}" wx:key="{{item.initial}}">
    <view class="item_letter" id="{{item.initial}}">{{item.initial}}</view>
    <view class="item_city" wx:for="{{item.cityInfo}}" wx:for-item="ct" wx:key="{{ct.id}}" data-cityCode="{{ct.code}}" data-city="{{ct.city}}" @tap="bindCity">
      {{ct.city}}
    </view>
  </view>
</scroll-view>
</template>

<script>
import wepy from 'wepy'
import axios from '@/http/config'
import city from '@/utils/city.js';

export default class search extends wepy.page {
  config = {
    navigationBarTitleText: '定位'
  }

  data = {
    searchLetter: [],
    showLetter: "",
    winHeight: 0,
    // tHeight: 0,
    // bHeight: 0,
    cityList: [],
    isShowLetter: false,
    scrollTop: 0, //置顶高度
    scrollTopId: '', //置顶id
    city: "上海市",
    hotcityList: [{
      cityCode: 110000,
      city: '北京市'
    }, {
      cityCode: 310000,
      city: '上海市'
    }, {
      cityCode: 440100,
      city: '广州市'
    }, {
      cityCode: 440300,
      city: '深圳市'
    }, {
      cityCode: 330100,
      city: '杭州市'
    }, {
      cityCode: 320100,
      city: '南京市'
    }, {
      cityCode: 420100,
      city: '武汉市'
    }, {
      cityCode: 410100,
      city: '郑州市'
    }, {
      cityCode: 120000,
      city: '天津市'
    }, {
      cityCode: 610100,
      city: '西安市'
    }, {
      cityCode: 510100,
      city: '成都市'
    }, {
      cityCode: 500000,
      city: '重庆市'
    }]
  }

  onShow(){
    let that=this;
    wx.getLocation({
      type: 'wgs84', // 默认为 wgs84 返回 gps 坐标，gcj02 返回可用于 wx.openLocation 的坐标
    success: function(res){
        // success
        var longitude=res.longitude
        var latitude=res.latitude
        that.loadCity(longitude,latitude)
      }
    })
  }

  loadCity(longitude,latitude){
    var page =this
    wx.request({
      url: 'http://restapi.amap.com/v3/geocode/regeo?&location='+longitude+','+latitude+'&key=<用户的key>',
      data: {},
      header:{
        'Content-Type':'application/json'
      },
      success: function(res){
        // success
        console.log(res);
      },
    })
  }


  methods = {
    clickLetter(e) {
     let showLetter = e.currentTarget.dataset.letter;
      this.showLetter =showLetter;
      this.isShowLetter=true,
      this.scrollTopId=showLetter;
      var that = this;
      setTimeout(function() {
        that.isShowLetter=false
        that.$apply()
      }, 500)
    },
    //选择城市
    bindCity(e) {
      this.city=e.currentTarget.dataset.city
      wx.navigateBack()
    },
    scroll: function(e) {
        // this.scrollTop=e.detail.scrollTop;
     },
    //选择热门城市
    bindHotCity(e) {
      this.city=e.currentTarget.dataset.city
      wx.navigateBack()
    },
    //点击热门城市回到顶部
    hotCity() {
      this.setData({
       scrollTop: 0,
     })
    }
  }
  onLoad() { // 生命周期函数--监听页面加载
    var searchLetter = city.searchLetter;
    this.cityList = city.cityList();
    var sysInfo = wx.getSystemInfoSync();
    this.winHeight = sysInfo.windowHeight;
    this.itemH = this.winHeight / searchLetter.length;
    this.searchLetter = [];
    for (var i = 0; i < searchLetter.length; i++) {
      var temp = {};
      temp.name = searchLetter[i];
      temp.tHeight = i * this.itemH;
      temp.bHeight = (i + 1) * this.itemH;
      this.searchLetter.push(temp)
    }
  }


}
</script>

<style media="screen" lang="scss" scoped>

.search-content {
  width:690rpx;
  margin: 0 auto;
  padding: 0 20rpx;
  display: flex;
  height: 64rpx;
  align-items: center;
  background: #F4F4F4;
  color:#C6C6C6;
  border-radius: 4rpx;
  font-size:26rpx;
  .text-sec {
    margin-left: 12rpx;
  }
}

.searchLetter {
    position: fixed;
    right: 0;
    width: 50rpx;
    text-align: center;
    justify-content: center;
    display: flex;
    flex-direction: column;
    color: #666;
    z-index: 1;
    view {
       margin-top: 20rpx;
   }
}


.touchClass {
    background-color: #fff;
    color: #fff;
    padding-top: 46rpx;
}

.showSlectedLetter {
    background-color: rgba(0, 0, 0, 0.5);
    color: #fff;
    display: flex;
    justify-content: center;
    align-items: center;
    position: fixed;
    top: 50%;
    left: 50%;
    margin: -100rpx;
    width: 200rpx;
    height: 200rpx;
    border-radius: 20rpx;
    font-size: 52rpx;
    z-index: 1;
}

.selection {
    display: flex;
    width: 100%;
    flex-direction: column;
    margin-top: 10rpx;
}

.item_letter {
    display: flex;
    background-color: #f5f5f5;
    height: 40rpx;
    padding-left: 34rpx;
    align-items: center;
    font-size: 24rpx;
    color: #666;
}

.item_city {
    display: flex;
    background-color: #fff;
    height: 100rpx;
    padding-left: 34rpx;
    align-items: center;
    border-bottom: 1rpx solid #ededed;
    font-size: 24rpx;
}

.hotcity-common {
    font-size: 24rpx;
    color: #666;
    padding: 0 0 0 30rpx;
}

.thisCity {
    padding-top: 30rpx;
}

.thisCityName {
    display: inline-block;
    border: 1rpx solid #FF931E;
    border-radius: 8rpx;
    padding: 10rpx 0;
    font-size: 24rpx;
    color: #FF931E;
    text-align: center;
    min-width: 149.5rpx;
    margin: 20rpx 0 20rpx 30rpx;
}

.thishotText {
    color: #333;
    font-size: 20rpx;
    margin: 0 !important;
}

.slectCity {
    border-color: #2ab4ff !important;
}

.slectCity view {
    color: #2ab4ff !important;
}

.weui-grid {
    position: relative;
    float: left;
    padding: 10rpx 0;
    width: 149.5rpx;
    box-sizing: border-box;
    border: 1rpx solid #ececec;
    border-radius: 8rpx;
    margin: 10rpx 12rpx;
}

.weui-grid__label {
    display: block;
    text-align: center;
    color: #333;
    font-size: 24rpx;
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
}
</style>
`
