### ISSUE TITLE
关于1.7.0wxs的使用问题

### ISSUE THREAD

**Issue by fitcong** [Tencent/wepy#925]
> [](url)
![1517987619935](https://user-images.githubusercontent.com/23007631/35903332-a69bf734-0c19-11e8-9cb1-7fc3e65fed71.jpg)
在编译期路径被更改了

**Comment by fitcong** [comment]
经排查,component内部使用相同的wxs会导致编译失败,无法上传代码至小程序端

**Comment by Gcaufy** [comment]
是指两个component使用同一个wxs么？

**Comment by Megasu** [comment]
1.7.0 的 wxs文件，按照官方文档的目录结构，在项目的index.wpy导入后，不能正常解析。
cmd终端编译不报错，

小程序运行的时候报错内容：
VM2570:2 webviewScriptError
modules is not defined
ReferenceError: modules is not defined
    at ./wxs/mywxs.wxs

**Comment by Megasu** [comment]
在交流群中上百号人，都没有人能正常使用过 wxs，
不知道是什么问题，希望能早点解决并更新到官方文档中。

**Comment by xty1992a** [comment]
有个深坑，你在子组件里引用的wxs必须按照组件被使用的位置来设定路径…
差不多就是废的啊

**Comment by Gcaufy** [comment]
@Megasu 看看是不是小程序基础库选择不对吧。

**Comment by maimake** [comment]
@Megasu 我也遇到了类似的问题，子组件嵌套另一个组件的时候，就会错乱

```
└── src
    ├── pages
    │   └── main
    │       ├── components
    │       │   ├── avatar-name.wpy
    │       │   └── avatar.wpy
    │       └── index.wp
    └── wxs
        └── common.wxs
```

index.wpy 引用 avatar.wpy 
avatar.wpy 引用avatar-name.wpy

avatar和avatar-name两个都引用了common.wxs
`import WxsCommon from '../../../../wxs/common.wxs'`

那么编译出来的index.wxml的相对路径明显有问题
```
    <wxs src="../../../wxs/common.wxs" module="xCommon"/>

    <view class="avatar">
      avatar
      <wxs src="../../../../wxs/common.wxs" module="xCommon"/>
  
      <view class="avatar name">
        avatar name
      </view>
  
    </view>

```

我的wepy版本是1.7.2-alpha1

**Comment by maimake** [comment]
另外，我把假如我的结构稍微修改下，甚至页面都出不来。

```
└── src
    ├── components
    │   └── avatar.wpy
    ├── pages
    │   └── main
    │       ├── components
    │       │   └── avatar-name.wpy
    │       └── index.wp
    └── wxs
        └── common.wxs
```

报错

```
in File: ./components/avatar.wxss

File not found: ./../pages/main/components/avatar-name.wxss
编译 .wxss 文件错误，错误信息如上，可在控制台查看更详细信息
```

我所有的wepy文件引用都是用@方式的

感觉wepy在处理相对路径这块太混乱了

**Comment by nigelvon** [comment]
这个问题不能关啊，根本就没解决。如果是非根目录下的组件，开发的时候wxs用相对路径没问题，打包之后路径就不对了。

**Comment by Gcaufy** [comment]
@dlhandsome

**Comment by xuweikang** [comment]
@maimake  兄弟，怎么解决的

**Comment by maimake** [comment]
@xuweikang 我也没有解决，只能尽量避免这样的结构。 @Gcaufy 既然是组件直接编译到Page.wxml，可否在编译出来后，稍微遍历一遍wxs修正相对路径？

**Comment by FEpccBo** [comment]
同问这个问题啊 子组件父组件都引用相同的wxs 编译就会报错

**Comment by FEpccBo** [comment]
@xty1992a  同意 请问有好的解决方案么

**Comment by fitcong** [comment]
在使用的时候引入的时候不要用相同的名字
page 
```
import filter from '../../utils/price-utils.wxs'
export default class Index extend wepy.page{
     wxs:{
        priceFilter:filter
   }
}
```
component 
```
import childFilter from '../../utils/price-utils.wxs'
export default class Index extend wepy.component{
     wxs:{
        priceChildFilter:childFilter
   }
}
```
你们可以试一下

**Comment by xuweikang** [comment]
@Gcaufy  所以说现在还没解决这个bug吗

**Comment by Slngle** [comment]
这个问题还没解决么？太蛋疼了

**Comment by jsGood** [comment]
按照官方文档正确操作，吗的，报错，报错
`VM3786:5 ./pages/collectLike/periodsCLike.wxml
@/wxs/filter.wxs not found from ./pages/collectLike/periodsCLike.wxml
> 1 | <wxs src="@/wxs/filter.wxs" module="fs" class="_55e52ec"/>
    | ^
  2 | 
  3 |   `

**Comment by jsGood** [comment]
我引入wxs成功了，一开始不成功是因为wxs 引入的时候用的@，就是你路径对也编译报错，是不是巨坑？非得要用../..这样层级去找。。。还有就是编写wxs的时候，记得不要用let，用var，否则不会继续执行了。
