### ISSUE TITLE
animation的使用限制

### ISSUE THREAD

**Issue by Hideer** [Tencent/wepy#926]
进初步测试，发现animation不可作用在组件中，不知你们怎么看

**Comment by Hideer** [comment]
貌似是组件中不支持api的实例化

**Comment by denty** [comment]
我再组件中使用animation确实无法使用

**Comment by Gcaufy** [comment]
能给出相关代码么？

**Comment by qiupanfeng** [comment]
![image](https://user-images.githubusercontent.com/21079388/36664176-d4d9412e-1b1e-11e8-88f0-2f9872233f18.png)

确实啊，组件里animation失效

**Comment by aoliaoliao** [comment]
@Gcaufy 项目刚开始，也遇到了这样的问题，不知道现在框架有什么解决方案或建议吗？

**Comment by ahjsrhj** [comment]
这个问题并没有解决,能否重新打开?

**Comment by ericzhou2008** [comment]
> 这个问题并没有解决,能否重新打开?

坑爹，这个问题我们也遇到了，so sad!

**Comment by qiuyaofan** [comment]
在每次赋值最后加this.$apply
