### ISSUE TITLE
如何通过 wepy 拿到 wepy.app 实例

### ISSUE THREAD

**Issue by lkspc** [Tencent/wepy#927]
自定义了一个工具类文件 utils.js, 想在里面获取我挂载到 wepy.app 实例上的 globalData，因为这个文件里面的函数没有 this 对象，无法通过 this.$root.$parent.globalData 来获取。<br>
请问 wepy 上有没有什么函数或者属性可以拿到这个实例？尝试使用 getApp() 发现拿不到 globalData。
```js
import wepy from 'wepy';
export function request() {
    // 有没有 wepy.xxx 或者 wepy.xxx() 可以拿到 globalData ?
   const { globalData } = ?
}
```

**Comment by lkspc** [comment]
找到了，wepy.$instance

**Comment by Suntgr** [comment]
请问下哪里找到的，我看文档里没有。 @lkspc

**Comment by lkspc** [comment]
@Suntgr 你直接 console.log(wepy) 就可以看到它的所有属性了

**Comment by xuweikang** [comment]
@lkspc 这样直接用，会有副作用吗？

**Comment by lkspc** [comment]
@xuweikang 没有副作用，源代码里面就是把 app 挂载到上面了的。有很多内部属性都以 $ 开头来挂载的
