### ISSUE TITLE
使用wx:else 小程序报错"Bad attr `wx"

### ISSUE THREAD

**Issue by renjunlincn** [Tencent/wepy#931]
使用wx:else 小程序报错"Bad attr `wx"
wx:if和hidden不会报错

**Comment by liuzhenji** [comment]
这种情况下，一般是wx:else没有对应的wx:if

**Comment by derickren** [comment]
有wx:if与之对应，自定义组件diary-list的最外层使用的repeat标签会出现这个报错，
`<template>
    <repeat>...</repeat>
</template>`
如果最外层使用view标签则不会报错。
`<template>
    <view>
        <repeat>...</repeat>
    </view>
</template>`

**Comment by cuijiemmx** [comment]
@derickren 原谅我插个嘴，建议你把出错的整个<template>...</template>发上来并且注明出错的地方，没有上下文光嘴说是讲不清楚的

**Comment by ZhuRuiHeng** [comment]
wx:for 和wx:if 不能同时出现在一个标签上
