### ISSUE TITLE
父组件怎么传递对象的属性，传过来是空的 

### ISSUE THREAD

**Issue by silinabai** [Tencent/wepy#932]
父组件需要传递一个数组给子组件：
这个数组是对象的属性：myObject.images
 父组件：` <slide :imageData.sync="myObject.images"></slide>`
子组件：`<block wx:for="{{imageData}}" wx:key="index" item="item"></block>`
   props = {
      imageData: {
        type: Array,
        default: []
      }
    }
现在的问题是传过来是空的，请问类似这种的数据传递怎么传

**Comment by masogit** [comment]
@silinabai 请问怎么解决的此问题? 我是了也是无法同步传递对象里面的属性给子节点
