### ISSUE TITLE
切换node版本后，WePY命令行工具报错

### ISSUE THREAD

**Issue by jxDeveloper** [Tencent/wepy#935]
## Description

  切换node版本后，WePY命令行工具报错
  

## Environment
  * Platform: [Web]
  * wepy-cli version: [1.7.0]

  [如何重现问题]

  假如我电脑安装了node版本6.11.3和8.9.3，我安装wepy-cli -g时是在node6.11.3版本时安装的话，当使
  用nvm切换到node8.9.3时，使用wepy命令就会报错

  [实际表现]
  
   只有切回我安装wepy-cli时的node 6.11.3版本，wepy命令可用，当我切到node8.9.3时，wepy命令报找
   不到错误，nvm切换node版本，造成安装路径找错了。
  

  [期望表现]
  
  无论当初的wepy-cli是在哪个node版本下安装的，切换node版本，wepy命令任然可用

**Comment by cuijiemmx** [comment]
@jxDeveloper 这个不是wepy的bug，nvm下不同版本的node使用的目录是不同的，你需要分别在6.11.3和8.9.3下通过npm i wepy-cli -g安装wepy-cli

**Comment by jxDeveloper** [comment]
@cuijiemmx 嗯嗯，谢谢。如果不需要切换node版本就安装一次，会更方便

**Comment by cuijiemmx** [comment]
@jxDeveloper nvm就是要为特定版本的node提供独立的环境。要是真的像你说的这样共享，相反就没有达到设计的初衷了
