### ISSUE TITLE
模拟器正常，真机报错 Page not found

### ISSUE THREAD

**Issue by dpzxsm** [Tencent/wepy#936]
## Description
   引入第三方模块时，模拟器运行正常，真机预览时直接卡死。但是打开微信开发工具的压缩上传选项时，却奇迹般的好了。

## Environment

  * Platform: [iOS/Andriod]
  * Platform version: [6.0.1]
  * Wechat version: [6.6.2]
  * wepy-cli version: [wepy-cli -v]
  * wepy version: [1.6.1-alpha9]
  
## Reproduce

 import 获取 require npm包，出错的包是公司内部使用的npm包，包本身没有问题，不使用wepy框架引入不会报错。

### Observed Results

  控制台打印 Page not found， 估计是编译时直接报错了。

**Comment by dpzxsm** [comment]
自己找到原因了，npm包里面require了一个空的js文件，至于打开微信开发工具的压缩上传选项却好了，不明所以，先溜了。

**Comment by cenxun** [comment]
# Description
预览版正常，模拟器正常，上传体验版出错

# Environment
Platform: [Andriod]
Wechat version: [6.6.6]
wepy version: [1.7.2]

# Observed Results
控制台打印如下问题
```
Page[pages/index] not found. May be caused by: 
1. Forgot to add page route in app.json.
2. Invoking Page() in async task.
```
