### ISSUE TITLE
import 引入wxs 文件后报错：modules is not defined

### ISSUE THREAD

**Issue by moshanghan** [Tencent/wepy#937]
按照wepy文档规范引入wxs后，报错
`ReferenceError: modules is not defined
    at ./wxs/filter.wxs
`
filter.js

modules.exports = {
    // 图片路径添加https
  imgHttpsPath:function (path) {
    if (path.indexOf('http') > -1 && path.indexOf('https') < 0){
      return 'https:' + path.slice(5)
    } else if (path.indexOf('https') < 0) {
      return 'https:' + path
    } else {
      return path
    }
  }
}

index.wpy

...
 import filter from '../../wxs/filter.wxs'
  export default class extends wepy.page {
...
 wxs = {
      filter: filter
    }
...
}

**Comment by Gcaufy** [comment]
版本？

**Comment by moshanghan** [comment]
版本wepy-cli1.7.0   wepy1.7.0

**Comment by moshanghan** [comment]
[官方文档如下写](https://tencent.github.io/wepy/document.html#/)
`
// mywxs.wxs
modules.exports = {
  text: 'This is from wxs',
  filter: function (num) {
    return num.toFixed(2);
  }
};
`
将modules.exports={...}修改为module.exports={...}
不知道是不是文档有问题呢？

**Comment by Gcaufy** [comment]
文档写错。欢迎pr
