### ISSUE TITLE
scss文件不会watch实时编译，每次更改需要重新build，如何解决？

### ISSUE THREAD

**Issue by xian107** [Tencent/wepy#938]
![image](https://user-images.githubusercontent.com/13252682/36015306-f43bedd8-0da8-11e8-849f-18abd5bccb73.png)
没有实时编译

**Comment by cuijiemmx** [comment]
板凳，同关注

**Comment by ACERY1** [comment]
同样遇到这样的情况，比如我在一个组件中引用了某个scss文件，但是当我改变这个scss文件后，组件内部导入的scss代码并没有得到更新，原因是这个组件的wxss没有重新编译

**Comment by Cheng007** [comment]
是的，严重影响开发体验，什么时候可以修复？

**Comment by binghuis** [comment]
sass修改完没有变化，最后手动去改dist下文件。累心。

**Comment by Gcaufy** [comment]
sass 中去 import 另外一个sass， 这个时候会有一些问题。再重新保存一下父文件还是可以触发编译的。

**Comment by Gcaufy** [comment]
刚发布了这个commit的alpha版本，解决了less/sass 在import 另外一个样式文件时，修改该样式文件时，不会触发父样式文件的更新的问题。

需要安装新版本解决这个问题：

```
npm install wepy-compiler-less@1.3.12 --save
npm install wepy-compiler-sass@1.3.12 --save
npm install wepy-cli@1.7.2-alpha2 -g

wepy build
```

**Comment by kitboy** [comment]
我用的webstorm，也遇到过修改并保存后watch时有响应的问题，后来检查了下发现可能是webstorm开启了safe write（first write to temp file）的选项，建议大家遇到这个问题同样检查下这个设置选项

**Comment by Gcaufy** [comment]
@kitboy 感谢，但这是另外一个问题。

**Comment by zhihaosu** [comment]
我在.wpy文件中引入一个1.scss文件，修改这个scss文件会触发.wpy文件的更新，但如果我在1.scss文件中继续引用了另一个2.scss文件，修改2.scss文件并不会触发.wpy文件的更新。
app.wpy
![image](https://user-images.githubusercontent.com/21259346/38079469-8f6ae212-3371-11e8-9c38-a5aa1800f86a.png)
1.scss
![image](https://user-images.githubusercontent.com/21259346/38079612-ebae2d72-3371-11e8-9e79-4fb7697f7e21.png)
![image](https://user-images.githubusercontent.com/21259346/38079676-19a6ff88-3372-11e8-9834-89f27ca6c550.png)
有人遇到类似的问题么？

**Comment by fancyMore** [comment]
@zhihaosu 可以保存1.scss触发更新，单独保存2.scss不会更新！
