### ISSUE TITLE
按照官方文档，引用组件报错

### ISSUE THREAD

**Issue by jxDeveloper** [Tencent/wepy#940]
官方文档写法：
![image11](https://user-images.githubusercontent.com/28999415/36022285-88717ac6-0dc3-11e8-961f-e59ffd8ced0e.png)

我自己写法：
![image10](https://user-images.githubusercontent.com/28999415/36022294-94612a5c-0dc3-11e8-8fd1-1140b1f9f140.png)

**Comment by cuijiemmx** [comment]
@jxDeveloper 应该是一个文档错误，你不报错的写法是正确的

**Comment by Gcaufy** [comment]
```
components = { 
    item: item
}
```
