### ISSUE TITLE
wepy config output 修改目录无效

### ISSUE THREAD

**Issue by wells1013** [Tencent/wepy#944]
当前wepy 版本 1.7.0   `output: 'prod',` 无效 

最后编译出来的地址始终是 `dist`

**Comment by wells1013** [comment]
#145 我看了 之前的这个issue   设置output 不知道是我弄错了吗？ 还是现在有问题？

**Comment by wells1013** [comment]
搞错了，应该用 `target`

**Comment by Gcaufy** [comment]
target
