### ISSUE TITLE
[bug] repeat自定义组件无法使用mixins中的方法

### ISSUE THREAD

**Issue by excaliburhan** [Tencent/wepy#946]
## Description

repeat自定义组件无法使用mixins中的方法

## Environment

  * wepy-cli version: [1.7.0]
  * wepy version: [1.7.0]
  
## Reproduce

repeat自定义组件，自定义组件定义了`tap`事件，使用`@tap.user="someMethod"`调用mixins种的method方法报错，但是单个引入，使用`@tap.user="someMethod"`功能正常。

**Comment by excaliburhan** [comment]
更正一下，只要是自定义组件的事件，比如`@tap.user="someMethod"`都会报错

**Comment by cuijiemmx** [comment]
@excaliburhan 我也用到自定义组件事件，并没有一用到就报错，建议把相关代码和错误信息发上来便于debug

**Comment by xty1992a** [comment]
混合实例和组件实例是不同的，混合里的methods跟组件的methods是不同的对象，有个hack的方法是，混合里你在constructor时把混合对象的引用保存在this上，（this.self=this）然后在onload阶段将slef（混合实例）上的methods内的方法全部复制到this（组件实例）上，注意bind(this)(this.foo=this.self.methods.foo.bind(this))
