### ISSUE TITLE
使用wx:for动态渲染子组件，子组件收到传入的props为undefined

### ISSUE THREAD

**Issue by brandonhulala** [Tencent/wepy#951]
## Description

如题~

## Relevant Code / Logs

  ```
<!--父组件-->
 <block wx:for="{{lists}}" wx:key="index" wx:for-index="index" wx:for-item="item">
	<List :itemInfo.sync="item" />
</block>	
data = {
	lists: []
}
components = {
	list: List
}
onLoad(){
	this.reqList();
}
reqList(){
	return wepy.request({
		...
	}).then((res) => {
		this.lists = res.data.data.list;

		this.$apply();
	});
}

// 子组件
onLoad(){
	console.log(this.itemInfo); // 打印出来为undefined
}
  ```

**Comment by brandonhulala** [comment]
补充一下，子组件中已经添加了props: { itemInfo: {} }

**Comment by zhenghongzhi** [comment]
当需要循环渲染WePY组件时(类似于通过wx:for循环渲染原生的wxml标签)，必须使用WePY定义的辅助标签<repeat>
https://tencent.github.io/wepy/document.html#/?id=%e7%bb%84%e4%bb%b6%e7%9a%84%e5%be%aa%e7%8e%af%e6%b8%b2%e6%9f%93

**Comment by brandonhulala** [comment]
楼上老哥，就是因为repeat标签有问题，我才改用的wx:for，你可以去看看issue里关于repeat的坑，多得想X人

**Comment by cuijiemmx** [comment]
@brandonhulala 自定义组件嵌套不用repeat props传不进去的，所以还是得用repeat，在repeat的子组件中避免使用computed, data这些带bug的东西，不用repeat想都别想...

**Comment by mayako21126** [comment]
可以用小程序自带的自定义组件来实现，如果嫌原生4个页面麻烦，想要用.wepy格式需要欺骗下compile模块。

**Comment by Cecil0o0** [comment]
深坑
