### ISSUE TITLE
wepy-redux将action绑定到methods中不合理

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#956]
如下面代码，定义了一个action creator 'loadMore'用于在onReachBottom()时调用
```
@connect({
  ...
}, {
  loadMore // loadMore是一个action creator，用于在页面到达底部时加载更多内容
})
export default class extends wepy.page {
...
   onReachBottom() {
       this.methods.loadMore(args) // 只能通过this.methods.loadMore调用
   }
...
}
```
翻看了过去的issue，@Gcaufy 说是有意这样设计的，methods是用来响应用户事件的，但是实际情况是，action有时不是通过UI上点击某个按钮（比如示例counter）自动调用的，有时需要手动调用，这种情况也不少，比如上文中的onReachBottom中调用，再比如有时需要根据api的调用是否成功决定调用哪个action，还有的情况下调用的时候需要动态传入参数，这些情况下，action不是通过UI的交互事件自动触发的，所以将action放在methods里不合理（跟据@Gcaufy的说法methods是用来处理UI交互事件的）

另外，在我自己的程序中，绝大部分情况因为要传入动态参数都是人肉通过this.methods.xxx调用的，每次写this.methods感觉也挺烦锁

综上两点，是否可以将action直接放到this下，通过this.loadMore调用？，对于UI事件的处理，仍然使用通常的方式，在methods中由用户定义事件处理函数，在处理函数内部再人肉this.loadMore，虽然这样貌似麻烦点，但其实更接近通常方式更容易理解。

**Comment by Gcaufy** [comment]
嗯嗯，在使用过程当中我也发现在这个问题。
但目前来说，1.7的版本中，不会去做大的调整，在2.x的设计中会重新处理这一部分问题。

**Comment by ystarlongzi** [comment]
@Gcaufy 
wepy-redux 接口思路是借鉴 react-redux 嘛？如果是这样的话，那能否：
1. connect 接收参数和 react-redux 保持一致，允许接收函数。（不同类型项目切换开发时，思路可以保持一致 😄😄）
2. this 上新增 `props` 属性，将 action 挂到 this.props ? 感觉这种风格有和 react 接近了，不知道 vue 是怎么处理的

**Comment by ystarlongzi** [comment]
@dolymood

**Comment by wanwusangzhi1992** [comment]
mixins中是否也能connect到methods或者处理好自动调用呢?

**Comment by cuijiemmx** [comment]
@wanwusangzhi1992 ，这个会有问题，原因是state是绑定为computed属性的，而mixins不支持computed

**Comment by cuijiemmx** [comment]
@wanwusangzhi1992 我提交了一个PR：https://github.com/Tencent/wepy/pull/1041
可以支持connect到mixin，满足你的需求

**Comment by guoooofu** [comment]
今天遇到这个问题了，看了下源码才弄明白，想来发个 issue，发现已经有了。太 nice 了
