### ISSUE TITLE
[BUG]onPageScroll会阻碍UI的更新

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#957]
有如下界面，Page拉到底部时触发onReachBottom，进而加载更多

![snap](https://user-images.githubusercontent.com/3148003/36338813-94e32e72-13f3-11e8-8aad-9914f4d7f24b.jpg)

目前发现的问题是，加载更多的数据早已拿到，但页面直到2秒后才更新（延迟值每次会有差异，不过延迟很明显）
如果在页面到底部加载更多时不停地向上撸列表，列表界面永远不更新直到停止撸了之后过几秒才更新（请注意后续撸的过程中并没有任何网络请求以及数据更新操作），列表页面也并没有定义onPageScroll

暂时解决方案是，编辑node_modules/wepy/lib/base.js，把onScrollPage去掉，如下图
<img width="851" alt="screen shot 2018-02-17 at 3 08 40 pm" src="https://user-images.githubusercontent.com/3148003/36338873-9121a83a-13f4-11e8-857b-74f94ed6948d.png">
这样以后加载更多的数据拿到后ui能立马更新了，不停的撸也不会阻止UI及时更新
另外目前页面滑动时会产生海量的onPageScroll日志在Log中，影响到真正关注的内容，有没有办法优化下这个行为，比如页面未定义onPageScroll时，就不要打印这些日志了

PS：**需要在真机上调试**，模拟器中即便按我说的改了也会有延迟，可能跟别人提的这个问题相关
https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=60d2ad000ebe17da82e338caf4feb193

**Comment by cuijiemmx** [comment]
@Gcaufy 看了下代码，每次onPageScroll时，框架会调用page.$apply()进行脏数据检查， 由于页面下滑onPageScroll是不断产生的，相应的page.$apply()也会不停地进行，阻碍了ui的及时更新
在图示代码中加入了对onPageScroll的检测，是则不自动调用$apply，如果期望保留自动的方式，可以采用类似loadash中的_debounce或者_.throttle方法去抖
<img width="483" alt="screen shot 2018-02-17 at 5 27 46 pm" src="https://user-images.githubusercontent.com/3148003/36339780-e7c1c6c6-1407-11e8-8b49-9077cc17edcc.png">

**Comment by wells1013** [comment]
+1 关注中

**Comment by Gcaufy** [comment]
@cuijiemmx 与我猜测的原因一样，但是需要具体测试一下

**Comment by ymqq** [comment]
+1 关注中

**Comment by cuijiemmx** [comment]
@Gcaufy @ymqq @wells1013 提交了一个pull request
