### ISSUE TITLE
使用该框架建议如何监听路由变化

### ISSUE THREAD

**Issue by yangbin1994** [Tencent/wepy#958]
目前能想到的方法是利用 intercept 对原生路由切换相关的 API 进行拦截；或者对 Page 的生命周期进行拦截。
以上2种方法需要自己定义一个 history 对象，不晓得有没有现成的。
另外针对第二种生命周期拦截的方式暂时没有找到合适的方法来实现。

**Comment by Gcaufy** [comment]
onRoute

**Comment by bigmeow** [comment]
@Gcaufy  但是onRoute是要在每一个页面里写，而不是有一个统一的入口写，在app.wpy里写没有效果

**Comment by bigmeow** [comment]
刚想到一个法子，自己写一个class做为基类：
```javascript
import wepy from 'wepy'
export default class BasePage extends wepy.page {
  onRoute () {
    console.log('Basepage路由跳转', arguments)
  }
}

```


然后 页面 文件，以前是继承wepy.page:
```javascript
export default class Login extends wepy.page {
}
```
现在改成继承基类BasePage
```javascript
export default class Login extends BasePage {
}
```

这样实现了统一调用，测试的确可以 
不过不知道是否会对编译有什么隐患？
@Gcaufy

**Comment by Gcaufy** [comment]
@bigmeow  可以这么做。

**Comment by cuijiemmx** [comment]
@bigmeow 可以用mixin啊
