### ISSUE TITLE
引入redux-saga报错

### ISSUE THREAD

**Issue by yangbin1994** [Tencent/wepy#959]
```js
import { call, put, takeEvery, takeLatest } from "redux-saga/lib/effects";
```

 ```console
Maximum call stack size exceeded
```

**Comment by cuijiemmx** [comment]
同样遇到此问题

**Comment by shenqihui** [comment]
我也遇到了。

**Comment by shenqihui** [comment]
#521  这个 issue 有临时解决方案。

**Comment by kala888** [comment]
@yangbin1994  能否提供一下wepy如何集成和使用saga的例子啊

**Comment by cuijiemmx** [comment]
@kala888 https://github.com/redux-saga/redux-saga/tree/master/dist，这下面的两个js任选一个copy到项目中引用就行了

**Comment by Gcaufy** [comment]
使用dist的文件

**Comment by 2534290808** [comment]
我也遇到这个问题

**Comment by kala888** [comment]
@2534290808 
![image](https://user-images.githubusercontent.com/1215976/38551011-a5f27dc4-3cea-11e8-878a-3948b3545fdd.png)

**Comment by YufJi** [comment]
import createSagaMiddleware from 'redux-saga/dist/redux-saga'；
import { effects } from 'redux-saga/dist/redux-saga'；
const { call, put, takeLatest } = effects；

**Comment by YufJi** [comment]
没问题的demo
