### ISSUE TITLE
wepy-cli升级1.7.0以后，不会往标签添加hash class导致样式无法应用到标签

### ISSUE THREAD

**Issue by IveChen** [Tencent/wepy#963]
以下是1.6.0的编译，显示image标签上有一个class
![image](https://user-images.githubusercontent.com/1736282/36524633-9e917194-17e1-11e8-9269-318080ffff24.png)
以下是1.7.0的编译，显示image的标签上的class被去掉了
![image](https://user-images.githubusercontent.com/1736282/36524659-becc6b62-17e1-11e8-86c7-71fd4ef677ec.png)

但是在生成的wxss文件中,image标签是带有class的。
![image](https://user-images.githubusercontent.com/1736282/36524719-067109fa-17e2-11e8-9bf1-b354430e5479.png)

想知道这个变动是正常变动还是bug？？

**Comment by Gcaufy** [comment]
https://github.com/Tencent/wepy/commit/acc643e9ba01310d8cc71d452051408907795f42

这是1.7的一个bug, 对于无class属性的节点不会添加hash

所以暂时你可以参考上面的改动去修改wepy-cli的代码，或者给节点加一个class属性

**Comment by IveChen** [comment]
@Gcaufy 可有修复计划？？如果有修复计划我就先暂时用着1.6.0先，不然要修改的地方有点多。。。

**Comment by Gcaufy** [comment]
暂不会因为这个问题发个正式版本，但过几天我可以先弄个alpha版本。

**Comment by AdamWei** [comment]
一个组件里边有很多的无class属性的节点，都需要挨个加class吗？这岂不是很坑

**Comment by xing00** [comment]
我遇到同样的问题，我把wepy-cli降到1.6了

**Comment by Gcaufy** [comment]
@xing00 
可以升级到1.7.1

**Comment by xing00** [comment]
@Gcaufy 好的，谢谢
