### ISSUE TITLE
无法将app.wepy的config中的pages抽取出来

### ISSUE THREAD

**Issue by whudongyang** [Tencent/wepy#964]
wepy将小程序原生的app.json合并到app.wepy中,  这样原意是好的, 但是随着config.pages的页面数量越来越多,  导致app.wepy这个页面越发的臃肿, 现在有将pages里配置的页面提取出来的想法, 但是没有好的方法.

**Comment by Gcaufy** [comment]
建议很好，感谢，1.7的版本中不会再优化这里了。下一个大版本中会考虑进这个问题。。
