### ISSUE TITLE
[BUG]wepy-redux @connect中this指向错误

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#976]
@Gcaufy 有如下的自定义组件，在获取events时打印this，发现this不稳定，有的时候指向component实例，有的时候指向mappedState方法，期望this能稳定指向connect的component实例以便在计算events时能访问到component中的props
```
@connect({
  events(state) {
     console.log(this) // 期望this指向connect的component实例，方便访问实例中的props
     return state.events[this.namespace]
  }
}, {})
export default class extends wepy.component {
    props = {
        namespace: String
    }
}
```
问题出现在wepy-redux源码src/connect/index.js中，解决方法是将
`const newV = states[k]()`
改为
`const newV = states[k].call(this)`
<img width="290" alt="screen shot 2018-02-24 at 10 15 36 pm" src="https://user-images.githubusercontent.com/3148003/36631289-4327d0b6-19b0-11e8-9fc7-c3c886fe4a9f.png">

**Comment by catwarrior** [comment]
@cuijiemmx 为什么不直接提一个pullrequest呢？

**Comment by cuijiemmx** [comment]
@catwarrior 你说得对，我学着弄一下
