### ISSUE TITLE
导入alias后的组件,比如A:B, 实际起作用的却是A的template+B的script

### ISSUE THREAD

**Issue by rchunping** [Tencent/wepy#977]
复现：

```bash
wepy init standard  testproj
```

其中 package.json 中默认是这样的

```js
  "wepy": {
    "module-a": false,
    "./src/components/list": "./src/components/wepy-list.wpy"
  },
```

wepy build 后的结果是，
模板使用了list.wpy中的，但是事件响应之类的确是 wepy-list.wpy中的

**Comment by rchunping** [comment]
补充：
如果将 list.wpy文件删掉重新 build
那么 template 和 script 就正确对应了。

**Comment by wang-fu** [comment]
是有这个问题，最早不清楚 demo 的package.json里设置了 alias，调了挺久的。事件响应和模板不一致~

**Comment by mangoooooo** [comment]
同样有疑问，不是很懂这一块，
事件响应之类的是 wepy-list.wpy中的，为啥this.$name 打印出来的是list

**Comment by rchunping** [comment]
@mangoooooo this.$name 应该是 
components = {
   'list': comList // 这里的 'list'
}

**Comment by mangoooooo** [comment]
@rchunping 原来如此😄，感谢感谢
