### ISSUE TITLE
[Proposal]建议将wepy的仓库拆分开来单独管理

### ISSUE THREAD

**Issue by cuijiemmx** [Tencent/wepy#980]
<img width="295" alt="screen shot 2018-02-25 at 5 35 38 pm" src="https://user-images.githubusercontent.com/3148003/36639975-5362844c-1a52-11e8-906f-437c5403c6d3.png">
当前wepy的辅助库和wepy共享的同一个代码仓库，而这些辅助功能的引入又是通过类似npm i wepy-redux这种方式单独引入的，它们在逻辑上是独立的，拆开来便于单独管理，几点原因都是实际中遇到的：

1. 比如修复了wepy-redux中的一个BUG，马上就能publish一个新的wepy-redux版本，而不是publish一个新的wepy版本
如果像当前这样集中管理遇到这种情况就很纠结了，为了一个wepy-redux的bug发布新的wepy感觉不值得，可是不发布新的wepy悄悄发布一个新的wepy-redux package的话谁又知道？如果屏着等到下个wepy版本一齐发布就很慢了。

2. 我发现了一个wepy-redux中的bug，很自然的想到去把wepy-redux源码checkout下来修复，结果找半天没找到，最后发现在wepy仓库中...，这下傻了为了wepy-redux要把整个wepy checkout下来，这就跟为了lodash中的一个assign方法把整个lodash引入一样，不应该为了一粒芝麻引入整个世界嘛

**Comment by Gcaufy** [comment]
每个包都是可以单独发布单独release的。

使用了lerna去管理包，建议参考一下这个：
https://github.com/lerna/lerna
https://github.com/babel/babel/tree/master/packages

**Comment by cuijiemmx** [comment]
@Gcaufy 好的谢谢
