### ISSUE TITLE
WePY的readme文档表述错误

### ISSUE THREAD

**Issue by fengxinming** [Tencent/wepy#983]
## Description

  在WePY的readme文档中，特性那个章节里面的“Styus”应改成“Stylus”

## Environment

  无
  
## Reproduce

  打开链接[**“https://github.com/Tencent/wepy”**](https://github.com/Tencent/wepy)后可看到

### Observed Results

  [实际表现]
  
  支持多种编译器，Less/Sass/Styus、Babel/Typescript、Pug
  
### Expected Results

  [期望表现]
  
  支持多种编译器，Less/Sass/Stylus、Babel/Typescript、Pug
  

## Relevant Code / Logs

  ```
  // TODO(you): code or logs ohere to reproduce the problem
  ```

**Comment by Gcaufy** [comment]
欢迎pr一下
