### ISSUE TITLE
base.js 里多了两行代码导致编译之后报错

### ISSUE THREAD

**Issue by JourneyL** [Tencent/wepy#986]
编译错误 结果发现 base.js里比同事多了几行代码
APP_EVENT = APP_EVENT.concat(appConfig.appEvents || []);
PAGE_EVENT = PAGE_EVENT.concat(appConfig.pageEvents || []);
结果就导致 编译出来直接报错 appEvents not defined
这两行注释就没错了
1.5.8

**Comment by cuijiemmx** [comment]
@JourneyL 怎么会出现package版本相同代码不同的情况？要不要重新装一下这个package

**Comment by JourneyL** [comment]
@cuijiemmx   重装过好几次了啊。。  不太清楚是什么原理 npm 4.0.5

**Comment by rodson** [comment]
我这边用1.7.0版本会有这个报错，appConfig是undefined。退回1.6.0就没问题

**Comment by rodson** [comment]
@JourneyL wepy-cli和wepy都升级到1.7.0后就没问题了

**Comment by JourneyL** [comment]
@rodson 现在换版本有好多东西要改 成本大
