### ISSUE TITLE
repeat循环组件时无法自定义变量名导致嵌套循环中对象引用问题

### ISSUE THREAD

**Issue by dlmys** [Tencent/wepy#990]
如下pug代码，首先通过repeat循环questionsType组件，生成了临时变量item和index。
view(slot="body")做为questionsType组件的插槽存在。
第二次repeat循环itemInfo组件时，由于无法自定义产生的临时变量名，又生成了临时变量item和index。
此时在itemInfo组件内部获取item和index的值的时候。获取到的是第一次循环也就是循环questionsType产生的值。
请问有没有自定义变量名的方法或贵团队在这种嵌套循环的地方是怎样避免作用域引用的？谢谢

```javascript
   //- index页面
    repeat(for="{{ questionTypeMap }}", key="index", index="index", item="item")
      questionsType(:typeInfo.sync="item")
        view(slot="body")
          repeat(for="{{ questions[item.name] }}", key="index", index="index", item="item")
            itemInfo(:data.sync="item", :index.sync="index")
            text {{ item }} 
  ```

```javascript
  //- itemInfo组件
  view.item-info
    view.qs-stem {{ item }} {{ index }}  //- 这里获取到的item和index是循环questionsType时产生的值。
  ```

**Comment by Gcaufy** [comment]
1.7.2的版本中支持了原生组件，可以试一下这个版本，解决了wepy组件的一些问题：

安装使用：
```
npm install wepy-cli@1.7.2-alpha1 -g
npm install wepy@1.7.2-alpha1 --save
wepy build --no-cache
```
文档说明：https://github.com/Tencent/wepy/blob/component/docs/md/doc.md#%E7%BB%84%E4%BB%B6
迁移参考：https://github.com/wepyjs/wepy-wechat-demo/commit/5f84a3aed82547d7db4eb816f5c83f5ad35eba65
