### ISSUE TITLE
page无法利用props向子组件传值的情况

### ISSUE THREAD

**Issue by trekerz** [Tencent/wepy#991]
在如下代码中，父页面给ticket子组件传递了5个props变量。在这种有repeat标签的情况下，可以顺利传递props值。
```html
<repeat for="{{ ticketList }}" key="index" index="index" item="ticket">
      <ticket
                :type="ticket.type"
                :num="ticket.num"
                :unit="ticket.unit"
                :detail="ticket.detail"
                :date="ticket.date"
     ></ticket>
</repeat>
```
但是，在如下代码中，子组件检测不到传过去的props值。（其中product是data里的一个对象）
```html
<view class="purchase-ticket">            
     <ticket
                :type="product.banner.type"
                :num="product.banner.num"
                :unit="product.banner.unit"
                :detail="product.banner.detail"
                :date="product.banner.date"
    ></ticket>
</view>
```

**Comment by trekerz** [comment]
貌似在没<repeat>的情况下传递data里的变量时只能传单层数据，不能深入对象内部的属性

**Comment by coolhwm** [comment]
不能使用点操作符，用computed 拆一层出来

**Comment by cuijiemmx** [comment]
@coolhwm repeat配合computed，那酸爽（cao）谁用谁知道（dan）

**Comment by trekerz** [comment]
@cuijiemmx `<repeat>`无法随computed或者watch的改变而动态更新，只能通过触发屏幕事件（比如滚动）来动态更新， @coolhwm 有没有什么方案？

**Comment by cuijiemmx** [comment]
@trekerz 我记得不管有没有repeat，使用:prop.sync="xxx"时，xxx都只能是单层的，另外如果你repeat的子组件中用了computed的话，嘿嘿...

**Comment by trekerz** [comment]
@cuijiemmx 我用repeat的时候可以两层啊（用的是repeat的item而不是直接data里的对象）
```html
<repeat for="{{ ticketList }}" key="index" index="index" item="ticket">
      <ticket
                :type="ticket.type"
                :num="ticket.num"
                :unit="ticket.unit"
                :detail="ticket.detail"
                :date="ticket.date"
     ></ticket>
</repeat>
```

computed暂时没用在repeat里，不知道会有什么奇怪的事情发生 :·P

**Comment by cuijiemmx** [comment]
@trekerz 你用的哪个版本的wepy?

**Comment by cuijiemmx** [comment]
@trekerz 明白你的意思了，你的repeat用法我一般会直接写成
<repeat for="{{ ticketList }}" key="index" item="ticket">
       <ticket :data.sync="ticket">
</repeat>

**Comment by shihanjun19** [comment]
```
遇到了同样的问题, 不能用 . 号取第二层数据好蛋疼啊
<view  :static="static.flag"/>

data = {
   static: {
      flag: true
   }
}
```

**Comment by Gcaufy** [comment]
1.7.2的版本中支持了原生组件，大家可以试一下这个版本，可以使用表达式传值：

安装使用：
```
npm install wepy-cli@1.7.2-alpha1 -g
npm install wepy@1.7.2-alpha1 --save
wepy build --no-cache
```
文档说明：https://github.com/Tencent/wepy/blob/component/docs/md/doc.md#%E7%BB%84%E4%BB%B6
迁移参考：https://github.com/wepyjs/wepy-wechat-demo/commit/5f84a3aed82547d7db4eb816f5c83f5ad35eba65

**Comment by cuijiemmx** [comment]
@Gcaufy 这么牛B版本号应该至少1.8.0吧.

**Comment by Gcaufy** [comment]
@cuijiemmx 等功能稳定了，版本号再说。

**Comment by maimake** [comment]
@Gcaufy 1.7.2-alpha1版本传值是可以，但是在组件里无法通过this.xxx读到传入的值

**Comment by jackiecookie** [comment]
终于找到组织了,应该是遇到了相同的问题。我的code
` <repeat for="{{page.list}}" key="index" index="index" item="item">
        <Item :item.sync="item"></Item>
      </repeat>`
Item
`<view>
        {{item.user.avatar}}
        <Avatar src="{{item.user.avatar}}" class="avatar {{item.user.avatar}}" ></Avatar>
      </view>`

试了.sync 也不行,查了issues说是对象属性传值不行,改成不是对象属性也不行也不知道是不是我写法上面的问题,**这么常用的写法文档里能不能体现一下**,虽然这个issue已经close了，还是提在这里了，写了两天的wepy就遇到了这么多坑，真的心很累啊,如果有时间的话希望能贡献一下自己的力量，因为wepy真的是个挺好的项目。以上

**Comment by WangShuXian6** [comment]
> @Gcaufy 1.7.2-alpha1版本传值是可以，但是在组件里无法通过this.xxx读到传入的值

可以通过这样读取：
```vue
this.props
```

**Comment by msdog** [comment]
辣鸡框架

**Comment by njdsnake** [comment]
坑了一下午  5小时
