### ISSUE TITLE
:name props传值不支持表达式

### ISSUE THREAD

**Issue by yangbin1994** [Tencent/wepy#999]
```js
 <searchbar :static="static"/>

data = {
  static: true
}
```
=>
```js
 <searchbar :static="true"/>
```

**Comment by shihanjun19** [comment]
好像是的,我也遇到了同样的问题, 而且还有个问题.  下面这种也不行
`<searchbar :static="static.flag"/>

data = {
  static: {
     flag:  true
  }
}`

**Comment by cuijiemmx** [comment]
这是个已知问题，还没有解决

**Comment by Gcaufy** [comment]
1.7.2的版本中支持了原生组件，可以试一下这个版本，props传递表达式也可以解决：

安装使用：
```
npm install wepy-cli@1.7.2-alpha1 -g
npm install wepy@1.7.2-alpha1 --save
wepy build --no-cache
```
文档说明：https://github.com/Tencent/wepy/blob/component/docs/md/doc.md#%E7%BB%84%E4%BB%B6
迁移参考：https://github.com/wepyjs/wepy-wechat-demo/commit/5f84a3aed82547d7db4eb816f5c83f5ad35eba65

**Comment by cuijiemmx** [comment]
@Gcaufy 封装自定义组件时，在created中申请了资源在何处释放？有没有相应的回调？

**Comment by someoneiscoding** [comment]
@Gcaufy 在官方demo中有个counter组件，，现在遇到一个问题：
新建一个goodlist组件，在这个组件中import了counter组件，counter组件中props的num直接使用了goodlist组件中props中的gl对象，代码如下
```
// goodlist组件中引用counter组件的代码
<slot name="glCounter">
      <counter :num="gl.num" @index-emit.user="counterEmit"></counter>
</slot>

props = {
      gl: Object
}
```
在页面中使用goodlist组件时，组件中其他数据正常，但商品数量num还是counter组件中的默认值。。另外，在增加某项商品的数量时，其余商品数量也增加了。。
这个问题该怎么解决？？还请给思路，，谢过
